### ISSUE TITLE
OpenAI remaining requests / tokens and requests / tokens consumed are the same

### ISSUE THREAD

**Issue by dmvieira** [DataDog/dd-trace-py#10143]
### Summary of problem
[OpenAI default metrics](https://ddtrace.readthedocs.io/en/stable/integrations.html#openai) `openai.ratelimit.remaining.requests` and `openai.ratelimit.requests` are the same. Similar to `openai.ratelimit.tokens` and `openai.ratelimit.remaining.tokens`.

![Captura de Tela 2024-08-08 às 14 34 51](https://github.com/user-attachments/assets/8a5c8c14-46e2-4d39-832f-75c5f3555c26)

### Which version of dd-trace-py are you using?
2.10.3

### Which version of pip are you using?
24.0 python 3.11

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
aiobotocore==2.13.0
aiohttp==3.9.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
alembic==1.13.2
amqp==5.2.0
annotated-types==0.7.0
antlr4-python3-runtime==4.9.3
anyio==4.4.0
appdirs==1.4.4
asyncssh==2.14.2
atpublic==4.1.0
attrs==24.2.0
backoff==2.2.1
billiard==4.2.0
boilerpy3==1.0.7
boto3==1.34.106
botocore==1.34.106
bytecode==0.15.1
cachetools==5.4.0
cattrs==23.2.3
celery==5.4.0
certifi==2024.7.4
cffi==1.17.0
charset-normalizer==3.3.2
click==8.1.7
click-didyoumean==0.3.1
click-plugins==1.1.1
click-repl==0.3.0
cloudpickle==3.0.0
colorama==0.4.6
coloredlogs==15.0.1
configobj==5.0.8
cryptography==43.0.0
db-dtypes==1.2.0
ddsketch==3.0.1
ddtrace==2.10.3
Deprecated==1.2.14
dictdiffer==0.9.0
diskcache==5.6.3
distro==1.9.0
dnspython==2.6.1
dpath==2.2.0
dulwich==0.22.1
dvc==3.30.3
dvc-data==2.22.6
dvc-http==2.32.0
dvc-objects==1.4.9
dvc-render==0.7.0
dvc-s3==2.23.0
dvc-studio-client==0.20.0
dvc-task==0.4.0
email_validator==2.2.0
entrypoints==0.4
envier==0.5.2
fastapi==0.109.2
filelock==3.15.1
flatten-dict==0.4.2
flufl.lock==7.1.1
freezegun==1.4.0
frozenlist==1.4.1
fsspec==2024.6.0
funcy==2.0
gitdb==4.0.11
GitPython==3.1.43
google-api-core==2.19.1
google-auth==2.33.0
google-cloud-bigquery==3.24.0
google-cloud-core==2.4.1
google-crc32c==1.5.0
google-resumable-media==2.7.2
googleapis-common-protos==1.63.2
grandalf==0.8
griffe==0.36.9
grpcio==1.65.4
grpcio-status==1.62.3
gto==1.6.2
guardrails-ai==0.4.5
guardrails-api-client==0.2.1
gunicorn==22.0.0
h11==0.14.0
haystack-ai==2.3.1
haystack-bm25==1.0.2
haystack-experimental==0.1.1
httpcore==1.0.5
httptools==0.6.1
httpx==0.27.0
humanfriendly==10.0
hydra-core==1.3.2
idna==3.7
importlib_metadata==8.0.0
iniconfig==2.0.0
iterative-telemetry==0.0.8
itsdangerous==2.2.0
Jinja2==3.1.4
jmespath==1.0.1
joblib==1.4.2
jsonpatch==1.33
jsonpointer==3.0.0
jwt==1.3.1
kombu==5.3.7
langchain-core==0.2.29
langsmith==0.1.98
lazy-imports==0.3.1
-e git+ssh://git@github.com/pagarme/lucy-engine.git@7d81b49ed8818c4ae479bff5ad3af131b85b5a2a#egg=lucy_engine
lxml==4.9.4
Mako==1.3.5
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mdurl==0.1.2
monotonic==1.6
more-itertools==10.4.0
multidict==6.0.5
networkx==3.3
nltk==3.8.1
numpy==1.26.4
omegaconf==2.3.0
openai==1.34.0
opentelemetry-api==1.26.0
opentelemetry-exporter-otlp==1.26.0
opentelemetry-exporter-otlp-proto-common==1.26.0
opentelemetry-exporter-otlp-proto-grpc==1.26.0
opentelemetry-exporter-otlp-proto-http==1.26.0
opentelemetry-proto==1.26.0
opentelemetry-sdk==1.26.0
opentelemetry-semantic-conventions==0.47b0
orjson==3.9.15
packaging==24.1
pandas==2.2.2
pathspec==0.12.1
pgvector==0.2.5
platformdirs==3.11.0
pluggy==1.5.0
posthog==3.5.0
prompt_toolkit==3.0.47
proto-plus==1.24.0
protobuf==4.25.4
psutil==5.9.8
psycopg==3.1.20
psycopg-binary==3.1.20
psycopg-c==3.1.20
psycopg-pool==3.2.2
py-cpuinfo==9.0.0
pyarrow==16.1.0
pyasn1==0.6.0
pyasn1_modules==0.4.0
pycparser==2.22
pydantic==2.7.4
pydantic-extra-types==2.9.0
pydantic-settings==2.4.0
pydantic_core==2.18.4
pydash==7.0.7
pydot==2.0.0
pygit2==1.15.0
Pygments==2.18.0
pygtrie==2.5.0
pyparsing==3.1.2
pytest==7.4.4
pytest-asyncio==0.23.7
pytest-benchmark==4.0.0
pytest-mock==3.12.0
pytest-order==1.1.0
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-json-logger==2.0.7
python-multipart==0.0.9
pytz==2024.1
PyYAML==6.0.2
regex==2023.12.25
requests==2.32.3
responses==0.24.1
rich==13.7.1
rsa==4.9
rstr==3.2.2
ruamel.yaml==0.18.6
ruamel.yaml.clib==0.2.8
ruff==0.3.7
s3fs==2024.6.0
s3transfer==0.10.1
scikit-learn==1.5.1
scipy==1.13.1
scmrepo==1.6.0
semver==3.0.2
shellingham==1.5.4
shortuuid==1.0.13
shtab==1.7.1
six==1.16.0
smmap==5.0.1
sniffio==1.3.1
SQLAlchemy==2.0.32
sqlmodel==0.0.19
sqlparse==0.5.0
sqltrie==0.11.0
starlette==0.36.3
starlette-context==0.3.6
tabulate==0.9.0
tenacity==8.3.0
threadpoolctl==3.5.0
tiktoken==0.5.2
tomlkit==0.12.5
tqdm==4.66.5
typer==0.9.4
typing_extensions==4.12.2
tzdata==2024.1
ujson==5.10.0
urllib3==2.2.2
uvicorn==0.30.5
uvloop==0.19.0
vine==5.1.0
voluptuous==0.14.2
watchfiles==0.23.0
wcwidth==0.2.13
websockets==12.0
Werkzeug==3.0.3
wrapt==1.16.0
xmltodict==0.13.0
yarl==1.9.4
zc.lockfile==3.0.post1
zipp==3.19.2
</details>

### How can we reproduce your problem?

We're running application with `ddtrace-run gunicorn api:app`. Just call OpenAI directly on this app. We're using datadog for monitoring.

### What is the result that you get?

just see in datadog metrics explorer. Same values from:
- `openai.ratelimit.remaining.requests` and `openai.ratelimit.requests`
- `openai.ratelimit.tokens` and `openai.ratelimit.remaining.tokens`

### What is the result that you expected?

Different values from them:
- `openai.ratelimit.remaining.requests` should be the complement of `openai.ratelimit.requests` and total requests used
- `openai.ratelimit.remaining.tokens` should be the complement of `openai.ratelimit.tokens` and total tokens used

**Comment by emmettbutler** [comment]
Thanks for letting us know about this, @dmvieira 

cc @Yun-Kim

**Comment by lievan** [comment]
Hi @dmvieira, thanks for raising this. Is the volume of openai requests your app is making is enough to cause a visual difference between `openai.ratelimit.requests` and `openai.ratelimit.remaining.requests`? These metric values are gauged every time an openai request is made and may have similar values if the openai request volume is low.

For the following two queries (exclude the 'by model' part of your query):

Query 1: `avg:openai.ratelimit.remaining.requests{*}` + `sum:openai.api.usage.n_requests{*}`
Query 2: `avg:openai.ratelimit.requests{*}`

Do the values match?

**Comment by dmvieira** [comment]
No, they don't match... There are a few more values in the second query:

<img width="1334" alt="Captura de Tela 2024-08-19 às 16 59 44" src="https://github.com/user-attachments/assets/9d000591-56ae-480c-9692-859b83fc1640">

but `avg:openai.ratelimit.remaining.requests{*}` is exactly the same as `avg:openai.ratelimit.requests{*}`

**Comment by lievan** [comment]
Hi Diogo,

All our integration does is take rate limit information from the [headers](https://github.com/DataDog/dd-trace-py/blob/3c813d6f0c7a014be833efd14215923cf8ed7422/ddtrace/contrib/internal/openai/patch.py#L337C1-L338C1) and emit it as a gauge metric.

From the graphs, I'm guessing your openai request volume is not high enough to cause a difference in the number being displayed in the line graph (e.g. both show 10.05k, but one may be 10,451 vs 10,500) 

> How can I get exactly what is remainings?

You can try selecting "query value" as your widget visualization, though this will still give you a rounded value
<img width="876" alt="image" src="https://github.com/user-attachments/assets/b5ea1200-dd3d-4928-8f19-99f6514c659a">

**Comment by dmvieira** [comment]
Thank, I will wait more tokens and requests to confirm that!
