### ISSUE TITLE
UnboundLocalError: cannot access local variable 'result' where it is not associated with a value

### ISSUE THREAD

**Issue by miketheman** [DataDog/dd-trace-py#10227]
### Summary of problem
This appears to be very similar to #9548 but the error surfaces in a different spot.

https://github.com/DataDog/dd-trace-py/blob/d47adb6c0b855bdb832ff1b5cb3c3c9484514950/ddtrace/contrib/redis/patch.py#L135-L137

### Which version of dd-trace-py are you using?

2.10.5

### Which version of pip are you using?

24.2

### Which libraries and their versions are you using?

See https://python-software-foundation.sentry.io/share/issue/880caf15ae324071b6830d35dfc937ca/#packages

### How can we reproduce your problem?

🤷 

### What is the result that you get?

https://python-software-foundation.sentry.io/share/issue/880caf15ae324071b6830d35dfc937ca/

### What is the result that you expected?

`UnboundLocalError` not being raised.

**Comment by emmettbutler** [comment]
Thanks for pointing this out, @miketheman. It's fixed in 2.10.6 https://github.com/DataDog/dd-trace-py/commit/504a34725ed8a7f3423df09974dc12e56898659f
