### ISSUE TITLE
LLM observability requires "DD_API_KEY" in the primary container even though datadog agent running as a sidecar has the "DD_API_KEY"

### ISSUE THREAD

**Issue by Gekko0114** [DataDog/dd-trace-py#10286]
### Summary of problem
I've started using the LLM observability function and have a question.  
LLM observability requires the DD_API_KEY in the primary container, even though the Datadog agent running as a sidecar already has the DD_API_KEY. I find this strange—is this intentional?
https://docs.datadoghq.com/llm_observability/setup/sdk/

### Which version of dd-trace-py are you using?
ddtrace = "^2.9.1"

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
  
</details>

### How can we reproduce your problem?
Using ECS and having a datadog agent sidecar.

**Comment by emmettbutler** [comment]
cc @Yun-Kim

**Comment by Yun-Kim** [comment]
Hi @Gekko0114, can you try upgrading `ddtrace` to the latest `ddtrace==2.11` version? LLM Observability originally required a `DD_API_KEY` in the primary container, but we introduced an agent proxy mode that does not require the API key set in the primary container in 2.11.

Please let us know if that doesn't resolve your issue, thanks!

**Comment by Gekko0114** [comment]
Thanks @Yun-Kim I will try it :)

**Comment by Yun-Kim** [comment]
Hi @Gekko0114, I'll close this issue for now but if that did not resolve your issue, feel free to reopen. Thanks!
