### ISSUE TITLE
Vendored msgpack (and other libs) causing issues with installed libs

### ISSUE THREAD

**Issue by JBKahn** [DataDog/dd-trace-py#1030]
Importing dtrace before importing msgpack causes issues with serializing custom types.

For example, if you run this code as is then it runs perfectly fine in a shell.
If you uncomment the import then it causes the error below.

The only dependancies to run this are msgpack and this library

```python
    # from ddtrace.vendor import msgpack as ddmsgpack
    import msgpack
    import enum
    from importlib import import_module

    def default(obj):
        if issubclass(type(obj), enum.Enum):
            components = (obj.__module__, obj.__class__.__name__, obj.value)
            return msgpack.ExtType(42, msgpack.packb(components, use_bin_type=True))
        raise TypeError("Unknown type: %r" % (obj,))

    def ext_hook(code, data):
        if code == 42:
            module, class_name, value = msgpack.unpackb(data, raw=False)
            if isinstance(module, bytes):
                module = module.decode()
            if isinstance(class_name, bytes):
                class_name = class_name.decode()
            obj = getattr(import_module(module), class_name)(value)
            return obj
        return msgpack.ExtType(code, data)


    class Garbo(enum.Enum):
        thing = 1


    data = {'a': Garbo.thing}
    packed = msgpack.packb(data, strict_types=True, default=default, use_bin_type=True)
    unpacked = msgpack.unpackb(packed, ext_hook=ext_hook, raw=False)
```

uncomment that line to cause the error

```python
TypeError                                 Traceback (most recent call last)
<ipython-input-1-b3fab8564c6e> in <module>
     26
     27 data = {'a': Garbo.thing}
---> 28 packed = msgpack.packb(data, strict_types=True, default=default, use_bin_type=True)

/usr/local/lib/python3.7/site-packages/msgpack/__init__.py in packb(o, **kwargs)
     44     See :class:`Packer` for options.
     45     """
---> 46     return Packer(**kwargs).pack(o)
     47
     48

msgpack/_packer.pyx in msgpack._cmsgpack.Packer.pack()

msgpack/_packer.pyx in msgpack._cmsgpack.Packer.pack()

msgpack/_packer.pyx in msgpack._cmsgpack.Packer.pack()

msgpack/_packer.pyx in msgpack._cmsgpack.Packer._pack()

msgpack/_packer.pyx in msgpack._cmsgpack.Packer._pack()

TypeError: can not serialize 'ExtType' object

```

**Comment by brettlangdon** [comment]
@JBKahn thanks for sharing, this is definitely weird. I would not have expected our vendored `msgpack` to cause any issues.

Just for context, the way we do vendoring of `msgpack`, we have modified the code so it is only available as `ddtrace.vendor.msgpack`, this even includes the built c-extension. We do this instead of other packages which will add hooks to the import system to override where a package is loaded from, instead we went for the good ol' approach of modifying the vendored code to work as a sub-module directly.

We are vendoring version `0.6.1`.


There are a few things you could try.

1. What happens if you try without `ddtrace` installed? (or not imported)
  a. Should be a clear indicator if the presence of our `msgpack` is causing an issue or not.
2. What happens if you set `MSGPACK_PUREPYTHON` environment variable (just needs to be set, value doesn't matter)
  a. This will force `msgpack` to use the pure python version instead of the c-extension.
  b. Maybe there is an issue with your's or our c-extension for `msgpack`
3. What happens if you replace `import msgpack` with `from ddtrace.vendor import msgpack`
  a. I am curious if we explicitly use our version of `msgpack` if the issue occurs, or if it is a conflict between your version and our vendored version?

**Comment by JBKahn** [comment]
I have tried a few of those:

1. It worked without it installed and without it imported.
2. It works with the pure python version. 
3. I'll try that now.

**Comment by brettlangdon** [comment]
Interesting.

What version of `ddtrace` are you using?

With `0.28.0` we just started to ship Wheels to PyPI, makes me wonder if maybe there is an issue with the compiled c-extension in the wheels we shipped?

**Comment by JBKahn** [comment]
```python
In [1]: from ddtrace.vendor import msgpack

In [2]: import enum
   ...: from importlib import import_module
   ...:
   ...: def default(obj):
   ...:     if issubclass(type(obj), enum.Enum):
   ...:         components = (obj.__module__, obj.__class__.__name__, obj.value)
   ...:         return msgpack.ExtType(42, msgpack.packb(components, use_bin_type=True))
   ...:     raise TypeError("Unknown type: %r" % (obj,))
   ...:
   ...: def ext_hook(code, data):
   ...:     if code == 42:
   ...:         module, class_name, value = msgpack.unpackb(data, raw=False)
   ...:         if isinstance(module, bytes):
   ...:             module = module.decode()
   ...:         if isinstance(class_name, bytes):
   ...:             class_name = class_name.decode()
   ...:         obj = getattr(import_module(module), class_name)(value)
   ...:         return obj
   ...:     return msgpack.ExtType(code, data)
   ...:
   ...:
   ...: class Garbo(enum.Enum):
   ...:     thing = 1
   ...:

In [3]: data = {'a': Garbo.thing}
   ...: packed = msgpack.packb(data, strict_types=True, default=default, use_bin_type=True)

In [4]:

In [4]: packed
Out[4]: b'\x81\xa1a\xc7\x11*\x93\xa8__main__\xa5Garbo\x01'

In [5]: import msgpack

In [6]: data = {'a': Garbo.thing}
   ...: packed = msgpack.packb(data, strict_types=True, default=default, use_bin_type=True)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-43cda1358749> in <module>
      1 data = {'a': Garbo.thing}
----> 2 packed = msgpack.packb(data, strict_types=True, default=default, use_bin_type=True)

/usr/local/lib/python3.7/site-packages/msgpack/__init__.py in packb(o, **kwargs)
     44     See :class:`Packer` for options.
     45     """
---> 46     return Packer(**kwargs).pack(o)
     47
     48

msgpack/_packer.pyx in msgpack._cmsgpack.Packer.pack()

msgpack/_packer.pyx in msgpack._cmsgpack.Packer.pack()

msgpack/_packer.pyx in msgpack._cmsgpack.Packer.pack()

msgpack/_packer.pyx in msgpack._cmsgpack.Packer._pack()

msgpack/_packer.pyx in msgpack._cmsgpack.Packer._pack()

TypeError: can not serialize 'ExtType' object
```

It seems to be whichever one it loads first works.
`msgpack_og.ExtType is msgpack_dd.ExtType` is likely the issue. The c code uses a check on the type and having both a vendored and non-vendored copy is likely somehow causing an issue.

**Comment by brettlangdon** [comment]
Great find! Thanks for checking on this. I'll schedule some time to triage/reproduce on our end and we'll dig into it!

**Comment by JBKahn** [comment]
I'm using `0.28.0` and just calling `ipython` to open a shell.

**Comment by brettlangdon** [comment]
👍 Thanks.

**Comment by JBKahn** [comment]
So here's a script you can use
```python
    # from ddtrace.vendor import msgpack as ddmsgpack
    import msgpack
    import enum
    from importlib import import_module

    def default(obj):
        if issubclass(type(obj), enum.Enum):
            components = (obj.__module__, obj.__class__.__name__, obj.value)
            return msgpack.ExtType(42, msgpack.packb(components, use_bin_type=True))
        raise TypeError("Unknown type: %r" % (obj,))

    def ext_hook(code, data):
        if code == 42:
            module, class_name, value = msgpack.unpackb(data, raw=False)
            if isinstance(module, bytes):
                module = module.decode()
            if isinstance(class_name, bytes):
                class_name = class_name.decode()
            obj = getattr(import_module(module), class_name)(value)
            return obj
        return msgpack.ExtType(code, data)


    class Garbo(enum.Enum):
        thing = 1


    data = {'a': Garbo.thing}
    packed = msgpack.packb(data, strict_types=True, default=default, use_bin_type=True)
```

uncomment that line to cause the error

**Comment by JBKahn** [comment]
Out of curiosity what did you need to change that you needed to vendor it as opposed to just relying on the normal version?

**Comment by brettlangdon** [comment]
Previously we just depended on `msgpack-python`, but then they deprecated that package in favor of just `msgpack` (just a naming change). However, we had some customers who weren't able to make the change to `msgpack` because we still depended on `msgpack-python`.

So, that was sort of the catalyst that got us thinking about how our dependencies should impact customers. We felt that vendoring specific versions would make it easier to build a more reliable package while having minimal side effects (I probably would have said "no side effects" until you opened this ticket 🤦‍♂).

The other approach would be just to depend on `msgpack`, but not a specific version, that way we don't lock customers into using our specific version constraints. It is much easier for us to code against `msgpack==0.6.1` if we know that that is the exact version we are using.

**Comment by JBKahn** [comment]
As long as you're willing to upgrade frequently or lock against major versions with a list of supported versions you've tested against it should be alright. Most libraries are good about not breaking things in minor versions. But vendoring is an option if you feel that strongly about it.

**Comment by jd** [comment]
Yeah, I tend to think the strategy of supporting wide ranges of libraries is a good enough strategy and avoid the pain of vendoring. It's a trade-off as you said anyway (i.e. you can't use the latest feature of `$lib` before a few years when you know everyone has it).

Though in the case of msgpack, the rename is more painful as it makes it hard to support both at the same time with only one dependency (do you pull the new or the old name?). 🤷‍♂

**Comment by JBKahn** [comment]
I tend to make go for the upgrade and cut a major dependency upgrade of my own lib (which is what I do in this case) and let my users go through the upgrade at their leisure. And if they are stuck on an older version of that lib, they are stuck in an older version of the library. That's been my philosophy.

**Comment by JBKahn** [comment]
We don't know exactly how it happens, we could reproduce it but it was only in Django. Patching botocore would override the timezone setting and caused strange behaviour. We ended up using an env var to set the value instead of Django's setting alone and that seemed to fix the issue. So not a vendored lib issue that time.

Speaking of which, have you had a chance to look into this yet @brettlangdon

**Comment by brettlangdon** [comment]
@JBKahn sorry, no I have not had a chance to dig into this this week, been bogged down with some other things :(

I am really glad that you may have found a work around, but lets not call this good, we should still be 100% our vendored packages are having any effects on anyone's applications.

**Comment by JBKahn** [comment]
Agreed, keep us posted if you have the time to look into it next week!

**Comment by emosesPatreon** [comment]
I have just run into this as well when attempting to upgrade `ddtrace` to 0.30.1, would love to see a resolution for this.  Thanks.

**Comment by majorgreys** [comment]
@JBKahn @emosesPatreon We will be unvendoring msgpack to avoid these issues with the C extensions.

Are there any other vendored libraries that you were having issues with?

**Comment by JBKahn** [comment]
Yay. Nothing that I can recall. But I'll think it over.

**Comment by iandelahorne** [comment]
@majorgreys That's good to hear (I'm from the same org as @emosesPatreon was reporting from). Eagerly looking forward to the next release.

We haven't seen any other vendored libraries cause issues yet but we'll file issues / support tickets if we do.

**Comment by majorgreys** [comment]
@iandelahorne @JBKahn @emosesPatreon Can you confirm the update now on `master` fixes this issue?

**Comment by majorgreys** [comment]
`master` now no longer has `msgpack` as a vendored dependency. I was able to reproduce the issue @JBKahn originally provided before this change (thanks for the clear description!) and the `TypeError` is no longer being thrown after the change. If there are still any issues with having msgpack as a dependency, please re-open this issue and I'll make the adjustments.
