### ISSUE TITLE
Update to v2.11.0 causes "Receiver binary path is not executable: /.venv/lib/python3.11/site-packages/ddtrace/internal/datadog/profiling/crashtracker/crashtracker_exe" error

### ISSUE THREAD

**Issue by somnam** [DataDog/dd-trace-py#10327]
### Summary of problem
Update to v2.11.0 causes error:
> Receiver binary path is not executable: /.venv/lib/python3.11/site-packages/ddtrace/internal/datadog/profiling/crashtracker/crashtracker_exe 

### Which version of dd-trace-py are you using?
v2.11.0 from pypi

### Which version of pip are you using?
pip 24.1

### How can we reproduce your problem?
Update from v2.10.3 to v2.11.0.
Run app with `ddtrace-run` and observe error logs in datadog UI.

### What is the result that you get?
Each time app starts the following error appears:
> Receiver binary path is not executable: /.venv/lib/python3.11/site-packages/ddtrace/internal/datadog/profiling/crashtracker/crashtracker_exe 

### What is the result that you expected?
No `Receiver binary path is not executable` error.

**Comment by P403n1x87** [comment]
@somnam thanks for your report. This issue should be resolved in 2.11.1. Would you be able to give this version a try, please?

**Comment by somnam** [comment]
@P403n1x87: Thanks, it looks that 2.11.1 fixed this issue, closing then.
