### ISSUE TITLE
GRPC patching incorrectly handles arbitrary exceptions

### ISSUE THREAD

**Issue by egeromin** [DataDog/dd-trace-py#1039]
Bug found on

- python3.7
- dd-trace-py==0.28.0
- grpcio==1.23.0

GRPC patching incorrectly handles arbitrary exceptions. If for whatever reason the GRPC call raises any error other than an `grpc.RpcError`, then this exception is handled incorrectly by the patching code. This is because the method `ddtrace.contrib.grpc.client_interceptor._handle_response_or_error` expects the exception to have `.code()` and `.details()` methods, which is not the case for errors other than `grpc.RpcError`s. As a result, an `AttributeError` is raised by this patching code. 

## How to reproduce

I encountered this while using `grpc` inside a celery task that timed out. Something along these lines should work:

https://gist.github.com/egeromin/cf6c78d06ad0005aec3e7c1a6f857db9

## Possible fix

This looks like a typo in `_handle_response_or_error`. It should probably just be 

```python
def _handle_response_or_error(span, response_or_error):
    exception = response_or_error.exception()
    if exception is not None:
        code = to_unicode(response_or_error.code())
        details = to_unicode(response_or_error.details())
        span.error = 1
        span.set_tag(errors.ERROR_MSG, details)
        span.set_tag(errors.ERROR_TYPE, code)
```

**Comment by majorgreys** [comment]
I pulled together a gist for reproducing this issue.

https://gist.github.com/majorgreys/758afd2d0bda717997a30ea0f4de314b

I was able to confirm what you reported for 0.28.0 and 0.29.0.

I started a branch and PR for resolving this: 

https://github.com/DataDog/dd-trace-py/pull/1050

When using the branch, the soft time limit is caught as expected and the trace included this information:

![image](https://user-images.githubusercontent.com/155673/64545778-64b74c00-d2f7-11e9-9087-c7364aa7a45f.png)

 @egeromin Can you confirm this resolves your issue?

**Comment by egeromin** [comment]
@majorgreys I can confirm this resolves the issue. Thanks for fixing!
