### ISSUE TITLE
Filter settings stop working after update to 2.11.2

### ISSUE THREAD

**Issue by d-labas** [DataDog/dd-trace-py#10478]
### Summary of problem
After upgrading from ddtrace 2.11.1 to 2.11.2, the filter settings are no longer being applied correctly. Instead all traces are being recorded, including those that should be filtered out.
```
ddtrace.tracer.configure(
    settings={"FILTERS": [FilterRequestsOnUrl([r"...", r"..."])]}
)
```
[Suspected changes:](https://github.com/DataDog/dd-trace-py/compare/v2.11.1...v2.11.2#diff-3ee322478554cf5c3393bc0bcbbff273887d06dc2e7c568341747de44c9b80e7R89-R102)
My bet is that the issue is related to the `_child_after_fork()` method, which seems to [overwrite](https://github.com/DataDog/dd-trace-py/compare/v2.11.1...v2.11.2#diff-3ee322478554cf5c3393bc0bcbbff273887d06dc2e7c568341747de44c9b80e7R92) the existing filters when the `init` runs. 
```
self.tracer.configure(settings={"FILTERS": [self._trace_processor]})
```
Probably want to make sure that the settings are always [keeping the previous trace filters](https://github.com/DataDog/dd-trace-py/compare/v2.11.1...v2.11.2#diff-3ee322478554cf5c3393bc0bcbbff273887d06dc2e7c568341747de44c9b80e7R99-R102) like they are in the `_start_service()`.
```
tracer_filters = self.tracer._filters
if not any(isinstance(tracer_filter, LLMObsTraceProcessor) for tracer_filter in tracer_filters):
    tracer_filters += [self._trace_processor]
self.tracer.configure(settings={"FILTERS": tracer_filters})
```

In case that I am wrong, let me know what other info do you need. :pray: 

### Which version of dd-trace-py are you using?
2.11.2
### How can we reproduce your problem?
Configure ddtrace with custom filter settings
```
ddtrace.tracer.configure(
    settings={"FILTERS": [FilterRequestsOnUrl([r"...", r"..."])]}
)
```
use 2.11.2 version and shoot.
### What is the result that you get?
All traces are being recorded, including those that should be filtered out based on the configured settings.
### What is the result that you expected?
The filter settings should be applied correctly, filtering out the specified URL patterns.

**Comment by Yun-Kim** [comment]
Hi @d-labas, thanks for reaching out! It seems you are correct, we did not account for existing custom filters when restarting on fork. We'll work on getting a fix asap.
