### ISSUE TITLE
Consider creating a changelog

### ISSUE THREAD

**Issue by pbasista** [DataDog/dd-trace-py#1056]
Consider creating a changelog so that it would be possible to easily determine what are the most important changes made between the released versions.

**Comment by jd** [comment]
We could set up https://pypi.org/project/reno/

**Comment by brettlangdon** [comment]
We do create release notes in https://github.com/DataDog/dd-trace-py/releases but adding a changelog to the repo could also help people find that information easier.

**Comment by jd** [comment]
It's also that using something like reno makes sure notes are part of the commits.

**Comment by adamchainz** [comment]
Can you link to the releases page prominently at least? I don't think to check GitHub releases because very few Python projects use them for their release notes.
