### ISSUE TITLE
USER_REJECT'ed traces are still appearing in APM

### ISSUE THREAD

**Issue by goodspark** [DataDog/dd-trace-py#1061]
Python 3.7
ddtrace 0.29.0
DD agent 6.18.0
pyramid 1.10.4

1. Setup a simple pyramid service with an endpoint that is USER_REJECT'ed
2. Point it to a DD agent
3. Hit said endpoint

Expect: The endpoint to not appear at all in APM
Actual: It does. The only difference seems to be that individual traces are removed. But requests against the endpoint still impact service-level metrics.

I'm following the instructions at http://pypi.datadoghq.com/trace/docs/advanced_usage.html#sampling

My particular use case here is:
- I have load balancers hitting my health check endpoint often
- I don't want metrics from health check endpoints (generally very fast) to faslely drive down my service-level performance metrics (which I will soon use to monitor for alerts and regressions for critical services)

My health check view function:
```python
def health(_request):
    tracer.context_provider.active().sampling_priority = USER_REJECT
    return {}
```

The service-level view in APM:
![Screenshot from 2019-09-16 13-11-03](https://user-images.githubusercontent.com/29210237/64989976-a742d080-d883-11e9-889c-72249967320f.png)

The health check resource in APM:
![Screenshot from 2019-09-16 13-11-21](https://user-images.githubusercontent.com/29210237/64990002-b45fbf80-d883-11e9-94f4-9f9c41980e28.png)

**Comment by majorgreys** [comment]
@goodspark Sorry for the delayed response here to this question. Perhaps you figured out an answer but I wanted to share a few responses that might help.

As described in [Trace Sampling and Storage](https://docs.datadoghq.com/tracing/guide/trace_sampling_and_storage/?tab=python), the agent computes aggregate statistics over all the instrumented traces, regardless of sampling decision. 

Setting the sampling priority to `USER_REJECT` will make sure the trace is not stored however the trace will be used for gathering statistics (see [ddtrace/ext/priority.py](https://github.com/datadog/dd-trace-py/blob/master/ddtrace/ext/priority.py).

You might instead want to use filtering to ignore traces from this endpoint:

http://pypi.datadoghq.com/trace/docs/advanced_usage.html#trace-filtering

**Comment by majorgreys** [comment]
@goodspark Can you update with whether my explanation and suggestion resolves this issue?

**Comment by majorgreys** [comment]
@goodspark I am closing this issue though do reopen if your original problem is still unaddressed.
