### ISSUE TITLE
Memory usage with disabled tracer

### ISSUE THREAD

**Issue by JBKahn** [DataDog/dd-trace-py#1075]
The disabled tracer is using up a lot of memory for code that uses `tracer.trace` and `tracer.wrap` is there a reason why the tracer/wrap code isn't just a no-op when it's disabled.
e.g. https://github.com/DataDog/dd-trace-py/pull/1074

**Comment by majorgreys** [comment]
@JBKahn I wanted to make sure they memory issue with a disabled tracer is the expected behavior given we do not currently provide a no-op solution. Have you found the memory usage increasing over time with a disabled tracer?

**Comment by JBKahn** [comment]
yes, we have. I would hope the memory leak isn't expected behaviour. At present I've had to wrap your tracer wrapper in one of my own that only applies your wrapper if it's enabled. This helps to keep the memory issues at bay (the same memory issues we have sometimes when it's enabled).
