### ISSUE TITLE
Aiopg patch doesn't work with aiopg 1.0.0

### ISSUE THREAD

**Issue by kestein** [DataDog/dd-trace-py#1076]
As of aiopg 1.0.0 there is no longer an [aiopg.connection._connect function](https://github.com/aio-libs/aiopg/blob/v1.0.0/aiopg/connection.py). The current release of ddtrace [patches this function](https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/aiopg/patch.py#L22) and will no longer work.

**Comment by k4nar** [comment]
I've tried to make fix, but I think that the tests will have to be rewritten as well. Aiopg 1.0 is only compatible with the async/await syntax, which is not used everywhere in ddtrace.

**Comment by jd** [comment]
I think we avoided the async/await syntax because we used to support Python 3.4. That's not the case anymore, so we should be fine using it now.

**Comment by thehesiod** [comment]
I'll work on this here https://github.com/DataDog/dd-trace-py/pull/973

**Comment by emmettbutler** [comment]
@DataDog/apm-framework-integrations-reviewers-py

**Comment by emmettbutler** [comment]
The request for an aiopg>=1.0.0 integration is in our team's feature backlog and is not planned for the short term. As part of the backlog it will be considered during feature prioritization.

If anyone reading this is motivated to contribute the integration, please do so.
