### ISSUE TITLE
ddtrace-run import requests before gevent can patch it

### ISSUE THREAD

**Issue by yury-primer** [DataDog/dd-trace-py#1090]
`ddtrace-run` imports `elasticsearch` which imports the `requests` module before gevent can patch it. This is essentially the same problem as #506. It appears to be a regression.

A simple way to reproduce is to run `ddtrace-run python -c 'import sys; print("requests" in sys.modules)'`.

I am using `ddtrace==0.29.0`.

**Comment by majorgreys** [comment]
@yury-primer Closing this as #981 should have addressed this. Please re-open if the issue persists.
