### ISSUE TITLE
Django API APM traces disappeared after upgrade from 0.29.0 to 0.30.0

### ISSUE THREAD

**Issue by JBKahn** [DataDog/dd-trace-py#1102]
In talking with @brettlangdon we couldn't find a quick solution, but downgrading the library version brought them back. Interestingly enough, even the custom traces we were using within the API disappeared but all the ones that exist outside of Django i.e. workers, are all fine on version 0.30.0

**Comment by awiddersheim** [comment]
I had similar issues going from `0.27.1` to `0.30.1`. Reported to DD support VIA chat and downgraded to fix.

**Comment by brettlangdon** [comment]
@awiddersheim would you be able to confirm that `0.29.0` works fine for you?

Want to try and isolate to only changes between `0.29.0` and `0.30.0`

**Comment by JBKahn** [comment]
@awiddersheim @brettlangdon upon investigation with @majorgreys , if I shell into a running container and run a local `python manage.py runserver` call, and use `curl` then it does end up in the APM data. Currently I suspect it might be something to do with threads, nginx, uwsgi as those are the only other "things" that are happening that should be different other than running it via `runserver`.

**Comment by JBKahn** [comment]
@awiddersheim are you using uwsgi? Is it threaded? How many?

**Comment by shshe** [comment]
We've experienced this as well when upgrading from 0.29 to 0.30.1 on our gunicorn + django app and celery workers. We've downgraded to 0.29 and APM traces have been restored.

**Comment by awiddersheim** [comment]
We are using `gunicorn` with `sync` workers.

**Comment by bryanculbertson** [comment]
I am using `gunicorn` with `sync` workers for a `flask` app and I stopped getting traces in `0.30.1` and do get traces in `0.29.0`.

I was still getting logs with `0.30.1` and have multiple `WARNING` level logs:
```
Writer queue is full has more than 1000 traces, some traces will be lost
```
from `/usr/local/lib/python3.7/site-packages/ddtrace/internal/writer.py` line `228` in funcName `put`.

**Comment by JBKahn** [comment]
I had the same, I tried increasing the max size to see if that fixed it, but it did not.

**Comment by zhaoyi0113** [comment]
Based on this PR: https://github.com/DataDog/dd-trace-py/pull/1094, it says `send statistics less often and disable by default`. It seems this feature is disabled by default. I wonder how I can enable it?

**Comment by JBKahn** [comment]
Unfortunately that was in `0.30.1` so it landed after the breakage, at least for us.

**Comment by cyface** [comment]
We are also having this issue with 0.30.1.

**Comment by aleyan** [comment]
Thank you for figuring this out. Will there be a point release for this fix?

**Comment by brettlangdon** [comment]
Yes, we are working on getting 0.30.2 out for this very quickly

**Comment by brettlangdon** [comment]
If anyone wants to try this out ahead of time:

`pip install git+https://github.com/datadog/dd-trace-py@d827a04896469f65511f364e1c017fb0972d63a3#egg=ddtrace`

**Comment by brettlangdon** [comment]
`v0.30.2` has been released to PyPI which should resolve this issue. Please reopen this issue if it does not.
