### ISSUE TITLE
Flask APM trace is disabled with 0.30.1

### ISSUE THREAD

**Issue by zhaoyi0113** [DataDog/dd-trace-py#1103]
After upgrade to ddtrace 0.30.1, all APM trace disappeared from Datadog. I see this PR https://github.com/DataDog/dd-trace-py/pull/1094 is part of the release. Does it have anything to do with disabling statistics by default? If yes, how can I enable it?

**Comment by brettlangdon** [comment]
@zhaoyi0113 I am sorry you are experiencing problems, this seems related to #1102 

I will keep this issue open for now until we determine that the issue here and for Django are actually the same.

**Comment by brettlangdon** [comment]
This should be resolved by #1106 and will be released as a 0.30.2 bug fix.

**Comment by brettlangdon** [comment]
`v0.30.2` has been released to PyPI which should resolve this issue. Please reopen this issue if it does not.
