### ISSUE TITLE
DD_TAGS seperator behavior is different than documented

### ISSUE THREAD

**Issue by jasondamour** [DataDog/dd-trace-py#11046]
Datadog [Documentation](https://docs.datadoghq.com/getting_started/tagging/assigning_tags/?tab=noncontainerizedenvironments#methods-to-assign-tags:~:text=version%22%3A%22versiontag%22%7D%0A%20%20%20%20%20%20%2D-,DD_TAGS,-%3D%22key1%3Avalue1%2C%20key2) states that `DD_TAGS` uses comma **and** spaces.

If I use both, I get the following error from the agent:
```
Failed to find separator for tag string: 'ci.pipeline.url:https://example.io/, ci.pipeline.id:1234, ci.pipeline.number:0'.
Tag strings must be comma **or** space separated:
  key1:value1,key2:value2
  key1:value1 key2:value2
```

Agent version: `2.11.6`

**Comment by quinna-h** [comment]
There are two types of usages for `DD_TAGS`: 

1. The Datadog Agent 
    - `DD_TAGS`: as mentioned in the [configuration docs](https://docs.datadoghq.com/getting_started/tagging/assigning_tags/?tab=noncontainerizedenvironments#environment-variables), `If you specify multiple tags, separate each one with a space.`
    - This should be used to set tags on the Agent for every metric, event, log, trace, and service check.
2. The Python tracer 
    - `DD_TAGS`: as mentioned in the [configuration docs](https://ddtrace.readthedocs.io/en/stable/configuration.html#DD_TAGS), `Value must be either comma or space separated. e.g. key1:value1,key2:value2 or key1:value key2:value2.`
    - This should be used to set tags on every span

The docs that you linked are specified for the Datadog Agent settings, but based on the error message that you provided it looks like you're configuring for the second method (the Python tracer). Please use either commas **or** spaces as defined in the Python tracer documentation. Let us know if you have further questions.

**Comment by jasondamour** [comment]
Thats confusing but alright
