### ISSUE TITLE
ddtrace==2.13.1 profiler issue

### ISSUE THREAD

**Issue by doudoujay** [DataDog/dd-trace-py#11069]
After i updated our docker's ddtrace from ddtrace==2.9.3 to ddtrace==2.13.1, we observed some weird behaviors on profiler.
We upgraded on Oct 11.

Heap - Bytes in Use drop to 0
 ![Image](https://github.com/user-attachments/assets/0af4d440-65f3-4bbc-8ce4-2de88d26e357)
![Image](https://github.com/user-attachments/assets/08c441b6-0dd0-4cff-a85d-66ce5cf0ea6c)

Allocated Bytes Significantly increased - 
![Image](https://github.com/user-attachments/assets/26eba438-8acd-4742-bef5-e309d1c3f9f0)
![Image](https://github.com/user-attachments/assets/c8c3fd7b-e301-4fad-bf59-06f0d7a6c18b)
Huge chunk of memory consumed by periodic `ensure_binary`

Increased CPU Time
![Image](https://github.com/user-attachments/assets/6a1d1831-9ef8-41e7-a093-80999867e837)
![Image](https://github.com/user-attachments/assets/cc017e9f-ce7d-4e40-83a3-a92bd6fa3d2f)

**Comment by doudoujay** [comment]
any updates?

**Comment by doudoujay** [comment]
@mabdinur @taegyunkim any updates on this?

**Comment by taegyunkim** [comment]
@doudoujay Hi could you share environment variables that you're giving to ddtrace? e.g. `DD_PROFILING_*` and `DD_TRACE_*`. Could you also share Python version too?

**Comment by doudoujay** [comment]
```
ENV DD_LOGS_ENABLED=true
ENV DD_LOGS_INJECTION=true
ENV DD_TRACE_ENABLED=true
ENV DD_PROFILING_ENABLED=true
# https://docs.datadoghq.com/tracing/trace_collection/custom_instrumentation/python/otel/
ENV DD_TRACE_OTEL_ENABLED=true
# https://docs.datadoghq.com/profiler/connect_traces_and_profiles/#identify-code-hotspots-in-slow-traces
# only available for ver 2.10.5+
ENV DD_PROFILING_TIMELINE_ENABLED=true
# https://docs.datadoghq.com/dynamic_instrumentation/enabling/python/?tab=environmentvariables
ENV DD_DYNAMIC_INSTRUMENTATION_ENABLED=true
# https://docs.datadoghq.com/tracing/metrics/runtime_metrics/python/
ENV DD_RUNTIME_METRICS_ENABLED=true
# https://docs.datadoghq.com/infrastructure/process/?tab=docker
ENV DD_PROCESS_CONFIG_PROCESS_COLLECTION_ENABLED=true
# code tracking
ARG DD_GIT_REPOSITORY_URL
ARG DD_GIT_COMMIT_SHA
ENV DD_GIT_REPOSITORY_URL=${DD_GIT_REPOSITORY_URL}
ENV DD_GIT_COMMIT_SHA=${DD_GIT_COMMIT_SHA}
```
@taegyunkim

**Comment by taegyunkim** [comment]
1. `ensure_binary_or_empty` shows up in your profiles as you've set `DD_PROFILING_TIMELINE_ENABLED`. The flag enables native profile exporter which uses `ensure_binary_or_empty` to convert Python `str` to utf-8 encoded `bytes` which is then passed to C++ native code as `std::string_view`. 
2. You don't see any frame below `ensure_binary_or_empty` as the function calls CPython's built-in `str.encode()` which is implemented in C [here](https://github.com/python/cpython/blob/e334022de0adef5bbf1f59c5226ca521dcfed4aa/Objects/clinic/unicodeobject.c.h#L194-L216)  and dd-trace-py profiler doesn't show native frames.
3. Looks like `str.encode()` always creates an object, allocating memory, even if the given str object is already in the desired encoding, in our case `utf-8`. We probably should use lower level CPython API, probably `PyUnicode_AsUTF8AndSize()`, which simply returns `const char*`, and pass that to C++ native code.

Thank you for pointing this out @doudoujay, will soon work on a fix for this, < 2 weeks.

**Comment by doudoujay** [comment]
So i guess for short term solution would be we turn off `DD_PROFILING_TIMELINE_ENABLED`?

**Comment by taegyunkim** [comment]
Yes, could you try turning it off?

**Comment by doudoujay** [comment]
@taegyunkim hey its still taking significant chunk of CPU cycle and memory - 
![Image](https://github.com/user-attachments/assets/4fc20e02-2588-4531-99a6-ab894436c126)
![Image](https://github.com/user-attachments/assets/795e996a-db55-4704-9a02-275da26064f7)
dd version 2.14.4

dd flags:
```
ENV DD_LOGS_ENABLED=true
ENV DD_LOGS_INJECTION=true
ENV DD_TRACE_ENABLED=true
ENV DD_PROFILING_ENABLED=true
# https://docs.datadoghq.com/tracing/trace_collection/custom_instrumentation/python/otel/
ENV DD_TRACE_OTEL_ENABLED=true
# https://docs.datadoghq.com/dynamic_instrumentation/enabling/python/?tab=environmentvariables
ENV DD_DYNAMIC_INSTRUMENTATION_ENABLED=true
# https://docs.datadoghq.com/tracing/metrics/runtime_metrics/python/
ENV DD_RUNTIME_METRICS_ENABLED=true
# https://docs.datadoghq.com/infrastructure/process/?tab=docker
ENV DD_PROCESS_CONFIG_PROCESS_COLLECTION_ENABLED=true
# code tracking
ARG DD_GIT_REPOSITORY_URL
ARG DD_GIT_COMMIT_SHA
ENV DD_GIT_REPOSITORY_URL=${DD_GIT_REPOSITORY_URL}
ENV DD_GIT_COMMIT_SHA=${DD_GIT_COMMIT_SHA}
```

**Comment by doudoujay** [comment]
@taegyunkim any updates?

**Comment by taegyunkim** [comment]
@doudoujay that flamegraph doesn't make sense to me as it shows `ensure_binary_or_empty` even though you don't have none of `DD_PROFILING_EXPORT_LIBDD_ENABLED`, `DD_PROFILING_STACK_V2_ENABLED`, or `DD_PROFILING_TIMELINE_ENABLED`. Could you check again your `DD_*` environment variables and flamegraph? You can also try to filter the profile using `profiler_config:*py*` to make sure that the flamegraph you get is only from those services without above environment variables set.

**Comment by taegyunkim** [comment]
@doudoujay Can you also try enabling `DD_PROFILING_STACK_V2_ENABLED`?

**Comment by doudoujay** [comment]
> Could you check again your DD_* environment variables and flamegraph
Im sure i didnt turn on `DD_PROFILING_TIMELINE_ENABLED` or any of them. @taegyunkim

**Comment by doudoujay** [comment]
I will try enable `DD_PROFILING_STACK_V2_ENABLED`. Whats the expected behavior? @taegyunkim

**Comment by taegyunkim** [comment]
`DD_PROFILING_STACK_V2_ENABLED` enables our new stack profiler which implemented in native languages, mostly C++/Rust.

**Comment by taegyunkim** [comment]
And do you mind sharing what Python version you're using? From our testing, Python 3.12 doesn't have the issue `ensure_binary_or_empty()` allocating a lot of memory.

**Comment by doudoujay** [comment]
> And do you mind sharing what Python version you're using? From our testing, Python 3.12 doesn't have the issue ensure_binary_or_empty() allocating a lot of memory.
@taegyunkim Im using python 3.1
```
FROM python:3.10
```

**Comment by slallema** [comment]
Hello @taegyunkim 
We use python 3.12.2 and we run into high CPU usage issue when upgrading ddtrace.
We tried this morning ddtrace 2.16.0 and we still notice CPU increase:
![Image](https://github.com/user-attachments/assets/551f14fc-a87a-44e2-90e6-da78c25308e4)
We had to revert to 2.9.2.

**Comment by VivaLaPanda** [comment]
Seeing the same thing, just rolled back

**Comment by yeisonvargasf** [comment]
Using `python:3.12-slim` and `ddtrace` 2.18.1 with `ddtrace-run uvicorn` caused high CPU usage. I rolled back to 2.9.2 and it worked for me.
