### ISSUE TITLE
How to set service name in the code?

### ISSUE THREAD

**Issue by zhaoyi0113** [DataDog/dd-trace-py#1108]
I have a regular python application without any framework. I'd like to know how I can set the service name for that. I have read this code: https://github.com/DataDog/dd-trace-py/blob/0dd8771be86348c2f538c46192d67bccd3385afd/ddtrace/commands/ddtrace_run.py#L32. And it says that for a non-web app, set the service name in the code. I wonder how I can do that? Is there an API I can set the service name globally for my app?

**Comment by brettlangdon** [comment]
There is no way at this time to configure a default service name if a span is started without one.

I assume you are doing custom instrumentation, e.g.:

```python
from ddtrace import tracer

with tracer.trace('my.operation') as span:
    pass
```

If so, all you need to do is:

```python
from ddtrace import tracer

with tracer.trace('my.operation', service='my-service') as span:
    pass
```

You only need to set the service name on the top level operation name for your service, all child spans created without a service name will inherit it's service from it's parent.

**Comment by zhaoyi0113** [comment]
Thanks for your comments. It makes sense to me. I have tried that the root service name works fine but some nested request doesn't work well. 

```
@tracer.wrap(service=service_name)
def run_main():
        db_connection = get_database_connection(DB_HOST, DB_USER, DB_PASSWORD, DB_DATABASE)
        Pin.override(db_connection, service=f'{service_name}')
        es_client = get_elasticsearch_client(ES_SERVICE)
        Pin.override(es_client, service=service_name)
```
The above is my python code. I can see my service name appears on datadog APM service page. However I see there is a `Elasticsearch` appears on the same level as my service. I did try to override the elasticsearch instance with my service name. But it still appears as a separate service. Below is the screenshot and you can see `elasticsearch` is the second. The top one is my service name. Do I need to do any other thing in order to move `elasticsearch` to be under my service?

![image](https://user-images.githubusercontent.com/3355579/67440066-d21f0200-f643-11e9-8e82-dbe7d50343b7.png)

**Comment by brettlangdon** [comment]
I believe you need to do `Pin.override(es_client.transport, service=service_name)`

http://pypi.datadoghq.com/trace/docs/db_integrations.html#elasticsearch

**Comment by zhaoyi0113** [comment]
I have added `patch_all` and using `transport` in my code. I can see that `Elasticsearch` appears under my service resources. But it is still showing as a separate service on the root level. Is it expected?

**Comment by zhaoyi0113** [comment]
As it is pretty clear about what to do with regular python program. Thanks for the response.
