### ISSUE TITLE
ddtrace not sending traces to datadog-agent for Django app in AWS EKS

### ISSUE THREAD

**Issue by mislavcimpersak** [DataDog/dd-trace-py#1110]
I'm trying to get APM tracing working for a Django app deyployed in AWS EKS.

- gunicorn==19.9.0
- Django==2.2.6
- django-configurations==2.1
- django-environ==0.4.5
- ddtrace==0.30.1

I've set up datadog agent as _DaemonSet_ following
https://docs.datadoghq.com/agent/kubernetes/daemonset_setup/?tab=k8sfile

I have a Django app running via Gunicorn. In kube config for it I'm setting env var `DD_AGENT_HOST` to `status.hostIp`.

I'm starting the Django app using a shell script:

```
#!/usr/bin/env bash

# some checks before container start are taken out

exec ddtrace-run gunicorn app_name.wsgi:application \
    --access-logfile - \
    --log-file - \
    --bind 0.0.0.0:8080 \
    --worker-tmp-dir /dev/shm \
    --workers=2 \
    --threads=4 \
    --worker-class=gthread
```

In my django settings I have:

```
DATADOG_TRACE = {
    "DEFAULT_SERVICE": "app_name",
    # read datadog agent host from env var
    "AGENT_HOSTNAME": ENV.str("DD_AGENT_HOST"),
    # read deployment env name from env var
    "TAGS": {"env": ENV.str("STAGE")},
}
INSTALLED_APPS = [
    ...
    "ddtrace.contrib.django"
]
MIDDLEWARE = [
    ...
    "ddtrace.contrib.django.TraceMiddleware"
    ...
]

...

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "console": {
            "format": "{levelname} {asctime} {stage} {module} {process:d} {thread:d} {message}",
            "style": "{",
            "level": "DEBUG",
        }
    },
    "filters": {"stage": {"()": "app_name.logger.DeployStageFilter"}},
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "console",
            # this filter is setting deployment env by reading the
            # value from env var (it's working since I see it in Sentry)
            "filters": ["stage"],
        }
    },
    "loggers": {
        "": {"handlers": ["console"], "level": "DEBUG", "propagate": True},
        "ddtrace": {"handlers": ["console"], "level": "INFO"},
    },
}
```

But, I got no traces of any kind in Datadog web UI.

Following troubleshooting docs on https://github.com/DataDog/dd-trace-py/blob/master/docs/advanced_usage.rst#ddtrace-run
I tried to see if my container can send anything to Datadog so straight from the app container I ran:

```
pip install ipython
DATADOG_TRACE_DEBUG=true ddtrace-run ipython
```

and I got traces in Datadog web UI from iPython's sqlite! Great :)

Following that, I've modified my container start script to have set a bunch of datadog related env vars:

```
#!/usr/bin/env bash

# some checks before container start are taken out

export DATADOG_TRACE_DEBUG=true
export DATADOG_TRACE_ENABLED=true
export DATADOG_TRACE_AGENT_HOSTNAME=$DD_AGENT_HOST
export DATADOG_STATSD_HOST=$DD_AGENT_HOST
export DATADOG_ENV=dev
export DATADOG_TRACE_AGENT_PORT=8126
export DATADOG_SERVICE_NAME=app_name

exec ddtrace-run gunicorn api.wsgi:application \
    --access-logfile - \
    --log-file - \
    --bind 0.0.0.0:8080 \
    --worker-tmp-dir /dev/shm \
    --workers=2 \
    --threads=4 \
    --worker-class=gthread
```

still nothing.
Also ran a copy of the startup script manually (changed the gunicorn's bind port) and still got nothing in datadog.

My logs from the container are:

```
[2019-10-22 19:28:37 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2019-10-22 19:28:37 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2019-10-22 19:28:37 +0000] [1] [INFO] Using worker: gthread
[2019-10-22 19:28:37 +0000] [46] [INFO] Booting worker with pid: 46
[2019-10-22 19:28:37 +0000] [47] [INFO] Booting worker with pid: 47
```

After some time in my logs I get a bunch of messages like this:

```
WARNING 2019-10-22 19:27:00,230 dev writer 45 139624218359552 Writer queue is full has more than 1000 traces, some traces will be lost, 57 additional messages skipped
```

I duct-taped an easy way to write _info/warning/error_ messages to the logger and when I trigger that I can see those messages in the pod's logs ie.

```
WARNING 2019-10-22 19:30:07,857 dev admin 46 140672519108352 [TESTING LOGGING] Warning
# or
INFO 2019-10-22 19:30:50,184 dev admin 45 139866437871360 [TESTING LOGGING] Info
```

Using info provided here I concluded that:

- datadog-agent is working as expected deployed as a DaemonSet
- app container can talk to the datadog-agent
- ddtrace-run is being used to run the app since the app is actually working
- I do have logs from both the Django app and gunicorn
- ddtrace wants to send the message to datadog-agent, but keeps them queued up, never sending them :'( 

The last conclusion is also the question of this issue 🎢

I have no idea what prevents ddtrace from sending data to datadog-agent and I'm kind of out of ideas how to find out :-/ 

Any help would be appreciated 🙏

**Comment by brettlangdon** [comment]
(but also, thanks for the detailed information in this issue!!!!)

**Comment by mislavcimpersak** [comment]
The suggestion to upgrade to 0.30.2 appeared as a shining light at the end of a long tunnel, but alas, it was a mirage 😞 

----

I' ve updated ddtrace to 0.30.2 and just to be sure deleted and re-created my datadog daemonset. Still no traces in datadog :-/ 

Also, tried a downgrade to 0.29.0. Still 0️⃣

**Comment by brettlangdon** [comment]
@mislavcimpersak can you send me an email at brett.langdon@datadoghq.com ?

(or can find me on our public Slack https://chat.datadoghq.com/ @ brettlangdon)

I'd like to dig into your account a bit to help try and debug this.

**Comment by brettlangdon** [comment]
Closing this for now since @mislavcimpersak is now seeing tracings coming in.

But we'll keep an eye on #1011.

**Comment by mislavcimpersak** [comment]
Thank you @brettlangdon for the assistance! 🌟
