### ISSUE TITLE
TypeError endpoint profiling for stack v2

### ISSUE THREAD

**Issue by lattwood** [DataDog/dd-trace-py#11141]
The recent change to fix/enable endpoint profiling for Stack V2 has introduced a type error, that should have been caught before release :(.

* `tracer.trace` (and friends such as `@tracer.wrap`, etc) has `span_type: Optional[str] = None`
* `ThreadSpanLinks.link_span` requires a string.
* The call to `_stack_v2.link_span` has `# type: ignore`, so this was missed during code quality checks.

If you are creating root spans and not specifying the `span_type` (and I mean, why would you, it's `Optional`), this results in a metric ton of logs for the TypeError.

The error, also doesn't have any of the details of the span, so tracking it down is incredibly frustrating.

```
Traceback (most recent call last):
  File "/usr/src/.venv/lib/python3.12/site-packages/ddtrace/_hooks.py", line 136, in emit
    func(*args, **kwargs)
  File "/usr/src/.venv/lib/python3.12/site-packages/ddtrace/internal/datadog/profiling/stack_v2/__init__.py", line 22, in link_span
    _stack_v2.link_span(span_id, local_root_span_id, local_root_span_type)  # type: ignore # noqa: F405
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument 3 must be str, not None
```

Tagging @taegyunkim as the original author of the feature.

**Comment by taegyunkim** [comment]
@lattwood Thank you for reporting the issue. I'll shortly submit a PR to fix this.

**Comment by taegyunkim** [comment]
@lattwood Fix has been backported to all release branches. You'll soon see new releases including this.
