### ISSUE TITLE
How to stop sending a binary attribute to SNS/SQS

### ISSUE THREAD

**Issue by gclements-chwy** [DataDog/dd-trace-py#11380]
Hi, we have an application using ddtrace to send traces to DataDog. I noticed that ddtrace is adding a binary attribute (named _datadog) as a header in the request through boto to AWS when publishing a message to SNS. The problem with this is a service that is reading the message sees the binary attribute and rejects the message because it doesn't understand the binary attribute type. Is there a way to stop ddtrace from sending that binary attribute?

I found the `DD_BOTOCORE_PROPAGATION_ENABLED` environment variable and thought that setting it `False` might stop ddtrace from sending the binary attribute but that doesn't seem to be the case. 

We are using version `2.16.0` of the python ddtrace library.

**Comment by gclements-chwy** [comment]
Looking closer at the documentation for `DD_BOTOCORE_PROPAGATION_ENABLED` and it's default value being False I was wrong to think this would stop sending the binary attribute. I think the correct solution is to just pass `botocore=False` to `patch_all()` and not instrument botocore at all.

**Comment by wconti27** [comment]
Hi. Please disable message trace injection using: `DD_BOTOCORE_DISTRIBUTED_TRACING=false`.
