### ISSUE TITLE
Cannot configure redis and mysql service name for celery worker

### ISSUE THREAD

**Issue by akshjain83** [DataDog/dd-trace-py#1140]
For our celery apps, we are not able to configure service name for redis and mysql modules. Please take a note of our celery setup here:
1. A different python app as celery producer
2. A different python app as celery worker
3. Redis as celery broker
4. MySQL as celery backend

Celery internally uses connection pooling so there is no way (as far as I went through celery code) to get the broker and backend clients and override them using `Pin`. I found a similar issue and particularly a suggested [comment](https://github.com/DataDog/dd-trace-py/issues/357#issuecomment-461481150), but apparently there does not exists any attribute `queue.backend.client` (due to how celery organizes configs and client).

Due to lack of this configuration, we end up with these services listed individually on Datadog APM dashboard and hard to figure out which traces (redis, mysql) are coming from what apps (producer app, worker app). It is impossible to find what apps(producer or worker) are generating redis and mysql traces.

### Which version of dd-trace-py are you using?
`ddtrace==0.29.0`

### Which version of the libraries are you using?
```
celery==4.3.0
redis==3.3.8
mysqlclient==1.4.4
```

### How can we reproduce your problem?
```
from ddtrace import config as dd_config
   
dd_config.celery['worker_service_name'] = 'worker-app'
patch(celery=True, redis=True, mysql=True)
app = Celery(broker='redis://redis:@localhost:6379/0', 
                       backend='db+mysql://user:@127.0.0.1:3306/db')
```
### What is the result that you get?
When I check out Datadog APM dashboard, I see the following services listed individually:
- worker-app
- redis
- mysql

### What is result that you expected?
Since I want to track APM traces for all services used for worker, it would make true sense to have them in either of the following options:
1. redis, mysql and celery worker traces all under one single service name
2. Or listed separately but with a prefix to identify traces generated by worker

In either of the options above, I need a way to configure redis and mysql service name individually.

### Workaround 
As a workaround to make sure our traces are organized in true sense on APM dashboard, I am planning to write code to use environment variable (if set, otherwise default) in the following code lines (tested and it works):
- [Redis](https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/redis/patch.py#L37)
- [MySQL](https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/mysql/patch.py#L41)

Please let me if this is a viable workaround and if we plan to address this issue for celery module. Thanks

**Comment by Kyle-Verhoog** [comment]
Hi @akshjain83 sorry for the super late reply! The service name of the redis and mysql integrations can be configured through the config API or with environment variables:

- redis: https://ddtrace.readthedocs.io/en/stable/integrations.html#redis
- mysql: https://ddtrace.readthedocs.io/en/stable/integrations.html#module-ddtrace.contrib.mysqldb

I'll close this issue now but please re-open it if you have any issues 🙂
