### ISSUE TITLE
Support for responder

### ISSUE THREAD

**Issue by povils** [DataDog/dd-trace-py#1142]
Is there an easy way to integrate with responder web framework?

https://github.com/taoufik07/responder

**Comment by Kyle-Verhoog** [comment]
For those looking to get `ddtrace` support for responder now the ASGI middleware can be used to wrap the responder application:

- https://ddtrace.readthedocs.io/en/stable/integrations.html#asgi

Something like the following should work:


```python
import responder
from ddtrace.contrib.asgi import TraceMiddleware

api = responder.API()
api.add_middleware(TraceMiddleware)
```

**Comment by emmettbutler** [comment]
I'm closing this because @Kyle-Verhoog's ASGI solution appears to answer the original question.
