### ISSUE TITLE
Celery task producer (celery.apply) span in APM triggers Datadog service inference into creating a new service for the service's own hostname

### ISSUE THREAD

**Issue by patrys** [DataDog/dd-trace-py#11491]
We've enabled service inference, and our service list is now filled with spurious services named after every pod in every k8s service that publishes tasks. After running for just an hour, we already have 150 of those.

All of the fake services only report a single source of data, `celery.apply` and visiting traces for `celery.apply` confirms that `celery.hostname` seems to be converted into `peer.hostname` despite this span not actually making a client connection anywhere.

Under each `celery.apply` span we see the expected `sqs.sendmessage` span for the actual delivery of the task. That second span has the correct peer tags and is paired with the expected queue service.

Agents are deployed using Helm chart version 3.73.0
Code is traced using dd-trace-py version 2.11.2

**Comment by patrys** [comment]
After some investigation, the signal handler calls `set_tags_from_context(span, kwargs["headers"])`, and the comment suggests, that it's specifically to set `celery.hostname`. The hostname in question is the pod name of the task producer.

Then, the `trace_afer_publish` signal handler extracts the `celery.hostname` and uses its value to set `out.host`, which is wrong as the hostname is the origin of the task, not its target.

`out.host` is then transformed (by the agent, I assume) to `peer.hostname`, which is correct behavior, but because of the above, the value is incorrect.

**Comment by wconti27** [comment]
Hello, this behavior has been fixed in our latest patch release of [2.17.2](https://github.com/DataDog/dd-trace-py/releases/tag/v2.17.2). `out.host` will now point to the celery broker host.
