### ISSUE TITLE
Get dashboard URL from LLMObs trace

### ISSUE THREAD

**Issue by conradlee** [DataDog/dd-trace-py#11605]
I keep track of LLM chain runs using Datadogs excellent LLMObs framework.

I also have an internal dashboard/system log which shows details of each run.

I would love to have links from my dashboard to the DataDog dashboard.  Is it possible for me to create a link to the datadog dashboard, given an LLMObs span object?  E.g. given a root span, can I construct a URL to the LLMObs trace view for that span?

**Comment by Yun-Kim** [comment]
Hi @conradlee, thanks for reaching out!

Currently we cannot directly link to the LLMObs trace view with just the span/trace ID, but we are currently exploring ways to make this possible for users moving forward.

One workaround I can suggest at this time is to link to the traces table page with the span ID as a search term to yield the span in question, which should be something like this URL:
```
https://app.datadoghq.com/llm/traces?query=@span_id%3A{SPAN_ID}
```
Two notes for this workaround:
1.  The default time range for the trace search link is the past week, so past that you'll need to adjust the time range in the trace search page accordingly to find the span.
2. Please use the correct [Datadog site](https://docs.datadoghq.com/getting_started/site/) URL according to your region. (i.e. datadoghq.eu to EU1, etc)

**Comment by conradlee** [comment]
Thank you, this is a suitable workaround!
