### ISSUE TITLE
LLMObs: DD_PATCH_MODULES is not taken into account

### ISSUE THREAD

**Issue by backmask** [DataDog/dd-trace-py#11639]
Hello, when enabling LLMObs with an env variable, it appears that `DD_PATCH_MODULES` configuration is at least partially ignored.

With the following docker setup:
```
ENV DD_PATCH_MODULES=langchain:false
ENV DD_LLMOBS_ENABLED=true
CMD ["ddtrace-run", "python", "-u", "service.py"]
```

The service will patch `langchain` on start-up. Changing `DD_LLMOBS_ENABLED` to false fixes the issue.

I haven't fully figured out the code, but I think it is because LLMObs calls `patch` on all supported integrations ([code](https://github.com/DataDog/dd-trace-py/blob/main/ddtrace/llmobs/_llmobs.py#L351)), and this method doesn't check env variables. Changing it to [patch_all](https://github.com/DataDog/dd-trace-py/blob/main/ddtrace/_monkey.py#L217) may fix the issue, but I am unsure of side effects

**Comment by Yun-Kim** [comment]
Hi @backmask, thanks for reaching out!

I can reproduce your issue, and we'll be working on a fix to avoid ignoring/overriding `DD_PATCH_MODULES`.
