### ISSUE TITLE
App analytics support for the Celery integration?

### ISSUE THREAD

**Issue by AdrianLC** [DataDog/dd-trace-py#1217]
### Which version of dd-trace-py are you using?
0.31.0

### Which version of the libraries are you using?
celery 4.4.0

### How can we reproduce your problem?
We've tried to enable app analytics for the traces generated with the Celery integration and the services `celery-producer` and `celery-worker` without success. We attempted with env vars:
`DD_CELERY_ANALYTICS_ENABLED=True` and also `DD_CELERY_WORKER_ANALYTICS_ENABLED=True`

### What is the result that you get?
Celery services don't show app under App Analytics.

### What is result that you expected?
We would have liked support for this integration in the App Analytics. Maybe we are missing something, or is this just not supported yet? I've seem in the code that it doesn't set the span `ANALYTICS_SAMPLE_RATE_KEY` which I guess it's required?

**Comment by Kyle-Verhoog** [comment]
This was added in v0.38, thanks for the report 🙂
