### ISSUE TITLE
redis-py-cluster new API 2.0.0

### ISSUE THREAD

**Issue by raphaelauv** [DataDog/dd-trace-py#1224]
### Which version of dd-trace-py are you using?
 lastest 0.34.0

### Which version of the libraries are you using?

redis-py-cluster  2.0.0

### How can we reproduce your problem?

change https://github.com/DataDog/dd-trace-py/blob/master/tox.ini redis-py-cluster version

### What is the result that you get?

ERROR. It's no more StrictRedisCluster but  just RedisCluster

### What is result that you expected?

moving to new api

**Comment by raphaelauv** [comment]
Can we expect a new release ? I do not now the release policy

thank again

**Comment by majorgreys** [comment]
@raphaelauv We released 0.34.0 a week ago and have had a cadence of a new release every 3-4 weeks.
