### ISSUE TITLE
Enabling logging when not running via ddtrace-run

### ISSUE THREAD

**Issue by jadami10** [DataDog/dd-trace-py#1229]
### Which version of dd-trace-py are you using?
0.34.0

### How can we reproduce your problem?
Use dd-trace-py in a python script but don't run with `ddtrace-run`

### What is the result that you get?
My script runs, and my logs appears, but no logs from ddtrace appear.

### What is result that you expected?
I expect some logging to appear. I realize that ddtrace-run calls logging.basicConfig. Is that the only way to ensure these logs appear? Is there a supported way to manually get and configure the ddtrace root logger?

**Comment by majorgreys** [comment]
Are you interested in the debug logs from the tracer, which you would get if you set the `DATADOG_TRACE_DEBUG` environment variable for `ddtrace-run`? If so, you'll need to set the logging level to `logging.DEBUG`.

More generally, you can use the instruction for manual instrumentation of the Logs Injection feature to see how to include trace and span identifiers in log messages.

http://pypi.datadoghq.com/trace/docs/advanced_usage.html?highlight=logging#manual-instrumentation

**Comment by jadami10** [comment]
Typically when we want to update a logger in python, we call https://docs.python.org/3/library/logging.html#logging.getLogger then make changes. But the only way to affect the datadog logger seems to be to change the global logging. And if this is not what you want in your other loggers, you have to go back and undo the changes to those.

**Comment by Kyle-Verhoog** [comment]
As of v1.0 we will no longer call basicConfig as it was causing issues like this. @jadami10 please let us know if you're still having logging issues with `ddtrace`

**Comment by jadami10** [comment]
thank you for the update. unfortunately i'm not longer at the role where I was using this library, but hopefully someone else that runs into this issue pre 1.0 will see this thread and confirm
