### ISSUE TITLE
Additional Environment Variable setting using patch

### ISSUE THREAD

**Issue by subodh101** [DataDog/dd-trace-py#1230]
Thanks for taking the time for reporting an issue!

Before reporting an issue on dd-trace-py, please be sure to provide all
necessary information.

If you're hitting a bug, make sure that you're using the latest version of this
library.

## What?
https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/monkey.py#L112

```python
ddtrace.patch(grpc=True)
ddtrace.Pin(service="some_service").onto(grpc.Server)
```

ddtrace works pretty fine with just 2 lines of code. ❤️ 
But I was hoping if I can set the [environment values](https://github.com/DataDog/dd-trace-py/blob/4653e97f332ae12a8a5bd8e465c127c5b74bb7c2/ddtrace/tracer.py#L68) directly from patch function with extra argument *args or something.

### Which version of dd-trace-py are you using?
N/A
### Which version of the libraries are you using?
version==0.34.0

### What is result that you expected?
So that I can use it like:
```python
ddtrace.patch(hostname="some_host",grpc=True)
```

**Comment by majorgreys** [comment]
@subodh101 Do you mean to configure the Datadog agent hostname for the tracer in particular? If so, you want to be using `tracer.configure()` to do any setup, or set the `DD_AGENT_HOST` environment variable.

http://pypi.datadoghq.com/trace/docs/advanced_usage.html?highlight=configure#agent-configuration

**Comment by subodh101** [comment]
Thank you so much! you just got a new follower :)
