### ISSUE TITLE
Django - set_tag on span require now ALLOWED_HOSTS in version 0.34.0

### ISSUE THREAD

**Issue by opalczynski** [DataDog/dd-trace-py#1231]
### Which version of dd-trace-py are you using?
The bug apply to 0.34.0

### Which version of the libraries are you using?
django==2.2.0

You can copy/paste the output of `pip freeze` here.

### How can we reproduce your problem?
Yay, it will require a bit of work, but my case is as follows:

* I have healtcheck view configured in the application which I am using with AWS Load Balancer healtcheck (then LB knows that targets are up and healthy)
* The ALB target do not set any particular HOST headers (also that is not configurable)
* I implemented the view in the way that django ALLOWED_HOST is not needed to make it successful
* However, the ddtrace==0.34.0 due to changes in the implementation of how the tag is set on the span - broke this; 

So how can you reproduce it? Simply create a view that passes ALLOWED_HOST check but it is expected to return something. This can be done - eg. using the Middleware. 

### What is the result that you get?

I am getting 500 django error (which is totally valid) but I am not sure if this is desired behaviour. Setting up the healtcheck in any internal network is pretty hard to be done in django using ALLOWED_HOSTS (as you can not set wildcards there) and workaround are not super nice. 

### What is result that you expected?

I would expect it to pass nicely (the healtcheck)

### Where the bug is?

So in 0.34.0 this was introduced in the ddtrace/contrib/django/patch.py (it starts in line 404)

```
span.set_tag(
    http.URL,
    parse.urlunparse(
        parse.ParseResult(
            scheme=request.scheme,
            netloc=request.get_host(),  # this will include `host:port`
            path=request.path,
            params="",
            query="",
            fragment="",
        )
    ),
)
```

The biggest issue is `request.get_host()` as this fire the ALLOWED_HOST check in django:

```
    def get_host(self):
        """Return the HTTP host using the environment or request headers."""
        host = self._get_raw_host()
        # Allow variants of localhost if ALLOWED_HOSTS is empty and DEBUG=True.
        allowed_hosts = settings.ALLOWED_HOSTS
        if settings.DEBUG and not allowed_hosts:
            allowed_hosts = ['localhost', '127.0.0.1', '[::1]']
        domain, port = split_domain_port(host)
        if domain and validate_host(domain, allowed_hosts):
            return host
        else:
            msg = "Invalid HTTP_HOST header: %r." % host
            if domain:
                msg += " You may need to add %r to ALLOWED_HOSTS." % domain
            else:
                msg += " The domain name provided is not valid according to RFC 1034/1035."
            raise DisallowedHost(msg)
```

Of course raises DisallowedHost exception.

We can argue about my 'unorthodox' solution, but my bet would be that ddtrace should not rely here on django implementation - but rather introduce own host and port extractor. 

Cause - even not attached ot my particular use case - any misconfiguration in ALLOWED_HOST will not reach the datadog agent (cause 500 will be raised) and execution will be stopped (or I am wrong here?).

**Comment by opalczynski** [comment]
Btw. the workaround is obviously to use 0.33.0 of ddtrace now :)

**Comment by majorgreys** [comment]
@opalczynski Thank you for reporting this. Can you check whether the fix I started in #1235 does in fact fix your issue?

**Comment by opalczynski** [comment]
@majorgreys I checked the fix - it should work, I will made a confirmation on the beginning of the week. Thanks for taking care of this issue.

**Comment by majorgreys** [comment]
@opalczynski Can you confirm the fix? Thanks!

**Comment by opalczynski** [comment]
@majorgreys Sorry for the late notice - did a check on local environment - it works now; Thanks.
