### ISSUE TITLE
ClassView method with static method

### ISSUE THREAD

**Issue by arturodelreal** [DataDog/dd-trace-py#1234]
In version 0.34.0, ddtrace doesnt allow to have this class view:

```
class SampleView(View):
     @staticmethod
     @login_required
     def get(request):
         do stuff
```

raising this error when the view is called
`TypeError: get() takes 1 positional argument but 2 were given`

I think that in this version, force to pass the instance

I solve it changing to ddtrace 0.33.0, but i report this anyway

Thanks

**Comment by majorgreys** [comment]
@arturodelreal Thank you for reporting this, we are working on a fix now.
