### ISSUE TITLE
Redis integration treats evalsha failures as error when using registered script.

### ISSUE THREAD

**Issue by jhgg** [DataDog/dd-trace-py#124]
The redis integration tracks `NoScriptError`as an exception when calling a registered script. This exception is acceptable when registering/calling a script for the first time - and shouldn't be logged or treated as an error.

https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L2922

**Comment by brettlangdon** [comment]
@jhgg sorry for the very long delay in replying to this issue.

It does appear that this is still the case in the current redis client:

https://github.com/andymccurdy/redis-py/blob/01300521a116893db4f4fab33c518ebbd3a801d5/redis/client.py#L3569-L3576

However, I think it is still useful to include the `NoScriptError` for the `evalsha` span. My thinking here is that while the redis client does recover properly (by creating the script and then calling `evalsha` again) your applications flamegraph will have 2 spans for `evalsha`, it is worth having the first marked as an error so you know exactly what happened and why it is being executed a second time.

I am more than happy to continue the conversation on this decision if you'd like, but I am going to close this issue for now. Please feel free to re-open or open a new issue if you'd like!
