### ISSUE TITLE
Unable to resolve resource names/urlpatterns when using django-hosts

### ISSUE THREAD

**Issue by paddycarey** [DataDog/dd-trace-py#1263]
## Which version of dd-trace-py are you using?

0.34.1

### Which version of the libraries are you using?

```
django-hosts==4.0
django[argon2]==2.2.10
```

### How can we reproduce your problem?

Use `ddtrace-run` to auto instrument a Django app that relies on `django-hosts` for host-based routing and make a request to an endpoint that isn't on the default domain.

### What is the result that you get?

All requests to endpoints on non-default domains fail to resolve and end up mis-classified in the APM UI and are treated as 404s.

![image](https://user-images.githubusercontent.com/164309/76434061-14579e80-63ad-11ea-814e-cc9328ace2af.png)

Requests to the default domain resolve as expected like so.

![image](https://user-images.githubusercontent.com/164309/76436006-9e086b80-63af-11ea-86ab-c54e62dbc3c9.png)

### What is result that you expected?

All requests to valid URLs should be resolved as expected. We use a standard(ish) django-hosts setup with request/response middleware that sets the correct urlconf as needed on the request, but it seems that ddtrace is unable to use it for some reason.

In previous versions this worked fine for us because the resource name was the view name rather than the URL pattern so (I assume) that the integration just didn't try to resolve the URL. But as it stands currently we're unable to upgrade to versions `>=0.34.0` as we lose all ability to filter by url/view in APM.

I attempted to modify the dd-trace-py code locally to make it do the right thing but couldn't quite seem to make it work. Any help here would be much appreciated, thanks!

**Comment by paddycarey** [comment]
Spent a little more time looking at this and I think I see what's wrong, though still not sure how best to fix:

- `dd-trace-py` patches `BaseHandler.get_response` here https://github.com/DataDog/dd-trace-py/blob/v0.34.1/ddtrace/contrib/django/patch.py#L309
- The patched `get_response` attempts to resolve the resource name for the request _before_ invoking the wrapped `get_response`.
- The wrapped `get_response` invokes the middleware chain and only at this point does `django-hosts` `HostRequestMiddleware` (https://github.com/jazzband/django-hosts/blob/4.0/django_hosts/middleware.py#L51) kick in and set the correct urlconf for the request and allow `resolve` to find the right view, but at this point it's too late.

So _somehow_, in order to make this work, I need to set the correct urlconf _before_ the patched `get_response` is called, _or_ I need to retry the resource name resolution _after_ the wrapped `get_response` is called.

**Comment by majorgreys** [comment]
@paddycarey Thanks for investigating this deeper and suggesting these two solutions.

The second retry solution might be preferable as the change could be restricted to updating the spans resource, e.g. by updating `_set_request_tags` at https://github.com/DataDog/dd-trace-py/blob/v0.34.1/ddtrace/contrib/django/patch.py#L119. 

If you have success with one of these approaches, definitely start a PR and we'll work on getting the issue resolved. We'll want to add a test with `django-host` to be confident we support this use case.

**Comment by paddycarey** [comment]
I've solved this temporarily in our app by adding a new middleware (after the django-hosts middleware) that retries the resource name resolution something like so:

```
class DdtraceResourceNameMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        try:
            resolver_match = resolve(request.path_info)
            resource_name = "{0} {1} {2}".format(
                request.method, request.get_host(), resolver_match.route
            )
        except django.urls.exceptions.Resolver404:
            pass
        else:
            span = get_current_root_span()
            span.resource = resource_name

        return self.get_response(request)
```

It works fine for right now but i'd much prefer not to have to do this at all. Now that I know the approach works, it should be easier to formulate a patch that works for `dd-trace-py` upstream.

I should be able to get back to this in a few weeks to submit a proper patch, but thought it worth mentioning now in case anyone else is having a similar issue.

**Comment by majorgreys** [comment]
Thank you for sharing your workaround. We will also be looking at this sometime next week for a fix.

**Comment by brettlangdon** [comment]
@paddycarey thanks for the code!

@majorgreys and I were digging into the `django-hosts` code on Friday to figure out this was happening, and it seems that what happens is:

1. No routes are registered on the main Django app
2. When our code runs it resolves as a 404, since there isn't a view associated with the request
3. `django-hosts` middleware runs, and resolves a route for the request
4. the request is handled

`django-hosts` mostly does it things by changing the `urlconf` when processing the request starts, and then unsetting back to the original when handling the request ends.

We've talked about a few different approaches on how we can handle this, but we'll need to try a few out to see which is easiest/most reliable/etc

**Comment by brettlangdon** [comment]
@paddycarey I was able to put together a quick prototype for a solution for this problem in #1365 if you want to give it a look over.

Just as a heads up, this is one possible approach we could take, we'll need to review as a team as there are a few other directions we could go in as well.

If you had any interest in trying out this change locally let me know and I can help you get that going.

**Comment by yevhen-m** [comment]
No updates for a year now. Any chance the issue will be fixed?

**Comment by paddycarey** [comment]
Looks like this was closed over in https://github.com/DataDog/dd-trace-py/pull/1365, thanks!
