### ISSUE TITLE
Add uds_path to ddtrace.opentracer.Tracer

### ISSUE THREAD

**Issue by worldwise001** [DataDog/dd-trace-py#1274]
### Which version of dd-trace-py are you using?
0.33.0 ?

### Which version of the libraries are you using?
0.33.0

### How can we reproduce your problem?
Try setting `uds_path` when creating a `ddtrace.opentracer.Tracer`. Oh wait.

### What is the result that you get?
This nastiness:
```
ddtracer = Tracer('appname', config={'agent_hostname': None, 'agent_port': None})
set_global_tracer(ddtracer)
tracer.configure(uds_path='/path/to/datadog.sock')
```

### What is result that you expected?
This beauty:
```
ddtracer = Tracer('appname', config={'agent_hostname': None, 'agent_port': None, 'uds_path': '/path/to/datadog.sock'})
set_global_tracer(ddtracer)
```
It is not clear from the documentation how to set up the tracer here, if using unix domain sockets but not using `ddtrace-run`.

I'm only filing to set up a PR real quick. Feel free to decline both if these are irrelevant.

**Comment by brettlangdon** [comment]
@worldwise001 great catch!

I gave a review of #1275, seems tests are failing, but shouldn't take much to fix it up.
