### ISSUE TITLE
Profiler: periodic flush option

### ISSUE THREAD

**Issue by xarg** [DataDog/dd-trace-py#1281]
### Which version of dd-trace-py are you using?

ddtrace[profile]==0.35.0

### Which version of the libraries are you using?

None

### How can we reproduce your problem?

When the profiler is used like: 

```python
from ddtrace.profile import profiler

prof = profiler.Profiler()
prof.start()
do_stuff()
prof.stop()
```

### What is the result that you get?

The `prof.stop()` call is synchronous - meaning that the the events to be sent to the datadog profiling service are flushed -> sent via a blocking HTTP request.

This is not ideal because in a production multi-threaded environment this will increase the latency of the application.  

### What is result that you expected?

The `prof.stop()` call should accept a `flush=False` argument that is then passed to the scheduler which supports the `flush` argument already which is set to `True` by default. That way we can benefit from the `PeriodicThread` used here: https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/profile/scheduler.py#L28

I guess in the meantime I can subclass the `Scheduler` or `Profiler` and change the `stop` method, but I prefer to not go too deep into the customization if possible since the API might change in the future.

**Comment by xarg** [comment]
@jd do you think this could be done or is there an alternative I'm not seeing? Sorry for the ping, I saw you are the main contributor for this part and thought this might be relevant for you.

**Comment by jd** [comment]
Hey @xarg!

I actually have a PR that adds `flush=True` to `stop()` but it's not doing what you want I think: it will just not flush at all — ever.

The `Profiler` has been designed for being always on and barely stopped. I imagine that in you case you want to start/stop it regularly?

**Comment by xarg** [comment]
Thanks for your quick reply @jd. My use-case is a decorator with the profiler. I'm trying to profile a single flask view by decorating it with a start/stop for example. I don't necessarily want to profile the entire flask application. If I'm using the auto-profiler then how do I distinguish between view in the interface? Using tags perhaps? It's not entirely clear to me how to do that.

Flask is just one example, what I'm really after is celery tasks. But I would say that the goal for me is to profile a single function at a time - that I know is having some sort of performance issues because I see it in other APM transaction list.

**Comment by jd** [comment]
The profiler has been designed to be always-on. The `start` and `stop` method are merely there so you're able to control more finely the flow if you _really_ need to. 

Starting/stopping the profiler too often definitely adds more overhead and is likely to generate less interesting data.

We don't necessarily advise to profile only a part of an application. There might be interactions between e.g. threads that you're not aware of until you start profiling the whole program — and many other things. As we like to say "you don't know what you don't know", so it's better to profile everything. The UI in our product then allows you to select a particular function if you want to study it more finely.

I'd say give a try at using the always-on mode with the _auto_ approach and feel free to circle back with me and @hugokash with the limitations you encounter or use cases that are not covered yet by the profiler or the UI.

**Comment by xarg** [comment]
Will try always on then and let you know how it goes.
