### ISSUE TITLE
Feature request: encode/databases support

### ISSUE THREAD

**Issue by andrei-shabanski** [DataDog/dd-trace-py#1299]
I wonder whether you have thought about integration with [databases](https://github.com/encode/databases)?

This quite popular tool provides asynchronous API to execute SqlAlchemy queries. databases uses asyncpg, aiomysql, and aiosqlite drivers which unfortunately weren't integrated yet. So no way to trace queries at all.

What do you think of it? If you've not got a plan, can I help to implement it?

**Comment by Kyle-Verhoog** [comment]
Hi @andrei-shabanski!

This is a sweet library. We haven't thought about integrating with it yet but we'd love to have you contribute if you're up to it 😄.

**Comment by Boian** [comment]
Hi @Kyle-Verhoog , I would also be interested in this integration.  Like @andrei-shabanski mentioned databases mainly uses asyncpg, aiomysql and aiosqlite so I wonder is it more of a databases integration or would having those libraries integrated really be most of the work?

For `asyncpg` it seems as though @thehesiod has done most of the work for that here: https://github.com/DataDog/dd-trace-py/pull/398/files#diff-12aa5a0c8a8af02e143c3be78d87f3b6f88a4c54a5ac90b4b48945dcfbbfc384 I tested this code in an app and it seems to work

**Comment by murata100** [comment]
I'm waiting for integration....

In the meantime, I will put up with it

``` python
from fastapi import FastAPI
import sqlalchemy as sqla, databases
from ddtrace.ext import SpanTypes, sql as sqlx

app = FastAPI()

engine = sqla.create_engine(DATABASE_URL)
database = databases.Database(DATABASE_URL)

 @app.get("/xxx")
 async def get_xxx(
    query  = xxx.select()
    vendor = sqlx.normalize_vendor(engine.name)
    with tracer.trace('{}.query'.format(vendor), vendor, span_type=SpanTypes.SQL, resource=str(query)) as span:
        span.set_tag('sql', str(query))
        data = await database.fetch_all(query)
        ....
```

**Comment by emmettbutler** [comment]
I'm closing this issue due to its old age and lack of activity. The request for a `databases` integration is still tracked on our team's private feature request backlog.
