### ISSUE TITLE
Datadog Agent sends traces to localhost even when agent address is changed

### ISSUE THREAD

**Issue by luvpreetsingh** [DataDog/dd-trace-py#1316]
### Which version of dd-trace-py are you using?
```
ddtrace==0.34.0
```

### Which version of the libraries are you using?

```
celery==4.2.0
coreapi==2.3.3
ddtrace==0.34.0
Django==2.2
django-admin-rangefilter==0.3.7
django-extensions==2.1.5
django-filter==2.0.0
django-guid==2.1.0
django-import-export==1.0.1
django-json-widget==0.2.0
django-model-utils==3.1.2
django-prometheus==1.1.0
djangorestframework==3.8.2
djangorestframework-gis==0.13
drf-url-filters==0.5.1
elastic-apm==5.4.2
elasticsearch==6.3.0
gevent==1.4.0
gunicorn==19.8.1
hashids==1.2.0
marshmallow==2.15.3
Pillow==7.0
psycopg2-binary==2.7.4
pypng==0.0.20
PyQRCode==1.2.1
raven==6.9.0
redis==2.10.6
requests==2.22.0
splitio-client==6.2.2
```

### How can we reproduce your problem?

This issue has already been reported (#798 and #1155 ) but I think not much information was given in those issues and also not much activity has happened in that thread. If you think my issue is not useful, please close it.

I think you should have the full context of my application and how I run it, so I am going to put some information here.

This is my datadog config in settings.py,

```
# this is from base_settings.py
# I keep static content in base_settings.py which does not vary from environment to environment
DATADOG_TRACE = {
    'DEFAULT_SERVICE': 'fleet-api',
    'DEFAULT_DATABASE_PREFIX': 'fleet-api',
    'TAGS': {'name': 'fleet-api', },
}

# this is from settings.py
# I run my application using settings.py in manage.py
if DATADOG_ENABLED:
    DATADOG_APP = ['ddtrace.contrib.django']
    INSTALLED_APPS = INSTALLED_APPS + DATADOG_APP
    DATADOG_TRACE["AGENT_HOSTNAME"] = os.getenv("FLEET_API_DATADOG_AGENT_HOST", "localhost")
    DATADOG_TRACE["ENABLED"] = True
```

I am using AWS EKS version 1.14 and running my application in a pod there. The entrypoint of my container is a script. Here is that script,

```
echo "I am going to migrate db changes...."

# Keeping migrations flag based as sometimes we need to have control over running migrations but sometimes we want to run it automatically on startup.
if [ $FLEET_API_RUN_MIGRATION_FLAG == "1" ]
then
 python manage.py migrate
elif [ $FLEET_API_RUN_MIGRATION_FLAG == "0" ]
then
 echo "wait!!! no migrations to run...."
else
 echo "migration flag value invalid"
fi

# Sometimes we need to run gunicorn without datadog and sometime with datadog
echo "I am going to run server...."
if [ $FLEET_API_DATADOG_FLAG == "1" ]
then
 exec ddtrace-run gunicorn -c gunicorn.conf api.wsgi
elif [ $FLEET_API_DATADOG_FLAG == "0" ]
then
 exec gunicorn -c gunicorn.conf api.wsgi
else
 echo "datadog flag invalid"
fi
```

Also, please feel free to point out if I am doing something stupid in my settings or the start-up script.

I am adding a partial description of a running pod from my production cluster,

```
    Environment:
      FLEET_API_DATADOG_AGENT_HOST:   (v1:status.hostIP)
```

I am overriding the datadog host environment variable here. To confirm if that has been successful, I run the following command,

```
$ kubectl exec fleet-api-b7bf9778c-8snlq -c fleet-api printenv | grep FLEET_API_DATADOG_AGENT
FLEET_API_DATADOG_AGENT_HOST=172.31.107.105
```

I believe the agent address was overridden successfully. And Also, another way to confirm this is that I get all my APM stats on my datadog dashboard. So, it means it is working.

I have datadog daemonset and cluster agent launched in my AWS EKS. I have enabled APM traffic in the daemonset too. 

I have explained my setup here so I guess it should be enough to reproduce the problem. If I have missed something, please let me know.

### What is the result that you get?

If the agent address value has been overridden, I believe it should not try to send traces to `http://localhost:8126/`. But it does try to send it to `http://localhost:8126/` every once in a while.

Here is a screenshot of sentry event of the same,

<img width="1220" alt="Screenshot 2020-03-30 at 8 18 03 PM" src="https://user-images.githubusercontent.com/23127804/77926317-9f98c580-72c3-11ea-83c8-5fa57ea97eb8.png">

You can see the trend from the last 30 days and also for the last 24 hours. Mostly it comes when we do a new deployment or when a pod restarts. But those are not the only times when it occurs.

_One thing could be that it takes some time to read environment variables. But before running the server I am running the `python manage.py migrations`, which also requires reading environment variables. I have never faced any issue in that command. So this leads me to think that slow environment variables reading might not be an issue although I can be wrong._

### What is the result that you expected?

I expect the APM agent not to send traces to `http://localhost:8126/` when I have overridden the DATADOG_AGENT_HOST value.

**Comment by majorgreys** [comment]
Thank you for the detailed explanation. From the looks of it, your approach should work, though I do wonder if those modifications to your `settings.DATADOG_TRACE` are in fact being made. Some print debugging could help us confirm that those settings are what you expect them to be before the tracer is configured.

Being that you are on 0.34.0, I would encourage you to try enabling and configuring the tracer integration for Django using the new approach that was introduced in this version:

http://pypi.datadoghq.com/trace/docs/web_integrations.html#django

**Comment by luvpreetsingh** [comment]
Thank you @majorgreys for the quick response and the suggestion.

I would like to add that we had recently switched to `0.34.0`. Earlier we were on `0.24.0`. Even then this issue was there.

About the settings.DATADOG_TRACE thing, I'm not sure how to do the _print debugging_ you are referring to? Can you please let me know how can I help you get the debug statements you need?

**Comment by majorgreys** [comment]
> About the settings.DATADOG_TRACE thing, I'm not sure how to do the _print debugging_ you are referring to? Can you please let me know how can I help you get the debug statements you need?

Sure, what I meant was printing (or logging) the values of that dictionary to inspect it. You can also enable the capturing of the tracer logs as described in the Django integration documentation. If you set the environment variable `DATADOG_TRACE_DEBUG=true` and the log level to debug for your traced application, you should see debug messages from the tracer as it is initialized and configured.

**Comment by Kyle-Verhoog** [comment]
@luvpreetsingh please let us know if you're still seeing this issue. We'll re-open and investigate!
