### ISSUE TITLE
How to run ddtrace-run with flask app in AWS elastic beanstalk?

### ISSUE THREAD

**Issue by maximillianus** [DataDog/dd-trace-py#1335]
I am trying to run ddtrace-run in AWS elastic beanstalk environment. As far as I know, the steps to run ddtrace according to the [docs](https://docs.datadoghq.com/tracing/setup/python/) in python's flask are:
1. Install ddtrace. `pip install ddtrace`
2. Include `ddtrace-run` in entry command. `ddtrace-run python app.py`

But in elastic beanstalk, we cannot configure the entry command as usually the app is zipped and uploaded to beanstalk and there is a pre-set entry command run from beanstalk. How to add `ddtrace-run` for beanstalk deployment?

**Comment by Kyle-Verhoog** [comment]
Hi @maximillianus, since you can't use `ddtrace-run` you can instead use `ddtrace` manually with the following code:

```python
from ddtrace import patch_all
patch_all()
```
for things to work smoothly we recommend doing this as soon as possible in your application, preferably before importing other libraries.

Let me know if this works! 🙂

**Comment by maximillianus** [comment]
Hi @Kyle-Verhoog !

Thanks for the response! I have seen that option of running it too but I am just wondering if there's some way we can add the `ddtrace-run` command when running it with elastic beanstalk.

Will try that first then. 👍

**Comment by Kyle-Verhoog** [comment]
Ah okay, I see. I'm not familiar with elastic beanstalk myself.

A quick search seems to show that if you're using docker that you just have to specify an `Entrypoint` in your configuration. https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/single-container-docker-configuration.html

But again, I'm not familiar with the platform 😄

**Comment by maximillianus** [comment]
ah yes, using Docker is another option but my deployment method is not using Docker 😅 , so I can't use that as well.

Let me try using what you suggested first 😄 .

As long as this snippet below runs what `ddtrace-run` is running, I think I should be pretty good.
```
from ddtrace import patch_all
patch_all()
```

**Comment by maximillianus** [comment]
@Kyle-Verhoog 
It seems to work using the patch_all() and it is sending metric for various libraries I used including aws sns, flask, and postgres. Can I disable some of those libraries by passing it to patch_all's arguments?

 I am also still curious about running using `ddtrace-run`. I saw in [here](https://github.com/DataDog/dd-trace-py/blob/master/docs/advanced_usage.rst#id112), we can add ddtrace-run to uWSGI and Gunicorn.

May I know how to do it with `apache + mod_wsgi`? (AWS beanstalk is using `apache + mod_wsgi`)

Thanks!

**Comment by Kyle-Verhoog** [comment]
Hi @maximillianus, sorry for the delayed reply. Glad to hear it worked.

Yes you can disable specific libraries with `patch_all` eg. `path_all(flask=False)`.

You should be able to use `ddtrace-run` with `mod_wsgi`. 

Let me know if you have further questions 🙂. I think we can close out this issue otherwise.

**Comment by maximillianus** [comment]
Hi in fact I cant use it with mod_wsgi. Would like to know how. 🙏🏻

**Comment by Kyle-Verhoog** [comment]
Hmm interesting. We don't test with it but I thought it would work. Are you seeing any errors or it just doesn't work?

**Comment by maximillianus** [comment]
Sorry I kinda missed the notification for your reply. I simply don't know how to make it work in the first place. Using mod_wsgi, the flask app is not run just by executing the entry file in terminal like `python3 app.py` for example. If I understand it correctly, there is this daemon service that runs the webserver and reads configuration from a config file.

I don't know how to integrate the ddtrace to that service.

**Comment by Kyle-Verhoog** [comment]
Ah okay. I'm not familiar with `mod_wsgi` and assumed it just forwarded on the python path and variables required to bootstrap the tracing library. Looks like a different approach might be required here.

I opened up a feature request/investigate issue here: #1431 to track it.

Is it okay to close out this issue?

**Comment by maximillianus** [comment]
Thanks Kyle! It's OK to close this issue.
