### ISSUE TITLE
logging in `ddtrace.context.Context` causes deadlock

### ISSUE THREAD

**Issue by zhammer** [DataDog/dd-trace-py#1337]
### Summary
`Context.close_span` logs out any unfinished child spans when the parent span closes. if log injection is enabled, the patched logger [tries to get the current span](https://github.com/DataDog/dd-trace-py/blob/682f9d9fdf8a5ad4285cc6adc31e8177599f5d0a/ddtrace/contrib/logging/patch.py#L38) which [tries to grab the same lock](https://github.com/DataDog/dd-trace-py/blob/682f9d9fdf8a5ad4285cc6adc31e8177599f5d0a/ddtrace/context.py#L92-L100) that `Context.close_span` is already holding.

https://github.com/DataDog/dd-trace-py/blob/682f9d9fdf8a5ad4285cc6adc31e8177599f5d0a/ddtrace/context.py#L125-L147

### Which version of dd-trace-py are you using?
`0.36.0`

### How can we reproduce your problem?
run `DATADOG_TRACE_DEBUG=true DD_LOGS_INJECTION=true ddtrace-run python script.py`
```py
# script.py
import ddtrace

def main():
    with ddtrace.tracer.trace("main") as span:
        unfinished_span = ddtrace.tracer.trace("unfinished_span")
        # unfinished_span.finish()  # <-- if this runs, deadlock will not occur

if __name__ == "__main__":
    main()
```

### What is the result that you get?
script deadlocks and hangs

### What is the result that you expected?
unfinished spans don't deadlock code

### Notes
possibly similar to https://github.com/DataDog/dd-trace-py/issues/1003

**Comment by zhammer** [comment]
put up #1338 as a possible fix for this

**Comment by majorgreys** [comment]
@zhammer I have reproduced this and will review your PR shortly. Thank you for reporting this with a reproducible test!

https://gist.github.com/majorgreys/8d1d1ed6f47f8b50bdc070bfa93df325

**Comment by zhammer** [comment]
@majorgreys ooh, multi-file gists! times have changed :)
