### ISSUE TITLE
Django 1.6 support

### ISSUE THREAD

**Issue by mattrobenolt** [DataDog/dd-trace-py#134]
From a quick glance, the only problem is the dependency on `django.apps` which should be simply to work around.

I was going to work through a PR for this.

**Comment by palazzem** [comment]
Hey @mattrobenolt thanks for reaching out! Yes actually we're targeting only versions that are still supported by the Django community so:
* Django 1.8 LTS (EOL: April 2018)
* Django 1.9 (EOL: April 2017)
* Django 1.10 (EOL: December 2017)

Basically, all versions that are listed in the [Django download page][1] are (and will be) supported by our Python client. For this reason we can't ensure support for Django 1.6, but feel free to submit a PR! We can support it in a best-effort if the PR doesn't impact the current integration.

Anyway, thank you a lot for contributing with your code! Let us know when your PR will be ready 😃 

[1]: https://www.djangoproject.com/download/

**Comment by mattrobenolt** [comment]
Yup, totally understandable. We, [Sentry](https://github.com/getsentry/sentry), are still stuck on 1.6.11 probably forever, but are excited to try this out. :)

**Comment by palazzem** [comment]
That's awesome! feel free to ask any detail about the Python integration. And let us know how is going with the PR. Having a generic way to support even versions pre ``AppConfig`` could be useful to other users 👍

**Comment by palazzem** [comment]
@mattrobenolt was #136 enough to close this issue? Anyway thanks for the PR!

**Comment by mattrobenolt** [comment]
Not entirely sure yet. There are other pieces that would need 1.7, but not sure if we're using them or if they're needed. I'll check today.

**Comment by palazzem** [comment]
Wonderful! I'll keep this issue opened so!

**Comment by palazzem** [comment]
At the moment Django 1.6 support is best-effort, and in our current roadmap, we don't have a plan to include Django 1.6 in our supported versions.

I'm going to close this issue but feel free to re-open if you want to work on it again!
Thanks a lot for all the initial work!

**Comment by ebpitts** [comment]
I just wanted to pop in and say thanks for this work! We had to handle out own initialization since we're pre-AppConfig, but otherwise the heart of the Django integration has worked well for us on 1.5.

**Comment by mattrobenolt** [comment]
Hey @ebpitts.
