### ISSUE TITLE
How to trace Django management commands?

### ISSUE THREAD

**Issue by casimir** [DataDog/dd-trace-py#1341]
### Which version of dd-trace-py are you using?
0.37.0

### Which version of the libraries are you using?
Django 1.11.23

### How can we reproduce your problem?
After following the [Django setup tutorial](http://pypi.datadoghq.com/trace/docs/web_integrations.html#django) run a Django command. For exemple `python manage.py shell`.

Note that the result is the same for the `patch_all()` and the `ddtrace-run` methods. Also it's working perfectly for the web part (`django` service).

### What is the result that you get?
For this run I can only see traces for `defaultdb` and `postgres`.

### What is the result that you expected?
I would at least expect a trace for the `Command.handle` execution with spans from python, `defaultdb` and `postgres`, most likely in the `django` service by default.

I went exploring the [source code](https://github.com/DataDog/dd-trace-py/tree/master/ddtrace/contrib/django) for the Django integration but I am not sure if I don't understand how it's work very well or if the tracing of managements commands are supported. Hence this issue.

**Comment by majorgreys** [comment]
While we don't have an auto-instrumentation for the management commands, you can manually instrument them following the [documentation](http://pypi.datadoghq.com/trace/docs/basic_usage.html#manual-instrumentation). Remember you will need to set a service name for the entry point for your commands.

For example:

```python
"""Django's command-line utility for administrative tasks."""
import os
import sys
import ddtrace

@ddtrace.tracer.wrap("main", service="django-manage")
def main():
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'mysite.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()
```

**Comment by casimir** [comment]
I finally grok the logic behind the tracer. Your example was a big help. Thanks.

**Comment by caleb15** [comment]
The example above was a great starting point, thanks! It just needs a small change to be 100% working:

```python
#!/usr/bin/env python
import os
import sys

import ddtrace

if __name__ == "__main__":
    if len(sys.argv) > 1:
        resource_name = ' '.join(sys.argv[1:])
    else:
        resource_name = ''
    root_span = ddtrace.tracer.trace('main', 'django-manage', resource_name)
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "mysite.settings")
    from django.core.management import execute_from_command_line
    try:
        execute_from_command_line(sys.argv)
    finally:
        root_span.finish()
```

By setting the resource name each management command shows up as a seperate resource. Otherwise you end up with different commands all showing up as the same "main" resource.

Here's an example of how it looks:

![image](https://user-images.githubusercontent.com/46505081/124185851-5a3be880-da70-11eb-8c76-773d64c94a04.png)

**Comment by amacfie** [comment]
@majorgreys out of curiosity, why does the span in your solution not become the parent of all request spans if we do `manage.py runserver`?

**Comment by majorgreys** [comment]
@amacfie These manage cli commands would be performed in a separate process than the server handling requests. Can you provide an example of where you would have expected a parenting relationship to the span started during the execution of the manage command?

**Comment by amacfie** [comment]
@majorgreys it works as I was hoping it would, I was just curious, thanks
