### ISSUE TITLE
feature proposal: user sitecustomization.py directory env var

### ISSUE THREAD

**Issue by zhammer** [DataDog/dd-trace-py#1344]
hey ddtrace team. i've been thinking that a clean way to add some custom setup across all our python apps would be to add a `sitecustomize.py` that'd be called by `ddtrace-run` in the following codeblock:
https://github.com/DataDog/dd-trace-py/blob/872a8880e942bf76296b83c703ca00a7e3c3eded/ddtrace/bootstrap/sitecustomize.py#L124-L141

there are a few issues with this:
1. we'd need to update `PYTHONPATH` to point somewhere in our app code directory for `sitecustomize.py` to be part of `sys.path`
    * (some of our jobs have `PYTHONPATH=.` but not all)
2. if `PYTHONPATH=.` and `./sitecustomize.py` exists, `./sitecustomize.py` will run both when `ddtrace-run` runs before [os.exec](https://github.com/DataDog/dd-trace-py/blob/872a8880e942bf76296b83c703ca00a7e3c3eded/ddtrace/commands/ddtrace_run.py#L69)ing *and* in the bootstrapped python app

i'm thinking it may be nice to have a `DD_USER_SITECUSTOMIZATION_DIR` env var that, if present, would be where `ddtrace-run` looks for a user `sitecustomization`. e.g. `DD_USER_SITECUSTOMIZATION_DIR=./datadog_config/`

curious what folks think of this. if you don't want to mess with sitecustomization, is there anything on the roadmap to add setup hooks to `ddtrace-run`?

**Comment by zhammer** [comment]
the code change needed here would be super light and i'd be happy to put up a PR to try this out.

basic idea is:
```diff
*** before.py	2020-04-07 16:28:53.000000000 -0400
--- after.py	2020-04-07 16:28:45.000000000 -0400
***************
*** 19,24 ****
--- 19,26 ----
      else ""
  )
  
+ USER_SITECUSTOMIZATION_DIR = os.environ.get("DATADOG_USER_SITECUSTOMIZATION_DIR", None)
+ 
  if config.logs_injection:
      # immediately patch logging if trace id injected
      from ddtrace import patch
***************
*** 131,136 ****
--- 133,141 ----
      if bootstrap_dir in path:
          path.remove(bootstrap_dir)
  
+     if USER_SITECUSTOMIZATION_DIR:
+         path.insert(0, USER_SITECUSTOMIZATION_DIR)
+ 
      try:
          (f, path, description) = imp.find_module("sitecustomize", path)
      except ImportError:
```

**Comment by zhammer** [comment]
also for some context, some things i'd want to do in a custom `sitecustomize.py` / init script are:
1. setup custom client integrations / patches
2. if the current invocation is a cron job, start a trace at start of run and setup `atexit` handler to close trace
3. add filters to the tracer

**Comment by majorgreys** [comment]
I think this makes sense as a PR for adding a user-specified directory to the `ddtrace-run` bootstrap. 

@zhammer: Want to get it started and we can iterate on this from there?

**Comment by zhammer** [comment]
@majorgreys will do

**Comment by Kyle-Verhoog** [comment]
I'm not sure if something changing in the meantime([?](https://github.com/DataDog/dd-trace-py/pull/1823)) or not but this functionality as far as I can tell does exist already as ddtrace will call the original sitecustomize before and after the app is run. 

```
/tmp ❯❯❯ cat sitecustomize.py
print("test")
/tmp ❯❯❯ PYTHONPATH=. ddtrace-run python -c ""
test
test
```

Also given that there hasn't been more activity here I think we can close it for now. @zhammer please feel free to reopen if I'm wrong here 🙂
