### ISSUE TITLE
Feature Request: Configurable Distributed Tracing Headers

### ISSUE THREAD

**Issue by nathan-knight** [DataDog/dd-trace-py#1362]
`dd-trace-go` provides the option to configure which headers contain the trace and parent span ids for the propagator (https://godoc.org/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer#PropagatorConfig). 

It would be really useful to have the ability to configure which headers `HTTPPropagator` uses to inject/extract the trace and span ids. This could be via an environment variable. For our particular use case we want this to be usable for Flask but I am sure it could be helpful for other integrations.

An alternative could be the ability to swap out the propagator that Flask uses so we can configure it ourselves.

Thank you!

**Comment by jfmyers9** [comment]
Has any thought been given to this issue?

This is something that would be very helpful when integrating with other OpenTracing/OpenTelemetry compatible systems.

**Comment by emmettbutler** [comment]
Selecting distributed tracing header style is now supported via `DD_TRACE_PROPAGATION_STYLE`, documented [here](https://github.com/DataDog/dd-trace-py/blob/1a3c4243184c34cf8ab02e2d409e4f017514a792/docs/configuration.rst#L294).
