### ISSUE TITLE
Django db tracer does not apply the django dot prefix.

### ISSUE THREAD

**Issue by JTCunning** [DataDog/dd-trace-py#139]
`django.cache` applies `django.` [here](https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/django/cache.py#L54)
`django.template` applies `django.` [here](https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/django/templates.py#L35)

yet `django.db` does not apply the `django.` prefix, which creates a service per database defined, and duplicates a large amount of data that the `postgres` patcher already collects.

Slide into my DMs on Datadog's official Slack to get some example links.

**Comment by palazzem** [comment]
Thank you for pointing that. Will take a look during the day so that we can triage/address this issue!

**Comment by brettlangdon** [comment]
Closing this ticket due to it's age, but we have work planned for re-working the Django integration and changes to the database tracing will be included.
