### ISSUE TITLE
Profile exporter crashes when DD_VERSION is used

### ISSUE THREAD

**Issue by kjagiello** [DataDog/dd-trace-py#1392]
The profile exporter is crashing due to `DD_VERSION` not being encoded before generating the export request. Looking at the code the same applies probably to `DD_ENV` as well.

Lines missing `.decode("utf-8")`: https://github.com/DataDog/dd-trace-py/blob/6a14a9ba75a6866d968ddf0eb84b8fee5bd3f49c/ddtrace/profiling/exporter/http.py#L144-L150

**Sentry traceback**
![image](https://user-images.githubusercontent.com/74944/80689205-43e17800-8acd-11ea-9068-87b76e106660.png)

### Which version of dd-trace-py are you using?

0.37.0

### Which version of the libraries are you using?

N/A

### How can we reproduce your problem?

```
DD_VERSION=foobar pyddprofile ...
```

**Comment by ab** [comment]
I ran into this TypeError involving str / bytes confusion as well.

Only found this issue from git blame when I tried to fix it myself, so I'm adding some more google-able content with this comment.

```
ERROR "Error while exporting 9910 events" scheduler.py:44(ddtrace.profiling.scheduler)
Traceback (most recent call last):
  File "ddtrace/profiling/scheduler.py", line 40, in flush
    exp.export(events, start, self._last_export)
  File "ddtrace/profiling/exporter/http.py", line 196, in export
    content_type, body = self._encode_multipart_formdata(fields, tags=self._get_tags(service_name),)
  File "ddtrace/profiling/exporter/http.py", line 122, in _encode_multipart_formdata
    + b"\r\n--%s--\r\n" % boundary
  File "ddtrace/profiling/exporter/http.py", line 114, in <genexpr>
    for tag, value in tags.items()

TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'str'
```
