### ISSUE TITLE
Customizable top-level django resource name

### ISSUE THREAD

**Issue by tredzko** [DataDog/dd-trace-py#1404]
In newer versions of ddtrace (with #1161 or later, so I believe 0.34.0 based on the milestone), there was a change introduced where the method was placed in the resource name, and for Django versions 2.2+, root resource names for Django were changed to be the url regex. You can find that in the [patch file for Django](https://github.com/DataDog/dd-trace-py/blame/master/ddtrace/contrib/django/patch.py#L349).

This change means that each method and each regex (in the case that a view has more than one regex, like detail/list) is showing when rolling up resources under a service. Here's an example:

### Prior to #1161
![asd0](https://user-images.githubusercontent.com/8700540/81112143-33c20200-8eec-11ea-973a-8902edcb917e.png)

### After #1161
![asd1](https://user-images.githubusercontent.com/8700540/81112150-36245c00-8eec-11ea-90a7-73dcf089a40e.png)

I was able to work around this by adding in some configuration options on my own branch, but I think others may also want to keep the previous resource naming scheme, even if they are upgrading ddtrace or Django.

Thoughts on either adding two boolean config options (to turn off regex and/or turn off the method respectively) or possibly adding a string with preexisting format names (like `"{method} {handler} {path}"`)?

#### ddtrace version
`0.37.0`
#### Django version
`3.0.x`

**Comment by Kyle-Verhoog** [comment]
Hi @tredzko!

Thanks for bringing this up. The change was made to be consistent with our existing integrations as well as across the APM product where the method and path are used for the resource name.

I do think that using the regex is not very human readable, especially at a glance. So there is room for improvement here. I do also see the merits in using the django view/function handler too.

Do you mind providing your reasoning for wanting to revert to the older resource names? That might help give us some more context to think about 🙂.

**Comment by tredzko** [comment]
Hey @Kyle-Verhoog !

Having the method in the resource means we have multiple entries for the same view, even ones that have no other methods we really care about (like `OPTIONS`). We also like the old style, so we want to make sure our new spans are at least aligned with our historical data for comparison on performance and traffic.

The main one is definitely readability though. It can be difficult to know what view is being used without going into the `urls.py` or digging into the spans to get the view, which (to my knowledge) requires opening the resource and opening up a trace from it (at least from a services perspective).

**Comment by Kyle-Verhoog** [comment]
Gotcha. Thanks for the feedback! I agree for Django that the view is more useful than a particular route or path.

Your PR #1415 does seem like a good solution.

I'll follow up with the team. 😄
