### ISSUE TITLE
Profiling causing gunicorn timeout (flask app)

### ISSUE THREAD

**Issue by youssefNM** [DataDog/dd-trace-py#1414]
### Which version of dd-trace-py are you using?

```
ddtrace[profiling]==0.37.0
```

### Which version of the libraries are you using?

```
flask==1.1.2
gunicorn==20.0.4
ddtrace[profiling]==0.37.0
datadog==0.36.0
```

### How can we reproduce your problem?
I'm using a simple hello world app flask application for the demonstration of this problem but the issue is happening also when we tried to integrated the profiling with our Flask project, i thought the issue was related to our project code but in this demo proved that it's a general issue, in `wsgi.py` you can add :

```
import ddtrace.profiling.auto
```

my gunicorn config is the default "simple" one : 

```
gunicorn --bind 0.0.0.0:8000 wsgi:app
```
### What is the result that you get?

```
docker run -p 8000:8000 flask/hello-world
[2020-05-07 15:17:06 +0000] [6] [INFO] Starting gunicorn 20.0.4
[2020-05-07 15:17:06 +0000] [6] [INFO] Listening at: http://0.0.0.0:8000 (6)
[2020-05-07 15:17:06 +0000] [6] [INFO] Using worker: sync
[2020-05-07 15:17:06 +0000] [9] [INFO] Booting worker with pid: 9
[2020-05-07 15:17:52 +0000] [6] [CRITICAL] WORKER TIMEOUT (pid:9)
[2020-05-07 15:17:52 +0000] [9] [INFO] Worker exiting (pid: 9)
[2020-05-07 15:17:52 +0000] [13] [INFO] Booting worker with pid: 13
```

### What is the result that you expected?
When i removed the auto profiler the app works and got the response.
Also strangely when using the "manual" profiler 

```
from ddtrace.profiling import Profiler

prof = Profiler()
prof.start()
``` 

The app works as expected and i get profiling events in my Datadog account, so my believe is that the auto profiler causes a lock somewhere in its code resulting in Gunicorn workers timeout.

**Comment by alecbrick** [comment]
I'm experiencing this issue as well with `ddtrace==0.41.0`. Is there anything we can do about this?

**Comment by jd** [comment]
Thanks for the report!
@youssefNM could you share your minimal test case to reproduce this? That'd be helpful.

Is pressing C-c giving you a backtrace or something of where it'd be stuck?

**Comment by noelhollingsworth** [comment]
We have the same issue - Python 3.8.5, ddtrace==0.43.0, uwsgi==2.0.19.1 Using prof.start() within the uwsgi initial process also fails. This is using uwsgi to spawn 10 workers, the workers all spawn, but are immediately unresponsive.

**Comment by russellcardullo** [comment]
I've run into something similar where my flask application hangs when enabling automatic profiling.  In my case it seems to happen when all of the following are true:

* Running inside a Docker container
* Using gunicorn with gevent
* Importing a library that uses the C library *after* enabling automatic profiling

If I change any of the conditions above it works for me.

I've created a gist here with a reproducer: https://gist.github.com/russellcardullo/c7f0e16f392dc2b393b61cfbc6b490de

**Comment by jd** [comment]
Thanks for the detailled report @russellcardullo!
This is only a problem with the `gevent` worker class. This happens because the `patch_all` from gevent is called too late *after* the profiler has started.

You need to use something like this in Flask for example:

```
@app.before_first_request
def start_profiler():
    import ddtrace.profiling.auto
```

That should work fine.

I'll check if we can detect this and report it and improve the documentation on our side.

**Comment by jd** [comment]
This is actually not true. My workaround works, but it has nothing to do with gevent monkey patching.
It's just `find_library` that deadlock somehow on Linux (Darwin is fine) when the profiler is loaded.

I'm still digging into this.
