### ISSUE TITLE
pymongo: Incomplete trace

### ISSUE THREAD

**Issue by LetzNico** [DataDog/dd-trace-py#1442]
### Which version of dd-trace-py are you using?

```
$pip3 freeze | grep ddtrace
ddtrace==0.37.1
```

### Which version of the libraries are you using?

```
$pip3 freeze | grep pymongo
pymongo==3.10.1
```

### How can we reproduce your problem?

```
import pymongo
from ddtrace import patch_all; patch_all()

ip = "xxx.xxx.xxx.xxx" # With a local server the problem will be difficult to notice as establishing a TCP connection on localhost is nowhere as slow as establishing it across the Internet
client = pymongo.MongoClient(ip, 27017)
with ddtrace.tracer.trace('QueryMongoMetadata', service='xxx', resource='GetMongoMetadatas'):
    server_info = client.server_info()                                                                     
```

produces

![image](https://user-images.githubusercontent.com/6052976/82158395-e3518980-9887-11ea-9ef1-0848a0f08d98.png)

### What is the result that you get?

In this example, when calling `client.server_info()`, pymongo silently establishes a new TCP connection. It then uses the newly created socket to perform the actual `buildinfo` request. This can be verified by capturing network while running that python snippet.
Only the second request is traced by ddtrace. The establishment of the new TCP connection is not. Still, it can take some time, as in this example. This behavior can lead to misleading traces like this one: in this example, the network calls traced by ddtrace only represent 1/5 of the total time taken by pymongo's public function,`server_info()`.

### What is the result that you expected?

I do not know if this is a known behavior. It could also be a regression (cf. 4yo comment [here](https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/pymongo/client.py#L56), the internal API may have changed).
In any case, I was wondering if you would accept pull requests for tracing new connections or at least for new connections established while calling a traced, public pymongo function.

It looks like pymongo is handling its sockets with `Pool` instances, attached to `Server` instances. Since ddtrace already traces `Server` instances (https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/pymongo/client.py#L86), I believe it could be done easily by tracing some functions of `Server`'s pool instances.
Another option could be to trace the [already overridden `get_socket`](https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/pymongo/client.py#L169) function of the `Server` instance. It looks like this function's role is to give a working socket to pymongo (using the appropriate `Pool`) so it can query the server. It would be faster to trace it. The downside would be that ddtrace would generate a trace both in the case where `get_socket` creates a new socket (good) and in the case where `get_socket` picks an already existing one (bad?).

Would you accept a contribution on that issue?

**Comment by Kyle-Verhoog** [comment]
Hey @LetzNico!

Thanks for the write-up! I'm not sure if this is a regression or not either, pymongo's one of our oldest integrations.

Without looking into pymongo, both of your approaches seem good. The `Pool` approach may give more visibility not just into this particular case, which would be great (also more work). We might want to avoid doing the `get_socket` approach if `get_socket` is called a bunch, which I feel like it could be, otherwise it might be a quick and easy solution.

We'd love to accept a contribution if you're up for it! 😄

**Comment by LetzNico** [comment]
Hey @Kyle-Verhoog !

I have started working on that issue. I'm considering the Pool patching approach. Still, I am not familiar with ddtrace internals, particularly `ObjectProxy`. I have been hitting my head on a problem with context managers used by pymongo.
Below is a minimal example.

```
from ddtrace.vendor.wrapt import ObjectProxy
import contextlib

class Pool():
    @contextlib.contextmanager
    def parent_function(self):
        # do some stuff
        yield self.target_function()                                                                                                                                         
        # do some stuff

    def target_function(self):
        print("original target")
        return 1

class TracedPool(ObjectProxy):
    def __init__(self, pool):
        super(TracedPool, self).__init__(pool)

    def target_function(self):
        print("overriden target")
        return 2

pool = Pool()
traced_pool = TracedPool(pool)
# stuff
with traced_pool.parent_function() as blablabla:
    pass
# stuff
```

The function I want to trace is `target_function`, called by `parent_function`. However, since `parent_function` is decorated by a `contextmanager`, its return value is a `contextlib._GeneratorContextManager`.
The annoying part is that the function and the arguments referenced by the `contextlib._GeneratorContextManager` are the original `target_function` and `Pool` objects. Thus, even though `target_function` is overriden in `TracedPool`, the original `target_function` will be executed.

Is it a known issue? I will continue working but if you have some insights, that would be greatly appreciated!

**Comment by Kyle-Verhoog** [comment]
Thanks for starting work on it!

Ahhh I see. Surprisingly, I don't think I've personally come across where we've had to instrument a `@contextlib.contextmanager` and don't think we do it anywhere in the tracer.

I think the advice I'd give is to not go the `ObjectProxy` approach. With our newer integrations we're instead wrapping the methods individually. See the [flask integration](https://github.com/DataDog/dd-trace-py/blob/a6df2696bc906758c027be3257deabce344fb5a9/ddtrace/contrib/flask/patch.py#L56-L77) for an example of this. This might make things a bit more straightforward. Let me know if you have any questions about this approach.

That is strange that it has the original references 🤔. Darn, the context manager decorator might be the reason for that... Might have to think about that one.

Do you have a develop branch you could share? Feel free to open up a draft PR I'd love to take a look. 🙂

**Comment by LetzNico** [comment]
Hey there!

Your advice is spot on, wrapping method individually made things way simpler.

I've pushed a little something: https://github.com/DataDog/dd-trace-py/pull/1455. Considering how the tests failed, it looks like we are indeed generating traces.

If you could give me feedback, that would be greatly appreciated, especially on the following topics:
- What could be a good approach to test the new trace?
- Are the tags correct? Is the way I instanciate the pin correct to?
- To make the old tests pass, I'm considering dropping from the spans retrieved by the writer all "tcp connect" spans. That would mean, for example, adding a list comprehension like `spans = [span for span in spans if span.name in ("mongo_op", "pymongo.cmd")]` after [this line](https://github.com/DataDog/dd-trace-py/blob/master/tests/contrib/pymongo/test.py#L281). Do you think it is a good idea? If not, can you recommend me another approach?

Also, I've dropped a comment in the PR regarding that point but do you think we should migrate all of the integration from `ObjectProxy` to the new wrapping method?

By advance, thank you.

**Comment by Kyle-Verhoog** [comment]
:+1: I'll comment on the PR to address your questions 🙂

**Comment by LetzNico** [comment]
Great! It's pretty much ready for final review, I'd just need you to check a comment I've made: https://github.com/DataDog/dd-trace-py/pull/1455#discussion_r438097352

**Comment by LetzNico** [comment]
Hey there!

Any news on this? :slightly_smiling_face: (@Kyle-Verhoog ?)

By advance, thanks!

**Comment by Kyle-Verhoog** [comment]
Hey @LetzNico!

Sorry about that - been quite busy! I'll try to take a look today still 🙂
