### ISSUE TITLE
Support traces for elasticsearch7

### ISSUE THREAD

**Issue by yatishb** [DataDog/dd-trace-py#1444]
Hi 👋, our team is using multiple versions of elasticsearch in our codebase and in order to maintain backward compatibility have defined `elasticsearch7` to talk to the ES 7 cluster. I noticed that calls to the ES7 cluster don't create spans. I'm suspecting it has something to do with https://github.com/DataDog/dd-trace-py/blob/v0.38.0/ddtrace/contrib/elasticsearch/patch.py#L16.

Is this something that's on the team's roadmap?

I'm using v0.14.0 of ddtrace-py.

And these are the elasticsearch related dependencies in my environment:
```
elasticsearch==2.4.1
elasticsearch-dsl==2.2.0
elasticsearch7==7.6.0
elasticsearch7-dsl==7.1.0
```

**Comment by Kyle-Verhoog** [comment]
Hi @yatishb!

We're working on getting support for elasticsearch 7 in https://github.com/DataDog/dd-trace-py/pull/1398 we hope to have it in for the `0.39` release 🙂

**Comment by yatishb** [comment]
Thanks for the update! Looking forward to it

**Comment by arianamiri** [comment]
I was wondering if there were any updates about this?  My team has also uses the elasticsearch7 library because we talk to multiple versions of elasticsearch.  It looks like there hasn't been any movement on that PR since last May.
