### ISSUE TITLE
[feature request] Track Query Params in Requests Integration

### ISSUE THREAD

**Issue by hydrosquall** [DataDog/dd-trace-py#1447]
In addition to the URL, sometimes I would also like to track the query parameters. For example, if I curl an endpoint shaped like the following fake address:

```
https://www.my-service.com/data?user=alex
```

I would like my trace to capture the `user=alex` information. Currently, my DD trace only records the `https://www.my-service.com/` portion. This would be helpful to me because my service is reporting `500` status part of the time, but I can't reproduce them without having the right query parameters.

From what I could tell from my currently collected traces, I don't think this information is presently captured. Since it's not mentioned on the docs for the `requests` integration ( http://pypi.datadoghq.com/trace/docs/other_integrations.html#requests , I figured it was worth requesting.

**Comment by hydrosquall** [comment]
Update: currently trying to track this via setting global config, per: http://pypi.datadoghq.com/trace/docs/advanced_usage.html#query-string-tracing

**Comment by hydrosquall** [comment]
I tried setting this inside a python flask lambda handler function using the `lambda layer` integration ( https://github.com/DataDog/datadog-lambda-layer-python ), using version `Datadog-Python37:15`. 

```python
from ddtrace import config
config.requests['trace_query_string'] = True
```

It looks like this tag would already be set via https://github.com/DataDog/dd-trace-py/blob/69cd010f37e392bd73e7a9040d0b2c1fee393bc1/ddtrace/contrib/requests/connection.py#L103

However, for some reason the query strings aren't appearing in my traces .

**Comment by Kyle-Verhoog** [comment]
Hi @hydrosquall! Hmmm, your snippet should be configuring the tracer to include the query string 🤔. Not sure why that's not working.

Are you sure that your code that is enabling the query string is being run? Could you share how you're using `ddtrace` in your app?

**Comment by Kyle-Verhoog** [comment]
@Isabella-Pham let's be sure to address this with #1833

**Comment by hydrosquall** [comment]
Awesome work, thanks @Kyle-Verhoog and @Isabella-Pham ! I'll test this out in my app when the new library is released
