### ISSUE TITLE
Celery distributed tracing

### ISSUE THREAD

**Issue by lsemel** [DataDog/dd-trace-py#1471]
It'd be great if we were able to trace subtasks that are started from celery task, all as one trace.
As an example, task A queues tasks B and C, I'd like one flame graph that traces spans for tasks A, B and C under one enclosing root span.  I'd imagine there'd need to be a way to pass an ID from A to B and C, and a way for the last task to end the root span.

I tried turning on the distributed tracing option in the latest version ddtrace for Celery (v4.2.1), which looked like it could do something like this but couldn't see any effect.

**Comment by majorgreys** [comment]
@lsemel Can you confirm you are calling the tasks asynchronously, either with `delay` or `apply_async`?

**Comment by Kyle-Verhoog** [comment]
This _should_ be covered by the distributed tracing feature in the celery integration. Distributed tracing has to be configured for both the produced and consumer however which might have been the issue. Feel free to re-open if this is still a problem 🙂
