### ISSUE TITLE
where are apm metrics configured?

### ISSUE THREAD

**Issue by zhammer** [DataDog/dd-trace-py#1492]
curious where the metrics submitted from dd-trace-py are configured. we use the tornado integration and have started to switch from manually emitted status code metrics to the built-in `trace.tornado.request.hits.by_http_status`.

i'd like to filter that metric by `http.method` but `http.method` doesn't seem to be available. i tried searching through the dd-trace-py repo but can't find any references to `.hits.`

are these metrics sent from dd-trace-py, or are they computed from traces on datadog's backend?

here are the docs on "trace metrics" i could find, but they don't seem relevant: https://docs.datadoghq.com/tracing/troubleshooting/agent_apm_metrics/

**Comment by Kyle-Verhoog** [comment]
hey @zhammer!

Yes, these are computed on the backend. I'll ask around to see if we can tag them with the method 🙂

**Comment by zhammer** [comment]
Awesome, appreciate it :)

**Comment by Kyle-Verhoog** [comment]
So it's actually done in the agent: https://docs.datadoghq.com/tracing/guide/metrics_namespace/ and it doesn't look like there's a way to tag it additionally unfortunately.

I can put a feature-request in for you if you like, but otherwise, running your own metrics might make more sense for now. 🙂

**Comment by zhammer** [comment]
@Kyle-Verhoog that would be great. i think there may even be some additional work done outside of the agent: for example, [i can't find a mention of `status_class` (one of the trace tags) in the agent.](https://github.com/DataDog/datadog-agent/search?q=%2Fstatus_class&unscoped_q=%2Fstatus_class)

request is to add `http.method` to "Tags: env, service, resource, http.status_code" (from [docs](https://docs.datadoghq.com/tracing/guide/metrics_namespace/#hits))

**Comment by Kyle-Verhoog** [comment]
The metrics tagging will be moved into ``ddtrace`` soon and the original question was answered so I'm going to close this out.
