### ISSUE TITLE
Add Peewee integration

### ISSUE THREAD

**Issue by awang** [DataDog/dd-trace-py#150]
http://docs.peewee-orm.com/

**Comment by brettlangdon** [comment]
From talking with @jontonsoup, they are using PostgreSQL/`psycopg2`, and have used `patch_all`, which should have patched `psycopg2.connect`, but that didn't seem to work.

It appears that `peewee` is using `psycopg2.connect`, which should have been patched:

https://github.com/coleifer/peewee/blob/master/peewee.py#L4043

**Comment by jontonsoup** [comment]
@brettlangdon  apologies -- The trace is working, but pinning does not work. 
```
conn = DB.get_conn()
pin = Pin.override(conn, service="user-db")
```
WARNING:ddtrace.pin:can't pin onto object. skipping
Traceback (most recent call last):
  File "/Users/jonathan/src/lib/python3.5/site-packages/ddtrace/pin.py", line 96, in
 onto
    return setattr(obj, '_datadog_pin', self)
AttributeError: 'psycopg2.extensions.connection' object has no attribute '_datadog_pin'

**Comment by brettlangdon** [comment]
We have recorded better PeeWee support as a feature request internally, and will plan work to make psycopg more configurable without using a Pin.
