### ISSUE TITLE
DD_TRACE_ANALYTICS_ENABLED usage with the docker agent

### ISSUE THREAD

**Issue by cesarob** [DataDog/dd-trace-py#1531]
With the documentation it was hard to me understand how to send traces to **App Analytics**. In order words to get spans analized. 

I checked using env env var DD_TRACE_ANALYTICS_ENABLED and it didn't work. 
When setting the spans I wished to analyzed in the agent config using the environment variale DD_APM_ANALYZED_SPANS ir worked. But... it worked independently of the value of DD_TRACE_ANALYTICS_ENABLED.

So my question is... Does DD_TRACE_ANALYTICS_ENABLED has any sense when using the agent. If not I guess it should be documented somehow... 

Thanks,

-- César

**Comment by majorgreys** [comment]
The details on how to configure App Analytics are at http://pypi.datadoghq.com/trace/docs/advanced_usage.html#app-analytics.

App Analytics for web frameworks are enabled by using the global `DD_TRACE_ANALYTICS_ENABLED` whereas the other integrations have to be enabled with integration-specific environment variables `DD_TRACE_{INTEGRATION}_ANALYTICS_ENABLED`.

Can you share what value you set `DD_APM_ANALYZED_SPANS ` for the agent? 

And, is your intention to have App Analytics for one of our integrations or for some custom spans you are creating?

**Comment by Kyle-Verhoog** [comment]
Going to close this out as we haven't gotten a response. Please feel free to re-open or follow up with support @cesarob!
