### ISSUE TITLE
Psycopg2 does not wrap custom cursors

### ISSUE THREAD

**Issue by alexmac** [DataDog/dd-trace-py#154]
The patches in "ddtrace/contrib/psycopg/connection.py" provide a new default cursor that performs APM tracing, but In my code I've been using the "psycopg2.extras.DictCursor" so no tracing is performed as the patch only replaces the default, it does not wrap the provided cursor.

Any ideas on how this should be solved?

**Comment by clutchski** [comment]
can you include a snippet of how you're setting this up?

**Comment by clutchski** [comment]
Closing this one. Re-open if it's still an issue.
