### ISSUE TITLE
Support trace for pynamodb

### ISSUE THREAD

**Issue by YukSeungChan** [DataDog/dd-trace-py#1557]
Hello,

I’m using `Pynamodb` library in order to use AWS Dynamodb. `Pynamodb` uses `botocore` internally.
There is `botocore` in supported library list so I was sure that this creates spans but it seems not.

Is there any solution to create spans with `Pynamodb`?

**Comment by brettlangdon** [comment]
Hey @YukSeungChan, thanks for reaching out. We have a draft PR available for `Pynamodb` #1544 

If you have any specific use cases/patterns you use, please feel free to share them on that PR so we can be sure they are addressed when this integration is ready to release!

**Comment by kuhnboy** [comment]
I'm not sure what the scope of the changes are, but it would be nice to know what table / index the operation is being performed on, so we can look at % of time spent querying 'X' table vs other parts of the system.

**Comment by brettlangdon** [comment]
hey @kuhnboy thanks for the feedback! That is out of scope for this specific integration, but a good feature request for any of our database integrations. I'll add to our list to discuss with the team!

**Comment by Kyle-Verhoog** [comment]
@kuhnboy #1544 will include the table as a tag. With [app analytics](https://docs.datadoghq.com/tracing/app_analytics/?tab=python) you'd be able to query the pynamodb spans by the table. However, it is out of the scope of the integration to pull any dynamodb metrics if that's what you were referring to 🙂

**Comment by jhonyf** [comment]
@brettlangdon I am curious to understand why dd-trace doesn't automatically pick up the boto calls made from within pynamodb library and that we need to explicitly trace pynamodb methods, from our experience if our application uses boto then dd-trace can be automatically trace all requests made from boto.

**Comment by Kyle-Verhoog** [comment]
@jhonyf this is because pynamodb [skips](https://github.com/pynamodb/PynamoDB/blob/3cdf4ce1642438ba3157895a66682b787b57064a/pynamodb/connection/base.py#L357-L362) the method that [we instrument](https://github.com/DataDog/dd-trace-py/blob/c124e2d778d1df819fe9939eb5a4f062a867dd5f/ddtrace/contrib/botocore/patch.py#L29) in our boto integration, unfortunately 😕. Otherwise it would work.

#1544 is adding support to trace that method within pynamodb 🙂 .
