### ISSUE TITLE
new django integration: uncaught view errors cause is no longer annotated on root span

### ISSUE THREAD

**Issue by chrono** [DataDog/dd-trace-py#1570]
With the introduction of the new django integration, any uncaught errors are no longer annotated at the root span.

Previously, when a view crashed, the corresponding error would be annotated at the `django.request` span and become searchable via analytics. Now, the only annotation is `error:true` and the actual error sitting on a `django.view` span further down in the stack.

One workaround that might be suggested is to index all `django.view` spans. This isn't useful as that span has no other annotations to break down results.

Old annotation:
![old annotation](https://user-images.githubusercontent.com/76803/87975831-24d5ff00-ca9a-11ea-9135-73d5f4d185b1.png)

New annotation
![new annotation](https://user-images.githubusercontent.com/76803/87975762-0d971180-ca9a-11ea-9c40-ac8f26ee6809.png)
![image](https://user-images.githubusercontent.com/76803/87976094-88602c80-ca9a-11ea-92ff-7949db1aceca.png)

**Comment by Kyle-Verhoog** [comment]
Hi @chrono, thanks for the report. We're aware of this in the Django integration and across other language implementations and integrations.

The status right now is that we're exploring whether this is something that can be better addressed by the product itself rather than the clients. I'll try to keep this issue up to date with any progress I hear on the matter.

**Comment by Kyle-Verhoog** [comment]
In the meantime I'll see if we can regain this functionality in Django since it's definitely not ideal.

**Comment by chrono** [comment]
What's the state of this now? Once again I'm in the midst of some investigation and I cannot break down `django.request` spans by `error.type` or `error.message`.

**Comment by Kyle-Verhoog** [comment]
Hi @chronos thanks for the patience here! Since it still doesn't seem like there's a way in the product to achieve this we're going to get you a solution that you can use next week. 🙂

**Comment by wantsui** [comment]
While this is a feature request on the product side, a workaround to pass the child span's error up to the `django.request` span is to set up a [custom trace filter](https://ddtrace.readthedocs.io/en/latest/advanced_usage.html#trace-filtering) like this (please adapt to your use case): 

```python
from ddtrace import Span, tracer
from ddtrace.filters import TraceFilter
class DjangoErrorFilter(TraceFilter):
    def process_trace(self, trace):        
        if not trace:
            return trace
        else: 
            local_root = trace[0]
            for span in trace[1:]:
                if local_root.get_tag('http.status_code') == '500' and span.error == 1:
                    local_root.meta['error.msg'] = span.meta.get('error.msg')
                    local_root.meta['error.type'] = span.meta.get('error.type')
                    local_root.meta['error.stack'] = span.meta.get('error.stack')
                    break
            return trace

# Configure the interceptor:
tracer.configure(settings={'FILTERS': [DjangoErrorFilter()]})
```

Some examples of what this could look like:
1. If the error happens on the middleware, the middleware span's error will show up on `django.request` like this: https://a.cl.ly/xQu7XxlO
2. If the error happens on the view, the view span's error will show up on `django.request` like this: https://a.cl.ly/2NuqL7xK 

Let us know if you have any issues if this doesn't work!

**Comment by faudebert** [comment]
Any news regarding that topic?

If that can be of any help for someone, suggested filter does not work anymore with `ddtrace>1` since `ddtrace.Span.meta` [has been removed](https://ddtrace.readthedocs.io/en/stable/release_notes.html#remove-span-meta). We use the following filter:

```python
class DjangoErrorFilter(TraceFilter):
    def __init__(self, error_statuses=None):
        try:
            self._status_low, self._status_high = (int(s) for s in error_statuses.split('-'))
        except Exception:
            self._status_low = 500
            self._status_high = 599

    def process_trace(self, trace):
        if not trace:
            return trace

        local_root = trace[0]

        try:
            status_code = int(local_root.get_tag('http.status_code'))
        except (TypeError):
            return trace

        if status_code < self._status_low or status_code > self._status_high:
            return trace

        for span in trace[1:]:
            if span.error == 1:
                local_root.set_tags({
                    'error.msg': span.get_tag('error.msg'),
                    'error.type': span.get_tag('error.type'),
                    'error.stack': span.get_tag('error.stack'),
                })
                break

        return trace
```

**Comment by majorgreys** [comment]
Thank you for flagging this @faudebert. I opened a docs change an explanation of the issue and the updated snippet for users that need a workaround.
