### ISSUE TITLE
Misleading error message when patching boto3 instead of boto2

### ISSUE THREAD

**Issue by enamrik** [DataDog/dd-trace-py#1634]
### Which version of dd-trace-py are you using?

0.41.0

### How can we reproduce your problem?

This logic of only exporting the `patch` method if there are no missing modules:

https://github.com/DataDog/dd-trace-py/blob/20ca41bf398f9dcd753cf40943de78f124ec9516/ddtrace/contrib/boto/__init__.py#L18-L24

causes this code:

https://github.com/DataDog/dd-trace-py/blob/20ca41bf398f9dcd753cf40943de78f124ec9516/ddtrace/monkey.py#L202

to fail with this misleading error:
```
AttributeError: module 'ddtrace.contrib.boto' has no attribute 'patch'
```

### What is the result that you expected?

A message that doesn't make me think something is wrong with my configuration.

**Comment by Kyle-Verhoog** [comment]
@enamrik yes totally agreed that this is an unhelpful log. It's actually expected behaviour but since it logs a stack trace it has the appearance of an error. I opened #1631 to address this 🙂

**Comment by enamrik** [comment]
@Kyle-Verhoog awesome! Thanks.
