### ISSUE TITLE
ddtrace-run gunicorn integration : Disable specific endpoint tracing

### ISSUE THREAD

**Issue by raphaelauv** [DataDog/dd-trace-py#1688]
I'm using the `ddtrace-run gunicorn ...`

( with flask workers )

It work perfectly but I have `/health` endpoint that I don't want to trace and also do not want my APM percentile been calculated with theses specific endpoints.

How can I deactivate the tracing of theses specific endpoints  ?

Thank you

**Comment by Kyle-Verhoog** [comment]
Hi @raphaelauv! We have a trace filtering feature which can be done within the client documented [here](https://ddtrace.readthedocs.io/en/stable/advanced_usage.html#trace-filtering). This can also be accomplished from the Agent as well as described [here](https://docs.datadoghq.com/tracing/custom_instrumentation/agent_customization/?tab=mongodb#exclude-resources-from-being-collected).
