### ISSUE TITLE
Flask support doesn't call store_request_headers

### ISSUE THREAD

**Issue by gatesn** [DataDog/dd-trace-py#1707]
Flask integration doesn't store request/response headers on the span. Other integrations such as Falcon do.

**Comment by gsmethells** [comment]
@gatesn is this documented? It does not work for me in ddtrace 1.3.4 and Flask 1.1.2

<img width="504" alt="Screen Shot 2022-08-22 at 5 13 31 PM" src="https://user-images.githubusercontent.com/3286666/186027922-dc67702a-0b5b-485a-b0cd-7c00edafa5b1.png">
