### ISSUE TITLE
ddtrace should not print DATADOG TRACER DIAGNOSTIC errors unless there's a real error

### ISSUE THREAD

**Issue by ryboe** [DataDog/dd-trace-py#1715]
Thanks for taking the time for reporting an issue!

Before reporting an issue on dd-trace-py, please be sure to provide all
necessary information.

If you're hitting a bug, make sure that you're using the latest version of this
library.

### Which version of dd-trace-py are you using?
0.42.0

### How can we reproduce your problem?

Start a program with `ddtrace-run`.

### What is the result that you get?

On startup, a few of these logs are printed.
```
- DATADOG TRACER DIAGNOSTIC - Agent not reachable. Exception raised: [Errno 99] Cannot assign requested address
```
Then, `ddtrace` eventually connects to the agent and everything is fine. According to one of your engs on the Datadog public Slack, these logs are normal and common.

If this isn't an error, it shouldn't be logged as an error. These logs could be printed at the DEBUG or INFO level, or your could omit them entirely and only log after the connection retry loop gives up.

### What is the result that you expected?

When everything is configured correctly, `ddtrace` should start without errors.

**Comment by espears1** [comment]
I would suggest this deserves the label 'bug' and not 'enhancement.' Many types of workflows can require exit behavior or error behavior when error logs are detected. For example, if you are working with a tool like Sentry (which _must_ be defined globally across all Python logging), then these errors can and often do generate huge volumes of spurious Sentry alert messages. Some workflows that rely on e.g. manipulating stdin, stdout and stderr for an interactive Docker container may detect something on stderr and be required to exit, or add unusual workarounds to detect this particular log message and then try to determine if it's occurring correctly or incorrectly in a given case.

**Comment by Kyle-Verhoog** [comment]
Thanks @ryboe, @espears1, we changed these start-up diagnostic logs to be disabled by default in v0.45 (#1717). I had forgotten to circle back here to close out the issue.

The logs were well-intended but due to the current implementation it's impossible to know when the tracer configuration is complete and hence they were output for the initial configuration (which may fail) as well as for any additional configuration.

We definitely appreciate the feedback 🙂
