### ISSUE TITLE
Django ASGI capture `django.http.response.Http404` as error

### ISSUE THREAD

**Issue by bertonha** [DataDog/dd-trace-py#1791]
### Which version of dd-trace-py are you using?
0.43.1

### DD-agent version
7

### Which version of the libraries are you using?
```
asgiref==3.3.1
ddtrace==0.43.1
Django==3.1.3
gunicorn==20.0.4
uvicorn==0.12.2
```

asgi.py
```
import os

from django.core.asgi import get_asgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'Grasp.settings')
django_asgi_application = get_asgi_application()

from ddtrace.contrib.asgi import TraceMiddleware  # noqa

application = TraceMiddleware(django_asgi_application)
```

settings.py
```
import ddtrace

ddtrace.tracer.configure(hostname='127.0.0.1')
ddtrace.config.django['service_name'] = 'my-service'
ddtrace.config.django['analytics_enabled'] = True
ddtrace.config.asgi['analytics_enabled'] = True
ddtrace.config.asgi['service_name'] = 'my-service'
ddtrace.tracer.set_tags({'env': 'production'})
ddtrace.patch_all()
```

running the server
```
gunicorn -w 4 -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker myapp.asgi:application
```

### How can we reproduce your problem?
Just do a request to where it should return 404 the error appears on APM traces

<img width="806" alt="Screenshot 2020-11-11 at 16 47 49" src="https://user-images.githubusercontent.com/1225902/98833409-42aae380-243e-11eb-965b-933e72dbea99.png">

**Comment by Kyle-Verhoog** [comment]
@bertonha thanks for reporting! This seems like it's being done implicitly by our DRF integration (it'll just report any exception as an error). I'll schedule this to be fixed in v0.45.
