### ISSUE TITLE
Unpinned version of intervaltree

### ISSUE THREAD

**Issue by alinagol** [DataDog/dd-trace-py#1849]
Hey,

I've noticed that `intervaltree` has no pinned version in `setup.py`. It can result in some inconsistencies, but also it takes a lot of time for [snyk monitor](https://snyk.io/) to run as it needs to download all versions of `intervaltree`. That is not very efficient.

Would it be possible to pin it?

https://github.com/DataDog/dd-trace-py/blob/b5df0ea5056413a1449a3ba5a963b8a4500bdf77/setup.py#L165

**Comment by jd** [comment]
Pinning it would break any dd-trace-py user who wants to use a different version we support. Pinning a library isn't a good practice for a library.
Is there any reason you couldn't pin it in your application?

**Comment by alinagol** [comment]
Hey!

Thanks for your quick response. I see your point, and indeed you are right about this. 

My reason was quite simple - I wanted to avoid pinning every dependency of every dependency of my project :)

**Comment by jd** [comment]
That's something you can actually do easily if you deploy an app using [Poetry](https://python-poetry.org/) or [pipenv](https://github.com/pypa/pipenv). Those are the recommended tools nowadays to achieve this.

You can also use a simpler approach and a plain `requirements.txt`, that's less powerful, but it still works well. Just generate it using `pip freeze` and use it as a constraint file with `pip -c`.

**Comment by alinagol** [comment]
Thanks a lot for the tips @jd! Much appreciated
