### ISSUE TITLE
Wheel support for linux aarch64[arm64]

### ISSUE THREAD

**Issue by odidev** [DataDog/dd-trace-py#1866]
**Summary**
Installing dd-trace-py on aarch64 via pip using command "pip3 install dd-trace-py" tries to build wheel from source code

**Problem description**
dd-trace-py doesn't have wheel for aarch64 on PyPI repository. So, while installing dd-trace-py via pip on aarch64, pip builds wheel for same resulting in it takes more time to install dd-trace-py. Making wheel available for aarch64 will benefit aarch64 users by minimizing dd-trace-py installation time.

**Expected Output**
Pip should be able to download dd-trace-py wheel from PyPI repository rather than building it from source code.

@dd-trace-py-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make dd-trace-py wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by jd** [comment]
We're using GitHub Actions to build the wheels. The first question is, can we use a runner that runs on aarch64 to build those wheels?

**Comment by odidev** [comment]
@jd Thanks for your quick response, Github Actions doesn't have arm64 runner. We can use qemu to build aarch64 wheels on x86 runner. Circleci has arm64 runner,  so circleci can also be used for building aarch64 wheels.

**Comment by Kyle-Verhoog** [comment]
This is done as of #1917 and #1951 with v0.46 being the first release to include aarch64 wheels.
