### ISSUE TITLE
Configuration of database name impossible?

### ISSUE THREAD

**Issue by davesade** [DataDog/dd-trace-py#1887]
https://github.com/DataDog/dd-trace-py/blob/15f1c92465e9b5e023c26c1dce20bc1c296ebf4e/ddtrace/contrib/psycopg/connection.py#L17

We use `ddtrace.patch_all()` method, but I couldn't find a way, how to configure name of a database resource - in APM it appears always as `postgres`, which is misleading - we got many databases and applications. How can one configure this detail, please?

**Comment by majorgreys** [comment]
@davesade Since 0.42.0, this can be configured using an environment variable. You also have the option to configure at the connection instance level as well.

https://ddtrace.readthedocs.io/en/stable/integrations.html#module-ddtrace.contrib.psycopg

**Comment by davesade** [comment]
I didn't know that. looked for it around. Thanks a lot!

**Comment by davesade** [comment]
To my surprise, exactly same solution did work in one Django (Shockwave) project, but it didn't worked on Gunicorn app (still shows `postgres`).
![image](https://user-images.githubusercontent.com/17637831/102892386-14b6b700-4460-11eb-9842-0413b3803f02.png)
I simply put `ENV DD_PSYCOPG_SERVICE=myapp-database` into the Dockerfile, I can confirm that env var is present in running container.
Maybe something is overriding that?

**Comment by majorgreys** [comment]
@davesade Can you open a support ticket as we'll need more information on your environment to help address this issue? We can leave issue open until we confirm this is a problem with the library or rather configuration.

https://www.datadoghq.com/support/

**Comment by andrewsouthard1** [comment]
@davesade - were you able to have this issue resolved through support?

**Comment by davesade** [comment]
@andrewsouthard1 Not yet, but frankly I contacted support few days ago.

**Comment by davesade** [comment]
We solved the issue - it was just old version (0.40) of dd-trace library! 🤦  Bumping to 0.47 solved the issue. Thanks everyone for your support!
