### ISSUE TITLE
Augment SNS messages with distributed tracing

### ISSUE THREAD

**Issue by sburns** [DataDog/dd-trace-py#1921]
(Snipping default issue text, not reporting a problem)

#1807 is really cool and I'm excited to be able to better trace from a web frontend (where messages are published) to a consumer backend (where messages are consumed).

We tend to publish messages on a SNS topic and then use [subscriptions](https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html) to direct a message into the appropriate queue(s) so our SQS messages are produced within Amazon machinery and therefore can't use the automatic distributed tracing in #1807.

I _believe_ following a similar pattern in #1807 for SNS publish methods should be able to help distributed tracing via SNS messages as well. Obviously y'all have your own internal roadmaps so I'm curious if I were to spend a little time on this if there's willingness to merge?

**Comment by Kyle-Verhoog** [comment]
Hey @sburns, sorry for the very late reply! I'm not familiar enough with AWS but we would definitely accept a contribution if you're willing to take this on!

**Comment by Kyle-Verhoog** [comment]
I believe this was implemented in https://github.com/DataDog/dd-trace-py/pull/3178 🙂
