### ISSUE TITLE
Incompatible with aws-lambda-java-libs

### ISSUE THREAD

**Issue by christianbundy** [DataDog/dd-trace-py#1934]
Hey there! My team uses Datadog every day, and we wanted to make you aware of an incompatibility with Java lambdas that parse HTTP requests with the official AWS Lambda Java libraries. I've made [a bug report upstream](https://github.com/aws/aws-lambda-java-libs/issues/212), but I thought you'd also want to know.

I've filled out the issue template below, as requested, but I'm not sure that it's very applicable to issues like this.

Thanks for all your work on Datadog. We're planning to workaround the issue by [disabling this feature](https://ddtrace.readthedocs.io/en/stable/integrations.html#id11):

```python

from ddtrace import config

# Enable distributed tracing
config.botocore['distributed_tracing'] = True
```

---

### Which version of dd-trace-py are you using?

0.45.0

### Which version of the libraries are you using?

N/A

### How can we reproduce your problem?

Use ddtrace==0.45.0 to call a lambda that uses aws-lambda-java-libs.

### What is the result that you get?

The lambda throws a parser error: https://github.com/aws/aws-lambda-java-libs/issues/212

### What is the result that you expected?

Updating ddtrace should not error out the lambda.

**Comment by Kyle-Verhoog** [comment]
https://github.com/DataDog/dd-trace-py/pull/2639 should address this (which will be included in 0.51). @christianbundy please re-open if this is not the case!
