### ISSUE TITLE
RateSampler samples at 100% when set to 0%

### ISSUE THREAD

**Issue by ekelleyv** [DataDog/dd-trace-py#1935]
When testing impact of different sample rates, we set the sample rate to `0.0`, at which point we started seeing 100% of traces sampled:

https://github.com/DataDog/dd-trace-py/blob/3fe328a0a12a7d107bdf85ba9073c219be20174b/ddtrace/sampler.py#L51-L53

Instead, I would expect this condition to check `<` rather than `<=` as 0 is a valid sampling rate.

**Comment by Kyle-Verhoog** [comment]
Yep, AFAICT this is a bug (perhaps the assumption was that setting a sample rate to 0 wasn't going to be a use-case). Looks like an easy fix.
