### ISSUE TITLE
Missing documentation of python versions supported

### ISSUE THREAD

**Issue by jacoor** [DataDog/dd-trace-py#198]
Hello
I just run into issue that I wasn't been able to make ddtrace work on python 2.7.6 (one of our servers) while it worked on local machine with py2.7.13 in docker container. 

Installing python 2.7.13 (compiling from source, just for the sake of test for this one project) make it working on server.

Upgrading python globally on server, to py2.7.13 did not work, ddtrace still complains with the error pasted below.

Going to keep you posted wit our findings and if you can help, please do not hesitate :)

Thanks!

**Comment by jacoor** [comment]
Just tried with 2.7.12 - still no go. 2.7.13 is working nicely.

**Comment by jacoor** [comment]
File "xxx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 125, in get_response
  response = middleware_method(request, callback, callback_args, callback_kwargs)

File "xxx/local/lib/python2.7/site-packages/ddtrace/contrib/django/middleware.py", line 52, in process_view
  span.resource = func_name(view_func)

File "xxx/local/lib/python2.7/site-packages/ddtrace/contrib/__init__.py", line 4, in func_name
  return "%s.%s" % (f.__module__, f.__name__)


Those are the errors I have.

**Comment by palazzem** [comment]
thank you @jacoor for reporting this issue! We're going to work on both sides: docs and better Python support. We'll keep you updated!

**Comment by jacoor** [comment]
@palazzem this issue is really peculiar. 
We have updated global python to 2.7.13 on our server and issue is still there, despite it working when I compiled py2.7.13 locally, just for this one project, on server. 
Going to keep you posted about what we will find later on. I also updated original description with a bit more insight.

**Comment by jacoor** [comment]
I am closing this as invalid. Further investigaton and we found this:
https://github.com/DataDog/dd-trace-py/pull/203
