### ISSUE TITLE
flask + gunicorn, different requests have the same trace_id.

### ISSUE THREAD

**Issue by hmlu** [DataDog/dd-trace-py#1990]
flask + gunicorn, different requests have the same trace_id.

### Which version of dd-trace-py are you using?
0.45.0

### Which version of the libraries are you using?
Flask==1.0.2
Jinja2==2.10
gunicorn==20.0.4
gevent==1.4.0
oyaml==0.7
requests==2.21.0
redis==3.0.1
Flask-Redis==0.3.0
PyMySQL==0.9.3
mysqlclient==1.4.6
shortuuid==0.5.0
influxdb==5.2.3
markdown==3.1.1
pycryptodome==3.9.7
elasticsearch>=7.0.0,<8.0.0

### How can we reproduce your problem?
example wsgi.py：
![image](https://user-images.githubusercontent.com/4734071/106838043-82e4cf80-66d6-11eb-8044-0acfc652fae0.png)

start command：
`ddtrace-run gunicorn -c wsgi.py "web:wsgi()" --limit-request-line 0 $*`

The example only opens one worker.

### What is the result that you get?
![image](https://user-images.githubusercontent.com/4734071/106837735-f803d500-66d5-11eb-8ba9-773be06d95c2.png)

### What is the result that you expected?
different trace_id

**Comment by majorgreys** [comment]
Are you setting the `DD_GEVENT_PATCH_ALL` environment variable which ensures gevent's monkey patching occurs before ddtrace patches?

```
If you are using ddtrace-run and experiencing issues with patching then set DD_GEVENT_PATCH_ALL=true and ddtrace will call gevent.monkey.patch_all() as early as possible in your application to avoid patching conflicts.
```

https://ddtrace.readthedocs.io/en/stable/integrations.html#gevent

**Comment by hmlu** [comment]
> Are you setting the `DD_GEVENT_PATCH_ALL` environment variable which ensures gevent's monkey patching occurs before ddtrace patches?
> 
> https://ddtrace.readthedocs.io/en/stable/integrations.html#gevent


Thank you very much,  the problem has been solved.
