### ISSUE TITLE
Inject Process ID Into Logs

### ISSUE THREAD

**Issue by ricky-sb** [DataDog/dd-trace-py#2017]
We should inject the process ID into the log data. It would be nice to associate a log event to a particular process. Sometimes, a single container may have multiple processes.   

I can submit a PR for this, it would be [adding another line here](https://github.com/DataDog/dd-trace-py/blob/9640832e67d20580f5e23f1c2d213a12e1331081/ddtrace/contrib/logging/patch.py#L42) with the process ID.

**Comment by Kyle-Verhoog** [comment]
While this was originally marked as a feature-request I think this falls outside the scope of the ddtrace library. ddtrace shouldn't be responsible for attaching additional data (beyond trace correlation data) to logs.

This should be achievable using a custom [log handler](https://docs.python.org/3/library/logging.html#handler-objects).

🤞 one day ddtrace will do logs too though!
