### ISSUE TITLE
Inconsistencies in health metrics

### ISSUE THREAD

**Issue by deadok22** [DataDog/dd-trace-py#2018]
I believe there are several inconsistencies in the health metrics reported [here](https://github.com/DataDog/dd-trace-py/blob/efe93da7ee33f12d29aef3c717dde8fd70091698/ddtrace/internal/writer.py#L285-L305):
1. `datadog.tracer.http.requests` is emitted both [as a count](https://github.com/DataDog/dd-trace-py/blob/efe93da7ee33f12d29aef3c717dde8fd70091698/ddtrace/internal/writer.py#L299) and [as a distribution](https://github.com/DataDog/dd-trace-py/blob/efe93da7ee33f12d29aef3c717dde8fd70091698/ddtrace/internal/writer.py#L197).
2. `datadog.tracer.http.requests`, the count metric, is incremented once per flush, while its distribution counterpart is incremented once per attempt - see how `_send_payload` is [called recursively](https://github.com/DataDog/dd-trace-py/blob/efe93da7ee33f12d29aef3c717dde8fd70091698/ddtrace/internal/writer.py#L223)
3. `datadog.tracer.http.sent.bytes` is emitted as a distribution in two places: [here](https://github.com/DataDog/dd-trace-py/blob/efe93da7ee33f12d29aef3c717dde8fd70091698/ddtrace/internal/writer.py#L300) and [here](https://github.com/DataDog/dd-trace-py/blob/efe93da7ee33f12d29aef3c717dde8fd70091698/ddtrace/internal/writer.py#L210). The semantics of the two invocations differ: the former emits a distribution metric once per payload, the latter - once per *successful* payload submission. The `.sum` component of the distribution is 2x the payload size on successful submissions, and is 1x the payload size on unsuccessful ones.

These metrics need some TLC

### Which version of dd-trace-py are you using?

The issues are present on the master branch (commit efe93da7ee33f12d29aef3c717dde8fd70091698)

**Comment by Kyle-Verhoog** [comment]
Hey @deadok22 thanks for finding and detailing! All 3 points like bugs to me. Looks like some stuff wasn't ported properly when the writer was refactored 😞.

Going to try to get a fix in for this by the end of the week!

**Comment by Kyle-Verhoog** [comment]
the health metrics feature was never fully GA'd and will be superseded by the telemetry effort
