### ISSUE TITLE
Unclear how to use trace filtering under ddtrace-run

### ISSUE THREAD

**Issue by adamf** [DataDog/dd-trace-py#2042]
I'm using ddtrace 0.45.0 with ddtrace-run in in a django application. I want to filter out healthcheck request by URL paths; I think this should work in my `app.py`:

```
from ddtrace import Tracer
from ddtrace.filters import FilterRequestsOnUrl

# Disable Datadog APM for healthz urls
Tracer.configure(settings={
    'FILTERS': [
        FilterRequestsOnUrl(r'_\/healthz')
    ],
})
```

This seems to be what the docs suggest - I get a copy of the global `Tracer` object and add some filter settings. However, when I do this I get:

```
    Tracer.configure(settings={
TypeError: missing 1 required positional argument
```

Am I doing something wrong? The docs don't really make it clear how to access the global Tracer, and the reading the code makes me think I'm correctly calling configure.

**Comment by adamf** [comment]
I think this is just a documentation update needed; it's not clear from the docs how to get the global tracer instance.

This works:

```  
from ddtrace import tracer
from ddtrace.filters import FilterRequestsOnUrl

tracer.configure(settings={
       'FILTERS': [
                FilterRequestsOnUrl(r'.*_\/healthz.*')
       ],
})

```

Two critical things here: 1) the global tracer instances is `tracer` 2) the filter needs to match the _whole_ URL, including any query parameters, or it doesn't work. A partial match/set of matches doesn't seem to work.

**Comment by Kyle-Verhoog** [comment]
@adamf thanks for the report!

Yup... looks like that documentation snippet was quite misleading :confused:. It's an instance method and not a class method as you discovered.

I've opened up #2043 to address this.
