### ISSUE TITLE
pika integration

### ISSUE THREAD

**Issue by ryankdwyer** [DataDog/dd-trace-py#2047]
Provide support for the RabbitMQ wrapper, pika - [repo](https://github.com/pika/pika)

I will begin work on a pika integration. If anyone has any comments, suggestions, or recommendations, please feel free to leave them below in the comments.

**Comment by cyril94440** [comment]
Any update on this?

**Comment by stephledev** [comment]
also interested in an update, judging by the timeline the original undertaking was abandoned. @Kyle-Verhoog any chance this will be picked up by the datadog team?

**Comment by emmettbutler** [comment]
Apologies for the lack of response, we missed this ticket for a long time. The request for a pika integration is in our team's feature backlog and is not planned for the short term. As part of the backlog it will be considered during feature prioritization.

If anyone reading this is motivated to contribute the integration, please do so.
