### ISSUE TITLE
aio-pika integration

### ISSUE THREAD

**Issue by ryankdwyer** [DataDog/dd-trace-py#2048]
Provide support for the RabbitMQ wrapper, aio-pika - [repo](https://github.com/mosquito/aio-pika)

I will begin work on an aio-pika integration. If anyone has any comments, suggestions, or recommendations, please feel free to leave them below in the comments.

**Comment by c0rv4x** [comment]
@ryankdwyer Hey Ryan!

Any progress on this one? I feel like I would love to have that one, but probably to lazy to write an integration for the tool, for which I already pay :D

**Comment by yaelmi3** [comment]
Same here, addition of aio-pika, would be really great

**Comment by emmettbutler** [comment]
Apologies for the lack of response, we missed this ticket for a long time. The request for an aio-pika integration is in our team's feature backlog and is not planned for the short term. As part of the backlog it will be considered during feature prioritization.

If anyone reading this is motivated to contribute the integration, please do so.
