### ISSUE TITLE
0.47.0 PyPi release?

### ISSUE THREAD

**Issue by aaaaahaaaaa** [DataDog/dd-trace-py#2066]
Hey. I can see you guys tagged 0.47.0 several days ago. When are you planning a release on Pypi?

**Comment by majorgreys** [comment]
We will have the release published to pypi before the end of next week.

**Comment by sf-jin-ku** [comment]
@majorgreys any update on pypi release? :)

**Comment by Kyle-Verhoog** [comment]
Hi @sf-jin-ku, @aaaaahaaaaa!

We caught an issue while doing our release testing but it has been resolved now. We're re-running our tests and hope to do the release tomorrow with all going well 🙂. Sorry for the delay!

**Comment by Kyle-Verhoog** [comment]
We backported two more small improvements (#2064, #2090) and our release testing looks good but unfortunately it's end of day for us so we'll post another update tomorrow.

**Comment by Kyle-Verhoog** [comment]
Release is out now 🙂: https://pypi.org/project/ddtrace/0.47.0/
