### ISSUE TITLE
No trace for elasticsearch7

### ISSUE THREAD

**Issue by jprestel-rue** [DataDog/dd-trace-py#2073]
My team's app has to work with multiple versions of elasticsearch, so we use the version-specific libraries. I saw in the [0.46.0 release](https://github.com/DataDog/dd-trace-py/releases/tag/v0.46.0) that y'all added support for `elasticsearch7` so I immediately upgraded and gave it a shot. Unfortunately, I'm not seeing any spans for elasticsearch in the trace.

### Which version of dd-trace-py are you using?
0.46.0

### Which version of the libraries are you using?
Here are the ES libs we're using:
```
elasticsearch              1.9.0
elasticsearch-dsl          0.0.11
elasticsearch7             7.11.0
elasticsearch7-dsl         7.2.1
```

### Tracer setup
This is at the top of our WSGI:

If it matters, we're running a django 1.8

```python
from ddtrace import config, patch_all

patch_all(httplib=True)
# header names are not case sensitive here
config.trace_headers([
    'cache-control',
    'expires',
    'host',
    'referer',
    'server',
    'user-agent',
])
config.django.http.trace_query_string = True
```

**Comment by Kyle-Verhoog** [comment]
Thanks for the report @jprestel-rue! Strange as support should have been included in 0.46 and I see it included in the tagged commit .

It's now showing up in the 0.47 release notes and not the 0.46, super strange 🤔. We'll take a look!

In the meantime could you try 0.47?

**Comment by jprestel-rue** [comment]
Trying with v0.47.0 now. I'll let you know how it goes!

**Comment by jprestel-rue** [comment]
No luck. Still not getting spans for ES with v0.47.0 :(

**Comment by Kyle-Verhoog** [comment]
Thanks for the super quick follow-up. We'll dig into it

**Comment by jprestel-rue** [comment]
I set `DD_TRACE_DEBUG=true`. Found this in the output:
```json
{
    "date": "2021-03-03T20:45:09.193161",
    "os_name": "Linux",
    "os_version": "4.14.193-149.317.amzn2.x86_64",
    "is_64_bit": true,
    "architecture": "64bit",
    "vm": "CPython",
    "version": "0.47.0",
    "lang": "python",
    "lang_version": "3.6.10",
    "pip_version": "21.0.1",
    "in_virtual_env": false,
    "agent_url": "http://localhost:8126",
    "agent_error": "Agent not reachable at localhost:8126. Exception raised: [Errno 99] Cannot assign requested address",
    "env": "orca",
    "is_global_tracer": false,
    "enabled_env_setting": null,
    "tracer_enabled": true,
    "sampler_type": "DatadogSampler",
    "priority_sampler_type": "RateByServiceSampler",
    "service": "product-indexer",
    "debug": true,
    "enabled_cli": false,
    "analytics_enabled": false,
    "log_injection_enabled": false,
    "health_metrics_enabled": false,
    "dd_version": "",
    "priority_sampling_enabled": true,
    "global_tags": "",
    "tracer_tags": "",
    "integrations": {
        "asyncio": "N/A",
        "boto": "N/A",
        "botocore": {
            "enabled": true,
            "instrumented": false,
            "module_available": true,
            "module_version": "1.11.9",
            "module_imported": true,
            "config": "N/A"
        },
        "bottle": "N/A",
        "cassandra": "N/A",
        "celery": {
            "enabled": true,
            "instrumented": false,
            "module_available": true,
            "module_version": "3.1.24",
            "module_imported": false,
            "config": "N/A"
        },
        "consul": "N/A",
        "django": "N/A",
        "elasticsearch": {
            "enabled": true,
            "instrumented": false,
            "module_available": true,
            "module_version": "7.6.0",
            "module_imported": false,
            "config": "N/A"
        },
        "algoliasearch": "N/A",
        "futures": "N/A",
        "grpc": "N/A",
        "mongoengine": "N/A",
        "mysql": "N/A",
        "mysqldb": "N/A",
        "pymysql": "N/A",
        "psycopg": "N/A",
        "pylibmc": "N/A",
        "pymemcache": "N/A",
        "pymongo": "N/A",
        "redis": {
            "enabled": true,
            "instrumented": false,
            "module_available": true,
            "module_version": "2.10.5",
            "module_imported": true,
            "config": "N/A"
        },
        "rediscluster": "N/A",
        "requests": {
            "enabled": true,
            "instrumented": false,
            "module_available": true,
            "module_version": "2.7.0",
            "module_imported": true,
            "config": "N/A"
        },
        "sanic": "N/A",
        "sqlalchemy": "N/A",
        "sqlite3": "N/A",
        "aiohttp": "N/A",
        "aiopg": "N/A",
        "aiobotocore": "N/A",
        "httplib": "N/A",
        "vertica": "N/A",
        "molten": "N/A",
        "jinja2": "N/A",
        "mako": "N/A",
        "flask": "N/A",
        "kombu": {
            "enabled": false,
            "instrumented": false,
            "module_available": true,
            "module_version": "3.0.37",
            "module_imported": false,
            "config": null
        },
        "starlette": "N/A",
        "falcon": "N/A",
        "pylons": "N/A",
        "pyramid": "N/A",
        "logging": "N/A",
        "pynamodb": "N/A",
        "pyodbc": "N/A",
        "fastapi": "N/A"
    }
}
```

**Comment by jprestel-rue** [comment]
If it's helpful in anyway, we used to have this sort of monkey patch to get partial tracing for es7 library. I removed it when upgrading to 0.47.0:

```python
from importlib import import_module

from ddtrace.contrib.elasticsearch.patch import _patch

# Patch the ES7 module
# This logic is mimiced from the below snippet
# https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/elasticsearch/patch.py#L15-L27
_patch(import_module('elasticsearch7'))
```

With that hack, we were able to get spans for Elasticsearch show up in traces. 
This graph from APM shows how the Elasticsearch visibility disappeared after removing that patch and using 0.47.0's built-in support instead:
![image](https://user-images.githubusercontent.com/17439030/109871776-89188e00-7c39-11eb-95a0-616bf53bd788.png)

**Comment by Kyle-Verhoog** [comment]
@jprestel-rue I'm going to take a look at it today 🙂.

**Comment by Kyle-Verhoog** [comment]
@jprestel-rue I've put up a fix in #2139 which should be included in the v0.48 release. It'd be great if you could try out the PR branch to confirm the fix as well 🙂

**Comment by jprestel-rue** [comment]
Unfortunately, I'm blocked by a build failure because my build machine is using pip 18.1 which has a bug related to installing from a git repo 🤦 

trying to figure out where in our build machinery i need to upgrade pip, so i probably won't be able to test this tonight 😭

**Comment by Kyle-Verhoog** [comment]
ahhhh, haha no worries! We can also get a wheel built and deployed to our own pypi index that I can send your way if need-be 🙂

**Comment by jprestel-rue** [comment]
I was able to test it! It worked! 👯 👯‍♂️ 🕺 💃 🎉

**Comment by jprestel-rue** [comment]
@Kyle-Verhoog is there a _**notional**_ timeline for the 0.48 release? Not looking for a firm commitment, just trying to get a rough sense of timing :)

**Comment by Kyle-Verhoog** [comment]
Nothing concrete yet! I think we want to get #2038 in still and that should do it. It'll for sure be out before the end of March but I can update as we get closer 🙂

**Comment by jprestel-rue** [comment]
Hey @Kyle-Verhoog wanted to check in to see if you might have an update here 🙃

**Comment by Kyle-Verhoog** [comment]
Good timing @jprestel-rue - we just released. The pypi package should be available shortly 🙂

**Comment by Kyle-Verhoog** [comment]
... or once github resolves their incident

https://github.com/DataDog/dd-trace-py/runs/2249670602?check_suite_focus=true

![image](https://user-images.githubusercontent.com/6321485/113357007-3225d780-9311-11eb-8a34-b953bd4d8315.png)

**Comment by jprestel-rue** [comment]
@Kyle-Verhoog thanks for your work on this! Strangely, I'm seeing the tracing work for queries but NOT for bulk operations:

I opened https://github.com/DataDog/dd-trace-py/issues/2272 to track this issue.

**Comment by Kyle-Verhoog** [comment]
hey @jprestel-rue, ugh, sorry! Thanks for opening a follow up 🙂
