### ISSUE TITLE
Tracing report levels

### ISSUE THREAD

**Issue by brettlangdon** [DataDog/dd-trace-py#208]
It might be nice to be able to define a tracing reporting level, like a log level, to traces and then set a global "trace level".

My reasoning here is there are some cases in development/testing where I want to trace many more things to be able to debug a specific problem or performance issue. However, these traces are just too much/noisy to leave in for production.

Not sure if there is already a way to handle such a case? Unless I create a separate `Tracer` instance and just enable/disable that one as needed?

```python
from ddtrace import tracer

# report all traces of level 'debug' or higher
tracer.set_level('debug')

# Trace this function only when level is 'debug'
@tracer.wrap(level='debug')
def child():
    pass


# Always trace this function
@tracer.wrap()
def parent():
    child()


with tracer.trace('main', service='main'):
    parent()
```

**Comment by jbonzo** [comment]
Can you elaborate how that will work with multiple services? Lets say you have service A, B, and C and you trace the entire application through each service. If you set the tracer object in services A and B to debug but don't specify a level in service C what should happen?
