### ISSUE TITLE
Pyspark Integration

### ISSUE THREAD

**Issue by bayarmunkh** [DataDog/dd-trace-py#2165]
Any plan on supporting [pyspark](https://pypi.org/project/pyspark/)?

**Comment by emmettbutler** [comment]
Apologies for the lack of response, we missed this ticket for a long time. The request for a pyspark integration is in our team's feature backlog and is not planned for the short term. As part of the backlog it will be considered during feature prioritization.

If anyone reading this is motivated to contribute the integration, please do so.
