### ISSUE TITLE
Async: Support of Quart

### ISSUE THREAD

**Issue by remi-debette** [DataDog/dd-trace-py#2169]
### Which version of dd-trace-py are you using?
0.47.0

### Which version of the libraries are you using?
Quart 0.13.1

Can you add the support of Quart or hint on how it could be done?

**Comment by emjohnson20** [comment]
+1 to this feature request or assistance instrumenting it ourselves.

**Comment by bercikr** [comment]
I've managed to get quart instrumented using the asgi middleware integration. Docs are [here](https://pgjones.gitlab.io/quart/how_to_guides/middleware.html) and [here](https://ddtrace.readthedocs.io/en/stable/integrations.html#asgi).  Snippet of code for quart looks like this: 

```
from ddtrace.contrib.asgi import TraceMiddleware
from quart import Quart, request, jsonify

app = Quart(__name__)
app.asgi_app = TraceMiddleware(app.asgi_app)
```

**Comment by emmettbutler** [comment]
Apologies for the lack of response, we missed this ticket for a long time.

@bercikr's custom instrumentation above is a great use case for the ASGI middleware integration and seems to me to answer the original question on this ticket.
