### ISSUE TITLE
Async: support of httpx

### ISSUE THREAD

**Issue by remi-debette** [DataDog/dd-trace-py#2170]
### Which version of dd-trace-py are you using?
0.47.0

### Which version of the libraries are you using?
httpx 0.16.1

Can you add the support of httpx or hint on how it could be done?

**Comment by etimberg** [comment]
Is there an anticipated release that will contain this feature? I noticed that it's not in the 0.52.0 milestone, does that mean that it would be released later?

**Comment by brettlangdon** [comment]
@etimberg it will be in 0.52.0. I didn't tag the PR with the milestone, but it is merged into `master` and will definitely be apart of 0.52.0.

No ETA just yet on the release, we'll discuss it on Monday and it'll definitely be sometime within the next 2 weeks.
