### ISSUE TITLE
Async: support of Motor

### ISSUE THREAD

**Issue by remi-debette** [DataDog/dd-trace-py#2171]
### Which version of dd-trace-py are you using?
0.47.0

### Which version of the libraries are you using?
Motor 2.3.0

Can you add the support of Motor or hint on how it could be done?

**Comment by emmettbutler** [comment]
Apologies for the lack of response, we missed this ticket for a long time. The request for a motor integration is in our team's feature backlog and is not planned for the short term. As part of the backlog it will be considered during feature prioritization.

If anyone reading this is motivated to contribute the integration, please do so.
