### ISSUE TITLE
setuptools_scm dropped support for py2.7

### ISSUE THREAD

**Issue by devenv** [DataDog/dd-trace-py#2226]
After trying to install 0.47.0 I got an error 
```
...
      File "/tmp/easy_install-eIWm4h/setuptools_scm-6.0.1/src/setuptools_scm/__init__.py", line 8, in <module>
      File "/tmp/easy_install-eIWm4h/setuptools_scm-6.0.1/src/setuptools_scm/config.py", line 6, in <module>
      File "/tmp/easy_install-eIWm4h/setuptools_scm-6.0.1/src/setuptools_scm/utils.py", line 41
        print(*k)
              ^
    SyntaxError: invalid syntax
```
After digging for where it came from (0.44.0 installed just fine a couple of months ago) I stumbled upon https://github.com/pypa/setuptools_scm/issues/541
Apparently, setuptools_scm dropped support for py2, so we either need to define a better range in requirements or also drop support for py2.

**Comment by jd** [comment]
Hi @devenv

Could you provide the command/procedure you used to install ddtrace?

**Comment by devenv** [comment]
The regular
```
pip download -d /tmp/tmpQhAGy2 --no-cache-dir ddtrace==0.47.0
```
which results in
```
pip --disable-pip-version-check wheel --no-deps -w /tmp/tmpGBofle 'setuptools_scm[toml]>=4'
````
and
```
      File "/tmp/pip-build-FlixPl/setuptools-scm/src/setuptools_scm/utils.py", line 41
        print(*k)
              ^
    SyntaxError: invalid syntax
```

**Comment by majorgreys** [comment]
@devenv Which version of `pip` are you on?

**Comment by devenv** [comment]
8.1.2

**Comment by majorgreys** [comment]
We require `pip>=18` for build system requirements. We recently updated our installation guide to reflect this: https://github.com/DataDog/dd-trace-py/blob/master/docs/installation_quickstart.rst#installation.

Also, the issue with `setuptools_scm` seems specific to `pip<10` from what I can gather in https://github.com/pypa/setuptools_scm/issues/541#issuecomment-805414412.

I will close this issue given that this is an unsupported version of pip. If you still experience this problem after upgrading pip, please do re-open or open another issue if a new problems crops up.
