### ISSUE TITLE
Sanic: IndexError tuple index out of range with latest version of sanic

### ISSUE THREAD

**Issue by HaithamMaya** [DataDog/dd-trace-py#2240]
Thanks for taking the time for reporting an issue!

Before reporting an issue on dd-trace-py, please be sure to provide all
necessary information.

If you're hitting a bug, make sure that you're using the latest version of this
library.

### Which version of dd-trace-py are you using?
```
ddtrace==0.47.0
```

### Which version of the libraries are you using?
```
sanic==21.3.2
```

You can copy/paste the output of `pip freeze` here.

### How can we reproduce your problem?
```
from ddtrace import patch_all
patch_all(sanic=True)

from sanic import Sanic
from sanic.response import text

app = Sanic(__name__)

@app.route('/')
def index(request):
    return text('hello world')

if __name__ == '__main__':
    app.run()
```
### What is the result that you get?
```
	Traceback (most recent call last):
	  File "/opt/venv/lib/python3.9/site-packages/sanic/http.py", line 125, in http1
	    await self.protocol.request_handler(self.request)
	  File "/opt/venv/lib/python3.9/site-packages/ddtrace/contrib/sanic/patch.py", line 86, in patch_handle_request
	    write_callback = kwargs.get("write_callback", args[1])
	IndexError: tuple index out of range
```

### What is the result that you expected?
No failure

**Comment by Kyle-Verhoog** [comment]
Hi @HaithamMaya, thanks for the report!

Indeed it looks like sanic had a significant refactor in https://github.com/sanic-org/sanic/pull/1876 in which the `handle_request` method's signature was changed which has resulted in the error you're seeing.

We'll work on getting a fix in for this 🙂
