### ISSUE TITLE
Make flask-cache tracer work with the flask-caching fork

### ISSUE THREAD

**Issue by underyx** [DataDog/dd-trace-py#2242]
The documentation mentions that there's [tracing is available for "Flask Cache"](https://ddtrace.readthedocs.io/en/stable/integrations.html#module-ddtrace.contrib.flask_cache). This project has been unmaintained for 7 years however: https://github.com/thadeusb/flask-cache

There is a maintained fork at https://github.com/sh4nks/flask-caching, and even though it's API-compatible with the old library, ddtrace is not compatible because [the import path is different](https://github.com/sh4nks/flask-caching#compatibility-with-flask-cache) and the dd-trace module [hardcodes the import path of the old library](https://github.com/DataDog/dd-trace-py/blob/dea3a6435612293aa592997e87983f3e58b75947/ddtrace/contrib/flask_cache/tracers.py#L7).

**Comment by brettlangdon** [comment]
hey @underyx sorry for the long delay responding here. I took a quick look and we might not be able fully support `flask-caching` with the way the integration is written today.

Like you noticed, I was hoping just updating the hard coded import path would be enough, but there is some other incompatibility with the way the cache clients are stored, making it harder for us to get the proper metadata we need.

Just something we have to think about.

It might be `flask-caching` is only useful along with the underlying cache client also being instrumented as well.
