### ISSUE TITLE
ERROR: Could not build wheels for ddtrace which use PEP 517 and cannot be installed directly Python-3.8 Alpine 

### ISSUE THREAD

**Issue by kaushalringle** [DataDog/dd-trace-py#2262]
### Which version of dd-trace-py are you using?
`0.47.0`

### Which version of pip are you using?
`pip 21.0.1 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)`

### Which version of the libraries are you using?
packages from `3.8-alpine` image.
```
Package    Version
---------- -------
pip        21.0.1
setuptools 54.2.0
wheel      0.36.2
```
### How can we reproduce your problem?
Dockerfile 
```
FROM python:3.8-alpine
RUN apk --update add gcc build-base
RUN pip install --no-cache-dir ddtrace=="0.47.0"
```
Build the image using 
```
docker build  -t test-alpine-python-dd-trace .
```
### What is the result that you get?
#6 53.92   ERROR: Failed building wheel for ddtrace
#6 53.92   Building wheel for intervaltree (setup.py): started
#6 54.31   Building wheel for intervaltree (setup.py): finished with status 'done'
#6 54.31   Created wheel for intervaltree: filename=intervaltree-3.1.0-py2.py3-none-any.whl size=26102 sha256=786a4e093e4a5fed01ffedd954e9ba94e7648a8035585423d5aa155388294028
#6 54.31   Stored in directory: /tmp/pip-ephem-wheel-cache-1_elt6gq/wheels/45/23/de/5789a92962483fd33cb06674792b9697c1b3766d7c7742830e
#6 54.31 Successfully built intervaltree
#6 54.31 Failed to build ddtrace
#6 54.31 ERROR: Could not build wheels for ddtrace which use PEP 517 and cannot be installed directly

### What is the result that you expected?
ddtrace should be installed on Alpine

**Comment by brettlangdon** [comment]
@kaushalringle sorry for the long delay in response, we were trying to figure out our options on this one.

I have opened up #2354 to help clarify installation instructions on Alpine.

I think the dependency you are missing is `linux-headers` (it doesn't seem like `build-base` installs `linux-headers`)

> apk add gcc musl-dev linux-headers


These are needed until [PEP-656](https://www.python.org/dev/peps/pep-0656/) is implemented and available for us to publish musl linux wheels.

I am planning to create and pin a new issue related only to installation on Alpine and tracking PEP-656, so I will close this in favor of that one. Please feel free to re-open if you are still experiencing issues after adding `linux-headers` dependency.

**Comment by brettlangdon** [comment]
#2355 is the more general issue opened.

**Comment by kaushalringle** [comment]
Working Dockerfile 

```
FROM python:3.8-alpine
RUN apk --update add gcc musl-dev linux-headers
RUN pip install --no-cache-dir ddtrace
```
