### ISSUE TITLE
OpenTelemetry DataDog exporter is broken because of breaking change in this package.

### ISSUE THREAD

**Issue by owais** [DataDog/dd-trace-py#2269]
This package introduced some breaking changes that caused OpenTelemetry Python's DataDog exporter to break as well. We've pinned `ddtrace` dependency to the last know working version to make things work again. Opening this issue to let maintainers here know about it so they can fix the Otel exporter as they see fit. 

https://github.com/open-telemetry/opentelemetry-python-contrib/pull/400

Thanks.

**Comment by Kyle-Verhoog** [comment]
Thanks for the quick fix @owais! We'll look into fixing the exporter to remove the pin 🙂

**Comment by phillipuniverse** [comment]
@Kyle-Verhoog what's the status here? And @owais is there a list of what the breaking changes are? I am interested in attempting a fix.

I'm running into #1413 which is resolved by #2459 and only available in 0.50.0+ of ddtrace.

**Comment by phillipuniverse** [comment]
@Kyle-Verhoog @owais any update here?

**Comment by phillipuniverse** [comment]
@pj-datadog I am a bit confused by your comment. What exactly is in beta and how would I test it to see if it behaves as I would expect?

OpenTelemetry still [pins the version of ddtrace to 0.47.0](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/07f81461df3e87da0495475d79eed415f3698634/exporter/opentelemetry-exporter-datadog/setup.cfg#L43). My original question was why, and I’m still not sure why.

What am I missing?

**Comment by pj-datadog** [comment]
Hi @phillipuniverse, pardon the ambiguity there. The [OTel Datadog Python Span Exporter](https://docs.datadoghq.com/tracing/setup_overview/open_standards/python/#opentelemetry) that this issue talks about is still in beta. We invite you to [reach out to Datadog support](https://docs.datadoghq.com/help/), we can learn more about the issue you are facing and your intended use of the library. We might also have an alternate option for you to test/use for your use-case.

As for your original question, we are still in the process of building and validating this feature. Before we release anything for our users, we want to make sure we are able to provide best support to our users on all of their use-cases. Thank you for being a valued DataDog customer!
