### ISSUE TITLE
Parsing container ID from cgroup file doesn't work

### ISSUE THREAD

**Issue by krosen040** [DataDog/dd-trace-py#2314]
The logic of parsing the container ID from cgroup doesn't work for us in dd-trace-py, which means that spans don't get tagged with Kubernetes information. It works correctly when using dd-trace-go and dd-trace-java. See below for an example of a line from cgroup that does not get parsed correctly in dd-trace-py.

### Which version of dd-trace-py are you using?
0.48.0

### Which version of pip are you using?

18.1

### How can we reproduce your problem?

Add a test case to `test_container.py` with the following as input to `from_line`.

**Input**
`1:name=systemd:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod2d3da189_6407_48e3_9ab6_78188d75e609.slice/docker-7b8952daecf4c0e44bbcefe1b5c5ebc7b4839d4eefeccefe694709d3809b6199.scope`

### What is the result that you get?

The container ID is `None`.

### What is the result that you expected?

The container ID should be `7b8952daecf4c0e44bbcefe1b5c5ebc7b4839d4eefeccefe694709d3809b6199`.

**Comment by Yun-Kim** [comment]
Hi @krosen040 thank you for reporting this! We're currently investigating this issue and will get back 😄

**Comment by Yun-Kim** [comment]
Hi @krosen040, PR #2535 was made to address this issue and has been merged into master. This should be live in the next release, let me know if that fixes this problem!
