### ISSUE TITLE
Support for tracing Django Rest Framework Serializers

### ISSUE THREAD

**Issue by jalaziz** [DataDog/dd-trace-py#2326]
This was brought up before in #936, but it was closed despite as a duplicate despite the duplicate issue only tackling class-based views.

With DRF, it's not uncommon for the majority of the runtime of a view to actually be consumed in the serializers. It would be great if the DRF support can be extended beyond just views. At the very least, it seems like serializer support could b useful.

One downside could be larger spans for views with nested or complicated serializers. Maybe serializer support could be opt-in or opt-out?

**Comment by emmettbutler** [comment]
Apologies for the lack of response, we missed this ticket for a long time. The request for django rest framework serializer support is in our team's feature backlog and is not planned for the short term. As part of the backlog it will be considered during feature prioritization.

If anyone reading this is motivated to contribute the integration, please do so.
