### ISSUE TITLE
Agent URL with suffix not working

### ISSUE THREAD

**Issue by AdamGold** [DataDog/dd-trace-py#2333]
### How can we reproduce your problem?
When using an agent URL with a suffix, the suffix gets removed therefore the request aren't working.

`export DD_TRACE_AGENT_URL=http://minikube-cluster.info/agent`

This is caused by these lines that drop the `/agent` part:
https://github.com/DataDog/dd-trace-py/blob/73f29241c7/ddtrace/internal/agent.py#L81
```
    if parsed.scheme == "https":
        conn = compat.httplib.HTTPSConnection(hostname, parsed.port, timeout=timeout)
    elif parsed.scheme == "http":
        conn = compat.httplib.HTTPConnection(hostname, parsed.port, timeout=timeout)
```

The `hostname` will be `minikube-cluster.info`.

### What is the result that you get?
404 on all requests to the agent.

### What is the result that you expected?
The agent URL to be `minikube-cluster.info/agent`.

**Comment by Kyle-Verhoog** [comment]
Hi @AdamGold! Thanks for the report, looks like an oversight on our part. We'll the fix in for v0.49 🙂
