### ISSUE TITLE
Installation issues on Alpine

### ISSUE THREAD

**Issue by brettlangdon** [DataDog/dd-trace-py#2355]
Until [PEP-656](https://www.python.org/dev/peps/pep-0656/) we are unable to provide binary distributions for musl linux.

This means `pip` will have to install the tracer from the source distribution, and will require build dependencies in order to build and install properly.

```bash
apk add gcc musl-dev linux-headers
pip install ddtrace
```

Note: `pip>=18` is required to install `ddtrace` on any platform.

**Comment by brettlangdon** [comment]
Starting with `ddtrace==0.56.0` we now publish musl linux wheels.

**Comment by jjpaulo2** [comment]
On **Alpine 3.11**, I got an installation problem, when I tried to install ddtrace, I always was gotten the source version. Solved it just upgrading the pip version.

Without pip upgrade:

```shell
$ pip install ddtrace==1.6.3

Collecting ddtrace==1.6.3
  Downloading ddtrace-1.6.3.tar.gz (1.9 MB)
```

With pip upgrade:

```shell
$ pip install --upgrade pip
$ pip install ddtrace==1.6.3

Collecting ddtrace==1.6.3
  Downloading ddtrace-1.6.3-cp38-cp38-musllinux_1_1_aarch64.whl (4.8 MB)
```
