### ISSUE TITLE
Documentation site code uses incorrect class from ddtrace/contrib/wsgi/wsgi.py

### ISSUE THREAD

**Issue by jeffreybrowning** [DataDog/dd-trace-py#2378]
### Which version of dd-trace-py are you using?
0.48.1

### What libraries am I using:
Python: 3.8

### How can we reproduce your problem?
1. Copy the example code from https://ddtrace.readthedocs.io/en/stable/integrations.html#wsgi
2. Example code cites `DDTraceMiddleware` class
2. Run any wsgi application with said code

### What is the result that you get?
```
ImportError: cannot import name 'DDTraceMiddleware' from 'ddtrace.contrib.wsgi' (/usr/local/lib/python3.8/site-packages/ddtrace/contrib/wsgi/__init__.py)
```

### What is the result that you expected?
Example code in readthedocs site should properly cite the import for the `DDWSGIMiddleware` class: https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/wsgi/wsgi.py#L83

**Comment by brettlangdon** [comment]
Thanks @jeffreybrowning , good catch. I have opened #2381 to address this issue.
