### ISSUE TITLE
Add tracing for aerospike package

### ISSUE THREAD

**Issue by dereklavigne18** [DataDog/dd-trace-py#2408]
Feature request for adding the support for instrumenting the aerospike package.

The repo for the package is here https://github.com/aerospike/aerospike-client-python.

**Comment by emmettbutler** [comment]
Apologies for the lack of response, we missed this ticket for a long time. The request for an aerospike integration is in our team's feature backlog and is not planned for the short term. As part of the backlog it will be considered during feature prioritization.

If anyone reading this is motivated to contribute the integration, please do so.
