### ISSUE TITLE
Proposal: Separate patching from tracing instrumentation in integrations

### ISSUE THREAD

**Issue by brettlangdon** [DataDog/dd-trace-py#2436]
Right now we have a tight coupling in our integrations with monkey patching and instrumenting tracing.

This means the patching we have can only be used for tracing. It would be better if we can separate our integrations into two pieces:

1. Inject event emitters into third party libraries to get instrumentation visibility in places where we do not currently have it.
  a. We should also consider upstreaming new event hooks into libraries where we find they are needed.
2. Change our tracing integrations to only listen for these new events to start spans, add metadata, or finish spans.

The main benefit we get from this is if other tooling, like profiling, want to be able to use the library instrumentation without needing to enable tracing. For example, if we wanted to add Flask request metadata to profiles while having tracing disabled.

**Comment by emmettbutler** [comment]
This pull request fully removes the knowledge of spans from the flask integration https://github.com/DataDog/dd-trace-py/pull/6418

This can function as an example of how other integrations can remove their dependence on tracing.

**Comment by emmettbutler** [comment]
This is moving forward with the adoption of `ddtrace.internal.core` by more contrib modules.
