### ISSUE TITLE
Allowing custom headers for the agent

### ISSUE THREAD

**Issue by AdamGold** [DataDog/dd-trace-py#2447]
Assuming I'm exposing the agent and it requires an auth header - how might I achieve passing headers to the agent?

I noticed the `__init__` method [here](https://github.com/DataDog/dd-trace-py/blob/4cffdf445c081d893fe45c8c9bff0d26b7188808/ddtrace/internal/writer.py#L196) does not accept a `headers` parameter meaning the cluster agent must be available without authentication?

**Comment by majorgreys** [comment]
@AdamGold Were you able to find a workaround to add the auth header? Otherwise, we can take this as a feature request.

**Comment by Kyle-Verhoog** [comment]
`AgentWriter` now supports a `headers` argument. Note that this is an internal API however.
