### ISSUE TITLE
Add support for async SQLAlchemy

### ISSUE THREAD

**Issue by mscheifer** [DataDog/dd-trace-py#2453]
We patch `create_engine` but not `create_async_engine` here: https://github.com/DataDog/dd-trace-py/blob/4ac313b75e6d558fc674a0bfd2e9e37aaadc7e3f/ddtrace/contrib/sqlalchemy/patch.py#L15-L16

### Which version of dd-trace-py are you using?

0.48.1

### Which version of pip are you using?

20.2.3

### Which version of the libraries are you using?

SQLAlchemy==1.4.11

**Comment by alk-gpajot** [comment]
The async engine is simply a wrapper around the sync engine so you could to:
```python
from ddtrace.contrib.sqlalchemy import trace_engine
engine = create_async_engine(...)
trace_engine(engine.sync_engine)
```
I confirm this is working well and tracing all queries.
The only drawback is that you need to have access to the engine to do that.

**Comment by amacfie** [comment]
`create_async_engine` calls `create_engine` so are any changes actually necessary?

**Comment by mscheifer** [comment]
Hey sorry, looking back at this I realized we never actually had `SQLalchemy` patched. What actually happened is that we were seeing spans from the `psycopg` patch code and when we switched to async `SQLAlchemy` we also switched to using`asyncpg` which is unsupported (although looks like it's in 0.60.0 which is great). My bad.

**Comment by amacfie-tc** [comment]
Oh I would have expected that if SQLAlchemy is patched the driver doesn't need to be patched.
