### ISSUE TITLE
Release target for Flask 2.X fix

### ISSUE THREAD

**Issue by stevepentland** [DataDog/dd-trace-py#2472]
I originally commented in #2426 but as it is closed I figured there may not be too many eyes on it. It appears that in `0.49.0` the change from #2439 was not included. Is there a target release for getting this change included?

**Comment by brettlangdon** [comment]
@stevepentland hey, sorry this did not make it into 0.49.0. We are going to release it in 0.49.1.

Backport PR: #2473

**Comment by stevepentland** [comment]
> @stevepentland hey, sorry this did not make it into 0.49.0. We are going to release it in 0.49.1.
> 
> Backport PR: #2473

Thanks so much for the clarification @brettlangdon, much appreciated!

**Comment by brettlangdon** [comment]
v0.49.1 has been released!

**Comment by stevepentland** [comment]
> v0.49.1 has been released!

Thanks so much!

**Comment by Kyle-Verhoog** [comment]
Going to close this one out now 🙂. Let us know if you have any issues @stevepentland!
