### ISSUE TITLE
Proposal: Add option to skip logging.basicConfig() in ddtrace-run

### ISSUE THREAD

**Issue by brettlangdon** [DataDog/dd-trace-py#2482]
Right now we always call `logging.basicConfig()` in `ddtrace-run`:

https://github.com/DataDog/dd-trace-py/blob/54be17c04b69a776ce3f6a664ebd5c608458daf4/ddtrace/bootstrap/sitecustomize.py#L36-L45

This has caused a number of issues for customers since:

1. You cannot call `basicConfig()` multiple times to update the formatter
2. For applications with their own existing logging setup they might end up with double logging since we are configuring a root handler for them

I am hesitant to suggest removing it completely since some people's logging setup might be relying on it at the moment, however it might be worth while to add an env variable which disables calling this.

```
$ DD_CALL_BASIC_CONFIG=false ddtrace-run python app.py
```

This is not an ideal solution but would offer some option for people who are impacted by this existing decision.

**Comment by jd** [comment]
100% agree. A library should never set up logging itself. 😢 
Providing facility to do it, sure, but calling it, nah.

I think your proposal is a good first step in this direction. I'd tend to think this is not the last one and I'd target for removing entirely `basicConfig` long term.

**Comment by Kyle-Verhoog** [comment]
Yup agreed as well. I've attached the 1.0 label since I think it's reasonable that we stop calling basicConfig with 1.0.

**Comment by brettlangdon** [comment]
Sounds good, I'll work on the short term fix for now, and we will keep this proposal open for 1.0 to remove `basicConfig` calls entirely

**Comment by majorgreys** [comment]
This proposal has been accepted and will be supported in 1.0.
