### ISSUE TITLE
ddtrace-run how to link trace to log 

### ISSUE THREAD

**Issue by hcheng2002cn** [DataDog/dd-trace-py#2489]
Thanks for help, want to know how we can link trace to log for django/gunicorn

the command line we used:
poetry run ddtrace-run gunicorn django_services.wsgi

Beside set the below environment variables, what else should we do ?

Thanks.

### Which version of dd-trace-py are you using?
0.49.2
We are able to get the resource on APM trace, but not able link trace to log. 
We  set environment variables (DD_ENV/DD_SERVICE/DD_VERSION):
```
             - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_TRACE_ENABLED
              value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_TRACE_DEBUG
              value: "true"
            - name: DD_TRACE_DJANGO_ENABLED
              value: "true"
            - name: DD_TRACE_STARTUP_LOGS
              value: "true
```
### What is the result that you get?
<img width="1228" alt="Screen Shot 2021-06-01 at 12 03 53 AM" src="https://user-images.githubusercontent.com/1393615/120280703-de7e2e80-c26c-11eb-853a-aa1fd8456257.png">

### What is the result that you expected?
we want link trace to the log.

**Comment by brettlangdon** [comment]
@hcheng2002cn thank you for reaching out. I am sorry you are having issues getting this working.

Do you have some example logs you could share with us? We can help validate if they are in the correct/expected format.

Would you be able to share any logging configuration you are using (besides our env variables)? For example, do you setup any handlers/formatters on your application?

If you would prefer not to share that information here, would you be able to reach out to support@datadoghq.com (and reference this issue) and we can help dig into your account further.

**Comment by hcheng2002cn** [comment]
@brettlangdon mail sent to support@datadoghq.com. thanks !

**Comment by majorgreys** [comment]
Thanks for opening the support card. We will track it there!

**Comment by caleb15** [comment]
@hcheng2002cn do you mind posting the fix here? The linking is also not working for us in some cases.
