### ISSUE TITLE
dependency graph: map ddtrace pip package to DataDog/dd-trace-py repo

### ISSUE THREAD

**Issue by ntravis** [DataDog/dd-trace-py#2494]
this is not an issue with ddtrace itself, but with the Github dependency graph. It appears that an admin from the Datadog Github org may be able to correct this via Github's virtual assistant but I cannot submit a request for you.

You may wish to see more details of my original report here (i.e. that ddtrace is attributed to Peloton's outdated fork instead of this repo): https://github.com/dependabot/dependabot-core/issues/3828

TL;DR to correct:
- Visit the github support page - [link](https://support.github.com/contact)
- select appropriate options until you are able to type in "dependency graph resolves to wrong repo"
- a button for a virtual assistant will show up
- going through that prompt should allow you to resolve the errant attribute in the dependency graph
- may want to double check other packages but I only have exposure to .NET and Python

from my attempt:
### Transcript:
- **from_agent**: Hi, @ntravis. Let's help you request a remapping of your package!  Sounds good!
- **from_user**: *Sounds good!*
- **from_agent**: What ecosystem does your package belong to?
- **from_agent**: You can pick between rubygems, npm, pip, maven, nuget, and composer.
- **from_user**: *pip*
- **from_agent**: You've selected the pip ecosystem. Is that correct?  Yes, that's right No, that's incorrect
- **from_user**: *Yes, that's right*
- **from_agent**: Okay, what is the name of your package?
- **from_user**: *ddtrace*
- **from_agent**: Great, we'll be taking a look at the package you've selected, 'ddtrace'. Is that right?  Yes, that's right No, that's incorrect
- **from_user**: *Yes, that's right*
- **from_agent**: Which repository should 'ddtrace' (pip) be mapped to? Paste in the URL of the repository, please.
- **from_user**: *https://github.com/Datadog/dd-trace-py*
- **from_agent**: Thanks! Validating, please wait...
- **from_agent**: It looks like either datadog/dd-trace-py doesn't exist or you are not an admin, only an admin can make this request

**Comment by brettlangdon** [comment]
Thanks @ntravis I was able to open a ticket for this. I'll keep this open until I get confirmation of the remapping

**Comment by brettlangdon** [comment]
This is now resolved!
