### ISSUE TITLE
[Question] spanning across sub-processes

### ISSUE THREAD

**Issue by thehesiod** [DataDog/dd-trace-py#250]
In our application we have a process pool of botocore workers.  Is there a way, in general, to ensure that sub-processes can chain up to their parent process traces?

I'm guessing the right context details needs to be transferred to the sub-process to make things work.

**Comment by thehesiod** [comment]
btw for asyncio I found I could do it by serializing the parent span in the base process via:

```python
        dd_span = tracer.get_call_context().get_current_span()
        attrs = {'name', 'service', 'resource', 'span_type', 'trace_id', 'span_id', 'parent_id', 'start'}
        dd_span_info = {n: getattr(dd_span, n) for n in attrs} if dd_span else None
```

then smashing it in in the child process:

```python
try:
        if dd_span_info:
            dd_ctx = tracer.get_call_context()
            parent_span = Span(tracer, **dd_span_info, context=dd_ctx)

            dd_ctx._current_span = parent_span

            task = asyncio.Task.current_task(loop=self._loop)
            set_call_context(task, dd_ctx)
finally:
            if dd_span_info:
                set_call_context(task, None)
```

**Comment by thehesiod** [comment]
looks like this may not draw the flow correctly, I'm guessing there's some logic to detect when the parent span was closed.  In this case there should be ~20 s3 ops in parallel but it seems to be showing them serially so not sure exactly what's going on.

<img width="1254" alt="screen shot 2017-04-12 at 9 48 38 pm" src="https://cloud.githubusercontent.com/assets/4001789/24990927/34fa42b4-1fcc-11e7-97a1-9e910208f321.png">

**Comment by thehesiod** [comment]
hmm, reading http://pypi.datadoghq.com/trace/docs/#distributed-tracing it seems like perhaps the asyncio patchers should support parent trace/span IDs

**Comment by thehesiod** [comment]
ok, I think I've implemented something acceptable in my PR: https://github.com/DataDog/dd-trace-py/pull/248 It adds optional kwargs that follows the aiohttp style for distributed spans

**Comment by palazzem** [comment]
Related to #247 that has been solved. Closing this one too.
