### ISSUE TITLE
No "django.request" traces being captured in Django 3.1

### ISSUE THREAD

**Issue by rnegron** [DataDog/dd-trace-py#2559]
Hello! We recently updated to Django 3.1 from Django 3.0 and noticed we were not longer receiving `django.request` traces. At the same time, we started to receive a proportional amount of `django.middleware` traces. The middleware traces do not contain the request information though, so we would like to get those request traces back.

### Which version of dd-trace-py are you using?

0.49.3

### Which version of pip are you using?

21.0.1

### Which version of the libraries are you using?

celery 5.1.0
datadog                               0.41.0
ddtrace                                0.49.3
Django                                          3.1.12
django-add-default-value                        0.9.0
django-admin-autocomplete-list-filter           0.1.3
django-celery-beat                              2.2.0
django-configurations                           2.2
django-cors-headers                             3.7.0
django-extensions                               3.1.3
django-filter                                   2.4.0
django-log-request-id                           1.6.0
django-migration-linter                         2.5.3
django-rest-passwordreset                       1.1.0
django-safedelete                               1.0.0
django-simple-history                           3.0.0
django-storages                                 1.11.1
django-timezone-field                           4.1.2
django-waffle                                   2.2.0
djangorestframework                             3.12.4
djangorestframework-api-key                     2.0.0
djangorestframework-simplejwt                   4.7.1

### How can we reproduce your problem?

Use Django 3.1.12 along with ddtrace version 0.45.0 or current latest 0.49.3

### What is the result that you get?

Here's how the dropoff for `django.request` and the rise in `django.middleware` spans looks like in Datadog for our staging environment. It coincides with a release where we upgraded to Django 3.1.12 from Django 3.0.14.
<img width="652" alt="Screen Shot 2021-06-17 at 2 50 59 PM" src="https://user-images.githubusercontent.com/4153103/122567231-71adb700-d016-11eb-9c3e-8bdb61c1005e.png">
<img width="650" alt="Screen Shot 2021-06-17 at 2 51 05 PM" src="https://user-images.githubusercontent.com/4153103/122567237-74101100-d016-11eb-9957-7ba3a5e21da4.png">

Wondering if this a configuration issue on our end or if there is some sort of incompatibility between this library and Django 3.1 request tracing.

### What is the result that you expected?

After upgrading to Django 3.1, we expected to still see traces for `django.request`.

**Comment by majorgreys** [comment]
@rnegron Thanks for reporting this with all those details. Can you also say how the application is instrumented with ddtrace? Are you using `ddtrace-run` or a different method? What if any environment variables are you setting to configure the tracer?

**Comment by rnegron** [comment]
@majorgreys Thanks for the prompt reply! We are indeed using `ddtrace-run` as follows:

```ddtrace-run gunicorn ourappname.asgi:application```

Here are the environment variables we are using:

```
DD_VERSION = 0.1
DD_ENV = staging
DD_SERVICE = ourappname
DD_LOGS_INJECTION = true
DD_TRACE_ENABLED = true
DD_TRACE_SAMPLE_RATE = 0.5
```

**Comment by rnegron** [comment]
@majorgreys Any updates? Can you confirm if this is an issue with `ddtrace`'s compatability with Django 3.1?

**Comment by rnegron** [comment]
We decided to roll back our Django installation and can confirm that `django.request` traces came back. I'm guessing this has to do with Django 3.1's [async views](https://docs.djangoproject.com/en/3.1/releases/3.1/#asynchronous-views-and-middleware-support)? In any case, I think it's worth adding a warning in the README that this package doesn't fully support Django 3.1 yet!

**Comment by Kyle-Verhoog** [comment]
Hey @rnegron we can confirm that we're seeing it too in Django 3.1+. Working on a fix for it that should be coming early next week!
