### ISSUE TITLE
Possibility to store tags to log

### ISSUE THREAD

**Issue by ashrub-holvi** [DataDog/dd-trace-py#2572]
Hello, we think about using ddtrace for adding our custom correlation ids to logs.
I see that using tags for custom data is [recommended](https://github.com/DataDog/dd-trace-java/issues/507), but, as I can [see](https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/logging/patch.py#L28), tags are not propagated to logs now.
I guess it's simple change (see [this](https://github.com/ashrub-holvi/dd-trace-py/commit/5fdcb9699030f302b63479fda5ce801666e1fb3f) commit), but as your [contribution guide](https://github.com/DataDog/dd-trace-py/blob/master/docs/contributing.rst) asks discuss in issue, I want to ask what do you think about such feature generally?
I think, we can allow to put particular tag to log, but, maybe it's idea for the next iteration.

Related, but more specific question [here](https://github.com/DataDog/dd-trace-py/issues/2017).

**Comment by ashrub-holvi** [comment]
Additional question about `str()` usage, maybe better to use something from `six` lib?

**Comment by brettlangdon** [comment]
hey @ashrub-holvi thanks for bringing this up.

Can you describe your use-case and desired/expected result? I want to make sure we approach this in the right manner.

**Comment by ashrub-holvi** [comment]
Hey @brettlangdon thanks for answer, the idea is just to improve our logging and as we already use datadog, using the ddtrace looks like a good enough approach for that.
I hope pseudocode below will show the idea, let's imagine we process order:
```
with add_order_id_to_log(order):
    do_some_action_with_order()  # order_id must be in all log messages
    do_some_action_with_order_item():  # order_id and item_id must be in logs
```
of course `do_some_action_with_order()` can run celery task and so on.
I guess same result can be achieve by redefining `trace_id` and `span_id`, but as mentioned [here](https://github.com/DataDog/dd-trace-java/issues/507) - no good way for that.

**Comment by ashrub-holvi** [comment]
Of course, it make sense if tags can be propagated same like trace_id and span_id, I am already not sure that it is.

**Comment by ashrub-holvi** [comment]
It will require some time for making MWE, but in our env I see that tags are not propagated to celery task and django signal handler. And looks like span_id not propagated to celery task.

**Comment by ashrub-holvi** [comment]
> I guess same result can be achieve by redefining trace_id and span_id, but as mentioned here - no good way for that.

Now I think that redefining is not a good idea, we want to have additional information, fro example, for find all requests/operations where particular order/payment was processed.

**Comment by ashrub-holvi** [comment]
So, I guess `trace_id` will be good enough for most cases, sorry for disturbing.
