### ISSUE TITLE
cannot import name '_rand' from 'ddtrace.internal' 

### ISSUE THREAD

**Issue by mohneeshdamade** [DataDog/dd-trace-py#2578]
### Which version of dd-trace-py are you using?
0.49.3

### Which version of pip are you using?
21.1.1

_ddtrace requires pip>=18 to install one of our pre-built wheels_

### Which version of the libraries are you using?
attrs==21.2.0
boto3==1.17.95
botocore==1.20.95
certifi==2021.5.30
chardet==4.0.0
datadog==0.41.0
ddtrace==0.49.3
decorator==5.0.9
dynaconf==3.1.4
export==0.1.2
fastjsonschema==2.15.1
future==0.18.2
jmespath==0.10.0
jsonpickle==2.0.0
packaging==20.9
pip-check-reqs==2.2.2
protobuf==3.17.3
pyparsing==2.4.7
python-dateutil==2.8.1
python-json-logger==2.0.1
requests==2.25.1
s3transfer==0.4.2
six==1.16.0
tenacity==7.0.0
urllib3==1.26.5
wrapt==1.12.1

### How can we reproduce your problem?
Trying to add tracing in python lambda application

Imported the ddtrace library 
and used the ddtrace.patch_all()

- Added the library in a lambda layer to the function.
- Added the enviroment variables for DD

### What is the result that you get?

[ERROR] Runtime.ImportModuleError: Unable to import module 'test': cannot import name '_rand' from 'ddtrace.internal' (/opt/python/ddtrace/internal/__init__.py)

### What is the result that you expected?
DD trace should be configured and tracing should be enabled

**Comment by jd** [comment]
This sounds like some installation/deployment failure.

Could you provide the full command list you typed or maybe a way to reproduce it?
That'd help us determine what is wrong here.

Thank you!

**Comment by mohneeshdamade** [comment]
I see, 
- Installed ddtrace : pip install ddtrace
- Zipped the dependencies (including ddtrace library) and uploaded to lambda layer attached to the function
- Tried to execute the function and resulted in the error.
- Function code is as simple as :
`import ddtrace 
ddtrace.patch_all()
// lambda handler starts after this
`

**Local Environment** :
- OS : Windows 10
- IDE : InetlliJ
- Python : 3.8

Lambda Environment :
Runtime : Python 38

**Environment Variables :**
![image](https://user-images.githubusercontent.com/26876273/123087546-4d9d0c00-d442-11eb-9d20-0aeb46e4cb50.png)

**Comment by jd** [comment]
Your zipping is probably at fault. `ddtrace` contains binaries that are OS and arch dependent, so you have to be sure to ship those files for the correct OS and architecture.
I imagine this is not the case, for example, if you install ddtrace on darwin (macOS) and then upload to a Linux server, it won't work.

You probably need to review your deployment method.

**Comment by mohneeshdamade** [comment]
Okay, Thanks for the explanation.

I will try to use docker and build the dependencies to match the environments.
Found this in the documents as well :
https://docs.datadoghq.com/serverless/installation/python/?tab=custom#using-the-package 
![image](https://user-images.githubusercontent.com/26876273/123090976-6c9d9d00-d446-11eb-8c43-1bfbbe62b8ba.png)
