### ISSUE TITLE
Proposal: 1.0 branch strategy

### ISSUE THREAD

**Issue by Kyle-Verhoog** [DataDog/dd-trace-py#2594]
To minimize the noise in getting to 1.0 (number of PRs, CI runs, etc) we can create a `1.0-dev` branch to collect all removals.

**Comment by brettlangdon** [comment]
sgtm, we'll need a strategy to keep it up to date with `master`.

**Comment by jd** [comment]
I'm not sure I fully understand the proposal. Is your plan to do a giant PR at the end merging `1.0-dev` in `master`?

**Comment by Kyle-Verhoog** [comment]
Yes, still doing our normal PR process just targeting `1.0-dev` instead of `master`. When we're good to go 1.0 then it will be one big PR to master.

**Comment by jd** [comment]
If you do the regular PR dance, how does that "minimize the noise"? 🤔

**Comment by Kyle-Verhoog** [comment]
It saves having a bunch of PRs open that need to be kept up to date individually for an unknown amount of time.

**Comment by jd** [comment]
> It saves having a bunch of PRs open that need to be kept up to date individually for an unknown amount of time.

You mean that 1.0 is not the next release and that we don't know how it'll get out so we can't merge those PR right away?

**Comment by Kyle-Verhoog** [comment]
Yeah exactly

**Comment by majorgreys** [comment]
#2663 has incorporated this strategy.
