### ISSUE TITLE
Logs not being sent to datadog

### ISSUE THREAD

**Issue by antiformio** [DataDog/dd-trace-py#2596]
### Which version of dd-trace-py are you using?
ddtrace==0.49.3 

### What is the result that you get?
No logs being pushed to datadog

### What is the result that you expected?
logs on datadog

Im having issues sending logs to datadog, im running ddtrace 0.49.3 and django 2.2 and i have this on my settings file:
ddtrace.monkey.patch(logging=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler'
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'ddtrace': {
            'handlers': ['console'],
            'level': 'WARNING',
        }
    },
}

I have tried to use patch_all on settings but that makes the build of the server hang, not sure why..

**Comment by Kyle-Verhoog** [comment]
Hi @antiformio!

Just to be clear: the logs will not be sent automatically to Datadog. You still need to forward the logs to the agent using one of the methods described here: https://docs.datadoghq.com/logs/log_collection/python/?tab=jsonlogformatter

As for the application hang: we've seen this before with the django dev server `python manage.py runserver ...`. Is this also the case for you?
