### ISSUE TITLE
Proposal: Add endpoint to tracer to allow switching log level without restarting application

### ISSUE THREAD

**Issue by ZStriker19** [DataDog/dd-trace-py#2611]
The need for users to restart their applications in debug mode in order to get the proper logs for troubleshooting is a large pain point.  Oftentimes users have issues that either start after some time, only occur intermittently, or will take a long time to recreate/redeploy with debug logging (oftentimes requiring x-team collaborations).  Some users are very burdened by having to restart production services to test theories with debug mode on and then collect sample logs before restarting again.

In order to change the logging level on the fly, the tracer would need to listen on an endpoint, similar to[ how the Datadog agent does]( https://docs.datadoghq.com/agent/troubleshooting/debug_mode/?tab=agentv6v7#containerized-agent ) (which has this functionality). When the endpoint is hit, we can change the logging level.

The ability to turn debug logging on and off via a CLI command which pings the endpoint e.g `ddtrace-run debug_mode`  would alleviate a significant amount of reluctance and back & forth coms while users get permission to start stop services after having changed env vars. 

The logging library makes this possible with:
```
    logger = logging.getLogger()
    logger.setLevel(logging.DEBUG)

```

**Comment by Kyle-Verhoog** [comment]
:+1: at a high level. One big problem we have right now with startup logs is that the tracer can be configured further in-code at runtime after the startup logs are produced.

One challenge we might have is if multiple tracer instances or multiple python apps are running on the same machine then we'd need some protocol to connect to a specific instance. Having a fixed port for this endpoint wouldn't work and if the port is output in the logs the log entry might be lost by the time the user wishes to interact with the tracer. 🤔

**Comment by emmettbutler** [comment]
Moved to our team's internal backlog
