### ISSUE TITLE
Python hangs in ddtrace module after completing Pytest run

### ISSUE THREAD

**Issue by gamerdonkey** [DataDog/dd-trace-py#2630]
### Which version of dd-trace-py are you using?

`ddtrace==0.49.3`

### Which version of pip are you using?

`pip 21.1.2`

### Which version of the libraries are you using?

`Python 3.8.10`

```
datadog==0.42.0
ddtrace==0.49.3
pytest==6.2.4
```

### How can we reproduce your problem?

Running a complete pytest suite on many (about 30) modules with functions wrapped by the tracer. Only occurs with Python 3.8.10. 

### What is the result that you get?

Pytest completes all tests successfully and finishes its teardown, but hangs indefinitely on exit. There is no output, and the process must be killed. Attaching a GDB debugger with python extensions to the stuck process reveals the following backtrace:

```
(gdb) py-bt
Traceback (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
  File "/usr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 857, in start
    self._started.wait()
  File "/usr/local/lib/python3.8/dist-packages/ddtrace/internal/periodic.py", line 454, in _start
Python Exception <class 'UnicodeDecodeError'> 'ascii' codec can't decode byte 0xc2 in position 2111: ordinal not in range(128):
Error occurred in Python: 'ascii' codec can't decode byte 0xc2 in position 2111: ordinal not in range(128)
```

### What is the result that you expected?

Pytest to complete and the Python process to exit successfully. Testing in 3.7.10 and 3.6.10 completes as expected, and running only a subset of tests also exits properly.

We have been able to work around this issue by disabling ddtrace during tests via the `DD_TRACE_ENABLED` environment variable.

**Comment by jd** [comment]
This looks suspicious. We also use pytest extensively in our test suite in ddtrace repo and never saw that.
Do you have a way to reproduce the issue with a minimal test case?

**Comment by majorgreys** [comment]
@gamerdonkey Would you be able to give an example of a test case with the traced function calls or a minimal reproduction?

**Comment by Kyle-Verhoog** [comment]
Closing as we haven't seen this issue or been able to repro it. Please feel free to re-open if the issue it is still occurring 🙂
