### ISSUE TITLE
Pytest : TestReport' object has no attribute 'wasxfail

### ISSUE THREAD

**Issue by shughes-uk** [DataDog/dd-trace-py#2697]
### Which version of dd-trace-py are you using?
0.52
### Which version of pip are you using?
21.1.3
_ddtrace requires pip>=18 to install one of our pre-built wheels_

### Which version of the libraries are you using?

pytest 6= 2.4
### How can we reproduce your problem?

```python
import pytest

pytestmark = pytest.mark.skip(reason="reason")

@pytest.mark.xfail(reason="xfaily")
def test_check():
    pass

@pytest.mark.xfail(condition=False)
def test_check1():
    pass

```
Causes 
```
*** AttributeError: 'TestReport' object has no attribute 'wasxfail'
```

We use this to skip whole modules of tests, and the end result is you have tests that are skipped, but also marked xfail. 

Conditional xfails also produce this error.

**Comment by Yun-Kim** [comment]
Hi @shughes-uk, thanks for reaching out and making a pull request for a fix! I've reproduced your issue and am working on putting out a more concise fix.

**Comment by shughes-uk** [comment]
> Hi @shughes-uk, thanks for reaching out and making a pull request for a fix! I've reproduced your issue and am working on putting out a more concise fix, I'll close the PR and open up a follow-up PR instead.

Thanks! Worth mentioning the `skipif` decorator also causes issues

**Comment by Yun-Kim** [comment]
> Worth mentioning the skipif decorator also causes issues

@shughes-uk what issues does the `skipif` decorator cause? I tried reproducing with the `skipif` decorator to no luck. Could you provide some more details on how I can reproduce? Thanks!

**Comment by shughes-uk** [comment]
Yes, sorry `skipif `
