### ISSUE TITLE
Proposal: don't configure logging

### ISSUE THREAD

**Issue by Kyle-Verhoog** [DataDog/dd-trace-py#2713]
`ddtrace` configures logging in `ddtrace-run` and when debug mode is enabled. Since `ddtrace` is a library it should not be configuring loggers for the application.

This would require a major version bump as users are possibly dependent on the automated logging configuration that `ddtrace` does today.

**Comment by jfly** [comment]
Can this get closed? It looks like this change happened in b68efdb2ef1c1c4547cc4bc34488ead5cc0aafd0 and recently got released with [ddtrace 1.0.0](https://ddtrace.readthedocs.io/en/stable/release_notes.html#v1-0-0):

> Default value of DD_CALL_BASIC_CONFIG was updated from True to False. Call logging.basicConfig() to configure logging in your application.

**Comment by Kyle-Verhoog** [comment]
yes!! thanks @jfly!
