### ISSUE TITLE
Add tracing support for PycURL

### ISSUE THREAD

**Issue by brettlangdon** [DataDog/dd-trace-py#2723]
Previously opened pr #2159 

Would be nice to have tracing support for the [PycURL](https://pypi.org/project/pycurl/) library.

**Comment by emmettbutler** [comment]
The request for a pycurl integration is in our team's feature backlog and is not planned for the short term. As part of the backlog it will be considered during feature prioritization.

If anyone reading this is motivated to contribute the integration, please do so.
