### ISSUE TITLE
Incorrect types for patch() and patch_all() keyword arguments

### ISSUE THREAD

**Issue by mscheifer** [DataDog/dd-trace-py#2743]
### Which version of dd-trace-py are you using?
0.51.1

### Which version of pip are you using?

20.2.3

### Which version of the libraries are you using?

fastapi==0.63.0

### How can we reproduce your problem?

I have this line of code: `    ddtrace.patch(fastapi=True)`

And then in the command line I run `mypy project_dir`

### What is the result that you get?

`error: Argument "fastapi" to "patch" has incompatible type "bool"; expected "Dict[str, bool]"`

### What is the result that you expected?

No type errors

I believe this is because the type of the patch_modules parameter should be just `bool` and not `Dict[str, bool]` because it is a keyword arguments parameter (declared with **) for these two functions. See: https://www.python.org/dev/peps/pep-0484/#arbitrary-argument-lists-and-default-argument-values

**Comment by gitpushdashf** [comment]
https://ddtrace.readthedocs.io/en/stable/advanced_usage.html#patch

I see `Dict[str, bool]`. Seems like just `bool`, I agree.

**Comment by brettlangdon** [comment]
@mscheifer and @gitpushdashf thanks! Great catch. I have opened up #2744 to address this issue.
