### ISSUE TITLE
Missing tags from metrics created from spans

### ISSUE THREAD

**Issue by nicoche** [DataDog/dd-trace-py#2746]
Hi :)

### Which version of dd-trace-py are you using?

0.51.1
____

We rely on metrics created from spans to monitor our gRPC services (e.g. `trace.grpc.errors`).
I am now trying to adapt our monitors such that they take into account the gRPC code. dd-trace-py seems to add it as the tag `error.type` (https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/grpc/server_interceptor.py#L41). According to my understanding (https://docs.datadoghq.com/tracing/guide/metrics_namespace/#errors & https://github.com/DataDog/dd-trace-py/issues/1492), this tag is likely not exported to metrics.

From that, 3 questions:
- Is that correct?
- I seem to understand that dd-trace-py will soon handle this instead of the agent; is there any ETA/issue to follow on that topic?
- Can I help to move forward with this?

Thanks for your time!

**Comment by brettlangdon** [comment]
>     * Is that correct?

Yes you are correct. That tag is added as a span tag and is not added to any `trace.*` metrics that we generate for APM.

>     * I seem to understand that dd-trace-py will soon handle this instead of the agent; is there any ETA/issue to follow on that topic?

There are plans to move the creation of `trace.*` metrics from the agent and into this Python library. No issues to follow yet, no work has yet begun hopefully soon 🤞🏻.

>     * Can I help to move forward with this?

Nothing yet! This is all blocked on our side to kick-start it.


While we are planning on moving metrics generation into this library it will still have the same tag constraints that the existing metrics have. Meaning we will unlikely be able to accommodate the request to add `error.type` tag to the `trace.grpc.errors` metrics.

However!

I suggest you review our docs for [Trace Search and Analytics](https://docs.datadoghq.com/tracing/trace_search_and_analytics/) as well as the docs for the beta [Span-to-metrics](https://docs.datadoghq.com/tracing/generate_metrics/) both/either of these should be able to achieve what you are looking to accomplish.

Please let me know your thoughts and if these are of any help to you.

**Comment by nicoche** [comment]
Hey @brettlangdon 

Thanks for your time! That answers pretty much all of my questions.
I've looked into the documentation you mentioned and as you said, we might be able to workaround our issue with a combination of those two
