### ISSUE TITLE
flask view_args doesnt support non-string arguments

### ISSUE THREAD

**Issue by yawhide** [DataDog/dd-trace-py#2756]
flask view_args doesnt support non-string arguments even though flask allows you to create non-string url parameters.
The code here: https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/flask/patch.py#L484 assumes all `view_args` will be strings.

### Which version of dd-trace-py are you using?
0.51.1

### Which version of pip are you using?
21

### Which version of the libraries are you using?
flask 1.1.4

### How can we reproduce your problem?
Create a route in a flask app that doesnt use string parameters. more documentation here: https://flask.palletsprojects.com/en/1.1.x/api/#url-route-registrations

### What is the result that you get?
The parameter is defined as follows:
`@app.route("/wallets/<int:container_type_value>")`
```
Aug 09 11:59:31 coin-tracker-stefan-ct--gpvg7l app/web.1 2021-08-09 18:59:31,173 WARNING [ddtrace.span] [span.py:326] [dd.trace_id=1555487579007622952 dd.span_id=3425534705218378124] - Failed to set text tag 'flask.view_args.container_type_value', 1 additional messages skipped
Aug 09 11:59:31 coin-tracker-stefan-ct--gpvg7l app/web.1 Traceback (most recent call last):
Aug 09 11:59:31 coin-tracker-stefan-ct--gpvg7l app/web.1   File "/app/.heroku/python/lib/python3.7/site-packages/ddtrace/span.py", line 322, in _set_str_tag
Aug 09 11:59:31 coin-tracker-stefan-ct--gpvg7l app/web.1     self.meta[key] = ensure_text(value, errors="replace")
Aug 09 11:59:31 coin-tracker-stefan-ct--gpvg7l app/web.1   File "/app/.heroku/python/lib/python3.7/site-packages/six.py", line 955, in ensure_text
Aug 09 11:59:31 coin-tracker-stefan-ct--gpvg7l app/web.1     raise TypeError("not expecting type '%s'" % type(s))
Aug 09 11:59:31 coin-tracker-stefan-ct--gpvg7l app/web.1 TypeError: not expecting type '<class 'int'>'
```
### What is the result that you expected?
No exceptions and no warning log.

Thanks

**Comment by brettlangdon** [comment]
@yawhide thank you for opening this issue. I have opened #2760 to address this issue.
