### ISSUE TITLE
typing: incompatible type for patch_all call

### ISSUE THREAD

**Issue by lucas03** [DataDog/dd-trace-py#2765]
### Which version of dd-trace-py are you using?

ddtrace==0.51.1

### Which version of pip are you using?

21.1.2

### Which version of the libraries are you using?

mypy==0.812

### How can we reproduce your problem?

code `ddtrace.patch_all(gevent=is_gevent_enabled)` is mentioned in [docs](https://ddtrace.readthedocs.io/en/stable/advanced_usage.html#patch-all)

### What is the result that you get?

Mypy complains with:
```
error: Argument "gevent" to "patch_all" has incompatible type "bool"; expected "Dict[str, bool]"
```

### What is the result that you expected?
mypy doesn't raise any errors

**Comment by brettlangdon** [comment]
hey @lucas03 thank you for reaching out, this has already been reported in #2743 and fixed by PR #2744.

This will be released in 0.51.2 (hopefully today).
