### ISSUE TITLE
Built-in support for grpclib

### ISSUE THREAD

**Issue by jalaziz** [DataDog/dd-trace-py#2795]
The default gRPC python support is quite lacking and projects like [betterproto](https://github.com/danielgtaylor/python-betterproto) help fill the gap. However, `betterproto` uses [`grpclib`](https://github.com/vmagamedov/grpclib) under the hood to provide an asyncio-compatible implementation of gRPC.

While I know I could add tracing support by patching `grpclib` myself, I'd still like to request that built-in support be added.

I do realize this is a bit of a farfetched request given that these are somewhat niche libraries, but it would be good to know what are the criteria for new libraries to be added and if a PR would be accepted?

**Comment by cassios** [comment]
hello. Any updates on this request?

**Comment by emmettbutler** [comment]
Apologies for the lack of response, we missed this ticket for a long time. The request for a grpclib integration is in our team's feature backlog and is not planned for the short term. As part of the backlog it will be considered during feature prioritization.

If anyone reading this is motivated to contribute the integration, please do so.
