### ISSUE TITLE
Context object type hints invalid

### ISSUE THREAD

**Issue by shughes-uk** [DataDog/dd-trace-py#2796]
Not sure if this is just an issue with pyright/pylance but it's not correctly identifying that `Context` accepts initalization arguments. So you'll get static analysis errors like ` No parameter named "trace_id"` when trying to pass them. 

Having a look at the Context class definition there's some shenanigans going on there that I think is throwing things off.   
       
```python
dd_ctx = Context(trace_id=__trace_id__, span_id=__span_id__) 
```

Workaround is just to add `# type: ignore`. We find static analysis to extremely helpful in catching bugs though so having to disable it for something like this where the function signature of `Context` may change in the future is not ideal.

Feel free to close this if you feel it's just a bug in pyright/pylance and should be resolved there rather than here.

### Which version of dd-trace-py are you using?
 0.51.2

### Which version of pip are you using?

22.1.3

**Comment by brettlangdon** [comment]
I only took a _very quick_ look at this and was able to reproduce very easily with pyright cli.

Then I found this note in the `attrs` docs: https://www.attrs.org/en/stable/types.html#pyright

Mainly this part: 

> requires explicit type annotations using the Next Generation APIs or @attr.s(auto_attribs=True) API

Which unfortunately we cannot do because we still need to support Python 2.7 in this library.

We can keep looking to see if there is a work around.

**Comment by shughes-uk** [comment]
This might be ugly but helpful https://www.python.org/dev/peps/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code

**Comment by brettlangdon** [comment]
I was thinking we might be able to use a stub file?

https://www.python.org/dev/peps/pep-0484/#stub-files

I'll still have to give it a try.

**Comment by brettlangdon** [comment]
A stub file seems like a viable solution, this worked for me.

```python
# ddtrace/context.pyi
class Context:
    def __init__(self, trace_id: int, span_id: int): ...
```

```python
# sample.py
from ddtrace.context import Context


ctx = Context(trace_id=1234, span_id=4567)
```

```
$ pyright sample.py
No configuration file found.
pyproject.toml file found at /.../dd-trace-py.
Loading pyproject.toml file at /.../dd-trace-py/pyproject.toml
Pyproject file "/.../dd-trace-py/pyproject.toml" is missing "[tool.pyright] section.
stubPath /.../dd-trace-py/typings is not a valid directory.
Assuming Python platform Darwin
Searching for source files
Found 1 source file
0 errors, 0 warnings, 0 infos
Completed in 0.57sec
```


I'll discuss with the team and we can figure out how we want to handle.

**Comment by shughes-uk** [comment]
Awesome!

**Comment by Kyle-Verhoog** [comment]
I think this was indirectly addressed when we moved away from using attrs for `Context`: https://github.com/DataDog/dd-trace-py/pull/2900 so this shouldn't be an issue anymore 🙂
