### ISSUE TITLE
Proposal: Do not use an `AgentWriter` to test connection to the agent

### ISSUE THREAD

**Issue by brettlangdon** [DataDog/dd-trace-py#2808]
As a follow-up to #2807 which is a mitigation of an issue. We should consider not using the tracer's writer (or even a background/threaded writer) to determine if we can properly connect to the trace agent.

Some alternatives are:

- send a manual/static payload that matches what the code is trying to do today
- just make an http request to `GET /` which will return a 404, but a 404 means we can connect
- make a request to `GET /info` which at best case will give us additional information we can debug, or a 404 (older versions of the trace agent) which still tells us we can connect to it

Should be easy enough to manually make an http call given our helper code:

```python
agent_url = tracer.writer.agent_url  # Is there a better way to get this?

conn = get_connection(agent_url)
try:
    conn.request("GET", "/info")
    resp = compat.get_connection_response(conn)

    status, body = resp.status, resp.read()
finally:
    conn.close()
```

**Comment by Kyle-Verhoog** [comment]
:+1: yeah one complication that you outlined is retrieving the configured agent url to use. I don't think there's a better way since the writer can always be configured manually in code and so we'd have to get it from the writer to ensure we're using the right one.

**Comment by emmettbutler** [comment]
@brettlangdon I think [this](https://github.com/DataDog/dd-trace-py/blob/dc89bf63f65101792a43da7a2168f7fc468146ad/ddtrace/internal/writer/writer.py#L265) is the logic you're proposing to replace. Is that right?

**Comment by emmettbutler** [comment]
Ah hah - since the `AgentWriter` doesn't start its worker thread until the first `write()` call ([source](https://github.com/DataDog/dd-trace-py/blob/0eecbc8b26fce7afa3fef40b0dfb0b865e18539f/ddtrace/internal/writer/writer.py#L347)), I think this is no longer an issue.
