### ISSUE TITLE
[enhancement] aiohttp client tracing

### ISSUE THREAD

**Issue by thehesiod** [DataDog/dd-trace-py#285]
This would be useful not only for the obvious reasons of being able to trace aiohttp client queries, however has side-benefits like tracing each request made from aiobotocore.

I'm adding this as a issue because I just found that botocore/aiobotocore doesn't trace the underlying retry requests, and right now only convey back the information from the last request.  This is useful in our case because we want to log the request IDs of AWS requests that timed out so we can open a support case.

**Comment by thehesiod** [comment]
feel free to assign to me because I need to use this soon.  Will be part of my larger asyncio PR: https://github.com/DataDog/dd-trace-py/pull/248

**Comment by palazzem** [comment]
Thanks for reporting this improvement! I think you can make an instrumentation for the underlying request, just working on the client right? something similar has been done for the built-in `httplib` (see #137). Does aiobotocore uses `requests` or `httplib` under the hood?

**Comment by thehesiod** [comment]
aiobotocore uses aiohttp, so by adding this we'd trace all the retries.  Thanks for the hints.  botocore uses a vendored requests so we'd have to be careful about supporting that.

**Comment by palazzem** [comment]
Great! Thank you for all those contributions for `aiohttp`!

**Comment by thehesiod** [comment]
ping ping ;)   https://github.com/DataDog/dd-trace-py/pull/294

**Comment by brettlangdon** [comment]
hey @thehesiod, I will close this issue for now since we have #294 to track this work.
