### ISSUE TITLE
Proposal: Enable env variables for all Django configuration options

### ISSUE THREAD

**Issue by brettlangdon** [DataDog/dd-trace-py#2908]
Not every configuration for Django can be controlled by environment variables.

https://github.com/DataDog/dd-trace-py/blob/e1ab88c78050f0fbaf1232a7cc8431b097b4f048/ddtrace/contrib/django/patch.py#L49-L63

Normally this is fine, but for options like `instrument_databases`/`instrument_caches` it would be good to offer these as env variables in case a database/cache connection is created before the setting could be set.

https://github.com/DataDog/dd-trace-py/issues/2438#issuecomment-940546328

This proposal is to at minimum add `DD_DJANGO_INSTRUMENT_DATABASES` and `DD_DJANGO_INSTRUMENT_CACHES`, but we can/should consider the other settings as well.

**Comment by emmettbutler** [comment]
This appears to have been resolved by https://github.com/DataDog/dd-trace-py/pull/3026
