### ISSUE TITLE
Thread becomes "blocked" when shutting down database connection after running tests

### ISSUE THREAD

**Issue by rdark** [DataDog/dd-trace-py#2912]
We're using ddtrace in a large gevented Django/Psycopg codebase and experiencing what "feels" like a blocked thread when the database is being torn down after the tests complete.

In context of the general test suite, we are _not_ monkey-patching, so `ddtrace.internal.writer:AgentWriter` is running as a real OS thread via `ddtrace.internal.periodic.PeriodicThread`.

The tests run fine, and then stop infinitely on "Destroying test database ..."

```
test_rename_user_util_called (foo.tests.integration.foo_user.test_tasks.RenameUserTaskTest) ... ok
test_products_updated (foo.tests.integration.foo_user.test_tasks.UpdateProductsUserDataBatch) ... ok

----------------------------------------------------------------------
Ran 2 tests in 8.359s

OK
Destroying test database for alias 'default' ('test_foo')...
```

Looking at the database server, the query has actually completed (the database has been dropped), but the server is waiting for data from the client (wait event: `ClientRead`, connection status: `idle`)
```
postgres=# SELECT usename, application_name, client_addr, query_start, state_change, wait_event_type, wait_event, state, query, backend_type FROM pg_stat_activity WHERE query='DROP DATABASE "test_foo"';
 usename  | application_name | client_addr |          query_start          |         state_change         | wait_event_type | wait_event | state |           query            |  backend_type  
----------+------------------+-------------+-------------------------------+------------------------------+-----------------+------------+-------+----------------------------+----------------
 foodba |                  | 172.21.0.1  | 2021-10-14 09:40:02.172109+00 | 2021-10-14 09:40:03.79976+00 | Client          | ClientRead | idle  | DROP DATABASE "test_foo" | client backend
(1 row)

```

By stepping through commits I've traced this to commit b9b63c4b98765bfdfb9add4ad650110bd365888c - (the previous commit 5311cf6e5449b7cc7c0468813acd8f865714ed03 works without issue).

What seems to happen is that the AgentWriter thread is successfully stopped after the database connection pool is closed down. After this happens a new database connection is created by Django to issue the final `DROP DATABASE` call, which results in a final span `postgres.connection.rollback` (autocommit side effect?) sent to to `AgentWriter.write()`. As the writer is stopped, we call `start()` > `)start_service()` and a new worker thread is attempted to be started [here](https://github.com/DataDog/dd-trace-py/blob/6c1f6454593cb323bb78943c96452c3a5fbefa30/ddtrace/internal/periodic.py#L219) - which is where we appear to be blocked, waiting for a lock.

For the time being I've worked around this by overloading the `destroy_test_db()` method and calling `tracer.enabled = False` before finally removing the DB.

### Which version of dd-trace-py are you using?
`0.54.0` - though this issue was introduced in commit b9b63c4b98765bfdfb9add4ad650110bd365888c

### Which version of pip are you using?

`20.2.3`

### Which version of the libraries are you using?

```
Django==2.2.24
gevent==20.9.0
psycogreen==1.0.2
psycopg2==2.8.6
...many others
```

### How can we reproduce your problem?

If I don't manage to solve this I'll try to get a reproducible example

### What is the result that you get?

Database connection is closed down cleanly after completing

### What is the result that you expected?

Database connection fails to be torn down

**Comment by mabdinur** [comment]
Hi @rdark,

Just following up. Are you still experiencing this issue?

**Comment by rdark** [comment]
The issue still exists AFAIAA, but a workaround was put in place to disable datadog integration during test suite runs

**Comment by jd** [comment]
One question would be, what's gevented if you don't monkey-patch the code? 🤔

**Comment by Kyle-Verhoog** [comment]
hey @rdark,

I'm going to close out the issue, please yell if it's still occurring and we can try to repro the issue. It does seem like it could be a bug and odd that no gevent monkey patching is done.
