### ISSUE TITLE
Disabling django "instrument_middleware" -> logs not linked to traces, some spans not linked together.

### ISSUE THREAD

**Issue by r-kells** [DataDog/dd-trace-py#2925]
### Which version of dd-trace-py are you using?
0.51.2

### Which version of pip are you using?
20.2.3

### Which version of the libraries are you using?

Django==2.2.x

### How can we reproduce your problem?
Haven't created a small reproducible example, I'm experiencing this in a large monolith which may have conflating factors.

- Configure Django App by calling `patch_all()` in `settings.py`
- No sampling

```
import ddtrace

ddtrace.config.env = APP_ENVIRONMENT
ddtrace.config.service = APP_NAME
ddtrace.config.version = APP_VERSION

# We are using a custom structured logger impl.
ddtrace.patch_all(logging=False)
```

Try to disable middleware using either:

- `ddtrace.config.django["instrument_middleware"] = False`  # in code
- `DD_DJANGO_INSTRUMENT_MIDDLEWARE: "false"`  # via ENV variable

Request an endpoint that renders a Django view and returns a webpage.

### What is the result that you expected?
Traces / logs should look the same as **before** trying to disable django middleware, except **without** middleware spans.

### What is the result that you get?
Everything works fine, until we disable django `instrument_middleware`:

1. logs that are inside Django middleware are not linked to traces. I suspect datadog hasn't started the trace when our middleware logger executes.
2. Spans from django request, template render, views, postgres, redis are no longer linked to the original `django.request` span.

Ex: Only a single span left for `django.request`:
 
    GET ^resource/(?P<resource_id>\d+)/(summary/)?$

### Screenshots before and after
![Screen Shot 2021-10-18 at 1 42 25 PM](https://user-images.githubusercontent.com/21321093/137781181-bdb3d08a-0309-45cb-ad74-beee76392b8e.png)
![Screen Shot 2021-10-18 at 1 42 48 PM](https://user-images.githubusercontent.com/21321093/137781195-c4aa1c8d-0792-4a02-9c84-ed7d3bd4b2f4.png)

cc @brettlangdon

**Comment by Kyle-Verhoog** [comment]
We weren't able to ever repro this issue 😕 

Please shout if this comes up again @r-kells!

**Comment by sarswamanishpl** [comment]
How can we disable django middleware span collection and keep other spans collection?
