### ISSUE TITLE
Parsing and usage of boolean environment variables doesn't work as expected

### ISSUE THREAD

**Issue by costas-basdekis** [DataDog/dd-trace-py#2978]
We cannot specify "falsy" values via environment variables, as they will be overridden by `default` in `get_env`.

Also some integrations (e.g. `botocore` for setting `distributed_tracing`) don't parse the result of `get_env` correctly, and thus cannot be changed via environment variables.

I would like to set `config.botocore["distributing_tracing"]` to `False` via the `DD_BOTOCORE_DISTRIBUTED_TRACING` environment variable, but because the default is `True`, there is no way to change the semantics of the setting to disable the behaviour.

There are two issues, and if either of them was fixed, the problem would be fixed.

I would be happy to provide a fix for both of them, or be directed to a way to fix it, without having to add extra code to my project.

## Empty environment variables are assumed to be missing

If you do `DD_BOTOCORE_DISTRIBUTED_TRACING=` (an empty string), [the relevant code](https://github.com/DataDog/dd-trace-py/blob/e7a73336ab7c4c1479d504f86730c4dfaeb2e5f7/ddtrace/utils/formats.py#L47-L58) will replace it with `default`, in which case it would be `True`:

```python
def get_env(*parts, **kwargs):
    ...

    # env = "DD_BOTOCORE_DISTRIBUTED_TRACING"
    value = os.getenv(env) # value = ""
    ...

    # legacy = None
    value = value or legacy # value = None
    # default = True
    return value if value else default # return True
```

The fix would be to check for `None`, instead for "falsy":

```python
if value is None:
    if legacy is not None:
        value = legacy
    else:
        value = default
```

## Usage of `get_env` for booleans should convert text values to boolean

When the `botocore` integration [uses](https://github.com/DataDog/dd-trace-py/blob/e7a73336ab7c4c1479d504f86730c4dfaeb2e5f7/ddtrace/contrib/botocore/patch.py#L39) `get_env` to define a boolean option, it should convert common boolean text values to boolean, and reject others:

```python
config._add(
    "botocore",
    {
        "distributed_tracing": get_bool_env("botocore", "distributed_tracing", default=True),
        ...,
    },
)
```
And
```python
TRUE_STRINGS = [True, "true", "yes", "y", "enable", "enabled", "1"]
FALSE_STRINGS = [False, "false", "no", "n", "disable", "disabled", "0"]


def to_boolean(value: str) -> bool:
    if value.lower() in TRUE_STRINGS:
        return True
    if value.lower() in FALSE_STRINGS:
        return False
    raise ValueError(f"Unknown boolean value '{value}'")



def get_bool_env(*parts, **kwargs):
    return to_boolean(get_env(*parts, **kwargs))
```

### Which version of dd-trace-py are you using?

`ddtrace==0.55.3`

### Which version of pip are you using?

`pip 21.2.4 (python 3.8)`

### Which version of the libraries are you using?

Not relevant

### How can we reproduce your problem?

First issue:

Before running the script:

```shell
DD_BOTOCORE_DISTRIBUTED_TRACING=
```

Run the script:

```python3
from ddtrace import config
from ddtrace.contrib import botocore
print(config.botocore["distributed_tracing"])
print(bool(config.botocore["distributed_tracing"]))
```

Outputs:

```
True
True
```

Second issue:

Before running the script:

```shell
DD_BOTOCORE_DISTRIBUTED_TRACING=False
```

Run the script:

```python3
from ddtrace import config
from ddtrace.contrib import botocore
print(config.botocore["distributed_tracing"])
print(bool(config.botocore["distributed_tracing"]))
```

Outputs:

```
False
True
```

### What is the result that you get?

I cannot meaningfully change the value of `config.botocore["distributed_tracing"]`

### What is the result that you expected?

I want to be able to meaningfully change `config.botocore["distributed_tracing"]` via the environment variable (i.e. `DD_BOTOCORE_DISTRIBUTED_TRACING`)

**Comment by costas-basdekis** [comment]
Hi @brettlangdon 

Thanks for the quick response. This should solve the problem. We're using DD in Lambda with the following layers - do you know when will we be able to use them there as well?

```
arn:aws:lambda:eu-west-1:464622532012:layer:Datadog-Python38:46
arn:aws:lambda:eu-west-1:464622532012:layer:Datadog-Extension:9
```

As for the empty string, I agree it might not be obvious how to handle it, but the documentation of the `get_env` function should be fixed in the mean time:

```
    :param kwargs: ``default`` is the only supported keyword argument which sets the default value
        if no environment variable is found
    :rtype: :obj:`str` | ``kwargs["default"]``
    :returns: The string environment variable value or the value of ``kwargs["default"]`` if not found
```

It mentions `if no environment variable is found` and `if not found`. If the variable is empty, it is there, so it should be "found". So you should amend the documentation to clarify that an empty string is considered "not found" while you figure out what's the correct approach.

I assume that if you start treating empty strings as present, it might break existing configurations. But on the other hand someone won't be able to set a variable to an empty string, where that makes sense in the context.

Two ideas, if empty strings are meaningful:
* Have a `DD_ALLOW_EMPTY_ENV_VARS` setting to allow people to opt-in in that behaviour
* Treat `VAR=<empty>` as an empty string

**Comment by brettlangdon** [comment]
@costas-basdekis I am going to try and get this fix out in a 0.55.4 release today. I am unsure how that impacts the lambda layer, but I can check with that team.

👍🏻 to updating the documentation.

> I assume that if you start treating empty strings as present, it might break existing configurations.

yes, this is my concern, but as long as we make it during a major version bump we should be good.... or we need to explicitly state that we don't support empty env variables.

**Comment by brettlangdon** [comment]
v0.55.4 is now released.

**Comment by brettlangdon** [comment]
@costas-basdekis you can follow along with this PR for updates to the Lambda layer: https://github.com/DataDog/datadog-lambda-python/pull/192

**Comment by costas-basdekis** [comment]
Thanks for the quick reply and turnaround!
