### ISSUE TITLE
"Spans from asynchronous executions will now be processed and flushed together" is a feature regression for us

### ISSUE THREAD

**Issue by adamserafini** [DataDog/dd-trace-py#3015]
Versions: 
ddtrace = "^0.53.0"
pip 20.2.2
Python 3.9.6

### How can we reproduce your problem?

The feature that was introduced in version v0.49.0 is actually unwanted for us and represents a feature regression:
"Spans from asynchronous executions (asyncio, gevent, tornado) will now be processed and flushed together."

We are heavily using asyncio tasks that are spawned from other tasks or API requests and  _we want to track these separately not as part of the 'parent' task_. We were previously doing this by decorating the task as follows:

```python
@tracer.wrap(name="chat", resource="push_notification")
async def push_notification():
   ...
```

And then calling it with:
```
asyncio.create_task(push_notification)
```

This meant the tasks would nicely appear separately to the parent task, with their own resource name, and their own latency, their own APM entry etc. etc. 

### What is the result that you get?

After v0.49.0, these "child tasks" would appear as part of the parent task and we could no longer get the monitoring we had before without introducing this custom decorator (which I pasted below). And it appears even this does not perfectly work, because the latency of the "child task" is still being included in the parent task, we think because we are trying to 'preserve' the tags of the parent task (which maybe includes the span id?).

```python
def root_trace(name: str, resource: str, preserve_tags=True):

    # mypy-friendly decorator: https://github.com/python/mypy/issues/3157
    def decorate(f: T) -> T:
        async def wrapper(*args, **kwargs):
            tags = {}
            if preserve_tags:
                if current_span := tracer.current_span():
                    tags = current_span.meta

            with tracer.start_span(name=name, resource=resource, activate=True) as span:
                span.set_tags(tags)

                return await f(*args, **kwargs)

        return cast(T, wrapper)

    return decorate
```

### What is the result that you expected?

We would like to propose that this "feature" to flush child tasks as part of parent tasks can be defined optionally in the trace decorator. The API we are imagining would be something like this:

```python
@tracer.wrap(name="some_name", resource="push_notification", root=True, inherit_tags=True)
```

Where if `root=True` then the asyncio task does not appear as part of the parent span, and if `inherit_tags=True`, then any tags that have been set in the application (eg. for business tracking / monitoring) are inherited by the child task.

**Comment by Kyle-Verhoog** [comment]
Hey @adamserafini, thanks for the detailed write-up!

So I think the solution to this is to have your tasks be separate services. The service name is what will break out the tasks by resource name, give you metrics, etc.

In your `tracer.wrap` decorator you can specify the service with `service=...` and this should give you what you need.

Let me know if this makes sense and if it works!

**Comment by adamserafini** [comment]
Hi @Kyle-Verhoog this solution won't work for us unfortunately - we _want_ the tasks to be under the same service so that they appear on the same APM page.

**Comment by brettlangdon** [comment]
Hey @adamserafini, @Kyle-Verhoog and I are discussing this to think of the best way to approach.

One option that might work is to mark the child task spans as "measured". This won't disconnect them into separate traces, but it will ensure that we compute metrics for those spans.

```python
from ddtrace import tracer
from ddtrace.constants import SPAN_MEASURED_KEY


with tracer.trace("root", service="my-svc"):
    with tracer.trace("child") as span:
        span.set_tag(SPAN_MEASURED_KEY)
```

Doing this will ensure you have `trace.root.*` **and** `trace.child.*` metrics.

It will also give you the multiple operation name drop down on the service page.

<img width="393" alt="image" src="https://user-images.githubusercontent.com/1320353/145643799-27554cfe-1307-4537-8ba6-06bdd3e3278c.png">


Do you think this solution could work for you?

**Comment by Kyle-Verhoog** [comment]
@adamserafini please let us know if this is still an issue and we can re-open the issue 🙂

**Comment by adamserafini** [comment]
@Kyle-Verhoog @brettlangdon

Sorry I never tried your suggestion here (we just carried on with the workaround above)

But.. I am going try this ^^

Thankyou :)
