### ISSUE TITLE
Feature Request: Support Click-based CLI tools

### ISSUE THREAD

**Issue by miketheman** [DataDog/dd-trace-py#3025]
Please support CLI tools that use Click https://click.palletsprojects.com/

Integration with Click would be great - since then `ddtrace-run mytool ...` would create the correct spans and traces without having to instrument the code directly.

Even better, and more generic: Having `ddtrace-run` to start a trace for the lifetime of the execution. This prevents needing to `import ddtrace` into my code and be an external wrapper and leverage `DD_SERVICE`, `DD_ENV`, etc.

**Comment by emmettbutler** [comment]
Related to https://github.com/DataDog/dd-trace-py/issues/7385

**Comment by emmettbutler** [comment]
Apologies for the lack of response, we missed this ticket for a long time. The request for a click integration is in our team's feature backlog and is not planned for the short term. As part of the backlog it will be considered during feature prioritization.

If anyone reading this is motivated to contribute the integration, please do so.
