### ISSUE TITLE
Error log still occurs when tracer is disabled (Django)

### ISSUE THREAD

**Issue by c-rhodes** [DataDog/dd-trace-py#304]
The tracer is logging the following error when disabled:

> 2017-07-05 12:54:36,552:[none]:[ddtrace.writer:134]:ERROR cannot send services: [Errno 111] Connection refused

This is occurring when integrated with Django with the following configuration:

```python
DATADOG_TRACE = {
    'ENABLED': False
}
```
From reading the [documentation](http://pypi.datadoghq.com/trace/docs/#module-ddtrace.contrib.django) which states:
> ENABLED (default: not django_settings.DEBUG): defines if the tracer is enabled or not. If set to false, the code is still instrumented but no spans are sent to the trace agent. This setting cannot be changed at runtime and a restart is required. By default the tracer is disabled when in DEBUG mode, enabled otherwise.

It seems this log should not occur. If no spans are sent to the trace agent then presumably a connection should not be established?

Package Info
------------------

> datadog==0.15.0
> ddtrace==0.8.5

**Comment by palazzem** [comment]
Thank you for reporting that! Actually it's true, when the tracer is disable it must not send traces but unfortunately we may have a bug in the `services` endpoint. So even if the tracer is disabled, we may try to send service metadata. We'll investigate further this issue that may impact other integrations.

Will keep you updated! Thanks!

**Comment by c-rhodes** [comment]
@palazzem Great, thx! :+1:
