### ISSUE TITLE
Proposal: `Context` refactor

### ISSUE THREAD

**Issue by Kyle-Verhoog** [DataDog/dd-trace-py#3044]
Problem
--------

`Context` is overridden to do several things:

- Distribute a trace across execution boundaries (threads, processes, etc). Data is a subset of the trace state (sampling priority, origin, etc) and is **immutable**.
- Store trace state **mutable**.

Having both the immutability and mutable usages makes `Context` quite confusing from a user standpoint and from an implementation perspective. Contexts appear to be immutable for users but internally are mutable which leads to weird cloning/copying: 

https://github.com/DataDog/dd-trace-py/blob/a1932e8ddb704d259ea8a3188d30bf542f59fd8d/ddtrace/context.py#L62-L67

Solution
--------

1. Split the immutable part of `Context` be a new immutable data structure called `TraceContinuation` which will represent a span + trace from another execution. This data structure will contain the active span, trace id and trace-level tags (the ones that need to be propagated).  When a trace needs to be propagated then a `TraceContinuation` can be created from a span with something like `span.continuation()` or `tracer.get_continuation()`.

2. The mutable trace state is encapsulated in a `LocalTrace` data structure which is mutable. Spans would share a reference to the same `LocalTrace` to override sampling decisions, trace-level tags etc.

**Comment by brettlangdon** [comment]
> trace-level tags (the ones that need to be propagated)

propagation shouldn't matter here right? this is still where we would store trace level tags that should be associated with all of the spans in the trace?

**Comment by brettlangdon** [comment]
> This data structure will contain the active span, trace id and trace-level tags (the ones that need to be propagated).

So the idea being:

When we inherit a context from an upstream service, we create a `TraceContinuation` which statically represents the data we are inheriting from.

When we go to create the first span in the `LocalTree` we initially populate it's data from that in any `TraceConinutation`.

The when we go to make a downstream service call, we create a new `TraceConinuation` which acts as a snapshot of the currently active span to use to populate headers for the downstream call.


It might be nice to see some pseudo-code/mock up of the interaction between these two new data structures, especially for the common scenarios we care about (inject/extract from http headers, passing traces across threads/processes, etc).
