### ISSUE TITLE
Fix root span resource name for FastAPI sub-applications

### ISSUE THREAD

**Issue by brettlangdon** [DataDog/dd-trace-py#3061]
(This should also apply to Starlette and possibly generic ASGI applications)

When you have a FastAPI sub-application the root span resource name will only be for the mounted route and not the full route.

For example:

```python
from fastapi import FastAPI


app = FastAPI()

subapp = FastAPI()

@subapp.get("/hello")
def hello():
    return {"Greeting": "Hello"}


app.mount("/sub-app", subap
```

We then end up with a trace that looks like:

```json
[
  {
    "service": "fastapi",
    "name": "fastapi.request",
    "resource": "GET /sub-app"
    "trace_id": 1,
    "span_id": 1,
    "parent_id": 0
  },
  {
    "service": "fastapi",
    "name": "fastapi.request",
    "resource": "GET /hello",
    "trace_id": 1,
    "span_id": 1,
    "parent_id": 1
  }
]
```

Having the root route only contain path information about the sub-route makes it more difficult to navigate the service page for this service.

The way we handle the routing in FastAPI/Starlette is to iterate over all of the routes and try to do a full match for the current `scope`.

The scope itself has `scope["path"]` which includes the route for the app, and `scope["root_path"]` which contains the path that the app is mounted at. So for our example, a request to `GET /sub-app/hello` will give us:

- root span middleware
  - `scope["path"] = "/sub-app/hello"`, `scope["root_path"] = ""`
- child span middleware
  - `scope["path"] = "/hello"`, `scope["root_path"] = "/sub-app"`

We could just change the route name to be `urljoin(scope["root_path"], scope["path"])` however, that can lead to cardinality issues since we want to prefer the route pattern instead of the raw request url.

**Comment by bryanhelmig** [comment]
Running into this as well. Would love a fix, we may end up enumerating and "remounting" alls sub-app routes into the parent app -- but that's a pain!

**Comment by bryanhelmig** [comment]
Also, it would be 👌 if we could also get those full paths listed in the "Endpoints" of the default service view. We just get the `root_path` there, and then spans just have the sub-`path` within that encompassing `root_path`.

**Comment by brettlangdon** [comment]
hey @bryanhelmig thanks for reaching out and sharing that you are impacted by this (that is helpful!). Is there anything different you are doing from the example above? I want to be sure if we work on it we can actually resolve your issue if it differs from the example.

**Comment by majorgreys** [comment]
> that can lead to cardinality issues since we want to prefer the route pattern instead of the raw request url.

If I'm understanding correctly, concatenating the route `path` and the mounted `root_path` would not be the raw request url and so cardinality is not an issue so much here. @brettlangdon?

**Comment by brettlangdon** [comment]
Yeah, this is the challenge, we'd need to get the route pattern from both and concatenate

the full request url will always be available via `http.url`, but we cannot use that for the resource name.

**Comment by brettlangdon** [comment]
thanks @bryanhelmig !

**Comment by brettlangdon** [comment]
#3612 has been merged in and will be released with `ddtrace==1.2.0`. Once we have an RC ready we will share here for people to try out!

**Comment by bryanhelmig** [comment]
Any guidance on availability of 1.2.0? TY!

**Comment by brettlangdon** [comment]
hey @bryanhelmig sorry for the delay, we are planning on getting RC2 out today, and then quickly the official release.

**Comment by brettlangdon** [comment]
@bryanhelmig `ddtrace==1.2.0rc2` is now available to try. Barring any issues we find in our final testing, we'll get `1.2.0` out as soon as we can.

**Comment by bryanhelmig** [comment]
Thanks @brettlangdon -- deploy going now! 🥳
