### ISSUE TITLE
Setting error metadata doesn't create an error trace

### ISSUE THREAD

**Issue by lexicalunit** [DataDog/dd-trace-py#3086]
### Which version of dd-trace-py are you using?
v0.56.1

### Which version of pip are you using?
I use `poetry` v1.1.8.

### Which version of the libraries are you using?
From the output of `poetry show`:

```
aiohttp 3.7.4.post0
aiohttp-jinja2 1.5
aiohttp-retry 2.4.6
alembic 1.7.5
asgiref 3.4.1
async-timeout 3.0.1
attrs 21.2.0
babel 2.9.1
certifi 2021.10.8
chardet 4.0.0
charset-normalizer 2.0.9
click 8.0.3
colorama 0.4.4
coloredlogs 15.0.1
datadog 0.43.0
ddtrace 0.56.1
discord-py-interactions 3.0.2
discord.py 1.7.3
dunamai 1.7.0
expiringdict 1.2.1
greenlet 1.1.2
gunicorn 20.1.0
humanfriendly 10.0
humanize 3.13.1
hupper 1.10.3
idna 3.3
importlib-resources 5.4.0
jinja2 3.0.3
mako 1.1.6
markupsafe 2.0.1
multidict 5.2.0
packaging 21.3
protobuf 3.19.1
psycopg2-binary 2.9.2
pygicord 1.0.1
pyparsing 3.0.6
pyreadline3 3.3
python-dateutil 2.8.2
python-dotenv 0.19.2
pytz 2021.3
pyyaml 6.0
requests 2.26.0
six 1.16.0
sqlalchemy 1.4.28
sqlalchemy-utils 0.38.1
supervisor 4.2.2
tenacity 8.0.1
types-python-dateutil 2.8.3
types-pytz 2021.3.3
types-pyyaml 6.0.1
types-toml 0.10.1
typing-extensions 4.0.1
urllib3 1.26.7
uvloop 0.16.0
wrapt 1.13.2
yarl 1.7.2
zipp 3.6.0
```

### How can we reproduce your problem?
```python
from ddtrace import tracer

ex: BaseException

span = tracer.current_span()
span.set_exc_info(ex.__class__, ex, getattr(ex, "__traceback__", None))

root = tracer.current_root_span()
root.set_tags(
    {
        ERROR_TYPE: "OperationalError",
        ERROR_MSG: "An error occurred during bot operation",
    },
)
```

### What is the result that you get?
Using the above code I get a trace with a Green "Ok" status like this:
![Screen Shot 2021-12-27 at 9 23 21 AM](https://user-images.githubusercontent.com/1903876/147493975-331d6240-b8a5-4dd5-b63b-231c1b6934ef.png)

Viewing details on the trace shows that it's error metadata IS set:
![Screen Shot 2021-12-27 at 9 24 08 AM](https://user-images.githubusercontent.com/1903876/147494041-2a312c65-835b-44dd-8f99-64fa61e0b577.png)

### What is the result that you expected?
This should be a red "Error" trace. Not a green "Ok" one.

**Comment by brettlangdon** [comment]
@lexicalunit the root span also needs `root.error = 1`, `span.set_exc_info` does this for you on the child span.

https://github.com/DataDog/dd-trace-py/blob/e269191fd85ea5fce0b1554338cf8cefbc862f1f/ddtrace/span.py#L462-L483

**Comment by lexicalunit** [comment]
Ty @brettlangdon! I found the same thing just now by digging through the code. It's not documented here https://ddtrace.readthedocs.io/en/stable/advanced_usage.html#span though as far as I can tell.

**Comment by brettlangdon** [comment]
> It's not documented here https://ddtrace.readthedocs.io/en/stable/advanced_usage.html#span though as far as I can tell.

thanks for calling this out, we don't clearly define how to mark a span as an error. it is only the very limited documentation for `Span.set_exc_info`
