### ISSUE TITLE
Require image for ARM64 architecture.

### ISSUE THREAD

**Issue by odidev** [DataDog/dd-trace-py#3100]
Hi Team, 

I am trying to use the  **dd-trace-py**  image on  **arm64**  platform, but it seems it is not available for arm64. 

I have successfully built the image for arm64 platform, using the command  `docker build -t image_name .` 

 

I have added a job in Github-action workflows to push images to docker hub. 

**Commit Link** - https://github.com/odidev/dd-trace-py/commit/6f93de71910630502624f55eff0ccf847b21f181

**Docker Hub Link** - https://hub.docker.com/r/odidev/dd-trace-py/tags

Do you have any plans for releasing ARM64 images? 

If interested, I will raise a PR with the above changes.

**Comment by brettlangdon** [comment]
Hey @odidev if you are referring to the `Dockerfile` in this repo, that is used for development / testing purposes only.

We already offer musllinux wheels of the `ddtrace` package on PyPI.

```
$ docker run -it --rm --platform linux/amd64 arm64v8/alpine /bin/sh
/ # uname -a
Linux d0aaeab35814 5.10.76-linuxkit #1 SMP Mon Nov 8 10:21:19 UTC 2021 aarch64 Linux
/ # apk add --no-cache python3 py3-pip
/ # pip install -U pip
/ # pip install ddtrace
Collecting ddtrace
  Downloading ddtrace-0.57.0-cp39-cp39-musllinux_1_1_aarch64.whl (3.0 MB)
     |████████████████████████████████| 3.0 MB 1.9 MB/s
Requirement already satisfied: packaging>=17.1 in /usr/lib/python3.9/site-packages (from ddtrace) (20.9)
Collecting attrs>=19.2.0
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
     |████████████████████████████████| 60 kB 2.5 MB/s
Collecting tenacity>=5
  Downloading tenacity-8.0.1-py3-none-any.whl (24 kB)
Collecting protobuf>=3
  Downloading protobuf-3.19.1-py2.py3-none-any.whl (162 kB)
     |████████████████████████████████| 162 kB 4.3 MB/s
Requirement already satisfied: six>=1.12.0 in /usr/lib/python3.9/site-packages (from ddtrace) (1.16.0)
Installing collected packages: tenacity, protobuf, attrs, ddtrace
Successfully installed attrs-21.4.0 ddtrace-0.57.0 protobuf-3.19.1 tenacity-8.0.1
```


Is there a specific reason you are looking to use our development image on arm64?

**Comment by odidev** [comment]
```
Is there a specific reason you are looking to use our development image on arm64? 

```

@brettlangdon  

Thanks for your response. I work on enabling Arm support across various open-source projects. If having arm64 image for this is useful then, I will raise a PR for this and if it's not useful to enable Arm images here, then we can close this request.

**Comment by brettlangdon** [comment]
hey @odidev, thanks! Our library is compatible with arm and we publish arm wheels to PyPI already for the package. No need to introduce a new development docker image.
