### ISSUE TITLE
pyramid crashes when 'include()' used with relative import paths

### ISSUE THREAD

**Issue by jimabramson** [DataDog/dd-trace-py#311]
We added `ddtrace-run` to our py3 + pyramid app which caused it to crash on startup with an `AttributeError` (module 'ddtrace.contrib.pyramid' has no attribute 'models').

The cause turned out to be a series of `config.include()` calls which were using relative import paths; under ddtrace, pyramid's path resolver was mapping `.foo` to `ddtrace.contrib.pyramid.foo` (i guess it changes what `__main__` means?)

Switching to absolute paths fixed the issue.

**Comment by palazzem** [comment]
@jimabramson this one has been merged https://github.com/DataDog/dd-trace-py/pull/342 ; it should fix the problem.

Closing.

**Comment by jimabramson** [comment]
confirmed, issue no longer exists with `0.9.1+master2494` - thanks.
