### ISSUE TITLE
AttributeError: 'coroutine' object has no attribute 'add_done_callback'

### ISSUE THREAD

**Issue by prsangappa** [DataDog/dd-trace-py#3133]
### Which version of dd-trace-py are you using?

ddtrace 0.57.1

### Which version of pip are you using?

pip 21.3.1

### Which version of the libraries are you using?

aioredis 1.3.1

### What is the result that you get?

```
  File "aioredis/commands/list.py", line 97, in lrange
    return self.execute(b'LRANGE', key, start, stop, encoding=encoding)
  File "ddtrace/contrib/aioredis/patch.py", line 147, in traced_13_execute_command
    task.add_done_callback(_finish_span)
```

### What is the result that you expected?

No errors

**Comment by brettlangdon** [comment]
@prsangappa thank you for reporting, we have a PR open now that should address this issue: #3095
