### ISSUE TITLE
Disabled tracker with pymongo gives AttributeError: __enter__

### ISSUE THREAD

**Issue by fredley** [DataDog/dd-trace-py#3140]
### Which version of dd-trace-py are you using?

0.57.1

### Which version of pip are you using?

31.3.1

_ddtrace requires pip>=18 to install one of our pre-built wheels_

### Which version of the libraries are you using?

You can copy/paste the output of `pip freeze` here.

pymongo[tls,srv]==3.12.3

### How can we reproduce your problem?

`patch` pymongo, but use a tracer with `enabled=False`

### What is the result that you get?

```
self = <TracedServer at 0x11d075140 for Server at 0x11d0381f0>
sock_info = <TracedSocket at 0x11d077440 for SocketInfo at 0x11d038b20>
operation = <pymongo.message._Query object at 0x11d1687d0>
args = (True, <pymongo.monitoring._EventListeners object at 0x106477a00>, <bound method Cursor._unpack_response of <pymongo.cursor.Cursor object at 0x11d14b940>>)
kwargs = {}

    def run_operation(self, sock_info, operation, *args, **kwargs):
>       with self._datadog_trace_operation(operation) as span:
E       AttributeError: __enter__

env10/lib/python3.10/site-packages/ddtrace/contrib/pymongo/client.py:124: AttributeError
```

### What is the result that you expected?

For the code to execute cleanly with ddtrace disabled.

The source of the bug seems quite clear to me. At `ddtrace/config/pymongo/client.py:124`:

```python
with self._datadog_trace_operation(operation) as span:
    result = self.__wrapped__.run_operation(sock_info, operation, *args, **kwargs)
```
However in line 102 of the same file, in `_datadog_trace_operation`:

```python
# if we couldn't parse or shouldn't trace the message, just go.
if not cmd or not pin or not pin.enabled():
    return None
```

If the pin is not enabled, `None` is returned, which cannot be used as a context manager. I'm not sure what should be returned (an empty `Span`?), or if this should be fixed in a different way.

**Comment by mabdinur** [comment]
Hey @fredley , 

We were able to reproduce this error and we are currently working on a fix. Thanks for flagging this issue
