### ISSUE TITLE
[cassandra] Queries generated by Session.execute_async do not generate spans.

### ISSUE THREAD

**Issue by jhgg** [DataDog/dd-trace-py#316]
Queries that are ran by using `Session.execute_async` do not generate spans. 

I'm in touch with @palazzem about the issue on Slack. 

Minimal reproduction, assuming you have a keyspace named `test` with a table, called `a`, with the appropriate fields. 

```py
cluster = cluster.Cluster()
keyspace = cluster.connect('test')
statement = keyspace.prepare('SELECT a, b, c FROM test WHERE a = ?')

def do_some_stuff():
    futures = []
    for i in xrange(100):
        futures.append(keyspace.execute_async(statement, {'a': 1}))

    return [
        c.result()[0]
        for c in futures
    ]
```

```
CREATE KEYSPACE IF NOT EXISTS test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'};
CREATE TABLE IF NOT EXISTS test.test (
    a bigint,
    b bigint,
    c bigint,
    PRIMARY KEY (a)
);
```

**Comment by palazzem** [comment]
@jhgg this has been fixed with #333 so that snippet should work as expected. We'll publish a new release soon, so let me know if you want to give it a try! Thank you for reporting that!
