### ISSUE TITLE
cpu stuck in memory profiling 

### ISSUE THREAD

**Issue by alangenfeld** [DataDog/dd-trace-py#3170]
Webserver application (`uvicorn` & `starlette`) stuck at 100% CPU in 
 `ddtrace/profiling/collector/memalloc.py:139` / `heap_tracker_untrack_thawed (_memalloc_heap.c:80)`

`py-spy top`
https://gist.github.com/alangenfeld/4dd201717208f7bde63ff26552d80096

`py-spy top -n`
https://gist.github.com/alangenfeld/fb51310ccf085f67fe717ebb2df9dee8

### Which version of dd-trace-py are you using?

observed in 0.57.2 and 0.57.1

### Which version of pip are you using?

pip 21.0.1

### Which version of the libraries are you using?

https://gist.github.com/alangenfeld/73336333915dd9e7e2b0a1592e38e24e

### How can we reproduce your problem?

Unclear - observed in one of our webservers but not the other 

### What is the result that you get?

CPU pegged at 100% at `heap_tracker_untrack_thawed (_memalloc_heap.c:80)`

### What is the result that you expected?

Profiling with reasonable overhead

**Comment by alangenfeld** [comment]
looks likely fixed by  https://github.com/DataDog/dd-trace-py/pull/3162

**Comment by jd** [comment]
@alangenfeld if you can give it a try, that'd be appreciated!

**Comment by alangenfeld** [comment]
Is there going to be a release soon or would I need to try from master?

**Comment by Flydiverny** [comment]
We are also seeing this in 0.56.0, probably after enabling `DD_PROFILING_ENABLED`, so we are attempting to disable this to see if this helps. :)

**Comment by jd** [comment]
The fixes have been released in 0.57.3 (and will be in 0.58 too, for the record). You can upgrade and see if that fixes everything for you.

If not, please reopen this!
