### ISSUE TITLE
httplib tracing bug returns empty response

### ISSUE THREAD

**Issue by thehesiod** [DataDog/dd-trace-py#323]
On this line: https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/httplib/patch.py#L39

it does a `return` w/o sending "resp", which ends up nulling out the response.  It should instead `return resp`

**Comment by palazzem** [comment]
Thank you! I'll look into it very soon so that we can ship a new release with some bugfixes!

**Comment by thehesiod** [comment]
any updates?

**Comment by yoichi** [comment]
I think this causes ddtrace error log when contrib.httplib.patch applied

```
cannot send services: 'NoneType' object has no attribute 'status'
cannot send spans: 'NoneType' object has no attribute 'status'
```

while conn.request actually succeed in ddtrace.api.API._put().

**Comment by thehesiod** [comment]
@palazzem ping :)

**Comment by palazzem** [comment]
@thehesiod going to review that one today so we can close and merge the PR. Sorry for the delay!

**Comment by palazzem** [comment]
@thehesiod the PR has been merged. Does it entirely solve your issue too?

**Comment by thehesiod** [comment]
@palazzem just trying to keep ticking away at my big PR: https://github.com/DataDog/dd-trace-py/pull/248 :)
