### ISSUE TITLE
Django Channels consumers are missing traceback when exceptions are thrown

### ISSUE THREAD

**Issue by gurchik** [DataDog/dd-trace-py#3238]
### Which version of dd-trace-py are you using?

~~0.53.0~~ 0.58.0

### Which version of pip are you using?

21.3.1

### Which version of the libraries are you using?

django == 3.2.11
django-redis = 5.0.0
channels == 3.0.4
channels_redis = 5.0.0
daphne == 3.0.2

### How can we reproduce your problem?

I am using code similar to the following:

asgi.py

```
import django
from channels.routing import get_default_application
from ddtrace.contrib.asgi import TraceMiddleware

django.setup()
application = TraceMiddleware(get_default_application())
```

routing.py

```
from django.urls import re_path
import my_app.consumers

websocket_urlpatterns = [
    re_path(r"^ws/test/$", consumers.TestConsumer.as_asgi()),
]
```

my_app/consumers.py

```
from channels.generic.websocket import WebsocketConsumer

class TestConsumer(WebsocketConsumer):
    groups = ["broadcast"]

    def connect(self):
        self.accept()

    def receive(self, text_data=None, bytes_data=None):
        raise Exception("An test exception")
```

I am running the application with: `ddtrace-run daphne asgi:application --bind 0.0.0.0 --port 8001`

### What is the result that you get?

When I hit the endpoint, I see the application raise the exception and the websocket is closed, as expected. However the data I get in APM is not as expected. These requests are shown as a "Hit", not an "Error". There is no indication an error occurred in the Traces (for example, a stack trace or an error attribute).
![Screen Shot 2022-02-09 at 7 15 21 PM](https://user-images.githubusercontent.com/602444/153312866-f632a10b-e0e7-492c-b213-67f4e637e5fd.png)
![Screen Shot 2022-02-09 at 7 16 27 PM](https://user-images.githubusercontent.com/602444/153313110-57612d20-b4f5-4fa0-a1c5-5fac55e74977.png)

### What is the result that you expected?

I am expecting an exception being thrown to cause the trace to be recognized as an Error in the APM, otherwise every request looks successful. I am also expecting more information in the trace, like the URI of the endpoint, although that isn't as important since I have the name of the consumer.

**Comment by mabdinur** [comment]
Hey @gurchik, 

Thanks for reaching out. We fixed a bug in our django instrumentation in `ddtrace v0.57.3`. This fix updated how we instrument channels applications. Can you try bumping your ddtrace version? This might resolve your issue.

**Comment by gurchik** [comment]
I've updated to 0.58.0, the most recent version on pypi. Now I don't get any traces at all, and my logs show this:

```Exception in callback traced_13_execute_command.<locals>._finish_span(<Future cancelled>) at /usr/local/lib/python3.10/site-packages/ddtrace/contrib/aioredis/patch.py:140
handle: <Handle traced_13_execute_command.<locals>._finish_span(<Future cancelled>) at /usr/local/lib/python3.10/site-packages/ddtrace/contrib/aioredis/patch.py:140>

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/site-packages/ddtrace/contrib/aioredis/patch.py", line 146, in _finish_span
    future.result()
asyncio.exceptions.CancelledError
```

**Comment by mabdinur** [comment]
Hi @gurchik , 

Thanks for flagging this aioredis issue. Can you share a reproduction case with your redis configuration? I will open a separate issue. 

For now can you disable the aioredis integration and see if that resolves your original issue? To do this you can run your application with `DD_TRACE_AIOREDIS_ENABLED=False` or call `ddtrace.contrib.aioredis.unpatch()` after importing `ddtrace.tracer`.

**Comment by marknotfound** [comment]
> @gurchik any word on whether `DD_TRACE_AIOREDIS_ENABLED=False` resolved the original issue?

I'll take a look in the next week or two and see if this resolves the issue for us. Thanks for checking in.

@gurchik thanks for sending this issue my way.

**Comment by emmettbutler** [comment]
I'm going to close this issue due to lack of activity. Please comment if it's still relevant, and I'll reopen.
