### ISSUE TITLE
Measure methods of Django classed based views separately.

### ISSUE THREAD

**Issue by hockeybuggy** [DataDog/dd-trace-py#324]
Hello,

While in the process of setting this up in a Django 1.11 project , we noticed that all of the methods in a class based view are being grouped together (in the list at the bottom of the APM view). E.g:

```
api.views.AccountView
api.views.HypotheticalView
```

However the methods in our class based views have different performance characteristics (we're pretty sure). It would be really nice to have each method of the views split out. E.g:

```
api.views.AccountView.get_account
api.views.AccountView.create_account
api.views.HypotheticalView.get_whimsy
api.views.HypotheticalView.create_whimsy
```

Not sure if this something happening within `ddtrace` or if this is UI issue? Happy to close this out if it's unrelated to the package.

**Comment by palazzem** [comment]
Thanks @hockeybuggy for reporting your use case. At the moment the auto-instrumentation is using the view as a `resource` and `name`. By default, we're not changing the name using the CBV methods. Can you share more details (and some snippets) for your Django view?

**Comment by hockeybuggy** [comment]
Hey @palazzem,

Sure thing. I think it may be clear if the snippets I add are in the abstract rather than real examples from our code base. This way I also don't have to find out if I have permission to share the code publicly. 

## Scenario

We have a view that is used to create, list, and provide details for the Modal `Account`s. It's a pretty standard CRUD Resource and we choose to implement it's api with a CBV. Lets say that it looks like this:

``` python
from django.http import HttpResponse, HttpRequest
from django.shortcuts import get_object_or_404
from django.views.generic import View

from accounts.models import Account

class AccountView(View):
    def create_account(self, request: HttpRequest) -> HttpResponse:
        """Creates and persists an Account"""
        Account.objects.create(name=request.POST['name'])
        return HttpResponse("account created")

    def list(self, request: HttpRequest) -> HttpResponse:
        """Returns a list of all accounts"""
        return HttpResponse("[]")

    def details(self, request: HttpRequest, account_id: str) -> HttpResponse:
        """Returns the details of a single account"""
        account = get_object_or_404(Account, pk=account_id)
        return HttpResponse("{}")
```

This would have urls that would look something like this:

```python
from django.conf.urls import url

from accounts import views


urlpatterns = [
    url(
        r"^account$",
        views.AccountView.as_view({"post": "create_account", "get": "list"}),
    ),
    url(
        r"^account/(?P<account_id>\d+)$",
        views.AccountView.as_view({"get": "get_account"}),
    ),
]
```

## Current state

Currently out of the box Datadog will only show a row in the table for `api.views.AccountView`:

<img width="698" alt="screen shot 2017-08-30 at 2 00 13 pm" src="https://user-images.githubusercontent.com/607279/29887779-8d34a446-8d8c-11e7-96dc-ef6611c50245.png">

## Desired

It would be nice to have each method of the view split out. The performance of creating an `Account` is likely very different to retrieving one.

**Comment by brett-lempereur** [comment]
I encountered this problem today while integrating Datadog APM into a Django REST Framework application that uses the ViewSet approach to exposing resources.  Given how class-based views are implemented in Django, I'm not sure there's an appropriate "one-size fits all" solution to this.  For example, Django REST Framework has an entirely separate way of achieving class-based views.

The solution we used was to adapt https://gist.github.com/beniwohli/b494bd4b368ea4095dad3b629333ae58 to support Datadog APM:

```python
class ViewSetAttributionMixin(object):
    """
    A mixin that ensures spans are correctly attributed to the method that
    handled them.
    """

    def initialize_request(self, request, *args, **kwargs):
        """
        Ensure that the resource name of a span correctly attributes the
        request to the method that handled it.

        :param request: the request from the client.
        :param args: positional request arguments.
        :param kwargs: keyword request arguments.
        """
        # Defer to the viewset to ensure the request is properly initialised.
        initialized = super().initialize_request(request, *args, **kwargs)
        # If tracing is enabled for the current request, update the resource
        # name of the span.
        span = getattr(request, "_datadog_request_span", None)
        if span is not None:
            module = self.__module__
            view_name = self.__class__.__name__
            action = self.action
            span.resource = "{}.{}.{}".format(module, view_name, action)
        return initialized
```

There's likely a similar solution for regular class-based views in Django.

**Comment by palazzem** [comment]
Thanks @brett-lempereur! It's definitely in our roadmap, but at the moment we have other priorities to follow-up (i.e. increase other frameworks compatibility). I would be very happy to merge both suggestions and leave a PR for your review.

On the other hand, if you want to provide a "quite generic" approach, feel free to open a PR! We'll review it as quick as possible!

Thank you very much!

**Comment by brett-lempereur** [comment]
Thanks @palazzem!

I don't think this is something the Datadog APM integration could reasonably be expected to handle without some extremely sketchy runtime monkey patching that would probably break things like DRF class-based views. The middleware stack in Django has no visibility of what method of a class-based view will end up handling a request - it's delegated to the function object returned by the `.as_view(...)` method. Which, incidentally, isn't the only way of achieving the same result.

It could be provided as some kind of mixin by the Django integration, but it feels like there should be a bigger question for the Django team about how they can integrate OpenTracing support into Django itself (and the DRF team, and any of the numerous Django GraphQL frameworks etc.).

**Comment by palazzem** [comment]
Thank you very much @brett-lempereur ! Agreed, it's something that is difficult to handle from our side, unless we increase the number of monkey patches we have to do (and that we would like to avoid). Having a mixin such as the one you provided in #448 would be good enough for now and can be considered an extension of manual instrumentation.

About your wider question, it's something we still need to figure out. We had the opportunity to chat with some core maintainers for other libraries (i.e. `aiohttp`) and they ended up with the idea to expose just a signaling system for tracing, instead of adding `opentracing` as a direct dependency. Then your module would instrument them via OpenTracing or any other Tracing API would exist in the future.

This is a subset of feedbacks that I wanted to share with you. The discussion is quite long and it would take time for sure.

**Comment by majorgreys** [comment]
We are currently working on a rewrite of the Django integration that will address this issue. Updates to come!

**Comment by hockeybuggy** [comment]
@majorgreys :airhorn: :airhorn: :airhorn:

Great news and good luck!

**Comment by lanterno** [comment]
👋 Hey @majorgreys is there any news on the progress here? I can't wait for this feature :)

**Comment by majorgreys** [comment]
@lanterno @hockeybuggy @brett-lempereur Can checkout the new Django integration that is now on `master`? 

Class-based views are being patched so you should gain some visibility into them:

https://github.com/datadog/dd-trace-py/blob/master/ddtrace/contrib/django/patch.py#L546

We have [documented how to migrate](https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/django/__init__.py#L91) to the new approach to configuring the `ddtrace` for the Django integration, though there is also some automatic migration that we have included to make upgrading as painless as possible. If you experience any issues with upgrading, please do raise them here or open a new issue.

**Comment by hockeybuggy** [comment]
@majorgreys Thanks very much! Sorry but I no longer have access to a Django app so I won't be able to try it out.

**Comment by majorgreys** [comment]
Closing this as v0.34.0 added support for class based views.

**Comment by mjhaller** [comment]
Does this also work for Django Rest Framework?

**Comment by majorgreys** [comment]
@mjhaller Here's a sample trace for https://github.com/encode/rest-framework-tutorial

![image](https://user-images.githubusercontent.com/155673/77803079-b1bffd00-7052-11ea-9ddd-72d9374b4a58.png)
