### ISSUE TITLE
ddtrace as dependency fails mypy check

### ISSUE THREAD

**Issue by gshaikov** [DataDog/dd-trace-py#3242]
### Which version of dd-trace-py are you using?
```
Version: 0.58.0
```
### Which version of pip are you using?
```
pip 22.0.3
```
### Which version of the libraries are you using?
```
mypy==0.931
mypy-extensions==0.4.3
```
### How can we reproduce your problem?

- Create a random lib
- Create a venv
- Install `mypy==0.931`, `ddtrace==0.58.0` and the lib in the venv
- Run `mypy .` form the lib root

If I downgrade `ddtrace==0.57.3` then `mypy` passes.

### What is the result that you get?
```
/env/lib/python3.8/site-packages/ddtrace/internal/utils/__init__.py: error: Source file found twice under different module names: "ddtrace.internal.utils" and "ddtrace.internal.utils.__init__"
Found 1 error in 1 file (errors prevented further checking)
```
### What is the result that you expected?

Mypy doesn't fail on ddtrace.

**Comment by brettlangdon** [comment]
Thanks @gshaikov for opening this issue. @Tenzer already has a PR open at #3241

**Comment by brettlangdon** [comment]
@gshaikov I am actually having some trouble reproducing this myself. Do you have a minimum single Python script which causes mypy to raise this issue?

I want to make sure we have a way to validate the fix before we merge/release it if we can.

**Comment by Tenzer** [comment]
Bisecting got me to this commit as being the culprit: https://github.com/DataDog/dd-trace-py/commit/d668dac47aea5327326979401a5504bc59323220.

I can't see anything obvious that should matter to mypy as part of that change.

**Comment by brettlangdon** [comment]
I can see `ddtrace.appsec.processor` is doing `from ddtrace.utils.formats import get_env` which  is importing the deprecated module, but even testing with a script of `from ddtrace.appsec import processor` I cannot get mypy to complain about it 🤔

**Comment by Tenzer** [comment]
Making the change you've prepared in #3243 also solves the issue for me locally, so that at least confirms it's this specific commit that caused the problem.

I'm yet to understand why it's only a problem in some setups though.

**Comment by Tenzer** [comment]
I can confirm mypy runs fine for me when I install the version from the `0.58` branch. Thank you!
