### ISSUE TITLE
Tracing with psycopg module results in very large trace size

### ISSUE THREAD

**Issue by robinovitch61** [DataDog/dd-trace-py#3250]
Thanks for taking the time for reporting an issue!

Before reporting an issue on dd-trace-py, please be sure to provide all
necessary information.

If you're hitting a bug, make sure that you're using the latest version of this
library.

### Which version of dd-trace-py are you using?
`ddtrace==0.52.0`

### Which version of pip are you using?
`22.0.3`

_ddtrace requires pip>=18 to install one of our pre-built wheels_

### Which version of the libraries are you using?

You can copy/paste the output of `pip freeze` here.

```
aiobotocore==2.0.0
aioch==0.0.2
aiofiles==0.5.0
aiohttp==3.8.1
aioitertools==0.9.0
aiokafka==0.7.2
aiopg==1.3.3
aiosignal==1.2.0
aniso8601==7.0.0
async-exit-stack==1.0.1
async-generator==1.10
async-timeout==4.0.2
attrs==21.4.0
backports.zoneinfo==0.2.1
botocore==1.22.8
certifi==2021.10.8
charset-normalizer==2.0.11
click==7.1.2
clickhouse-cityhash==1.0.2.3
clickhouse-driver==0.2.3
clickhouse-sqlalchemy==0.1.8
colorama==0.4.4
ddtrace==0.52.0
dnspython==2.2.0
email-validator==1.1.3
fastapi==0.68.1
frozenlist==1.3.0
graphene==2.1.9
graphql-core==2.3.2
graphql-relay==2.0.1
h11==0.13.0
httptools==0.1.2
idna==3.3
itsdangerous==1.1.0
Jinja2==2.11.3
jmespath==0.10.0
kafka-python==2.0.2
loguru==0.5.3
lz4==3.1.10
MarkupSafe==2.0.1
multidict==6.0.2
numpy==1.22.2
orjson==3.6.6
packaging==21.3
pandas==1.4.0
prometheus-client==0.11.0
promise==2.3
protobuf==3.19.4
psycopg2-binary==2.9.3
pyarrow==7.0.0
pydantic==1.9.0
pyparsing==3.0.7
python-dateutil==2.8.2
python-dotenv==0.19.2
python-multipart==0.0.5
pytz==2021.3
pytz-deprecation-shim==0.1.0.post0
PyYAML==5.4.1
requests==2.27.1
Rx==1.6.1
shellingham==1.4.0
six==1.16.0
SQLAlchemy==1.3.24
starlette==0.14.2
starlette-prometheus==0.8.0
tenacity==8.0.1
typer==0.4.0
typing_extensions==4.0.1
tzdata==2021.5
tzlocal==4.1
ujson==4.3.0
urllib3==1.26.8
uvicorn==0.13.4
uvloop==0.16.0
watchgod==0.7
websockets==8.1
wrapt==1.13.3
yarl==1.7.2
```

### What is the result that you get?

I have a very large postgres query I'm tracing with ddtrace (inserts about 6MB of data into postgres). When I trace with psycopg module enabled, I get an error indicating a very large (~18MB) trace is dropped:
```
trace (18235132b) larger than payload buffer limit (8388608b), dropping
```
When I run my app with `patch_all(psycopg=False)` and upload the same data with the same query, I get a reasonable trace size.

### What is the result that you expected?

I'm not sure why the trace is so large with psycopg enabled. DataDog doesn't show me the entire postgres query string anyway - I see something like:
```
INSERT INTO intervals ( field1, field2, ... ) VALUES ( ? )
```
If the trace is large because it's transmitting the whole query string, that isn't particularly necessary then.

The span count is expected (8) within the trace, 2 of which are postgres-related.

What I would love is:
1) Visibility into exactly why a given trace is large - maybe a breakdown of span sizes for a trace, or the ability to examine all the contents of a trace that is being sent to the agent
2) The ability to use psycopg module without it blowing up my trace size

**Comment by JordanP** [comment]
I see this a lot too. Also using psycopg2 and our app also have biiiggggggg queries.

**Comment by JordanP** [comment]
Hi @mabdinur ,
It would be great to have a built-in answer to this problem. Datadog is going to charge based on volume of ingested traces. Although our ingestion rate is 5% (sampling), estimated bill just for this is going to be 10k usd/month.

**Comment by brettlangdon** [comment]
@JordanP your concern is around the size of the query string being added as the span's resource name, or are you concerned about the total number of queries causing the trace to be large? (all comments in this issue suggest size of query string, I just wanted to confirm that we are talking about the same thing).

If we had a built-in feature to address this, how would you envision it working? I have a few thoughts, but would like you get your input/ideas here!

**Comment by JordanP** [comment]
Actually I am not sure what my problem is :) It's def one of these 2 options. I am leaning towards `your concern is around the size of the query string being added as the span's resource name`

I am going to experiment with 
```py
class TestFilter(TraceFilter):
    def process_trace(self, trace):
        for span in trace:
            if span.span_type != "sql" or span.name != "postgres.query":
                continue
            if len(span.resource) > 10*1024:
                span.resource = "select 'abridged by filter'"
        return trace
```
and let you know

**Comment by brettlangdon** [comment]
@JordanP if it helps, the trace agent truncates to a max size of 5k

https://github.com/DataDog/datadog-agent/blob/c23c61954e223dbf39211de802cfbd8388e670c5/pkg/trace/traceutil/truncate.go#L12-L51


the one thing to also keep in mind, if we truncate before sending to the trace agent. the agent will do some obfuscation on any sql queries, if we truncate or produce an off query then the obfuscation won't be able to happen. this shouldn't be an issue with your implementation since you are just using a sentinel value when truncating.

your experiment was similar to what I was going to suggest. rather than truncate if a max size is exceeded, just drop the whole query and set with a "query exceeded max size" fixed value.

**Comment by emmettbutler** [comment]
If I'm understanding the issue and suggestion correctly, the "drop the whole query" approach was [added to the tracer code](https://github.com/DataDog/dd-trace-py/blob/458dbe0f1e42d60306ab08910ba16106f508c5df/ddtrace/internal/_encoding.pyx#L250) not that long ago.

Given this, I'm going to close this issue as resolved. @JordanP please let me know if you have more questions or comments on this topic, and thank you!
