### ISSUE TITLE
OpenTracing compatibility

### ISSUE THREAD

**Issue by kop** [DataDog/dd-trace-py#330]
Is there any plan to support [OpenTracing](http://opentracing.io/)?

It's a part of CNCF now and it would be great to use a single standard for tracing.

**Comment by palazzem** [comment]
Hello @kop! we can say that there is some work around it, indeed we're also contributing to their in-process context propagation that is a must-have feature for us to support OpenTracing (at least at the client level). Here the reference: https://github.com/opentracing/opentracing-python/pull/52

We can keep you updated as soon as we have a clear direction on that. Thank you a lot, your interest in the topic is really appreciated!

**Comment by sjahl** [comment]
I gather that the feature this issue was waiting on upstream was merged with https://github.com/opentracing/opentracing-python/pull/64 ? What is the current status of opentracing support in dd-trace-py?

**Comment by palazzem** [comment]
Hello @sjahl! we're scheduling the work to make it happen. The ETA will be this month (May) and before shipping this functionality we'll provide a beta/release candidate to be sure the compatibility is 100%. In the meantime, we're still waiting for https://github.com/opentracing/opentracing-python/issues/65 because the OpenTracing Python version 2.0.0 is still in Release Candidate.

Our planned compatibility, will support only version 2.0 because the biggest change (in-process context propagation) is really required to make our instrumentation easier and without not so many changes.

I will keep this thread updated once we've active engineers working on it. Thank you very much!

**Comment by jimymodi** [comment]
@palazzem Waiting for this :). We are at a point where we need to take a hard call of either going ahead with dd-trace and re-write it later to make it opentracing compatibility. Or wait for this release and go ahead with opentracing. Could you ETA ?

**Comment by palazzem** [comment]
Hello @jimymodi ! we're actively working on it and one of our goal is having a beta during the next couple of weeks. You can check our progress in the `opentracer` [branch](https://github.com/DataDog/dd-trace-py/tree/opentracer). Also we have a [milestone](https://github.com/DataDog/dd-trace-py/milestone/20) with all the OpenTracing work.

I'll keep updated this thread in the meantime as soon we're near to ship a beta with OpenTracing support. Then your feedbacks will be very important.

**Comment by palazzem** [comment]
@uudashr we're almost ready! At the moment we're focusing on a bugfix and minor release. After that we'll ship a release candidate with only OpenTracing so people can test it without impacting the rest of our integrations. We'll keep you updated!

The ETA of our releases is this week.

**Comment by raybotha** [comment]
Is this still happening?

**Comment by wenbochang** [comment]
just wanted to check in, in case there's update

**Comment by palazzem** [comment]
@wenbochang @raybotha yes! we're wrapping up the last set of integrations test (you can check the PR page) and then we're good to ship this release. It should be considered a beta functionality and your feedbacks will be great to improve our OpenTracing support for the Python Tracer.

Thank you very much and sorry for the wait!

**Comment by Kyle-Verhoog** [comment]
Hi everyone,

I apologize for the delay.

We have just included the beta of our OpenTracing-compatible tracer in our `0.14.0` release.

See https://github.com/DataDog/dd-trace-py/releases/tag/v0.14.0 for more information.

Thank you all for your patience! 😄
