### ISSUE TITLE
Traces not flowing between containers and client

### ISSUE THREAD

**Issue by jordan-carson** [DataDog/dd-trace-py#3310]
Our current stack uses EKS, building with Skaffold, Kustomize, kubectl and Docker for base images. Restful service is written in FastAPI.

We have a restful service, which is served with `ddtrace-run uvicorn --host 0.0.0.0 --port 8050`. This runs within its own namespace in an EKS cluster with datadog daemons and cluster-metrics already running.

When we serve our app locally to a lower environment cluster, i.e. DEV. We receive an error stating Tenacity.RetryError. 

For info: 
We created a datadog.yml ConfigMap for the purpose of setting several env vars for datadog. This includes, DD_PROXY_HTTPS, DD_PROXY_NO_PROXY, DD_APM_ENABLED, DD_AGENT_HOST, DATADOG_TRACE_AGENT_HOSTNAME, DD_APN_NON_LOCAL_TRAFFIC etc.

This configmap is applied using Kustomize with skaffold build. When this issue is raised, what is not properly configured on datadog side / within our containers that may be raising this error?

A ticket was also opened with support team; I have also re-created the environment on a local computer and receive the same issue using docker-compose.

Reference
_Originally posted by @brettlangdon in https://github.com/DataDog/dd-trace-py/issues/3288#issuecomment-1047810652_

**Comment by brettlangdon** [comment]
> When we serve our app locally to a lower environment cluster, i.e. DEV. We receive an error stating Tenacity.RetryError.

You see the error when running in you local/dev environment and not in production? I assume this is an environment where a Datadog agent is *not* running, correct?

**Comment by jordan-carson** [comment]
I do, in my lower environment. I have now removed all related API/Hostname configurations and noticed a few issues.

The pods running the dd daemon have its own `datadog` namespace. Pods description references env vars DD_CLUSTER_AGENT_AUTH_TOKEN and DD_API_KEY. These are set to <set to the key 'dd-api_token' in secret 'dd-api_token'>. The current user cannot inspect secrets within the `datadog` namespace, thus unable to verify. I suspect they do not exist as no authenticate tokens have been created for our datadog account.

Do these vars need to be set within the `datadog` namespace? If we are tracing an application running inside a separate namespace, what additional / modification do we need to do for configuration.

**Comment by brettlangdon** [comment]
@jordan-carson sorry for the delay getting back to you.

This is something we are not experts on (agent setup in k8s/containers/etc). I would suggest opening a case with support@datadoghq.com to get feedback from someone with more experience than the Python team.
