### ISSUE TITLE
TagsetEncodeError, failed to encode x-datadog-tags

### ISSUE THREAD

**Issue by fredrikaverpil** [DataDog/dd-trace-py#3318]
### Which version of dd-trace-py are you using?

`0.58.4`

### Which version of pip are you using?

```
pip 21.2.4 from /opt/venv/lib/python3.10/site-packages/pip (python 3.10)
```
_ddtrace requires pip>=18 to install one of our pre-built wheels_

### Which version of the libraries are you using?

I would prefer not to post a `pip freeze` in public but can provide this privately. But I can say we are using [`loguru` 0.6.0](https://github.com/Delgan/loguru/releases/tag/0.6.0) with a custom sink, meaning we construct and inject `trace_id` and `span_id` manually.

### How can we reproduce your problem?

N/A

### What is the result that you get?

I'm seeing an issue in when viewing logs in datadog:

```
2022-02-24 00:43:59,585 WARNING [ddtrace.propagation.http] [http.py:97] [dd.service=conversation-svc dd.env=staging dd.version=v3-134 dd.trace_id=8793797471281061728 dd.span_id=11227667759570421022] - failed to encode x-datadog-tags

Traceback (most recent call last):
File "/opt/venv/lib/python3.10/site-packages/ddtrace/propagation/http.py", line 89, in inject
encoded_tags = encode_tagset_values(tags_to_encode)
File "ddtrace/internal/_tagset.pyx", line 160, in ddtrace.internal._tagset.encode_tagset_values
ddtrace.internal._tagset.TagsetEncodeError: Value is not valid: 'cGF0LWFwaQ==|1|1|1'
```

The value itself is a base64-encoded string and it contains a carriage return. We started seeing this error after upgrading from ddtrace 0.57.3 to 0.58.4.

When looking at the release notes, it seems you've been doing work on the span tagging.

I'm thinking we'll have to downgrade back to 0.57.3 or so to avoid disruptions, but it would be good to understand what is causing this.

### What is the result that you expected?

Not to see that `TagsetEncodeError` error at all.

**Comment by brettlangdon** [comment]
@fredrikaverpil thanks for raising this issue. I found the issue and have opened #3320 to address the bug.

I do want to confirm, this is not causing any exceptions / failed requests / crashes in your application right? Only increase in noisy warning logs? (If your app is crashing, then the PR I have open isn't good enough to address, this part of the codebase should _never_ cause that kind of crash)

**Comment by fredrikaverpil** [comment]
@brettlangdon hi, yes we believe this was not crashing the application as we'd see pods acting up if that was so. 👍 
Great to see you already found what was the cause of this!
