### ISSUE TITLE
Django Integration Defaults ignore Environment Variables

### ISSUE THREAD

**Issue by techdragon** [DataDog/dd-trace-py#332]
The Django integration should use the same environment variables as the command line tool documentation defines.

I shouldn't need to have lines like these.

```python
DATADOG_TRACE =  {
    'AGENT_HOSTNAME': os.environ['DATADOG_TRACE_AGENT_HOSTNAME']
}
```

**Comment by palazzem** [comment]
Thanks for the feedback! we can provide that as a default, instead of using simply `localhost`, so that we use the env var, our the current default as a fallback.

**Comment by wklken** [comment]
that confuse me too, I have to change some code in `ddtrace/contrib/django/apps.py`

```python
tracer.writer.api.hostname = os.environ.get("DATADOG_TRACE_AGENT_HOSTNAME") or settings.AGENT_HOSTNAME
tracer.writer.api.port = os.environ.get("DATADOG_TRACE_AGENT_PORT") or settings.AGENT_PORT
```
