### ISSUE TITLE
DD_TRACE_ENABLED=false not disabling tracing as expected.

### ISSUE THREAD

**Issue by ABM-TS** [DataDog/dd-trace-py#3379]
### Which version of dd-trace-py are you using?
0.59.0

### Which version of pip are you using?
21.2.4

### How can we reproduce your problem?

Follow the instructions in the docs to add tracing to Celery: https://ddtrace.readthedocs.io/en/stable/integrations.html#celery

Once you have done this tracing works as expected. (also I am doing it this way a purposefully not using ddtrace-run as we only want to trace celery for the time being)

However if you do this locally and are not using the DataDog agent it will continually throw errors.
```failed to send traces to Datadog Agent at http://localhost:8126/v0.4/traces,```

So, in our environment variables I try to add "DD_TRACE_ENABLED=false" (which from my understanding we should be able to add to disable all tracing)

### What is the result that you get?
ddtrace continues to try to connect and throw errors.

### What is the result that you expected?
I expect adding "DD_TRACE_ENABLED=false" to my env variables to tell ddtrace not to do any tracing or try to connect.

**Comment by ABM-TS** [comment]
I apologize this was due to me being a dope! Very important to remember to restart your pipenv when changing env variables ☺️

**Comment by brettlangdon** [comment]
No worries! Glad you were able to figure it out.
