### ISSUE TITLE
ddtrace causing UserWarnings to be raised by numpy

### ISSUE THREAD

**Issue by janbrab** [DataDog/dd-trace-py#3394]
Hello, I discovered the following issue. I am not sure right now whether ddtrace is the culprit, but **I could not replicate it without ddtrace involvement**.

Importing ddtrace seems to change the floating point subnormal numbers CPU handling mode. However, this happens only when celery module is installed. I checked and it seems like ddtrace has an integration with celery so it actually may import celery on ddtrace import.

Versions of libraries involved:

```
ddtrace==0.59.0
numpy==1.22.3
scikit-learn==1.0.2
celery[gevent]==5.2.3
```

### How can we reproduce your problem?

I have trouble reproducing this locally (MacOS), but the following Dockerfile reproduces the issue:

```
FROM python:3.9-slim
RUN python3 -m pip install ddtrace==0.59.0 numpy==1.22.3 scikit-learn==1.0.2 celery[gevent]==5.2.3

SHELL ["/bin/bash", "-c"]
RUN python3 -c $'import ddtrace\nfrom sklearn.metrics.pairwise import cosine_similarity'
```

### What is the result that you get?

Running:

```
docker build --progress=plain .
```

with the Dockerfile above produces the following warnings on output:

```
 0.754 /usr/local/lib/python3.9/site-packages/numpy/core/getlimits.py:499: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
#7 0.754   setattr(self, word, getattr(machar, word).flat[0])
#7 0.754 /usr/local/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
#7 0.754   return self._float_to_str(self.smallest_subnormal)
#7 0.754 /usr/local/lib/python3.9/site-packages/numpy/core/getlimits.py:499: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
#7 0.754   setattr(self, word, getattr(machar, word).flat[0])
#7 0.754 /usr/local/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
#7 0.754   return self._float_to_str(self.smallest_subnormal)
```

#### Ablation studies

```
FROM python:3.9-slim
RUN python3 -m pip install numpy==1.22.3 scikit-learn==1.0.2 celery[gevent]==5.2.3

SHELL ["/bin/bash", "-c"]
RUN python3 -c $'import celery\nfrom sklearn.metrics.pairwise import cosine_similarity'
```

Without ddtrace the output is clean.

```
FROM python:3.9-slim
RUN python3 -m pip install ddtrace==0.59.0 numpy==1.22.3 scikit-learn==1.0.2

SHELL ["/bin/bash", "-c"]
RUN python3 -c $'import ddtrace\nfrom sklearn.metrics.pairwise import cosine_similarity'
```

Without celery installed the output is clean.

### What is the result that you expected?

No UserWarnings on output are expected.

**Comment by emmettbutler** [comment]
I just attempted this reproduction with the latest tracer version, and didn't see the warnings described in the original post.
```
FROM python:3.9-slim
RUN python3 -m pip install ddtrace==1.15.0 numpy==1.22.3 scikit-learn==1.0.2 celery[gevent]==5.2.3

SHELL ["/bin/bash", "-c"]
RUN python3 -c $'import ddtrace\nfrom sklearn.metrics.pairwise import cosine_similarity'
```
Given that, I'm going to close this issue since it appears that the warnings have been silenced. @janbrab please let me know if you have further questions or comments on this topic, and thank you!
