### ISSUE TITLE
Resource names not displayed when longer than 32 characters

### ISSUE THREAD

**Issue by ebpitts** [DataDog/dd-trace-py#340]
When viewing traces, we noticed that some of our resource names in our custom instrumentation were not being displayed. After some debugging, we realized that any resource name longer than 32 characters did not display. We adjusted our code to truncate at 32 characters, e.g. 

```
with tracer.trace('span_name', resource=resource_name[:32], service=service_name) as span:
```

and now the spans that were missing resource names have them.

If Datadog's APM has a 32 character limit on resource names, then I think that the ddtrace library should handle this truncation for us.

**Comment by ebpitts** [comment]
cc @shigekihirose

**Comment by ebpitts** [comment]
Actually, this was a misunderstanding on our part. Resource names longer than 32 characters are not displayed when viewing a trace, but they are still recorded. Otherwise, things like capture of text of sql queries would not be working! Our solution will be to just set a tag that also has the resource name in it, so that we can view it.

**Comment by palazzem** [comment]
@ebpitts no worries! Whenever you even think something is not working, feel free to reach us! Most of the time if it's not a bug in the code, it's a bug in the docs, so still something to improve!

Thanks a lot for reporting your concerns!
