### ISSUE TITLE
Detect environment variables compose of other environment variables and expand their value

### ISSUE THREAD

**Issue by carlosjgp** [DataDog/dd-trace-py#3439]
### Which version of dd-trace-py are you using?
```
name = "ddtrace"
version = "0.57.4"
```

### Which version of pip are you using?
```
docker run --rm --entrypoint pip python:3.10-slim --version
pip 21.2.4 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)
```

### Which version of the libraries are you using?

we use poetry instead
```
[[package]]
name = "ddtrace"
version = "0.57.4"
description = "Datadog APM client library"
category = "main"
optional = false
python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*"
```

### How can we reproduce your problem?

Deploy application on Kubernetes with the environment variables
```
- name: HOST_IP
  valueFrom:
    fieldRef:
      fieldPath: status.hostIP
- name: DD_AGENT_HOST
  name: ${HOST_IP}
```

### What is the result that you get?

```
ERROR:ddtrace.internal.writer:failed to send traces to Datadog Agent at http://${HOST_IP}:8126/v0.4/traces
```

### What is the result that you expected?

I was expecting the environment variable value to get expanded when its value was composed of other environment variables or composition of many env vars and/or strings
https://github.com/DataDog/dd-trace-py/blob/fb8dfa2f33fff37d21df9728d8386c0260df9744/ddtrace/internal/agent.py#L27

This could be applied to other environment variables

**Comment by brettlangdon** [comment]
@carlosjgp I am going to close this issue for now. Please feel free to re-open if you are still experiencing issues or you can open a support case with support@datadoghq.com.
