### ISSUE TITLE
Add support for eventlet

### ISSUE THREAD

**Issue by xarg** [DataDog/dd-trace-py#351]
Saw asyncio and gevent here: http://pypi.datadoghq.com/trace/docs/#asynchronous-libraries

Are there any plans to support [eventlet](http://eventlet.net/)?

**Comment by xarg** [comment]
Thanks for the clear answer :)

**Comment by majorgreys** [comment]
@JordanP Happened upon this as I was looking into eventlet. Any chance you would still be interested in opening a PR with the custom eventlet provider? Were you able to sort out the issues when upgrading? Either way, we can help work out any remaining issues.

**Comment by JordanP** [comment]
@majorgreys I'll submit a PR (draft) today

**Comment by JordanP** [comment]
Actually I'd like to make some more research. I am not very comfortable with eventlet/gevent/greenlet but I found this interesting GH issue https://github.com/eventlet/eventlet/issues/663 so maybe, given that the `DefaultContextProvider` uses a `contextvars.ContextVar`, there's actually no need for a `EventletContextProvider` ?

**Comment by Kyle-Verhoog** [comment]
Oh yes, if eventlet supports/uses contextvars then we might just have out of the box support for it. I'll see if I can add some eventlet test cases to our suite to confirm.

**Comment by emmettbutler** [comment]
Closing due to age. The request for eventlet support is also tracked on our team's private feature request backlog.
