### ISSUE TITLE
How does v1.0+ enable analytics for all like below v1.0 does? 

### ISSUE THREAD

**Issue by ayokota** [DataDog/dd-trace-py#3519]
Hello, I am upgrading from v0.19, and the way I initializing the tracer is 

tracer.init({
  analytics: true,  <-------
  env: process.env.STAGE,
  logInjection: true,
  plugins: true,
  runtimeMetrics: true,
  service: 'service',
});

after upgrading to v2.4 (or anything above 1.0), this option is gone, and no where to be found. How does one enable analytics globally like the way it is below v0.19?

**Comment by Kyle-Verhoog** [comment]
@ayokota it looks like you're using the JS tracer which is here: https://github.com/datadog/dd-trace-js. This repository is specifically for the Python library 🙂
