### ISSUE TITLE
Flask: allow mutability of "resource" field within request

### ISSUE THREAD

**Issue by donald-tt** [DataDog/dd-trace-py#353]
I'm using the Flask middleware.  It sets span.resource to the value of request.endpoint.  I've got endpoints that take a URL or form parameter indicating an action to be taken.  At the moment I've had to monkey-patch the TraceMiddleware._finish method to set the resource to something more meaningful to me.

Would it be possible to add a hook to TraceMiddleware to allow the resource to be set at _finish() time, or alternatively get it to check span.resource and not override it, if it hasn't been set yet?

**Comment by clutchski** [comment]
@donald-tt ---^

**Comment by palazzem** [comment]
@donald-tt we've merged the PR #410 that should address exactly your issue. It will be part of the next bugfix release! Thanks for reporting the problem and sorry for the very late response!
