### ISSUE TITLE
Cannot override `redis` service_name when run inside a Celery worker

### ISSUE THREAD

**Issue by ncherro** [DataDog/dd-trace-py#357]
Hi - I'm trying to change the service name for Redis running inside my Celery worker. Here's what I've done:

```python
from ddtrace import tracer, patch, Pin

# ...

# patch Redis, Celery, and our databases
patch(redis=True, celery=True, sqlalchemy=True)

# configure and initialize the Redis client
app.redis = redis.StrictRedis(
    host=app.config.get('REDIS_HOST'), port=6379, db=0)

# initialize the celery queue
queue = Celery(app.name, broker=app.config.get('REDIS_URL'))

# configure the Datadog APM client
tracer.configure(hostname=app.config.get('STATSD_HOST'),
                 port=app.config.get('STATSD_PORT_APM'),
                 enabled=app.config.get('STATSD_APM_ENABLED'))
tracer.set_tags({"env": app.config.get('RELEASE_STAGE')})

# service name overrides (works)
Pin.override(app.redis, service='foo-redis')
Pin.override(queue, service='foo-celery')

# this doesn't seem to work - still seeing Redis from the queue come in as
# 'redis'
Pin.override(queue.connection(), service='foo-redis-queue')
```

I also `Pin.override` in my database classes, and everything works - services appear as `foo-...` in Datadog (including the app.redis service - appears as `foo-redis`)

It's all working *except* redis calls from the Celery worker are appearing in Datadog as `redis` (no `foo-` prefix). How can I override the service name in that case?

I'm running Flask 0.10.0, Celery 3.1.19 and Redis 2.10.3

**Comment by spesnova** [comment]
I am in the same situation

**Comment by AndreiTapai** [comment]
Is there any workaround to get this done? Also annoyed by having multiple separate redis instances lumped together under one name

**Comment by brettlangdon** [comment]
Unfortunately I have not tested this yet, but in theory we should be able to do:

```python
from ddtrace import Pin

# Create app redis client and override service name
app.redis = redis.StrictRedis(host=app.config.get('REDIS_HOST'), port=6379, db=0
Pin.override(app.redis, service='foo-redis')

# Configure Celery app and override redis client service name
queue = Celery(app.name, broker=app.config.get('REDIS_URL'))
Pin.override(queue.backend.client, service='foo-redis')
```

The reason we have to do this is because `Pin.override` will only override for the specific instance passed in. Since the Redis client instance is different for `app.redis` and `queue.backend.client` the service name overriding will need to be done on both.

**Comment by brettlangdon** [comment]
Closing this issue for now, @ncherro please feel free to re-open if you are still experiencing this issue.
