### ISSUE TITLE
tracer.wrap decorator does not work as expected on class methods.

### ISSUE THREAD

**Issue by perlow** [DataDog/dd-trace-py#3577]
tracer.wrap does not handle class methods. There are many edge cases in handling decorators. You may want to consider using the wrapt library (or copying it into your project if you don't want the dependency). 

### Which version of dd-trace-py are you using?

0.61

### Which version of pip are you using?

22.0.4

_ddtrace requires pip>=18 to install one of our pre-built wheels_

### How can we reproduce your problem?

```
from ddtrace import tracer

class TestClass:

    @tracer.wrap()
    @classmethod
    def run(cls, msg):
        print(msg)


TestClass.run("here")

```
### What is the result that you get?

```
Traceback (most recent call last):
  File "/Users/jonathan/src/nextdoor.com/apps/scratch/2022-04-13-datadog-bugs/class_method.py", line 12, in <module>
    TestClass.run("here")
  File "/var/lib/conda/envs/nextdoor3/lib/python3.10/site-packages/ddtrace/tracer.py", line 996, in func_wrapper
    return f(*args, **kwargs)
TypeError: 'classmethod' object is not callable
```

### What is the result that you expected?

For it to call the method correctly.

**Comment by perlow** [comment]
Here's an example of a decorator based on wrapt.

[decorator_wrapt.txt](https://github.com/DataDog/dd-trace-py/files/8483112/decorator_wrapt.txt)

**Comment by brettlangdon** [comment]
hey @perlow thanks for opening the issue and the example using `wrapt.decorator`

If you flip the order of the decorators then it will also work.

```python
from ddtrace import tracer


class TestClass:
    @classmethod
    @tracer.wrap()
    def run(cls, msg):
        print(msg)


TestClass.run("here")
```

But I'll leave this issue open so we can discuss if there are improvements we can/want to make to better support your usage!

**Comment by emmettbutler** [comment]
I'm going to close this issue because it's been open for 11 months with no further discussion. To anyone watching - please reopen if you want to continue the discussion.
