### ISSUE TITLE
feature request: Add aiomysql

### ISSUE THREAD

**Issue by dba4x4** [DataDog/dd-trace-py#3581]
Proposed aiomysql support.
[doc of aiomysql](https://github.com/aio-libs/aiomysql)

Indeed it is used by other libraries for which a request is made here: #1299 

aiomysql support is already developed from branch 1.X

I'm just waiting to be able to become a contributor to make a pull request

**Comment by majorgreys** [comment]
> I'm just waiting to be able to become a contributor to make a pull request

@dba4x4 Are you referring to opening a PR against this repo? If so, you should be able to do so.

**Comment by dba4x4** [comment]
@majorgreys 
I can't create a branch and then make a pull request

**Comment by majorgreys** [comment]
You should fork and then the PR.

**Comment by Kyle-Verhoog** [comment]
Done in https://github.com/DataDog/dd-trace-py/pull/3585
