### ISSUE TITLE
gevent patching order unclear in the docs

### ISSUE THREAD

**Issue by kamikaz1k** [DataDog/dd-trace-py#3595]
Hi, my team is investigating an issue with ddtrace on our gevent/gunicorn application. During this investigation we were trying to determine what the right order for patching is supposed to be - between gevent and ddtrace, the instructions for order the patching is contradictory.

See the gevent section [here](https://ddtrace.readthedocs.io/en/stable/integrations.html#gevent), under the *Note* section
> If ddtrace-run is not being used then be sure to **call gevent.monkey.patch_all before importing ddtrace** and calling ddtrace.patch or ddtrace.patch_all`.

Then later in the *Enabling* [section](https://ddtrace.readthedocs.io/en/stable/integrations.html#id57)
> Or use [patch()](https://ddtrace.readthedocs.io/en/stable/api.html#ddtrace.patch) to manually enable the integration:
> `from ddtrace import patch`
> `patch(gevent=True)`
> Note: these calls need to be performed **before calling the gevent patching.**

What is the ordering supposed to be? And can the docs be updated to clearly reflect that?

Thank you!

**Comment by Kyle-Verhoog** [comment]
Thanks for the report @kamikaz1k! Yes this is unclear and contradictory. The latter documentation is outdated.

The correct one is to patch gevent prior to ddtrace as there are conflicts with the threads `ddtrace` starts to submit traces/profiles.

I'll open up a PR to remove the older conflicting documentation!
