### ISSUE TITLE
patch_all causes AssertionError when importing various packages in my project

### ISSUE THREAD

**Issue by andrei-ivanov-pie** [DataDog/dd-trace-py#3670]
Thanks for taking the time for reporting an issue!

Before reporting an issue on dd-trace-py, please be sure to provide all
necessary information.

If you're hitting a bug, make sure that you're using the latest version of this
library.

### Which version of dd-trace-py are you using?
1.1.0

### Which version of pip are you using?
22.0.4

### Which version of the libraries are you using?
In this particular example:
boto3==1.21.4
botocore==1.24.5

### How can we reproduce your problem?
I have a large python project I'm trying to integrate dd tracing into.
I followed the docs to 
`from ddtrace import patch_all
patch_all(logging=True)
`
but I'm encountering random import patch resolution issues whenever patch_all is called.
### What is the result that you get?
`
ImportError while loading conftest 'path to conftest.py'.
..\..\conftest.py:16: in <module>
    from x.y.z import (
..\..\..\a.b.c:5: in <module>
..........
..\..\..\n.m.p\__init__.py:3: in <module>
    import botocore
..\..\..\venv\lib\site-packages\ddtrace\vendor\wrapt\importer.py:156: in load_module
    module = self.loader.load_module(fullname)
E   AssertionError
`
If I remove the botocore import from the offending init, then I get a different import error in a completely different class.
This problem exists only when I add patch_all() call. The project works fine without it.

### What is the result that you expected?
patch_all() to succeed without issues.

**Comment by Kyle-Verhoog** [comment]
hey @andrei-ivanov-pie, thanks for reporting and so sorry for the late reply!

Are you still seeing this issue and if so do you have a repro for the problem?

I tried to repro based off your libraries and the ddtrace version but didn't see the same behaviour.

**Comment by Kyle-Verhoog** [comment]
Going to close but please yell if you're still seeing the issue!
