### ISSUE TITLE
pytest plugin starts tracer when plugin is disabled

### ISSUE THREAD

**Issue by majorgreys** [DataDog/dd-trace-py#3671]
### Which version of dd-trace-py are you using?

1.1.1

### Which version of pip are you using?

```
# pip --version
pip 22.0.4 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)
```

### Which version of the libraries are you using?

```
# pip freeze
attrs==21.4.0
ddsketch==2.0.1
ddtrace==1.1.1
iniconfig==1.1.1
packaging==21.3
pluggy==1.0.0
protobuf==3.20.1
py==1.11.0
pyparsing==3.0.8
pytest==7.1.2
six==1.16.0
tenacity==8.0.1
tomli==2.0.1
```

### How can we reproduce your problem?

Check out https://gist.github.com/majorgreys/f799970f731fdf70d865d18325e1c34d and run:

```
docker run -it --rm (docker build -q .)
```

### What is the result that you get?

`ddtrace` modules are imported by the Python interpreter. Importing any of these modules starts the global tracer.

The workaround for this is to disable the `ddtrace` plugin with `-p no:ddtrace` in the command.

### What is the result that you expected?

`ddtrace` should not be the modules imported by the Python interpreter.

**Comment by clodo** [comment]
@majorgreys, the workaround you have proposed doesn't work for version 2.6.0; I had to turn off 3 plugins
`-p no:ddtrace -p no:ddtrace.pytest_bdd -p no:ddtrace.pytest_benchmark`

**Comment by LewisCowlesMotive** [comment]
It's kind of disgusting that the above is the workaround... I don't have pytest_bdd so it's just the first and last. I've not set this up or configured it. There is a lot to be said for not magically doing things people have not asked to do
