### ISSUE TITLE
Configuration improvements

### ISSUE THREAD

**Issue by Kyle-Verhoog** [DataDog/dd-trace-py#3703]
## Existing configuration issues

1. **Well defined initialization point.** A lot (almost all) existing configuration is done implicitly at import as modules are loaded. This makes it hard to know when configuration is established or if it can still be modified or will be overwritten.
1. **Knowledge of whether a value is user-defined.** 
1. **Typing.** Currently the configuration is not typed or guarded. (eg. `ddtrace.config.servce = "my-svc"` does not raise an error and will silently fail).
1. **Inconsistent parity of programmatic and environment variable configuration.** There are many options available in the library that can only be configured via environment variable xor programmatic.
1. **Documentation.** Configuration options are not standardized and so there is no established process to document them. In particular, programmatic configurations are not documented well or consistently.

## Requirements

1. Support each feature provided by the library. The configuration has to be decoupled from each feature in the event that a feature has to be disabled or is not available.
2. Support for run-time changes (RCM)

TODO

## Challenges

- Have to be backwards compatible with the current configuration system. Probably means that the old configuration has to live on and we have to support the old and new systems until 2.0.
- 

## Links

- Previous proposal for improvements to IntegrationConfig: https://github.com/DataDog/dd-trace-py/pull/1309
- An example of a declarative configuration API: https://github.com/Kyle-Verhoog/datadog-python#proposed-api

**Comment by emmettbutler** [comment]
The assumptions underlying this ticket have changed a lot in recent weeks with the addition of new functionality to the remote configuration system.
