### ISSUE TITLE
Where to define the Datadog API Token ?

### ISSUE THREAD

**Issue by dgarros** [DataDog/dd-trace-py#378]
Hi 

I'm sure it's written somewhere but I've been looking for 30 min and I can't find it so here I am. 

I would like to integrate ddtrace with Django, but i don't see how and where I should define the API tokens to reach my datadog account.

Thanks for your help and sorry if I missed an obvious point

**Comment by palazzem** [comment]
Hello @dgarros ! for the Django instrumentation you can check our Python documentation: http://pypi.datadoghq.com/trace/docs/#django

Then you need to install our Datadog Agent where you have to provide your API key. You can find more details here after you login in with your Datadog account: https://app.datadoghq.com/account/settings#agent

Let me know if it doesn't work for you!

**Comment by dgarros** [comment]
Hi @palazzem, thanks for your response.
Right now i don't have an agent installed on my system and it's working great.
I'm using `datadog.threadstats` with the python library `datadogpy` and I'm sending events and metrics to datadog directly from python.
Somehow I assumed that `dd-trace-py` would work the same way.

The things is my app is running in a Paas like solution so I don't  want to install something on the host itself.

is there a way I can make `dd-trace-py` work in my environment or is the agent a strict requirement ? 

https://github.com/DataDog/datadogpy

**Comment by palazzem** [comment]
@dgarros oh I see. Unfortunately at the moment having a running Datadog agent is a strict requirement to have traces correctly reported to our API. Mostly because we're doing some computation at the Agent level for Sampling, Distributed Sampling, checking the time spent in each layer of your request. The client doesn't include that logic because it's just a collector of traces.

**Comment by dgarros** [comment]
Thanks for your response.
