### ISSUE TITLE
Remove side-effect on `ddtrace` import

### ISSUE THREAD

**Issue by jirikuncar** [DataDog/dd-trace-py#3784]
## Current situation

`ddtrace.tracer` is automatically created on `ddtrace` [import](https://github.com/DataDog/dd-trace-py/blob/f1a2e8086b1b29c1ac133af7cbbecf1f14340dec/ddtrace/__init__.py#L13). As a side-effect the `AgentWriter` instance is automatically created which might result in spawning new thread.

## Requirements

1. Allow integrations (mostly CI Visibility) to control tracer configuration on startup.
2. Keep backwards compatibility for accessing `ddtrace.tracer`.

## Proposed changes

1. Configuration changes might come as a result of #3703.
2. Add [`__getattr__`](https://peps.python.org/pep-0562/) method to `ddtrace/__init__.py` that will return `Tracer()` instance when `tracer` property is accessed.
    * **Question**: Do we want to keep the "global" tracer with import side effect as the "official" API in other module and if yes, where (`ddtrace.init:tracer` or `ddtrace.global:tracer` or other)?

**Comment by emmettbutler** [comment]
Since the `AgentWriter` was changed to start its thread on the first `write()` call, this is no longer an issue.
