### ISSUE TITLE
Celery subtask traces are missing (distributed tracing)

### ISSUE THREAD

**Issue by jheyder213** [DataDog/dd-trace-py#3838]
Hello  all, 

I am facing a very similar bug as described [here](https://github.com/DataDog/dd-trace-py/issues/1471)

### Which version of dd-trace-py are you using?

1.1.4

### Which version of pip are you using?

pip 22.0.3

### Which version of the libraries are you using?

celery 5.2.7
redis 4.3.3

### How can we reproduce your problem?

Create an application with celery workers and a redis broker with ddtrace installed.
Add the environment flag `DD_CELERY_DISTRIBUTED_TRACING="true"` and enable celery tracing.
Annotate your functions with `@tracer.wrap` to show custom spans.
Split worker tasks into subtasks, e.g. backend -> worker task A -> worker task B, worker task C.

### What is the result that you get?

Only traces (spans) from the backend and worker-task A are shown in datadog. 
Traces for worker task B and C only show up if there is an error in the computation.

### What is the result that you expected?

Traces for worker task B and C always show up.

As I can see the traces in the main worker task and when an error shows up, I assume the application is configured correctly. However, subtasks of celery are not traced correctly.

**Comment by jheyder213** [comment]
@Kyle-Verhoog Do you have tests that ensure this should work?

**Comment by adawalli** [comment]
I can confirm the same issue. With `DD_CELERY_DISTRIBUTED_TRACING=true` in my environment variables on **both the producer and consumer**, can confirm that  `x-datadog-trace-id` is identical for all produced messages, causing a mess of traces in Datadog - thoughts @Kyle-Verhoog ?

**Comment by jheyder213** [comment]
@adawalli Could you specify? 
You have tests that confirm that the traces for tasks B and C are collected?

This is still an issue on our project.

**Comment by adawalli** [comment]
I don't have tests per say. 

```python
@celery.task
def b():
  logger.info("test")

@celery.task
def a():
  logger.info("test")

@celery.task
def c():
 a.delay()
 b.delay()
```
With distributed tracing turned on, I am easily able to see in datadog that the trace id from `c` is propagated as the trace ID in `a` and `b` (I can also dump the headers in the rabbitmq task and see the headers added)

With celery distributed tracing turned off, `a`, `b`, and `c` all have separate trace IDs

**Comment by jheyder213** [comment]
Hello Kyle,

Thank you for the late answer!
We are setting the `DD_CELERY_DISTRIBUTED_TRACING` flag on the worker process as well.
It seems that the issue was that the traces were silently dropped because they were too large. 
Increasing the `DD_TRACE_WRITER_BUFFER_SIZE_BYTES` and `DD_TRACE_WRITER_MAX_PAYLOAD_SIZE_BYTES` limits seems to have resolved the issue.

It would be great to have a better indication within the datadog UI that traces are dropped due to max-size (or submitting the truncated trace).

**Comment by Kyle-Verhoog** [comment]
hey @jheyder213, thanks for the quick follow up!

Ah I see, that would do it. 

> It would be great to have a better indication within the datadog UI that traces are dropped due to max-size (or submitting the truncated trace).

Yes! This is something that is in the works! We'll hopefully be seeing this soon 👀 

I'm going to close the issue now that it is resolved 🙂
