### ISSUE TITLE
Incorrect render patching in pyramid.

### ISSUE THREAD

**Issue by joual** [DataDog/dd-trace-py#385]
https://github.com/DataDog/dd-trace-py/blob/261136e112b23862a78308a2423e15364ae4aaa6/ddtrace/contrib/pyramid/trace.py#L31

Here we're removing request from kwargs but pyramid's render has a request kwarg so we need to keep it.

**Comment by palazzem** [comment]
Thanks @joual to report this! We'll take a look at your PR so that it will be shipped in the next bugfix release!
