### ISSUE TITLE
release notes are not in docs

### ISSUE THREAD

**Issue by lucas03** [DataDog/dd-trace-py#3853]
### How can we reproduce your problem?

check https://ddtrace.readthedocs.io/en/stable/release_notes.html

### What is the result that you get?

only link to old release notes

### What is the result that you expected?

see latest release notes

**Comment by brettlangdon** [comment]
@lucas03 thanks for reporting that. Not sure what happened, we'll look into it.

In the meantime, you can browse the release notes for `latest` which is properly showing them:

https://ddtrace.readthedocs.io/en/latest/release_notes.html
