### ISSUE TITLE
Feature request: Support traceparent header

### ISSUE THREAD

**Issue by goodspark** [DataDog/dd-trace-py#3872]
This is similar to this feature request made on the JS library: https://github.com/DataDog/dd-trace-js/issues/1789

https://www.w3.org/TR/trace-context/#examples-of-http-traceparent-headers

We're using a self-hosted 3rd party service that uses OpenTelemetry for tracing and sending it to an OpenTelemetry ingest endpoint on Datadog agents. The service uses `traceparent` headers for outgoing HTTP requests to support distributed tracing, but I don't think the Python library supports this (at least, the term doesn't show up from a source search).

As referenced in the JS library issue, here's the spec on `traceparent`: https://www.w3.org/TR/trace-context/#traceparent-header

**Comment by phillipuniverse** [comment]
@ZStriker19 so what's the plan for this now that #4170 was reverted in #4295? @Kyle-Verhoog shouldn't this be re-opened?

**Comment by ZStriker19** [comment]
Hi @phillipuniverse . We reverted the change in favor of working on full support for W3C tracecontext which will use both traceparent and tracestate headers. You can see[ here](https://github.com/DataDog/dd-trace-py/pull/4614) that the work for extraction has already been merged. The work for injection is nearing completion as well. As soon as the PR to create a traceparent and tracestate we will be able to make the PR for injection: https://github.com/DataDog/dd-trace-py/pull/4617

**Comment by phillipuniverse** [comment]
@ZStriker19 Awesome! Great stuff!!

**Comment by alecor191** [comment]
@ZStriker19 could you please share the current status on this ticket? From what I understand, both PRs mentioned in your last message are merged by now. Is there an ETA by when this feature will be supported?

**Comment by ZStriker19** [comment]
Hi @alecor191, @phillipuniverse, and @goodspark as of dd-trace-py 1.7.0 we made traceparent, tracestate, along with Datadog (for backwards compatibility) the default headers used for propagation. Therefore as long as you upgrade to that version or greater, it should work ootb with OpenTelemetry. Please let me know if you have any questions. https://github.com/DataDog/dd-trace-py/releases/tag/v1.7.0
