### ISSUE TITLE
aiomysql: AttributeError: __aenter__

### ISSUE THREAD

**Issue by brettlangdon** [DataDog/dd-trace-py#3877]
### Which version of dd-trace-py are you using?

`ddtrace==1.2.0`

### Which version of the libraries are you using?

`aiomysql==0.1.1`

### How can we reproduce your problem?

```python
# repro.py
import asyncio

import aiomysql


loop = asyncio.get_event_loop()


async def go():
    pool = await aiomysql.create_pool(
        host="127.0.0.1",
        port=3306,
        user="test",
        password="test",
        db="test",
        loop=loop,
        autocommit=False,
    )

    async with pool.acquire() as conn:
        await conn.ping(reconnect=True)
        async with conn.cursor() as cur:
            await cur.execute("SELECT 10")
            (r,) = await cur.fetchone()
            return r


loop.run_until_complete(go())
```

```
ddtrace-run python repro.py
```

### What is the result that you get?

```
❯ ddtrace-run python repro.py
repro.py:16: RuntimeWarning: coroutine 'AIOTracedConnection.cursor' was never awaited
  async with conn.cursor() as cur:
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "/Users/brett.langdon/datadog/dd-trace-py/repro.py", line 22, in <module>
    loop.run_until_complete(go())
  File "/Users/brett.langdon/.pyenv/versions/3.9.10/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/brett.langdon/datadog/dd-trace-py/repro.py", line 16, in go
    async with conn.cursor() as cur:
AttributeError: __aenter__
```

### What is the result that you expected?
No attribute error, and `async with conn.cursor()` works as expected.

**Comment by sriram-enphase** [comment]
aiomysql==0.1.0 seems to work for me, can you please explain why this error occurs only with the newer version of aiomysql==0.1.1

**Comment by brettlangdon** [comment]
hey @sriram-enphase thanks for sharing that it is working on `aiomysql==0.1.0`.

I have left slightly more detailed description in a code comment for the fix: https://github.com/DataDog/dd-trace-py/pull/3879/files#diff-5b0e259257b8862084d8a0f21dc82c1cf37dec6abff2ab3922db05e29e8fa879R110


The tl;dr; is:

`Connection.cursor()` is a sync function which returns an async context manager wrapper around a Coroutine (Future). Our wrapper instead wrapped `Connection.cursor()` as an async function returning a wrapped cursor.

Using our wrapped `cursor()` method with `async with` is what was causing issues, since:

1. When doing `async with conn.cursor():` it would be trying to use `__aenter__` on the Coroutine returned by our wrapper
2. When doing `cur = await conn.cursor(); async with cur:` we were not properly passing through `__aenter__`/`__aexit__` to the wrapped cursor

The PR with the fix ensures that we do not change the original function from a `def` to an `async def`, and we ensure the return type is the same (aiomysql context manager wrapping a coroutine).
