### ISSUE TITLE
Incorrect Error Handling in Flask

### ISSUE THREAD

**Issue by patforna** [DataDog/dd-trace-py#390]
The code in flask/middleware.py has two issues that are related to how flask handles errors.

## Issue 1
According to Flasks design, the signal handler for `got_request_exception` gets executed *before* any error handling logic. This is an issue, because the middleware will process and finish the span as an error, even though an error handler might process the exception into a let's say `404` or even `200`. Unfortunately, the way the code is written, by the time the handler for `request_finished` gets called (which is *after* error handling), the span has already been processed and marked as finished.

## Issue 2
Related to above, the current code will always set the status code to `500`, which leads to exceptions that are handled and turned into a non-500 response to be wrongly reported in DataDog as `500`s even though they might have turned into something else.

## Potential Fix
A potential fix is to let the handler for `got_request_exception` only set the exception info on the active span and then let the handler for `request_finished` do the rest (incl. setting the error flag based on the final http status code).

See [this gist for a draft of a possible fix](https://gist.github.com/patforna/a3f61a3d17174622d29e2f741674bc2b).

**Comment by clutchski** [comment]
@patforna do you have a minimal app that demonstrates this that I can turn into a test case?

**Comment by clutchski** [comment]
@patforna if you'd like, check out the above PR.

**Comment by palazzem** [comment]
Hello @patforna ! We've merged #409 that should address your issue! It will be part of the next release 0.10.1. Feel free to reopen the ticket if you think this change (the way we handle the request signals / hooks) doesn't solve your problem.

Thank you for reporting that and for the very accurate triage!

**Comment by patforna** [comment]
Looks good. Think this should work. Thanks a lot! 👍
