### ISSUE TITLE
asyncio task parenting not serializing parent service name

### ISSUE THREAD

**Issue by thehesiod** [DataDog/dd-trace-py#399]
so currently if you patch asyncio it will enable linking of contexts via _wrapped_create_task.  The way it works is that it will create a new Context with the trace and span IDs from the current_task.  The issue with this is that when you start a span, it will get the trace_id and span_id of the context, however the service name is lost, so the parent's span's service name will not get propagated if the context was created via _wrapped_create_task.

This is really important because if the service is not set then the span will get silently dropped.

I suggest fixing this by storing the parent's service name in the context.  I'll create a PR shortly to solve this.

**Comment by thehesiod** [comment]
NOTE: I'd also suggest perhaps a warning/assert if service is missing when creating a span w/ a parent, otherwise it will get silently dropped

**Comment by palazzem** [comment]
Thanks for reporting @thehesiod ! Will check also your PR. In general, we should provide a reasonable default service name (i.e. the name of the Python script) so that in the worst case we still set a service name if none is provided.

We'll work on the other issue another time, while this could (and should be addressed) soon.

**Comment by thehesiod** [comment]
hmm, getting the script name is not too easy, I suppose we could walk the python stack and try to figure the first script name outside ddtrace? This would kinda break if someone wraps ddtrace with another library and wouldn't help too much.  Couldn't we just assert or throw an exception?  To use something useful I think we'd need to ask the user.

**Comment by brettlangdon** [comment]
@thehesiod in the most recent version of the agent (6.13+) we actually no longer drop spans that are missing a service name, we will however group them under a default `unnamed-<language>-service` service name instead.

As well, we have done some work on `asyncio`/`contextvars` support in `ddtrace==0.28.0` for Python 3.7, while this probably does not fully resolve this issue it might be worth trying out the latest version anyways.

**Comment by thehesiod** [comment]
seems like it works now post https://github.com/DataDog/dd-trace-py/pull/1352.  I've change to PR to just ensure this works going forwards

**Comment by thehesiod** [comment]
going to close this then, but if someone could review and merge that PR it would be nice
