### ISSUE TITLE
Wrong service name when using split_by_domain for requests

### ISSUE THREAD

**Issue by goodspark** [DataDog/dd-trace-py#4062]
### Which version of dd-trace-py are you using?
1.2.1

### Which version of pip are you using?
20.3.4

### How can we reproduce your problem?
I assume this is caused by the `text@domain.com` at the _end_ of the URL.

### What is the result that you get?
![image](https://user-images.githubusercontent.com/29210237/183526731-05796a95-de6b-4765-9d2f-f2bfa130be4f.png)

### What is the result that you expected?
The service should be 'sendgrid.com'.

**Comment by goodspark** [comment]
I'm guessing it's caused by this code: https://github.com/DataDog/dd-trace-py/blob/fb8dfa2f33fff37d21df9728d8386c0260df9744/ddtrace/contrib/requests/connection.py#L29-L36

Should probably use something like urllib.parse or only strip out user creds from the host after first narrowing down the possible hostname between `://` and the first `/` or `?` characters.

**Comment by goodspark** [comment]
Yup that seems to be it.
```
>>> _extract_hostname('https://asd.com/blah/hello@zxc.com')
'zxc.com'
```

**Comment by mabdinur** [comment]
Hi @goodspark, 

Thanks for calling out this issue. I opened a pull request to address this bug.
