### ISSUE TITLE
Clean up GitHub project labels

### ISSUE THREAD

**Issue by majorgreys** [DataDog/dd-trace-py#4177]
I want to propose the following label changes:

| name | description | change |
| -- | -- | -- |
|  bug                     |                                                  | keep |
|  enhancement             |                                                  | keep |
|  question                |                                                  | keep |
|  integrations            |                                                  | keep |
|  do-not-merge            |  Block automatic merging of pull request         | drop |
|  feature-request         |                                                  | keep |
|  changelog/no-changelog  |  A changelog entry is not required for this PR.  | keep |
|  conflict                |                                                  | merge with `label:conflicts` |
|  manual merge            |  Do not automatically merge                      | keep |
|  proposal                |                                                  | keep |
|  conflicts               |                                                  | keep (used by Mergify) |
|  proposal:in-progress    |  proposal is in progress                         | rename to proposal |
|  proposal:accepted       |  proposal is accepted                            | merge with `label:proposal` |
|  proposal:rejected       |  proposal is rejected                            | merge with `label:proposal` |
|  needs-triage            |  default label for new pull requests             | keep |
|  Stale                   |                                                  | keep |
|  ASM                     |  Application Security Monitoring                 | keep |

I am not sure why the `label:conflicts` is being applied by Mergify to [backports](https://github.com/DataDog/dd-trace-py/issues?q=label%3Aconflicts) that have merge conflicts rather than `label:conflict`.

**Comment by Kyle-Verhoog** [comment]
> I am not sure why the label:conflicts is being applied by Mergify to [backports](https://github.com/DataDog/dd-trace-py/issues?q=label%3Aconflicts) that have merge conflicts rather than label:conflict.

I've seen mergify do both labels (I think in different contexts)

**Comment by Kyle-Verhoog** [comment]
@majorgreys what's the rationale for merging the proposal labels?

Should we also merge `do-not-merge` and `manual merge`? I think when we attach `manual merge` we really mean `do-not-merge`.

**Comment by majorgreys** [comment]
> I've seen mergify do both labels (I think in different contexts)

Do you have an example of `label:conflict` being applied? We can open a bug report.

> @majorgreys what's the rationale for merging the proposal labels?

I should have included that in my proposal!

We have not separated the proposal issues into those stages so far, which makes me think we can do with just one label.

> Should we also merge `do-not-merge` and `manual merge`? I think when we attach `manual merge` we really mean `do-not-merge`.

I see your point that `do-not-merge` is more to the point. We'd have to change the Mergify rules. I'm not sure where else `manual merge` is being used.

**Comment by Kyle-Verhoog** [comment]
> Do you have an example of `label:conflict` being applied? We can open a bug report.

Here's one that mergify applies both: https://github.com/DataDog/dd-trace-py/pull/4138

I think this is because we define a new conflict label here: https://github.com/DataDog/dd-trace-py/blob/46aa1054d906260638dc120aaa1f839902f70335/.mergify.yml#L45 and mergify uses another. 

Fix here: https://github.com/DataDog/dd-trace-py/pull/4178


> We have not separated the proposal issues into those stages so far, which makes me think we can do with just one label.

If we're not using it then I'm ok to remove them 👍 


> I see your point that do-not-merge is more to the point. We'd have to change the Mergify rules. I'm not sure where else manual merge is being used.

I'm ok to update the rule, I think this is the only place 👍

**Comment by majorgreys** [comment]
@Kyle-Verhoog updated the proposal given the change to our Mergify rules. 

Being that there is no other code changes, I'll apply the changes to the Github project and close this proposal.

**Comment by Kyle-Verhoog** [comment]
SGTM 👍
