### ISSUE TITLE
Incorrect Error Handling in Django

### ISSUE THREAD

**Issue by patforna** [DataDog/dd-trace-py#418]
The code in `contrib/django/middleware.py` has an issues related to how django handles errors:

When a view throws an exception, `TraceExceptionMiddleware.process_exception` gets called and  will set the `span.error = 1`. This is an issue, because other middleware might handle the exception and turn it into a non-500 response (e.g. `raise Http404` will be handled by django and turned into a 404 response, which should have `span.error = 0`).

## Potential Fix

One way to fix this would be to set `span.error` in `process_response` depending on the response's status code. For example:

     def process_response(self, request, response):
        ...
        span.error = 0 if response.status_code < 500 else 1
        span.finish()
        ...

This issue is related to a similar issue which has been reported and fixed for flask in `0.10.1` (see [Issue 390](https://github.com/DataDog/dd-trace-py/issues/390))

**Comment by Kyle-Verhoog** [comment]
This should be fixed in #462! Let us know if there is any issue still 😄

**Comment by palazzem** [comment]
Hello @patforna ! because the PR has been merged, do you have a way to check if it's working properly? we're about to ship the 0.12.1 next week, but want to be sure that problem can be considered closed. Thank you very much!
