### ISSUE TITLE
failed to send traces to Datadog Agent

### ISSUE THREAD

**Issue by szpulak** [DataDog/dd-trace-py#4203]
Thanks for taking the time for reporting an issue!

Before reporting an issue on dd-trace-py, please be sure to provide all
necessary information.

If you're hitting a bug, make sure that you're using the latest version of this
library.

### Which version of dd-trace-py are you using?
1.3.2
### Which version of pip are you using?
22.0.2

### Which version of the libraries are you using?
[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.0.1"
djangorestframework = "^3.12.4"
ddtrace = "1.3.2"
psycopg2 = "^2.9.2"
tier-sdk-python = "^0.1.22"
gunicorn = "^20.1.0"
pydantic = "^1.8.2"
prometheus-client = "^0.14.1"
django-allow-cidr = "^0.3.1"
django-prometheus =
python-decouple = "^3.5"
sentry-sdk = "^1.5.12"
whitenoise = "^5.3.0"
django-cors-headers = "^3.10.1"
django-enumfields = "^2.1.1"
django-money = "^2.1"
django-countries = "^7.2.1"
django-extensions = "^3.1.5"
django-filter = "^21.1"
pyOpenSSL = "^22.0.0"
requests = "^2.27.0"
djangorestframework-camel-case = "^1.3.0"
PyJWT = "^2.3.0"
celery = {extras = ["redis"], version = "^5.2.3"}
django-celery-results = "^2.2.0"
django-jsonform = "2.7.0"
django-fsm = "^2.8.0"
httpx = "^0.22.0"
pyhumps = "^3.7.1"
mozilla-django-oidc = "^2.0.0"
PyYAML = "^6.0"
click = "8.1.3"
djangorestframework-api-key = "^2.2.0"
djangorestframework-jsonapi = "^5.0.0"
uritemplate = "^4.1.1"
django-celery-beat = "^2.3.0"
python-json-logger = "^2.0.4"
dj-database-url = "^1.0.0"
You can copy/paste the output of `pip freeze` here.

### How can we reproduce your problem?
it happens in production, in containerized environment 
### What is the result that you get?
Error stack like below: 

**RetryError[<Future at 0x7fdf0b2a9a50 state=finished raised FileNotFoundError>]**
failed to send traces to Datadog Agent at unix:///var/run/datadog/apm.socket/v0.4/traces
<RetryCallState 140595939976496: attempt #3; slept for 0.14; last result: failed (FileNotFoundError [Errno 2] No such file or directory)>
<Retrying object at 0x7fdf08ab42e0 (stop=<tenacity.stop.stop_after_attempt object at 0x7fdf0741f730>, wait=<tenacity.wait.wait_random_exponential object at 0x7fdf08b453f0>, sleep=<function sleep at 0x7fdf0b161c60>, retry=<tenacity.retry.retry_if_exception_type object at 0x7fdf06efd7b0>, before=<function before_nothing at 0x7fdf0b1635b0>, after=<function after_nothing at 0x7fdf0b19c4c0>)>

### What is the result that you expected?
no such a errors are expeted

**Comment by Kyle-Verhoog** [comment]
Hi @szpulak!

Thanks for reporting. It looks like ddtrace is attempting to use the UDS socket `/var/run/datadog/apm.socket/v0.4/traces` which is mounted by the [cluster agent](https://docs.datadoghq.com/containers/cluster_agent/). Can you confirm that you are using the cluster agent and maybe provide a bit more detail about your environment?
