### ISSUE TITLE
ddtrace-run breaks Celery support, have to patch manually

### ISSUE THREAD

**Issue by apolloFER** [DataDog/dd-trace-py#423]
The issue appears when trying to run Celery workers with `ddtrace-run`.

`dd-trace-py` library attempts to patch Celery but fails with the message - _module not installed_. Upon further examination we've discovered that it fails at `ddtrace/contrib/celery/__init.py__` line 51 when trying to import the Celery module.

The reason for that is that the import fails with Exception saying that `sys.argv` doesn't exists. Somewhere in the Celery module there is a reference towards `sys.argv`. As it seems, when importing Celery from `ddtrace-run`, this is not set (or `sys` is perhaps patched or muted) so the import fails and the patching fails silently saying that Celery is not installed.

The workaround is to manually call `patch(celery=True)` once your application regains control from `ddtrace-run`. In that case, Celery is normally imported as `sys.argv` exists.

**Comment by palazzem** [comment]
Thank you @apolloFER ! Will continue from here fixing this issue before the other!

**Comment by palazzem** [comment]
Hello @apolloFER! I'm still checking this example and this is exactly what is happening:
* If I use the example, I can reproduce the issue having also the following issue (#449):
```
TypeError: missing 1 required positional argument
```
* If I run a modified example that uses `ddtrace-run` without any `ddtrace` import (especially the `@patch_task` that is causing the problem above) I can send correctly traces to our Agent. Here a gist to replicate my current environment: https://gist.github.com/palazzem/615faaa7d26b69399ba681a01160dd8c

I'm still triaging the problem, but what I got is:
* while using the `@patch_task` and `patch(celery=True)` together, we have the `TypeError` issue
* if we remove all `ddtrace` imports and simply use the `ddtrace-run` it works as expected
* of course it's not working in your case as stated in this thread, so I'm wondering if I can slightly modify my gist to have exactly a case where `ddtrace-run` raises an `ImportError` avoiding patching Celery

**Comment by apolloFER** [comment]
Hi @palazzem 

I tried the modified example where I removed the `ddtrace` import (including all `@patch_task` calls).  Here's my current worker:
https://gist.github.com/apolloFER/a0e7ac6f5e0419c878d8bb120f3dfc69
Here's the startup log:
https://gist.github.com/apolloFER/7883745d5088595629f73f351a5f92a0
As you can see, celery is not patched (the reason is that ImportError which is caught so you won't get it in logs). Nothing crashes (the TypeError crash) but that's because Celery isn't patched and neither are the tasks. This is also seen in Datadog dashboard -- there are traces reported, but those are all Redis traces and no Celery traces.

**Comment by palazzem** [comment]
With #469 we have fixed the issue about the `argv` error. Because the issue was only about using `ddtrace-run`, we can consider it addressed. I'll follow-up in other GitHub issues. Thank you very much!
