### ISSUE TITLE
Question: is "ddtrace-run uvicorn" supported?

### ISSUE THREAD

**Issue by fredrikaverpil** [DataDog/dd-trace-py#4237]
In the [ddtrace-run docs](https://ddtrace.readthedocs.io/en/stable/advanced_usage.html#ddtracerun), a few supported use cases are mentioned with ddtrace-run. I'm using FastAPI and running it with `uvicorn`. These docs doesn't say explicitly that something like `ddtrace-run uvicorn main:app` is supported. Is it?

**Comment by brettlangdon** [comment]
Yes, it is!

We did not exhaustively list all possibilities but but `ddtrace-run` is meant to work as a prefix for any way that you execute your Python application.

If it is not working as intended please let us know!
