### ISSUE TITLE
Extend support for Python 3.6 in 0.59.x version

### ISSUE THREAD

**Issue by iamhssingh** [DataDog/dd-trace-py#4240]
# Not an issue - Extending support for `Python 3.6`

### Which version of dd-trace-py are you using?
`>=0.59.0`, `<0.60.0`

### Which version of pip are you using?
`>=18.1`, `<=21.3.1`

_ddtrace requires pip>=18 to install one of our pre-built wheels_

### Which version of the libraries are you using?

Not relevant

### How can we reproduce your problem?

Install `ddtrace>=0.59.0,<0.60.0` on `Python 3.6.15`

### What is the result that you get?

Error because `protobuf` released `4.21.1` wherein they dropped support for `Python 3.6`.
`ddtrace` `0.59.0-0.60.0` supports `Python 3.6` but the requirement file doesn't but a version limit on `protobuf`

### What is the result that you expected?

Limit version of `protobuf` at `<4.0.0`. Release `0.59.x` with this fix

**Comment by brettlangdon** [comment]
@iamhssingh thank you for opening the issue. Are you able to upgrade to `ddtrace>=0.61.1`?

We have already made this change to the `0.x` release line: https://ddtrace.readthedocs.io/en/stable/release_notes.html#v0-61-1
