### ISSUE TITLE
aioredis merged into redis library

### ISSUE THREAD

**Issue by Yun-Kim** [DataDog/dd-trace-py#4351]
As of `redis>=4.2.0`, `aioredis` has been merged into the `redis` library and is no longer maintained or supported as a separate library ([see farewell message](https://github.com/aio-libs/aioredis-py)).

However, our library has a separate `aioredis` integration and test suite for `aioredis`. Let's use this issue to discuss and track how we'll follow up the merging of the two libraries.

**Comment by emmettbutler** [comment]
@DataDog/apm-framework-integrations-reviewers-py

**Comment by emmettbutler** [comment]
My plan with this is to update the tested library versions in the riotfile and include the aioredis test suite in the redis riot environment.
