### ISSUE TITLE
Connecting to a trace agent not in localhost

### ISSUE THREAD

**Issue by achanda** [DataDog/dd-trace-py#436]
I have my trace agent running on another box, with port 8126 open. How do I make my flask app connect to it? I followed the docs here to setup my app http://pypi.datadoghq.com/trace/docs/#module-ddtrace.contrib.flask

**Comment by palazzem** [comment]
Hello @achanda ! Assuming you're following the manual activation without the `ddtrace-run` script, this is what you can do:
```python
from flask import Flask
import blinker as _

from ddtrace import tracer
from ddtrace.contrib.flask import TraceMiddleware

# configure the Tracer
tracer.configure(hostname='ddagent.consul.local')

# configure the Flask app
app = Flask(__name__)
traced_app = TraceMiddleware(app, tracer, service="my-flask-app", distributed_tracing=False)

@app.route("/")
def home():
    return "hello world"
```

Let me know if it solves the problem! thank you very much! :)

**Comment by achanda** [comment]
Ah, that makes sense. Thanks for explaining!

**Comment by palazzem** [comment]
@achanda you're welcome!
