### ISSUE TITLE
Support for psycopg3

### ISSUE THREAD

**Issue by Meemaw** [DataDog/dd-trace-py#4393]
### Summary of problem
Psycopg 3 is the new implementation of the most used, reliable and feature-rich PostgreSQL adapter for Python.

Having a datadog integration would be great.

**Comment by brettlangdon** [comment]
@Meemaw thanks for opening the issue.

Some links for others since I was confused by https://pypi.org/projects/psycopg3/

This is being released under the package name `psycopg`

Repo: https://github.com/psycopg/psycopg
Docs: https://www.psycopg.org/psycopg3/
PyPI: https://pypi.org/project/psycopg/

**Comment by jsekerez** [comment]
This feature would be much appreciated!!!

**Comment by Eyal-Shalev** [comment]
@brettlangdon I think this should be tagged with `integrations`.

**Comment by snuderl** [comment]
Django will ship support for this in next release too, so the package might start getting some much wider addoptation too now.

**Comment by ryan-thielke-ent** [comment]
[SQLAlchemy 2.0 adds psycopg3 dialect support](https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#dialect-support-for-psycopg-3-a-k-a-psycopg). Will the sqlalchemy ddtrace integration work properly when using this dialect?

**Comment by sidmitra** [comment]
This has now landed in Django. See [4.2 release notes](https://docs.djangoproject.com/en/4.2/releases/4.2/#psycopg-3-support)

**Comment by emmettbutler** [comment]
psycopg3 support was added in https://github.com/DataDog/dd-trace-py/pull/5213

**Comment by jsekerez** [comment]
Amazing, so glad!

**Comment by anayrat** [comment]
Hello,
Maybe you should mention psycopg3 in https://docs.datadoghq.com/database_monitoring/connect_dbm_and_apm/?tab=go&site=eu
![image](https://github.com/DataDog/dd-trace-py/assets/6862220/da737148-48da-4a8d-b486-feb8a47425d7)

Regards
