### ISSUE TITLE
Configuration documentation table hard to read

### ISSUE THREAD

**Issue by plannigan** [DataDog/dd-trace-py#4396]
### Summary of problem
The documentation's [configuration page](https://ddtrace.readthedocs.io/en/stable/configuration.html) contains a table of all the possible variables that can be set. This table includes the default value. There are a few variables that default to long regular expressions which don't render with any extra line breaks. This causes the description column to be far to the right after a long scroll.

### Which version of dd-trace-py are you using?
n/a

### Which version of pip are you using?
n/a

### Which libraries and their versions are you using?
n/a

### How can we reproduce your problem?
Go to the [documentation website](https://ddtrace.readthedocs.io/en/stable/configuration.html)

### What is the result that you get?
A table that requires significant horizontal scrolling.

### What is the result that you expected?
Have the page render in a way that doesn't require significant horizontal scrolling. Alternately, move the default column to be the most right column. This would only require scrolling when people care about the few values that are long.

**Comment by brettlangdon** [comment]
Hey @plannigan thanks for opening this issue. We noticed this recently as well but haven't found a good way to fix it yet.

But this is a good reminder that we should try again!
