### ISSUE TITLE
Trace middleware in Fastapi

### ISSUE THREAD

**Issue by Meemaw** [DataDog/dd-trace-py#4397]
### Summary of problem

It seems middlewares are not traced in fastapi.

Moreover, trying to use `tracer.get_log_correlation_context()` within a middleware will not return any active context, which means we can't operate with `traceId` (e.g to enrich response/logs within a middleware).

https://fastapi.tiangolo.com/tutorial/middleware/

### Which version of dd-trace-py are you using?

1.5.2

**Comment by brettlangdon** [comment]
@Meemaw thank you for opening this issue.

We do not support creating spans automatically from FastAPI middleware.

But I would have expected there to be an active root `fastapi.request` span that is accessible from the middleware.

Do you have a minimal reproducible setup? I assume just FastAPI with a route, and then a custom middleware that tries to access the current active span (`get_log_correlation_context()` is one way) ?

**Comment by Meemaw** [comment]
I would have expected that as well. Should be reproducible with just any route, and just adding a custom middleware.
