### ISSUE TITLE
Duplicate Django App Labels

### ISSUE THREAD

**Issue by mjhea0** [DataDog/dd-trace-py#4408]
Any recommendations for dealing with clashes in Django app label names?

--

Issue when used with [nplusone](https://github.com/jmcarp/nplusone):

```
INSTALLED_APPS = (
    ...
    "nplusone.ext.django",
    "ddtrace.contrib.django",
)
```

`django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: django`

**Comment by brettlangdon** [comment]
@mjhea0 thank you for opening an issue.

Can you please share which version of `django` and `ddtrace` you are using?

**Comment by mjhea0** [comment]
Sure:

django v4.1.1 and ddtrace v1.5.2

**Comment by brettlangdon** [comment]
thanks!

with the latest version of `ddtrace` you do not need to specify `ddtrace.contrib.ddtrace` as an installed app, you should be able to remove that entry without any issues.

you can see the Django setup instructions in our docs: https://ddtrace.readthedocs.io/en/stable/integrations.html#django
