### ISSUE TITLE
Deprecation warning when using flask 2.2

### ISSUE THREAD

**Issue by pmdarrow** [DataDog/dd-trace-py#4430]
### Summary of problem

The following deprecation warning is displayed when using the the latest version of ddtrace and flask:

```
/Users/pmdarrow/Library/Caches/pypoetry/virtualenvs/dh-potluck-3D02a94F-py3.10/lib/python3.10/site-packages/ddtrace/contrib/flask/helpers.py:11: DeprecationWarning: 
'_app_ctx_stack' is deprecated and will be removed in Flask 2.3. Use 'g' to store data, or 'app_ctx' to access the current context.
    appctx = flask._app_ctx_stack.top
```

### Which version of dd-trace-py are you using?

1.5.3

### Which version of pip are you using?

22.3

### Which libraries and their versions are you using?

Flask 2.2.2

### How can we reproduce your problem?

Instrument a Flask 2.2.2 app with ddtrace 1.5.3.

### What is the result that you get?

A deprecation warning.

### What is the result that you expected?

No deprecation warning. The offending line can be found here: https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/contrib/flask/helpers.py#L11.

**Comment by mabdinur** [comment]
Hey @pmdarrow, 

Thanks for bringing this issue to our attention. We will refactor our flask integration to avoid using this deprecated attribute:  [flask. _request_ctx_stack](https://github.com/pallets/flask/blob/2a54cfa5cecf4dd9f17525bf3ebae4d33a155776/src/flask/__init__.py#L69).
