### ISSUE TITLE
set tags in route decorator to be picked up by the trace

### ISSUE THREAD

**Issue by HoneyryderChuck** [DataDog/dd-trace-py#4447]
### Summary of problem

Hi, 

I'm using the flask integration. I wanted to set up a few tags in a decorator, where I usually set some request context stuff, which would then appear in the trace tags. Sadly, this isn't happening:

```python
# what I'm doing:

def client_id_required(func):
    @functools.wraps(func)
    def _employee_login_required(*args, **kwargs):
        headers = request.headers
        client_id = headers["x-client-id"]
        # ...
        span = tracer.current_span()

        if not span:
          return
        span.set_tag("client_id", client_id)
        return func(*args, **kwargs)

# then the route
@api.get("/")
@client_id_required
def fetch_items(request):
```

The corresponding trace (and metric) does not contain the tag.

### Which version of dd-trace-py are you using?

`ddtrace-1.0.1`.

### Which version of pip are you using?

Using poetry (1.2)

### How can we reproduce your problem?

I'm going to assume this is a non-issue.

### What is the result that you get?

No tag in trace.

### What is the result that you expected?

The tag in the trace.

**Comment by mabdinur** [comment]
Hey @HoneyryderChuck, 

Thanks for opening this issue. 

What is the type of the tag? In ddtrace v1.0.1 if a tag is NOT a [string type](https://six.readthedocs.io/#six.string_types) it will not be set ([code](https://github.com/DataDog/dd-trace-py/blob/v1.0.1/ddtrace/span.py#L237)).  To avoid this you can use `span.set_tag("client_id", str(client_id))`. 
Note - this tag is not set on the tracer it's set on the span. If the span is sent to the agent and is not sampled out then you should see the tag in your Datadog org.

To set a metric you can use [span.set_metric(k_str, metric_int)](https://github.com/DataDog/dd-trace-py/blob/v1.0.1/ddtrace/span.py#L348). 
Note - a metric must be have a string key and an integer value.

Let me know if that doesn't work.

**Comment by HoneyryderChuck** [comment]
> What is the type of the tag?

It is a string.

> Note - this tag is not set on the tracer it's set on the span.

Indeed. However, this is not the problem I'm talking about. After some digging, I think I have a better understanding now, so let me expand:

The span, which generates the metrics we cover, is tagged as "flask.request" (metric: "trace.flask.request"). These are fired [here](https://github.com/DataDog/dd-trace-py/blob/61f0177592636a76db113daf3dd1b8bb5c18be13/ddtrace/contrib/flask/patch.py#L349). However, the span I'm accessing to in the decorator is tagged as "{blueprint_name}.{route_name}". This span is generated [here](https://github.com/DataDog/dd-trace-py/blob/61f0177592636a76db113daf3dd1b8bb5c18be13/ddtrace/contrib/flask/wrappers.py#L44). 

My expectation was that I was setting the tags in the former, as that's the span I'd like to target. But that only comes after, and does not contain the information I just set. 

Is there a way to make it so? For instance, we also use `sentry-sdk`, which allows one to set "context tags", i.e. bound to the current thread, which are then caught by all further spans. Does datadog have smth similar?

**Comment by mabdinur** [comment]
Hey @HoneyryderChuck, 

The ddtrace api only exposes the current active span. Once a blueprint span is activated there is no easy way to access the flask.request span. However you can configure [header tracing](https://ddtrace.readthedocs.io/en/stable/advanced_usage.html#headers-tracing) to set the x-clent-id header on flask.request spans. 
 
Configure header tracing
- By setting the following configuration from ddtrace import config; config.flask.http = trace_headers(['x-client-id']), the tracer will add the following tag to all `flask.request` spans: `http.request.headers.x_client_id`. The value associated with this tag should be `request.headers["x-client-id"]`. 
- Note you can also map request/response headers to span tags using the following environment variable: `DD_TRACE_HEADER_TAGS` (example usage: `DD_TRACE_HEADER_TAGS="X-CLIENT-ID:client_id"`). 

If you would like to intercept all spans before they are sent to the Datadog agent you can do this by configuring a trace filter. At this point you can add any tags or metrics to your spans. However this filter will most likely be applied after a request is complete. Here are a doc on how to set up a tracer filter: https://ddtrace.readthedocs.io/en/stable/advanced_usage.html#trace-filtering

Would these solutions work for you?

**Comment by mabdinur** [comment]
Hey @HoneyryderChuck, 

Feel free to reopen this issue if the steps above don't work for you.

**Comment by Kyle-Verhoog** [comment]
hey @HoneyryderChuck, just to clarify we do have [a way](https://ddtrace.readthedocs.io/en/stable/api.html#ddtrace.Tracer.current_root_span) to set the tag on the root span (but this is not necessarily the `flask.request` span, like if you used our Tracing WSGI middleware).

Otherwise the method @mabdinur suggested with the `TraceFilter` would be the way to go.
