### ISSUE TITLE
DDtrace Flask middleware logging as flask instead of ddtrace

### ISSUE THREAD

**Issue by vascop** [DataDog/dd-trace-py#447]
Here:
https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/flask/middleware.py#L31

You attach to flask's logger and log that line. Could you log it as ddtrace (using log.info) instead so that we can configure ddtrace's log handlers appropriately without having to create custom log filters?

**Comment by palazzem** [comment]
Thanks @vascop for your suggestion! Sure we can switch to the `ddtrace` logger so that you only need to configure the appropriate handler. I'll keep it in our backlog and will update you once it's in our current sprint.

**Comment by palazzem** [comment]
Hello @vascop ! We made a PR about this issue https://github.com/DataDog/dd-trace-py/pull/455. Can you confirm if it solves your problem? If it's the case, I can merge it and ship it in the next 0.12 release.

Thank you!

**Comment by palazzem** [comment]
@vascop the 0.12.0 release is out: https://github.com/DataDog/dd-trace-py/releases/tag/v0.12.0!
