### ISSUE TITLE
Add a non-root user to run containers from the `dd-lib-python-init` image

### ISSUE THREAD

**Issue by nilushancosta** [DataDog/dd-trace-py#4476]
### Summary of problem
When a Docker container is started from `datadoghq/dd-lib-java-init`, it runs as root. This image is used in an init-container when using the Datadog admission controller to add Python tracer libraries.
Since its recommended to run containers as non-root users, it's good if we can add a non root user for this image

### Which version of dd-trace-py are you using?
latest

**Comment by nilushancosta** [comment]
If it's ok to do this change, I would like to send a PR and contribute

**Comment by mabdinur** [comment]
Hey @nilushancosta,

Thanks for opening this issue. Yes, feel free to open a PR! Also are you noticing any issues with running the container with root permissions or is this proposal an enhancement?

**Comment by nilushancosta** [comment]
@mabdinur, No problem.
In Pod definitions where the [following security context](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted) is enabled, the pod fails to start with a `Init:CreateContainerConfigError` error

```
securityContext:
        runAsNonRoot: true
```
So I would say it's an enhancement to support running in Pods with the above security Context
