### ISSUE TITLE
Distributed tracing doesn't work in Django

### ISSUE THREAD

**Issue by keattang** [DataDog/dd-trace-py#456]
Specifying `DISTRIBUTED_TRACING=True` in the Django Datadog settings doesn't work because the propagator looks for the `x-datadog-trace-id` header in the Django `request.META` object which converts the header name to `HTTP_X_DATADOG_TRACE_ID`. For more details on this see [here](https://docs.djangoproject.com/en/2.0/ref/request-response/#django.http.HttpRequest.META).

In order to work around this I've had to monkey patch the library so that it looks for the headers with the correct keys:
```
from ddtrace.propagation import http
http.HTTP_HEADER_TRACE_ID = 'HTTP_X_DATADOG_TRACE_ID'
http.HTTP_HEADER_PARENT_ID = 'HTTP_X_DATADOG_PARENT_ID'
http.HTTP_HEADER_SAMPLING_PRIORITY = 'HTTP_X_DATADOG_SAMPLING_PRIORITY'
```

**Comment by praseodym** [comment]
The monkeypatch works for us, but it would be great to see this fixed in the library.

**Comment by Kyle-Verhoog** [comment]
Hi all, looking into this issue now.

From what I can tell this behaviour is defined in the WSGI spec: https://www.python.org/dev/peps/pep-3333/#environ-variables so this shouldn't be an issue with just Django.

I think it makes sense to change our HTTP propagator to check for the converted headers as well when extracting.

**Comment by Kyle-Verhoog** [comment]
@praseodym @keattang we'll be including the fix for this issue in our upcoming release! 😄
