### ISSUE TITLE
additional context for grpc errors

### ISSUE THREAD

**Issue by kc-sn** [DataDog/dd-trace-py#4588]
### Summary of problem

We are seeing reports of transient 502 bad gateway errors from GCP services (pubsub/bigtable), and their team is unable to correlate these issues with anything on their end. I suspect these error reports are from the unary tracers on the grpc instrumentation, and I'm curious if there is any additional context I might be able to gather by modifying / implementing some custom trace logic. To be clear, I don't know exactly what I'm looking for here other than more information, as GCP support seems entirely unable to correlate these errors to anything on their side. 

### Which version of dd-trace-py are you using?

1.5.0

### Which libraries and their versions are you using?

```
attrs==22.1.0
bugsnag==4.3.0
bytecode==0.13.0
cachetools==5.2.0
cattrs==22.2.0
certifi==2022.9.24
charset-normalizer==2.1.1
ddsketch==2.0.4
ddtrace==1.5.0
envier==0.4.0
exceptiongroup==1.0.4
google-api-core==2.10.2
google-auth==2.14.1
google-cloud-bigtable==2.13.2
google-cloud-core==2.3.2
google-cloud-pubsub==2.13.11
googleapis-common-protos==1.57.0
grpc-google-iam-v1==0.12.4
grpcio==1.50.0
grpcio-status==1.48.2
idna==3.4
importlib-metadata==5.0.0
importlib-resources==5.10.0
ipaddress==1.0.23
jsonschema==4.17.0
numpy==1.21.6
packaging==21.3
pandas==1.3.5
pkgutil_resolve_name==1.3.10
prometheus-client==0.15.0
proto-plus==1.22.1
protobuf==3.20.3
psycopg2-binary==2.9.5
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==3.0.9
pyrsistent==0.19.2
python-dateutil==2.8.2
python-decouple==3.6
pytz==2022.6
requests==2.28.1
rsa==4.9
setproctitle==1.3.2
six==1.16.0
tenacity==8.1.0
typing_extensions==4.4.0
urllib3==1.26.12
WebOb==1.8.7
xmltodict==0.13.0
zipp==3.10.0
```

### How can we reproduce your problem?

publish/ack roughly 12k messages/min (30-100kb in size) to gcp pubsub and observe the bad gateway errors

![image](https://user-images.githubusercontent.com/91487203/202737549-612f8288-855a-4afe-88ec-3e15268af12e.png)

### What is the result that you get?

What appears to be a poorly managed service (Google Pubsub, mostly)

### What is the result that you expected?

To not see hundreds or thousands of transient errors a day.

**Comment by majorgreys** [comment]
Can you confirm this issue persists if you disable the grpc integration with the `DD_TRACE_GRPC_ENABLED=0` or `patch(grpc=False)`?

**Comment by emmettbutler** [comment]
@kc-sn it looks to me like there might be some additional information available in the integration's [`_ClientCallDetails.metadata`](https://github.com/DataDog/dd-trace-py/blob/458dbe0f1e42d60306ab08910ba16106f508c5df/ddtrace/contrib/grpc/client_interceptor.py#L220), though pulling that out with custom instrumentation code would be complex. It's also not clear that it would contain anything you don't already know, since it looks like it just contains some request headers.

Aside from that I don't think there's any additional context we can offer about these errors at the moment.
