### ISSUE TITLE
CLIs exiting with `builtins.SystemExit: 0` are getting parsed as an error

### ISSUE THREAD

**Issue by coilysiren** [DataDog/dd-trace-py#4606]
### Summary of problem

<img width="974" alt="image" src="https://user-images.githubusercontent.com/5768468/203379588-521d792e-4fbc-4499-9c22-fd0034c48d23.png">

### Which version of dd-trace-py are you using?

`1.6.1`

### Which version of pip are you using?

`pip 22.3.1`

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
    asttokens==2.1.0
    attrs==22.1.0
    backcall==0.2.0
    black==22.3.0
    boto3==1.24.96
    botocore==1.27.96
    bytecode==0.13.0
    cattrs==22.2.0
    certifi==2022.9.24
    charset-normalizer==2.1.1
    click==8.1.3
    coverage==5.0.4
    datadog-api-client==2.6.0
    ddsketch==2.0.4
    ddtrace==1.6.1
    decorator==5.1.1
    distlib==0.3.6
    entrypoints==0.3
    envier==0.4.0
    exceptiongroup==1.0.4
    executing==1.2.0
    filelock==3.8.0
    flake8==3.7.9
    greenlet==2.0.1
    icdiff==2.0.5
    idna==3.4
    invoke==1.7.3
    ipython==8.6.0
    isodate==0.6.0
    jedi==0.18.1
    jmespath==1.0.1
    jsonschema==4.17.0
    matplotlib-inline==0.1.6
    mccabe==0.6.1
    metrics-client==1.0.2
    more-itertools==9.0.0
    mypy-extensions==0.4.3
    packaging==21.3
    parso==0.8.3
    pathspec==0.10.2
    pexpect==4.8.0
    pickleshare==0.7.5
    pipenv==2022.11.11
    platformdirs==2.5.4
    pluggy==0.13.1
    pprintpp==0.4.0
    prompt-toolkit==3.0.33
    protobuf==4.21.9
    psycopg2-binary==2.9.3
    ptyprocess==0.7.0
    pure-eval==0.2.2
    py==1.11.0
    pycodestyle==2.5.0
    pyflakes==2.1.1
    Pygments==2.13.0
    pynamodb==4.3.1
    pyparsing==3.0.9
    pyrsistent==0.19.2
    pytest==5.3.5
    pytest-cov==2.8.1
    pytest-icdiff==0.6
    python-dateutil==2.8.2
    python-dotenv==0.10.5
    PyYAML==6.0
    requests==2.28.1
    s3transfer==0.6.0
    six==1.16.0
    SQLAlchemy==1.4.44
    sqlalchemy-redshift==0.8.9
    stack-data==0.6.1
    structured-logger==1.7.1
    tenacity==8.1.0
    textio-athena==0.5.0
    tomli==2.0.1
    traitlets==5.5.0
    typing_extensions==4.4.0
    urllib3==1.26.12
    virtualenv==20.16.7
    virtualenv-clone==0.5.7
    wcwidth==0.2.5
    xmltodict==0.13.0
</details>

### How can we reproduce your problem?

```python
import click
import ddtrace
import sys


@click.pass_context
def cli():
    # do something successful
    pass


if __name__ == "__main__":
    ddtrace.patch_all()

    with ddtrace.Tracer().trace(__file__, span_type="cli") as span:
        span.set_tags({f"agrv{index}": arg for index, arg in enumerate(sys.argv)})
        cli()
```

### What is the result that you get?

builtins.SystemExit being parsed as an error when exit code is 0, resulting an all our successful jobs being marked as "errors".

### What is the result that you expected?

builtins.SystemExit being parsed as success when exit code is 0

**Comment by ZStriker19** [comment]
Hi @coilysiren , the current behavior of the tracer is to capture any exception that is raised while the code is running and tag it as an error accordingly. To work around this there are a couple of options:
1. If you can catch the exception then you can modify the span so that does not count as an error:
```
    with tracer.trace(__file__, span_type="cli") as span:
        try:
            span.set_tags({f"agrv{index}": arg for index, arg in enumerate(sys.argv)})
            sys.exit(0)
        except SystemExit as e:
            # if termination is successful, we don't want the span to be marked as an error
            if e.code == 0:
                span = tracer.current_root_span()
                span.error = 0
            else:
                raise e
```

2. The other option would be to use a trace filter to change all spans with system exit code 0 to not be errors. In some ways the opposite of this example we have:
https://ddtrace.readthedocs.io/en/stable/troubleshooting.html#root-span-is-missing-error-details

Please let me know if either of these would fit your use case.
