### ISSUE TITLE
No ability to override default stack trace frame size

### ISSUE THREAD

**Issue by martinamps** [DataDog/dd-trace-py#4623]
### Summary of problem

No ability to override stack trace length for errors. Attempted to override it with functools but doesn't seem to work in practice:

```
>>> import ddtrace
>>> from functools import partial
>>> ddtrace.Span.set_traceback = partial(ddtrace.Span.set_traceback, limit=40)
>>> span = ddtrace.tracer.start_span("foo")
>>> import inspect
>>> inspect.signature(span.set_traceback)
<Signature (self, *, limit=40)>
```

A sample trace/error in our account has the following details:

fingerprint id: `v2.3B6279362E1BD138CC28D824D737C260`
trace id: `1917319239765696373`
span id: `9701638903928124247`
issue uuid: `fabdb59c-678a-11ed-8547-da7ad0900002`

Would be great to have this configurable!

### Which version of dd-trace-py are you using?

1.6.3

### Which version of pip are you using?

22.3.1

### Which libraries and their versions are you using?

N/A

### How can we reproduce your problem?

Trigger an error with >20 frames in the stacktrace

### What is the result that you get?

20

### What is the result that you expected?

Ability to set more than 20.

**Comment by martinamps** [comment]
Thanks @emmettbutler !

**Comment by emmettbutler** [comment]
@martinamps no problem!
