### ISSUE TITLE
Pylons - Handled Exceptions Reporting as Errors

### ISSUE THREAD

**Issue by tony-schellenberg** [DataDog/dd-trace-py#463]
This seems to be a similar problem to the following: https://github.com/DataDog/dd-trace-py/issues/418 and https://github.com/DataDog/dd-trace-py/issues/390 but for Pylons.

We have an exeption handler that is bound in the routes map. When the code handling a particular request throws an exception, this is reporting in DataDog as an error and a 500 return code. However, the exception handler remaps this from the clients perspective and they actually receive a 200.

**Comment by Kyle-Verhoog** [comment]
Hi @tony-schellenberg!

 I've been trying to reproduce the issue and want to make sure that I cover the bug you found. 

Could you provide a bit more context on the issue you're having? Some code samples would be great if possible!

Thanks

**Comment by Kyle-Verhoog** [comment]
@tony-schellenberg following up again - let us know if you still have this issue. I put out a PR #529 which covers test cases for exception handling but it does not introduce any changes to the logic.

If the issue remains could you provide us with a code sample replicating the issue or provide some more context of where your exception handler is?

Thanks!

**Comment by tony-schellenberg** [comment]
Sorry for not getting back to this sooner. This is still an issue for us but, looking at it again now with fresh eyes, I suspect that part of the issue may be that we're using some older, deprecated elements of Pylons and that may explain why it's not being intercepted properly.

Until we change how we're doing things, it probably doesn't make sense to keep this ticket open and we can reopen it in the future if it comes up again.

Cheers.

**Comment by Kyle-Verhoog** [comment]
@tony-schellenberg I see. Thanks!
