### ISSUE TITLE
Profiling a gevent app

### ISSUE THREAD

**Issue by yevhen-m** [DataDog/dd-trace-py#4632]
### Summary of problem
Don't see `gevent` mentioned in Profiling section of the documentation. Does the profiler support it? Any specific configurations required?

I've tried to enable profiling for my app with `DD_PROFILING_ENABLED` but the graph I see is not informative at all:
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/10185058/204335646-433c822e-04a7-4266-bf6c-69c22d67aa07.png">

### Which version of dd-trace-py are you using?
```
ddtrace==1.5.2
```

**Comment by ZStriker19** [comment]
Hi @yevhen-m thanks for reaching out. What version of Python are you running on? As long as it's not 3.11 (currently known performance regression), I'd recommend upgrading to 1.7.4 and trying out code provenance which can give you more insight into the library. https://docs.datadoghq.com/profiler/enabling/python/#code-provenance Please note that there's also a known performance issue with code provenance, but at least we could know if this fits your use case.
