### ISSUE TITLE
When submitting traces, response will come back 1 byte at a time

### ISSUE THREAD

**Issue by tinycogio** [DataDog/dd-trace-py#464]
strace of our uwsgi process
```
[pid 10885] 23:23:15.735284 sendto(11, "PUT /v0.3/traces HTTP/1.1\r\nHost: localhost:8126\r\nAccept-Encoding: |snip|  

[pid 10885] 23:23:15.735448 recvfrom(11, "H", 1, 0, NULL, NULL) = 1
[pid 10885] 23:23:15.735869 recvfrom(11, "T", 1, 0, NULL, NULL) = 1
[pid 10885] 23:23:15.735955 recvfrom(11, "T", 1, 0, NULL, NULL) = 1
[pid 10885] 23:23:15.736032 recvfrom(11, "P", 1, 0, NULL, NULL) = 1
|snip|
[pid 10885] 23:23:15.743480 recvfrom(11, "\r", 1, 0, NULL, NULL) = 1
[pid 10885] 23:23:15.743549 recvfrom(11, "\n", 1, 0, NULL, NULL) = 1
[pid 10885] 23:23:15.743627 recvfrom(11, "\r", 1, 0, NULL, NULL) = 1
[pid 10885] 23:23:15.743697 recvfrom(11, "\n", 1, 0, NULL, NULL) = 1
```
It seems it's due to httplib behavior: https://github.com/DataDog/dd-trace-py/blob/7a115a2c0c1ad2301361456c27bcce5b05dc13f7/ddtrace/api.py#L142

https://stackoverflow.com/questions/14519829/python-httplib-getresponse-issues-many-recv-calls

```
Ubuntu 16.04
Python 2.7.12

ddtrace==0.11.0
Django==1.11.13
uwsgi==2.0.17
```
Also opened a similar issue for the datadog python project: DataDog/datadogpy#270

**Comment by Kyle-Verhoog** [comment]
Hi @tinycogio! Can you confirm that #527 solves the issue on your end?

**Comment by tinycogio** [comment]
@Kyle-Verhoog seemed to work - thanks!

`recvfrom(12, "HTTP/1.1 200 OK\r\nDate: Fri, 03 Aug 2018 19:30:20 GMT\r\nContent-Length: 3\r\nContent-Type: text/plain; charset=utf-8\r\n\r\nOK\n", 8192, 0, NULL, NULL) = 119`

**Comment by Kyle-Verhoog** [comment]
@tinycogio great! We'll include the patch in an upcoming release. Thanks for reporting and the quick follow-up 😄
