### ISSUE TITLE
SyntaxError running dd-trace-py on Python 3

### ISSUE THREAD

**Issue by nickwilliams-eventbrite** [DataDog/dd-trace-py#472]
I received this syntax error running a program with `dd-trace-py` enabled on Python 3:

```
  File "/mnt/jenkins/workspace/generic-python3-phabricator-pipeline/src/.eggs/ddtrace-0.9.2-py3.5.egg/ddtrace/contrib/pylons/middleware.py", line 58
    raise typ, val, tb
             ^
SyntaxError: invalid syntax
```

Looking at the code in that file, [it's clearly not Python 3-compatible](https://github.com/DataDog/dd-trace-py/blob/75b727569ac5a7aa4115af6b54ba763f29dd571e/ddtrace/contrib/pylons/middleware.py#L81). Not sure much more needs to be said. This code needs to be fixed to be Python 3 compatible.

**Comment by palazzem** [comment]
Hello @nickwilliams-eventbrite ! We're investigating the issue, I'll reach you back once we have a proper test for that code path. Thanks for reporting!

**Comment by palazzem** [comment]
Also, do you have the `SyntaxError` only when using our middleware in your Pylons app? In that case, are you using the official https://pypi.org/project/Pylons/ package?

I may miss something, but does it work properly with Python 3? As far as I can see it's reported as `Python :: 2 :: Only`. Also, if I run the test suite that emulates a real application, I hit this exception:
```
======================================================================
ERROR: Failure: SyntaxError (invalid syntax (core.py, line 108))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/emanuele/workspaces/datadog/dd-trace-py/.tox/py35-pylons10/lib/python3.5/site-packages/nose/case.py", line 134, in run
    self.runTest(result)
  File "/Users/emanuele/workspaces/datadog/dd-trace-py/.tox/py35-pylons10/lib/python3.5/site-packages/nose/case.py", line 152, in runTest
    test(result)
  File "/Users/emanuele/.pyenv/versions/3.5.2/lib/python3.5/unittest/case.py", line 648, in __call__
    return self.run(*args, **kwds)
  File "/Users/emanuele/.pyenv/versions/3.5.2/lib/python3.5/unittest/case.py", line 608, in run
    self._feedErrorsToResult(result, outcome.errors)
  File "/Users/emanuele/.pyenv/versions/3.5.2/lib/python3.5/unittest/case.py", line 538, in _feedErrorsToResult
    result.addError(test, exc_info)
  File "/Users/emanuele/workspaces/datadog/dd-trace-py/.tox/py35-pylons10/lib/python3.5/site-packages/nose/proxy.py", line 132, in addError
    self.result.addError(self.test, self._prepareErr(err))
  File "/Users/emanuele/workspaces/datadog/dd-trace-py/.tox/py35-pylons10/lib/python3.5/site-packages/nose/result.py", line 61, in addError
    exc_info = self._exc_info_to_string(err, test)
  File "/Users/emanuele/workspaces/datadog/dd-trace-py/.tox/py35-pylons10/lib/python3.5/site-packages/nose/result.py", line 187, in _exc_info_to_string
    return _TextTestResult._exc_info_to_string(self, err, test)
  File "/Users/emanuele/.pyenv/versions/3.5.2/lib/python3.5/unittest/result.py", line 186, in _exc_info_to_string
    exctype, value, tb, limit=length, capture_locals=self.tb_locals)
  File "/Users/emanuele/.pyenv/versions/3.5.2/lib/python3.5/traceback.py", line 481, in __init__
    self.filename = exc_value.filename
AttributeError: 'SyntaxError' object has no attribute 'filename'
```

Where the involved line is [core.py#L108](https://github.com/Pylons/pylons/blob/069471fd347442ee93027a015a30fc64cf409b54/pylons/controllers/core.py#L108) that is not Python 3 compatible.

Probably you're using another library or fork? Not strictly related to the issue you're reporting, just want to be sure I'm getting entirely your use case.

Thanks a lot!

**Comment by nickwilliams-eventbrite** [comment]
We're not using Pylons or any fork of Pylons or a Pylon-related library or app. I've no idea how our code resulted in execution reaching this line. I can't even reliably duplicate it. The `SyntaxError` happens only when a unit test on a certain, internal project fails for some reason, but not every time that test fails. When the `SyntaxError` happens, it masks the cause of the test failure.

I see now that Pylons doesn't support Python 3; however, every line of code in `dd-trace-py` should, in my opinion, support Python 3, especially given that we are quickly approaching the EOL for Python 2.

**Comment by palazzem** [comment]
@nickwilliams-eventbrite sure thing! was only curious about the stack. I will schedule the work to make it compatible. Maybe we can have couple of iterations to be sure everything works on your stack. Sounds good?

**Comment by palazzem** [comment]
Hey @nickwilliams-eventbrite ! can you check if that PR #475 addresses your issues? If you confirm, I'll proceed with the merge and it will be available in the 0.12.1 release (you may need to upgrade your `ddtrace` dependency since it seems you're using the 0.9.2).

Thank you very much for the feedback!

**Comment by nickwilliams-eventbrite** [comment]
Note that, oddly, I'm not getting this error just _installing_ ddtrace-py. Very strange. 🤔 

```
$ setup.py test
running pytest
Searching for ddtrace~=0.9.0
Reading https://pypi.org/simple/ddtrace/
Downloading https://files.pythonhosted.org/packages/a3/8e/774f4316084a41d1553600f90e6d8acbd2408651ba25ecd6bf1ac4fee122/ddtrace-0.9.2.tar.gz#sha256=d752c02292f88198e07d2bcbdf9df8d9f36096cd8470687492a39b1513a57230
Best match: ddtrace 0.9.2
Processing ddtrace-0.9.2.tar.gz
Writing /tmp/easy_install-ux4maxhg/ddtrace-0.9.2/setup.cfg
Running ddtrace-0.9.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ux4maxhg/ddtrace-0.9.2/egg-dist-tmp-wu98waol
  File "build/bdist.linux-x86_64/egg/ddtrace/contrib/pylons/middleware.py", line 58
    raise typ, val, tb
             ^
SyntaxError: invalid syntax
```

**Comment by palazzem** [comment]
Weird, that part has been removed from middleware. Does it happen with the version that PR is pointing to? If you can check the `palazzem/pylons-improvement` branch. This part has been changed with a Python 3 compatible code.

Let me know so I can help with the triage. If it works, I'll merge and enqueue the change in the next release. Thank you!

**Comment by nickwilliams-eventbrite** [comment]
Sorry, I wasn't clear. I'm not able to test the above scenario with the PR. It's `python setup.py test` ran just like that, without PIP, so I can't really use a GitHub URL with hash, etc. Gotta be a released artifact for me to test that scenario. If it were something else (like, it happened just when running `pytest`), I could manually install it using PIP and the GitHub URL, but not when the error happens running `python setup.py test`.

I'm satisfied that the PR should, indeed, fix the issue, so I'd go ahead and merge it and release.

**Comment by palazzem** [comment]
Oh gotcha, sorry I misunderstood that part @nickwilliams-eventbrite ! sure thing, let me merge it prepare a release, I'll ping you once it's done. I'll keep this issue open until you can confirm that it's working.
