### ISSUE TITLE
Add control to which `botocore` products to trace

### ISSUE THREAD

**Issue by IlyaMichlin** [DataDog/dd-trace-py#4736]
### Summary of problem
Currently there is no ability to control which product of `botocore` to trace and which not to trace, its either all of them (the ones supported by `ddtrace`) or none of them.

Suggested interface is to leave the ability to trace all of the `botocore` products when using `patch(botocore=True)`.

The second way is to control which products to trace. There are two interface suggestions I want to make:
First is to provide a list of product names to trace:
```
patch(
    botocore=["lambda", "kinesis", "sns"]
)
```

Second is to control the products similarly to how `patch` is currently working:
```
patch(
    botocore={
        "lambda"=True,
        "kinesis"=True,
        "sns"=False,
    }
)
```

### Which version of dd-trace-py are you using?
1.6.3

### Which version of pip are you using?
22.3.1

### Which libraries and their versions are you using?
N/A

### How can we reproduce your problem?
`patch(botocore=True)`
And use one of the supported `botocore` products.

### What is the result that you get?
Tracing for all the `botocore` products supported by `ddtrace`.

### What is the result that you expected?
Trace only selected `botocore` products.

**Comment by ZStriker19** [comment]
Hi @IlyaMichlin,

Thanks for bringing this to our attention. We'll add this feature request to our backlog. Feel free to open a PR if this is an urgent request and I can help provide feedback.

In the meantime, depending on what your use case is, we may have some ways to assist. Could you provide some further insight into why tracing only certain components of botocore would be helpful to you?

**Comment by IlyaMichlin** [comment]
Hey @ZStriker19 thank you for the quick reply.

In my case, I use `Kinesis` to log some metrics and there is no need to trace that. Also I use other `AWS` products that I want to trace.

**Comment by emmettbutler** [comment]
Closing because #5342 was merged
