### ISSUE TITLE
[psycopg2] The quote_ident function requires psycopg2.extensions.connection.

### ISSUE THREAD

**Issue by eliwind** [DataDog/dd-trace-py#474]
This is very related to https://github.com/DataDog/dd-trace-py/issues/383.

To reproduce:
```
from ddtrace import patch_all
patch_all()

import psycopg2
from psycopg2.extensions import quote_ident

conn = psycopg2.connect(dbname="test")
quote_ident('foo', conn) # Fails with TypeError: argument 2 must be a connection or a cursor
```

**Comment by palazzem** [comment]
Hello @eliwind! A PR is available here https://github.com/DataDog/dd-trace-py/pull/477 that should address the issue. I'll double check it with the other connected issue #383 and will reach you again. 

In the meantime, do you want to temporarily test this branch in your development environment to validate the fix? Thank you very much!

**Comment by eliwind** [comment]
Thanks @palazzem.

Unfortunately I tried it out, and no dice.  I see your change in the version of the ddtrace code inside my venv, I can now see `quote_ident` in the list of things in ` _psycopg2_extensions`.  But when I do exactly what's in your test interactively, something isn't happy:

```>>> from ddtrace import patch_all
>>> import psycopg2
>>> from psycopg2.extensions import quote_ident
>>> conn=psycopg2.connect(dbname='mydb')
>>> quote_ident('foo', conn)
'"foo"'
>>>
>>> patch_all()
>>> conn2=psycopg2.connect(dbname='mydb')
>>> quote_ident('foo', conn2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: argument 2 must be a connection or a cursor
>>>
>>> from ddtrace.contrib.psycopg.patch import _psycopg2_extensions
>>> _psycopg2_extensions
[(<built-in function register_type>, <module 'psycopg2.extensions' from '/Users/eli/.virtualenvs/wevo-raw-survey-handler-mNlG-o--/lib/python2.7/site-packages/psycopg2/extensions.pyc'>, 'register_type', <function _extensions_register_type at 0x10dea69b0>), (<built-in function register_type>, <module 'psycopg2._psycopg' from '/Users/eli/.virtualenvs/wevo-raw-survey-handler-mNlG-o--/lib/python2.7/site-packages/psycopg2/_psycopg.so'>, 'register_type', <function _extensions_register_type at 0x10dea69b0>), (<built-in function adapt>, <module 'psycopg2.extensions' from '/Users/eli/.virtualenvs/wevo-raw-survey-handler-mNlG-o--/lib/python2.7/site-packages/psycopg2/extensions.pyc'>, 'adapt', <function _extensions_adapt at 0x10dea6a28>), (<built-in function register_type>, <module 'psycopg2._json' from '/Users/eli/.virtualenvs/wevo-raw-survey-handler-mNlG-o--/lib/python2.7/site-packages/psycopg2/_json.pyc'>, 'register_type', <function _extensions_register_type at 0x10dea69b0>), (<built-in function quote_ident>, <module 'psycopg2.extensions' from '/Users/eli/.virtualenvs/wevo-raw-survey-handler-mNlG-o--/lib/python2.7/site-packages/psycopg2/extensions.pyc'>, 'quote_ident', <function _extensions_register_type at 0x10dea69b0>)]

```

**Comment by palazzem** [comment]
OK thank you! we'll continue the investigation then.

**Comment by Kyle-Verhoog** [comment]
Hey @eliwind!

I've been digging into the issue and I can confirm that our test case was not properly testing the patching since `quote_ident` was probably patched prior to the test running.

If you try running:

```python
>>> patch_all()
>>> import psycopg2
>>> from psycopg2.extensions import quote_ident
>>> conn=psycopg2.connect(dbname='mydb')
>>> quote_ident('foo', conn)
```
do you still get the error?

**Comment by eliwind** [comment]
@Kyle-Verhoog, indeed, no error when I `patch_all()` at the beginning.

**Comment by Kyle-Verhoog** [comment]
Great!

@eliwind are you able to test it in your application and confirm that it works? Then we can close out this issue. 😄

**Comment by palazzem** [comment]
We're going to merge the PR and prepare the release. If your application is still impacted by the issue after the 0.12.1 release, feel free to re-open the issue so we can continue the triage!

Thanks a lot for your feedback on that!
