### ISSUE TITLE
Upload to PyPI failing due to quota limits

### ISSUE THREAD

**Issue by majorgreys** [DataDog/dd-trace-py#4817]
The GitHub action that uploads wheels to PyPI is failing due to the ddtrace project reaching the size quota limits. 

This blocks ddtrace releases.

https://github.com/DataDog/dd-trace-py/actions/runs/3735499666/jobs/6341830710

```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         Project size too large. Limit for project 'ddtrace' total size is 20   
         GB. See https://pypi.org/help/#project-size-limit      
```

We have opened a request to increase the project limit: 

https://github.com/pypa/pypi-support/issues/2483

**Comment by Yun-Kim** [comment]
Limit has been lifted as of https://github.com/pypa/pypi-support/issues/2483#issuecomment-1368088841
