### ISSUE TITLE
error_statuses not customizable for tornado integration

### ISSUE THREAD

**Issue by Peilun-Li** [DataDog/dd-trace-py#4838]
### Summary of problem
In one of our use cases, we are trying to mark HTTP 404 as Error (instead of Ok) for APM. As the [doc](https://ddtrace.readthedocs.io/en/stable/advanced_usage.html#custom-error-codes) suggests I've tried the following but it doesn't work (HTTP 404 still marked as error)

```
from ddtrace import patch, tracer, config

# tried here, not work
# config.http_server.error_statuses = '404,500-599'

patch(tornado=True)
tracer.configure(hostname=DD_AGENT_HOST, port=DD_AGENT_PORT, https=False)

# tried here, also not work
config.http_server.error_statuses = '404,500-599'
```

Digging a bit it looks like for tornado we are hard coding the error range [here](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/contrib/tornado/handlers.py#L107-L108). 

Anything I was missing or could we make tornado integration compatible with the `error_statuses` setting? Thanks!

### Which version of dd-trace-py are you using?
0.49.4 but guess the same applies to latest versions

**Comment by mabdinur** [comment]
Hey @Peilun-Li, 

Thanks for calling out this out. Currently we do not support `config.http_server.error_statuses` in tornado. I opened a PR to add this functionality in the next release of ddtrace (v1.8.0). 

Backporting features to earlier ddtrace releases goes against our version policy. If upgrading to the latest version of ddtrace is not an option, in your application you can override `tornado.web.RequestHandler.log_exception()`  to check `config.http_server.error_statuses`. 

Here's an example:

```python
import tornado
from ddtrace import config

class MainHandler(tornado.web.RequestHandler):
    @tornado.gen.coroutine
    def get(self):
        self.write("Hello, world")

    def on_finish(self):
        # closes ddtrace spans
        super(MainHandler, self).on_finish()
        # do other clean-up

    def log_exception(self, typ, value, tb):
        if isinstance(value, tornado.web.HTTPError):
            if not config.http_server.is_error_code(value.status_code):
                return
        # this method is patched by ddtrace and will set error tags on the tornado.request span
        return super(MainHandler, self).log_exception(typ, value, tb) 
```

Would this mitigation work for you?

**Comment by Peilun-Li** [comment]
Thanks @mabdinur , that sounds good and we can update to the next release when it's available.
