### ISSUE TITLE
Feature request: Add Gunicorn integration for tracing support

### ISSUE THREAD

**Issue by Meemaw** [DataDog/dd-trace-py#4883]
### Summary of problem

Would like to understand if the `gunicorn` tracing is supposed to work? According to the docs, there should be something, but when trying to use it we see no differences in our traces.

Looking at the [code](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/contrib/gunicorn/__init__.py), it seems to be a noop, but I assume its using the default wsgi integration.

### Which version of dd-trace-py are you using?

1.6.0

### Which version of pip are you using?

N/A

### Which libraries and their versions are you using?

gunicorn = "20.1.0"

### What is the result that you get?

No extra spans for the gunicorn request

### What is the result that you expected?

Additional span on the gunicorn server

**Comment by brettlangdon** [comment]
Hey @Meemaw thank you for opening this issue.

Apologies if our documentation is misleading but we do not have an "integration" for `gunicorn`, meaning we will not generate any spans for the gunicorn server.

Our documentation here: https://ddtrace.readthedocs.io/en/stable/advanced_usage.html#gunicorn

is just to state that our library will work when using `gunicorn` with just a few caveats to consider if you are using a `gevent` worker.

Would it be ok with you if I mark this issue as a feature request to add tracing support for `gunicorn` ?

**Comment by Meemaw** [comment]
Yes, having tracing support for `gunicorn` would be 💯

**Comment by emmettbutler** [comment]
The request for a gunicorn tracing integration is in our team's feature backlog and is not planned for the short term. As part of the backlog it will be considered during feature prioritization.

If anyone reading this is motivated to contribute the integration, please do so.
