### ISSUE TITLE
Datadog Resource_Name bug with redis Integration when value contains `\n` character

### ISSUE THREAD

**Issue by mmick78** [DataDog/dd-trace-py#4892]
### Summary of problem

We had a lot of unique resource_name taken by our redis monitoring on datadog, when we checked we saw it was all due to weird `SET ` followed by any character pattern after. We didn't have the issue anywhere else.
We tracked down the issue and we ended up seeing a code where we were generating a random mutex value equal uuid.bytes() + uuid.bytes(), that was sometimes generating a `\n` pattern and thus generating the issue. Didn't see this pattern with other special characters but it may also exist.

### Which version of dd-trace-py are you using?
1.7.0

### Which version of pip are you using?
22.2.2

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
aenum==3.1.11
aiobotocore==2.4.1
aiohttp==3.8.3
aiohttp-cors==0.7.0
aioitertools==0.11.0
aiosignal==1.3.1
alembic==1.8.1
antlr4-python3-runtime==4.11.1
apispec==5.2.2
async-timeout==4.0.2
attrs==22.1.0
boto3==1.26.34
botocore==1.27.59
bytecode==0.14.0
cachetools==5.2.0
cattrs==22.2.0
cchardet==2.1.7
certifi==2022.12.7
cffi==1.15.1
chardet==5.0.0
charset-normalizer==2.1.1
ciso8601==2.2.0
cityhash==0.4.2
click==8.1.3
coverage==6.5.0
cryptography==38.0.4
datadog==0.44.0
ddsketch==2.0.4
ddtrace==1.7.0
Deprecated==1.2.13
diff-cover==7.0.1
distconfig3==1.0.1
envier==0.4.0
exceptiongroup==1.0.4
fastjsonschema==2.16.2
flake8==5.0.4
forbiddenfruit==0.1.4
frozenlist==1.3.3
google-auth==2.12.0
greenlet==2.0.1
gunicorn==20.1.0
hiredis==2.0.0
idna==3.4
itsdangerous==2.1.2
Jinja2==3.1.2
jmespath==1.0.1
jsonschema==4.17.3
lxml==4.9.1
Mako==1.2.3
MarkupSafe==2.1.1
marshmallow==3.19.0
mccabe==0.7.0
mistune==2.0.4
multidict==6.0.3
numpy==1.23.4
orjson==3.8.0
packaging==22.0
pluggy==1.0.0
protobuf==4.21.12
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.9.1
pycparser==2.21
pyflakes==2.5.0
Pygments==2.13.0
pynamodb==5.2.1
pyparsing==3.0.9
pyrsistent==0.19.2
python-dateutil==2.8.2
pytz==2022.1
PyYAML==6.0
redis==4.3.4
requests==2.28.1
responses==0.22.0
rsa==4.9
s3transfer==0.6.0
sentry-sdk==1.10.1
Shapely==1.8.4
six==1.16.0
SQLAlchemy==1.4.41
SQLAlchemy-Utils==0.38.3
sqlparse==0.4.3
tenacity==8.1.0
time-machine==2.8.2
toml==0.10.2
types-toml==0.10.8.1
typing_extensions==4.3.0
tzdata==2022.6
unittest-xml-reporting==3.2.0
urllib3==1.26.13
vyper-config==1.1.1
watchdog==2.2.0
webargs==8.2.0
Werkzeug==2.2.2
wrapt==1.14.1
xmltodict==0.13.0
yarl==1.8.1
</details>

### How can we reproduce your problem?
Minimal Code:
```
import ddtrace
import redis

# Init ddtrace tracer + patch redis
dd_tracer = ddtrace.Tracer()
dd_tracer.configure(
    enabled=True,
    hostname='localhost',
    port=8126,
    https=False
)
ddtrace.patch(redis=True)

# Init redis + send normal set value
redis_client = redis.Redis()
redis_client.set(name='test', value=b'test_value', ex=10)

# Send faulty set value
faulty_value = b'test_value' + b'\n' + b'Key_Generated'

# Send faulty set value
redis_client.set(name='test_faulty', value=faulty_value, ex=10)
```

Require also a local docker container with datadog + datadog Ui to visualize the resource_name taken under service `redis`

### What is the result that you get?
2 resource_name being created, one called `SET` (as expected) and another one called `SET KEY_GENERATED`

### What is the result that you expected?
Only one resource_name `SET`

**Comment by emmettbutler** [comment]
Thank you for the issue report, @mmick78. I agree the behavior you're seeing is confusing and unexpected.

dd-trace-py actually includes the key name (and value, in the case of `SET` commands) in the `span.resource` attribute, as you can see in [this test code](https://github.com/DataDog/dd-trace-py/blob/81ead41b525799cab64439042464cd91499600cd/tests/contrib/redis/test_redis.py#L106). Accordingly, I'm not sure why you're seeing resource name `SET` in the UI without a key or value. I suspect it's some backend processing that happens after dd-trace-py sends a span. You might try running your test again with the latest version to make sure you're not seeing behavior that changed recently.

My current theory is that whatever backend processing happens on these resource names treats newlines in a special way. If that were the case the fix would be to remove newlines from resource names before spans are sent to the agent.

**Comment by emmettbutler** [comment]
https://github.com/DataDog/dd-trace-py/pull/7425 changes the default behavior of the redis integration to avoid including keys and values in resource names. When that's merged, I think this can be closed.
