### ISSUE TITLE
DD_TRACE_STARTUP_LOGS can get called multiple times resulting serialization exception

### ISSUE THREAD

**Issue by thehesiod** [DataDog/dd-trace-py#4896]
### Summary of problem
Typical workflow is calling tracer.configure, and if DD_TRACE_STARTUP_LOGS is enabled it will log some extra info.  If you have botocore tracing enabled, then make a botocore call, it will add a key to config.botocore.operations via [patched_api_call](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/contrib/botocore/patch.py#L316), which due to the [defaultdict](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/contrib/botocore/patch.py#L68), will create a _HTTPServerConfig in the config module.  If you then call aiohttp trace_app, it will call configure again: https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/contrib/aiohttp/middlewares.py#L144 which will cause it to try to serialize this _HTTPServerConfig and fail:
```
  File "fbn_async_server/base_server.py", line 109, in set_app
    trace_app(app, global_apm_tracer, service=server_name)
  File "ddtrace/contrib/aiohttp/middlewares.py", line 144, in trace_app
    tracer.configure(context_provider=context_provider)
  File "ddtrace/tracer.py", line 491, in configure
    msg = "- DATADOG TRACER CONFIGURATION - %s" % json.dumps(info)
  File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _HTTPServerConfig is not JSON serializable
```

I think the DD_TRACE_STARTUP_LOGS is only meant to happen once, so perhaps it should keep track that it has already run, or, don't have trace_app call configure, and instead directly set what it needs to set.

### Which version of dd-trace-py are you using?
latest

### Which version of pip are you using?
unrelated

### Which libraries and their versions are you using?
unrelated

### How can we reproduce your problem?
see description

### What is the result that you get?
exception during start-up

### What is the result that you expected?
no-exception

**Comment by viginti23** [comment]
Did you manage to solve this issue?

**Comment by thehesiod** [comment]
we changed the order of calls

**Comment by xxthegonzxx** [comment]
I just wanted to contribute and say that we are also experiencing this issue. We had to temporarily comment out the `tracer.configure` method in our settings.py file in order to get this working properly.
