### ISSUE TITLE
How to add multilevel tags

### ISSUE THREAD

**Issue by jimymodi** [DataDog/dd-trace-py#490]
I would like to add multilevel tags like
![multi_level_metadata](https://user-images.githubusercontent.com/415224/41358182-7891f930-6f45-11e8-814b-a8132eb5633f.png)
I tried passing mutilevel dict to `set_tag` function. But it didn't worked.
```
consumer_root_span.set_tags({
	'kafka' : {
		'topic' : msg.topic,
		'partition': msg.partition,
		'offset': msg.offset
		}
	})

```

**Comment by palazzem** [comment]
Hello @jimymodi! to set a tag you should prefix your tags with a dot. Based on your code, it should be:
```python
consumer_root_span.set_tags({
    'kafka.topic': msg.topic,
    'kafka.partition': msg.partition,
    'kafka.offset': msg.offset,
})
```

Can you confirm that?

**Comment by jimymodi** [comment]
It works ! Thanks
![image](https://user-images.githubusercontent.com/415224/41374252-4323cc12-6f70-11e8-927f-cba5937e17a4.png)
