### ISSUE TITLE
UWSGI process fails to respond after Harakiri/respawn

### ISSUE THREAD

**Issue by georgmzimmer** [DataDog/dd-trace-py#491]
We run a django application under UWSGI.  We use harakiri to protect against stuck processes.  Any request that takes longer than 60 seconds will trigger a Harakiri in the worker process and the master uwsgi process will spawn a new child process.  This works very well when datadog is not installed.

When datadog is installed, however, uwsgi starts a new child process but that newly-spawned process never responds to any more requests.

Attached is an example from our logs.  Look for the word DAMN.  Please notice, activity for the new worker process that is started is absent from the log.  

[web1.log.txt](https://github.com/DataDog/dd-trace-py/files/2103018/web1.log.txt)

After a while, this happens again, and then there are no more responding workers and the server becomes inaccessible for web requests.

If we remove datadog, we do not experience this problem.

Also attached is the configuration file we use for UWSGI.  We are using UWSGI 2.0.17
[django.ini.txt](https://github.com/DataDog/dd-trace-py/files/2102943/django.ini.txt)

What could be going wrong?

**Comment by sabw8217** [comment]
Try setting lazy-apps to true.

https://uwsgi-docs.readthedocs.io/en/latest/Options.html?highlight=lazy-apps#lazy-apps

**Comment by georgmzimmer** [comment]
Thanks.  We'll try it.

**Comment by georgmzimmer** [comment]
lazy-apps does fix the problem.  Thank you!
