### ISSUE TITLE
Cannot run `ddtrace-run celery worker` attempts to execute celery with python

### ISSUE THREAD

**Issue by jcummins54** [DataDog/dd-trace-py#493]
`ddtrace-run celery` runs the celery application, but if anything is added after "celery" ddtrace-run attempts to run it with python:

```
$ ddtrace-run celery worker --queues default --loglevel=INFO --concurrency=4 --maxtasksperchild=100 -n default.%%n

/home/vagrant/venv/bin/python2.7 /home/vagrant/venv/bin/celery worker --queues default --loglevel=INFO --concurrency=4 --maxtasksperchild=100 -n default.%%n: can't open file '/home/vagrant/venv/bin/celery worker --queues default --loglevel=INFO --concurrency=4 --maxtasksperchild=100 -n default.%%n': [Errno 2] No such file or directory
```

Update: This is only an issue with ddtrace 0.12.1, verified that ddtrace 0.12.0 runs celery. However, we aren't seeing APM metrics in the dashboard either way.

**Comment by palazzem** [comment]
Hello @jcummins54 and thanks for the feedback! I'm checking this issue with the `ddtrace-run` script that requires more work in this 0.12.x release. Once I've reproduced the problem, I'll provide you a PR to test so that we're sure the script properly wraps any kind of binary.

**Comment by mgu** [comment]
Same error for me when lauching gunicorn.
If I revert https://github.com/DataDog/dd-trace-py/pull/469/files the error disappears.

Looks like sys.argv is not filled for a good reason https://bugs.python.org/issue2972

**Comment by mgu** [comment]
After some tests, the error with gunicorn appears with ddtrace 0.12.1 AND setproctitle installed.
If I uninstall setproctitle then I can launch gunicorn without error

**Comment by mgu** [comment]
I can test your fix before the release if it can help

**Comment by Kyle-Verhoog** [comment]
Hi @jcummins54, @mgu 

I've been looking into this issue, can you provide some more detail about your setups? A regression test or sample app would be of great help!

**Comment by mgu** [comment]
I will try to setup a test or a small app in order to reproduce this issue, I'll keep you updated

**Comment by mgu** [comment]
Harder to reproduce than expected (on a dedicated app), I'll try something else tomorrow :)

**Comment by Kyle-Verhoog** [comment]
Hey @mgu thanks so much for the effort! Haha, I had absolutely no success replicating it either.

Don't worry about trying to replicate further. We've changed our patching mechanism for `celery` with #534. It is also based off of #530 which should include our improved `celery` integration. 

If you could try using the `kyle-verhoog/celery-hook` branch and report back if you have any problems that'd be awesome!

Thanks 😄

**Comment by mgu** [comment]
Tested (with a fix to avoid undefined `patched` variable in monkey.py) : 
- `[Errno 2] No such file or directory` is gone
- it seems to work without `patch(celery=True)`

Thanks a lot ! :grin:

**Comment by palazzem** [comment]
Great @mgu ! ok we'll connect all the dots to prepare our release. We had also other positive feedbacks so we can proceed. I'll keep the thread updated.

Thank you very much, especially for your patience!
