### ISSUE TITLE
Support for Pymemcache

### ISSUE THREAD

**Issue by jamescarr** [DataDog/dd-trace-py#496]
I noticed that DD APM didn't pick up memcached calls in our application while NR APM did. It seems this is really down to the fact that the Datadog integration [explicitly patches pylibmc](https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/pylibmc/patch.py#L1) while the New Relic integration [generically wraps the module](https://github.com/edmorley/newrelic-python-agent/blob/master/newrelic/newrelic/hooks/datastore_memcache.py#L65). 

I took a quick look and it seems that [pymemcache](https://github.com/pinterest/pymemcache) supports the same methods that pylibmc does and the `**kwargs` in the client wrapper used by DataDog can pass the additional arguments down without issue. 

I think this would be an easy add, although I'm not quite sure how we could patch the client through django settings. 🤔

**Comment by Kyle-Verhoog** [comment]
Pymemcache support was merged with #511. It will be included in the upcoming 0.13 release.
