### ISSUE TITLE
Tornado Tracer configuration doesn't have access to settings object for Trace Filtering

### ISSUE THREAD

**Issue by kave** [DataDog/dd-trace-py#499]

**Comment by palazzem** [comment]
Hello @kave and thanks for the feedback! In the current implementation, you can still use the Tracer configuration to access the Trace Filtering. It means having:
```python
# we assume Tornado is patched as described in our docs
import tornado.web
from ddtrace import tracer

settings = {
    'datadog_trace': {
        'default_service': 'my-tornado-app',
        'tags': {'env': 'production'},
        'distributed_tracing': True,
    },
}

app = tornado.web.Application([
    (r'/', MainHandler),
], **settings)

tracer.configure(settings={
    'FILTERS': [
        FilterRequestsOnUrl(r'http://test\.example\.com'),
    ],
})
```
Does it work for you, or you would like to put everything in the Tornado settings? It's something we should do (for consistency), but it's just to get the sense of priority. Thanks a lot!

**Comment by palazzem** [comment]
@kave I've updated your PR #498 . Let me know if the problem is addressed that way! thank you!
