### ISSUE TITLE
Feature: Add support for tracing Kafka libraries

### ISSUE THREAD

**Issue by mironnn** [DataDog/dd-trace-py#5027]
Could you please advise, does `ddtrace` can trace aiokafka, confluent-kafka, etc..

**Comment by brettlangdon** [comment]
hey @mironnn thanks for opening the issue.

We do not yet have support for aiokafka, confluent-kafka, or any other kafka library.

**Comment by mironnn** [comment]
@brettlangdon is worth waiting for? is this included in the next milestone? It is a blocker for us.

**Comment by brettlangdon** [comment]
We have plans to work on this, but no ETA available at the moment.

**Comment by mironnn** [comment]
Understood, thank you

**Comment by ffissore** [comment]
Version 1.11.0 breaks confluent-kafka `AvroConsumer` and `AvroProducer` classes, because, compared to `Consumer` and `Producer`, they have additional fields not listed in the `__slots__` of `TracedConsumer` and `TracedProducer`.

The traceback is
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 521, in <module>
    AvroConsumer(
  File "/home/federico/.pyenv/versions/test-env/lib/python3.11/site-packages/confluent_kafka/avro/__init__.py", line 161, in __init__
    self._serializer = MessageSerializer(schema_registry, reader_key_schema, reader_value_schema)
    ^^^^^^^^^^^^^^^^
AttributeError: 'cimpl.Consumer' object has no attribute '_serializer'
```

[I have a fix](https://github.com/DataDog/dd-trace-py/compare/1.x...ffissore:dd-trace-py:1.x) but it's probably naive and lacks test coverage. I'll try to make it better in the coming days but don't hold your breath.

**Comment by Yun-Kim** [comment]
Hi @mironnn, as of ddtrace==1.11.0, we provide an integration for the `confluent-kafka` library. Note that there is currently a known issue with it as mentioned above in #5494, but we have a change in review that should fix the issue.

I'll close this issue in the meantime.

**Comment by shubh28** [comment]
Hello, is there an integration with [kafka-python](https://kafka-python.readthedocs.io/en/master/) library?

**Comment by ls-cam-smith** [comment]
Hi @Yun-Kim @brettlangdon, similar question, is it possible to use custom instrumentation in my code to have data streams monitoring support for unsupported libraries/message brokers?

I see this is possible in the golang and java ddtrace libraries, and was wondering if some prior art exists as a useful reference.

**Comment by kzap** [comment]
We're also looking for support for https://kafka-python.readthedocs.io/en/master/ at our company.
