### ISSUE TITLE
ddtrace always display to Error Status

### ISSUE THREAD

**Issue by xncbf** [DataDog/dd-trace-py#5028]
I running django application in k8s as container.

This is my django logging setting in `settings.py`
```py
import ddtrace

ddtrace.patch(logging=True)

LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": (
                    "%(asctime)s %(levelname)s [%(name)s] [%(filename)s:%(lineno)d] "
                    "[dd.service=%(dd.service)s dd.env=%(dd.env)s "
                    "dd.version=%(dd.version)s "
                    "dd.trace_id=%(dd.trace_id)s dd.span_id=%(dd.span_id)s] "
                    "- %(message)s"
                ),
            },
            "simple": {"format": "%(levelname)s %(message)s"},
        },
        "handlers": {
            "console": {
                "level": "DEBUG",
                "class": "logging.StreamHandler",
                "formatter": "verbose",
                "stream": sys.stdout,
            }
        },
        "loggers": {
            "django.request": {"handlers": ["console"], "level": "DEBUG"},
            "django.server": {"handlers": ["console"], "level": "DEBUG"},
            "root": {
                "handlers": ["console"],
                "level": "DEBUG",
            },
        },
    }
```

Here are some of the logs collected by container :

> ```2023-02-03 09:02:22,628 DEBUG [ddtrace.tracer] [tracer.py:749] [dd.service=rcs-chatbot dd.env=dev dd.version=0.1 dd.trace_id=0 dd.span_id=0] - finishing span name='django.request' id=18389100229012140599 trace_id=9425158709616909114 parent_id=None service='servicename' resource='GET health' type='web' start=1675414942.6220047 end=1675414942.6283667 duration=0.00636207 error=0 tags={'asgi.spec_version': '2.3', 'asgi.version': '3.0', 'django.request.class': 'django.core.handlers.asgi.ASGIRequest', 'django.response.class': 'django.http.response.HttpResponse', 'django.user.is_authenticated': 'False', 'django.view': 'core.urls.<lambda>', 'env': 'dev', 'http.method': 'GET', 'http.route': 'health', 'http.status_code': '200', 'http.url': 'http://172.31.188.221:80/health', 'http.useragent': 'kube-probe/1.24+', 'http.version': '1.1', 'runtime-id': '75ffadf93e994ac0b114eaeeaf23c6d7', 'version': '0.1'} metrics={'_dd.measured': 1, '_dd.rule_psr': 0.1, '_dd.top_level': 1, '_dd.tracer_kr': 1.0, '_sampling_priority_v1': -1, 'process_id': 876} (enabled:True)```

All logs marked as error 

<img width="267" alt="image" src="https://user-images.githubusercontent.com/9462045/216558532-db8d9d4d-fb16-405a-9493-014521528803.png">

please tell me what am i doing wrong.

**Comment by xncbf** [comment]
I solved it. The cause was completely different.

I am using the us3.datadoghq.com server, but when I first installed the agent on my server, I set the site setting to the default value.
When I checked the log of cluster pods, I saw the following error, and it returned to normal as soon as I set up the site properly.

> API Key invalid, dropping transaction for https://orchestrator.datadoghq.com/api/v2/orch

**Comment by brettlangdon** [comment]
Glad to hear you resolved it! Thank you for following up here.
