### ISSUE TITLE
Please support Dramatiq

### ISSUE THREAD

**Issue by santigandolfo** [DataDog/dd-trace-py#5043]
### Summary of problem

Please consider adding [dramatiq](https://github.com/Bogdanp/dramatiq) to the [list of supported libraries](https://docs.datadoghq.com/tracing/trace_collection/compatibility/python/#library-compatibility). It currently has around 3.4k stars on github, so it is certainly a popular and widely used library.

### Which version of dd-trace-py are you using?

1.7.4

### Which version of pip are you using?

23.0

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
dramatiq==1.13.0
</details>

### How can we reproduce your problem?

When you currently use ddtrace like with dramatiq like so:

```
$ ddtrace-run dramatiq app.main
```

### What is the result that you get?

Nothing really happens.

### What is the result that you expected?

The app should how up under Datadog / APM / Services.

**Comment by oav17** [comment]
It would be nice to support Dramatiq. Do you think it's possible?
