### ISSUE TITLE
Configuring tracer endpoint

### ISSUE THREAD

**Issue by j-vizcaino** [DataDog/dd-trace-py#509]
The current tracer implementation relies on a global variable that gets initialised with the default Tracer() values. Once this is done, traces and spans can be created and published.

Now, we want to have the tracer send traces to a different endpoint. The use-case for this is that the traced program lives in a container and needs to talk to the trace agent running on the host. As a result, `localhost:8126` is not a valid endpoint, from the application point-of-view.

Configuring the tracer client is achieved by the `bootstrap` phase of the application and calls the `tracer.configure()` function to do so.

The problem is that this happens after traces have already been submitted. As a result, https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/writer.py#L36 has already created an AsyncWorker that tries to send traces to localhost.

When `trace.configure()` is called, it will happily overwrite the existing worker and replace it with the new one, using the correct endpoint, **but it never stops the thread started by the previous worker**.

As a result:

* the library logs errors submitting traces, since it targets the wrong endpoint. From a user perspective, this is misleading since all traces generated after the config change are properly uploaded and the user might think the configuration step never succeeded
* all traces generated before the configuration is done are lost.

**Comment by brettlangdon** [comment]
This has been resolved in #524
