### ISSUE TITLE
ddtrace-run build too slow.

### ISSUE THREAD

**Issue by xncbf** [DataDog/dd-trace-py#5119]
I am using k8s and deploy api application to pod.
But ddtrace build takes too long.
About 10 seconds when ddtrace is not included in the run,
Running it with the ddtrace-run command takes about 5 minutes. Can I pre-run everything needed to build and install when dockerize?

**Comment by xncbf** [comment]
I just tried 1.7.5. but still slow and server try install dependencies for ddtrace


>Collecting git+https://github.com/Datadog/dd-trace-py@637bd68ef765bd9eb4a5f7ac374713c02227f790
  Cloning https://github.com/Datadog/dd-trace-py (to revision 637bd68ef765bd9eb4a5f7ac374713c02227f790) to /tmp/pip-req-build-ju89b7u6
  Running command git clone --filter=blob:none --quiet https://github.com/Datadog/dd-trace-py /tmp/pip-req-build-ju89b7u6
  Running command git rev-parse -q --verify 'sha^637bd68ef765bd9eb4a5f7ac374713c02227f790'
  Running command git fetch -q https://github.com/Datadog/dd-trace-py 637bd68ef765bd9eb4a5f7ac374713c02227f790
  Running command git checkout -q 637bd68ef765bd9eb4a5f7ac374713c02227f790
  Resolved https://github.com/Datadog/dd-trace-py to commit 637bd68ef765bd9eb4a5f7ac374713c02227f790
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting ddsketch>=2.0.1
  Downloading ddsketch-2.0.4-py3-none-any.whl (18 kB)
Collecting packaging>=17.1
  Downloading packaging-23.0-py3-none-any.whl (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.7/42.7 kB 6.4 MB/s eta 0:00:00
Collecting tenacity>=5
  Downloading tenacity-8.2.1-py3-none-any.whl (24 kB)
Collecting cattrs
  Downloading cattrs-22.2.0-py3-none-any.whl (35 kB)
Collecting six>=1.12.0
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting typing-extensions
  Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting jsonschema
  Downloading jsonschema-4.17.3-py3-none-any.whl (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.4/90.4 kB 13.2 MB/s eta 0:00:00
Collecting xmltodict>=0.12
  Downloading xmltodict-0.13.0-py2.py3-none-any.whl (10.0 kB)
Collecting envier
  Downloading envier-0.4.0-py3-none-any.whl (10 kB)
Collecting attrs>=20
  Downloading attrs-22.2.0-py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 16.9 MB/s eta 0:00:00
Collecting protobuf>=3
  Downloading protobuf-4.21.12-cp37-abi3-manylinux2014_x86_64.whl (409 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 409.8/409.8 kB 60.5 MB/s eta 0:00:00
Collecting bytecode
  Downloading bytecode-0.14.0-py3-none-any.whl (37 kB)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Downloading pyrsistent-0.19.3-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 13.4 MB/s eta 0:00:00
Building wheels for collected packages: ddtrace
  Building wheel for ddtrace (pyproject.toml): started

**Comment by Kyle-Verhoog** [comment]
@xncbf based off your logs it looks like v1.7.2 is being used:

```
~/d/auto_inject ❯❯❯ docker run -it gcr.io/datadoghq/dd-lib-python-init:v1.7.2 head -n11 sitecustomize.py
"""
This module when included on the PYTHONPATH will install the ddtrace package from pypi
for the Python runtime being used.
"""
import os
import sys


# This special string is to be replaced at container build time so that the
# version is fixed in the source.
version = "git+https://github.com/Datadog/dd-trace-py@637bd68ef765bd9eb4a5f7ac374713c02227f790"
```

**Comment by xncbf** [comment]
```
annotations:
        admission.datadoghq.com/python-lib.version: "v1.7.5"
```

Big thanks! this was my solution.
