### ISSUE TITLE
Running Django shell without `ddtrace-run` causes logging errors 

### ISSUE THREAD

**Issue by apolloFER** [DataDog/dd-trace-py#513]
Steps to reproduce:

1. Add `ddtrace.contrib.django` to `INSTALLED_APPS` in your Django settings.
2. Launch Django shell: `python manage.py shell`
3. A rogue error message appears - `No handlers could be found for logger "ddtrace.writer"`

It will also appear every time you run something that initialises Django (like a celery app) and loads the ddtrace Django app without using `ddtrace-run`.

If you add `logging.getLogger('ddtrace.writer').addHandler(logging.NullHandler())` somewhere in your codebase there will be no log error.

It's and identical issue like this one: https://github.com/DataDog/datadogpy/issues/130

**Comment by Kyle-Verhoog** [comment]
Hey @apolloFER - looking into this now and trying to reproduce the issue to confirm a fix. Following the steps you provided assuming a Django version and Python version didn't seem to give me the error.

Could you please provide the version of Python, Django, ddtrace you are using?
