### ISSUE TITLE
aiohttp middleware tracing closes span too soon

### ISSUE THREAD

**Issue by thehesiod** [DataDog/dd-trace-py#5132]
currently it's closed in `on_prepare` handler: https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/contrib/aiohttp/middlewares.py#L119

The problem is that the access logger happens after on_prepare so the access lines don't get the trace info attached to it.

**Comment by emmettbutler** [comment]
This sounds quite similar to https://github.com/DataDog/dd-trace-py/issues/6030

**Comment by thehesiod** [comment]
also potentially related: https://github.com/DataDog/dd-trace-py/issues/1619

**Comment by kravemir** [comment]
> The problem is that the access logger happens after on_prepare so the access lines don't get the trace info attached to it.

It doesn't seem to be solved. The StreamResponse support fix only fixed it conditionally - for StreamResponse only.

**Comment by kravemir** [comment]
It can be worked around by preserving the `span` in `aiohttp.web.Request` via middleware:

```python
@middleware
async def preserve_trace_for_access_log(request: aiohttp.web.Request, handler):
    span = ddtrace.tracer.current_span()

    trace_id, span_id = (
        (span.trace_id & ((1 << 64) - 1), span.span_id) if span else (None, None)
    )

    request["dd_trace_log_vars"] = {
        "dd.trace_id": str(trace_id or 0),
        "dd.span_id": str(span_id or 0),
    }

    return await handler(request)
```

Then it's available in the call of `log` method of `AbstractAccessLogger`, using:

```python
dd_trace_log_vars = (
    request["dd_trace_log_vars"] if "dd_trace_log_vars" in request else {}
)
```
