### ISSUE TITLE
No APM support for redis-py's RedisCluster

### ISSUE THREAD

**Issue by zakaf** [DataDog/dd-trace-py#5157]
### Summary of problem
redis-py-cluster has reached EOL in favor of redis-py 4, which has RedisCluster built-in support ([official notice](https://github.com/Grokzen/redis-py-cluster#redis-py-cluster-eol)).
However, RedisCluster in redis-py 4 can't be traced with dd-trace-py.

### Which version of dd-trace-py are you using?
1.7.5

### Which version of pip are you using?
21.3.1

### How can we reproduce your problem?
replace existing redis-py-cluster with redis-py 4.1.0 or greater

### What is the result that you get?
no trace on RedisCluster

### What is the result that you expected?
trace on RedisCluster's execute_command, pipeline and ClusterPipeline's execute just like RedisCluster in redis-py-cluster

I've briefly wrote below in my own codebase and it seems to work
```
wrapt.wrap_function_wrapper("redis.cluster", "RedisCluster.execute_command", traced_execute_command(config.redis))
wrapt.wrap_function_wrapper("redis.cluster", "RedisCluster.pipeline", traced_pipeline)
Pin(service=None).onto(redis.cluster.RedisCluster)
```

**Comment by mabdinur** [comment]
Hi @zakaf, 

Thanks for bringing this to our attention. I opened the following PR to add support for `redis.cluster`: https://github.com/DataDog/dd-trace-py/pull/5164. Would you like to own this PR and push this feature request along (add tests, fix failing tests, etc.)? I am currently busy but I should be able to get to back to this in the coming weeks.

**Comment by zakaf** [comment]
Thanks for the quick response @mabdinur 
i'll take a look at the PR and make the necessary changes.
