### ISSUE TITLE
gunicorn documentation clarification

### ISSUE THREAD

**Issue by ewdurbin** [DataDog/dd-trace-py#5228]
### Summary of problem

I'm having a hard time determining if I can use gunicorn under ddtrace-run with version 1.9.0 with Python 3.11 and "vanilla" workers.

### Which version of dd-trace-py are you using?

Currently 1.7.3, but we'd like to upgrade!

---

In reviewing the changelog for 1.9.0 in https://github.com/pypi/warehouse/pull/13103, I noted a callout about gunicorn and took a look at the docs linked. I walked away a little more confused than enlightened.

https://ddtrace.readthedocs.io/en/latest/integrations.html#gunicorn states:

> Note: ddtrace-run and Python 2 are both not supported with [Gunicorn](https://gunicorn.org/).
> 
> ddtrace only supports Gunicorn’s gevent worker type when configured as follows:
>   - The application is running under a Python version >=3.6 and <=3.10
>   - ddtrace-run is not used
>   - ...

I believe I can confidently read the note as: Python 2 is not supported, neither ddtrace-run nor gunicorn support it.

But I'm seeking clarification on the second point and associated bullets. Is this saying that Python 3.11 is unsupported entirely or just when running under gevent workers?

**Comment by Yun-Kim** [comment]
Thanks for reaching out @ewdurbin!

If you're not using gevent in your application or using gevent workers in your gunicorn application, this shouldn't apply to you and you continue to use gunicorn under `ddtrace-run`. This changelog entry is only referring to cases involving gevent.

**Comment by ewdurbin** [comment]
Thanks. That clarifies enough for me!
