### ISSUE TITLE
gunicorn is randomly crashing after ddtrace 1.9.0 update

### ISSUE THREAD

**Issue by ecarruda** [DataDog/dd-trace-py#5258]
### Summary of problem

gunicorn process started to crash after updating dd-trace without any other change on the environment.

### Which version of dd-trace-py are you using?

1.9.0

### Which version of pip are you using?

22.0.2

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
anyio==3.6.2
attrs==22.1.0
autocommand==2.2.2
Babel==2.11.0
boto3==1.26.80
botocore==1.29.80
bytecode==0.14.0
cattrs==22.2.0
certifi==2022.12.7
charset-normalizer==2.1.1
cheroot==9.0.0
CherryPy==18.8.0
click==8.1.3
ddsketch==2.0.4
ddtrace==1.9.0
disposable-email-domains==0.0.86
dnspython==2.2.1
envier==0.4.0
exceptiongroup==1.0.4
gevent==22.10.2
greenlet==2.0.1
gunicorn==20.1.0
h11==0.14.0
httptools==0.5.0
idna==3.4
inflect==6.0.2
install==1.3.5
jaraco.classes==3.2.3
jaraco.collections==3.8.0
jaraco.context==4.2.0
jaraco.functools==3.5.2
jaraco.text==3.11.0
jmespath==1.0.1
jsonschema==4.17.3
money==1.3.0
more-itertools==9.0.0
numpy==1.23.5
packaging==22.0
phonenumberslite==8.13.6
Pillow==9.4.0
portend==3.1.0
protobuf==4.21.12
pydantic==1.10.2
PyJWT==2.6.0
pymongo==4.3.3
pyrsistent==0.19.2
python-dateutil==2.8.2
python-dotenv==0.21.0
pytz==2022.7.1
PyYAML==6.0
requests==2.28.2
s3transfer==0.6.0
sentry-sdk==1.16.0
setproctitle==1.3.2
shapely==2.0.1
six==1.16.0
sniffio==1.3.0
tempora==5.1.0
tenacity==8.1.0
twilio==7.16.4
typing_extensions==4.4.0
urllib3==1.26.13
uvicorn==0.20.0
uvloop==0.17.0
watchfiles==0.18.1
websockets==10.4
xmltodict==0.13.0
zc.lockfile==2.0
zope.event==4.5.0
zope.interface==5.5.2
</details>

### How can we reproduce your problem?

All my clusters, instances, on premises machines and etc running gunicorn with dd-trace are crashing randomly al day, downgrading to 1.8.0 it completeness stop.
 
### What is the result that you get?

Mar  3 03:22:59 kernel: [6735145.729814] gunicorn: worke[723250]: segfault at 7f273801d ip 00007f279e4811e0 sp 00007f27447e0da0 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:23:08 kernel: [6735154.508807] gunicorn: worke[723298]: segfault at 0 ip 00007f279e4c2b6c sp 00007f27447e07a0 error 6 in libddwaf.so[7f279e474000+f5000]
Mar  3 03:23:12 kernel: [6735158.516370] gunicorn: worke[723362]: segfault at 7f2724008 ip 00007f279e4811e0 sp 00007f27447e0da0 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:23:44 kernel: [6735190.438814] gunicorn: worke[723665]: segfault at 7f2734001 ip 00007f279e4811e0 sp 00007f27447e0da0 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:24:00 kernel: [6735206.468727] gunicorn: worke[723787]: segfault at 7f271c2cf ip 00007f279e4811e0 sp 00007f2740989da0 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:24:01 kernel: [6735207.749674] gunicorn: worke[723837]: segfault at 7f20ce72a296 ip 00007f279e48af40 sp 00007f2743fdfa80 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:24:14 kernel: [6735221.001198] gunicorn: worke[723449]: segfault at 7f273c054 ip 00007f279e4811e0 sp 00007f27447e0da0 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:24:15 kernel: [6735221.512751] gunicorn: worke[723737]: segfault at 0 ip 00007f279e48db5f sp 00007f27427dc7a0 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:24:15 kernel: [6735221.956504] gunicorn: worke[716875]: segfault at 7f27440ce ip 00007f279ec821e0 sp 00007f2748a5b690 error 4 in libddwaf.so[7f279ec40000+f5000]
Mar  3 03:24:22 kernel: [6735229.015082] gunicorn: worke[724072]: segfault at 7f20c2735ee5 ip 00007f279e48af40 sp 00007f27447e0a80 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:24:24 kernel: [6735230.539746] gunicorn: worke[724168]: segfault at 10 ip 00007f279e48d2b4 sp 00007f2743fdf7f8 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:24:27 kernel: [6735233.794380] gunicorn: worke[724225]: segfault at 7f20c2739849 ip 00007f279e4811e0 sp 00007f2741fdbda0 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:24:46 kernel: [6735252.579951] gunicorn: worke[724344]: segfault at 2d0 ip 00007f279e48d2b4 sp 00007f274118a7f8 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:24:59 kernel: [6735265.833884] gunicorn: worke[724274]: segfault at 7f272801d ip 00007f279e4811e0 sp 00007f27447e0da0 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:25:07 kernel: [6735274.159067] gunicorn: worke[724390]: segfault at 7f27340a8 ip 00007f279e4811e0 sp 00007f27437dd690 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:25:24 kernel: [6735290.527492] gunicorn: worke[724582]: segfault at 7f2734325 ip 00007f279e4811e0 sp 00007f27447df690 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:25:29 kernel: [6735295.892873] gunicorn: worke[724534]: segfault at 7f273c0a9 ip 00007f279e4811e0 sp 00007f27427dcda0 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:25:32 kernel: [6735298.955429] gunicorn: worke[724767]: segfault at 7f273c065 ip 00007f279e4811e0 sp 00007f2741adcda0 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:25:43 kernel: [6735310.037696] gunicorn: worke[724606]: segfault at 7f273400e ip 00007f279e4811e0 sp 00007f272b3fbda0 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:25:48 kernel: [6735314.565332] gunicorn: worke[724981]: segfault at 7f2724009 ip 00007f279e4811e0 sp 00007f27427dcda0 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:25:50 kernel: [6735316.985845] gunicorn: worke[707345]: segfault at 7f273c0b3 ip 00007f279e48d73c sp 00007f27427dc7c0 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:26:04 kernel: [6735330.833628] gunicorn: worke[725106]: segfault at 7f273000c ip 00007f279e4811e0 sp 00007f27447e0da0 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:26:05 kernel: [6735332.078464] gunicorn: worke[724757]: segfault at 7f27302ae ip 00007f279e4811e0 sp 00007f27447df690 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:26:19 kernel: [6735346.235151] gunicorn: worke[725219]: segfault at 7f273c0a0 ip 00007f279e4811e0 sp 00007f2743fdfda0 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:26:36 kernel: [6735363.158105] gunicorn: worke[725412]: segfault at 0 ip 00007f279e48db5f sp 00007f27447e07a0 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:26:43 kernel: [6735370.294866] gunicorn: worke[725521]: segfault at 0 ip 00007f279e48db5f sp 00007f27447e07a0 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:26:45 kernel: [6735371.795516] gunicorn: worke[725587]: segfault at 198 ip 00007f279e48db0f sp 00007f2743fdf7a0 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:27:18 kernel: [6735404.686723] gunicorn: worke[725634]: segfault at 90 ip 00007f279e48d2b4 sp 00007f27447e07f8 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:27:20 kernel: [6735407.315186] gunicorn: worke[725846]: segfault at d0 ip 00007f279e48d2b4 sp 00007f274118a7f8 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:27:22 kernel: [6735409.287804] gunicorn: worke[725893]: segfault at 0 ip 00007f279e48db5f sp 00007f27447e07a0 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:27:32 kernel: [6735418.670781] gunicorn: worke[725286]: segfault at 7f27302dd ip 00007f279e4811e0 sp 00007f27447e0da0 error 4 in libddwaf.so[7f279e43f000+f5000]
Mar  3 03:27:59 kernel: [6735445.806452] gunicorn: worke[726014]: segfault at 2e8 ip 00007f279e4c22b4 sp 00007f27447e07f8 error 4 in libddwaf.so (deleted)[7f279e474000+f5000]
Mar  3 03:28:05 kernel: [6735452.235442] gunicorn: worke[725943]: segfault at 1 ip 00007f279e48d73c sp 00007f27447e07c0 error 4 in libddwaf.so (deleted)[7f279e43f000+f5000]

### What is the result that you expected?

Non crashing (segfaulting) process.

**Comment by juanjux** [comment]
Hopefully fixed by https://github.com/DataDog/dd-trace-py/pull/5260 once merged.

**Comment by lattwood** [comment]
Hopefully fixed by #5267

**Comment by ecarruda** [comment]
@juanjux just updated right now to 1.9.2 and I am doing all tests to close this issue. Looks fixed the random crash dump, i am just going to check all traces being uploaded do Datadog and then close this issue :) 💯 Thank you all 🥇 @christophe-papazian

**Comment by ecarruda** [comment]
Fixed with release `1.9.2` https://github.com/DataDog/dd-trace-py/releases/tag/v1.9.2

**Comment by doker78** [comment]
Still this  version  doing  problems with  SIGSEGV errors  on the kubenrnetes 

may be upgrade to  version  1.11 + will solve the issue  but not  sure  --->
