### ISSUE TITLE
Cannot build 1.9.0 wheel on windows

### ISSUE THREAD

**Issue by aymondebroglie** [DataDog/dd-trace-py#5261]
### Summary of problem

When building the wheel for the 1.9.0 release on windows for conda forge the build fail with the error below 

![image](https://user-images.githubusercontent.com/10114614/222717552-7e63a403-855b-4353-aabf-71d913e9bb92.png)

See [an example run log here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=667252&view=logs&j=171a126d-c574-5c8c-1269-ff3b989e923d&t=1183ba29-a0b5-5324-8463-2a49ace9e213)

### Which version of dd-trace-py are you using?
1.9.0 

### Which libraries and their versions are you using?

The list of the dependencies can be found [in this file](https://github.com/conda-forge/ddtrace-feedstock/pull/158/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9al 

### How can we reproduce your problem?

Feel free to modify the conda forge pr here if needed => https://github.com/conda-forge/ddtrace-feedstock/pull/158
Running the CI should trigger the fail. 
Maybe trying to build the wheel on windows will fail as well

**Comment by aymondebroglie** [comment]
Thanks for the answer. 
I see, according [the python docs](https://docs.python.org/3/library/platform.html) ,`platform.system()` can return an empty string so maybe this is what is happening ? 

We might try to rewrite the check so that we only compile if the OS is detected as linux / osx. 
In any case I am unable to test this as I do not have any windows machine.

**Comment by gnufede** [comment]
@aymondebroglie can you try to build this branch? https://github.com/DataDog/dd-trace-py/tree/gnufede/iast-taint-tracking-compilation-platforms

**Comment by aymondebroglie** [comment]
@gnufede  I have tested with the latest commit from your branch and now it's building properly on windows !
