### ISSUE TITLE
django.cache not categorized as app_type 'cache'?

### ISSUE THREAD

**Issue by bryanhelmig** [DataDog/dd-trace-py#528]
We know it is getting reported just fine:

![](https://cdn.zapier.com/storage/photos/b1ae081f3ca372c8d8fe5cca6d95ec1a.png)

But if you look at the type tab for cache:

![](https://cdn.zapier.com/storage/photos/5d2d774d7a330ef9c2e5494e5fcda169.png)

Funny enough, the `span_type` for the `trace()` looks correct:

https://github.com/DataDog/dd-trace-py/blob/7a3d0f69610a160bfd71cec8caa8366bc6977a8e/ddtrace/contrib/django/cache.py#L55

Seems to be working fine for db:

https://github.com/DataDog/dd-trace-py/blob/7a3d0f69610a160bfd71cec8caa8366bc6977a8e/ddtrace/contrib/django/db.py#L98

**Comment by bryanhelmig** [comment]
@palazzem definitely appreciate your eyes on this!

**Comment by bryanhelmig** [comment]
Looks like this might be a Datadog UI issue -- as if you drill into a trace it understands there are cache calls. Is it because the service has a mixed span types?

![](https://cdn.zapier.com/storage/photos/a95b3de152f30660f278145b1b8430e8.png)

**Comment by bryanhelmig** [comment]
Yeah, a little more digging and the likely fix is to have a custom `service=...` similar to how the database patching works, or at least a way to override (IE: maybe `getattr(backend, '_datadog_service')` or something).

**Comment by palazzem** [comment]
Hello @bryanhelmig ! actually the Django cache is not reported as a standalone service, so you will not find it as "Cache" in the main service list. As you found, the Span will be considered as a cache. 

Maybe a solution could be changing the name via Django settings (ref to ours: https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/django/conf.py#L24-L38), so that by default the cache is not considered a standalone service, but you can change it like you will do for the Database service.

Do you think it could solve your problem?

**Comment by bryanhelmig** [comment]
My understanding is changing the name in the settings will impact all of the services reported, including http?

**Comment by palazzem** [comment]
Hey @bryanhelmig ! just to be clear, currently we don't offer this option in the Django settings. Mine was mostly a thought to see if it could address your problem. It means:
* we add this feature to change the name of the caching layer
* the caching layer is reported as a standalone service (so you'll see a "Cache" service in the service list)
* you can filter and see stats for the Caching layer

`http` services (so Django itself or `requests` or other libraries) will not be impacted by the change.

What do you think?

**Comment by bryanhelmig** [comment]
Yeah, I think those all make sense -- thanks for the clarification!

**Comment by bryanhelmig** [comment]
Awesome! If we can get pymemcached support -- we might prefer that over this! It'll sort of solve both our problems! 😄

**Comment by palazzem** [comment]
Perfect! `pymemcache` support is already merged (https://github.com/DataDog/dd-trace-py/pull/511) and scheduled for release (0.13.0). I'm in touch with @apolloFER to test it in the meantime.
