### ISSUE TITLE
The aws_lambda patch module can't handle callable object event handlers

### ISSUE THREAD

**Issue by michaeldimchuk** [DataDog/dd-trace-py#5284]
### Summary of problem
NOTE: I'll be cross-posting this in [datadog-lambda-python](https://github.com/DataDog/datadog-lambda-python) project because I'm not sure whether this is in the domain of the Lambda layer or this library itself. This could either be solved in this library by checking if the function being wrapped is a callable class instance, or by the Lambda layer passing the `__call__` function reference instead of the callable class.

The issue stems from ddtrace (specifically the `aws_lambda` module) trying to patch the outer most Lambda handler functions, which can be any callable that accepts an event and context arguments, so either a standard function or a callable object, like a class instance that defines `__call__`.

The internal wrapper is passed the class instance itself instead of the `__call__` function however, so as a result, it fails as a class instance isn't going to have a `__code__` property. The `patch_all` the Lambda layer is executing is in a try/catch block and only runs once, so there's no errors being raised, but on every cold start there's a stack trace popping up in the logs. 

Platform: AWS Lambda
Runtime: Python 3.9
Serverless Framework Version: 3.28.0
Serverless Plugin Version: 5.20.0
DataDog Lambda Layer Version: 68
ddtrace Version: 1.9.1

### Which version of dd-trace-py are you using?
ddtrace@1.9.1

### Which version of pip are you using?
pip@21.2.4

### Which libraries and their versions are you using?
Output of `poetry show --no-dev`, excluded some internal libraries irrelevant to this and added `chalice` since that's packaged manually using their internal packaging mechanism.

attrs@21.4.0
aws-lambda-context@1.1.0
boto3@1.24.57
botocore@1.27.57
bytecode@0.14.0
cattrs@22.2.0
certifi@2022.6.15
charset-normalizer@2.1.1
ddsketch@2.0.4
ddtrace@1.9.1
elasticsearch@7.9.1
elasticsearch-dsl@7.3.0
envier@0.4.0
exceptiongroup@1.1.0
idna@3.3
jmespath@0.10.0
jsonschema@3.2.0
marshmallow@3.15.0
packaging@23.0
protobuf@4.22.0
pyrsistent@0.18.1
python-dateutil@2.8.2
python-json-logger@2.0.4
requests@2.28.1
requests-aws4auth@1.0
s3transfer@0.6.0
simplejson@3.17.2
six@1.16.0
tenacity@8.2.2
typing-extensions@4.3.0
urllib3@1.26.12
xmltodict@0.13.0
chalice@1.26.6

### How can we reproduce your problem?
Deploy a lambda function where the event handler is a callable class instance, whether through the [chalice](https://github.com/aws/chalice) framework or something like this:
```
# app.py
from typing import Any

class LambdaHandler:
    def __call__(self, event: dict[str, Any], context: Any) -> dict[str, Any]:
        return {"hello": "world"}

app = LambdaHandler()
```
With `app.app` being the handler of the lambda function.

### What is the result that you get?
The following stack trace is thrown on every cold start as `patch_all` fails:
```
Traceback (most recent call last):
	File "/opt/python/lib/python3.9/site-packages/datadog_lambda/wrapper.py", line 177, in __init__
		patch_all()
	File "/opt/python/lib/python3.9/site-packages/datadog_lambda/patch.py", line 36, in patch_all
		patch_all_dd()
	File "/var/task/ddtrace/_monkey.py", line 190, in patch_all
		patch(raise_errors=False, **modules)
	File "/var/task/ddtrace/_monkey.py", line 230, in patch
		when_imported(module)(_on_import_factory(contrib, raise_errors=False))
	File "/var/task/ddtrace/vendor/wrapt/importer.py", line 284, in register
		register_post_import_hook(hook, name)
	File "/var/task/ddtrace/vendor/wrapt/decorators.py", line 470, in _synchronized
		return wrapped(*args, **kwargs)
	File "/var/task/ddtrace/vendor/wrapt/importer.py", line 82, in register_post_import_hook
		hook(module)
	File "/var/task/ddtrace/_monkey.py", line 155, in on_import
		imported_module.patch()
	File "/var/task/ddtrace/contrib/aws_lambda/patch.py", line 156, in patch
		wrap(handler, wrapper)
	File "/var/task/ddtrace/internal/wrapping.py", line 428, in wrap
		f.__code__,
	AttributeError: 'EventSourceHandler' object has no attribute '__code__'
```

### What is the result that you expected?
This operation should not fail, and either [ddtrace.internal.wrapping.wrap](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/internal/wrapping.py#L417) should account for callable classes, or `datadog_lambda` should be figuring out that the handler is a callable class instance and passing the `__call__` function reference instead of the class instance.

**Comment by duncanista** [comment]
Hello @michaeldimchuk,

Thank you for raising this issue. I will work on multiple POCs to reproduce this and will come with a bug fix.
