### ISSUE TITLE
dd-lib-python-init break of change on 1.19 version

### ISSUE THREAD

**Issue by knitehias** [DataDog/dd-trace-py#5291]
### Summary of problem
dd-lib-python-init 1.16 version could be used on non-root-user kubernetes admission controller apm injector
but the 1.19 version has to be run under root user and it will install and build python c libs on the air and set the bin under /.local/bin
this is impossible or too much break of change 
### Which version of dd-trace-py are you using?
1.16.3
### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
  
</details>

### How can we reproduce your problem?
create a target app running as non-root user in a kubernetes env, admission controller apm inject it
### What is the result that you get?
installation will require /.local/xx/xx/xx/xx which is impossible for non-root user
### What is the result that you expected?
like 1.16.3 use default user to run it and install it and use the tracer

**Comment by mabdinur** [comment]
Hi @knitehias,

From: https://github.com/DataDog/dd-trace-py/pull/4490
 - "Containers using the root user can be blocked in Kubernetes which makes our lib injection image incompatible with certain Kubernetes configurations. The solution is to simply add and use a non-root user in the image". 

Just to confirm you tried upgrading from ddtrace v1.6.3 to ddtrace v.1.9.3. While v1.6.3 worked as expected, with v1.9.3 you are unable to use library injection with a non-root-user kubernetes admission controller. From your assessment the PR above introduced a breaking change and you would like to option to use the previous behavior. Is this correct?

**Comment by knitehias** [comment]
> Hi @knitehias,
> 
> From: #4490
> 
> * "Containers using the root user can be blocked in Kubernetes which makes our lib injection image incompatible with certain Kubernetes configurations. The solution is to simply add and use a non-root user in the image".
> 
> Just to confirm you tried upgrading from ddtrace v1.6.3 to ddtrace v.1.9.3. While v1.6.3 worked as expected, with v1.9.3 you are unable to use library injection with a non-root-user kubernetes admission controller. From your assessment the PR above introduced a breaking change and you would like to option to use the previous behavior. Is this correct?

Yeah, in 1.6.3 the inject lib will figure it is non root so it will use default user access ( I got it from the logging instead of source code though), we still want to use newer version but as non root :)

**Comment by Kyle-Verhoog** [comment]
@knitehias 🤔 can you share the logs you mentioned and/or provide a basic repro of the issue? 1.9.3 should not be running as the root (the change introduced in https://github.com/DataDog/dd-trace-py/pull/4490)

**Comment by Kyle-Verhoog** [comment]
Going to close this as we haven't heard back, please let us know if your issue is still present @knitehias and we can re-open and investigate further 🙂

**Comment by knitehias** [comment]
> Going to close this as we haven't heard back, please let us know if your issue is still present @knitehias and we can re-open and investigate further 🙂



Mar 3, 2023 @ 16:52:59.454 | datadog autoinstrumentation: successfully installed python package
-- | --

  | Mar 3, 2023 @ 16:52:59.454 | datadog autoinstrumentation: installing python package

  | Mar 3, 2023 @ 16:52:58.866 | You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.

  | Mar 3, 2023 @ 16:52:58.866 | WARNING: You are using pip version 22.0.4; however, version 23.0.1 is available.

  | Mar 3, 2023 @ 16:52:58.639 | Successfully installed attrs-22.2.0 bytecode-0.14.0 cattrs-22.2.0 ddsketch-2.0.4 ddtrace-1.9.0 envier-0.4.0 exceptiongroup-1.1.0 importlib-resources-5.12.0 jsonschema-4.17.3 packaging-23.0 pkgutil-resolve-name-1.3.10 protobuf-4.22.0 pyrsistent-0.19.3 six-1.16.0 tenacity-8.2.2 typing-extensions-4.5.0 xmltodict-0.13.0 zipp-3.15.0

  | Mar 3, 2023 @ 16:52:55.977 | Installing collected packages: zipp, xmltodict, typing-extensions, tenacity, six, pyrsistent, protobuf, pkgutil-resolve-name, packaging, exceptiongroup, envier, attrs, importlib-resources, ddsketch, cattrs, bytecode, jsonschema, ddtrace

  | Mar 3, 2023 @ 16:52:55.374 | Downloading zipp-3.15.0-py3-none-any.whl (6.8 kB)

  | Mar 3, 2023 @ 16:52:55.368 | Collecting zipp>=3.1.0

  | Mar 3, 2023 @ 16:52:55.177 | Downloading importlib_resources-5.12.0-py3-none-any.whl (36 kB)

  | Mar 3, 2023 @ 16:52:55.171 | Collecting importlib-resources>=1.4.0

  | Mar 3, 2023 @ 16:52:54.987 | Downloading pkgutil_resolve_name-1.3.10-py3-none-any.whl (4.7 kB)

  | Mar 3, 2023 @ 16:52:54.982 | Collecting pkgutil-resolve-name>=1.3.10

  | Mar 3, 2023 @ 16:52:54.952 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 KB 111.0 MB/s eta 0:00:00

  | Mar 3, 2023 @ 16:52:54.947 | Downloading pyrsistent-0.19.3-py3-none-any.whl (57 kB)

  | Mar 3, 2023 @ 16:52:54.942 | Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0

  | Mar 3, 2023 @ 16:52:54.666 | Downloading exceptiongroup-1.1.0-py3-none-any.whl (14 kB)

  | Mar 3, 2023 @ 16:52:54.660 | Collecting exceptiongroup

  | Mar 3, 2023 @ 16:52:54.437 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.4/90.4 KB 143.3 MB/s eta 0:00:00

  | Mar 3, 2023 @ 16:52:54.382 | Downloading jsonschema-4.17.3-py3-none-any.whl (90 kB)

  | Mar 3, 2023 @ 16:52:54.377 | Collecting jsonschema

  | Mar 3, 2023 @ 16:52:54.254 | Downloading cattrs-22.2.0-py3-none-any.whl (35 kB)

  | Mar 3, 2023 @ 16:52:54.248 | Collecting cattrs

  | Mar 3, 2023 @ 16:52:54.177 | Downloading ddsketch-2.0.4-py3-none-any.whl (18 kB)

  | Mar 3, 2023 @ 16:52:54.173 | Collecting ddsketch>=2.0.1

  | Mar 3, 2023 @ 16:52:54.141 | Downloading envier-0.4.0-py3-none-any.whl (10 kB)

  | Mar 3, 2023 @ 16:52:54.136 | Collecting envier

  | Mar 3, 2023 @ 16:52:54.067 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 KB 125.6 MB/s eta 0:00:00

  | Mar 3, 2023 @ 16:52:54.062 | Downloading attrs-22.2.0-py3-none-any.whl (60 kB)

  | Mar 3, 2023 @ 16:52:54.057 | Collecting attrs>=20

  | Mar 3, 2023 @ 16:52:53.973 | Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)

  | Mar 3, 2023 @ 16:52:53.963 | Collecting six>=1.12.0

  | Mar 3, 2023 @ 16:52:53.902 | Downloading bytecode-0.14.0-py3-none-any.whl (37 kB)

  | Mar 3, 2023 @ 16:52:53.897 | Collecting bytecode

  | Mar 3, 2023 @ 16:52:53.849 | Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)

  | Mar 3, 2023 @ 16:52:53.844 | Collecting typing-extensions

  | Mar 3, 2023 @ 16:52:53.758 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.4/302.4 KB 147.3 MB/s eta 0:00:00

  | Mar 3, 2023 @ 16:52:53.752 | Downloading protobuf-4.22.0-cp37-abi3-manylinux2014_x86_64.whl (302 kB)

  | Mar 3, 2023 @ 16:52:53.747 | Collecting protobuf>=3

  | Mar 3, 2023 @ 16:52:52.500 | Downloading xmltodict-0.13.0-py2.py3-none-any.whl (10.0 kB)

  | Mar 3, 2023 @ 16:52:52.494 | Collecting xmltodict>=0.12

  | Mar 3, 2023 @ 16:52:52.455 | Downloading tenacity-8.2.2-py3-none-any.whl (24 kB)

  | Mar 3, 2023 @ 16:52:52.450 | Collecting tenacity>=5

  | Mar 3, 2023 @ 16:52:52.352 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.7/42.7 KB 115.8 MB/s eta 0:00:00

  | Mar 3, 2023 @ 16:52:52.347 | Downloading packaging-23.0-py3-none-any.whl (42 kB)

  | Mar 3, 2023 @ 16:52:52.342 | Collecting packaging>=17.1

  | Mar 3, 2023 @ 16:52:52.076 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 59.7 MB/s eta 0:00:00

  | Mar 3, 2023 @ 16:52:51.991 | Downloading ddtrace-1.9.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.8 MB)

  | Mar 3, 2023 @ 16:52:51.963 | Collecting ddtrace

  | Mar 3, 2023 @ 16:52:44.856 | Defaulting to user installation because normal site-packages is not writeable

  | Mar 3, 2023 @ 16:52:44.853 | WARNING: The directory '/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.

  | Mar 3, 2023 @ 16:26:09.857 | ModuleNotFoundError: No module named 'ddtrace'

  | Mar 3, 2023 @ 16:26:09.857 | Error in sitecustomize; set PYTHONVERBOSE for traceback:

  | Mar 3, 2023 @ 16:26:01.859 | You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.

  | Mar 3, 2023 @ 16:26:01.859 | WARNING: You are using pip version 22.0.4; however, version 23.0.1 is available.

  | Mar 3, 2023 @ 16:26:01.657 | ERROR: Could not install packages due to an OSError: [Errno 30] Read-only file system: '/.local'

  | Mar 3, 2023 @ 16:26:01.656 | Installing collected packages: xmltodict, tenacity, pyrsistent, pkgutil-resolve-name, packaging, exceptiongroup, envier, ddsketch, bytecode, attrs, jsonschema, cattrs, ddtrace

  | Mar 3, 2023 @ 16:26:00.986 | Requirement already satisfied: zipp>=3.1.0 in /app/src/expense_check/docker_image.binary.runfiles/ec_pip_deps_pypi__zipp (from importlib-resources>=1.4.0->jsonschema->ddtrace) (3.10.0)

  | Mar 3, 2023 @ 16:26:00.968 | Requirement already satisfied: importlib-resources>=1.4.0 in /app/src/expense_check/docker_image.binary.runfiles/ec_pip_deps_pypi__importlib_resources (from jsonschema->ddtrace) (5.10.0)

  | Mar 3, 2023 @ 16:26:00.965 | Downloading pkgutil_resolve_name-1.3.10-py3-none-any.whl (4.7 kB)

  | Mar 3, 2023 @ 16:26:00.962 | Collecting pkgutil-resolve-name>=1.3.10

  | Mar 3, 2023 @ 16:26:00.880 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 KB 240.0 MB/s eta 0:00:00

  | Mar 3, 2023 @ 16:26:00.877 | Downloading pyrsistent-0.19.3-py3-none-any.whl (57 kB)

  | Mar 3, 2023 @ 16:26:00.864 | Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0

  | Mar 3, 2023 @ 16:26:00.662 | Downloading exceptiongroup-1.1.0-py3-none-any.whl (14 kB)

  | Mar 3, 2023 @ 16:26:00.656 | Collecting exceptiongroup

  | Mar 3, 2023 @ 16:26:00.463 | Requirement already satisfied: typing-extensions in /app/src/expense_check/docker_image.binary.runfiles/ec_pip_deps_pypi__typing_extensions (from ddtrace) (4.4.0)

  | Mar 3, 2023 @ 16:26:00.462 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.7/42.7 KB 236.6 MB/s eta 0:00:00

  | Mar 3, 2023 @ 16:26:00.459 | Downloading packaging-23.0-py3-none-any.whl (42 kB)

  | Mar 3, 2023 @ 16:26:00.455 | Collecting packaging>=17.1

  | Mar 3, 2023 @ 16:26:00.296 | Downloading xmltodict-0.13.0-py2.py3-none-any.whl (10.0 kB)

  | Mar 3, 2023 @ 16:26:00.292 | Collecting xmltodict>=0.12

  | Mar 3, 2023 @ 16:26:00.197 | Downloading cattrs-22.2.0-py3-none-any.whl (35 kB)

  | Mar 3, 2023 @ 16:26:00.194 | Collecting cattrs

  | Mar 3, 2023 @ 16:26:00.092 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.4/90.4 KB 277.1 MB/s eta 0:00:00

  | Mar 3, 2023 @ 16:26:00.089 | Downloading jsonschema-4.17.3-py3-none-any.whl (90 kB)

  | Mar 3, 2023 @ 16:26:00.085 | Collecting jsonschema

  | Mar 3, 2023 @ 16:25:59.897 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 KB 249.6 MB/s eta 0:00:00

  | Mar 3, 2023 @ 16:25:59.895 | Downloading attrs-22.2.0-py3-none-any.whl (60 kB)

  | Mar 3, 2023 @ 16:25:59.891 | Collecting attrs>=20

  | Mar 3, 2023 @ 16:25:59.785 | Requirement already satisfied: six>=1.12.0 in /app/src/expense_check/docker_image.binary.runfiles/ec_pip_deps_pypi__six (from ddtrace) (1.16.0)

  | Mar 3, 2023 @ 16:25:59.783 | Downloading bytecode-0.14.0-py3-none-any.whl (37 kB)

  | Mar 3, 2023 @ 16:25:59.780 | Collecting bytecode

  | Mar 3, 2023 @ 16:25:59.683 | Downloading envier-0.4.0-py3-none-any.whl (10 kB)

  | Mar 3, 2023 @ 16:25:59.679 | Collecting envier

  | Mar 3, 2023 @ 16:25:59.588 | Downloading tenacity-8.2.2-py3-none-any.whl (24 kB)

  | Mar 3, 2023 @ 16:25:59.584 | Collecting tenacity>=5

  | Mar 3, 2023 @ 16:25:59.478 | Downloading ddsketch-2.0.4-py3-none-any.whl (18 kB)

  | Mar 3, 2023 @ 16:25:59.474 | Collecting ddsketch>=2.0.1

  | Mar 3, 2023 @ 16:25:59.381 | Requirement already satisfied: protobuf>=3 in /app/src/expense_check/docker_image.binary.runfiles/ec_pip_deps_pypi__protobuf (from ddtrace) (3.19.6)

  | Mar 3, 2023 @ 16:25:59.302 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 215.4 MB/s eta 0:00:00

  | Mar 3, 2023 @ 16:25:59.277 | Downloading ddtrace-1.9.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.8 MB)

  | Mar 3, 2023 @ 16:25:59.258 | Collecting ddtrace

**Comment by Kyle-Verhoog** [comment]
@knitehias thanks for getting back to us!

Hmm I'm not seeing anything in the logs that indicates that the install failed. Did the logs get cut off in your reply?

**Comment by knitehias** [comment]
> | Mar 3, 2023 @ 16:26:01.657 | ERROR: Could not install packages due to an OSError: [Errno 30] Read-only file system: '/.local'

Sorry that I've been sick.

**Comment by knitehias** [comment]
> @knitehias thanks for getting back to us!
> 
> Hmm I'm not seeing anything in the logs that indicates that the install failed. Did the logs get cut off in your reply?
I am sorry that I've been sick and this is the error: 
  | Mar 3, 2023 @ 16:26:01.657 | ERROR: Could not install packages due to an OSError: [Errno 30] Read-only file system: '/.local'

**Comment by asfaltboy** [comment]
We are having the same issue as described by original poster, and still in version `1.13.3`.

I believe it's because we use `securityContext.readOnlyRootFilesystem: true` ([reference](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/), tl;dr it prevents writes to the container's file system on mount).

I'm wondering if there's a way to add ddtrace packages to path without needing to call pip in a read-only system. I noticed that dd-trace-js does this by copying `node_modules`, equiv to python libs, to the mount path ([source](https://github.com/DataDog/dd-trace-js/blob/d638b4b7bc0eaee1be0044c181619378a41e069c/lib-injection/copy-lib.sh#L2)). This path is later added to the requires config key of `NODE_OPTIONS` in the main container ([source](https://github.com/DataDog/datadog-agent/blob/28f3540a85018c960d369b15eb3adcaf1a32b967/pkg/clusteragent/admission/mutate/auto_instrumentation.go#L37-L38)).

How about adding installing the wheels in `/datadog-lib/ddtrace_pkgs/` into `/datadog-lib/` in the init container, this path is then to the `PYTHONPATH` and allows the packages to be used? Would that not work?
