### ISSUE TITLE
WSGI Middleware fails to call `close()` on iterables

### ISSUE THREAD

**Issue by petersalas** [DataDog/dd-trace-py#5325]
The WSGI middleware attempts to [call close on `iter(x)` rather than `x`](https://github.com/DataDog/dd-trace-py/blob/caca9d3b875d1a6d4d3708d948477d0df31572a9/ddtrace/contrib/wsgi/wsgi.py#L195-L217). This works correctly if the iterable happens to be its own iterator  but not generally. Per the [WSGI spec](https://peps.python.org/pep-0333/#specification-details) close should be attempted on the _iterable_ rather than its iterator.

In Django applications this can prevent the [`request_finished` signal](https://docs.djangoproject.com/en/4.1/ref/signals/#django.core.signals.request_finished) from being sent and cause database connection leaks.

I was able to work around this by adding middleware that introduces a wrapper iterable that ensures that `close()` on its iterator is forwarded to the original iterable.

**Comment by emmettbutler** [comment]
Though #5858 is mentioned here, it looks like that change doesn't resolve this issue.

**Comment by emmettbutler** [comment]
@petersalas does https://github.com/DataDog/dd-trace-py/pull/6692 fix the issue you're describing? Do you have any suggestions about how we might replicate the failure mode you mentioned?

**Comment by petersalas** [comment]
Looking at that fix, I think it would only fix it in certain scenarios (namely: iterables that are also iterators, but not their _own_ iterator). Here's the workaround I used:

```python
class IterableCloseForwarder:
    """Wraps an iterable to ensure that `iter(self).close()` will forward the
    `close()` call to the wrapped iterable.

    Works around a bug in ddtrace-py where it assumes that iter(x).close() is
    equivalent to x.close().

    https://github.com/DataDog/dd-trace-py/blob/975266967de6ca3d1a753f843cd3ea5b6ce56f45/ddtrace/contrib/wsgi/wsgi.py#L195-L217
    """

    def __init__(self, iterable):
        self._iterable = iterable
        self._iterator = iter(iterable)

    def __next__(self):
        return next(self._iterator)

    def __iter__(self):
        return self

    def close(self):
        if getattr(self._iterable, "close", None):
            self._iterable.close()

    @classmethod
    def middleware(cls, app):
        return lambda *args, **kwargs: cls(app(*args, **kwargs))
```

and then I ensured that `IterableCloseForwarder.middleware(app)` was the WSGI app passed to `ddtrace.contrib.wsgi.DDWSGIMiddleware`.

Looking briefly at the code it looks like `_TracedIterable` expects an _iterator_. My inclination would be to do something like this instead: https://github.com/DataDog/dd-trace-py/compare/1.x...petersalas:dd-trace-py:fix-iterable?expand=1

Does that make sense? If I get some time I can try to put together a minimal django sample that repros the issue.

**Comment by petersalas** [comment]
@emmettbutler I created a minimal repro with Django here: https://gist.github.com/petersalas/aa1ce634e2cd83fdf2dc22431c3a1b9b
