### ISSUE TITLE
Gunicorn + gevent error

### ISSUE THREAD

**Issue by johnnymetz** [DataDog/dd-trace-py#5337]
### Summary of problem

Seeing a cryptic error message in the logs when using gunicorn with gevent. Not sure what it means or if it's causing any issues in Datadog.

### Which version of dd-trace-py are you using?

1.9.3

### Which version of pip are you using?

23.0.1

### Which libraries and their versions are you using?

Python 3.11.2

<details>
  <summary>`pip freeze`</summary>
  amqp==5.1.1
arrow==1.2.3
asgiref==3.6.0
astroid==2.15.0
async-timeout==4.0.2
attrs==22.2.0
bandit==1.7.5
beautifulsoup4==4.11.2
billiard==3.6.4.0
blinker==1.5
boto3==1.26.90
botocore==1.29.90
Brotli==1.0.9
bytecode==0.14.0
cattrs==22.2.0
celery==5.2.7
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==3.1.0
chevron==0.14.0
click==8.1.3
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.2.0
ConfigArgParse==1.5.3
coverage==7.2.1
cryptography==39.0.2
cytoolz==0.12.1
ddsketch==2.0.4
ddtrace==1.9.3
deepdiff==6.2.3
deepmerge==1.1.0
defusedxml==0.7.1
dill==0.3.6
dj-database-url==1.2.0
Django==4.1.7
django-colorfield==0.8.0
django-cors-headers==3.14.0
django-cprofile-middleware==1.0.5
django-csp==3.7
django-db-geventpool==4.0.1
django-environ==0.10.0
django-extensions==3.2.1
django-filter==22.1
django-redis==5.2.0
django-sendgrid-v5==1.2.2
django-sesame==3.1
django-storages==1.13.2
django-timezone-field==5.0
django-waffle==3.0.0
django-webpack-loader==1.8.1
django-zen-queries==2.1.0
django_debug_toolbar==3.8.1
djangorestframework==3.14.0
djangorestframework-csv==2.1.1
djangorestframework-dataclasses==1.2.0
djangorestframework-link-header-pagination==0.1.1
envier==0.4.0
et-xmlfile==1.1.0
execnet==1.9.0
factory-boy==3.2.1
Faker==17.6.0
Flask==2.2.3
Flask-BasicAuth==0.2.0
Flask-Cors==3.0.10
fqdn==1.5.1
genson==1.2.2
gevent==22.10.2
geventhttpclient==2.0.8
gitdb==4.0.10
GitPython==3.1.31
greenlet==2.0.2
gunicorn==20.1.0
idna==3.4
iniconfig==2.0.0
isoduration==20.11.0
isort==5.12.0
itsdangerous==2.1.2
Jinja2==3.1.2
jmespath==1.0.1
jsonpointer==2.3
jsonschema==4.17.3
kombu==5.2.4
lazy-object-proxy==1.9.0
locust==2.15.0
markdown-it-py==2.2.0
MarkupSafe==2.1.2
mccabe==0.7.0
mdurl==0.1.2
mixpanel==4.9.0
moto==4.1.4
msgpack==1.0.4
networkx==3.0
newrelic==8.7.0
nplusone==1.0.0
oauthlib==3.2.2
openpyxl==3.1.2
ordered-set==4.1.0
orjson==3.8.7
packaging==23.0
pbr==5.11.1
Pillow==9.4.0
platformdirs==3.1.0
pluggy==1.0.0
prompt-toolkit==3.0.38
protobuf==4.22.1
psutil==5.9.4
psycogreen==1.0.2
psycopg2==2.9.5
py-mini-racer==0.6.0
pycparser==2.21
Pygments==2.14.0
PyJWT==2.6.0
pylint==2.17.0
pylint-django==2.5.3
pylint-plugin-utils==0.7
pyrsistent==0.19.3
pytest==7.2.2
pytest-cov==4.0.0
pytest-django==4.5.2
pytest-socket==0.6.0
pytest-xdist==3.2.1
python-dateutil==2.8.2
python-http-client==3.3.7
python3-openid==3.2.0
pytz==2022.1
PyYAML==6.0
pyzmq==25.0.0
redis==4.5.1
requests==2.28.2
requests-oauthlib==1.3.1
responses==0.23.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.3.2
rollbar==0.16.3
roundrobin==0.0.4
s3transfer==0.6.0
sendgrid==6.9.6
six==1.16.0
smmap==5.0.0
social-auth-app-django==5.0.0
social-auth-core==4.3.0
soupsieve==2.4
sq-native==1.1.2.0.0
sqlparse==0.4.3
sqreen==1.28.0b1
starkbank-ecdsa==2.2.0
stevedore==5.0.0
tenacity==8.2.2
time-machine==2.9.0
toml==0.10.2
tomlkit==0.11.6
toolz==0.12.0
types-PyYAML==6.0.12.8
types-toml==0.10.8.5
typing_extensions==4.5.0
tzdata==2022.7
unicodecsv==0.14.1
uri-template==1.2.0
uritemplate==4.1.1
urllib3==1.26.14
vine==5.0.0
watchdog==2.3.1
wcwidth==0.2.6
webcolors==1.12
Werkzeug==2.2.3
whitenoise==6.4.0
wrapt==1.15.0
xmltodict==0.13.0
zope.event==4.6
zope.interface==5.5.2
</details>

### How can we reproduce your problem?

```
$ DD_SERVICE=my-app ddtrace-run gunicorn remix.wsgi --worker-class gevent
```

Wait about a minute to see the error message. May need to click around the web app a bit to generate data for datadog to send off.

### What is the result that you get?

The application runs fine and everything seems to work but I'm seeing this error in the logs after about a minute.

```
Exception in thread ddtrace.internal.telemetry.writer:TelemetryWriter:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Users/johnnymetz/Repos/pixiebrix-app/venv/lib/python3.11/site-packages/ddtrace/internal/periodic.py", line 56, in run
    self._target()
  File "/Users/johnnymetz/Repos/pixiebrix-app/venv/lib/python3.11/site-packages/ddtrace/internal/telemetry/writer.py", line 134, in periodic
    self._app_integrations_changed_event(integrations)
  File "/Users/johnnymetz/Repos/pixiebrix-app/venv/lib/python3.11/site-packages/ddtrace/internal/telemetry/writer.py", line 242, in _app_integrations_changed_event
    self.add_event(payload, "app-integrations-change")
  File "/Users/johnnymetz/Repos/pixiebrix-app/venv/lib/python3.11/site-packages/ddtrace/internal/telemetry/writer.py", line 176, in add_event
    "host": get_host_info(),
            ^^^^^^^^^^^^^^^
  File "/Users/johnnymetz/Repos/pixiebrix-app/venv/lib/python3.11/site-packages/ddtrace/internal/telemetry/data.py", line 115, in get_host_info
    "os": platform.platform(aliased=True, terse=True),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/platform.py", line 1212, in platform
    system, node, release, version, machine, processor = uname()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/platform.py", line 799, in __iter__
    (self.processor,)
     ^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/platform.py", line 794, in processor
    return _unknown_as_blank(_Processor.get())
                             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/platform.py", line 739, in get
    return func() or ''
           ^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/platform.py", line 762, in from_subprocess
    return subprocess.check_output(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnnymetz/Repos/pixiebrix-app/venv/lib/python3.11/site-packages/gevent/subprocess.py", line 413, in check_output
    with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnnymetz/Repos/pixiebrix-app/venv/lib/python3.11/site-packages/gevent/subprocess.py", line 842, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/johnnymetz/Repos/pixiebrix-app/venv/lib/python3.11/site-packages/gevent/subprocess.py", line 1675, in _execute_child
    self.pid = fork_and_watch(self._on_child, self._loop, True, fork)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnnymetz/Repos/pixiebrix-app/venv/lib/python3.11/site-packages/gevent/os.py", line 434, in fork_and_watch
    _watch_child(pid, callback, loop, ref)
  File "/Users/johnnymetz/Repos/pixiebrix-app/venv/lib/python3.11/site-packages/gevent/os.py", line 402, in _watch_child
    watcher = loop.child(pid, ref=ref)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/gevent/libev/corecext.pyx", line 716, in gevent.libev.corecext.loop.child
  File "src/gevent/libev/corecext.pyx", line 1257, in gevent.libev.corecext.child.__cinit__
TypeError: child watchers are only available on the default loop
```

Note, the application continues to run without any visible problems.

### What is the result that you expected?

No error message.

**Comment by emmettbutler** [comment]
@johnnymetz thank you for opening this issue! 1.9.3 made some significant changes to how the library handles greenlets, and I suspect this is a side effect of those changes.

I wonder if you continue to see the error when this code runs in an environment with the `DD_INSTRUMENTATION_TELEMETRY_ENABLED=0` variable set.

**Comment by P403n1x87** [comment]
The call to `platform.platform` performed by the telemetry worker triggers a subprocess. Internally, the `platform` module loads the `subprocess` module lazily on function call, which means it ends up getting a reference to the module after it's been patched by `gevent`
https://github.com/python/cpython/blob/84e20c689a8b3b6cebfd50d044c62af5d0e7dec1/Lib/platform.py#L819-L822

Since this exception happens in the telemetry worker, we can expect that the only affected part is the telemetry product itself, with no harm done to the traced application.

I can see a couple of ways to get rid of this issue:
- Find an alternative to `platform.platform`
- If we know we are going to call it, call it once on startup and cache the result.

**Comment by johnnymetz** [comment]
@emmettbutler just confirmed setting `DD_INSTRUMENTATION_TELEMETRY_ENABLED=0` generates NO error

**Comment by johnnymetz** [comment]
@emmettbutler what are the effects of this bug? Our app is running fine so just wondering what we're missing out on until this is fixed. Looks like traces will not be sent to the Datadog platform?

**Comment by twschiller** [comment]
>  Looks like traces will not be sent to the Datadog platform?

This other issue/feature request seems to indicate the tracing is not supported with gunicorn/gevent: https://github.com/DataDog/dd-trace-py/issues/4883

**Comment by P403n1x87** [comment]
> > Looks like traces will not be sent to the Datadog platform?
> 
> This other issue/feature request seems to indicate the tracing is not supported with gunicorn/gevent: #4883

@twschiller the issue you referenced is about the tracing of the gunicorn server itself. Tracing in general is supposed to work with gunicorn + gevent. Please let us know if this is not the case for you 🙏

**Comment by emmettbutler** [comment]
@johnnymetz that environment variable turns off the tracking that powers the [Observability Pipelines](https://www.datadoghq.com/blog/datadog-observability-pipelines/) product. If you use that product, you'll notice it not receiving new data from this app. If not, you're not missing out on anything with that flag set.

**Comment by emmettbutler** [comment]
@johnnymetz If you're able, it would be helpful if you tried to reproduce this issue using the code from #5378 and see if it resolves this.

**Comment by johnnymetz** [comment]
@emmettbutler just installed it via:

```
pip install git+https://github.com/datadog/dd-trace-py
```

Confirmed I'm not seeing the error anymore. Thanks for the help!
