### ISSUE TITLE
Possible random spans dropping

### ISSUE THREAD

**Issue by GeyseR** [DataDog/dd-trace-py#543]
Some of our background tasks generate a lot of different spans (DB, Cache, etc), sometimes more than 10000.
ddtrace has in its internal such code https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/writer.py#L233-L235 and it looks like all spans are written to the send queue in one go. Does this mean that:
a) we will see no more than 1000 spans for each trace?
b) it's possible that root span will be dropped from the queue and won't be reported at all?

**Comment by GeyseR** [comment]
Hi @Kyle-Verhoog!

Thanks for looking into this problem. 

Yea, we already faced this problem with high memory consumption by DD tracer in several of our products, so we implemented a workaround for finishing all spans tree before it collected more than 1000 spans

Still waiting for implementing https://github.com/DataDog/dd-trace-py/issues/460

**Comment by brettlangdon** [comment]
@GeyseR the issue of large trace payloads should be resolved as of `0.27.0`.

I am going to close this issue for now, please feel free to re-open if you are still having issues.
