### ISSUE TITLE
Cannot disable certain integrations

### ISSUE THREAD

**Issue by P403n1x87** [DataDog/dd-trace-py#5458]
### Summary of problem

It doesn't seem to be possible to disable certain integrations. For example `DD_TRACE_DJANGO_ENABLED=0` has no effect when the tracer is enabled and Django is patched regardless. The issue is quite likely related to the use of this `dict`

https://github.com/DataDog/dd-trace-py/blob/4d641c4f0f268ce21b14d73fc3d1ac6a84b16838/ddtrace/bootstrap/sitecustomize.py#L74-L81

**Comment by mabdinur** [comment]
Hey @P403n1x87, 

I believe these integrations can be disabled using [DD_PATCH_MODULES](https://github.com/DataDog/dd-trace-py/blob/c37f9303f4e08145a88f31eac036c9098e0ff844/ddtrace/bootstrap/sitecustomize.py#L85). Ex: ``DD_PATCH_MODULES= bottle:false, django:false,...``. This behavior is confusing and poorly documented.  Are there any drawbacks of removing  ``EXTRA_PATCHED_MODULES``?

**Comment by P403n1x87** [comment]
I think this is a question for @Kyle-Verhoog or @brettlangdon to answer. The documentation even has a Django example for `DD_TRACE_<INTEGRATION>_ENABLED`. My take on this is either that needs to be clarified, or the logic around `EXTRA_PATCHED_MODULES` fixed.
