### ISSUE TITLE
Inconsistent documentation about HTTPPropagator usage

### ISSUE THREAD

**Issue by yatishb** [DataDog/dd-trace-py#546]
The docs on injecting the context attributes for propagation of HTTP requests states that the `inject()` can be called on the `HTTPPropagator` class as follows:

```python
def parent_call():
  with tracer.trace("parent_span") as span:
    headers = {}
    HTTPPropagator.inject(span.context, headers)
    url = "<some RPC endpoint>"
    r = requests.get(url, headers=headers)
```

When doing this, I get an error that the method `HTTPPropagator.inject()` requires an instance to be passed. Looking at the [code](https://github.com/DataDog/dd-trace-py/blob/v0.13.0/ddtrace/propagation/http.py#L32), `inject()` is not a classmethod or a staticmethod, and the example should be updated to:

```python
def parent_call():
  with tracer.trace("parent_span") as span:
    headers = {}
    propagator = HTTPPropagator()
    propagator.inject(span.context, headers)
    url = "<some RPC endpoint>"
    r = requests.get(url, headers=headers)
```

The same follows for the `extract()` method as well.

**Comment by Kyle-Verhoog** [comment]
@yatishb good catch. We'll add this to our documentation fixes we're working on, thanks!
