### ISSUE TITLE
Django patch breaks cache 

### ISSUE THREAD

**Issue by nicootto** [DataDog/dd-trace-py#5460]
### Summary of problem
Django cache patch is evaluating the cache result, which might not be valid.

https://github.com/DataDog/dd-trace-py/blob/1.11/ddtrace/contrib/django/patch.py#L182

That line is calling `bool` on `result`, which e.g. is not defined for a pandas DataFrame

### Which version of dd-trace-py are you using?
1.11

### Which version of pip are you using?
pip 22.0.4

### Which libraries and their versions are you using?
django 3.2.18

<details>
  <summary>`pip freeze`</summary>
	```
	asgiref==3.6.0
	attrs==22.2.0
	bytecode==0.14.0
	cattrs==22.2.0
	ddsketch==2.0.4
	ddtrace==1.11.0
	Deprecated==1.2.13
	Django==4.2
	envier==0.4.0
	importlib-metadata==6.0.1
	jsonschema==4.17.3
	numpy==1.24.2
	opentelemetry-api==1.17.0
	packaging==23.0
	pandas==2.0.0
	protobuf==4.22.1
	pyrsistent==0.19.3
	python-dateutil==2.8.2
	pytz==2023.3
	six==1.16.0
	sqlparse==0.4.3
	tenacity==8.2.2
	typing_extensions==4.5.0
	tzdata==2023.3
	wrapt==1.15.0
	xmltodict==0.13.0
	zipp==3.15.0
	```
</details>

### How can we reproduce your problem?
```python

import os
from ddtrace import patch_all

patch_all()

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "settings")

import django
django.setup()

class NoBool:
    def __bool__(self):
        raise NotImplementedError

from django.core.cache import cache
cache.set(1, NoBool())
cache.get(1)


```

### What is the result that you get?
On the example:
```
NotImplementedError
```
If you are using pandas DataFrame:
```
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

### What is the result that you expected?
The saved dataframe without trying to evaluate it

**Comment by vfoss** [comment]
I have the same issue. It looks like it was introduced in v1.10.0: https://github.com/DataDog/dd-trace-py/blob/v1.10.0/ddtrace/contrib/django/patch.py#L180 , and it appears that v1.9.5 is the latest stable version without the bug.

**Comment by majorgreys** [comment]
This change was introduced in https://github.com/DataDog/dd-trace-py/pull/5052. 

@wconti27, can you look into this?

**Comment by viginti23** [comment]
Did it solve the problem for OP? The error still persists in my case. 
With no ddtrace enabled requests pass through with 200, with ddtrace enabled I am getting 500 with `The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().` 
Tested ddtrace `1.11.2` (BTW there seems to be an issue of not finding the version `1.11.3`) and `1.12.1`

**Comment by ZStriker19** [comment]
> Did it solve the problem for OP? The error still persists in my case. With no ddtrace enabled requests pass through with 200, with ddtrace enabled I am getting 500 with `The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().` Tested ddtrace `1.11.2` (BTW there seems to be an issue of not finding the version `1.11.3`) and `1.12.1`

Hi @viginti23 ! The fix was only pushed for 1.11.3 and 1.12.1, so if you're not using those version I wouldn't expect it to fix the issue for you: https://github.com/DataDog/dd-trace-py/releases

What issues are you having with finding those versions?  They [should be available on pypi](https://pypi.org/project/ddtrace/#history) and downloadable as usual via pip.

**Comment by viginti23** [comment]
Hi @ZStriker19
As I mentioned before I tested version `1.12.1` yet it still doesn't fix the problem for `DataFrame` objects. I monkey patched the `traced_cached` function with custom implementation and it finally works properly.

As for the second issue: 1.11.3 was apparently unavailable in pypi at the time of me posting this information: when adding the library to `requirements.txt`, I was listed all releases but 1.11.3 was not one of them. It is there now indeed.

**Comment by viginti23** [comment]
It is not the prettiest implementation but since it works I left it right the way it is: 
```
        elif command_name == "get":

            try:
                if result is not None and result != getattr(instance, "_missing_key", None):
                    span.set_metric(db.ROWCOUNT, 1)
                else:
                    span.set_metric(db.ROWCOUNT, 0)
            except ValueError:
                if isinstance(result, DataFrame):
                    if result.empty:
                        span.set_metric(db.ROWCOUNT, 0)
                    else:
                        span.set_metric(db.ROWCOUNT, 1)
```

**Comment by ZStriker19** [comment]
@viginti23 1.12.5 has been cut which contains @wconti27 's fix. Could you please give it a go and let us know if it resolves the issue for you?

**Comment by viginti23** [comment]
Hello, yes, that seems to fix the issue; thanks. :)
