### ISSUE TITLE
"No context found" error when tests run with `DD_APPSEC_ENABLED=True`

### ISSUE THREAD

**Issue by johnnymetz** [DataDog/dd-trace-py#5485]
### Which version of dd-trace-py are you using?

1.11.0

### Which version of pip are you using?

23.0.1

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
attrs==22.2.0
bytecode==0.14.1
cattrs==22.2.0
ddsketch==2.0.4
ddtrace==1.11.0
Deprecated==1.2.13
envier==0.4.0
importlib-metadata==6.0.1
iniconfig==2.0.0
jsonschema==4.17.3
opentelemetry-api==1.17.0
packaging==23.0
pluggy==1.0.0
protobuf==4.22.1
pyrsistent==0.19.3
pytest==7.2.2
six==1.16.0
tenacity==8.2.2
typing_extensions==4.5.0
wrapt==1.15.0
xmltodict==0.13.0
zipp==3.15.0
</details>

### How can we reproduce your problem?

```
from ddtrace import tracer
from ddtrace.contrib.trace_utils import set_user

def test_set_user():
    set_user(tracer=tracer, user_id="123")
```

Run the test with `DD_APPSEC_ENABLED=True`:

```
DD_APPSEC_ENABLED=True pytest
```

### What is the result that you get?

Get the following error:

```
    def test_set_user():
>       set_user(tracer=tracer, user_id="123")

tests.py:6:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
venv/lib/python3.11/site-packages/ddtrace/contrib/trace_utils.py:644: in set_user
    block_request_if_user_blocked(tracer, user_id)
venv/lib/python3.11/site-packages/ddtrace/appsec/trace_utils.py:182: in block_request_if_user_blocked
    if should_block_user(tracer, userid):
venv/lib/python3.11/site-packages/ddtrace/appsec/trace_utils.py:149: in should_block_user
    if _context.get_item(WAF_CONTEXT_NAMES.BLOCKED, span=span):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

key = 'http.request.blocked', span = None

    def get_item(key, span=None):
        # type: (str, Optional[Span]) -> Optional[Any]
        """Get and item from the context of a trace."""
        ctx = span if span is not None else _DD_CONTEXTVAR.get()
        if not isinstance(ctx, Span) or ctx._local_root is None:
>           raise ValueError("No context found")
E           ValueError: No context found

venv/lib/python3.11/site-packages/ddtrace/internal/_context.py:22: ValueError
-------------------------------------- Captured log call --------------------------------------
WARNING  ddtrace.contrib.trace_utils:trace_utils.py:635 No root span in the current execution. Skipping set_user tags. See https://docs.datadoghq.com/security_platform/application_security/setup_and_configure/?tab=set_user&code-lang=python for more information.
```

### What is the result that you expected?

I don't think the test test should raise an exception. If there is no context, I would think imagine the test passes. Maybe just log a warning, similar to what is done here:

https://github.com/DataDog/dd-trace-py/blob/be229e2913f39af13d9ff7c9a226d9498b48e18a/ddtrace/appsec/trace_utils.py#L38-L42

**Comment by juanjux** [comment]
Hi @johnnymetz, thanks for your report. I've created the linked PR. Once merged, it'll be backported to the released versions with the user events SDK. Note that your test will still not set the user since it required a span, but will not raise, just log.
