### ISSUE TITLE
Using library injection on Kubernetes, /datadog-init/ddtrace_pkgs/bytecode is mangled

### ISSUE THREAD

**Issue by egnor** [DataDog/dd-trace-py#5565]
### Summary of problem

When automatically injecting ddtrace via library injection on Kubernetes, the `bytecode` package (a dependency of `ddtrace`) which is installed is a mangled combination of versions, with files from older versions taking priority.

### Which version of dd-trace-py are you using?

`v1.11.2`, also reproduces from the current head of the `v1.x` branch of the `dd-trace-py` repo

### Which version of pip are you using?

N/A

### Which libraries and their versions are you using?

N/A

### How can we reproduce your problem?

1. Make sure you have docker and git installed.
2. `git clone https://github.com/DataDog/dd-trace-py`
3. `cd dd-trace-py/lib-injection`
4. `docker build . --tag test-init-image --build-arg DDTRACE_PYTHON_VERSION=v1.11.2`
5. `docker run -it test-init-image sh`

You should now have a shell running inside the Docker image. (You can also just pull a released init image, but I thought I'd demonstrate all the steps to directly build one.)

6. `cd /datadog-init/ddtrace_pkgs/bytecode`
7. `tail -1 version.py`

For me, this shows `__version__ = "0.14.1"` -- so far so good, [this is the latest version of `bytecode`](https://pypi.org/project/bytecode/)

8. `head -1 __init__.py`

Now this shows `__version__ = "0.13.0"`. That's different! Older! Not the same!

### What is the result that you get?

Mismatched version numbers. More significantly, `__init__.py` and other files come from [version 0.13.0 of the module](https://github.com/MatthieuDartiailh/bytecode/tree/0.13.0/bytecode). However, `version.py` and `py.typed` hail from [version 0.14.1 of the module](https://github.com/MatthieuDartiailh/bytecode/tree/0.14.1/src/bytecode).

This would be a minor quirk -- `version.py` and `py.typed` aren't important in a deployment context -- but most of the files come from version 0.13.0 which is from March 2020 and doesn't support newer versions of Python, among other things because calls to `types.CodeType(...)` in `concrete.py` use the wrong constructor arguments, so the instrumentation crashes under some circumstances.

### What is the result that you expected?

A coherent, consistent, and appropriate version of the `bytecode` module, bundled with `ddtrace`.

### Why does this happen?

The `ddtrace` package depends on different versions of `bytecode` depending on the Python version:
https://github.com/DataDog/dd-trace-py/blob/ba0397a1cc5017d85a1fac3d78848a44deaf76e0/setup.py#L330

However, the `dl_megawheel.py` script used in building the init container image simply iterates through all combinations of supported Python versions, architectures, and platforms, downloads the `.whl` files for `ddtrace` and its dependencies (including `bytecode`), and unzips all those `.whl` files into a single directory:
https://github.com/DataDog/dd-trace-py/blob/ba0397a1cc5017d85a1fac3d78848a44deaf76e0/lib-injection/dl_megawheel.py#L114

Since different versions of the `bytecode` wheel will be downloaded based on the Python version, that means several different such files are downloaded and unzipped, and all of the files are splatted on top of each other willy-nilly, leading to the mishmash of versions described above.

**Comment by Kyle-Verhoog** [comment]
hey @egnor thanks for the report! Yep, this an issue introduced in 1.11.1 with the new approach we're using for the injection image exactly as you described.

We're working on a fix for this. In the meantime if you'd like to use automatic injection v1.11.0 should not have the issue (but comes with the drawbacks of `pip install`-ing at application startup).
