### ISSUE TITLE
SQLite integration only times execution, not fetch

### ISSUE THREAD

**Issue by makmanalp** [DataDog/dd-trace-py#557]
Hi!

I've been experimenting with datadog APM and ddtrace, and I noticed some interesting results in the flame graph for my application, which directly contradicted numbers I got running similar queries standalone in sqlite:

![screen shot 2018-09-04 at 2 05 52 pm](https://user-images.githubusercontent.com/161965/45049143-b7f32080-b04b-11e8-9084-b85c1b56914e.png)

The issue seems to be that ddtrace patches .execute, but not .fetchone, .fetchall etc:

https://github.com/DataDog/dd-trace-py/blob/16b8f017076cc4d272a68c93bbc52605b3392f27/ddtrace/contrib/sqlite3/patch.py#L38

In cases with large result sets, the data fetch times can be orders of magnitude larger than the execution time, so this is probably worth also timing.

Experimentally, it seems like sqlalchemy has the same issue, however I'm unsure of the way I collected the sqlalchemy results, since I enabled sqlalchemy in addition to sqlite3, which I'm not sure is allowed. In the flame graph the results show up as approximately the same:

![screen shot 2018-09-04 at 3 12 16 pm](https://user-images.githubusercontent.com/161965/45052494-f8a36780-b054-11e8-837b-6bafbeb167ba.png)

But in the list you see major timing differences, but specifically the sqlalchemy ones seem to be the microsecond ones (I can tell them apart because when you click on them, the sqlalchemy ones have the db name vs sqlite ones have a rowcount property, set to -1).

![screen shot 2018-09-04 at 3 09 21 pm](https://user-images.githubusercontent.com/161965/45052352-92b6e000-b054-11e8-8179-fa9b50c6ff56.png)

There doesn't seem to be any sqlalchemy events for fetching, but perhaps that counts as part of execution: http://docs.sqlalchemy.org/en/latest/core/events.html

In the sqlalchemy performance examples they time things by explicitly wrapping chunks of code with decorators, which ddtrace is by definition trying to avoid: https://github.com/zzzeek/sqlalchemy/blob/master/examples/performance/__init__.py

**Comment by makmanalp** [comment]
(For reference, the same query from above, takes around 37 ms in reality, rather than the 3.68ms ddtrace picks up on, as tested by the raw sqlite command line client using `.timer on`, output piped to /dev/null to make sure I'm not taking into account printing overhead). Not quite apples to apples, but should give you a sense.

Similarly for a larger query where the sqlite timing shows up in the microseconds, the raw query itself takes 554ms.

**Comment by brettlangdon** [comment]
@makmanalp this is actually supported since version `0.19.0` but it is disabled by default (since it is really easy to generate a **ton** of spans from fetching).

To enable you can do it via code:

```python
from ddtrace import config
config.dbapi2.trace_fetch_methods = True
```

Or via the environment variable `DD_DBAPI2_TRACE_FETCH_METHODS=true`.

Closing this issue for now, please feel free to re-open if this does not resolve your issue.
