### ISSUE TITLE
Django `LOGGING` example

### ISSUE THREAD

**Issue by jensenbox** [DataDog/dd-trace-py#5636]
### Summary of problem
I have been working on integrating ddtrace to report properly formatted log entries. As I understand the documentation on the datadog site the preferred format when using containers is to use stdout with JSON.

Would it be possible to provide an example of how best to configure the `LOGGING` setting?

### Which version of dd-trace-py are you using?
Latest

### Which libraries and their versions are you using?
Django 4.2

**Comment by mabdinur** [comment]
Hey @jensenbox, 

I am not sure if I follow. Are you referring to the following doc? https://ddtrace.readthedocs.io/en/stable/advanced_usage.html#logs-injection
