### ISSUE TITLE
Pin.override not working for pymemcached when using HashClient

### ISSUE THREAD

**Issue by damjankuznar** [DataDog/dd-trace-py#5637]
### Summary of problem
Pin.override not working for `pymemcached` lib when using `HashClient`. This is further complicated when setting `use_pooling=True` which then dynamically creates client connections. Being able to only override service name for `Client` instances is not really useful since any kind of serious use of `pymemcached` will involve a Memcached cluster and use of `HashClient`.

### Which version of dd-trace-py are you using?
1.12.0

### Which version of pip are you using?
22.3.1

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
ddtrace==1.12.0
pymemcache==4.0.0
</details>

### How can we reproduce your problem?
Minimal example to demonstrate the issue:
```python
from ddtrace import Pin
from pymemcache import HashClient

servers = ["localhost:11211"]

client = HashClient(servers=servers, use_pooling=True)

Pin.override(client, service="memcached-hashclient-pooling")

# still reports as `memcached` service in DataDog
client.set("test", "value")
```
Only `Client` class is patched and that doesn't work well with overriding since client connections are created dynamically in `HashClient` and `PooledClient` class.

### What is the result that you get?
After using `Pin.override` on `HashClient` instance `ddtrace` still reports traces as `memcached` service in DataDog.

### What is the result that you expected?
I would expect that I could override service name for `HashClient`.

**Comment by emmettbutler** [comment]
@damjankuznar thank you for reporting this issue. We'll take a look and see if we can implement a fix.

**Comment by emmettbutler** [comment]
@damjankuznar After looking into this more closely, I discovered that there is an undocumented way to override the service name on `HashClient` instances. Instead of overriding the pin on the `HashClient` itself, you should do so on each of its held `Client` instances:
```
for _c in client.clients.values():
        Pin.override(_c, service="my-service")
```
I'm going to close this ticket to indicate that the issue has been addressed. Please reopen if you disagree, and thanks again!

**Comment by damjankuznar** [comment]
I tried that but it doesn't work with `use_pooling=True` argument since it's using `PooledClient` in that case, which also doesn't have support for `Pin.override`.

**Comment by emmettbutler** [comment]
@damjankuznar My mistake, sorry about that.

Does [this test](https://github.com/DataDog/dd-trace-py/pull/6084/files#diff-d42d6810060d0c3f0a21547023f59633cc644d201f8b7fc4cbe6cbf74be7395dR324) accurately replicate the use case you're looking for?

**Comment by damjankuznar** [comment]
@emmettbutler sorry for late reply, but yes, I think the test does replicate the use case. Thank you!
