### ISSUE TITLE
socket.gaierror when using ddtrace + gevent will throw an error and never return

### ISSUE THREAD

**Issue by fbexiga** [DataDog/dd-trace-py#5742]
### Summary of problem

When using a combination of a recent version of ddtrace, gunicorn and gevent, if there's a socket.gaierror, an error is thrown because gaierror cannot be pickle, causing the requested endpoint never returns. This only happens on recent versions of ddtrace.

### Which version of dd-trace-py are you using?

1.12.3

### Which version of pip are you using?

Python 3.10.6
pip 23.1.2

### Which libraries and their versions are you using?

gevent==22.10.2
greenlet==2.0.2
gunicorn==20.1.0
Flask==2.3.2

### How can we reproduce your problem?

The following snippet will trigger the problem:

```
import socket
from flask import Flask

app = Flask(__name__)

@app.route('/')
def index():
    try:
        res = socket.getaddrinfo('jfgdjgfdhfdhfdhfdsfdsgfds.com', None, socket.AF_INET)
        return bool(res)
    except socket.gaierror:
        pass

    return 'Hello, world!'
```

And then run it as:
```ddtrace-run gunicorn --worker-class=gevent test:app```

And try to call the endpoint with:
```curl localhost:8000```

### What is the result that you get?

I get the following error on the server:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gevent/threadpool.py", line 633, in _on_async
    self.receiver(self)
  File "src/gevent/event.py", line 402, in gevent._gevent_cevent.AsyncResult.__call__
  File "src/gevent/event.py", line 320, in gevent._gevent_cevent.AsyncResult.set_exception
  File "/usr/local/lib/python3.10/dist-packages/gevent/_tblib.py", line 415, in g
    return f(a)
  File "/usr/local/lib/python3.10/dist-packages/gevent/_tblib.py", line 470, in dump_traceback
    return dumps(tb)
TypeError: cannot pickle 'traceback' object
2023-05-03T12:07:17Z <async_ at 0xffffa2e37370 native=0xffffa2e373b0> failed with TypeError
```

And no response on the client, until it eventually times out.

### What is the result that you expected?

The expected result is for the endpoint to return something, in this case "Hello, world!".

**Comment by P403n1x87** [comment]
This seems due to the unloading of the `copyreg` module. Investigating for a fix.

**Comment by fbexiga** [comment]
It did resolve the issue. Much appreciated!
