### ISSUE TITLE
Autoinstrumentation installs incorrect version of ddtrace

### ISSUE THREAD

**Issue by esauser** [DataDog/dd-trace-py#5770]
### Summary of problem
Autoinstrumentation within Kubernetes via the annotation and label is installing the wrong version of `ddtrace`.  It appears to be installing the latest version instead of the specified version.

### How can we reproduce your problem?
Our deployments are annotated with
```
admission.datadoghq.com/python-lib.version: v1.12.1
```

### What is the result that you get?
The autoinstrumentation installs `1.12.4`.
```
datadog autoinstrumentation: installing python package
Looking in links: /datadog-lib/ddtrace_pkgs
Collecting ddtrace
  Downloading ddtrace-1.12.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.1/4.1 MB 60.4 MB/s eta 0:00:00
```

### What is the result that you expected?
`1.12.1` is installed.

**Comment by Kyle-Verhoog** [comment]
Thanks for the report @esauser, this should issue will be resolved with #5758
