### ISSUE TITLE
Kafka Trace recursion max depth error 

### ISSUE THREAD

**Issue by Manan-Kothari** [DataDog/dd-trace-py#5888]
### Summary of problem
Seeing a recursion max depth error when tracing kafka 

### Which version of dd-trace-py are you using?
1.13.3

### Which version of pip are you using?
23.1.2

### Which libraries and their versions are you using?
<details>
  <summary>`pip freeze`</summary>
anyio==3.6.2
asgiref==3.6.0
asn1crypto==1.5.1
async-timeout==4.0.2
attrs==23.1.0
build==0.10.0
bytecode==0.14.1
CacheControl==0.12.11
cachetools==5.3.0
cattrs==22.2.0
certifi==2023.5.7
cffi==1.15.1
charset-normalizer==2.1.1
cleo==2.0.1
click==8.1.3
confluent-kafka==1.9.2
coverage==7.2.5
crashtest==0.4.1
cryptography==40.0.2
Cython==0.29.34
ddsketch==2.0.4
ddtrace==1.13.3
decorator==4.4.2
Deprecated==1.2.13
distlib==0.3.6
dulwich==0.21.5
envier==0.4.0
exceptiongroup==1.1.1
fastapi==0.74.1
fastavro==1.7.4
filelock==3.12.0
google-api-core==2.11.0
google-auth==2.18.0
google-cloud-core==2.3.2
google-cloud-secret-manager==1.0.2
google-cloud-storage==1.44.0
google-crc32c==1.5.0
google-resumable-media==2.5.0
googleapis-common-protos==1.59.0
grpc-google-iam-v1==0.12.6
grpcio==1.54.2
grpcio-status==1.48.2
gunicorn==20.1.0
h11==0.14.0
h3==3.7.6
html5lib==1.1
httpcore==0.17.0
httpx==0.24.0
idna==3.4
importlib-metadata==6.0.1
iniconfig==2.0.0
installer==0.7.0
jaraco.classes==3.2.3
jeepney==0.8.0
joblib==1.2.0
jsonschema==4.17.3
keyring==23.13.1
lockfile==0.12.2
more-itertools==9.1.0
msgpack==1.0.5
networkx==2.5.1
numpy==1.24.3
numpyencoder==0.3.0
opentelemetry-api==1.17.0
oscrypto==1.3.0
p44-common-models==1.1.12
p44-datadog==1.0.8
p44-ds-utils==1.0.51
p44-fastapi==1.0.26
p44-logging==1.0.14
p44-ml-prediction-bookkeeper==1.0.17
p44-transit-time-models==2.0.146
packaging==23.1
pandas==1.5.3
parameterized==0.8.1
pexpect==4.8.0
Pint==0.18
pkginfo==1.9.6
platformdirs==2.6.2
pluggy==1.0.0
poetry==1.4.2
poetry-core==1.5.2
poetry-plugin-export==1.3.1
prometheus-client==0.16.0
protobuf==3.20.3
ptyprocess==0.7.0
py==1.11.0
pyarrow==6.0.1
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
pycryptodomex==3.17
pydantic==1.10.7
PyJWT==2.7.0
pyOpenSSL==23.1.1
pyproject_hooks==1.0.0
pyrsistent==0.19.3
pytest==6.2.5
pytest-cov==4.0.0
python-dateutil==2.8.2
pytz==2022.7.1
quantities==0.13.0
rapidfuzz==2.15.1
redis==4.3.6
requests==2.30.0
requests-toolbelt==0.10.1
rsa==4.9
Rtree==1.0.1
scikit-learn==0.24.2
scipy==1.9.3
SecretStorage==3.3.3
Shapely==1.8.5.post1
shellingham==1.5.0.post1
six==1.16.0
sniffio==1.3.0
snowflake-connector-python==3.0.3
starlette==0.17.1
starlette-context==0.3.6
starlette-exporter==0.10.0
tenacity==8.2.2
threadpoolctl==3.1.0
toml==0.10.2
tomli==2.0.1
tomlkit==0.11.8
# Editable install with no version control (transit-time-service==0.1.18)
-e /p44/transit_time
trove-classifiers==2023.5.2
typing_extensions==4.5.0
urllib3==1.26.15
uvicorn==0.14.0
virtualenv==20.21.1
webencodings==0.5.1
wrapt==1.15.0
xmltodict==0.13.0
zipp==3.15.0
  <!>
</details>

### How can we reproduce your problem?
Seeing a recursion error when tracing kafka spans after upgrading to 1.13.3 from 1.5.5

### What is the result that you get?
[transit-time-kafka-error.log](https://github.com/DataDog/dd-trace-py/files/11501539/transit-time-kafka-error.log)

```
error closing trace
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ddtrace/span.py", line 538, in __exit__
    self.finish()
  File "/usr/local/lib/python3.9/site-packages/ddtrace/span.py", line 261, in finish
    self._finish_ns(time_ns())
  File "/usr/local/lib/python3.9/site-packages/ddtrace/span.py", line 274, in _finish_ns
    cb(self)
  File "/usr/local/lib/python3.9/site-packages/ddtrace/tracer.py", line 768, in _on_span_finish
    active = self.current_span()
  File "/usr/local/lib/python3.9/site-packages/ddtrace/tracer.py", line 878, in current_span
    active = self.context_provider.active()
  File "/usr/local/lib/python3.9/site-packages/ddtrace/provider.py", line 137, in active
    return self._update_active(item)
  File "/usr/local/lib/python3.9/site-packages/ddtrace/provider.py", line 103, in _update_active
    self.activate(new_active)
  File "/usr/local/lib/python3.9/site-packages/ddtrace/provider.py", line 130, in activate
    super(DefaultContextProvider, self).activate(ctx)
  File "/usr/local/lib/python3.9/site-packages/ddtrace/provider.py", line 45, in activate
    self._hooks.emit(self.activate, ctx)
  File "/usr/local/lib/python3.9/site-packages/ddtrace/_hooks.py", line 129, in emit
    for func in self._hooks.get(hook, ()):
RecursionError: maximum recursion depth exceeded in comparison
```

### What is the result that you expected?

Being able to trace kafka spans without errors

**Comment by mabdinur** [comment]
Hey @Manan-Kothari, 

Thanks for brining this issue to our attention 😄. For now you can disable the kafka integration by setting the following environment variable: `DD_TRACE_KAFKA_ENABLED=false`. This should resolve these errors. 

From the stack trace it is not clear how this error occurred.  Can you provide a reproduction case?

**Comment by Manan-Kothari** [comment]
We rolled back the tracer for now, but this is occurring when we are tracing log messages. We send all of our log messages to a kafka consumer group for processing. 

Not sure if this helps  [transit-time-kafka-error.log](https://github.com/DataDog/dd-trace-py/files/11510030/transit-time-kafka-error.log)

**Comment by Manan-Kothari** [comment]
Some more details, we fixed this internally by updating our own internal logging library to remove importing the producer from confluent_kafka 

> # ddtrace will patch the confluent_kafka.Producer and if debug logs are enabled
# an infinite recursion of DataDog spans caused by kafka.produce of logs
# ddtrace saves the original unpatch producer and we will use this instead of the
# patched one for producing log messages
try:
    from ddtrace.contrib.kafka.patch import _Producer as Producer
except ImportError:
    from confluent_kafka import Producer

**Comment by emmettbutler** [comment]
@Manan-Kothari my understanding from reading this thread is that your application overrides `log.debug` to include a `produce()` call, and because ddtrace's Kafka integration includes `log.debug` calls, infinite recursion occurs when the tracer calls `log.debug`, which calls `trace`, which calls `log.debug`, etc.

If that understanding is correct, I think you've taken the right approach by disabling ddtrace's Kafka patching. This isn't a use case that ddtrace attempts to support.

If you agree, we can close this ticket. What am I missing?

**Comment by Manan-Kothari** [comment]
Yes, we were able to use the kafka integration included with dd_trace by disabling the import from the confluent_kafka and only use ddtrace to pull in the producer import. This can be closed.
