### ISSUE TITLE
Psycopg 3 patch does not support ClientCursor and AsyncClientCursor

### ISSUE THREAD

**Issue by mastizada** [DataDog/dd-trace-py#5970]
### Summary of problem
To make psycopg (or psycopg3) work similarly to psycopg2, cursor factory ClientCursor (and AsyncClientCursor for async engine) can be used. This is very helpful for large projects that are migrating to psycopg3. dd-trace-py recently added support for psycopg3, however, it is only patching Cursor and AsyncCursor. It will be nice to add support for ClientCursor's too.

### Which version of dd-trace-py are you using?
1.13.3

### Which version of pip are you using?
23.1.2

### Which libraries and their versions are you using?
A lot, however, it shouldn't affect this issue. I'm trying to move from manually patching sqlalchemy to auto-patch of psycopg3.

### How can we reproduce your problem?
`_patch` function in `ddtrace.contrib.psycopg.patch.py` file.

### What is the result that you get?
Non-parsable SQL query

### What is the result that you expected?
SQL query

**Comment by emmettbutler** [comment]
Thanks for bringing this to our attention, @mastizada. We'll add it to our backlog of feature requests.

**Comment by mastizada** [comment]
@emmettbutler tracing works, no issues with that, the problem is that it doesn't capture SQL queries. Datadog shows "Non-parsable SQL query" message for most of the sql queries, only some simple select statements were shown. Sorry that it wasn't clear in the issue definition.

**Comment by emmettbutler** [comment]
@mastizada I think we need some more information to solve this issue, because the tests in #6043 verify that the tested SQL query attributes are identical between `Cursor` and `ClientCursor` tracing.

What kind of SQL queries are failing to parse in the UI? What do they have in common?

**Comment by emmettbutler** [comment]
I'm going to close this due to lack of activity. Please comment if there's new information to share.
