### ISSUE TITLE
Wagtail CMS support

### ISSUE THREAD

**Issue by allixsenos** [DataDog/dd-trace-py#598]
Wagtail is a Django-based CMS. Unfortunately, instrumenting the app using the default Django integration records all traces as belonging to "wagtail.wagtailcore.views.serve".

Since wagtail supports python code behind certain pages, there can be a huge difference between different pages being served.

I think an option in the integration to use URL as the resource name instead of the view function name would greatly improve the situation.

**Comment by Kyle-Verhoog** [comment]
Hi @allixsenos!

I agree that the name of the handling view function is not ideal in a lot of cases. We'll look into whether we can provide an option to use the URL route which would provide a much better indication of what the trace is actually tracing.

Thanks!

**Comment by majorgreys** [comment]
We are currently working on a rewrite of the Django integration that will address this issue. Updates to come!

**Comment by Kyle-Verhoog** [comment]
This rewrite was done back in v0.34 of the library and I've tried out the Django integration with a Wagtail app and it seems to work alright.

Feel free to reopen this issue if further improvements could be made!
