### ISSUE TITLE
Datadog showing "warning" as "error" when message attribute is more than 10 for SNS record

### ISSUE THREAD

**Issue by Arpan198829** [DataDog/dd-trace-py#5980]
Hello,

We have a python where we are publishing messages in SNS but the message attribute is more than 10.
Now, as there message attribute is more than 10 so we seeing error in the datadog as below.

**Error: "skipping trace injection, max number (10) of MessageAttributes exceeded, 24 additional messages skipped"**

When we checked the ddtrace code by installing ddtrace(pip install ddtrace) in local system we found that the above error log is coming from inject_trace_data_to_message_attributes() in patch.py file. Please find the screenshot of the actual codebase attached.

![image](https://github.com/DataDog/dd-trace-py/assets/86417574/6ba7f526-c6a2-4466-be6c-2c867d7cbe94)

As per the code its a "WARNING" but in the datadog its coming as "ERROR". Please find the screenshot from datatdog UI.
![image](https://github.com/DataDog/dd-trace-py/assets/86417574/717adc65-eb45-40c7-986e-f8dd2b40dce4)

Thanks in advance!!

**Comment by emmettbutler** [comment]
Thank you for opening this ticket, @Arpan198829.

I recommend checking your [Log Status Remapper](https://docs.datadoghq.com/logs/log_configuration/processors/?tab=ui#log-status-remapper) configuration. The Log Status Remapper applies a processing stage between the log being generated and it appearing in the Datadog UI. I suspect that in this case it's remapping this Warning log to an Error.
