### ISSUE TITLE
Deprecate Tracer.configure?

### ISSUE THREAD

**Issue by rmorshea** [DataDog/dd-trace-py#5986]
As per [this comment](https://github.com/DataDog/dd-trace-py/blob/ab52739267a1e10e9e4ede619d96e6898ac7f9f8/ddtrace/tracer.py#L366), `Tracer.configure` should be deprecated at some point. That, or the deprecation comment should be removed and the `Tracer.configure` API preserved.

**Comment by majorgreys** [comment]
Are you currently using this interface?
