### ISSUE TITLE
psycopg3 integration is broken due to improper implementation of `__aexit__`

### ISSUE THREAD

**Issue by seandstewart** [DataDog/dd-trace-py#6001]
### Summary of problem

psycopg3's AsyncConnection requires that the `exc_type`, `exc_val`, and `exc_tb` values be passed:

https://github.com/psycopg/psycopg/blob/580ea8c57b2e57ab1e7e6392e130348ac4d9b146/psycopg/psycopg/connection_async.py#L143-L148

However, the dbapi implementation in this library calls them without passing in those parameters:

https://github.com/DataDog/dd-trace-py/blob/5861a61b063f8cb7f04bdeaa2c9e8141bc25fcd8/ddtrace/contrib/dbapi_async/__init__.py#L220-L224

Not only is this broken, this is likely erasing the error-handling present in libraries where this may work.

### Which version of dd-trace-py are you using?

v1.14.0

update:

I have verified that v1.13.0-2 are unusable due to #5821 and this bug was present starting with v1.13.3. 

I am able to successfully enter and exit an async context in v1.12.9, however it looks like there is no async support for psycopg in this version, so this is effectively the same an having no telemetry.

### Which version of pip are you using?

n/a

### Which libraries and their versions are you using?

This is with the latest version of psycopg, although the problem likely exists with all versions.

```
❯ poetry show psycopg                                                                                         
 name         : psycopg                                
 version      : 3.1.9                                  
 description  : PostgreSQL database adapter for Python 
```

### How can we reproduce your problem?

```python

>>> import ddtrace
>>> ddtrace.patch_all()
>>> import psycopg
>>> async with await psycopg.AsyncConnection.connect("dbname=postgres user=postgres host=127.0.0.1") as conn:
...     await conn.execute("select 1")
...     
Traceback (most recent call last):
  File "/Users/seanstewart/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/223.8836.34/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py", line 367, in runcode
    loop.run_until_complete(coro)
  File "/Users/seanstewart/.pyenv/versions/3.11.0/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "<input>", line 1, in <module>
  File "/Users/seanstewart/PycharmProjects/payments/.venv/lib/python3.11/site-packages/ddtrace/contrib/dbapi_async/__init__.py", line 224, in __aexit__
    return await self.__wrapped__.__aexit__()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AsyncConnection.__aexit__() missing 3 required positional arguments: 'exc_type', 'exc_val', and 'exc_tb'
```

### What is the result that you get?

When tracing is enabled, all successful connections fail on exit from the context.

### What is the result that you expected?

We should be able to make use of async contexts.

**Comment by emmettbutler** [comment]
Thanks for the bug report @seandstewart. We'll look into implementing a fix.
