### ISSUE TITLE
Add Anthropic support similar to OpenAI

### ISSUE THREAD

**Issue by Tradunsky** [DataDog/dd-trace-py#6055]
### Summary of problem
Thanks for adding OpenAI support, it is awesome!

I am curious if there any plans to add other providers of LLM such as [Anthropic](https://console.anthropic.com/docs/api/reference)?

### Which version of dd-trace-py are you using?
1.14.0

### Which version of pip are you using?
Not using pip.

### Which libraries and their versions are you using?
poetry==1.4.2

<details>
  <summary>`pip freeze`</summary>
  
</details>

### What is the result that you expected?
Anthropic LLM dedicated metrics similar to OpenAI. Ideally with its own dashboard.

**Comment by Yun-Kim** [comment]
Hi @Tradunsky, thanks for reaching out! Apologies for the late response - while we'd love to add support for tracing Anthropic (and it is definitely on our to-do list of integrations), it's challenging to make an integration for it as access to Anthropic is still private and invite-only at the moment.

**Comment by ishaan-jaff** [comment]
Hi @Yun-Kim @brettlangdon @Tradunsky  I believe we can help with this issue. I’m the maintainer of LiteLLM https://github.com/BerriAI/litellm

**TLDR:**
**We allow you to use any LLM as a drop in replacement for `gpt-3.5-turbo`. 
If you don't have access to the LLM you can use the LiteLLM proxy to make requests to the LLM**

You can use LiteLLM in the following ways:

## With your own API KEY:
This calls the provider API directly

```python
from litellm import completion
import os
## set ENV variables 
os.environ["OPENAI_API_KEY"] = "your-key" # 
os.environ["COHERE_API_KEY"] = "your-key" # 

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion(model="command-nightly", messages=messages)
```

## Using the LiteLLM Proxy with a LiteLLM Key 
this is great if you don’t have access to claude but want to use the open source LiteLLM proxy to access claude


```python
from litellm import completion
import os

## set ENV variables 
os.environ["OPENAI_API_KEY"] = "sk-litellm-5b46387675a944d2" # [OPTIONAL] replace with your openai key
os.environ["COHERE_API_KEY"] = "sk-litellm-5b46387675a944d2" # [OPTIONAL] replace with your cohere key

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion(model="command-nightly", messages=messages)
```

**Comment by Yun-Kim** [comment]
As Anthropic is finally publicly available, we've started work on an Anthropic integration (see #9420).
