### ISSUE TITLE
Missing type information in 1.15.0

### ISSUE THREAD

**Issue by burritoatspoton** [DataDog/dd-trace-py#6109]
### Summary of problem

After updating ddtrace to the latest release `mypy` complains about missing type info for `ddtrace` – I believe this is connected to the exclusion of `py.typed` marker from package data in https://github.com/DataDog/dd-trace-py/pull/5940.

### Which version of dd-trace-py are you using?

1.15.0

### Which version of pip are you using?

22.3.1

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>

```
attrs==23.1.0
bytecode==0.14.2
cattrs==23.1.2
ddsketch==2.0.4
ddtrace==1.15.0
Deprecated==1.2.14
envier==0.4.0
importlib-metadata==6.0.1
jsonschema==4.17.3
mypy==1.3.0
mypy-extensions==1.0.0
opentelemetry-api==1.18.0
protobuf==4.23.2
pyrsistent==0.19.3
six==1.16.0
typing_extensions==4.6.3
wrapt==1.15.0
xmltodict==0.13.0
zipp==3.15.0
```

</details>

### How can we reproduce your problem?

1. `main.py`:
```python
from ddtrace import Tracer
```
2. invoke `mypy main.py`

### What is the result that you get?

```
main.py:1: error: Skipping analyzing "ddtrace": module is installed, but missing library stubs or py.typed marker  [import]
main.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```

### What is the result that you expected?

`mypy` exiting successfully.

**Comment by emmettbutler** [comment]
Thanks for the report @burritoatspoton!

I've opened https://github.com/DataDog/dd-trace-py/pull/6115 fixing this issue.

I'd like to check for this in an automated test, but so far I haven't been able to replicate it aside from installing `ddtrace` from PyPI.

**Comment by Eyal-Shalev** [comment]
This issue still exists in `ddtrace==1.15.0`

```
❯ pip freeze | grep ddtrace
ddtrace==1.15.0
❯ mypy --config-file pyproject.toml .
path/to/file.py:13: error: Skipping analyzing "ddtrace": module is installed, but missing library stubs or py.typed marker  [import]
path/to/file.py:13: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 2 errors in 2 files (checked 33 source files)
```
