### ISSUE TITLE
X-Datadog-Trace-Id Header has negative value

### ISSUE THREAD

**Issue by alexruden** [DataDog/dd-trace-py#6125]
**Question**: Why `X-Datadog-Trace-Id` Header has negative value?
One of our web applications does http request to our backend app and we see error in Sentry:
"OverflowError: can't convert negative value to uint64_t"
I checked http headers of request and made attention to this header.
`X-Datadog-Trace-Id: -6546508155668190000`

Question - is this ok that it has negative value?

### Summary of problem
`X-Datadog-Trace-Id` header has a strange value(?)

### Which version of dd-trace-py are you using?
1.7.5

**Comment by emmettbutler** [comment]
@alexruden Thanks for reporting this issue. We'll look into it!

**Comment by mabdinur** [comment]
Hi @alexruden,

Weird. Trace ids should never be negative. `X-Datadog-Trace-Id` headers with negative values should not be sent in the first place.

Are the negative trace ids headers generated by an application using ddtrace v1.7.5? If not, what tracing library and versions is being used to generate these headers?

**Comment by mabdinur** [comment]
Resolved by: https://github.com/DataDog/dd-trace-py/pull/6133
