### ISSUE TITLE
Guidance when integrating ddtrace in multi-threaded apps?

### ISSUE THREAD

**Issue by goodspark** [DataDog/dd-trace-py#613]
I'm using a thread pool to refresh compute/IO heavy cached functions for a pyramid web app. The ddtrace docs don't really describe how to handle threading and the docstring for `Tracer` says:

> If you're running an application that will serve a single trace per thread,
>    you can use the global tracer instance::

... without really going further to describe what a multi-threaded integration would look like. 

1. Ultimately, my question is: What is the DD team's recommendation on how to approach this? A thread local that wraps the tracer objects and only uses the global `ddtrace.tracer` instance on the main thread? Has such an approach been documented/tested somewhere I've simply missed?
2. When creating multiple `Tracer` instances, what's the easiest way to 'inherit' or 'copy' the configuration/settings/etc from the global instance? (eg: Things like hostname, tags, etc).
3. Is it reasonable to expect a linkage between reported traces and spans from background threads and those from the main thread?

My current integration without any thread locals looks like this:

```python
from ddtrace import tracer
from ddtrace import patch_all
from ddtrace.contrib.pyramid import trace_pyramid
import time
import random

patch_all()

# In my pyramid config/init...
def pyramid_init():
   ...
   trace_pyramid(configurator)
   ...

# In my other modules
THREAD_POOL = ...

@tracer.wrap()
def something_slow():
  ...
  time.sleep(random.choice([0.3, 3.0]))
  return value

@view_config(route_name='test', renderer='json')
def get_something(request):
  THREAD_POOL.submit(something_slow)
  time.sleep(1)
  return {'value': 'blah'}
```

What I see in Datadog APM is something like this:
![screenshot from 2018-09-21 13-29-06](https://user-images.githubusercontent.com/29210237/45904936-75e41180-bda3-11e8-9eea-e96a5b748485.png)

In regards to question 3, my naive expectation was that I'd see a vertical line branch out of the `pyramid.request` span and show the work in the background thread (ie. `something_slow`), running horizontally in parallel with the main thread's span (ie. the request).

**Comment by goodspark** [comment]
Update, sometimes I see multiple requests' traces combined!

![screenshot from 2018-09-22 22-13-30](https://user-images.githubusercontent.com/29210237/45924432-e169d400-beb4-11e8-91dc-e9485cfea50f.png)

The highlighted trace belongs to the wrapped function run inside a thread pool.

**Comment by goodspark** [comment]
This works now with a recent fix to handling futures.

**Comment by ejholmes** [comment]
@goodspark curious what fix you're referring to. We're running into similar issues with some code that uses threads to parallelize some work.

**Comment by goodspark** [comment]
I believe the fix was https://github.com/DataDog/dd-trace-py/releases/tag/v0.20.3 although I haven't done a full before-after test to verify. I'm now on 0.24.0 and span from futures appear correctly for me (ie. they branch out vertically and run in parallel to the parent spans and they don't cause mega-traces like the image above).

**Comment by aonamrata** [comment]
> I believe the fix was https://github.com/DataDog/dd-trace-py/releases/tag/v0.20.3 although I haven't done a full before-after test to verify. I'm now on 0.24.0 and span from futures appear correctly for me (ie. they branch out vertically and run in parallel to the parent spans and they don't cause mega-traces like the image above).

Has anyone tried this? I am on `ddtrace==0.46.0` and i get the traces from the main thread but not from the spawn threads.

**Comment by torstenrudolf** [comment]
> > I believe the fix was https://github.com/DataDog/dd-trace-py/releases/tag/v0.20.3 although I haven't done a full before-after test to verify. I'm now on 0.24.0 and span from futures appear correctly for me (ie. they branch out vertically and run in parallel to the parent spans and they don't cause mega-traces like the image above).
> 
> Has anyone tried this? I am on `ddtrace==0.46.0` and i get the traces from the main thread but not from the spawn threads.

@aonamrata  do you patch futures?
see https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/futures/patch.py

**Comment by aonamrata** [comment]
> @aonamrata do you patch futures?
> see https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/futures/patch.py

Thanks, yes I had patch all. 
FYI, I was able to resolve it with the very latest version.

**Comment by inikolaev** [comment]
I would like to bring this thread alive as we are seeing some spans which get stuck in `on_span_finish` for a very long time sometimes (~50 seconds). After looking at the code, I noticed that the method tries to acquire a lock at the very beginning, so I'm wondering if this could potentially cause the issue?

Here's where the lock is being acquired: 
https://github.com/DataDog/dd-trace-py/blob/afd2b3054bf2e9682caa65fd0d4b4408fce99f64/ddtrace/internal/processor/trace.py#L161

And seems there's quite a bit of processing happening inside - would it be beneficial to somehow narrow the scope of the lock? I'm not familiar with the code, but it doesn't look like there's a lot of shared state being updated, but maybe lock can be more granular if needed?

Or is it recommended to create a separate instance if the `Tracer` instance per thread as was mentioned by OP?

**Comment by inikolaev** [comment]
And if a separate tracer instance is created, how would it affect patched libraries - they would need to somehow know which tracer instance to use 🤔
