### ISSUE TITLE
@emmettbutler We started facing this again. Can we look for a long-term fix? Increasing the buffer size every time doesn't sound feasible.

### ISSUE THREAD

**Issue by Priya997** [DataDog/dd-trace-py#6152]
@emmettbutler We started facing this again. Can we look for a long-term fix? Increasing the buffer size every time doesn't sound feasible.

_Originally posted by @Priya997 in https://github.com/DataDog/dd-trace-py/issues/5799#issuecomment-1594155922_

**Comment by brettlangdon** [comment]
@Priya997 thanks for bringing to our attention, we can just re-open the original issue since all the context there is still applicable.
