### ISSUE TITLE
TypeError when producing Kafka message without a partition `key`

### ISSUE THREAD

**Issue by fpighi** [DataDog/dd-trace-py#6162]
### Summary of problem

Patching of Kafka library expects the partition key to be text, even when it's None.

### Which version of dd-trace-py are you using?

1.15.0

### Which version of pip are you using?

22.2.2

### Which libraries and their versions are you using?

Available if needed.

### How can we reproduce your problem?

Using the `confluent_kafka` library and running the app with `ddtrace-run`:

1. Produce a message in any topic without specifying a `key` in the [Producer](https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#pythonclient-producer) `produce()` parameters
2. Verify the exception to contain the following stack trace
3. Set `DD_TRACE_KAFKA_ENABLED=false` and verify it works fine.

### What is the result that you get?

```
  File "/usr/local/lib/python3.11/site-packages/ddtrace/contrib/kafka/patch.py", line 99, in traced_produce
    span.set_tag_str(kafkax.MESSAGE_KEY, ensure_text(message_key))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/six.py", line 955, in ensure_text
    raise TypeError("not expecting type '%s'" % type(s))
TypeError: not expecting type '<class 'NoneType'>'
```

### What is the result that you expected?

Probably the MESSAGE_KEY tag should be set to something like "N/A" or something similar, or not be present in the worst case.

**Comment by mabdinur** [comment]
Fix was released in v1.18.0: https://github.com/DataDog/dd-trace-py/commit/8536722284dfd57f35c04adf0db7e49d1bf290dc
