### ISSUE TITLE
Getting "re.error: internal: unsupported operand type BRANCH" on bootstrap when using ddtrace with scylla-driver

### ISSUE THREAD

**Issue by fbexiga** [DataDog/dd-trace-py#6197]
### Which version of dd-trace-py are you using?

1.15.0 (issue seems to start with version 1.13.4)

### Which version of pip are you using?

Python 3.10.6 pip 23.1.2

### Which libraries and their versions are you using?

scylla-driver==3.26.2

### How can we reproduce your problem?

When trying to start a Flask API using
`ddtrace-run gunicorn --config conf/gunicorn_conf.py app`

it fails immediately with the following traceback:
```
File "/usr/local/lib/python3.10/dist-packages/ddtrace/internal/module.py", line 220, in _exec_module
    self.loader.exec_module(module)
  File "cassandra/cqltypes.py", line 91, in init cassandra.cqltypes
  File "/usr/lib/python3.10/re.py", line 363, in __init__
    self.scanner = sre_compile.compile(p)
  File "/usr/lib/python3.10/sre_compile.py", line 792, in compile
    code = _code(p, flags)
  File "/usr/lib/python3.10/sre_compile.py", line 631, in _code
    _compile(code, p.data, flags)
  File "/usr/lib/python3.10/sre_compile.py", line 263, in _compile
    raise error("internal: unsupported operand type %r" % (op,))
re.error: internal: unsupported operand type BRANCH
```

It doesn't even get to execute any part of the code, so I suspect this happens during monkey patching.

It works if ddtrace-run is removed, or if an older version is used.

### What is the result that you get?

I am unable to start the application, getting the error mentioned above.

### What is the result that you expected?

I expected the application to start and work just like it does with an older version of ddtrace.

**Comment by P403n1x87** [comment]
@fbexiga is `gevent` being used here? If so, could you test with the environment variable `DD_UNLOAD_MODULES_FROM_SITECUSTOMIZE` set to `0`, please? Note that your app _might_ still not work as expected, but if we get a different behaviour it helps us narrowing the issue down 🙏 .

**Comment by fbexiga** [comment]
Indeed `gevent` is being used. It looks like setting `DD_UNLOAD_MODULES_FROM_SITECUSTOMIZE=0` did make the app work as expected.

**Comment by P403n1x87** [comment]
@fbexiga thanks for confirming that!
