### ISSUE TITLE
patch for mariadb causes alembic+sqlalchemy to fail when connection string doesn't explicitly specify password or port

### ISSUE THREAD

**Issue by danju-papaya** [DataDog/dd-trace-py#6203]
### Summary of problem
patch for mariadb causes alembic+sqlalchemy to fail when connection string doesn't explicitly specify password or port

### Which version of dd-trace-py are you using?
1.15

### Which version of pip are you using?
23.0.1

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
  
alembic==1.11.1
attrs==23.1.0
blinker==1.6.2
boto3==1.26.152
botocore==1.29.152
bytecode==0.14.1
cattrs==22.2.0
click==8.1.3
colorama==0.4.6
ddsketch==2.0.4
ddtrace==1.15.0
Deprecated==1.2.13
envier==0.4.0
et-xmlfile==1.1.0
exceptiongroup==1.1.1
Flask==2.3.2
greenlet==2.0.2
importlib-metadata==6.0.1
iniconfig==2.0.0
itsdangerous==2.1.2
Jinja2==3.1.2
jmespath==1.0.1
jsonpickle==3.0.1
jsonschema==4.17.3
Mako==1.2.4
mariadb==1.0.11
MarkupSafe==2.1.2
mock==5.0.2
numpy==1.24.3
numpy-financial==1.0.0
openpyxl==3.1.2
opentelemetry-api==1.18.0
packaging==23.0
pandas==2.0.2
pika==1.3.2
pluggy==1.0.0
protobuf==4.23.1
pyrsistent==0.19.3
pytest==7.3.2
pytest-dotenv==0.5.2
python-dateutil==2.8.2
python-dotenv==1.0.0
pytz==2023.3
ruff==0.0.272
s3transfer==0.6.1
scipy==1.10.1
six==1.16.0
SQLAlchemy==2.0.16
tenacity==8.2.2
tomli==2.0.1
typing_extensions==4.5.0
tzdata==2023.3
urllib3==1.26.16
Werkzeug==2.3.4
wrapt==1.15.0
xlcalculator==0.5.0
xmltodict==0.13.0
yearfrac==0.4.8
zipp==3.15.0

</details>

### What is the result that you get?
exception - 

```
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 615, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.9/site-packages/ddtrace/contrib/mariadb/patch.py", line 42, in _connect
    net.TARGET_PORT: kwargs["port"],
KeyError: 'port'
```

### What is the result that you expected?

That the following connection string would work:
mariadb+mariadbconnector://root@db/my-db

the problem is that the patch assumes host, port, user, database are always exist.
This seems to be wrong. The kwargs in my case have host, username, and database

suggested fix:
use port or default to 3306
use user or username (not sure about this one)

**Comment by emmettbutler** [comment]
@danju-papaya thank you for reporting this issue. At first glance it looks like a fix would be pretty straightforward. We'll add this to our issue backlog.
