### ISSUE TITLE
Cannot enable dynamic instrumentation with environement variable in Django project

### ISSUE THREAD

**Issue by ryan-shaw** [DataDog/dd-trace-py#6364]
### Summary of problem

Setting `DD_DYNAMIC_INSTRUMENTATION_ENABLED=true` should enable dynamic tracing but can only enable it programmatically using 

```python
from ddtrace.debugging import DynamicInstrumentation

DynamicInstrumentation.enable()
```

ddtrace is configured in `settings.py` using

```python
from ddtrace import config, tracer, patch_all

tracer.configure(
    hostname=os.environ.get("DD_AGENT_HOST", "172.17.0.1"),
)
config.django["cache_service_name"] = ...
config.django["instrument_caches"] = ...
config.django["instrument_databases"] = ...
tracer.set_tags(...)

patch_all(psycopg=False)
```

I have used DD_TRACE_DEBUG and can confirm DI is not even attempted to be initialised, when I use the code to enable DI I see the "debugging" log messages.

### Which version of dd-trace-py are you using?

1.16.0

### Which version of pip are you using?

23.1.2

### Which libraries and their versions are you using?

Can provide privately 

### How can we reproduce your problem?

Django project

```
DD_PROFILING_ENABLED=1
DD_VERSION=<version>
DD_ENV=staging
DD_SERVICE=django
DD_TRACE_RATE_LIMIT=50
DD_TRACE_SAMPLE_RATE=0.1
DD_DYNAMIC_INSTRUMENTATION_ENABLED=true
DD_TRACE_SAMPLING_RULES=...
DD_SPAN_SAMPLING_RULES=...
DD_AGENT_HOST=...
```

### What is the result that you get?

I can only enable dynamic instrumentation programmatically .

### What is the result that you expected?

I would like to enable dynamic instrumentation using an environment variable

**Comment by P403n1x87** [comment]
@ryan-shaw thanks for reporting this. Can I confirm with you that you are using `ddtrace-run` to start your application. Setting `DD_DYNAMIC_INSTRUMENTATION_ENABLED` has an effect only when `ddtrace-run` is used to start the application. If you are not using/cannot use `ddtrace-run`, then the programmatic enablement is the only other way of enabling DI at the moment.

In fact, importing `ddtrace.auto` should also honour the environment variable (see the note in https://ddtrace.readthedocs.io/en/stable/integrations.html#gevent), but we do recommend the use of `ddtrace-run` when possible.

**Comment by ryan-shaw** [comment]
Ah! That could be it, we have never started the app with `ddtrace-run`, I'll give that a try and report back.

**Comment by P403n1x87** [comment]
Thanks for reporting back and for the recommendation. I'll see that we improve our documentation around the use of `ddtrace.auto`.

**Comment by brettlangdon** [comment]
@ryan-shaw one consideration with your tracing configuration and adding in `import ddtrace.auto`, `ddtrace.auto` has the same behavior as `ddtrace-run`, which means it will call `patch_all()`. Since I see you are trying to disable `psycopg` integration you will want to use the env var [DD_PATCH_MODULES](https://ddtrace.readthedocs.io/en/stable/configuration.html#DD_PATCH_MODULES) instead (e.g. `DD_PATCH_MODULES=psycopg:false`.

The same goes for your django integration configuration, those configuration options are used only when we initial patch django, so you'll want to configure them via env vars to ensure they are available for `ddtrace.auto`.

Here is an example change that could work for you.


```
DD_PATCH_MODULES=psycopg:false
DD_DJANGO_CACHE_SERVICE_NAME=my-cache
DD_DJANGO_INSTRUMENT_CACHES=true
DD_DJANGO_INSTRUMENT_DATABASES=true
DD_TAGS=my:tag,key:value
```

```python
import ddtrace.auto
from ddtrace import tracer

tracer.configure(
    # If you are able to set this via env var always it would be much better, some
    # other products will also use `DD_AGENT_HOST` to figure out how to talk to
    # the agent, where this will only configure tracing
    hostname=os.environ.get("DD_AGENT_HOST", "172.17.0.1"),
)

# I added the DD_TAGS env var since that will ensure other products can pick up on
# your global tags (dogstatsd for example), but what you have with `set_tags()` is fine
# tracer.set_tags(...)
```

I hope this helps!

**Comment by ryan-shaw** [comment]
Unfortunately I had to fall back to using the programatic approach as we our settings come through a yaml file that is parsed before the `tracer.configure` line so we use custom extracts to get the settings, although this could probably be rewritten in the future to expose environment variables instead 🤔  thanks for the help!
