### ISSUE TITLE
aws lambda support

### ISSUE THREAD

**Issue by AlJohri** [DataDog/dd-trace-py#639]
does dd-trace (and APM more generally) work with aws lambda? there's no agent available in this setting so I wasn't sure if it had an option to send the data using the datadog api

**Comment by brettlangdon** [comment]
hey @AlJohri thank you for reaching out!

Unfortunately we do not support AWS lambda at this time. It is on our roadmap, but we do not have an ETA at this time.

Please let me know if you have any other questions.

**Comment by digitalfiz** [comment]
Can this be reopened as a feature request instead of just closed or should a new issue be opened to request this feature? With the growth of lambda usage I imagine this is becoming more and more of a problem.

**Comment by brettlangdon** [comment]
@digitalfiz sure, I probably should have just left this open in the first place.

**Comment by brettlangdon** [comment]
https://www.datadoghq.com/blog/datadog-for-serverless/
