### ISSUE TITLE
docs: contributing page has broken links to release notes and versioning page.

### ISSUE THREAD

**Issue by romainkomorndatadog** [DataDog/dd-trace-py#6411]
### Summary of problem

The "contributing" documentation page links to release notes cause 404 because the URLs are `.html` , not `.rst`. 

### Which version of dd-trace-py are you using?
N/A

### Which version of pip are you using?
N/A

### Which libraries and their versions are you using?
N/A

### How can we reproduce your problem?

From https://ddtrace.readthedocs.io/en/stable/contributing.html , 
* [the release notes documentation](https://ddtrace.readthedocs.io/en/stable/releasenotes.rst#Scope)
* [release note](https://ddtrace.readthedocs.io/en/stable/releasenotes.rst)
* [version support policy](https://ddtrace.readthedocs.io/en/stable/versioning.rst#release-versions)

### What is the result that you get?

* https://ddtrace.readthedocs.io/en/stable/releasenotes.rst results in a 404
* https://ddtrace.readthedocs.io/en/stable/releasenotes.rst#Scope results in a 404
* https://ddtrace.readthedocs.io/en/stable/versioning.rst#release-versions results in 404

### What is the result that you expected?

* https://ddtrace.readthedocs.io/en/stable/releasenotes.html
* https://ddtrace.readthedocs.io/en/stable/releasenotes.html#Scope
* https://ddtrace.readthedocs.io/en/stable/versioning.html#release-versions

**Comment by ericlaz** [comment]
Thanks for reporting, this issue should be addressed by [https://github.com/DataDog/dd-trace-py/pull/6420](https://github.com/DataDog/dd-trace-py/pull/6420)
