### ISSUE TITLE
Injecting Libraries - GCR Repository missing v1.16.1 and v1.17.0 versions

### ISSUE THREAD

**Issue by willianvalerio** [DataDog/dd-trace-py#6427]
### Summary of problem

The repository gcr.io/datadoghq/dd-lib-python-init is not being updated with the latest version tags, when the init container tries to download the image we get the following message

`ErrImagePull (rpc error: code = NotFound desc = failed to pull and unpack image "gcr.io/datadoghq/dd-lib-python-init:v1.16.1": failed to resolve reference "gcr.io/datadoghq/dd-lib-python-init:v1.16.1": gcr.io/datadoghq/dd-lib-python-init:v1.16.1: not found)`

The latest version available is the v1.16.0

### Which version of dd-trace-py are you using?

v1.16.1 and v1.17.0

### Which version of pip are you using?

N/A

### Which libraries and their versions are you using?

N/A

### How can we reproduce your problem?

Reach gcr.io/datadoghq/dd-lib-python-init:v1.16.1 or gcr.io/datadoghq/dd-lib-python-init:v1.17.0

### What is the result that you get?

`ErrImagePull (rpc error: code = NotFound desc = failed to pull and unpack image "gcr.io/datadoghq/dd-lib-python-init:v1.16.1": failed to resolve reference "gcr.io/datadoghq/dd-lib-python-init:v1.16.1": gcr.io/datadoghq/dd-lib-python-init:v1.16.1: not found)
`
### What is the result that you expected?

Get the image with the latest version tag

**Comment by Yun-Kim** [comment]
Hi @willianvalerio, thanks for reaching out!

Could you try again and let me know if this issue is resolved for you?

**Comment by willianvalerio** [comment]
Hi @Yun-Kim it is working now! 

Thank you!

**Comment by asfaltboy** [comment]
@Yun-Kim we are getting this again with 1.18.2:

>  rpc error: code = NotFound desc = failed to pull and unpack image
>   "gcr.io/datadoghq/dd-lib-python-init:v1.18.2": failed to resolve
>   reference "gcr.io/datadoghq/dd-lib-python-init:v1.18.2":
>   gcr.io/datadoghq/dd-lib-python-init:v1.18.2: not found
