### ISSUE TITLE
[django] Jinja2 templates rendering is not traced

### ISSUE THREAD

**Issue by mgu** [DataDog/dd-trace-py#648]
the current contrib only trace `django.template.base.Template` so if we are using the jinja2 engine we don't have the rendering in our traces.

I could try to add this but I have a question on how it can be done : 
- trace `django.template.backends.jinja2.Template.render`
- trace `jinja2.environment.Template.render` in the django contrib
- add a new jinja2 contrib (and trace at least jinja2.environment.Template.render)

**Comment by brettlangdon** [comment]
@mgu thank you for bringing to our attention!

I think having a stand alone `jinja2` integration is probably a good idea. I am sure more than a few people use `jinja2` on it's own and would love an out of the box way to configure tracing for it.

If this is something you are interested in writing, please do not hesitate to ask questions!

**Comment by mgu** [comment]
I'll try to write it :)

**Comment by brettlangdon** [comment]
Thanks @mgu !!!!

An integration you can look to as a simple example would be the `redis` integration. I assume that the `jinja2` one would be similar.

[redis/__init__.py](https://github.com/DataDog/dd-trace-py/blob/87b9ff74509fab917c7341f34ffabbbf14b74578/ddtrace/contrib/redis/__init__.py)
[redis/patch.py](https://github.com/DataDog/dd-trace-py/blob/87b9ff74509fab917c7341f34ffabbbf14b74578/ddtrace/contrib/redis/patch.py)

You can ignore the `redis/tracers.py` file, that is from an old way we were doing patching.

As always, please reach out if you have any questions at all.

**Comment by Kyle-Verhoog** [comment]
@mgu looking good!

We use the `Pin` api to handle configuring the tracing: 
https://github.com/DataDog/dd-trace-py/blob/87b9ff74509fab917c7341f34ffabbbf14b74578/ddtrace/contrib/redis/patch.py#L28

https://github.com/DataDog/dd-trace-py/blob/87b9ff74509fab917c7341f34ffabbbf14b74578/ddtrace/contrib/redis/patch.py#L44-L48

feel free to open a PR with your work, we'd be happy to review it! 😄

**Comment by mgu** [comment]
I just don't know what I should pin and what to do if a don't want to define a new service ;)
I'll open a PR for the comments :)

**Comment by mgu** [comment]
https://github.com/DataDog/dd-trace-py/pull/649

**Comment by brettlangdon** [comment]
aw yeah... we can close this, fixed by @mgu in #649 🎉
