### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'callbacks'

### ISSUE THREAD

**Issue by pravindahal** [DataDog/dd-trace-py#6659]
### Summary of problem

The following issue is occurring frequently after we upgraded `ddtrace` to `1.17.3`. We see the same with `1.18.0`:

```python
AttributeError: 'NoneType' object has no attribute 'callbacks'
  File "starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "ddtrace/contrib/asgi/middleware.py", line 142, in __call__
    with _asm_request_context.asm_request_context_manager(ip, headers):
  File "contextlib.py", line 142, in __exit__
    next(self.gen)
  File "ddtrace/appsec/_asm_request_context.py", line 326, in asm_request_context_manager
    _on_context_ended(resources)
  File "ddtrace/appsec/_asm_request_context.py", line 339, in _on_context_ended
    resources.finalise()
  File "ddtrace/appsec/_asm_request_context.py", line 125, in finalise
    callbacks = GLOBAL_CALLBACKS.get(_CONTEXT_CALL, []) + env.callbacks.get(_CONTEXT_CALL)
```

### Which version of dd-trace-py are you using?
`1.17.3` and `1.18.0`

### Which version of pip are you using?
Not using pip, using poetry 1.5.1.

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
<html>
<body>

anyio | 3.7.1
asyncache | 0.3.1
asyncpg | 0.27.0
attrs | 23.1.0
azure-ad-verify-token | 0.4.0
azure-common | 1.1.28
azure-core | 1.29.1
azure-identity | 1.14.0
azure-keyvault-secrets | 4.7.0
bytecode | 0.14.2
cachetools | 5.3.1
cattrs | 23.1.2
certifi | 2023.7.22
cffi | 1.15.1
charset-normalizer | 3.2.0
click | 8.1.6
cryptography | 41.0.3
ddsketch | 2.0.4
ddtrace | 1.18.0
deprecated | 1.2.14
docopt | 0.6.2
envier | 0.4.0
et-xmlfile | 1.1.0
exceptiongroup | 1.1.2
fastapi | 0.96.1
greenlet | 2.0.2
gunicorn | 20.1.0
h11 | 0.14.0
httptools | 0.6.0
idna | 3.4
importlib-metadata | 6.8.0
isodate | 0.6.1
jdcal | 1.4.1
msal | 1.23.0
msal-extensions | 1.0.0
numpy | 1.25.2
openpyxl | 2.4.11
opentelemetry-api | 1.19.0
orjson | 3.9.4
pandas | 1.5.3
pip | 23.2.1
portalocker | 2.7.0
protobuf | 4.24.0
psycopg2 | 2.9.7
pycparser | 2.21
pydantic | 1.10.12
pyjwt | 2.8.0
python-dateutil | 2.8.2
python-dotenv | 1.0.0
pytz | 2023.3
pyyaml | 6.0.1
records | 0.5.3
requests | 2.31.0
sentry-sdk | 1.29.2
setuptools | 68.0.0
six | 1.16.0
sniffio | 1.3.0
sqlalchemy | 2.0.19
starlette | 0.27.0
tablib | 3.5.0
tomlkit | 0.11.8
typing_extensions | 4.7.1
urllib3 | 2.0.4
uvicorn | 0.22.0
uvloop | 0.17.0
watchfiles | 0.19.0
websockets | 11.0.3
wheel | 0.41.1
wrapt | 1.15.0
xmltodict | 0.13.0
zipp | 3.16.2

</body>
</html>
</details>

### How can we reproduce your problem?

Unsure.

### What is the result that you get?

The exception above.

### What is the result that you expected?

No exceptions.

**Comment by emmettbutler** [comment]
Thank you for reporting this issue, @pravindahal. I'm having a hard time understanding the traceback you provided. Could you please share the text of the exception message?

**Comment by pravindahal** [comment]
@emmettbutler Sorry, I copied formatted stacktrace. I have updated the post with raw stacktrace.

**Comment by emmettbutler** [comment]
@pravindahal if you're able, could you try reproducing the bug with [this change](https://github.com/DataDog/dd-trace-py/pull/6669) and let me know what the result is?

**Comment by pravindahal** [comment]
@emmettbutler I have deployed our app with the ddtrace from that branch to our dev environment. From the limited testing on that environment, the error doesn't seem to occur anymore. So, I think that change should fix the issue.

**Comment by pravindahal** [comment]
@emmettbutler Please ignore my previous message. I still get this exception with that version:

```python
TypeError: 'NoneType' object is not iterable
  File "starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "ddtrace/contrib/asgi/middleware.py", line 142, in __call__
    with _asm_request_context.asm_request_context_manager(ip, headers):
  File "contextlib.py", line 142, in __exit__
    next(self.gen)
  File "ddtrace/appsec/_asm_request_context.py", line 338, in asm_request_context_manager
    _end_context(resources)
  File "ddtrace/appsec/_asm_request_context.py", line 367, in _end_context
    resources.finalise()
  File "ddtrace/appsec/_asm_request_context.py", line 136, in finalise
    callbacks += env.callbacks.get(_CONTEXT_CALL)
```

**Comment by majorgreys** [comment]
@pravindahal Can you elaborate on when exactly you are seeing this error occur? Is it with each request, at initialization, or when the application is getting redeployed or restarted?

**Comment by sebastianreh** [comment]
Hi! I'm having the same issue happening to me. Is there any chance that you merge that branch and fix it?

**Comment by emmettbutler** [comment]
The fix has been merged! Please comment here if the issue reoccurs.
