### ISSUE TITLE
pytest stop working, cannot import ddup module

### ISSUE THREAD

**Issue by joke2k** [DataDog/dd-trace-py#6708]
### Summary of problem

I'm trying to upgrade from version 1.15.1 to 1.18.0, but after installing the new version my tests with pytest are failing with this error:
```
from ddtrace.internal.datadog.profiling import ddup
E   ImportError: cannot import name 'ddup' from 'ddtrace.internal.datadog.profiling' (/workspace/my-app/venv/lib/python3.11/site-packages/ddtrace/internal/datadog/profiling/__init__.py)
```

### Which version of dd-trace-py are you using?

1.18.0

### Which version of pip are you using?

23.0.1

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
alembic==1.11.3
attrs==23.1.0
Babel==2.12.1
black==22.12.0
boto3==1.28.30
botocore==1.31.30
bytecode==0.14.2
cachetools==5.3.1
cattrs==23.1.2
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.7
coverage==7.3.0
cryptography==41.0.3
ddsketch==2.0.4
ddtrace==1.18.0
Deprecated==1.2.14
envier==0.4.0
et-xmlfile==1.1.0
Faker==17.6.0
google-auth==2.22.0
google-auth-oauthlib==1.0.0
greenlet==2.0.2
gspread==5.10.0
gspread-dataframe==3.3.1
idna==3.4
importlib-metadata==6.8.0
iniconfig==2.0.0
Jinja2==3.1.2
jmespath==1.0.1
jsonschema==4.19.0
jsonschema-specifications==2023.7.1
Mako==1.2.4
MarkupSafe==2.1.3
memory-profiler==0.61.0
more-itertools==9.1.0
moto==2.3.2
mypy-extensions==1.0.0
mysql-connector-python==8.1.0
numpy==1.25.2
oauthlib==3.2.2
openpyxl==3.1.2
opentelemetry-api==1.19.0
packaging==23.1
pandas==1.5.3
pathspec==0.11.2
pika==1.3.2
platformdirs==3.10.0
pluggy==1.2.0
protobuf==4.21.12
psutil==5.9.5
psycopg2-binary==2.9.7
pyaml-env==1.2.1
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
pydantic==1.10.12
pytest==7.4.0
pytest-env==0.8.2
python-dateutil==2.8.2
python-json-logger==2.0.7
pytz==2023.3
PyYAML==6.0.1
referencing==0.30.2
reporting-database-manager-tillo==2.8.0
reporting-job-status-updates-tillo==1.4.9
reporting-types-tillo==1.20.0
requests==2.31.0
requests-oauthlib==1.3.1
responses==0.23.3
rpds-py==0.9.2
rsa==4.9
s3transfer==0.6.2
service-errors-tillo==1.9.2
service-logging-tillo==2.0.0
simplejson==3.19.1
six==1.16.0
SQLAlchemy==1.4.49
SQLAlchemy-Utils==0.41.1
types-PyYAML==6.0.12.11
typing_extensions==4.7.1
urllib3==1.26.16
watchdog==2.3.1
Werkzeug==2.3.7
wrapt==1.15.0
XlsxWriter==3.1.2
xmltodict==0.13.0
zipp==3.16.2
</details>

### How can we reproduce your problem?

My module just trying to import the Profiler:
```
from ddtrace.profiling import Profiler
```

### What is the result that you get?

```

../myapp/runner.py:11: in <module>
    from ddtrace.profiling import Profiler
../venv/lib/python3.11/site-packages/ddtrace/internal/module.py:220: in _exec_module
    self.loader.exec_module(module)
../venv/lib/python3.11/site-packages/_pytest/assertion/rewrite.py:178: in exec_module
    exec(co, module.__dict__)
../venv/lib/python3.11/site-packages/ddtrace/profiling/__init__.py:5: in <module>
    from .profiler import Profiler  # noqa:F401
../venv/lib/python3.11/site-packages/ddtrace/internal/module.py:220: in _exec_module
    self.loader.exec_module(module)
../venv/lib/python3.11/site-packages/_pytest/assertion/rewrite.py:178: in exec_module
    exec(co, module.__dict__)
../venv/lib/python3.11/site-packages/ddtrace/profiling/profiler.py:19: in <module>
    from ddtrace.internal.datadog.profiling import ddup
E   ImportError: cannot import name 'ddup' from 'ddtrace.internal.datadog.profiling' (/workspace/myapp/venv/lib/python3.11/site-packages/ddtrace/internal/datadog/profiling/__init__.py)

```

### What is the result that you expected?

To work as the version 1.15, 1.16 and 1.17.

**Comment by P403n1x87** [comment]
I believe #6529 is the fix for this issue. We will backport it. cc @sanchda

**Comment by sanchda** [comment]
That's right.  #6670 is the backport, which was merged.  I just need to cut a new release.  Will do that ASAP.

**Comment by P403n1x87** [comment]
> That's right. #6670 is the backport, which was merged. I just need to cut a new release. Will do that ASAP.

Ah right. Somehow I couldn't spot that! 🤦 So only the release needed to get the fix out.

**Comment by joke2k** [comment]
Thank you guys @sanchda @P403n1x87
