### ISSUE TITLE
flask error tracking support

### ISSUE THREAD

**Issue by jbrantly** [DataDog/dd-trace-py#6709]
### Summary of problem

When using the Flask integration, errors are not reported in Error Tracking. I believe this is because they are not attached to the service entry span (`flask.request`). See screenshot where the lower spans do have the exception, but the primary span does not.

![image](https://github.com/DataDog/dd-trace-py/assets/196944/476ada1d-e40f-4b6f-b99c-0142b589dde0)

Note that the primary span is marked as an error I believe due the status code being 500. However, if I look at the Errors tab for the trace, I see this for the primary span:

![image](https://github.com/DataDog/dd-trace-py/assets/196944/b05d3226-c0e9-4e36-ac52-f2fb806fa080)

### Which version of dd-trace-py are you using?

1.18

### Which version of pip are you using?

21.1.3

### Which libraries and their versions are you using?

Note that we are running under uWSGI

<details>
  <summary>`pip freeze`</summary>
aiohttp==3.8.5
aiosignal==1.3.1
aniso8601==9.0.1
async-timeout==4.0.3
attrs==23.1.0
blinker==1.6.2
boto3==1.28.3
botocore==1.31.30
bytecode==0.14.2
cattrs==23.1.2
certifi==2023.7.22
charset-normalizer==3.2.0
click==8.1.7
ddsketch==2.0.4
ddtrace==1.18.0
Deprecated==1.2.14
envier==0.4.0
exceptiongroup==1.1.3
Flask==2.3.2
Flask-Cors==4.0.0
Flask-Jsonpify==1.5.0
Flask-RESTful==0.3.10
frozenlist==1.4.0
idna==3.4
importlib-metadata==6.8.0
itsdangerous==2.1.2
Jinja2==3.1.2
jmespath==1.0.1
MarkupSafe==2.1.3
multidict==6.0.4
numpy==1.21.2
openai==0.27.8
opentelemetry-api==1.19.0
pandas==1.3.2
protobuf==4.24.1
python-dateutil==2.8.2
pytz==2023.3
requests==2.31.0
s3transfer==0.6.2
shapely==2.0.1
six==1.16.0
street-address==0.4.0
tqdm==4.66.1
typing-extensions==4.7.1
urllib3==1.26.16
uWSGI==2.0.22
werkzeug==2.3.7
wrapt==1.15.0
xmltodict==0.13.0
yarl==1.9.2
zipp==3.16.2
</details>

### How can we reproduce your problem?

Run a Flask application with auto instrumentation where a route throws an exception.

### What is the result that you get?

The exception does not show in Error Tracking (even though it does show in Traces)

### What is the result that you expected?

The exception to be tracked in Error Tracking

**Comment by emmettbutler** [comment]
Thank you for reporting this, @jbrantly! At first look it appears to be something we can fix.

**Comment by amarteaux** [comment]
Is there any workaround for this issue ?
