### ISSUE TITLE
DBM / APM integration support for MySQL 

### ISSUE THREAD

**Issue by bepetersn** [DataDog/dd-trace-py#6802]
### Summary of problem

According to this [documentation](https://docs.datadoghq.com/database_monitoring/connect_dbm_and_apm/?tab=go#before-you-begin), Database Monitoring is supported for MySQL, but dd-trace-py does not support MySQL (mysqlclient, etc.). Is there any plan to add support for MySQL? Or, is this documentation out of date and it is supported? I don't see anything about psycopg2 or postgres anywhere in the codebase, yet, around propagation. But I haven't looked too far into it.

### Which version of dd-trace-py are you using?

I'm interested in any version up to the latest.

### What is the result that you expected?

"Connecting APM and DBM injects APM trace identifiers into DBM data collection, which allows for correlation of these two data sources. This enables product features showing database information in the APM product, and APM data in the DBM product."

**Comment by emmettbutler** [comment]
@bepetersn the document you linked appears to be outdated. dd-trace-py has automatic instrumentation for `mysql-connector`, `pymysql`, and `aiomysql` (see [this document](https://github.com/DataDog/dd-trace-py/blob/2.x/docs/index.rst)).

The actionable bit on this ticket is to update the documentation [here](https://github.com/DataDog/documentation/blob/2602b8114e79c351d58d0219ea263afae1ad4af3/content/en/database_monitoring/connect_dbm_and_apm.md?plain=1#L54-L55) to reflect current support for mysql client integrations.

**Comment by emmettbutler** [comment]
https://github.com/DataDog/documentation/pull/20464
