### ISSUE TITLE
Library which releases GIL causes python to crash when using ddtrace.Span

### ISSUE THREAD

**Issue by mark-oshea** [DataDog/dd-trace-py#6875]
### Summary of problem

Using a python library which releases the GIL (calling out C/C++ through python bindings) whilst using `ddtrace.Span` the python interpreter crashes as ddtrace is not expecting the GIL to be released. 

### Which version of dd-trace-py are you using?

1.18.4

It looks like this became an issue in ddtrace version 1.5.0 as it does not occur when using ddtrace version 1.4.0

### Which version of pip are you using?

22.2.2

### Which libraries and their versions are you using?

Python 3.10

Pip installs:
```
pip install ddtrace==1.18.4
pip install opentimelineio==0.15.0
```

Pip freeze reports:
```
attrs==23.1.0
bytecode==0.15.0
cattrs==23.1.2
ddsketch==2.0.4
ddtrace==1.18.4
Deprecated==1.2.14
envier==0.4.0
exceptiongroup==1.1.3
importlib-metadata==6.8.0
opentelemetry-api==1.20.0
OpenTimelineIO==0.15.0
protobuf==4.24.3
pyaaf2==1.6.0
six==1.16.0
typing_extensions==4.7.1
wrapt==1.15.0
xmltodict==0.13.0
zipp==3.16.2
```

### How can we reproduce your problem?

Run the following code snippet:

```python
from ddtrace import Span
import opentimelineio as otio

path = "../timeline.xml"

timeline = otio.adapters.read_from_file(path)
```

The file `timeline.xml` can be obtained here:
https://gist.github.com/mark-oshea/40672972bf7b33c00576c70b5351fced

### What is the result that you get?

```
Fatal Python error: PyThreadState_Get: the function must be called with the GIL held, but the GIL is released (the current Python thread state is NULL)
Python runtime state: finalizing (tstate=0x000055ef8feef260)

Aborted
```

### What is the result that you expected?

I expect to get back a `opentimelineio._otio.Timeline` object from the function call `otio.adapters.read_from_file(path)`

The `dir()` of the expected object:
```
['__class__', '__copy__', '__deepcopy__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '_dynamic_fields', 'audio_tracks', 'children_if', 'clip_if', 'clone', 'deepcopy', 'duration', 'each_child', 'each_clip', 'from_json_file', 'from_json_string', 'global_start_time', 'is_equivalent_to', 'is_unknown_schema', 'metadata', 'name', 'range_of_child', 'schema_name', 'schema_version', 'to_json_file', 'to_json_string', 'tracks', 'video_tracks']
```

This does work as expected if I switch ddtrace version to 1.4.0.

**Comment by emmettbutler** [comment]
Thank you for the bug report, @mark-oshea! I managed to replicate the core dump against `v1.18.4`, and then found that it doesn't occur against `v2.3.0` or `v1.20.13`. Please let me know if upgrading to 1.20.13 or later doesn't resolve the issue for you.
