### ISSUE TITLE
Encountering error TypeError: Argument 'filename' has incorrect type

### ISSUE THREAD

**Issue by LukeZeller** [DataDog/dd-trace-py#6892]
### Summary of problem

Encountering the following error on a small but consistent portion of overall volume:

```
TypeError: Argument 'filename' has incorrect type (expected str, got bytes)
  File "ddtrace/profiling/scheduler.py", line 65, in flush
    exp.export(events, start, self._last_export)
  File "ddtrace/profiling/exporter/http.py", line 175, in export
    profile, libs = super(PprofHTTPExporter, self).export(events, start_time_ns, end_time_ns)
  File "ddtrace/profiling/exporter/pprof.pyx", line 672, in ddtrace.profiling.exporter.pprof.PprofExporter.export
    converter.convert_stack_event(
  File "ddtrace/profiling/exporter/pprof.pyx", line 267, in ddtrace.profiling.exporter.pprof._PprofConverter.convert_stack_event
    self._to_locations(frames, nframes),
  File "ddtrace/profiling/exporter/pprof.pyx", line 239, in ddtrace.profiling.exporter.pprof._PprofConverter._to_locations
    self._to_Location(filename, lineno, funcname).id for filename, lineno, funcname, class_name in frames
```

### Which version of dd-trace-py are you using?

1.18.4

### Which version of pip are you using?

Poetry 1.4.2
Pip 23.2.1

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
aiohttp==3.8.5
aiosignal==1.3.1
alembic==1.11.1
anthropic==0.3.6
anyio==4.0.0
appnope==0.1.3
asttokens==2.4.0
async-cache==1.1.1
async-lru==2.0.4
async-timeout==4.0.3
attrs==23.1.0
azure-ai-formrecognizer==3.2.1
azure-common==1.1.28
azure-core==1.29.4
azure-identity==1.13.0
azure-keyvault-secrets==4.7.0
azure-mgmt-cognitiveservices==13.5.0
azure-mgmt-core==1.4.0
azure-storage-blob==12.17.0
backcall==0.2.0
beautifulsoup4==4.12.2
black==23.7.0
-e git+ssh://git@github.com/ramp/applied-ai.git@f5f600ce80edce72f06d865c51900995ab590898#egg=bore&subdirectory=bore
bytecode==0.15.0
cachetools==5.3.1
cattrs==23.1.2
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.7
comm==0.1.4
cryptography==41.0.3
datadog==0.45.0
ddsketch==2.0.4
ddtrace==1.17.2
debugpy==1.7.0
decorator==5.1.1
Deprecated==1.2.14
distro==1.8.0
envier==0.4.0
executing==1.2.0
fastapi==0.95.2
fastapi-restful==0.5.0
fastapi-shell==0.1.3
filelock==3.12.3
frozenlist==1.4.0
fsspec==2023.9.0
greenlet==2.0.2
grpcio==1.58.0
gunicorn==20.1.0
h11==0.14.0
hiredis==2.2.3
httpcore==0.17.3
httpx==0.24.1
huggingface-hub==0.16.4
idna==3.4
importlib-metadata==6.8.0
iniconfig==2.0.0
ipykernel==6.25.0
ipython==8.6.0
isodate==0.6.1
isort==5.12.0
jedi==0.19.0
Jinja2==3.1.2
jmespath==1.0.1
joblib==1.3.2
jsonschema==4.19.0
jsonschema-specifications==2023.7.1
jupyter_client==8.3.1
jupyter_core==5.3.1
Mako==1.2.4
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib-inline==0.1.6
mdurl==0.1.2
mpmath==1.3.0
msal==1.23.0
msal-extensions==1.0.0
msgpack==1.0.5
msrest==0.7.1
multidict==6.0.4
mypy==1.5.1
mypy-extensions==1.0.0
nest-asyncio==1.5.7
networkx==3.1
ninja==1.11.1
nltk==3.8.1
nodeenv==1.8.0
numpy==1.25.2
oauthlib==3.2.2
openai==0.27.8
opentelemetry-api==1.20.0
orjson==3.9.2
packaging==23.1
parso==0.8.3
pathspec==0.11.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.3.0
portalocker==2.7.0
prompt-toolkit==3.0.30
protobuf==4.24.3
psutil==5.9.5
psycopg==3.1.10
psycopg-binary==3.1.10
ptyprocess==0.7.0
pure-eval==0.2.2
pycparser==2.21
pydantic==1.10.12
Pygments==2.16.1
PyJWT==2.8.0
pypdf==3.15.2
pyright==1.1.318
pytest==7.4.2
pytest-asyncio==0.21.1
python-dateutil==2.8.2
python-dotenv==1.0.0
python-json-logger==2.0.7
python-multipart==0.0.6
PyYAML==6.0.1
pyzmq==25.1.1
quickjs==1.19.2
ray==2.6.3
redis==4.6.0
referencing==0.30.2
regex==2023.8.8
requests==2.31.0
requests-oauthlib==1.3.1
rich==13.4.2
rpds-py==0.10.2
safetensors==0.3.3
scikit-learn==1.3.0
scipy==1.9.3
sentence-transformers @ git+https://github.com/UKPLab/sentence-transformers.git@179b659621c680371394d507683b25ba7faa0dd8
sentencepiece==0.1.99
sentry-sdk==1.22.2
setproctitle==1.3.2
six==1.16.0
sniffio==1.3.0
soupsieve==2.5
SQLAlchemy==2.0.20
SQLAlchemy-serializer==1.4.1
stack-data==0.6.2
starlette==0.27.0
structlog==23.1.0
structlog-sentry==2.0.3
sympy==1.12
termcolor==2.3.0
threadpoolctl==3.2.0
tiktoken==0.4.0
tokenizers==0.13.3
torch @ https://download.pytorch.org/whl/cpu/torch-2.0.1-cp311-none-macosx_11_0_arm64.whl
torchvision==0.15.2
tornado==6.3.3
tqdm==4.66.1
traitlets==5.9.0
transformers==4.33.1
typeguard==4.0.1
types-cachetools==5.3.0.6
types-jmespath==1.0.2.7
types-pyOpenSSL==23.2.0.2
types-redis==4.6.0.3
typing_extensions==4.7.1
urllib3==1.26.16
uvicorn==0.22.0
wcwidth==0.2.6
wrapt==1.15.0
xmltodict==0.13.0
yarl==1.9.2
zipp==3.16.2
</details>

### How can we reproduce your problem?

N/A, don't know how to reproduce. Was told to report by this message:
`Unexpected error while exporting events. Please report this bug to https://github.com/DataDog/dd-trace-py/issues`

### What is the result that you get?
N/A
### What is the result that you expected?
N/A

**Comment by LukeZeller** [comment]
Ah missed #6652, thanks - looking forward to the fix!

**Comment by rsb177** [comment]
yeah, getting the same issue.  do we have an ETA?
