### ISSUE TITLE
Python 3.11 - Celery, Gevent, Greenlet appears to be blocked, Blocked stack

### ISSUE THREAD

**Issue by kzap** [DataDog/dd-trace-py#6913]
### Summary of problem
We found when running the exact same Celery worker in a Docker image on a different environment we get Greenlet blocks that seem to indicate that something in dd-trace `ddtrace/internal/periodic.py`

We find this when running Celery with the `gevent` and sending a lot of jobs to it.
- `ddtrace-run celery -A queue_conf worker -c 90 -P gevent --prefetch-multiplier 1`
- `GEVENT_MONITOR_THREAD_ENABLE=true`
- `GEVENT_MAX_BLOCKING_TIME=60`

We run this application in a `python:3.11-slim-bookworm` Docker image.

We think it is causing some of our MongoDB queries to be set with invalid data. This is the monitor thread log:

```
2023-09-13T18:25:39Z : Greenlet <greenlet.greenlet object at 0x7efda27b2240 (otid=0x7efd92d35ad0) suspended active started main> appears to be blocked
Reported by <gevent._gevent_c_tracer.GreenletTracer object at 0x7efd3a8a8bd0>
Blocked Stack (for thread id 0x7efda18fe6c0):
File "/usr/local/lib/python3.11/threading.py", line 995, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/venv/lib/python3.11/site-packages/ddtrace/internal/periodic.py", line 55, in run
    while not self.quit.wait(self.interval):
  File "/usr/local/lib/python3.11/threading.py", line 622, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/local/lib/python3.11/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
```

### Which version of dd-trace-py are you using? 
- `1.18.2`

### Which version of pip are you using?
- `23.2.1`

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>

aiohttp==3.8.5
aiosignal==1.3.1
amqp==5.1.1
async-timeout==4.0.3
attrs==23.1.0
authy==2.2.2
bcrypt==3.2.2
beautifulsoup4==4.12.2
billiard==4.1.0
bleach==4.1.0
bleach-allowlist==1.0.3
blinker==1.6.2
boto==2.49.0
boto3==1.17.105
botocore==1.20.105
bytecode==0.14.2
cachetools==4.0.0
cattrs==23.1.2
celery==5.3.0
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.7
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
contextlib2==21.6.0
cryptography==41.0.3
cssselect==1.2.0
cssutils==2.7.1
datadog==0.45.0
ddsketch==2.0.4
ddtrace==1.18.2
decorator==5.1.1
defusedxml==0.7.1
Deprecated==1.2.14
dnspython==1.16.0
elastic-site-search==2.1.1
elasticsearch==7.13.4
envier==0.4.0
feedfinder2==0.0.4
feedparser==6.0.10
filelock==3.12.3
Flask==2.3.3
Flask-Cors==3.0.9
Flask-JWT-Extended==4.3.1
Flask-Limiter==2.0.4
Flask-Pydantic==0.9.0
frozenlist==1.4.0
gevent==23.7.0
google-api-core==2.11.1
google-auth==2.22.0
google-cloud-core==2.3.3
google-cloud-translate==3.12.0
googleapis-common-protos==1.60.0
greenlet==2.0.2
grpcio==1.57.0
grpcio-status==1.57.0
gunicorn==20.1.0
idna==3.4
ImageHash==4.1.0
importlib-metadata==6.8.0
importlib-resources==6.0.1
itsdangerous==2.1.2
jieba3k==0.35.1
Jinja2==3.1.2
jmespath==0.10.0
joblib==1.3.2
kombu==5.3.1
limits==3.5.0
lxml==4.9.3
Markdown==2.6.11
MarkupSafe==2.1.3
marshmallow==3.20.1
marshmallow-dataclass==8.5.14
marshmallow-mongoengine==0.30.2
mongoengine==0.21.0
multidict==6.0.4
mypy-extensions==1.0.0
ndg-httpsclient==0.5.1
newspaper3k==0.2.8
nltk==3.8.1
numpy==1.25.2
oauthlib==3.1.0
openai==0.27.2
opentelemetry-api==1.19.0
packaging==23.1
phonenumbers==8.13.19
Pillow==9.5.0
pluggy==0.13.1
premailer==3.1.1
prompt-toolkit==3.0.39
proto-plus==1.22.3
protobuf==4.24.2
psycopg2-binary==2.9.7
pusher==3.3.2
pyap==0.1.0
pyasn1==0.5.0
pyasn1-modules==0.3.0
pybreaker==1.0.1
pycparser==2.21
pycryptodome==3.15.0
pydantic==1.9.0
PyJWT==2.7.0
pymongo==3.12.0
PyNaCl==1.5.0
pyOpenSSL==23.2.0
python-dateutil==2.8.2
python-dotenv==0.20.0
python-http-client==3.3.7
python-json-logger==0.1.11
python-Levenshtein==0.12.2
python-redis-lock==3.4.0
pytz==2023.3
PyWavelets==1.4.1
PyYAML==6.0.1
redis==4.5.4
regex==2023.8.8
requests==2.31.0
requests-aws4auth==0.9
requests-file==1.5.1
rsa==4.9
s3transfer==0.4.2
schema==0.7.5
scipy==1.10.0
sendgrid==6.9.6
sentry-sdk==1.25.0
sgmllib3k==1.0.0
simplejson==3.19.1
six==1.16.0
smooch==5.20.0
soupsieve==2.4.1
SQLAlchemy==1.3.3
starkbank-ecdsa==2.2.0
tenacity==6.2.0
tinysegmenter==0.3
tld==0.11.9
tldextract==3.4.4
tqdm==4.66.1
twilio==6.35.1
typing-inspect==0.9.0
typing_extensions==4.7.1
tzdata==2023.3
unicodecsv==0.14.1
Unidecode==1.1.1
urllib3==1.26.13
validators==0.18.2
vine==5.0.0
wcwidth==0.2.6
webencodings==0.5.1
Werkzeug==2.3.7
wrapt==1.15.0
XlsxWriter==3.1.2
xmltodict==0.13.0
yarl==1.9.2
zenpy==2.0.25
zipp==3.16.2
zope.event==5.0
zope.interface==6.0
</details>

### How can we reproduce your problem?
We only replicate when we run on our newer environment which is the following:
<details>
  <summary>New Environment</summary>

- Instance Types: c5, c6
- k8s v1.25.12
- Amazon Linux 2
- Kernel 5.10.186-179.751.amzn2.x86_64
- Containerd 1.6.19
</details>

<details>
  <summary>Old Environment</summary>

- Instance Types: m5
- k8s 1.20.10
- Ubuntu 20.04.4 LTS
- Kernel 5.13.0-1023-aws
- Docker 19.3.15
</details>

### What is the result that you get?
The monitor thread reports blocks every 60seconds right away

### What is the result that you expected?
In our old environment the worker runs fine and works as expected and the monitor thread reports nothing.

- Seems that full Celery support in 3.11 is not yet done: https://github.com/DataDog/dd-trace-py/pull/6389

**Comment by kzap** [comment]
Though maybe this a red herring as I can find some logs similar to this back when we were running Python 3.9

```
File "/usr/local/lib/python3.9/threading.py", line 937, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/venv/lib/python3.9/site-packages/ddtrace/internal/periodic.py", line 55, in run
    while not self.quit.wait(self.interval):
  File "/usr/local/lib/python3.9/threading.py", line 581, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/local/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
```

**Comment by P403n1x87** [comment]
Thanks for reporting this @kzap. Does this actually cause any issues to your application? After a first look into the greenlet tracer https://github.com/gevent/gevent/blob/b4aa4a4e660eb88c72d03c61cc12f3e2e4f9b0d9/src/gevent/_tracer.py#L71, I believe this is only a log message that should not cause any harm to the application. I believe this happens because somehow this gevent tracer decides to monitor the ddtrace threads, which are not greenlets, and sees them as blocked on a stdlib lock, but I would have to look deeper into it to ascertain that this is indeed the case. If so, we could look for a way to prevent this "noise" in logs from our end.

**Comment by ZStriker19** [comment]
Hi @kzap thanks for reaching out. Do you happen to have an app you could share that recreates the issue?

**Comment by kzap** [comment]
None for now, closing this as its hard to recreate
if its true that the gevent tracer decides to monitor ddtrace threads as a mistake it would be nice to fix that as it would help us discover what is really blocking this.
