### ISSUE TITLE
importing ddtrace causes an exception atexit when working with flask and gevent

### ISSUE THREAD

**Issue by dsimidzija** [DataDog/dd-trace-py#6923]
### Summary of problem

The act of importing `ddtrace` causes a `gevent` error on python shutdown when trying to use Flask CLI (but can also be reproduced without using the CLI explicitly, see below).

### Which version of dd-trace-py are you using?

`1.18.5`

### Which version of pip are you using?

`pip 23.2`

### Which libraries and their versions are you using?

The libraries listed are the result of running `pip install flask gevent ddtrace`.

<details>
  <summary>`pip freeze`</summary>

> attrs==23.1.0
> blinker==1.6.2
> bytecode==0.15.0
> cattrs==23.1.2
> click==8.1.7
> ddsketch==2.0.4
> ddtrace==1.18.5
> Deprecated==1.2.14
> envier==0.4.0
> Flask==2.3.3
> gevent==23.9.1
> greenlet==3.0.0rc3
> importlib-metadata==6.8.0
> itsdangerous==2.1.2
> Jinja2==3.1.2
> MarkupSafe==2.1.3
> opentelemetry-api==1.20.0
> protobuf==4.24.3
> six==1.16.0
> typing_extensions==4.7.1
> Werkzeug==2.3.7
> wrapt==1.15.0
> xmltodict==0.13.0
> zipp==3.16.2
> zope.event==5.0
> zope.interface==6.0

</details>

### How can we reproduce your problem?

This is the minimal `app.py` to reproduce the error:

```python
# app.py
from gevent import monkey

monkey.patch_all()

import ddtrace
from flask import Flask

app = Flask("testy")
```
Running `flask --help` will give the error below.

The reason seems to be the fact that flask is imported before `monkey.patch_all()` is called, but _only if `ddtrace` is imported as well_. Removing the `import ddtrace` line removes the exception.

The error is also visible when just importing flask manually before `monkey.patch_all()`:

```python
# oops.py
from gevent import monkey

import flask

monkey.patch_all()

import ddtrace
```

`python oops.py` gives the same error. Importing flask before running `monkey.patch_all()` is a mistake of course, but one that cannot be avoided when running `flask` as CLI directly.

As far as I can tell, this is caused by `ModuleWatchdog.install()` on import, as commenting that line seems to fix the error. Running `ModuleWatchdog.uninstall()` "manually" before shutdown doesn't seem to help.

### What is the result that you get?

This is shown _always_ at shutdown, and it seems it cannot be suppressed:

```
Exception ignored in: <function _removeHandlerRef at 0x7fc252f6fb00>
Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/__init__.py", line 855, in _removeHandlerRef
  File "/usr/lib/python3.11/logging/__init__.py", line 235, in _acquireLock
  File "/usr/lib/python3.11/threading.py", line 164, in acquire
  File "/tmp/testimir/.venv/lib/python3.11/site-packages/gevent/thread.py", line 67, in get_ident
TypeError: 'NoneType' object is not callable
```

### What is the result that you expected?

To not see the error :1st_place_medal:

**Comment by P403n1x87** [comment]
@dsimidzija thanks for the report and for narrowing it down to `ModuleWatchdog`. I have a change that should fix the issue, currently validating in our CI 🤞
