### ISSUE TITLE
Crash caused by GraphQL patch

### ISSUE THREAD

**Issue by werkshy** [DataDog/dd-trace-py#6959]
### Summary of problem

My Python FastAPI app is making a GraphQL call to another service using the `gql` package, which uses graphql-core under the hood. With `ddtrace.patch(graphql=True)`, my code reliably crashes when making this client request, due to what looks like an unchecked None reference in ddtrace. Setting `patch(graphql=False)` fixes the problem.

A partial stack trace of the failure:
```
forms        |   File "/app/lib/python/gql-client/src/gql_client/dsl_client.py", line 83, in execute
forms        |     ] = await session.execute(  # pyright: ignore [reportUnknownMemberType]
forms        |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
forms        |   File "/usr/local/lib/python3.11/site-packages/gql/client.py", line 1220, in execute
forms        |     result = await self._execute(
forms        |              ^^^^^^^^^^^^^^^^^^^^
forms        |   File "/usr/local/lib/python3.11/site-packages/gql/client.py", line 1111, in _execute
forms        |     self.client.validate(document)
forms        |   File "/usr/local/lib/python3.11/site-packages/gql/client.py", line 147, in validate
forms        |     validation_errors = validate(self.schema, document)
forms        |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
forms        |   File "/usr/local/lib/python3.11/site-packages/graphql/validation/validate.py", line 20, in validate
forms        |     schema: GraphQLSchema,
forms        |   File "/usr/local/lib/python3.11/site-packages/ddtrace/contrib/graphql/patch.py", line 142, in _traced_validate
forms        |     source_str = _get_source_str(document)
forms        |                  ^^^^^^^^^^^^^^^^^^^^^^^^^
forms        |   File "/usr/local/lib/python3.11/site-packages/ddtrace/contrib/graphql/patch.py", line 287, in _get_source_str
forms        |     source_str = obj.loc.source.body
forms        |                  ^^^^^^^^^^^^^^
forms        | AttributeError: 'NoneType' object has no attribute 'source'
```

And this is the code that is crashing
https://github.com/DataDog/dd-trace-py/blob/2.x/ddtrace/contrib/graphql/patch.py#L286-L287
```python
    elif isinstance(obj, Document):
        source_str = obj.loc.source.body
```

We can see in graphql-core that DocumentNode.loc is optional: https://github.com/graphql-python/graphql-core/blob/main/src/graphql/language/ast.py#L347
```python
class Node:
    """AST nodes"""

    # allow custom attributes and weak references (not used internally)
    __slots__ = "__dict__", "__weakref__", "loc", "_hash"

    loc: Optional[Location]
```

### Which version of dd-trace-py are you using?

ddtrace 1.20.0

### Which version of pip are you using?

poetry 1.6.1

### Which libraries and their versions are you using?

gql 3.4.1
graphql-core 3.2.3
fastapi-0.103

### How can we reproduce your problem?

I don't have a small reproducible test case, sorry.

### What is the result that you get?

Crash with " 'NoneType' object has no attribute 'source'"

### What is the result that you expected?

Code doesn't crash, gql client request succeeds.

**Comment by mabdinur** [comment]
Thanks for opening this issue. We missed this edge case in our implementation. 

By default the [graphql.parse(....)](https://github.com/graphql-python/graphql-core/blob/main/src/graphql/language/parser.py#L86) is called with `no_location=False`.  However the `gqlclient` library can create graphql DocumentNode where [no_location=True](https://github.com/graphql-python/graphql-core/blob/v3.2.3/src/graphql/language/parser.py#L109). 

PR6960 should address this issue.
