### ISSUE TITLE
pkg_resources is deprecated as an API

### ISSUE THREAD

**Issue by sodul** [DataDog/dd-trace-py#6966]
### Summary of problem

We are seeing deprecation warnings when loading the ddtrace library.

### Which version of dd-trace-py are you using?

This happens with ddtrace==1.18.4 and the latest 1.20.1.

### Which version of pip are you using?

Python 3.11.5 and pip 23.2.1.

### Which libraries and their versions are you using?

Not relevant.

### How can we reproduce your problem?

Import and use the ddtrace library.

### What is the result that you get?

```
.pyenv/versions/3.11.5/lib/python3.11/site-packages/ddtrace/internal/module.py:220
.pyenv/versions/3.11.5/lib/python3.11/site-packages/ddtrace/internal/module.py:220: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    self.loader.exec_module(module)
```

### What is the result that you expected?

No warning.

**Comment by bennettandrews** [comment]
Also running into this with `ddtrace-2.0.2` and python 3.11.5
