### ISSUE TITLE
New signal handling code is problematic

### ISSUE THREAD

**Issue by hauntsaninja** [DataDog/dd-trace-py#7014]
The signal handling code introduced in https://github.com/DataDog/dd-trace-py/pull/6588 is problematic.

It causes `ValueError: signal only works in main thread of the main interpreter`.

I also saw it cause:
```
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/ddtrace/__init__.py", line 42, in <module>
    tracer = Tracer()
             ^^^^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/ddtrace/tracer.py", line 300, in __init__
    register_on_exit_signal(self._atexit)
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/ddtrace/internal/atexit.py", line 70, in register_on_exit_signal
    signals.handle_signal(signal.SIGINT, handle_exit)
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/ddtrace/internal/utils/signals.py", line 27, in handle_signal
    return signal.signal(sig, wrap_signals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Can't set signal handler for SIGINT while SIGINT is being deferred within a DeferSigint context.
```

Fixed by downgrading dd-trace-py, 1.18.2 is known to be fine.

Apologies, don't have time to make a minimal repro, but happens in large multithreaded app with some imports that effectively get deferred

**Comment by johnnymetz** [comment]
I'm also experiencing this error

**Comment by hvtuananh** [comment]
Me too, from the stack trace it seems the `register_on_exit_signal` function can only be called in the main thread.

**Comment by emmettbutler** [comment]
Thank you for the bug report, and apologies for the delay. We'll look into it.

cc @piochelepiotr

**Comment by tabgok** [comment]
I am investigating this now

**Comment by tabgok** [comment]
https://github.com/DataDog/dd-trace-py/pull/7204 is set to address this issue

**Comment by hauntsaninja** [comment]
This will still interact badly with things like https://github.com/ray-project/ray/blob/4b0aa5293ad0ee7aab08e1b1bb560a7c359976a1/python/ray/_private/utils.py#L1982. Would it be possible to have a way to not register the signal handler at all?

**Comment by tabgok** [comment]
Thanks hauntsaninja - just to double check, your concern is something like the following will fail, correct?

```
with DeferSigInt():
    import ddtrace
```

**Comment by emmettbutler** [comment]
I believe https://github.com/DataDog/dd-trace-py/pull/7578 fixes this issue.
