### ISSUE TITLE
UnboundLocalError when Redis commands time out

### ISSUE THREAD

**Issue by tonycosentini** [DataDog/dd-trace-py#7084]
### Summary of problem

Running a Redis command like this that results in a TimeoutError:
```
client.hget('some_keys', 'some_fields')
```

Results in this crash:
```
UnboundLocalError cannot access local variable 'result' where it is not associated with a value
```

### Which version of dd-trace-py are you using?

1.20.1

### Which version of pip are you using?

pip 23.2.1 from /opt/app-root/lib64/python3.11/site-packages/pip (python 3.11)

### Which libraries and their versions are you using?

redis==4.5.4

### How can we reproduce your problem?

Running a Redis command with a timeout should repro it.

### What is the result that you get?

It crashes with an UnboundLocalError within ddtrace.

### What is the result that you expected?

It should crash with a TimeoutError

**Comment by ethervoid** [comment]
Trace from our sentry system

![image](https://github.com/DataDog/dd-trace-py/assets/741240/d8a3be80-4c97-456d-9fbe-9758f32e2b79)

**Comment by emmettbutler** [comment]
Thanks for the report! I believe this was fixed in https://github.com/DataDog/dd-trace-py/releases/tag/v1.20.2 . Could you try replicating the issue with that version of ddtrace?

**Comment by tonycosentini** [comment]
Hi, upgrading fixed it - apologizes for not realizing this was already addressed.
