### ISSUE TITLE
Profiler passes incorrect type when creating Rust profile object

### ISSUE THREAD

**Issue by danielsn** [DataDog/dd-trace-py#7100]
### Summary of problem

When we create a Profiler object, we have the following signature on the rust side

```rust
pub unsafe extern "C" fn ddog_prof_Profile_new(
    sample_types: Slice<ValueType>,
    period: Option<&Period>,
    start_time: Option<&Timespec>,
) -> ProfileNewResult {
```
https://github.com/DataDog/libdatadog/blob/main/profiling-ffi/src/profiles.rs#L348-L351

But, on the C++ side, we make the following calls
```C++
    ddog_prof_Period default_sampler = { samplers[0], 1 }; // Mandated by pprof, but probably unused
    ddog_profile = ddog_prof_Profile_new({ &samplers[0], samplers.size() }, &default_sampler, nullptr);
```
https://github.com/DataDog/dd-trace-py/blob/2.x/ddtrace/internal/datadog/profiling/src/exporter.cpp#L318-L319
The types are not the same, meaning that the `Period` we get on the Rust side may have arbitrary data in it.

### Which version of dd-trace-py are you using?
NA

### Which version of pip are you using?
NA

### Which libraries and their versions are you using?

NA

**Comment by sanchda** [comment]
Oh, forgot to mention that this was fixed in #8416.
