### ISSUE TITLE
dd-trace-py + pyodbc (mssql): missing spans

### ISSUE THREAD

**Issue by robertomonteromiguel** [DataDog/dd-trace-py#7104]
### Summary of problem

I have a python application connected to mssql server using pyodbc.

I realized that in the generated dd traces I can't find some important spans. For example: db.system or db.type, db.user, db.operation.

It seems that when I connect my application to other DB like postgres or mysql the spans are generate well 

### Which version of dd-trace-py are you using?

My environment:
- python 3.9
- flask 2.2.4
- dd-trace-py 1.20.2

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
  
</details>

**Comment by emmettbutler** [comment]
Thank you for the issue report! Do I understand correctly that you're looking for the following span tags and not finding them?

* `db.system`
* `db.type`
* `db.user`
* `db.operation`

If so, this will make sense as a feature request in our team's backlog.

**Comment by robertomonteromiguel** [comment]
> Thank you for the issue report! Do I understand correctly that you're looking for the following span tags and not finding them?
> 
> * `db.system`
> * `db.type`
> * `db.user`
> * `db.operation`
> 
> If so, this will make sense as a feature request in our team's backlog.

Yes, I'm looking for these spans. Thanks!

**Comment by emmettbutler** [comment]
@robertomonteromiguel does this change fix the issue you're seeing? https://github.com/DataDog/dd-trace-py/pull/7131

**Comment by cbeauchesne** [comment]
Hi @emmettbutler ,

I still seee issues here, I've reported them to https://datadoghq.atlassian.net/browse/APMAPI-741
