### ISSUE TITLE
Is it possible to relax the `psutil` dependency in 2.0.0 to prevent dependency version conflicts?

### ISSUE THREAD

**Issue by kkom** [DataDog/dd-trace-py#7142]
### Which version of dd-trace-py are you using?

2.0.0

### Which version of pip are you using?

Poetry 1.6.1

### Which libraries and their versions are you using?

```
taskipy==1.12.0
```

### How can we reproduce your problem?

Try to install `ddtrace==2.0.0` and `taskipy==1.12.0` in a single Poetry virtual environment

### What is the result that you get?

```
Because ddtrace (2.0.0) depends on psutil (5.6.7)
 and taskipy (1.12.0) depends on psutil (>=5.7.2,<6.0.0), ddtrace (2.0.0) is incompatible with taskipy (1.12.0).
```

### What is the result that you expected?

Installation succeeds, because ddtrace supports a wider range of versions of the psutil dependency:

https://github.com/DataDog/dd-trace-py/blob/e54c6efdc966468d398c1f18fdcef2b09e8ab82c/pyproject.toml#L33

(at least something equal to or newer than `5.7.2`)

**Comment by deMarigny-ZEFR** [comment]
+1 to loosening it... ill add that i don't think psutil 5.6.7 has a wheel prebuilt for Python 3.11, so im getting issues installing ddtrace now unless i install python dev headers.

It seems this is new too, it used to be relaxed... https://github.com/DataDog/dd-trace-py/commit/5d94749903adc48d8a890849a1494ad28cd9bc40#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L45
