### ISSUE TITLE
Kafka Protobuf Consumer - No such configuration property: "value.deserializer"

### ISSUE THREAD

**Issue by gautam-goudar** [DataDog/dd-trace-py#7174]
### Summary of problem
Our Kafka application is not able to create a Kafka consumer using protobuf de-serialization and results in the below error
```
KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "value.deserializer""}
```

The Kafka consumer code works just fine with versions <= "1.17.3" of ddtrace or no ddtrace packages at all.

### Which version of dd-trace-py are you using?
>= 1.20.2 

### Which version of pip are you using?
Python 3.11.4

### Which libraries and their versions are you using?
confluent-kafka = "^2.1.0"
protobuf = "^4.22.3"

<details>
  <summary>`pip freeze`</summary>
  
</details>

### How can we reproduce your problem?
By using the confluent kafka consumer and subscribing to a topic which has messages serialized in protobuf format. 

### What is the result that you get?
No such configuration property: "value.deserializer"

### What is the result that you expected?
The consumer should get created and must be able to read messages from the topic

**Comment by emmettbutler** [comment]
Thank you for the issue report, @gautam-goudar.

At first glance it seems possible this is related to @piochelepiotr's pull request #6711.
