### ISSUE TITLE
The type signature of `set_tags` appears to be wrong

### ISSUE THREAD

**Issue by jfly** [DataDog/dd-trace-py#7175]
### Summary of problem

The type signature of `set_tags` seems to be incorrect. It says [the function takes a `_MetaDictType`](https://github.com/DataDog/dd-trace-py/blob/v2.0.1/ddtrace/span.py#L405), but that restricts the values to `typing.Text`, yet [`set_tag` allows values to be `typing.Any`](https://github.com/DataDog/dd-trace-py/blob/v2.0.1/ddtrace/span.py#L290-L291C18).

As a result, mypy isn't happy with the code I've written. I don't think it's safe for me to stringify all my values before passing them to `set_tags` (I see logic down in `set_tag` that looks at [the types of values](https://github.com/DataDog/dd-trace-py/blob/v2.0.1/ddtrace/span.py#L331)).

### Which version of dd-trace-py are you using?

v2.0.1

### Which version of pip are you using?

23.0.1

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>

```
attrs==23.1.0
bytecode==0.15.0
cattrs==23.1.2
ddsketch==2.0.4
ddtrace==2.0.1
Deprecated==1.2.14
envier==0.4.0
exceptiongroup==1.1.3
importlib-metadata==6.8.0
mypy==1.5.1
mypy-extensions==1.0.0
opentelemetry-api==1.20.0
protobuf==4.24.4
psutil==5.9.5
six==1.16.0
tomli==2.0.1
typing_extensions==4.8.0
wrapt==1.15.0
xmltodict==0.13.0
zipp==3.17.0
```

</details>

### How can we reproduce your problem?

Install mypy and ddtrace (see exact versions in `pip freeze` above). Create this `demo.py` file and run `mypy` against it:

```
$ cat demo.py
import ddtrace

span = ddtrace.span.Span("my span")
span.set_tags({
    "foo": 42,
})

$ mypy demo.py
demo.py:5: error: Dict entry 0 has incompatible type "str": "int"; expected "str | bytes": "str"  [dict-item]
Found 1 error in 1 file (checked 1 source file)
```

**Comment by emmettbutler** [comment]
Thank you for the report, @jfly. I've opened https://github.com/DataDog/dd-trace-py/pull/7182, which I think mitigates this issue.
