### ISSUE TITLE
Changelog generation seems broken, empty release notes page in documentation

### ISSUE THREAD

**Issue by noirbee** [DataDog/dd-trace-py#7176]
### Summary of problem

`CHANGELOG.md` specifies that starting from v44, « Changelogs are now managed automatically by reno and located at https://ddtrace.readthedocs.io/en/stable/release_notes.html »

Said https://ddtrace.readthedocs.io/en/stable/release_notes.html is empty, save for a similar message pointing to the old release notes in `CHANGELOG.md`.

### Which version of dd-trace-py are you using?

N/A

### Which version of pip are you using?

N/A

### Which libraries and their versions are you using?

N/A

### How can we reproduce your problem?

Go to https://pypi.org/project/ddtrace/ , click on "Changelog" in the "Project links" list.

### What is the result that you get?

Almost empty page at https://ddtrace.readthedocs.io/en/stable/release_notes.html

### What is the result that you expected?

The full changelog from v45+

**Comment by noirbee** [comment]
Forgot to say: this was broken a few minor releases back, I'd say… ~1.17 maybe ?

**Comment by emmettbutler** [comment]
Thank you for reporting this, @noirbee. We'll look into it! In the meantime you can find release notes [here](https://github.com/DataDog/dd-trace-py/releases).

**Comment by emmettbutler** [comment]
1.18.1 appears to be the oldest version with this issue https://ddtrace.readthedocs.io/en/v1.18.1/release_notes.html

**Comment by emmettbutler** [comment]
The `build_docs` CI job succeeds in building the release notes page ([example](https://output.circle-artifacts.com/output/job/7cc6b53d-6667-4313-9881-f61145c5c877/artifacts/0/tmp/docs/_release_notes_all.html)), but the readthedocs build does not.

**Comment by emmettbutler** [comment]
Screenshot of the last patch-release build that had working release notes
<img width="1920" alt="Screenshot 2023-10-05 at 1 25 32 PM" src="https://github.com/DataDog/dd-trace-py/assets/723615/1d30b644-4105-441a-88b5-1af09eb00aa2">

Screenshot of the earliest patch-release build with broken release notes
<img width="1920" alt="Screenshot 2023-10-05 at 1 25 30 PM" src="https://github.com/DataDog/dd-trace-py/assets/723615/94dcfac2-65dc-4113-b0cc-224db2685186">

An apparently related change to ReadTheDocs that was released between these two builds https://github.com/readthedocs/readthedocs.org/pull/8968

**Comment by emmettbutler** [comment]
Theory: https://github.com/readthedocs/readthedocs.org/pull/8968 changed readthedocs' repository cloning behavior to avoid fetching all release branches, instead fetching only the branch being built. Since our repo's method of assembling release notes relies on being able to read all historical release branches, the release notes build fails.

While we figure out whether there's a readthedocs workaround or whether we'll need to rethink how we build these release notes pages, I think pointing the "release notes" sidebar link to the github releases page will clear up the confusion this is causing.
