### ISSUE TITLE
dd-trace-py triggers CWE 78 in Veracode scans

### ISSUE THREAD

**Issue by jacob-kinzer** [DataDog/dd-trace-py#7183]
### Summary of problem
dd-trace-py triggers an CWE 78 ( https://cwe.mitre.org/data/definitions/78.html ) during Veracode scans for Improper Neutralization of Special Elements used in an OS Command on line 140 in ddtrace_run.py https://github.com/DataDog/dd-trace-py/blob/85d5ec5129f8addb575656b24a3b2bfd683d1c68/ddtrace/commands/ddtrace_run.py#L140

### Which version of dd-trace-py are you using?
1.18.0 but i believe the same line is still in the newest versions.

### Which version of pip are you using?
N/A

### Which libraries and their versions are you using?
N/A

### How can we reproduce your problem?
Scan the library using Veracode
### What is the result that you get?
Veracode finds/marks line 140 as CWE 78
### What is the result that you expected?
No vulnerabilities found

**Comment by emmettbutler** [comment]
This point from the vulnerability description appears to be the one that applies in this case

> The application accepts an input that it uses to fully select which program to run, as well as which commands to use. The application simply redirects this entire command to the operating system. For example, the program might use "exec([COMMAND])" to execute the [COMMAND] that was supplied by the user. If the COMMAND is under attacker control, then the attacker can execute arbitrary commands or programs. If the command is being executed using functions like exec() and CreateProcess(), the attacker might not be able to combine multiple commands together in the same line.
> ...the programmer does not intend for the command to be accessible to any untrusted party, but the programmer probably has not accounted for alternate ways in which malicious attackers can provide input.

**Comment by emmettbutler** [comment]
I'm going to close this because CWE 78 doesn't appear to apply to dd-trace-py's use of user input to select which program to run.

**Comment by jonathan-hafner** [comment]
ddtrace_run.py defines the behavior of the ddtrace-run wrapper command that is provided as part of the installation for the module.  This is intended to be a command line interface which is composable with other wrappers or end-user commands. Customers are able to specify a vast variety of arguments as inputs for the ddtrace-run command. Additionally, using ddtrace-run would not permit any activity that the user running it did not already have permission to perform.  If users prefer to not use the ddtrace-run wrapper, they can also enable the product at the level of code by importing ddtrace as a module and starting it manually. See the “When ddtrace-run cannot be used“ section of the following documentation: [Installation + Quickstart - ddtrace documentation](https://ddtrace.readthedocs.io/en/stable/installation_quickstart.html#tracing) (which does not invoke os.execl() )
