### ISSUE TITLE
Installation fails because of lack of psutil version

### ISSUE THREAD

**Issue by paulschreiber** [DataDog/dd-trace-py#7213]
### Summary of problem
Installation fails because of lack of psutil version. This worked with ddtrace 1.x.

See related #7169.

### Which version of dd-trace-py are you using?
2.0.2

### Which version of pip are you using?
Whatever is included with the Python 3.12 Docker image.

### What is the result that you get?
Here's the [log excerpt from pip install](https://github.com/techmatters/terraso-backend/actions/runs/6461221390/job/17540464120?pr=877):
```
#12 68.67 Collecting psutil~=5.8 (from ddtrace==2.0.2->-r requirements.txt (line 249))
#12 68.67 ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
#12 68.67     psutil~=5.8 from https://files.pythonhosted.org/packages/af/4d/389441079ecef400e2551a3933224885a7bde6b8a4810091d628cdd75afe/psutil-5.9.5-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from ddtrace==2.0.2->-r requirements.txt (line 249))
#12 69.86 make: *** [Makefile:40: install] Error 1
#12 ERROR: process "/bin/sh -c pip install --upgrade pip && make install" did not complete successfully: exit code: 2
```

### What is the result that you expected?
Installation succeeds.

**Comment by majorgreys** [comment]
Looking at the commit from dependabot, the lock file has not been updated to include the dependencies added with 2.0.2, hence the error in require-hashes mode.

https://github.com/techmatters/terraso-backend/commit/e5f3033e6aa09920f40660d98ee9015955cb3d3d

Have you tried a manual bump by regenerating the lock file?

**Comment by paulschreiber** [comment]
Weird. Must have been a dependabot bug. Running `make lock` and `make lock-dev` manually cleaned it up. Apologies for the noise.
