### ISSUE TITLE
Unexpected exception on shutdown

### ISSUE THREAD

**Issue by sileht** [DataDog/dd-trace-py#7214]
### Summary of problem

When our application shutdown, we got this backtrace from time to time:

```
....
  File "asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "asyncio/base_events.py", line 1884, in _run_once
    event_list = self._selector.select(timeout)
  File "selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
  File "ddtrace/internal/atexit.py", line 67, in handle_exit
    f()
  File "ddtrace/tracer.py", line 314, in _atexit
    self.shutdown(timeout=self.SHUTDOWN_TIMEOUT)
  File "ddtrace/tracer.py", line 1048, in shutdown
    forksafe.unregister(self._child_after_fork)
  File "ddtrace/internal/forksafe.py", line 56, in unregister
    _registry.remove(after_in_child)
ValueError: list.remove(x): x not in list
```

### Which version of dd-trace-py are you using?

ddtrace==1.20.2

### Which version of pip are you using?

22.3.1

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
annotated-types==0.6.0
anyio==3.7.1
asgi-ratelimit==0.10.0
asgiref==3.7.2
attrs==23.1.0
Authlib==1.2.1
black==23.9.1
blinker==1.6.3
boltons==21.0.0
bracex==2.4
bytecode==0.15.0
cattrs==23.1.2
certifi==2023.7.22
cffi==1.16.0
charset-normalizer==3.3.0
click==8.1.7
click-option-group==0.5.6
colorama==0.4.6
cryptography==41.0.4
daiquiri==3.2.1
datadog==0.47.0
ddsketch==2.0.4
ddtrace==1.20.2
defusedxml==0.7.1
Deprecated==1.2.14
envier==0.4.0
face==22.0.0
fastapi==0.103.2
glom==22.1.0
greenlet==3.0.0
gunicorn==21.2.0
h11==0.14.0
h2==4.1.0
hiredis==2.2.3
hpack==4.0.0
httpcore==0.18.0
httptools==0.6.0
httpx==0.25.0
hyperframe==6.0.1
idna==2.10
imia==0.5.3
importlib-metadata==6.8.0
iniconfig==2.0.0
itsdangerous==2.1.2
jsonschema==4.19.1
jsonschema-specifications==2023.7.1
markdown-it-py==3.0.0
mdurl==0.1.2
migra==3.0.1663481299
mypy==1.5.1
mypy-extensions==1.0.0
opentelemetry-api==1.20.0
packaging==23.2
passlib==1.7.4
pastel==0.2.1
pathspec==0.11.2
peewee==3.16.3
platformdirs==3.11.0
pluggy==1.3.0
poethepoet==0.24.1
protobuf==4.24.4
psycopg==3.1.12
psycopg-binary==3.1.12
psycopg2-binary==2.9.9
pycountry==22.3.5
pycparser==2.21
pydantic==2.4.2
pydantic_core==2.10.1
Pygments==2.16.1
PyJWT==2.8.0
pytest==7.4.2
pytest-asyncio==0.21.1
python-dotenv==1.0.0
python-json-logger==2.0.7
python-lsp-jsonrpc==1.0.0
PyYAML==6.0.1
redis==5.0.1
referencing==0.30.2
requests==2.31.0
respx==0.20.2
rich==13.6.0
rpds-py==0.10.4
ruamel.yaml==0.17.35
ruamel.yaml.clib==0.2.8
ruff==0.0.292
schemainspect==3.1.1663587362
semgrep==1.43.0
sentry-sdk==1.31.0
setproctitle==1.3.3
six==1.16.0
sniffio==1.3.0
SQLAlchemy==2.0.21
SQLAlchemy-Utils==0.41.1
sqlbag==0.1.1617247075
starlette==0.27.0
starsessions==2.1.3
stripe==6.7.0
tenacity==8.2.3
tomli==2.0.1
types-pyOpenSSL==23.2.0.2
types-PyYAML==6.0.12.12
types-redis==4.6.0.7
types-urllib3==1.26.25.14
typing_extensions==4.8.0
ujson==5.8.0
urllib3==1.26.17
uvicorn==0.23.2
uvloop==0.17.0
watchfiles==0.20.0
wcmatch==8.5
websockets==11.0.3
wrapt==1.15.0
xmltodict==0.13.0
yamllint==1.32.0
zipp==3.17.0

</details>

### How can we reproduce your problem?

No idea, it's random.

### What is the result that you get?

A backtrace during shutdown

### What is the result that you expected?

No backtrace during shutdown

**Comment by majorgreys** [comment]
@sileht thank you for the bug report.

Not sure, but the same error on shutdown was report by https://github.com/DataDog/dd-trace-py/issues/6894#issuecomment-1746101774.

**Comment by sileht** [comment]
The root cause seems the same, but in my case, this occurs on an actual application in production, not in your testing framework.

**Comment by majorgreys** [comment]
Right, the linked issue was initially understood as an issue with the pytest integration but the root cause seems more with how the library is starting and stopping threads.

**Comment by majorgreys** [comment]
@sileht Could you try 1.20.3? There were some recent changes to atexit hooks which might be at issue.

**Comment by sileht** [comment]
> @sileht Could you try 1.20.3? There were some recent changes to atexit hooks which might be at issue.

The new version should land in production tomorrow, I will give you feedback in a couple of days, as it occurs at least once a day.

**Comment by sileht** [comment]
We now have ddtrace 2.1.4 and still see this issue.

**Comment by sileht** [comment]
looks like someone else opened the same issue: #7273 we should close one of them.

**Comment by lawrenceong** [comment]
@sileht I've got reproduction steps in the one i raised.  Are you happy to close this one?

**Comment by sileht** [comment]
Yes I subscribe the other one (https://github.com/DataDog/dd-trace-py/issues/7273).
