### ISSUE TITLE
Docs / Bikeshed: Reconsider maintaining a single `CHANGELOG.md` file

### ISSUE THREAD

**Issue by tony** [DataDog/dd-trace-py#7227]
Hi!  Thank you for the project.

### Summary of problem

dd-trace-py release notes aren't being conveyed succinctly to downstream users due to replacing a changelog file for GitHub releases. 

Release notes are not a viable replacement for a changelog:

1. Changelogs are a single file, can be scrolled across in a stream, `git tag`d, and portable

   Example spec: [keepachangelog](https://keepachangelog.com/en/1.1.0/)
2. Releases are kept in https://github.com/DataDog/dd-trace-py/releases

    GitHub releases are fragmented across releases with blog-like typesetting and whitespacing, file assets, include unnecessary repetition in the form of pre-releases, and further break concentration by paginating.

   It hampers understanding what's changed across versions, esp. after a few months pass.

### How can we reproduce your problem?

Try to link to a tag or span of a version release, e.g. [v2.0.2](https://github.com/DataDog/dd-trace-py/blob/v2.0.2/CHANGELOG.md) to find updates since [v1.13.0](https://github.com/DataDog/dd-trace-py/blob/v1.13.0/CHANGELOG.md)

### What is the result that you get?

1. Load changelog page via [docs](https://ddtrace.readthedocs.io/en/stable/release_notes.html) or [GitHub](https://github.com/DataDog/dd-trace-py/blob/1.x/CHANGELOG.md)

    ![image](https://github.com/DataDog/dd-trace-py/assets/26336/359a32a8-cc61-4161-971c-dd9347e0ed9e)
2. And then, after a few clicks, going to https://github.com/DataDog/dd-trace-py/releases
3. Paginating through pages of beta releases / repetition, whitespacing, and having a very difficult time compared to just having a markdown file.

   https://github.com/DataDog/dd-trace-py/assets/26336/f6cf2ecb-d2cd-4e3b-8536-5baf0433b91a

### What is the result that you expected?

Being able to load CHANGELOG.md at [v2.0.2](https://github.com/DataDog/dd-trace-py/blob/v2.0.2/CHANGELOG.md) and simply scroll down and see final version releases since v1.13.0 without GitHub releases.

Example, [Flask](https://github.com/pallets/flask) (CHANGES.rst: [repo](https://github.com/pallets/flask/blob/3.0.0/CHANGES.rst), [docs](https://flask.palletsprojects.com/en/3.0.x/changes/))

https://github.com/DataDog/dd-trace-py/assets/26336/06b936c0-5fb0-4d51-a806-5ebdb79330ea

**Comment by majorgreys** [comment]
Thank you @tony for raising this!

Your proposal to maintain a changelog is one we have discussed on the team. 

The question I have had is what we should do with the "release notes" we included in our sphinx docs. Do we continue to use reno and publish them with the GitHub releases?

What do others think of maintaining a separate release notes file more information relevant to a release can be communicated?

**Comment by majorgreys** [comment]
@tony you also highlighted how having release notes included in pre-releases creates problems:

> Paginating through pages of beta releases / repetition, whitespacing, and having a very difficult time compared to just having a markdown file.

Including release notes with the pre-releases gives a preview of the documented changes to come. Unfortunately GitHub does not allow for that.

The only solution to the problem you are raising that I see is for us to edit or delete pre-releases once another RC or final version is created. What do others think?

**Comment by emmettbutler** [comment]
The CHANGELOG.md file is now automatically updated when stable versions are released. It doesn't currently contain the entire history of patch releases, but it should.

As far as I can tell, this issue is now resolved. Please comment if I missed something.
