### ISSUE TITLE
Binary for GCP Function mini-agent

### ISSUE THREAD

**Issue by jeffclay** [DataDog/dd-trace-py#7287]
Hi. I'm trying to take advantage of the serverless mini agent for GCP Functions as described in this [PR](https://github.com/DataDog/dd-trace-py/pull/5536) but I'm not seeing where to obtain the rust binary. 

Any pointers to documentation or the binary would be very helpful. I'm hoping to use ddtrace in my python GCP Function. 

Thanks!

**Comment by mabdinur** [comment]
Hi @jeffclay, 

The rust binaries used in the mini agent is installed when these conditions are met: https://github.com/DataDog/dd-trace-py/blob/v2.1.4/ddtrace/internal/serverless/mini_agent.py#L15-#L20. This should occur when ddtrace is imported and the global tracer is [initialized](https://github.com/DataDog/dd-trace-py/blob/98aeeffeb7514c7acb88d53ff7e83a2770b5b552/ddtrace/tracer.py#L211).

I believe this feature is still in beta/development so there is not a lot of public documentation. 

Here's the source code for the rust mini agent:
- https://github.com/DataDog/libdatadog/tree/main/serverless

cc: @maxday who may have more context here

Let me know if this helps!

**Comment by mabdinur** [comment]
Hi @jeffclay,

The serverless mini agent is currently on hold. Currently there is no timeline for GA. I am closing this issue but feel free to reopen.
