### ISSUE TITLE
Flask distributed tracing documentation is missing

### ISSUE THREAD

**Issue by poffdeluxe** [DataDog/dd-trace-py#730]
It seems like a recent version of dd-trace-py moved away from the flask middleware and is now using the patcher for handling flask tracing. However, I can't seem to find any documentation anymore around enabling distributed tracing on Flask. 

The flask framework section here seems to only have how to enable default tracing: http://pypi.datadoghq.com/trace/docs/web_integrations.html#flask

**Comment by brettlangdon** [comment]
@poffdeluxe thank you for catching this.

Yes, it does appear the configuration options are missing from the documentation.


```python
from ddtrace import config

# Override service name, default 'flask'
config.flask.service_name = 'custom-service-name'

# Configure distributed tracing, default False
config.flask.distributed_tracing_enabled = True
```



A full example:

```python
# app.py
from ddtrace import config
from flask import Flask

config.flask.distributed_tracing_enabled = True
app = Flask(__name__)


@app.route('/')
def index():
    return 'Hello World!', 200
```


```bash
FLASK_APP=app.py ddtrace-run flask run
```

**Comment by poffdeluxe** [comment]
@brettlangdon Fantastic. Thanks for this!

**Comment by brettlangdon** [comment]
@poffdeluxe hey, I messed up the example.

You want `config.flask['distributed_tracing_enabled'] = True` instead of `config.flask.distributed_tracing_enabled = True`

So sorry about that. I always mess that up (probably a good reason for us to have the documentation).
