### ISSUE TITLE
pymysql double span after version upgrade

### ISSUE THREAD

**Issue by maven-jim** [DataDog/dd-trace-py#7314]
### Summary of problem

We are using ddtrace APMs for service monitoring purposes and we use the default `patch_all` option for dependencies including pymysql. After a recent version upgrade, we noticed the pymsql double span issue right after version upgrade. We did an internal analysis and it looks like the last version we don't have a double span issue for pymysql is ddtrace `v1.8.3` and the issue starts from `v1.9.0`.

### Which version of dd-trace-py are you using?

We are currently using `v1.19.3` in production after the version upgrade. Before that, we were on v0.54.1.

### Which version of pip are you using?

Poetry `v1.4.2`

### Which libraries and their versions are you using?

pymysql `v0.10.1`

<details>
[[package]]
name = "pymysql"
version = "0.10.1"
description = "Pure Python MySQL Driver"
category = "dev"
optional = false
python-versions = "*"
files = [
    {file = "PyMySQL-0.10.1-py2.py3-none-any.whl", hash = "sha256:44f47128dda8676e021c8d2dbb49a82be9e4ab158b9f03e897152a3a287c69ea"},
    {file = "PyMySQL-0.10.1.tar.gz", hash = "sha256:263040d2779a3b84930f7ac9da5132be0fefcd6f453a885756656103f8ee1fdd"},
]
</details>

### How can we reproduce your problem?

import pymysql as a dependency and switch ddtrace version between v1.8.3 and later versions and check the `trace.pymysql.query.hits` stats differences.

### What is the result that you get?

After version upgrade, `trace.pymysql.query.hits`stats got doubled. See snapshot below.
![image](https://github.com/DataDog/dd-trace-py/assets/102182470/31da2b14-ed6d-4067-9881-ec777c26fe9a)

### What is the result that you expected?

`trace.pymysql.query.hits` stats should remain flat after version upgrade.

**Comment by majorgreys** [comment]
@maven-jim, can you share output of `pip freeze` and your library configuration? 

Thank you for sharing that this starts with v1.9.0. I don't immediately see a change in that release that could explain this: https://github.com/DataDog/dd-trace-py/releases/tag/v1.9.0

**Comment by mabdinur** [comment]
Hi @maven-jim, 

ddtrace v1.19.0 introduced a [regression](https://github.com/DataDog/dd-trace-py/commit/ec3e14d3fb008d0104951abca31790f32ee35a32) where trace agent sampling rates were ignored. This resulted in a larger number of spans being ingested. This could be the cause of the increase in the number of pymysql spans. This bug was fixed [here](https://github.com/DataDog/dd-trace-py/pull/7333) and backported to the 1.19 release line. 

Can you install [v1.19.4](https://github.com/DataDog/dd-trace-py/releases/tag/v1.19.4) and see if that resolves this issue?

**Comment by emmettbutler** [comment]
I'm going to close this issue because I expect @mabdinur's proposed workaround to fix the problem. Please comment or reopen if it doesn't end up working out.

**Comment by maven-jim** [comment]
Thanks @mabdinur for the answer and sorry I was busy on other things in the past month or so. Will upgrade to v1.19.4 and keep you updated on the results.
