### ISSUE TITLE
ddtrace 2 + python 3.12 requires compilation of psutil?

### ISSUE THREAD

**Issue by wicol** [DataDog/dd-trace-py#7316]
### Summary of problem

Trying to upgrade to python 3.12 and ddtrace 2.1.1. Building in docker on an ARM Mac. It seems the new psutil dependency doesn't have wheels available for 3.12 and so requires gcc etc.

Putting this here for googlers in the same situation:
`error: command 'gcc' failed: No such file or directory`

What are my options here?
* Stay on python 3.11 and ddtrace 1.20 until psutil has newer wheels available? Looks like they're building for up to 3.8 now so guessing that'll take a while.
* Add compilation of psutil in my base docker images? (oh but they're so clean right now 🙈 )

### Which version of dd-trace-py are you using?

2.1.1

### Which version of pip are you using?

23.2.1

**Comment by majorgreys** [comment]
@wicol Thank you getting this discussion started.

As you point out, we added psutil as a dependency with the most recent major version bump. This was in fact an "unvendoring" as we had previously vendored psutil, which we had done in the first place for partly for the reason of install requirements (which you highlight here) as well as avoiding dependency conflicts if a user was already installing psutil.

But, as you also point out, the upstream project is not building and releasing wheels for all os and architectures that are supported by ddtrace. https://github.com/giampaolo/psutil/pull/2224 seems to be the relevant upstream PR which would address this. 

Given that, we will have to reconsider our decision to unvendor, or at least consider an alternative to psutil in our library.

**Comment by wicol** [comment]
Thanks for the insight @majorgreys. That all sounds very reasonable. My only complaint would be that this wasn't mentioned in the changelog for dd-trace 2 (or did I miss it?) or otherwise in docs (not that I'd know where to look) - might save people the trouble of trying to upgrade only to back off until this is resolved.

Anyways, I'll poke that PR for some more info (will it really yield a wheel for python 3.12?).

**Comment by majorgreys** [comment]
> My only complaint would be that this wasn't mentioned in the changelog

You are correct and we should have included a note or documentation changes before merging https://github.com/DataDog/dd-trace-py/pull/6651.

> I'll poke that PR for some more info (will it really yield a wheel for python 3.12?)

Being that it already makes use of cibuildwheel, getting 3.12 wheels should be straightforward.
