### ISSUE TITLE
Trace breaks with psycopg2 Composed type

### ISSUE THREAD

**Issue by ProvoK** [DataDog/dd-trace-py#732]
Hello there,
Lately I was trying to run one of our services behind the python tracer, and I encountered some troubles.

The trace sending fails totally when using specific psycopg2.sql objects. 
For instance, it does with queries composed with this utility function:

```python

from psycopg2.sql import SQL, Identifier, Placeholder

def _list(schema: str, tablename: str, filters: Mapping = None):
    filters = filters or {}
    where_clause = [
        SQL('{} = {}').format(Identifier(col), Placeholder(col))
        for col in filters
    ]
    where = SQL(' AND ').join(where_clause or [SQL('TRUE')])

    query = SQL("""
        SELECT *
        FROM {schema}.{tablename}
        WHERE
            {where}
    """).format(
        schema=Identifier(schema),
        tablename=Identifier(tablename),
        where=where
    )
    return query
```
In this case, the resulting query is not a string but a special psycopg2 type called [Composed](http://initd.org/psycopg/docs/sql.html?highlight=composed#psycopg2.sql.Composed), which is not serializable with standard encoders by msgpack nor the json builtin.

The resulting error, that **blocks** the trace to be sent, is:
```
[2018-11-26 09:46:09,793] [ERROR] [TRACER] - ddtrace.writer: cannot send spans to localhost:8126: can't serialize Composed([SQL('\n        SELECT *\n        FROM '), Identifier('analytics'), SQL('.'), Identifier('widget'), SQL('\n        WHERE\n            '), Composed([Composed([Identifier('id'), SQL(' = '), Placeholder('id')])]), SQL('\n    ')])
```
First of all, am I missing something? The error seems pretty clear but never say never.

Second, I've been hacking around and this issue could maybe be solved with a psycopg2 "custom" TracedCursor, so that if the "resource" variable is of type "Composed" uses the `as_string` method to return a representation of the query.
Something like that seems actually doing the job.

```python
# contrib/psycopg/patch.py

from psycopg2.sql import Composed

class PgTracedCursor(dbapi.TracedCursor):
    def _trace_method(self, method, resource, extra_tags, *args, **kwargs):
        if isinstance(resource, Composed):
            resource = resource.as_string(self.__wrapped__)
        super()._trace_method(method, resource, extra_tags, *args, **kwargs)

# Uses the custom TracedCursor
class PgTracedConnection(dbapi.TracedConnection):
    """ TracedConnection wraps a Connection with tracing code. """

    def cursor(self, *args, **kwargs):
        cursor = self.__wrapped__.cursor(*args, **kwargs)
        pin = Pin.get_from(self)
        if not pin:
            return cursor
        return PgTracedCursor(cursor, pin)

# changed from dbapi.TracedConnection to above class
def patch_conn(conn, traced_conn_cls=PgTracedConnection):
    [...]
```

EDIT: Added imports for first code snippet

**Comment by majorgreys** [comment]
@ProvoK Thank you for the terrific detective work! As you figured out, the problem occurs because of the serialization of the `Composed` object. We'll work on a fix, for which your solution here will be super helpful.

**Comment by majorgreys** [comment]
Closing this issue.

**Comment by mlennon-lumere** [comment]
I'm seeing this issue on ddtrace 0.23.0, on the following query:
```

    input_table = sql.Identifier('foo_table')
    cursor.execute(sql.SQL("SELECT EXISTS (SELECT * FROM {input_table} FOR UPDATE SKIP LOCKED LIMIT 1)").format(
        input_table=input_table))
    return cursor.fetchone()[0]
```
I'm trying to write a small app to isolate the issue
