### ISSUE TITLE
Cannot start ddtrace on Python2 Flask app

### ISSUE THREAD

**Issue by remi-debette** [DataDog/dd-trace-py#733]
Hi,

We are trying to use the datadog service to profile a Flask server. But so far we cannot even get it to work on a sample app.

We are trying to use the ddtrace library on python 2.7 by following the getting started docs.
https://www.datadoghq.com/blog/monitoring-flask-apps-with-datadog/
http://pypi.datadoghq.com/trace/docs/web_integrations.html#flask
Nothing works so far, we wonder if there is any additional steps not described in the documentation.

We use the latest ddtrace v0.16.0
We tried by installing the latest Datadog Agent v6.7.0 and APM trace agent on MacOs, Windows and the docker image.
Everytime the following error happens at startup of ddtrace:

To replicate:

run_minim.py:
```python
from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hello, World!'
```

```bash
 FLASK_APP=run_minim.py DATADOG_ENV=python_app ddtrace-run flask run --host=0.0.0.0 --port=5555
```

ddtrace error:
```
 * Serving Flask app "run_minim"
ERROR:ddtrace.writer:failed_to_send services to Agent: HTTP error status 400, reason Bad Request, message Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Mon, 26 Nov 2018 13:00:53 GMT
Content-Length: 59
```

Agent error:
```
[ TRACE ] 2018-11-26 12:58:42 INFO (api.go:324) - no data received
[ TRACE ] 2018-11-26 12:59:28 ERROR (api.go:274) - cannot decode v0.3 services payload: msgp: attempted to decode type "nil" with method for "str"
```

Thank you

**Comment by remi-debette** [comment]
We also tried to install ddtrace v0.15.0, which does not have an error apparently, but then we do not see anything in the page:
https://app.datadoghq.com/apm

Thank you

**Comment by brettlangdon** [comment]
@remi-debette thank you for reaching out. My apologies that you are having issues.

That error message you are seeing from your application, although it sounds bad, shouldn't be effecting your application or tracing at all. That message is from a feature we are working on deprecating and it is being very noisy and sounds really bad when you see it in the logs.

Is the only issue that you are seeing that error message or are you not getting traces as expected either?

**Comment by remi-debette** [comment]
Hi Brett, thank you for your answer.
Indeed if we can make it work, we are interested in the possibilities of the tool.
So now, I tried again setting up everything and ignoring the error. 

I have a Flask server that runs fine on my local Mac in which we added ddtrace.patch_all()
The Agent is a Docker agent on the same Mac running alongside other containers such as our MongoDB.

Now I tried to do a few actions on the server to trigger some tracing
There is the following additional error:
`No handlers could be found for logger "ddtrace.writer"`

Also, I can now see some data within https://app.datadoghq.com/apm/ but it is only the DB requests. Do you think ddtrace sent them successfully or did the agent capture them from the MongoDB Docker?

Thank you

**Comment by remi-debette** [comment]
We were expecting at least to see some routes traces

**Comment by remi-debette** [comment]
Actually it eventually works, as long as we just ignore the errors and let the server live for a while.

But now we cannot filter between the routes of our real app and the sample app we created to test datadog in https://app.datadoghq.com/apm/
This is even though we run the two with different DATADOG_ENV.

Is there a documentation somewhere that we could rely on to get the data of one server only?

Thank you,

**Comment by brettlangdon** [comment]
@remi-debette are you running the app via `ddtrace-run`?

`DATADOG_ENV` is only used by `ddtrace-run`.

However, if you are manually patching, you can do the following to set the environment.

```python
from ddtrace import tracer

tracer.set_tags(dict(env=os.environ['DATADOG_ENV']))
```

Let me know if this resolves your issue.

Also, it will usually take a little bit for a new service to show up for the first time (few minutes at most usually).

**Comment by remi-debette** [comment]
Hi @brettlangdon ,

Thanks, your method works. 
We also used the jinja2 integration as explained in your documentation and it works fine.

So the key is ignoring the errors and wait for a little with the server running before seeing data (which can be counter intuitive after errors)

Is there something equivalent when running through uWSGI?

Thank you

**Comment by brettlangdon** [comment]
Once a service is recognized by our system for the first time you should always see data/traces fairly quickly in the UI (< 1 min), it just that initial environment or service showing up that can take a little longer.

Everything should work perfectly fine with `uWSGI` as well.
