### ISSUE TITLE
Support distributed headers for graphql traces

### ISSUE THREAD

**Issue by ruan-stint** [DataDog/dd-trace-py#7429]
### Summary of problem

Is it possible to support distributed tracing via the graphql service ex. `config.graphq["distributed_tracing"] = True`

Currently the APM traces of our graphql service (graphene) is not being connected to our RUM data, seemingly because the graphql patching code doesn't support distributed tracing headers.

```
    config.django["service_name"] = "api"
    config.django["instrument_databases"] = True
    config.django["database_service_name"] = "postgres"
    config.django["instrument_caches"] = True
    config.django["cache_service_name"] = "redis"
    config.django["instrument_middleware"] = True
    config.django["trace_query_string"] = True
    config.django["analytics_enabled"] = True
    config.celery["distributed_tracing"] = True
    config.botocore["distributed_tracing"] = True
    config.graphql["service"] = "graphql"
```

The traces are connected to our RUM data when doing REST requests (since the django config supports the distributed headers), but not for any of our graphql queries.

### Which version of dd-trace-py are you using?
ddtrace = "1.17.3"

### Which version of pip are you using?
`pip 23.2.1 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)`

### Which libraries and their versions are you using?
```
graphene-django = "2.9.1"
ddtrace = "1.17.3"
django = "3.2.16"
graphene = "2.1.9"
graphql-core = "2.3.2"
```
### How can we reproduce your problem?
1. Configure APM on an app with graphene/graphql-core, and instrument graphql as a service
2. Connect RUM and APM https://docs.datadoghq.com/real_user_monitoring/connect_rum_and_traces/?tab=flutter
3. Observe that no traces are connected to the RUM data

### What is the result that you get?
No traces that involve graphql are connected to the RUM data.

### What is the result that you expected?
Traces with graphql operations should be connected to RUM data

**Comment by mabdinur** [comment]
Hi, @ruan-stint

The ddtrace library does not provide support for distributed tracing via the graphql integration. However distributed tracing can be configured manually.

Distributed tracing can be enabled by extracting/injecting ddtrace headers from incoming/outgoing http headers. This can be configured in your application code:

### Sends distributing tracing info downstream 

```python
from ddtrace import tracer
from ddtrace.propagation.http import HTTPPropagator

current_span = tracer.current_span()        # get current from the global context
if current_span is not None:
  headers = HTTPPropagator.inject(current_span.context,  headers)   # updating headers to include tracing data
  # Send requests with ddtrace http headers
```

### Extracts distributing tracing info from upstream services

```
from ddtrace import tracer
from ddtrace.propagation.http import HTTPPropagator

context = HTTPPropagator.extract(headers)     # get tracing data from incoming http headers
tracer.context_provider.activate(context)          # activate trace data from incoming headers
```



### Additional Context

The ddtrace library provides support for distributed tracing by adding `x-datadog-*` and/or [tracecontext](https://www.w3.org/TR/trace-context/) headers to incoming/outgoing http requests. `ddtrace` supports tracing for graphql via the [graphql-core](https://github.com/graphql-python/graphql-core/blob/main/src/graphql/__init__.py) library. The `graphql-core` library does not make assumptions about how requests are served and how graphql schemas are resolved. Therefore it does not have an api to intercept request headers. Supporting distributing tracing for graphql will require a different approach than all of our other integrations. For exampling we may need to generate comments containing distributed tracing info and then append it to the incoming/outgoing graphql queries. I will mark this a feature request.

**Comment by ruan-stint** [comment]
I see thanks for the response. We'll give this a try
