### ISSUE TITLE
Error traces marked with MANUAL_KEEP are not kept

### ISSUE THREAD

**Issue by Apakottur** [DataDog/dd-trace-py#7443]
### Summary of problem
Error traces marked with MANUAL_KEEP are not kept in an environment with many traces.

### Which version of dd-trace-py are you using?
2.1.4

### Which version of pip are you using?
23.3.1

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
aiobotocore==2.6.0
aiohttp==3.8.6
aioitertools==0.11.0
aiopg==1.4.0
aiosignal==1.3.1
amplitude-analytics==1.1.3
annotated-types==0.6.0
anyio==4.0.0
async-timeout==4.0.3
asyncpg==0.28.0
attrs==23.1.0
botocore==1.31.17
bytecode==0.15.1
CacheControl==0.13.1
cachetools==5.3.2
cattrs==23.1.2
certifi==2023.7.22
cffi==1.16.0
charset-normalizer==3.3.1
click==8.1.7
cryptography==41.0.5
ddsketch==2.0.4
ddtrace==2.1.4
Deprecated==1.2.14
distro==1.8.0
dnspython==2.4.2
email-validator==2.1.0.post1
envier==0.4.0
firebase-admin==6.2.0
frozenlist==1.4.0
funcsigs==1.0.2
geographiclib==2.0
geopy==2.4.0
google-api-core==2.12.0
google-api-python-client==2.106.0
google-auth==2.23.3
google-auth-httplib2==0.1.1
google-cloud-core==2.3.3
google-cloud-firestore==2.13.0
google-cloud-storage==2.12.0
google-crc32c==1.5.0
google-resumable-media==2.6.0
googleapis-common-protos==1.61.0
greenlet==3.0.1
grpcio==1.59.2
grpcio-status==1.59.2
h11==0.14.0
h3==3.7.6
httpcore==0.18.0
httplib2==0.22.0
httptools==0.6.1
httpx==0.25.0
idna==3.4
importlib-metadata==6.8.0
jmespath==1.0.1
loguru==0.7.2
msgpack==1.0.7
multidict==6.0.4
numpy==1.26.1
opentelemetry-api==1.20.0
pgpasslib==1.1.0
phonenumbers==8.13.23
proto-plus==1.22.3
protobuf==4.24.4
psutil==5.9.6
psycopg2-binary==2.9.9
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
pydantic==2.4.2
pydantic-settings==2.0.3
pydantic_core==2.10.1
pyinstrument==4.6.0
PyJWT==2.8.0
pyparsing==3.1.1
python-dateutil==2.8.2
python-dotenv==1.0.0
PyYAML==6.0.1
redis==5.0.1
requests==2.31.0
rook==0.1.209
rsa==4.9
six==1.16.0
sniffio==1.3.0
SQLAlchemy==2.0.22
starlette==0.31.1
tenacity==8.2.3
timezonefinder==6.2.0
typeguard==4.1.5
typing_extensions==4.8.0
uritemplate==4.1.1
urllib3==1.26.18
uvicorn==0.23.2
uvloop==0.19.0
watchfiles==0.21.0
websocket-client==1.6.4
websockets==12.0
wrapt==1.15.0
xmltodict==0.13.0
yarl==1.9.2
zipp==3.17.0

</details>

### How can we reproduce your problem?
I'm tracing Starlette requests in my project, and I want to manually keep all errors by using `ddtrace.constants.MANUAL_KEEP_KEY`.
To do that, I first mark erroneous traces as errors with:
```python
if dd_span := tracer.current_span():
    dd_span.set_exc_info(type(e), e, e.__traceback__)
```

And then mark them for manual keeping:
```python
dd_span.set_tag(ddtrace.constants.MANUAL_KEEP_KEY)
```

This worked perfectly up until about 2 months ago, when all error traces stopped appearing on Datadog (other, non error traces are still working, with various ingestion reasons).

This only occurs on my production environment, and not on staging. The only difference between the two is the amount of traffic/traces they have (Production has much more traces).

I investigated a bit and found out that the value of `dd_span._context._metrics._sampling_priority_v1` is correctly set to `2` on staging but remains `-1` on production after calling `set_tag(ddtrace.constants.MANUAL_KEEP_KEY)`.
I suspect that this has to do https://github.com/DataDog/dd-trace-py/pull/6693 which introduces the `_override_sampling_decision` function.

### What is the result that you get?
Error traces marked as MANUAL_KEEP are not kept.

### What is the result that you expected?
All traces marked as MANUAL_KEEP are kept.

**Comment by ZStriker19** [comment]
Hi @Apakottur, thanks for reaching out. We had a known sampling issue that was solved with 2.1.2, but if you're using a greater version than that on both staging and prod it's unlikely that's still the problem.

Let's take a look at the current code path when you run `dd_span.set_tag(ddtrace.constants.MANUAL_KEEP_KEY)`. 
1. We recognize the key set and run `_override_sampling_decision` with a value of 2:
https://github.com/DataDog/dd-trace-py/blob/2.x/ddtrace/span.py#L352-L353

2. `_override_sampling_decision` simply takes that 2 values and sets the span context sampling_priority to 2 https://github.com/DataDog/dd-trace-py/blob/2.x/ddtrace/span.py#L288

3. the `context.sampling_priority` setter puts the value in its metrics: https://github.com/DataDog/dd-trace-py/blob/2.x/ddtrace/context.py#L127

That all seems correct to me.


Before we used to do these two things ```self.context.sampling_priority = USER_KEEP
            update_sampling_decision(self.context, SamplingMechanism.MANUAL, True)``` But I can't see how those would cause a difference? 

Maybe we're doing something to the `sampling_priority_v1` after, but I can't find where that would occur. 

Mostly we need to look for something that would vary based on higher load. Usually things that are reactive like that are agent sampling rates. Let's say the load is very high and the agent is saying to sample out a great deal of spans. Still that sampling decision should be made at trace start, and then overridden with your `dd_span.set_tag(ddtrace.constants.MANUAL_KEEP_KEY)`.

Could you please tell me how you verified this:
 "Investigated a bit and found out that the value of dd_span._context._metrics._sampling_priority_v1 is correctly set to 2 on staging but remains -1 on production after calling set_tag(ddtrace.constants.MANUAL_KEEP_KEY)." Are you able to pinpoint when `_sampling_priority_v1` is set from 2 back to -1?  That would be the crucial piece we could use to figure out what code path is being activated. Alternatively if you have an example app, then we could use that to further pinpoint the issue on our side.

**Comment by Apakottur** [comment]
Thank you for the thorough response, your analysis sounds correct to me, I initially thought that perhaps [this](https://github.com/DataDog/dd-trace-py/blob/d87c005733e314aa6acc212e0d6f0539f5e81885/ddtrace/span.py#L292) is where the flag was being unset.

In our code we have a trace filter, I added a print of the value inside it (before the logic we have, that modifies some env related tags to ECS) and that's where I saw that the value is `-1`.
```python
class _TraceFilter(ddtrace.filters.TraceFilter):
    def process_trace(self, trace: list[ddtrace.Span]) -> list[ddtrace.Span] | None:
        for span in trace:
           if span.name in TOP_LEVEL_SPAN_NAMES:
               print(dd_span._context._metrics._sampling_priority_v1) # 2 in staging, -1 in prod
               ...
```

To try and overcome the problem, after opening the ticket I modified our logic to stop manually keeping the errors and instead rely on the error trace mechanism of the agent, and now almost all of the error traces are visible also in production (I need to check why not all of them, I don't think we're hitting the threshold).

**Comment by ZStriker19** [comment]
Hi @Apakottur I think that would be of concern if it were not for the [TraceTagsProcessor](https://github.com/DataDog/dd-trace-py/blob/d87c005733e314aa6acc212e0d6f0539f5e81885/ddtrace/internal/processor/trace.py#L146-L151), which should be setting the context metrics on the local root span once the trace is ready to send out.  Unless you're using a filter or processor that runs after TraceTagsProcessor to use [override_sampling_decision](https://github.com/DataDog/dd-trace-py/blob/d87c005733e314aa6acc212e0d6f0539f5e81885/ddtrace/span.py#L292) on the spans that are errors.... then that seems like it would almost certainly be the issue, but judging by your first comment that doesn't seem to be what you're doing. Do you have any other trace filters setup? Could you verify that the filter you're using to test that `dd_span._context._metrics._sampling_priority_v1` value runs after the TraceTagsProcessor(since if so, it may be getting an incorrect reading, since the priority has not been added from the context to the root_span)? It's usually first in the list, so unless you're prepending your filters onto the list, it should run before: https://github.com/DataDog/dd-trace-py/blob/d87c005733e314aa6acc212e0d6f0539f5e81885/ddtrace/tracer.py#L126

**Comment by ZStriker19** [comment]
Following up on this, I realized that:
1.  in `_update_tags` (used by the `TraceTagsProcessor`)  we are only setting the root span tags and metrics to the the context's tags and metrics if there's not already a set value for the local root span using `setdefault`.
2. In `_override_sampling_decision` we actually never delete the local_root_span's `_sampling_priority_v1`, just some other tags that shouldn't effect whether or not it's actually sampled.
Therefore my theory above is wrong. This will need further investigation.

**Comment by mabdinur** [comment]
Hi @Apakottur,

Sorry for the late replay. We set `dd_span.context.sampling_priority` to `-1` (USER_REJECT) when spans are rate limited. This is done here: https://github.com/DataDog/dd-trace-py/blob/v2.1.6/ddtrace/internal/sampling.py#L299. What's strange is that this is set when a span is initialized: https://github.com/DataDog/dd-trace-py/blob/62d2ebd2ad9bc096ec7288af01f385d8ec9e7aad/ddtrace/tracer.py#L722.  Calling `span.set_tag(ddtrace.constants.MANUAL_KEEP_KEY)` should override this value. My theory is that the `dd_span.set_tag(ddtrace.constants.MANUAL_KEEP_KEY)` is not being applied to ALL error spans. I think a workaround here is to use a TracerFilter to ensure all error spans have a sampling priority of `2`.

Rate limiting can be configured by setting the following envar: ``DD_TRACE_RATE_LIMIT`` to a much higher value.

To investigate this further you can open a support ticket here. This will allow us to get a better understanding of your configuration: https://www.datadoghq.com/support/

**Comment by Apakottur** [comment]
Thanks for the response.

As I mentioned in my previous comment, our current setup, where we don't manually mark error traces and instead let them be ingested with the reason "error", is working well and all traces are being ingested.

One other thing that might be related is that we were also using the MANUAL_DROP_KEY flag a lot to drop traces that we did not want, and now we do so much less, letting the agent deal with most of the dropping. Hard for me to say which change exactly fixed the problem.

From my point of view we can close this issue, and reopen it if/when the problem resurfaces.
