### ISSUE TITLE
[Feature] Make distributed_tracing_enabled externally configurable

### ISSUE THREAD

**Issue by jcassee** [DataDog/dd-trace-py#750]
Tracing a Flask application does not require any code changes, just running it with `ddtrace-run`. However, I still need to [change code](http://pypi.datadoghq.com/trace/docs/web_integrations.html#configuration) to enable distributed tracing. It does not appear possible to set this configuration using, for example, an environment variable.

Would it make sense to make this configuration externally configurable?

**Edit:** Also, why is this set to `False` by default? Are there drawbacks to using it?

**Comment by brettlangdon** [comment]
@jcassee thank you for reaching out.

Yes, this is something we will likely want to adjust (make it configurable via environment variable). We are currently in the process of thinking about how we configure all of our integrations and how we can make it be more consistent across our integrations.

Right now all distributed tracing is disabled by default for all integrations. The reason for this is that we need to have a better understanding for how distributed tracing is being used and any consequences of having distributed tracing enabled for either 1) public web services or 2) calls to third party services.

For the first point. If you have a public Flask server that has distributed tracing enabled I could manually send you the HTTP headers to set trace id and parent id. No idea why someone would or how someone would find out, but this could be a way to mess with your traces. It could mess up stats, and I could potentially just cause your traces to be sampled out.

For the latter point. If you are using `requests` for example to make HTTP calls to a third party API you would be attaching the distributed tracing headers to all outbound requests which would leak the tracing information to the service.

The information is pretty basic, it is just trace/span ids, and a sampling priority. However I still think we want to have a good understanding of side effects from being enabled by default before we do.

For an internal service that only calls other third party services, it is a no brainer to just enable distributed tracing by default. It is the other cases we need to be considerate of.

Hopefully this helps answer your question. This is still mostly a discussion we need to continue having as a team as we make overall improvements to this library.

https://github.com/DataDog/dd-trace-py/blob/6656236df620161e7c68eb4c63198e96aeb9decd/ddtrace/propagation/http.py#L11-L13

**Comment by jcassee** [comment]
Good points about the potential data injection and leakage. Almost suggest a whitelist of trusted ingress sources and egress destinations right?

Anyway, sounds like you're on it. My questions are answered. Feel free to either close this issue or keep it open until these issues are resolved.

**Comment by brettlangdon** [comment]
Let's leave this open for now until we at least resolve the Flask configuration via environment variable issue.

Thanks again :)

**Comment by brettlangdon** [comment]
@jcassee as of `0.21.0` we now enable distributed tracing by default.

**Comment by jcassee** [comment]
Great, thanks @brettlangdon!
