### ISSUE TITLE
Operation and resource name the same for Opentelemetry spans.

### ISSUE THREAD

**Issue by arguile-** [DataDog/dd-trace-py#7543]
### Summary of problem

Using the `ddtrace.opentelemetry.TraceProvider` shim with `ddtrace` handling the exporting there is no way to map to operation and resource names. The operation and resource name are set to be the same thing, which _really_ hampers APM use.

https://github.com/DataDog/dd-trace-py/blob/v2.1.5/ddtrace/opentelemetry/_span.py#L143-L146

With something like the `OpenTracing` bridge tags were provided:

https://github.com/DataDog/dd-trace-py/blob/v2.1.5/ddtrace/opentracer/tags.py#L16-L19

Opentracing has some [semantic conventions](https://opentelemetry.io/docs/specs/semconv/) that lend themselves well to this split (if not easy to parse out).

As an example with [cloud events semantic naming](https://opentelemetry.io/docs/specs/semconv/cloudevents/cloudevents-spans/) we might have `f"CloudEvents Process {event_type}"` which would easily map to:
```python
{
  "operation.name": "CloudEvents Process", 
  "resource.name": event_type,
}
```

### Which version of dd-trace-py are you using?

2.1.5

### How can we reproduce your problem?

```python
from ddtrace.opentelemetry import TracerProvider
from opentelemetry import trace
from opentelemetry.trace import set_tracer_provider

set_tracer_provider(TracerProvider())

tracer = trace.get_tracer(__name__)

event_type = "com.github.pull_request.opened"

with tracer.start_as_current_span(f"CloudEvents Process {event_type}", kind=SpanKind.CONSUMER) as span:
  # do stuff
```

Observe the horror of the span name in the UI.

### What is the result that you get?

```
"CloudEvent_Process_com.github.pull_request.opened > CloudEvent_Process_com.github.pull_request.opened"
```

### What is the result that you expected?

```
"CloudEvent_Process > com.github.pull_request.opened"
```

**Comment by arguile-** [comment]
### Proposal

I'm not expecting every experimental semantic naming proposal to Otel be supported, though a few more language agnostic mapping during trace ingest into the agent would be nice. :) 

Within the scope of `dd-trace-py` though in the short term it would be nice to be able to at least override the operation and resource names. Before I go off and write tests, etc. would something like the below be an avenue a pull request would be accepted for?

```diff
diff --git a/ddtrace/constants.py b/ddtrace/constants.py
index ee1a024f5..324a3729c 100644
--- a/ddtrace/constants.py
+++ b/ddtrace/constants.py
@@ -15,6 +15,8 @@ HOSTNAME_KEY = "_dd.hostname"
 RUNTIME_FAMILY = "_dd.runtime_family"
 ENV_KEY = "env"
 VERSION_KEY = "version"
+OPERATION_KEY = "operation.name"
+RESOURCE_KEY = "resource.name"
 SERVICE_KEY = "service.name"
 BASE_SERVICE_KEY = "_dd.base_service"
 SERVICE_VERSION_KEY = "service.version"
diff --git a/ddtrace/span.py b/ddtrace/span.py
index 0e6ef5669..b6dab7e3a 100644
--- a/ddtrace/span.py
+++ b/ddtrace/span.py
@@ -19,6 +19,8 @@ from .constants import ERROR_STACK
 from .constants import ERROR_TYPE
 from .constants import MANUAL_DROP_KEY
 from .constants import MANUAL_KEEP_KEY
+from .constants import OPERATION_KEY
+from .constants import RESOURCE_KEY
 from .constants import SAMPLING_AGENT_DECISION
 from .constants import SAMPLING_LIMIT_DECISION
 from .constants import SAMPLING_RULE_DECISION
@@ -354,6 +356,10 @@ class Span(object):
         elif key == MANUAL_DROP_KEY:
             self._override_sampling_decision(USER_REJECT)
             return
+        elif key == OPERATION_KEY:
+            self.name = value
+        elif key == RESOURCE_KEY:
+            self.resource = value
         elif key == SERVICE_KEY:
             self.service = value
         elif key == SERVICE_VERSION_KEY:
```

Adding a user extensible parser to the `TraceProvider` could be nice in the medium term especially for packages you don't control the instrumentation of.

**Comment by majorgreys** [comment]
Thank you for opening this issue and detailing the problem with how we are mapping OpenTelemetry span attributes to the Datadog model. This is being addressed by ongoing efforts and I will be sure to link this issue to PRs.
