### ISSUE TITLE
dd.trace.header.baggage support in DD python tracing library

### ISSUE THREAD

**Issue by martin2176** [DataDog/dd-trace-py#7561]
### Summary of problem
Datadog Java tracing library supports dd.trace.header.baggage
Is there a plan to add this to python library ?

### Which version of dd-trace-py are you using?
ddtrace-1.20.10 

### Which version of pip are you using?
pip 21.2.2 

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
  
</details>

**Comment by mabdinur** [comment]
Hey @martin2176,

Thanks for bringing this to our attention.

Datadog Java tracing library support for baggage was a community contribution. Supporting baggage is not currently on our roadmap for this quarter. However we will revisit this feature request in the coming quarters.

**Comment by majorgreys** [comment]
@martin2176, would adding support for baggage in the http propagator, as started in #6072, satisfy your requirements?

**Comment by martin2176** [comment]
That should work. Basically I want to carry a baggage header throughout the trace

> @martin2176, would adding support for baggage in the http propagator, as started in #6072, satisfy your requirements?

**Comment by mabdinur** [comment]
Baggage is supported in ddtrace>=2.4.0 🥳
