### ISSUE TITLE
readthedocs build broken

### ISSUE THREAD

**Issue by emmettbutler** [DataDog/dd-trace-py#7606]
readthedocs builds are failing due to a possible circular import: https://readthedocs.org/projects/ddtrace/builds/22553712/

**Comment by mabdinur** [comment]
@Yun-Kim Thanks for the community contribution!!!

**Comment by brettlangdon** [comment]
This error does showcase something interesting... which is errors raised from `imported_module.patch()` can have side effects on the application even if `raise_errors=False`.
