### ISSUE TITLE
the package version is useless

### ISSUE THREAD

**Issue by eedwards-sk** [DataDog/dd-trace-py#762]
the package versioning is currently useless

I just updated from `0.11.0` to `0.16.0` and the celery metrics we were monitoring changed from `trace.celery.task.run.hits` to `trace.celery.run.hits`

this is a backwards incompatible change, yet the version bump only happened on the minor version

can you please clarify what the versioning scheme is? because it's definitely not semantic versioning

I would like to avoid breaking our infrastructure in the future when upgrading minor versions.

For reference, industry standard and semver tend to agree that:

- major: backwards incompatible changes
- minor: new features
- patch: same features, bugfixes / hotfixes

**Comment by brettlangdon** [comment]
@eedwards-sk thank for your reaching out and my apologies that you have run into that issue.

We try our best to adhere to semver with regards to the public API for this package. We would like to be sure your migrattion from `0.11.0` to `0.16.0` went straightforward at least for the API part. Was that the case?

I am sorry that the metrics changed for `celery`, while we take these changes very seriously and we try our best to limit them whenever possible we felt that this was a necessary change for the stability of the `celery` integration for all of our users.

**Comment by eedwards-sk** [comment]
hey @brettlangdon I appreciate the response

unfortunately what you described does directly violate semver, which means either there was a  mistake made when the version was released, or there is no actual intent to strictly follow semver (which means it's not semver at all)

If it's known that a release will result in a breaking change, the major version should be bumped, no exceptions.

I hope you can understand that the more I use this APM package across our org, the larger the impact of a breaking change.

If releases adhere to strict semantic versioning, I can leverage automation to take on minor updates without much concern. As it stands, I cannot.

>**What do I do if I accidentally release a backwards incompatible change as a minor version?**
>As soon as you realize that you’ve broken the Semantic Versioning spec, fix the problem and release a new minor version that corrects the problem and restores backwards compatibility. Even under this circumstance, it is unacceptable to modify versioned releases. If it’s appropriate, document the offending version and inform your users of the problem so that they are aware of the offending version.

Please keep this in mind for the future.

https://semver.org/

**Comment by amacfie-tc** [comment]
They're still not doing semantic versioning. Going from v2.19.0 to v2.20.0 we get ` "tracer" is not exported from module "ddtrace"`. Reopen the issue please.
