### ISSUE TITLE
Expose an interface to configure resource_name in datadog trace metrics

### ISSUE THREAD

**Issue by csaska** [DataDog/dd-trace-py#7668]
### Summary of problem

[operation_name is hardcoded](https://github.com/DataDog/dd-trace-py/blob/1fdbcab9cb0e2c86e2c9b0bbd6c6cfc983f11964/ddtrace/contrib/requests/connection.py#L99C41-L101) to `requests.requests` which results in [Datadog trace metrics](https://docs.datadoghq.com/tracing/metrics/metrics_namespace/) with `resource_name:requests:request`. Instead, this project should expose an interface that lets clients override the [`operation_name` here](https://github.com/DataDog/dd-trace-py/blob/9381db7c6d44664fcf31dab479afa8b3946da167/ddtrace/internal/schema/span_attribute_schema.py#L83).

Consider copying the interface of https://pypi.org/project/django-cors-headers where they expose an env variable CORS_ALLOWED_ORIGIN_REGEXES that allows users to specify a list of regexes. 

Currently, users are forced to patch `requests` module in order to override `tracer.get_call_context().get_current_span().resource`

E.g. 

```python
# regexs to scrub a URL of path parameters that look like ids or uuids
uuid_regex = r"\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
only_digits_regex = r"\/\d+(?=\/|$)"
combined = rf"{only_digits_regex}|{uuid_regex}"
pattern = re.compile(combined, flags=re.IGNORECASE)

# dd-trace uses this env variable to do re.sub() on requested URL
DD_TRACE_RESOURCE_NAME_SCRUB_REGEXES = [pattern]
```

### Which version of dd-trace-py are you using?

1.17.3 but issue exists on latest commit.

### Which version of pip are you using?

N/A

### Which libraries and their versions are you using?

N/A

### How can we reproduce your problem?

N/A

### What is the result that you get?

N/A

### What is the result that you expected?

N/A

**Comment by mabdinur** [comment]
Hey @csaska, 

Thanks for bringing this issue to our attention. Span's with the operation name `requests.request` SHOULD NOT have a resource name that is also `request.request`. I agree this makes trace metrics and our resource views harder to use. This also goes against our conventions for "request" spans.

In this PR I updated the resource name to include the method and url: https://github.com/DataDog/dd-trace-py/pull/7717. Would this fix be sufficient or would you like more granular control of setting resource names? 

If so, you can  override resource names and operation names by configuring [TraceFilters](https://ddtrace.readthedocs.io/en/stable/advanced_usage.html#trace-filtering). These filters are applied before spans are sent to the Datadog agent.

**Comment by csaska** [comment]
Thanks for taking a look at my feature request!

At a quick glance, I think https://github.com/DataDog/dd-trace-py/pull/7717 is what we need which is:
1. my app at foo.indeed.com implements dd-trace-py
2. my app foo requests external API by doing `GET bar.com/api/employee/123`
3. result is `resource_name:GET bar.com/api/employee/123`

I think at this point we'll probably implement a TraceFilter to scrub path parameters ultimately resulting in `resource_name:POST bar.com/api/employee/*/get`.

I've been told that having an unbounded number of resource names can cause problems; however, I have no data nor supporting anecdotes.

**Comment by mabdinur** [comment]
Great point. Cardinality would be an issue here. I added this suggestion to the PR linked above: https://github.com/DataDog/dd-trace-py/pull/7717/files#r1402638110. 

This should handle most instances of high cardinality resource names. However we can still expect some edges cases (ex: if a path contains a hash or base16 integer).

**Comment by csaska** [comment]
Thanks for merging this guys!

Will this ticket be updated when a release package of this project is published to PyPi?
