### ISSUE TITLE
unpin mariadb:10.7 and use mariadb:lts

### ISSUE THREAD

**Issue by grooverdan** [DataDog/dd-trace-py#7818]
### Summary of problem

In #3913 MariaDB was pinned to 10.7 due a a Docker <= 20.10.9 having incorrect secomp filters.

While I can't see a circle-ci version of docker currently, the [Ubuntu 20.04 packaged version is 20.10.20](https://packages.ubuntu.com/focal/docker.io).

Given MariaDB-10.7  (and 10.8, 10.9, and 10.10) where short term release all are now end of life. `mariadb:lts` is a good tag for picking the lts version (currently 10.11).

### Which version of dd-trace-py are you using?

N/A

### Which version of pip are you using?

N/A

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
  
</details>

### How can we reproduce your problem?

Look at [circle ci outuput](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/51882/workflows/3a0a5775-d8db-4487-b7cc-85f7af812738/jobs/3307759).

### What is the result that you get?

Still testing against eol mariadb:10.7

### What is the result that you expected?

mariadb:lts

**Comment by emmettbutler** [comment]
@grooverdan thanks for pointing this out. I've opened a pull request making this update.
