### ISSUE TITLE
Tag django.user.name can't support UUID username field

### ISSUE THREAD

**Issue by swong-wavefin** [DataDog/dd-trace-py#7831]
### Summary of problem
ddtrace throw warning `
not expecting type '<class 'uuid.UUID'>'`

This warning is thrown because django user model is UUID type in our project. 
In django/utils.py, it haven't wrap username field as str
https://github.com/DataDog/dd-trace-py/blob/main/ddtrace/contrib/django/utils.py#L330

### Which version of dd-trace-py are you using?
1.20.9

### Which version of pip are you using?
23.1.2

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
  
</details>

### What is the result that you expected?

```
TypeError: not expecting type '<class 'uuid.UUID'>'
  File "ddtrace/span.py", line 383, in set_tag_str
    self._meta[key] = ensure_text(value, errors="replace")
  File "six.py", line 955, in ensure_text
    raise TypeError("not expecting type '%s'" % type(s))
```

**Comment by emmettbutler** [comment]
Thanks for reporting this crash, @swong-wavefin. From my reading of the [Django documentation](https://docs.djangoproject.com/en/4.2/ref/contrib/auth/#django.contrib.auth.models.User.username), setting `User.username` to a UUID object doesn't seem to be a supported use case. Is this something that's commonly done, and is there documentation for it somewhere?

If it's a documented use case for Django, we'll easily be able to add support for it to ddtrace. If not, it might make sense for you to apply one of the following workarounds:
* set the environment variable `DD_DJANGO_INCLUDE_USER_NAME=0`
* set the username to the result of `UUID.hex` (a string)

Thanks again, and please let me know if there's documentation somewhere about this approach that I'm missing.

**Comment by swong-wavefin** [comment]
Hi @emmettbutler 
I think string is default username type in django. 
We are using custom user model in our project. USERNAME_FIELD is UUID because it's a unique identifier (though [Django doc](https://docs.djangoproject.com/en/4.2/topics/auth/customizing/#specifying-custom-user-model) still suggest to use CharField in the example)  

That make sense to follow document in Django. I am going to ignore logged warning or set DJANGO_INCLUDE_USER_NAME as suggested.
Let me know if casting as str could be updated in ddtrace library. Thanks

**Comment by emmettbutler** [comment]
Thanks @swong-wavefin. My interpretation of the documentation is that the username field is expected to be a string, so I recommend setting it to `UUID().hex` instead of `UUID()`.  I don't think any changes to ddtrace to support UUID usernames are appropriate in this case.

Thanks again for the contribution!
