### ISSUE TITLE
[Question] Tracing the stdlib like subprocess?

### ISSUE THREAD

**Issue by wklken** [DataDog/dd-trace-py#784]
We have some python applications execute command via `subprocess`

like

```python
import subprocess
subprocess.call(["ls", "-l"])
```

Currently, the `dd-trace-py` do not patch the stdlib, so we don't know the time spent on the `subprocess.call`.

After reading the doc, it may be done by adding a function calling the `subprocess.call` with [decorator](http://pypi.datadoghq.com/trace/docs/basic_usage.html#decorator) or [context-manager](http://pypi.datadoghq.com/trace/docs/basic_usage.html#context-manager)

Is there any chance to patch it ?(maybe it better not to patch stdlib by default)

**Comment by brettlangdon** [comment]
@wklken sorry for the delay in replying here, but yeah, we try to be very conservative when it comes to patching the standard library.

Based on what we have available today, I would personally use a context manager for this.

```python
import subprocess

from ddtrace import tracer


with tracer.trace('subprocess.call') as span:
    subprocess.call(['ls', '-l'])
```

The context manager will pick up on any exceptions thrown from the `subprocess.call`, and you can add custom tags to `span` as well based on the results from your command, etc.


Let me know if you need any other help with this!

**Comment by wklken** [comment]
Thanks @brettlangdon , currently we use the context manager for subprocess tracing :)
