### ISSUE TITLE
Context cannot be pickled because _span_links are missing in __getstate__

### ISSUE THREAD

**Issue by Igosuki** [DataDog/dd-trace-py#7849]
### Summary of problem

We use pickle to serialize dd-trace contexts across distributed tasks so we can keep meta attributes, spans etc.
With the latest versions (2.3.0 onwards) a span_links attribute was introduced, which was not added to getstate and setstate, making repr break when the pickled Context gets reloaded.

### Which version of dd-trace-py are you using?
2.3.1

### Which version of pip are you using?
22.3.1

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
  
</details>

### How can we reproduce your problem?
Trace anything and do a decode/encode roundtrip :
```
from ddtrace import tracer
from ddtrace.context import Context
import codecs, pickle
with tracer.trace("my_trace"):
  ctx =  tracer.current_trace_context()
  b = codecs.encode(pickle.dumps(ctx), "base64")
  pickle.loads(codecs.decode(b, "base64"))
```

### What is the result that you get?
AttributeError: 'Context' object has no attribute '_span_links'

### What is the result that you expected?
A Context instance

**Comment by emmettbutler** [comment]
Thank you for the issue report, @Igosuki. I tried a few different ways to replicate the problem, and haven't been able to. From what I can see, the lack of `_span_links` in `__getstate__` and `__setstate__` isn't breaking the serializability of the `Context` object.

What might I be missing that would help me replicate the behavior you're experiencing? Thanks again.
