### ISSUE TITLE
Loss of auto generated APM metrics for FastAPI when upgrading to 2.3

### ISSUE THREAD

**Issue by saroh** [DataDog/dd-trace-py#7850]
### Summary of problem
A couple of teams within our org have reported that upgrading to `ddtrace` 2.3 has resulted in the loss of the `fastapi.request` operation which was autogenerated for this framework.

Rolling back `ddtrace` to 2.2 or 2.1 allowed us to get the metrics back.

### Which version of dd-trace-py are you using?
2.3.1

### Which version of pip are you using?
pip 23.2.1
poetry 1.61

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
algoliasearch==3.0.0
amqp==5.2.0
annotated-types==0.6.0
anyio==3.7.1
attrs==23.1.0
Babel==2.13.1
[some internal libs]
backoff==2.2.1
billiard==4.2.0
boto3==1.33.1
botocore==1.33.1
bytecode==0.14.2
cattrs==23.2.3
celery==5.3.6
celery-types==0.20.0
certifi==2023.11.17
cffi==1.16.0
cfgv==3.4.0
charset-normalizer==3.3.2
click==8.1.7
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
colorama==0.4.6
coverage==7.3.2
cryptography==36.0.2
datadog==0.47.0
ddsketch==2.0.4
ddtrace==2.3.1
Deprecated==1.2.14
deprecation==2.1.0
distlib==0.3.7
docker==6.1.3
envier==0.4.0
fastapi==0.104.1
filelock==3.13.1
ghp-import==2.1.0
graphql-core==3.2.3
greenlet==3.0.1
gunicorn==21.2.0
h11==0.14.0
hishel==0.0.19
httpcore==1.0.2
httptools==0.6.1
httpx==0.25.2
hypothesis==6.91.0
hypothesis-graphql==0.11.0
hypothesis-jsonschema==0.23.0
identify==2.5.32
idna==3.6
importlib-metadata==4.13.0
iniconfig==2.0.0
jaraco.classes==3.3.0
jeepney==0.8.0
Jinja2==3.1.2
jmespath==1.0.1
jsonschema==4.20.0
jsonschema-specifications==2023.11.2
junit-xml==1.9
jwcrypto==1.5.0
keyring==24.3.0
keyrings.codeartifact==1.2.0
kombu==5.3.4
langcodes==3.3.0
Markdown==3.5.1
MarkupSafe==2.1.3
mergedeep==1.3.4
mkdocs==1.5.3
mkdocs-material==9.4.14
mkdocs-material-extensions==1.3.1
more-itertools==10.1.0
multidict==6.0.4
mypy==1.7.1
mypy-extensions==1.0.0
nodeenv==1.8.0
opentelemetry-api==1.16.0
packaging==23.2
paginate==0.5.6
pathspec==0.11.2
platformdirs==4.0.0
pluggy==1.3.0
pre-commit==3.5.0
problem-detail-lib==0.2.2
prompt-toolkit==3.0.41
protobuf==4.25.1
pycparser==2.21
pydantic==2.5.2
pydantic-settings==2.1.0
pydantic_core==2.14.5
Pygments==2.17.2
PyJWT==2.8.0
pymdown-extensions==10.5
pyrate-limiter==2.10.0
pytest==7.4.3
pytest-asyncio==0.21.1
pytest-cov==4.1.0
pytest-subtests==0.7.0
python-dateutil==2.8.2
python-dotenv==1.0.0
PyYAML==6.0.1
pyyaml_env_tag==0.1
ratelimitingfilter==1.2
redis==5.0.0
referencing==0.31.1
regex==2023.10.3
requests==2.31.0
rpds-py==0.13.2
ruamel.yaml==0.18.5
ruamel.yaml.clib==0.2.8
s3transfer==0.8.0
schemathesis==3.22.0
SecretStorage==3.3.3
sentry-sdk==1.38.0
setuptools==69.0.2
six==1.16.0
sniffio==1.3.0
sortedcontainers==2.4.0
SQLAlchemy==2.0.23
starlette==0.27.0
starlette-testclient==0.2.0
testcontainers==3.7.1
tomli==2.0.1
tomli_w==1.0.0
tomlkit==0.12.3
types-PyYAML==6.0.12.12
types-requests==2.31.0.0
types-urllib3==1.26.25.14
typing_extensions==4.8.0
tzdata==2023.3
urllib3==2.1.0
uvicorn==0.24.0.post1
uvloop==0.19.0
vine==5.1.0
virtualenv==20.25.0
watchdog==3.0.0
watchfiles==0.21.0
wcwidth==0.2.12
websocket-client==1.6.4
websockets==12.0
Werkzeug==3.0.1
wrapt==1.16.0
xmltodict==0.13.0
yarl==1.9.3
zipp==3.17.0

</details>

### How can we reproduce your problem?
Unsure you can, hopefully bootstrap a simple fastapi example and run it with ddtrace.
### What is the result that you get?
No `fastapi.request` operation in the APM

### What is the result that you expected?
`fastapi.request` operation reported in the APM

**Comment by emmettbutler** [comment]
Thanks for the report, @saroh. At first glance I can't see a reason why `fastapi.request` spans would have stopped being sent - in fact we have a bunch of automated tests that confirm it's still sent in many common use cases ([example](https://github.com/DataDog/dd-trace-py/blob/a97914751d3bc8845f7491f9e9e36e91c5f5142d/tests/snapshots/tests.contrib.fastapi.test_fastapi.test_tracing_in_middleware.json#L3)).

With more details about the particular situation you're using ddtrace in, we can debug this issue further. Filing a support ticket at help.datadoghq.com is probably the best way to do that, since you'll likely want to provide some non-public information about your setup.

If there's anything else we can do on this public ticket to more clearly replicate the issue you're experiencing, please let me know. Thanks!
