### ISSUE TITLE
The error list index out of range on langchain

### ISSUE THREAD

**Issue by beobeboi** [DataDog/dd-trace-py#7851]
### Summary of problem
I faced the issue `list index out of range` when ddtrace with langchain on ddtrace/contrib/langchain/patch.py in traced_embedding at line 553
`embeddings = func(*args, **kwargs)
        if isinstance(embeddings, list) and isinstance(embeddings[0], list):`
The problem happen by when I am trying to convert a pdf with image to vector without install python tesseract
### Which version of pip are you using?
23.2.1

### Which libraries and their versions are you using?
langchain 0.0.344
<details>
  <summary>`pip freeze`</summary>
  
</details>

### How can we reproduce your problem?
Use a langchain for pdf with image and do not use python tesseract

### What is the result that you get?
Error: list index out of range

### What is the result that you expected?
Should not throw any error

**Comment by Yun-Kim** [comment]
Hi @beobeboi, could you give us steps (preferably a code block of what you're running) to reproduce this? I'm not understanding what you mean by `use a langchain for pdf with image`, as that shouldn't affect embeddings by itself. Thanks!

**Comment by beobeboi** [comment]
Hello, @Yun-Kim, let me explain:
We currently parse material from PDFs using Langchain and Unstructured, then store it as a vector in Postgresql. In addition, we use ddtrace to track openAI and langchain queries.
Calling the function 'PGVector.from_documents' with an empty document produces the issue I indicated in the ticket description.
`
"""
        Store embed documents in a PostgreSQL database.

        :param documents: list of Documents
        :return:
        """
        embeddings = OpenAIEmbeddings(
            client=None,
            openai_api_key=self.__openai_api_key,
            model=EMBEDDING_MODEL,
        )

        return PGVector.from_documents(
            documents=documents,
            embedding=embeddings,
            collection_name=self.organisation_uuid,
            collection_metadata={"organisation_name": self.organisation_name},
            distance_strategy=DistanceStrategy.COSINE,
            connection_string=self.__connection_string,
            ids=[self.document_uuid] * len(documents),
        )

`
