### ISSUE TITLE
Add ability to set global tags in code (alternative to DD_TAGS)

### ISSUE THREAD

**Issue by idanya** [DataDog/dd-trace-py#7872]
Currently, the only way to set global tags that will be attached to all spans is by using `DD_TAGS` environment variable (unless I'm missing something). 
This is an issue for use cases where the service tags are loaded on runtime. 

Possible mitigation:
Setting the config/tracer with the global tags at runtime

version used: dd-trace-py 2.1.1

**Comment by emmettbutler** [comment]
Thanks for noting this request, @idanya. We'll add it to our feature request backlog and it will be included in future prioritization passes.

**Comment by Eckhart-csjc** [comment]
Is there ab alternative available now?  I sure would like to see this resurrected.
