### ISSUE TITLE
datadog equivalent of tracing a function

### ISSUE THREAD

**Issue by ekimia** [DataDog/dd-trace-py#788]
with newrelic, they have a `function_trace` decorator which we can use to see additional information (function calls and duration) for a particular view. Anything like this for ddtrace?

ref: https://docs.newrelic.com/docs/agents/python-agent/python-agent-api/function_trace

**Comment by brettlangdon** [comment]
@ekimia thank you for reaching out, unfortunately we do not have a feature like this yet.
