### ISSUE TITLE
Trace id mismatch in logging and APM in 2.x version

### ISSUE THREAD

**Issue by skuam** [DataDog/dd-trace-py#7883]
### Summary of problem
I run Django application. 
I encountered the problem with our logs and traces when they started to miss match traces in APM and in logs, meaning the trace_id in logs were different. For logs, we use struclogs with this config from documentation:
```python
def tracer_injection(logger, log_method, event_dict):
    # get correlation ids from current tracer context
    span = tracer.current_span()
    trace_id, span_id = (span.trace_id, span.span_id) if span else (None, None)

    # add ids to structlog event dictionary
    event_dict['dd.trace_id'] = str(trace_id or 0)
    event_dict['dd.span_id'] = str(span_id or 0)

    # add the env, service, and version configured for the tracer
    event_dict['dd.env'] = ddtrace.config.env or ""
    event_dict['dd.service'] = ddtrace.config.service or ""
    event_dict['dd.version'] = ddtrace.config.version or ""
    return event_dict


# in setting.py
LOGGING_PROCESSOR = [
    structlog.contextvars.merge_contextvars, 
    tracer_injection,
    structlog.processors.TimeStamper(fmt="iso"),
    structlog.stdlib.add_logger_name,
    structlog.stdlib.add_log_level,
    structlog.processors.CallsiteParameterAdder(),
    structlog.processors.StackInfoRenderer(),
    structlog.processors.format_exc_info,
    structlog.stdlib.PositionalArgumentsFormatter(),
    structlog.processors.UnicodeDecoder(),
    structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
]

```

### Which version of dd-trace-py are you using?

In begging, I was using ddtrace==2.3.1 and now downgraded to ddtrace==1.20.14

### Which version of pip are you using?
pip --version
pip 23.3.1 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)

### Which libraries and their versions are you using?

Not related

### How can we reproduce your problem?

Collecting traces with version 1.20.14 and 2.3.1 and looking if traces id match for the same trace

### What is the result that you get?

When running the 2.x traces, they look different from in version 1.x and the way to generate trace_id and span differ.
Example trace in 1.x 11338093727575270596 (both in APM and in logs) 
Example trace in 2.x 6576041900000000d4ade98381c0d1bb (only in APM)

Please fix the ` span = tracer.current_span()` in 2.x so it returns trace_id consistent with the one given by APM 

### What is the result that you expected?
Same format of trace_id

**Comment by emmettbutler** [comment]
Thanks for reporting this behavior, @skuam. We'll look into it!

@mabdinur do you think this could be the result of intentional major-version trace ID changes?

**Comment by mabdinur** [comment]
Hi @skuam, 

Thanks for opening this issue. All Datadog tracers are migrating from 64bit trace ids to 128bit trace ids. This will improve the interoperability of Datadog and OpenTelemetry traces. 

## Background

With the release of `ddtrace 2.0` the python tracer generates 128 bit trace ids (by default) but only logs the lower order 64bits. This ensures Datadog and OpenTelemetry traces are interoperable while maintaining backwards compatibility with Datadog's Logs product. This is a temporary measure. In the near future the python tracer will generate AND log 128 bit trace ids. The generation of 128 bit trace ids should not break log correlation and you should be able to query traces using both the 128bit and 64bit trace id. 

## Mitigation

To log and generate 64bit trace ids (ie revert to 1.x functionality) you can set ``DD_TRACE_128_BIT_TRACEID_GENERATION_ENABLED=False``: https://ddtrace.readthedocs.io/en/stable/configuration.html#DD_TRACE_128_BIT_TRACEID_GENERATION_ENABLED.

Feel free to reopen this issue if this mitigation is not sufficient.

**Comment by xxthegonzxx** [comment]
For what it's worth, it looks like this is still an issue. We're using the newest version of ddtrace-py 2.x and we're seeing 128 bit trace_id's in APM using Django's auto-instrumentation feature with 64-bit trace_ids in our logs. They're not being correlated unless I specifically disable 128 bit trace_ids by using: `DD_TRACE_128_BIT_TRACEID_GENERATION_ENABLED=False`

**Comment by xxthegonzxx** [comment]
> For what it's worth, it looks like this is still an issue. We're using the newest version of ddtrace-py 2.x and we're seeing 128 bit trace_id's in APM using Django's auto-instrumentation feature with 64-bit trace_ids in our logs. They're not being correlated unless I specifically disable 128 bit trace_ids by using: `DD_TRACE_128_BIT_TRACEID_GENERATION_ENABLED=False`

Turns out we are using a pulling in our own custom library that is using ddtrace version `2.0.2` to log certain traces/spans but are also using ddtrace 2.3.0 within the same application in other places, which I think is causing the issues. My suspicion is that the version using 2.0.2 is using 64 bit trace_ids in the logs but defaults to the latest version of ddtrace (2.3.0) for the django framework APM traces which causes a mismatch.
