### ISSUE TITLE
ddtrace and zipkin compatibility 

### ISSUE THREAD

**Issue by JoeHitHard** [DataDog/dd-trace-py#789]
The data format sent by ddtrace is not compatible with zipkin, I  am working on a python django web-framework, I followed all the config's for django and set  `DATADOG_TRACE['AGENT_PORT']=9411` (fyi: 9411 is port of ZIPKIN) and when ddtrace is sending the data it is throwing this error,
```
ERROR:ddtrace.writer:failed_to_send traces to Agent: HTTP error status 404, reason Not Found, message Content-Encoding: identity
Connection: keep-alive
vary: origin
Transfer-Encoding: chunked
Content-Type: application/json;charset=UTF-8
```

**Comment by brettlangdon** [comment]
@JoeHitHard unfortunately `ddtrace` is not compatible with Zipkin. It is meant to be used with our agent and platform: https://docs.datadoghq.com/agent/apm/?tab=agent630
