### ISSUE TITLE
Psycopg3TracedAsyncCursor's __aexit__ incorrect return value stops exception propagation

### ISSUE THREAD

**Issue by fers490** [DataDog/dd-trace-py#7900]
### Summary of problem
Psycopg3TracedAsyncCursor's __aexit__ method is incorrectly returning a truthy value, causing exceptions thrown inside the cursor's context to be ignored and not propagated outside the context.
The relevant code is on [async_cursor.py](https://github.com/DataDog/dd-trace-py/blob/main/ddtrace/contrib/psycopg/async_cursor.py) (line 25). The code doesn't even match the method typing definition (it states it will return a None as the original psycopg cursor does).

### Which version of dd-trace-py are you using?
v2.3.1

### Which version of pip are you using?
23.1.2

### How can we reproduce your problem?

Just raise an exception inside an async cursor context with patched code. The exception will be caught and not propagated
up the call stack.
```
async with await psycopg.AsyncConnection.connect(
        "dbname=test user=postgres") as aconn:
    async with aconn.cursor() as acur:
        raise Exception('Testing')
```

### What is the result that you get?
The exception is caught and not propagated up the call stack

### What is the result that you expected?
The exception should be propagated so it can be addressed outside the cursor context.

**Comment by emmettbutler** [comment]
Thanks for bringing this to our attention, @fers490. We'll take a look!

**Comment by fers490** [comment]
Thanks for fixing it so soon!
