### ISSUE TITLE
logging module doesn't work with async code

### ISSUE THREAD

**Issue by carlosperello** [DataDog/dd-trace-py#792]
The new logging module is using `get_correlation_ids` which uses `tracer.current_span()` which uses `context.get_current_span()` which clearly states: 

> Return the last active span that corresponds to the last inserted
> item in the trace list. This cannot be considered as the current active
> span in asynchronous environments, because some spans can be closed
> earlier while child spans still need to finish their traced execution.

Which causes a zero value always for the span_id or trace_id parameters on `aiohttp`'s logs.

**Comment by carlosperello** [comment]
I did some testing and found that in this concrete case with async code using `context.trace_id` and `context.span_id` if `span` is None, it has the right information, or at least it matches the APM trace spans on my tests.
Sharing it in case it helps fixing the issue...

**Comment by majorgreys** [comment]
@carlosperello Thanks for looking at this further! If possible, could you provide a reproducible example for the case you are finding this issue?

**Comment by majorgreys** [comment]
@carlosperello I wasn't able to reproduce this issue with async code on my end. Can you confirm this is still an issue?

**Comment by carlosperello** [comment]
We can discard this issue, it was a problem on my side, the ddtrace patching was done after logger initialization, and thus, I was getting wrong data there... Doing the patch before any system import fixes the issue.

Thanks and sorry for the noise.

**Comment by brettlangdon** [comment]
@carlosperello not a problem at all, glad you were able to find a solution to your problem.

Please do not hesitate to reach out with any other issues in the future!
