### ISSUE TITLE
Error `tornado.request` trace doesn't appear on the `Total Error` graph. APM!

### ISSUE THREAD

**Issue by andela-sjames** [DataDog/dd-trace-py#793]
After using the doc as recommended logs and trace are successfully sent to Datadog agent 👍 , but when you check the Total Error graph from the GUI, the errors do not show up or get populated. 

<img width="825" alt="dd_full" src="https://user-images.githubusercontent.com/13233374/51147734-af152580-185b-11e9-8c5c-b57106583a0e.png">

<img width="779" alt="dd_nil" src="https://user-images.githubusercontent.com/13233374/51147814-f996a200-185b-11e9-9f28-d839fae582e9.png">

Error present but datadog apm can't/doesn't see it to show it on the error graph.

**Comment by majorgreys** [comment]
@andela-sjames Thank you for reporting this issue.

Along with versions of the libraries, can you also share a debug log of the traces with `DATADOG_TRACE_DEBUG=true`?

https://docs.datadoghq.com/tracing/advanced_usage/?tab=python#debugging

**Comment by andela-sjames** [comment]
I created a ticket and sent a flare as well in response to the email I received. @majorgreys

**Comment by andela-sjames** [comment]
Here is the ticket number for reference : (#191962)

**Comment by majorgreys** [comment]
Closing since we have a support ticket tracking this already.
