### ISSUE TITLE
gunicorn access log lines have dd.trace_id=0 

### ISSUE THREAD

**Issue by alex-kowalczyk** [DataDog/dd-trace-py#7962]
### Summary of problem
When running instrumented **django+gunicorn** app with access log enabled, `dd.trace_id` values are not set properly for top-level access log (`gunicorn.access`). 

While Django displays access log lines by itself in 'manage.py runserver', this is not the case when served behind **gunicorn**. In that production recommended config Django would emit only access log lines for `status >= 400`. 

So enabling `gunicorn.access` is the proper way to display all access logs. Having `dd.trace_id` on them is crucial to correlate "master-detail", ie. detailed log lines with specific request.

### Which version of dd-trace-py are you using?
2.4.0rc1

### Which version of pip are you using?
poetry 1.6.1

### Which libraries and their versions are you using?
django                         4.2.7
gunicorn                       20.1.0

### How can we reproduce your problem?
Run instrumented gunicorn with `--access-logfile -` option, which enables access log for all requests (not only failed ones).
```
DD_ENV=LOCALHOST DD_LOGS_INJECTION=true DD_SERVICE=LOCALHOST DD_VERSION=LOCALHOST \
ddtrace-run gunicorn --access-logfile - module:app
```

Same bug occurs when run with non-instrumented gunicorn and `import ddtrace.auto` in Django's `settings.py` (this way allows to debug and put breakpoints/logpoints).

Django logging config:
```
    LOGGING = {
        'version': 1,
        'formatters': {
            'ddtrace': {
                'format': ('%(asctime)s %(levelname)s [%(name)s] [%(filename)s:%(lineno)d] '
                 '[dd.service=%(dd.service)s dd.env=%(dd.env)s '
                 'dd.version=%(dd.version)s '
                 'dd.trace_id=%(dd.trace_id)s dd.span_id=%(dd.span_id)s] '
                 '- %(message)s'),
            }
        },
        'handlers': {
            'console': {
                'level': 'DEBUG',
                'class': 'logging.StreamHandler',
                'formatter': 'ddtrace'
            },
        },
        'loggers': {
            '': {
                'handlers': ['console'],
                'level': 'DEBUG'
            },
            "gunicorn.access": {
                'level': 'DEBUG',
                'handlers': ['console'],
                'filters': ['request'],
                'propagate': False
            }
        }
    }
```

### What is the result that you get?
The top-level `gunicorn.access` has `dd.trace_id=0`. Only the detailed lines emitted inside the request handler are properly annotated with trace.  

```
2023-12-20 13:50:43,496 DEBUG [root] [middleware.py:706] [dd.service=LOCALHOST dd.env=LOCALHOST dd.version=LOCALHOST dd.trace_id=16479745745090217897 dd.span_id=16227831817129083363] - detailed log line
2023-12-20 13:50:43,884 INFO [gunicorn.access] [glogging.py:349] [dd.service=LOCALHOST dd.env=LOCALHOST dd.version=LOCALHOST dd.trace_id=0 dd.span_id=0] - 127.0.0.1 - - [20/Dec/2023:13:50:43 +0000] "GET / HTTP/1.1" 302 0 "-" "curl agent"
```
Setting a logpoint on `span.py:271` (`Span.finish`) with `(self.trace_id, self.span_id, self)` content displays that the trace is finished before gunicorn access log line is emitted.

```
2023-12-20 13:50:43,496 DEBUG [root] [middleware.py:706] [dd.service=LOCALHOST dd.env=LOCALHOST dd.version=LOCALHOST dd.trace_id=16479745745090217897 dd.span_id=16227831817129083363] - detailed log line
(134931918188008636537262274320961079209, 16227831817129083363, <Span(id=16227831817129083363,trace_id=134931918188008636537262274320961079209,parent_id=6856971614390104096,name=django.middleware)>)
[...]
(134931918188008636537262274320961079209, 6705879339268237911, <Span(id=6705879339268237911,trace_id=134931918188008636537262274320961079209,parent_id=6823092686602671400,name=django.middleware)>)
(134931918188008636537262274320961079209, 6823092686602671400, <Span(id=6823092686602671400,trace_id=134931918188008636537262274320961079209,parent_id=None,name=django.request)>)
2023-12-20 13:50:43,884 INFO [gunicorn.access] [glogging.py:349] [dd.service=LOCALHOST dd.env=LOCALHOST dd.version=LOCALHOST dd.trace_id=0 dd.span_id=0] - 127.0.0.1 - - [20/Dec/2023:13:50:43 +0000] "GET / HTTP/1.1" 302 0 "-" "curl agent"
```

### What is the result that you expected?
The trace ID should span to top of the request, including the `gunicorn.access` log line.

**Comment by brettlangdon** [comment]
@alex-kowalczyk thank you for opening this issue.

The reason it doesn't work is exactly as you point out. Because we instrument the Python framework the request span is finished by the time gunicorn logs.

We haven't had a chance to look into how we can make it work (e.g. do we need a gunicorn tracing integration, or is there a way for us to programmatically give gunicorn some extra logging info?). I am going to mark this a feature request since it is working as "intended", but we can definitely do better here.

**Comment by MitchellMcKenna** [comment]
@brettlangdon Any updates on getting gunicorn access-logs working with ddtrace?

@alex-kowalczyk What did you end up doing as a workaround?
