### ISSUE TITLE
Loguru integration only works after adding a new sink

### ISSUE THREAD

**Issue by connorbrinton** [DataDog/dd-trace-py#7988]
### Summary of problem

I'm trying to set up a production app to log messages in JSON format using Loguru with Datadog trace and span IDs included in the serialized JSON output. [This Datadog documentation](https://ddtrace.readthedocs.io/en/stable/integrations.html#loguru) states that Loguru can be automatically patched using `ddtrace-run` by setting the environment variable `DD_LOGS_INJECTION=true`. Additionally, [this Loguru documentation](https://loguru.readthedocs.io/en/stable/api/logger.html#env) indicates that JSON-serialized output can be requested using `LOGURU_SERIALIZE=true`. Based on this documentation, I ran:

```console
$ DD_LOGS_INJECTION=true DD_ENV=local LOGURU_SERIALIZE=true ddtrace-run python -c 'from loguru import logger; logger.info("Hello world")'
{"text": "2023-12-22 17:23:16.035 | INFO     | __main__:<module>:1 - Hello world\n", "record": {"elapsed": {"repr": "0:00:00.004042", "seconds": 0.004042}, "exception": null, "extra": {}, "file": {"name": "<string>", "path": "<string>"}, "function": "<module>", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 1, "message": "Hello world", "module": "<string>", "name": "__main__", "process": {"id": 14, "name": "MainProcess"}, "thread": {"id": 281473772081184, "name": "MainThread"}, "time": {"repr": "2023-12-22 17:23:16.035797+00:00", "timestamp": 1703265796.035797}}}
```

I successfully obtained JSON output from Loguru, but no Datadog information is included in the log message.

Based on further experimentation, it appears that once a new sink has been added to Loguru, all log messages include Datadog tracing information (even those emitted by the original sink). For example:
```console
$ DD_LOGS_INJECTION=true DD_ENV=local LOGURU_SERIALIZE=true ddtrace-run python -c 'from loguru import logger; logger.add("/dev/null"); logger.info("Hello world")'
{"text": "2023-12-22 17:24:16.143 | INFO     | __main__:<module>:1 - Hello world\n", "record": {"elapsed": {"repr": "0:00:00.006569", "seconds": 0.006569}, "exception": null, "extra": {"dd.trace_id": "0", "dd.span_id": "0", "dd.env": "local", "dd.service": "", "dd.version": ""}, "file": {"name": "<string>", "path": "<string>"}, "function": "<module>", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 1, "message": "Hello world", "module": "<string>", "name": "__main__", "process": {"id": 20, "name": "MainProcess"}, "thread": {"id": 281473861623840, "name": "MainThread"}, "time": {"repr": "2023-12-22 17:24:16.143068+00:00", "timestamp": 1703265856.143068}}}
```

To work around this issue, I can clear the sinks and add a new default logger during my application's startup, but it would be nice if `ddtrace-run` could also patch the default sink added to the logger 😄

Thank you for maintaining this project! ❤️

### Which version of dd-trace-py are you using?

2.4.0

### Which version of pip are you using?

23.2.1

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
attrs==23.1.0
bytecode==0.15.1
cattrs==23.2.3
ddsketch==2.0.4
ddtrace==2.4.0
Deprecated==1.2.14
envier==0.5.0
importlib-metadata==6.11.0
loguru==0.7.2
opentelemetry-api==1.22.0
protobuf==4.25.1
setuptools==69.0.2
six==1.16.0
typing_extensions==4.9.0
wheel==0.42.0
wrapt==1.16.0
xmltodict==0.13.0
zipp==3.17.0
</details>

### How can we reproduce your problem?

```console
$ pip install --quiet ddtrace loguru
$ DD_LOGS_INJECTION=true DD_ENV=local LOGURU_SERIALIZE=true ddtrace-run python -c 'from loguru import logger; logger.info("Hello world")'
```

### What is the result that you get?

```json
{"text": "2023-12-22 17:23:16.035 | INFO     | __main__:<module>:1 - Hello world\n", "record": {"elapsed": {"repr": "0:00:00.004042", "seconds": 0.004042}, "exception": null, "extra": {}, "file": {"name": "<string>", "path": "<string>"}, "function": "<module>", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 1, "message": "Hello world", "module": "<string>", "name": "__main__", "process": {"id": 14, "name": "MainProcess"}, "thread": {"id": 281473772081184, "name": "MainThread"}, "time": {"repr": "2023-12-22 17:23:16.035797+00:00", "timestamp": 1703265796.035797}}}
```

### What is the result that you expected?

```json
{"text": "2023-12-22 17:24:16.143 | INFO     | __main__:<module>:1 - Hello world\n", "record": {"elapsed": {"repr": "0:00:00.006569", "seconds": 0.006569}, "exception": null, "extra": {"dd.trace_id": "0", "dd.span_id": "0", "dd.env": "local", "dd.service": "", "dd.version": ""}, "file": {"name": "<string>", "path": "<string>"}, "function": "<module>", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 1, "message": "Hello world", "module": "<string>", "name": "__main__", "process": {"id": 20, "name": "MainProcess"}, "thread": {"id": 281473861623840, "name": "MainThread"}, "time": {"repr": "2023-12-22 17:24:16.143068+00:00", "timestamp": 1703265856.143068}}}
```

**Comment by mabdinur** [comment]
Hey @connorbrinton, 

Thanks for opening this issue. This is a great find!

The ddtrace loguru integration [intercepts](https://github.com/DataDog/dd-trace-py/blob/f9867c633286d1e8a3ab6a24f1dd65fead8ceca3/ddtrace/contrib/loguru/patch.py#L65) all invocations of `loguru.logger.add(...)` and then calls `logger.configure` to ensure ddtrace fields are added to the log format. This approach works well most of the time. In your reproduction the ddtrace loguru integration is enabled **after** `loguru.logger` is imported. So [this](https://github.com/Delgan/loguru/blob/0.7.2/loguru/__init__.py#L31) invocation of `loguru.logger.add(....)` is never intercepted. Adding a new sink to triggers the ddtrace interceptors to format the loguru logger. This is why your second reproduction works as expected.

I opened a fix to resolve this quirky behavior.
