### ISSUE TITLE
CHANGELOG links are broken

### ISSUE THREAD

**Issue by hauntsaninja** [DataDog/dd-trace-py#7999]
The link in https://github.com/DataDog/dd-trace-py/blob/main/CHANGELOG.md is broken

This link seems live: https://ddtrace.readthedocs.io/en/v1.16.0/release_notes.html
But the latest, stable and most v2 tags I tried are broken:
https://ddtrace.readthedocs.io/en/latest/release_notes.html
https://ddtrace.readthedocs.io/en/stable/release_notes.html
https://ddtrace.readthedocs.io/en/v2.4.0/release_notes.html

**Comment by emmettbutler** [comment]
Thanks for pointing this out, @hauntsaninja. That link was broken by https://github.com/DataDog/dd-trace-py/pull/7185. I'll fix it.
