### ISSUE TITLE
ImportError  cannot import name '_build_git_packfiles_with_details' from 'ddtrace.ext.git'

### ISSUE THREAD

**Issue by pmourlanne** [DataDog/dd-trace-py#8001]
### Summary of problem

On start-up, Sentry picks up the following error: `ImportError: cannot import name '_build_git_packfiles_with_details' from 'ddtrace.ext.git'`. We indeed don't see any traces in Datadog following this error.

The final error is `AttributeError: module 'our-project-name' has no attribute 'logging'`.

This issue appeared once we upgraded to dd-trace-py 2.4.0. I suspect https://github.com/DataDog/dd-trace-py/pull/7532 to be the culprit. I also don't understand why internal imports about ci visibility are run in our live environments.

### Which version of dd-trace-py are you using?

2.4.0

### Which version of pip are you using?

pip 23.3.2

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
$ pip freeze
amqp==5.1.1
analytics-python==1.2.9
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
asgiref==3.7.2
asttokens==2.2.1
attrs==23.1.0
awscli==1.29.85
backcall==0.2.0
billiard==3.6.4.0
boto3==1.28.80
botocore==1.31.85
bytecode==0.14.2
cached-property==1.5.2
cachetools==5.3.1
cattrs==23.1.2
celery==5.2.7
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.3
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
colorama==0.4.4
cryptography==41.0.7
datadog-api-client==1.12
ddsketch==2.0.4
ddtrace==2.4.0
decorator==5.1.1
defusedxml==0.7.1
Deprecated==1.2.14
Django==4.2.8
django-admin-autocomplete-filter==0.7.1
django-admin-inline-paginator==0.3.0
django-admin-rangefilter==0.10.0
django-adminfilters==2.0.4
django-autocomplete-light==3.9.4
django-better-choices==1.17
django-cors-headers==3.11.0
django-countries==7.1
django-db-views==0.1.5
django-environ==0.11.2
django-extensions==3.2.3
django-filter==22.1
django-jsonform==2.17.0
django-localflavor==3.1
django-otp==1.1.6
django-pgtrigger==4.6.0
django-rosetta==0.9.5
django-simple-history==3.0.0
django-storages==1.13.2
djangorestframework==3.14.0
djangorestframework-camel-case==1.3.0
docutils==0.16
envier==0.4.0
exceptiongroup==1.1.2
executing==1.2.0
gocardless-pro==1.49.0
google-auth==2.22.0
google-auth-oauthlib==1.0.0
greenlet==2.0.2
gspread==3.7.0
gunicorn==20.1.0
idna==3.4
importlib-metadata==6.8.0
ipython==8.12.0
isodate==0.6.1
jedi==0.18.2
Jinja2==3.1.2
jmespath==1.0.1
kombu==5.2.4
lxml==4.9.3
MarkupSafe==2.1.3
matplotlib-inline==0.1.6
oauthlib==3.2.2
opentelemetry-api==1.19.0
parso==0.8.3
parsy==2.0
pdfkit==1.0.0
pexpect==4.8.0
pickleshare==0.7.5
platformdirs==3.9.1
polib==1.2.0
prompt-toolkit==3.0.39
protobuf==4.23.4
psycopg2==2.9.9
ptyprocess==0.7.0
pure-eval==0.2.2
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
Pygments==2.15.1
PyJWT==2.6.0
pypng==0.20220715.0
python-dateutil==2.8.2
python-json-logger==2.0.7
python-Levenshtein==0.12.2
python-stdnum==1.18
pytz==2023.3
PyYAML==6.0.1
qrcode==7.4.2
requests==2.31.0
requests-file==1.5.1
requests-oauthlib==1.3.1
requests-toolbelt==1.0.0
rsa==4.7.2
s3transfer==0.7.0
sentry-sdk==1.14.0
setproctitle==1.3.3
shortuuid==0.5.0
six==1.16.0
slack-sdk==3.26.1
SQLAlchemy==1.4.49
sqlparse==0.4.4
stack-data==0.6.2
stripe==5.4.0
systemdunitparser==0.2
thefuzz==0.19.0
toml==0.10.2
traitlets==5.9.0
typing_extensions==4.7.1
urllib3==1.26.18
vine==5.0.0
wcwidth==0.2.6
wrapt==1.15.0
xmltodict==0.13.0
zeep==4.1.0
zipp==3.16.2
</details>

### How can we reproduce your problem?

This happens as soon as we start our application :shrug:

### What is the result that you get?

As outlined above, an exception in Sentry, then no traces are sent to Datadog.

### What is the result that you expected?

No exception, and traces sent to Datadog.

**Comment by benjaminrigaud** [comment]
Hi, I am taking over this issue from @pmourlanne on our side.

We are reproducing the issue with `ddtrace==2.6.0` 

Digging into it :+1:

**Comment by benjaminrigaud** [comment]
I reproduced the issue only one time after the installation.

All subsequents service restarts worked correctly :crying_cat_face: 

I don't know if it is a good news or not: I have learned nothing and am not confident to move this update forward.

Just a hunch, but could it be related to the remote config change introduced in `2.4.0`?

**Comment by benjaminrigaud** [comment]
@romainkomorndatadog found something :+1: 

I was reloading our gunicorn service (with systemctl).

A **restart** is working properly!

I don't know if it expected: but a **reload** isn't properly reloading the code of the updated **ddtrace** library.

I'll dig a bit more that aspect to understand how we are reloading our service and if (and how) we are restarting the gunicorn workers or not.

**Comment by benjaminrigaud** [comment]
Reloading the service is sending a HUP signal to gunicorn: it restarts new workers.
These new workers should have a fresh and up-to-date ddtrace code.

But it still generates the `ModuleNotFoundError: No module named 'ddtrace.internal.core.event_hub'; 'ddtrace.internal.core' is not a package` as long as we don't restart.

https://docs.gunicorn.org/en/stable/signals.html#reload-the-configuration

Our service correctly respawning worker on a reload:

```
[2024-02-13 10:56:11 +0000] [316541] [INFO] Handling signal: hup
[2024-02-13 10:56:11 +0000] [316541] [INFO] Hang up: Master
[2024-02-13 10:56:11 +0000] [316908] [INFO] Booting worker with pid: 316908
[2024-02-13 10:56:11 +0000] [316547] [INFO] Worker exiting (pid: 316547)
[2024-02-13 10:56:11 +0000] [316551] [INFO] Worker exiting (pid: 316551)
[2024-02-13 10:56:11 +0000] [316549] [INFO] Worker exiting (pid: 316549)
[2024-02-13 10:56:11 +0000] [316910] [INFO] Booting worker with pid: 316910
[2024-02-13 10:56:11 +0000] [316911] [INFO] Booting worker with pid: 316911
[2024-02-13 10:56:12 +0000] [316541] [WARNING] Worker with pid 316549 was terminated due to signal 15
[2024-02-13 10:56:12 +0000] [316541] [WARNING] Worker with pid 316551 was terminated due to signal 15
[2024-02-13 10:56:12 +0000] [316541] [WARNING] Worker with pid 316547 was terminated due to signal 15
```

**Comment by benjaminrigaud** [comment]
I can reproduce the issue locally with the following steps:

- `ddtrace-run gunicorn my_app.wsgi:application`
- `pip install ddtrace -U`
- `kill -HUP $(pgrep -f "gunicorn: master")`

**Comment by benjaminrigaud** [comment]
`ddtrace-run` is most likely on of the causes:

When used, it loads `ddtrace` in the master process (and we won't be able to reload that code).
When not used, `ddtrace` is being loaded only in the workers.

A plausible explanation https://github.com/aio-libs/aiohttp/issues/2976#issuecomment-387011007

> Apparently whenever the Gunicorn master process starts a child process, the child process "inherits" whatever the master process has already imported.

**Comment by romainkomorndatadog** [comment]
I'm going to pass this off to @mabdinur for sorting since it's not a CI Visibility issue.

@benjaminrigaud many thanks for the repro/debugging help.
