### ISSUE TITLE
Problem with importlib.resources.files and ddtrace 2.4.0

### ISSUE THREAD

**Issue by gg-mmill** [DataDog/dd-trace-py#8003]
### Summary of problem

When using ddtrace 2.4.0, the `importlib.resources.files` function seems broken in some edge case (more precisions below)

### How can we reproduce your problem?

1. Have a folder that does not contain python code, but can still be loaded as a python module
2. Call the `importlib.resources.files` with this module
3. A `importlib._adapters.DegenerateFiles.Path ` is returned, instead of `MultiplexedPath`

### What is the result that you get?

```
Python 3.10.10 (main, Nov 21 2023, 12:11:43) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ddtrace
>>> ddtrace.__version__
'2.4.0'
>>> import importlib.resources
>>> importlib.resources.files("config.fixtures")
<importlib._adapters.DegenerateFiles.Path object at 0x7ff9afcf8280>
```

### What is the result that you expected?

```
Python 3.10.10 (main, Nov 21 2023, 12:11:43) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ddtrace
>>> ddtrace.__version__
'2.3.3'
>>> import importlib.resources
>>> importlib.resources.files("config.fixtures")
MultiplexedPath('/home/mmillet/dev/my-project/backend/config/fixtures')
```

**Comment by emmettbutler** [comment]
Thanks for the report, @gg-mmill. Can you be any more specific about how to create a python module that doesn't contain python code that could be used to replicate this issue?

**Comment by gg-mmill** [comment]
Hello, any empty folder in the python path would fit.

**Comment by jd** [comment]
We also have one app impacted by this and after spending some time bisecting, the culprit is #7727.
Here's the issue we're now seeing at startup:
```
...
mergify_shadow_office/routers/badges.py:23: in <module>
    _MERGIFY_LOGO_SVG = _read_text("mergify_shadow_office.static.img", "mergify-logo.svg")
mergify_shadow_office/routers/badges.py:20: in _read_text
    return importlib.resources.files(package).joinpath(resource).read_text()
E   FileNotFoundError: Can't open orphan path
```

Not sure which change has been done in this PR to make that happen, but it's a regression between 2.3 and 2.4.

@P403n1x87 any idea?

**Comment by P403n1x87** [comment]
@jd thanks for your analysis of the issue. I have opened #8603 to address this 🤞
