### ISSUE TITLE
Kafka error writing tag kafkax.TOMBSTONE if message is None

### ISSUE THREAD

**Issue by josumoreno-BP** [DataDog/dd-trace-py#8016]
### Summary of problem

ddtrace fails wiriting tag kafkax.TOMBSTONE if message is None

```
Traceback (most recent call last):
  File "/usr/src/app/.venv/lib/python3.9/site-packages/....../consumer.py", line 35, in poll
    ....
  File "/usr/src/app/.venv/lib/python3.9/site-packages/ddtrace/contrib/kafka/patch.py", line 216, in traced_poll
    span.set_tag_str(kafkax.TOMBSTONE, str(len(message) == 0))
TypeError: object of type 'NoneType' has no len()
```

### Which version of dd-trace-py are you using?
2.4.0

### Which version of pip are you using?
pip 23.3.1

### Which libraries and their versions are you using?
confluent-kafka 2.3.0

**Comment by emmettbutler** [comment]
@josumoreno-BP sure! If you could provide a simple bit of code that reproduces the issue, it would be helpful.

**Comment by emmettbutler** [comment]
@josumoreno-BP that's an awesome find, nice work. I had been wondering how that `None` check allowed this error to happen. I think the solution is probably to patch the ddtrace kafka instrumentation code to catch the `TypeError`. I'll pull request that. Thanks again.
