### ISSUE TITLE
openai == 0.28.1 with function calling response does not have "content" key in message

### ISSUE THREAD

**Issue by maccam912** [DataDog/dd-trace-py#8045]
https://github.com/DataDog/dd-trace-py/blob/0ba57d15200661815fc36ef61e8cfcf5e1d97eb0/ddtrace/contrib/openai/_endpoint_hooks.py#L281

message.content here fails because instead of "content" the response has "function_call", but no content. This is happening on an old openai version, cannot confirm if it happens on 1.0+ or not. Could additional checks be added to see if that key is present before trying to use the value?

**Comment by emmettbutler** [comment]
Thanks for reporting this, @maccam912. We'll look into it.

cc @Yun-Kim

**Comment by Yun-Kim** [comment]
Hi @maccam912, unfortunately I wasn't able to reproduce your issue. Could you give me an example call you're making that leads to the error? Thanks!

**Comment by maccam912** [comment]
I don't have it any more. We ended up turning off ddtrace for now and don't need it in the immediate future, at least until we upgrade the openai python version probably. If it still happens we might be back but I'll be optimistic for now that it will fix itself once everything is updated.

**Comment by Yun-Kim** [comment]
I'll close this in the meantime as I wasn't able to reproduce, but feel free to reopen if you run into the same/similar issue.
