### ISSUE TITLE
Request for a new patch release ASAP with the fix for langchain #7996

### ISSUE THREAD

**Issue by MrinalJain17** [DataDog/dd-trace-py#8060]
### Summary of problem

This commit fixes an error that crashes any application using ddtrace with langchain. https://github.com/DataDog/dd-trace-py/pull/7996

What is the timeline for a new patch release with the fix above?

### Which version of dd-trace-py are you using?

3.4.0

### Which libraries and their versions are you using?

langchain: 0.0.364
open: 1.6.0

<details>
  <summary>`pip freeze`</summary>
  
</details>

**Comment by emmettbutler** [comment]
Patch version 2.4.1 was released yesterday https://github.com/DataDog/dd-trace-py/releases/tag/v2.4.1
