### ISSUE TITLE
ddtrace/internal/sampling.py incorrectly logs with exc_info=True

### ISSUE THREAD

**Issue by leifwalsh** [DataDog/dd-trace-py#8067]
### Summary of problem

https://github.com/DataDog/dd-trace-py/blob/7dbb2cc13b22828c524d0f01561134323ef94fa8/ddtrace/internal/sampling.py#L93 passes `exc_info=True` to `logger.warning()` in a non-exception context. 

### Which version of dd-trace-py are you using?

2.3.2, but it's still present in 2.4.0 and has been there for ages.

### Which version of pip are you using?

Doesn't matter

### Which libraries and their versions are you using?

Doesn't matter

### How can we reproduce your problem?

Not really sure - we don't know why that line of code suddenly started getting executed recently, it never has before this week.

### What is the result that you get?

This causes our logging middleware to try to get `sys.exc_info()` and then that code (incorrectly) assumes there _must_ be an exception available, and since there isn't, it crashes. We'll fix our logging middleware, but IMO this library should also be fixed.

### What is the result that you expected?

Don't pass `exc_info` unless you're in an exception handler.

**Comment by emmettbutler** [comment]
Thank you for the report, @leifwalsh. We'll look into it!
