### ISSUE TITLE
export profiling  to http handler

### ISSUE THREAD

**Issue by zdyj3170101136** [DataDog/dd-trace-py#8125]
#### expected
the datadog heap profiling is useful, but it would produce too much overhead.

i expect export profiling to http handler.

and i could profiling the program only when i want to reduce overhead.

**Comment by emmettbutler** [comment]
Thank you for reporting this issue, @zdyj3170101136. Can you provide any more detail about the problem you're encountering?

**Comment by zdyj3170101136** [comment]
> 感谢您报告此问题，@zdyj3170101136。您能否提供有关您遇到的问题的更多详细信息？

i want to know why my python process memory was high.

 but i find is cost 20 percent of http handler latency in my program.

so i need to dynamic start  and stop profile in my process only when i want to resuce overhead.

**Comment by sanchda** [comment]
:wave: Hello, thank you for the report!

20 percent of HTTP latency is high!  We do not usually expect this amount of overhead.

Currently, the profiler cannot be turned on and off dynamically.  However, I do have one suggestion.

The easiest thing to try is to reduce the profiler's upload frequency.  It will collect the exact same data, but upload the data less frequently.  [Here is the documentation](https://ddtrace.readthedocs.io/en/stable/configuration.html?highlight=upload#DD_PROFILING_UPLOAD_INTERVAL).  I would try setting `DD_PROFILING_UPLOAD_INTERVAL=120` as a start, to see if it improves latency.

Another idea is to [remove the types of profiling that are less interesting for you](https://ddtrace.readthedocs.io/en/stable/configuration.html?highlight=upload#DD_PROFILING_STACK_ENABLED).  If you report back that any of these helped, we can try to improve performance.

DD_PROFILING_STACK_ENABLED=false
DD_PROFILING_LOCK_ENABLED=false


Finally, I'm currently finishing some work that will reduce the frequency that the profiler takes the GIL.  This may also help.

**Comment by zdyj3170101136** [comment]
> 👋您好，感谢您的报告！
> 
> 20% 的 HTTP 延迟很高！我们通常预计不会有这么大的开销。
> 
> 目前，分析器无法动态打开和关闭。不过，我确实有一个建议。
> 
> 最简单的尝试是降低分析器的上传频率。它将收集完全相同的数据，但上传数据的频率较低。 [这是文档](https://ddtrace.readthedocs.io/en/stable/configuration.html?highlight=upload#DD_PROFILING_UPLOAD_INTERVAL)。我会尝试将设置`DD_PROFILING_UPLOAD_INTERVAL=120`作为开始，看看它是否可以改善延迟。
> 
> 另一个想法是[删除您不太感兴趣的分析类型](https://ddtrace.readthedocs.io/en/stable/configuration.html?highlight=upload#DD_PROFILING_STACK_ENABLED)。如果您反馈其中任何一个有帮助，我们可以尝试提高性能。
> 
> DD_PROFILING_STACK_ENABLED=假 DD_PROFILING_LOCK_ENABLED=假
> 
> 最后，我目前正在完成一些工作，这些工作将降低探查器获取 GIL 的频率。这也可能有帮助。

here is a program.

 when i send a http get request to endpoint /debug/pprof/heap/start, it would start alloc profile.
 
when i send a http get request to endpoint /debug/pprof/heap/stop, it would stop alloc profile.
```
from flask import Flask, jsonify
import threading
from ddtrace.profiling import Profiler

prof = Profiler(
    url="http://127.0.0.1:8081",
    #enable_code_provenance=True, # provide library version
)

app = Flask(__name__)
lock = threading.Lock()
processing_request = False
started = False

@app.route('/debug/pprof/heap/start', methods=['GET'])
def start_profiling():
    global processing_request, started
    with lock:
        if processing_request:
            return jsonify({'message': 'Another request is being processed'}), 409
        if started:
            return jsonify({'message': 'already started'}), 409
        processing_request = True


    prof.start() 

    with lock:
        processing_request = False
        started = True
    
    return jsonify({'message': 'Profiling started'}), 200  # 添加这行

@app.route('/debug/pprof/heap/stop', methods=['GET'])
def stop_profiling():
    global processing_request, started
    with lock:
        if processing_request:
            return jsonify({'message': 'Another request is being processed'}), 409
        if not started:
            return jsonify({'message': 'not started'}), 409
        processing_request = True

    prof.stop()

    with lock:
        processing_request = False
        started = False

    return jsonify({'message': 'Profiling stopped'}), 200  # 添加这行

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)

```

but i do not know how to make it work with multiprocess.

**Comment by zdyj3170101136** [comment]
also i do not know why the datadog ProfileInstance restart_on_fork?

if i do disable restart_on_fork, it means the new started python process would send a duplicate data.

but the periodic collector like cpu, wall collector would run correctly after collect interval?
![截屏2024-01-23 下午4 46 58](https://github.com/DataDog/dd-trace-py/assets/52686065/42292df0-e810-41c7-b74c-c0e1f863103c)

**Comment by zdyj3170101136** [comment]
directly call /debug/pprof/allocs
```
from aiohttp import web
import asyncio
from ddtrace.profiling import Profiler

prof = Profiler(
    url="http://127.0.0.1:8081",
    #enable_code_provenance=True, # provide library version
)

async def handle(request):
    asyncio.create_task(heap_profile())
    return web.Response(text="Request received")

async def heap_profile():
    prof.start()
    print("started")
    await asyncio.sleep(60)
    prof.stop()
    print("stoped")

app = web.Application()
app.add_routes([web.get('/debug/pprof/allocs', handle)])

web.run_app(app)

```
