### ISSUE TITLE
OpenAI and ddtrace clash

### ISSUE THREAD

**Issue by OmriBenShoham** [DataDog/dd-trace-py#8128]
### Summary of problem

My application cannot load with the latest openai and latest ddtrace

### Which version of dd-trace-py are you using?
2.4.0

### Which version of pip are you using?
23.3.2

### Which libraries and their versions are you using?

The issue is with openai library - version 1.8.0 (latest)

### How can we reproduce your problem?
You can just try to load application with:
openai 1.8.0
ddtrace 2.4.0

### What is the result that you get?
```
 File "/usr/local/lib/python3.9/site-packages/ddtrace/contrib/openai/patch.py", line 370, in patch
    wrap(openai._base_client.BaseClient._process_response, _patched_convert(openai, integration))
AttributeError: type object 'BaseClient' has no attribute '_process_response'
```

### What is the result that you expected?
No errors

**Comment by GalDayan** [comment]
Same here!

**Comment by Yun-Kim** [comment]
Hi @OmriBenShoham, thanks for reaching out!

I was able to reproduce your issue, #8131 should resolve this. In the meantime, I would suggest pinning `openai<1.8` for now until this fix is released.
