### ISSUE TITLE
is python memory profiling support python package written in c?

### ISSUE THREAD

**Issue by zdyj3170101136** [DataDog/dd-trace-py#8135]
is python memory profiling support python package written in c?

like pillow?

**Comment by P403n1x87** [comment]
@zdyj3170101136 the memory profiler tracks the allocations made via the [CPython allocators](https://docs.python.org/3/c-api/memory.html#overview). Any memory allocations done via other allocators (e.g. `malloc`) won't be tracked. So if the C extension uses the CPython allocators then that information will be collected.

**Comment by emmettbutler** [comment]
Closing because the question has been answered

**Comment by zdyj3170101136** [comment]
> @zdyj3170101136 the memory profiler tracks the allocations made via the [CPython allocators](https://docs.python.org/3/c-api/memory.html#overview). Any memory allocations done via other allocators (e.g. `malloc`) won't be tracked. So if the C extension uses the CPython allocators then that information will be collected.

i find we only add hook for PYMEM_DOMAIN_OBJ.

so if the c use  PyMem_New to allocate object, we would not get it.
