### ISSUE TITLE
heap profiling is not correct

### ISSUE THREAD

**Issue by zdyj3170101136** [DataDog/dd-trace-py#8150]
### Summary of problem
i use pillow to read lots of image and do not release them.

the heap increase to GB of memory.

but the inuse bytes of heap only 100 MB.
### Which version of dd-trace-py are you using?
ddtrace==1.20.16

[centos@plat-sg03-infra-testing-parca006 pillow-bench]$ python3 --version
Python 3.6.8
### Which libraries and their versions are you using?
```
attrs==22.2.0
bytecode==0.13.0
cattrs==1.0.0
chardet==3.0.4
conda==4.6.14
ddsketch==2.0.4
ddtrace==1.20.16
distro==1.5.0
envier==0.4.0
idna==2.10
importlib-metadata==4.8.3
ipaddress==1.0.23
pep562==1.1
Pillow==8.4.0
protobuf==3.19.6
pycosat==0.6.3
pycrypto==2.6.1
PySocks==1.6.8
PyYAML==3.13
requests==2.14.2
ruamel.yaml==0.13.14
six==1.16.0
typing_extensions==4.1.1
urllib3==1.25.6
xmltodict==0.13.0
zipp==3.6.0
```

### How can we reproduce your problem?

```
from ddtrace.profiling import Profiler

prof = Profiler(
        url="http://127.0.0.1:8081",
   enable_code_provenance=True, # provide library version
)
prof.start() # Should be as early as possible, eg before other imports, to ensure everything is profiled
import os
import PIL
from PIL import Image

dir = "/home/centos/pillow-bench/Images_0/0"
onlyfiles = []

filedir = dir
files = [f for f in os.listdir(filedir) if os.path.isfile(os.path.join(filedir, f))]
filepaths = map( lambda x: os.path.join(filedir, x), files )
onlyfiles += list(filepaths)

images = []
s = 0
for i in range(len(onlyfiles)):
    fname = onlyfiles[i]
    image = PIL.Image.open(fname)
    # Do something
    images.append(image)
    image.tobytes("xbm", "rgb")
    if i % 10000 == 0:
        print('iteration ', i)

input("Press Enter to continue...")
```
### What is the result that you get?
heap inuse space only 150MB.
### What is the result that you expected?
heap inuse space should use  GB of memory.

the pprof file:
[auto5.zip](https://github.com/DataDog/dd-trace-py/files/13986482/auto5.zip)

**Comment by sanchda** [comment]
:wave: Hello, thank you for the report!

Currently, the Datadog profiler only captures Python allocations.  Heap allocations performed in native libraries are not included (we may improve this in the future).

I notice that Pillow primarily uses libjpeg or openjpeg for .jpeg processing (in addition to other native libraries!), but I'm not an expert in Pillow.  If these are native allocations, the [Datadog native profiler](https://github.com/DataDog/ddprof) should be able to reveal the allocation sites are indeed in native code.

I can try to give this a shot as well, but we're currently blocked on other customer issues, so it will take a few days before I can investigate.

**Comment by zdyj3170101136** [comment]
> 👋您好，感谢您的报告！
> 
> 目前，Datadog 分析器仅捕获 Python 分配。不包括在本机库中执行的堆分配（我们将来可能会改进这一点）。
> 
> 我注意到 Pillow 主要使用 libjpeg 或 openjpeg 进行 .jpeg 处理（以及其他本机库！），但我不是 Pillow 方面的专家。如果这些是本机分配，则[Datadog 本机分析器](https://github.com/DataDog/ddprof)应该能够显示分配站点确实在本机代码中。
> 
> 我也可以尝试一下，但目前我们因其他客户问题而受阻，因此我需要几天时间才能进行调查。

oh, the allocation profiler is correct, but the heap inuse profiler is not correct, i do not know the difference between them.
