### ISSUE TITLE
profiling overhead

### ISSUE THREAD

**Issue by zdyj3170101136** [DataDog/dd-trace-py#8160]
i want to enable memory profiling in prod, what is the overhead to process?

how much http latency or cpu cost?

**Comment by ZStriker19** [comment]
Hi @zdyj3170101136 thanks for reaching out, we don't have an exact estimate for this as it depends a decent amount on your application. What we'd recommend is enabling it in staging and seeing if the http latency and cpu increase are acceptable for prod.

**Comment by ZStriker19** [comment]
Closing this for now, but if you have any follow up please feel free to reopen.
