### ISSUE TITLE
Latest Langchain throws deprecated warnings

### ISSUE THREAD

**Issue by scottberres-tr** [DataDog/dd-trace-py#8212]
### Summary of problem
Upgrading to the latest langchain, we are now getting deprecated warnings

LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:\n\n`from langchain_community.chat_models import ChatOpenAI`

Vectorstores also throws this deprecated warning.

It looks like it is trying import the old code first, then if it can't find it, it imports the correct code. 

### Which version of dd-trace-py are you using?
2.5.1

### Which libraries and their versions are you using?
langchain - 0.1.4
langchain-community - 0.0.14
langchain-core - 0.1.16
langchain-openai - 0.0.4

<details>
  <summary>Upgrading to the latest langchain, we are now getting deprecated warnings</summary>
  
</details>

### How can we reproduce your problem?
Use the latest langchain with ddtrace you will get deprecated warnings. 

### What is the result that you expected?
Update to the recommended calls so the warnings go away.

**Comment by emmettbutler** [comment]
Thank you for bringing this to our attention, @scottberres-tr. I've added it to an internal backlog and it will be considered during upcoming prioritization passes.

**Comment by ericbuehl** [comment]
@emmettbutler Could we get some more insight from the DD team as to why this issue is not planned to be addressed?

**Comment by emmettbutler** [comment]
@ericbuehl we plan to address it, but we don't know exactly when we'll do that. I'll reopen this issue to reduce confusion.

**Comment by emmettbutler** [comment]
@Yun-Kim

**Comment by nicolablago** [comment]
I think [this line](https://github.com/DataDog/dd-trace-py/blob/3c62805ca6108ecc5a613aada21b13c60ff9c9c1/ddtrace/contrib/langchain/patch.py#L680) and the following one are the source of the issue.

they should be importing from `langchain-community`.

**Comment by rf-synth** [comment]
Any updates on this?

**Comment by alon-parag-taiwa** [comment]
Any update on this, it is an incredibly annoying issue!

**Comment by rf-synth** [comment]
In the meantime, putting the following **before** any ddtrace import silences the warnings:
```
import warnings
from langchain._api import LangChainDeprecationWarning
warnings.simplefilter("ignore", category=LangChainDeprecationWarning)
```

**Comment by FadelDabaja** [comment]
Hey, can we get an update on this?

**Comment by Yun-Kim** [comment]
Hi all, sorry for the delay. This was not as trivial of an issue to fix as expected as this essentially required ddtrace to support `langchain==0.1`, but should be included in the next minor release of ddtrace (note that we are dropping support for tracing deprecated methods for `langchain>=0.1` as recommended by [langchain's release notes](https://python.langchain.com/docs/changelog/core)). In the meantime, I recommend following @rf-synth's suggestion to ignore deprecation warnings from langchain.

**Comment by RemoSande** [comment]
`LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:
`
just dropping by that a fresh new install of Langchain produced the following message. I am confused what to do: ignore or install the langchain-community ?

Additional error was. I double checked and my quota is not even close to being reached. Any tips ?  `in _request
    raise self._make_status_error_from_response(err.response) from None
openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}`

**Comment by Yun-Kim** [comment]
Hi @RemoSande, we have not yet released support for `langchain==0.1` which should get rid of your error. I suggest waiting until the next minor release of `ddtrace==2.8`.

For your other error, this seems like an openai/langchain specific error and would be better addressed by creating an issue on their github repositories: [openai](https://github.com/openai/openai-python/issues/new/choose) / [langchain](https://github.com/langchain-ai/langchain/issues/new/choose)

**Comment by jackchan0528** [comment]
To clarify, this is correct syntax right?
from langchain.document_loaders import PyPDFLoader

**Comment by alon-parag-taiwa** [comment]
@jackchan0528 It's possible that they moved this class to langchain_community
