### ISSUE TITLE
TypeError: unhashable type: 'bytearray'

### ISSUE THREAD

**Issue by dannosaur** [DataDog/dd-trace-py#8218]
### Summary of problem
```
  File "ddtrace/profiling/scheduler.py", line 65, in flush
    exp.export(events, start, self._last_export)
  File "ddtrace/profiling/exporter/http.py", line 175, in export
    profile, libs = super(PprofHTTPExporter, self).export(events, start_time_ns, end_time_ns)
  File "ddtrace/profiling/exporter/pprof.pyx", line 787, in ddtrace.profiling.exporter.pprof.PprofExporter.export
  File "ddtrace/profiling/exporter/pprof.pyx", line 587, in ddtrace.profiling.exporter.pprof.PprofExporter._group_stack_events
  File "ddtrace/profiling/exporter/pprof.pyx", line 132, in ddtrace.profiling.exporter.pprof.groupby
```

### Which version of dd-trace-py are you using?
2.4.1

### Which version of pip are you using?
23.2.1

### Which libraries and their versions are you using?
See #8132 

### How can we reproduce your problem?
No idea

### What is the result that you get?
Error

### What is the result that you expected?
No error :)

**Comment by emmettbutler** [comment]
Thanks @dannosaur. Where's the "unhashable type" error? It seems like the traceback here might be incomplete.

**Comment by dannosaur** [comment]
I copy/pasted it straight out of our Sentry instance. Unfortunately that's all it gave me. 

![Screenshot_20240129-171719](https://github.com/DataDog/dd-trace-py/assets/461956/76b8f003-23be-41b5-b6bc-a03627ba2b23)

**Comment by P403n1x87** [comment]
I'm not quite sure what's happening here. The provided information seems to indicate that we might be getting a `bytearray` object when computing the key used to group stack events.

@dannosaur I've put up yet [another PR](https://github.com/DataDog/dd-trace-py/pull/8435) for you to test, if that's OK 🙏 . Because it's not totally clear where the problem comes from, I'm adding some warnings to see what the offending key looks like. We would then take it from there and fix the actual problem.

**Comment by dannosaur** [comment]
@P403n1x87 I've updated my project's requirements file. I'll get this out to production early next week and report back.

Thanks!

**Comment by dannosaur** [comment]
This PR was deployed to our production stack 2 days ago, and Sentry hasn't reported any more errors coming from ddtrace. What's also interesting is that the new warning message you added also hasn't been seen. I just scoured the logs for the string and came up empty. Very strange.

I'll keep an eye out for the warning message and post back if/when I see it.

**Comment by P403n1x87** [comment]
@dannosaur Thanks for reporting back. I have merged the latest changes into the PR, so that it will include the latest fixes.

**Comment by P403n1x87** [comment]
@dannosaur if you are not seeing any more occurrences of this issue from the PR linked above, then it should be safe to use the latest release
