### ISSUE TITLE
Silent ddtrace crashes on 2.5 with FastAPI

### ISSUE THREAD

**Issue by sanchda** [DataDog/dd-trace-py#8228]
This is a new issue created for the defect observed in #6701 for ddtrace 2.5.1

From @sheluchin in that thread:
> Our observation was that very large requests would eventually cause the server to die without leaving any logs or stacktrace. When we uninstalled ddtrace, the same requests went through successfully without issue.

**Comment by sheluchin** [comment]
There were two things we tried independent of each other, both of which eliminated the server restart problem we were troubleshooting:
1. Uninstalling ddtrace.
2. The FastAPI endpoint we were calling made two database queries to retrieve the response data. Eliminating the first query by hardcoding the data it returned likewise allowed us to get a response from the server without causing a restart. This was something we tried as part of the troubleshooting process, but it's not a viable option for our implementation.
