### ISSUE TITLE
Support aiopg >= 1.0 (and aiopg with python 3.11)

### ISSUE THREAD

**Issue by wlach** [DataDog/dd-trace-py#8229]
### Summary of problem

The current aiopg module for ddtrace currently uses a syntax that is no longer supported:

https://github.com/DataDog/dd-trace-py/blob/0cc5742b5973ed972284f998cc076aca5e1d1c39/ddtrace/contrib/aiopg/connection.py#L33

This was previously discussed in this closed ticket under python 3.11 support, filing this to support aiopg explicitly:

https://github.com/DataDog/dd-trace-py/issues/4149#issuecomment-1452661656

### Which version of dd-trace-py are you using?

Problem is in latest (2.5.1 as of this writing)

### Which version of pip are you using?

N/A

### Which libraries and their versions are you using?

Currently using aiopg 1.3.5

### How can we reproduce your problem?

Use this library and configure ddtrace

### What is the result that you get?

Error when attempting to patch aiopg (`AttributeError: module 'asyncio' has no attribute 'coroutine'`)

### What is the result that you expected?

No error

**Comment by emmettbutler** [comment]
Thanks for flagging this, @wlach. We'll take a look. Please open a pull request fixing it if you're so inclined.

**Comment by wlach** [comment]
> Thanks for flagging this, @wlach. We'll take a look. Please open a pull request fixing it if you're so inclined.

I put up a preliminary PR here: https://github.com/DataDog/dd-trace-py/pull/8657

**Comment by ghthor** [comment]
@emmettbutler The PR has been opened
