### ISSUE TITLE
Setting DD_TRACE_OTEL_ENABLED=True causes error when using fastapi with OpenTelemetry

### ISSUE THREAD

**Issue by suemayaheldursi** [DataDog/dd-trace-py#8259]
### Summary of problem
When enabling the DD_TRACE_OTEL_ENABLED=True Fast API healthchecks fail with error 'int' object has no attribute 'sampled'

### Which version of dd-trace-py are you using?
2.5.1
### Which version of pip are you using?
I am using Poetry

### Which libraries and their versions are you using?
This is my pyproject.toml
[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["----"]
readme = "README.md"
packages = [
  {include = "api"},
]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
fastapi = "^0.93.0"
uvicorn = {extras = ["standard"], version = "^0.20.0"}
aiohttp = "^3.8.4"
ddtrace = "^2.5.1"
opentelemetry-instrumentation-fastapi = "^0.43b0"
opentelemetry-sdk = "^1.22.0"
opentelemetry-instrumentation-logging = "^0.43b0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"
httpx = "^0.23.3"
pytest-asyncio = "^0.20.3"
pytest-mock = "^3.10.0"
pyclean = "^2.7.0"

[tool.pytest.ini_options]
pythonpath = [
  "."
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

### How can we reproduce your problem?
I am running Fast API on ECS fargate. I followed the instructions in [this guide](https://docs.datadoghq.com/integrations/ecs_fargate/?tab=webui) to setup tracing using OpenTelemetry with datadog.
My application is instrumented as follows:
``` 
import logging
import uuid

import uvicorn
from fastapi import APIRouter, FastAPI
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
from opentelemetry.instrumentation.logging import LoggingInstrumentor, logging
from opentelemetry.sdk.metrics import MeterProvider
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import TracerProvider

from api import __version__ as API_VERSION

# Instrumentation setup and logging
resource = Resource.create(
    {
        "service.name": "api",
        "service.instance.id": str(uuid.uuid4()),
        "service.version": API_VERSION,
    }
)
tracer = TracerProvider(resource=resource)
meter = MeterProvider(resource=resource)
LoggingInstrumentor().instrument(tracer_provider=tracer)


root_router = APIRouter()
app = FastAPI(
    title="API",
    version=API_VERSION,
    openapi_url="/openapi.json",
    docs_url="/docs",
)
app.include_router(root_router)

FastAPIInstrumentor.instrument_app(
    app,
    tracer_provider=tracer,
    meter_provider=meter
)


@app.get("/ruok", status_code=200)
def health():
    return


logger = logging.getLogger(__name__)

logger.info(f"API: {API_VERSION}) starting...")


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8080, log_level="debug")

```

My task definition is:
```
{
    "taskDefinitionArn": "arn:aws:ecs:eu-west-1:xxx:task-definition/api-dev:1",
    "pidMode": "task",
    "containerDefinitions": [
        {
            "name": "api",
            "image": "xxx.dkr.ecr.eu-west-1.amazonaws.com/euw1-api",
            "cpu": 0,
            "portMappings": [
                {
                    "containerPort": 8080,
                    "hostPort": 8080,
                    "protocol": "tcp",
                    "name": "api-8080-tcp",
                    "appProtocol": "http"
                }
            ],
            "essential": true,
            "environment": [
                {
                    "name": "DD_SERVICE",
                    "value": "api"
                },
                {
                    "name": "DD_ENV",
                    "value": "DEV"
                },
                {
                    "name": "DD_TRACE_DEBUG",
                    "value": "true"
                },
                {
                    "name": "DD_TRACE_OTEL_ENABLED",
                    "value": "true"
                },
                {
                    "name": "OTEL_EXPORTER_OTLP_ENDPOINT",
                    "value": "http://datadog-agent:4318"
                }
            ],
            "environmentFiles": [],
            "mountPoints": [],
            "volumesFrom": [],
            "logConfiguration": {
                "logDriver": "awsfirelens",
                "options": {
                    "Name": "datadog",
                    "apikey": "xxx",
                    "Host": "http-intake.logs.datadoghq.eu",
                    "dd_service": "api",
                    "dd_source": "python",
                    "dd_message_key": "log",
                    "dd_tags": "project:fluentbit",
                    "TLS": "on",
                    "provider": "ecs",
                    "compress": "gzip"
                }
            },
            "healthCheck": {
                "command": [
                    "CMD-SHELL",
                    "curl -f http://127.0.0.1:8080/ruok || exit 1"
                ],
                "interval": 60,
                "timeout": 60,
                "retries": 3,
                "startPeriod": 30
            },
            "dockerLabels": {
                "com.datadoghq.ad.instances": "[{\"host\": \"%%host%%\", \"port\": 8080}]",
                "com.datadoghq.ad.check_names": "[\"api\"]",
                "com.datadoghq.ad.init_configs": "[{}]",
                "com.datadoghq.tags.env": "DEV",
                "com.datadoghq.tags.service": "api"
                "com.datadoghq.tags.version": "v0.1"
            }
        },
        {
            "name": "datadog-agent",
            "image": "public.ecr.aws/datadog/agent:latest",
            "portMappings": [
                {
                    "containerPort": 4318,
                    "hostPort": 4318,
                    "protocol": "tcp",
                    "name": "datadog-agent-4318-tcp",
                    "appProtocol": "http"
                },
                {
                    "containerPort": 4317,
                    "hostPort": 4317,
                    "protocol": "tcp",
                    "name": "datadog-agent-4317-tcp",
                    "appProtocol": "grpc"
                },
                {
                    "hostPort": 8126,
                    "protocol": "tcp",
                    "containerPort": 8126,
                    "name": "datadog-agent-8126-tcp"
                }
            ],
            "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                    "awslogs-create-group": "true",
                    "awslogs-group": "/ecs/api-datadog-agent",
                    "awslogs-region": "eu-west-1",
                    "awslogs-stream-prefix": "ecs"
                }
            },
            "environment": [
                {
                    "name": "DD_API_KEY",
                    "value": "xxx"
                },
                {
                    "name": "ECS_FARGATE",
                    "value": "true"
                },
                {
                    "name": "DD_ENV",
                    "value": "DEV"
                },
                {
                    "name": "DD_APM_ENABLED",
                    "value": "true"
                },
                {
                    "name": "DD_SITE",
                    "value": "datadoghq.eu"
                },
                {
                    "name": "DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT",
                    "value": "0.0.0.0:4318"
                },
                {
                    "name": "DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT",
                    "value": "0.0.0.0:4317"
                },
                {
                    "name": "DD_LOGS_ENABLED",
                    "value": "true"
                },
                {
                    "name": "DD_OTLP_CONFIG_LOGS_ENABLED",
                    "value": "true"
                }
            ]
        },
        {
            "essential": true,
            "image": "amazon/aws-for-fluent-bit:stable",
            "name": "datadog-log-router",
            "firelensConfiguration": {
                "type": "fluentbit",
                "options": {
                    "enable-ecs-log-metadata": "true"
                }
            }
        }
    ],
    "family": "api-dev",
    "taskRoleArn": "arn:aws:iam::xxx:role/apiExecutionRole",
    "executionRoleArn": "arn:aws:iam::xxx:role/apiExecutionRole",
    "networkMode": "awsvpc",
    "revision": 1,
    "volumes": [],
    "status": "ACTIVE",
    "requiresAttributes": [
        {
            "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
        },
        {
            "name": "ecs.capability.execution-role-awslogs"
        },
        {
            "name": "com.amazonaws.ecs.capability.ecr-auth"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
        },
        {
            "name": "ecs.capability.secrets.asm.environment-variables"
        },
        {
            "name": "ecs.capability.container-health-check"
        },
        {
            "name": "ecs.capability.execution-role-ecr-pull"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
        },
        {
            "name": "ecs.capability.task-eni"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.29"
        }
    ],
    "placementConstraints": [],
    "compatibilities": [
        "EC2",
        "FARGATE"
    ],
    "runtimePlatform": {
        "cpuArchitecture": "X86_64",
        "operatingSystemFamily": "LINUX"
    },
    "requiresCompatibilities": [
        "FARGATE"
    ],
    "cpu": "1024",
    "memory": "3072"
}
```

The applications runs with the following on the dockerfil:
```
ENTRYPOINT ["ddtrace-run", "uvicorn", "api.main:app", "--host", "0.0.0.0" ,"--port", "8080"]
```

### What is the result that you get?
Traceback (most recent call last):
  File "/apps/api/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/apps/api/.venv/lib/python3.10/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 563, in __call__
    span, token = _start_internal_or_server_span(
  File "/apps/api/.venv/lib/python3.10/site-packages/opentelemetry/instrumentation/utils.py", line 117, in _start_internal_or_server_span
    span = tracer.start_span(
  File "/apps/api/.venv/lib/python3.10/site-packages/opentelemetry/sdk/trace/__init__.py", line 1084, in start_span
    sampling_result = self.sampler.should_sample(
  File "/apps/api/.venv/lib/python3.10/site-packages/opentelemetry/sdk/trace/sampling.py", line 361, in should_sample
    if parent_span_context.trace_flags.sampled:
AttributeError: 'int' object has no attribute 'sampled'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/api/.venv/lib/python3.10/site-packages/ddtrace/contrib/asgi/middleware.py", line 275, in __call__
    return await self.app(scope, receive, wrapped_send)
  File "/apps/api/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 179, in __call__
    await response(scope, receive, send)
  File "/apps/api/.venv/lib/python3.10/site-packages/starlette/responses.py", line 164, in __call__
    await send(
  File "/apps/api/.venv/lib/python3.10/site-packages/ddtrace/contrib/asgi/middleware.py", line 234, in wrapped_send
    return await send(message)
  File "/apps/api/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 489, in send
    self.access_logger.info(
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1622, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args,
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1591, in makeRecord
    rv = _logRecordFactory(name, level, fn, lno, msg, args, exc_info, func,
  File "/apps/api/.venv/lib/python3.10/site-packages/opentelemetry/instrumentation/logging/__init__.py", line 117, in record_factory
    record.otelTraceSampled = ctx.trace_flags.sampled
AttributeError: 'int' object has no attribute 'sampled'

### What is the result that you expected?
Requests should be successful

**Comment by mabdinur** [comment]
Thanks for opening this issue.

The ddtrace library implements the `opentelemetry-api` to generate and submit traces to the datadog agent. The opentelemetry sdk, metrics api, logs api, and exporters are not supported. `ddtrace` provides logging support by default and to submit metrics to datadog you can use [statsd](https://github.com/DataDog/dd-trace-py/tree/507510d20fbda0d738686dc8b8ea5a12213abd86/ddtrace/vendor/dogstatsd).

An alternative of using opentelemetry-api with the ddtrace library is otlp ingest. This will allow you to use the opentelemetry-sdk with the datadog agent: https://docs.datadoghq.com/opentelemetry/otlp_ingest_in_the_agent/?tab=host.


To use the ddtrace library with opentelemetry you we will need to apply the following changes to your application:

```python
import logging
import uuid

# remove all imports from the opentelemetry sdk, metrics and logs api
import uvicorn
from fastapi import APIRouter, FastAPI
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
from opentelemtry.trace import get_tracer_provider

from api import __version__ as API_VERSION

# Instrumentation setup and logging
import ddtrace

# ddtrace does not support resources but you can set the analogous ddtrace configurations
ddtrace.config.service = "api"
# DD_SERVICE, ddtrace sets a "runtime-id" attribute on all spans, this is equivalent to setting the "instance-id" here
ddtrace.config.version = API_VERSION. # DD_ENV


root_router = APIRouter()
app = FastAPI(
    title="API",
    version=API_VERSION,
    openapi_url="/openapi.json",
    docs_url="/docs",
)
app.include_router(root_router)

FastAPIInstrumentor.instrument_app(
    app,
    tracer_provider=get_tracer_provider(), # will return the ddtrace trace provider: https://github.com/DataDog/dd-trace-py/blob/507510d20fbda0d738686dc8b8ea5a12213abd86/ddtrace/bootstrap/preload.py#L88
)


@app.get("/ruok", status_code=200)
def health():
    return


logger = logging.getLogger(__name__)

logger.info(f"API: {API_VERSION}) starting...")


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8080, log_level="debug")
```


Let me know if this works for you.

**Comment by mabdinur** [comment]
The ddtrace library does not support OpenTelemetry Metrics API (at least not yet). It only supports OpenTelemetry tracing API and [dogstatsd](https://docs.datadoghq.com/developers/dogstatsd/?tab=hostagent) (Datadog's metrics API)

The only way to use the OpenTelemetry metrics API is via [opentelemetry ingest](https://docs.datadoghq.com/opentelemetry/otlp_ingest_in_the_agent/?tab=host). Here's some docs on how to set that up: https://docs.datadoghq.com/opentelemetry/otel_metrics/

**Comment by emmettbutler** [comment]
Closing because the questions appear to have been answered. Please comment if there's more to discuss.

**Comment by suemayaheldursi** [comment]
@mabdinur @emmettbutler Apologies for my delay - from my setup above you can see that I followed the instructions for the [opentelemetry ingest](https://docs.datadoghq.com/opentelemetry/otlp_ingest_in_the_agent/?tab=host). Yet I still don't have metrics. Apologies if I'm missing something or misunderstood but are you able to advise? I'm also not really sure how to troubleshoot this.

**Comment by mabdinur** [comment]
Hey @suemayaheldursi, 

I am not familiar with the internals of OpenTelemetry Ingest but there is likely issues with your [agent](https://github.com/DataDog/datadog-agent/blob/main/comp/otelcol/otlp/README.md) configurations. I would recommend reaching creating a support ticket and sharing your datadog setup here: https://help.datadoghq.com/hc/en-us/requests/new.

**Comment by suemayaheldursi** [comment]
Ok thanks @mabdinur
