### ISSUE TITLE
Support celery task shadow name

### ISSUE THREAD

**Issue by holvianssi** [DataDog/dd-trace-py#8275]
### Summary of problem

The automatic tracing for Celery tasks doesn't respect the `shadow` parameter for celery tasks, which per celery documentation is a way to set name for monitoring and logging. See https://docs.celeryq.dev/en/stable/reference/celery.app.task.html#celery.app.task.Task.apply_async and the shadow parameter.

The use case is to have custom resource name for a task in Datadog.

### Which version of dd-trace-py are you using?

ddtrace==2.5.2

### Which version of pip are you using?

pip 23.1.2

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
amqp==5.2.0
attrs==23.2.0
billiard==4.2.0
bytecode==0.15.1
cattrs==23.2.3
celery==5.3.6
click==8.1.7
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
ddsketch==2.0.4
ddtrace==2.5.2
Deprecated==1.2.14
envier==0.5.1
importlib-metadata==6.11.0
kombu==5.3.5
opentelemetry-api==1.22.0
prompt-toolkit==3.0.43
protobuf==4.25.2
python-dateutil==2.8.2
redis==5.0.1
six==1.16.0
typing_extensions==4.9.0
tzdata==2023.4
vine==5.1.0
wcwidth==0.2.13
wrapt==1.16.0
xmltodict==0.13.0
zipp==3.17.0
</details>

### How can we reproduce your problem?

Two files: thetask.py
```
from celery import Celery

app = Celery('tasks', broker='redis://localhost')

from ddtrace import config, patch_all, tracer

config.env = "dev"      # the environment the application is in
config.service = "app"  # name of your application
config.version = "0.1"  # version of your application
patch_all()

@app.task
def add(x, y):
        return x + y
```
and  runner.py
```
from thetask import add

add.apply_async(args=(4, 4), shadow='async_send.foobar')
```
Execute in one shell `celery -A thetask worker --loglevel=INFO` and in another `python runner.py`. Note also the celery logs show the task name as async_send.foobar, respecting the shadow name given.

### What is the result that you get?

I see thetask.add as resource name in Datadog APM.

### What is the result that you expected?

I expect to send async_send.foobar as resource name in Datadog APM.

Currently the resource name is set in ddtrace/contrib/celery/signals as task.name, when it likely should be set as task.request.get('shadow') or task.name (though this might depend on celery version).

**Comment by emmettbutler** [comment]
Thank you for the report, @holvianssi. This seems to be a bug in ddtrace's support of Celery. We'll look into it.
