### ISSUE TITLE
Add `trace_connect` for pymysql

### ISSUE THREAD

**Issue by baraklevy20** [DataDog/dd-trace-py#8284]
### Summary of problem

`mysqldb` and `psycopg` have a `trace_connect` property that creates a span for connection attempts:
> Whether or not to trace connecting.

In the code this looks something like this:
```
def _connect(func, instance, args, kwargs):
    pin = Pin.get_from(MySQLdb)

    if not pin or not pin.enabled() or not config.mysqldb.trace_connect:
        conn = func(*args, **kwargs)
    else:
        with pin.tracer.trace(
            "MySQLdb.connection.connect", service=ext_service(pin, config.mysqldb), span_type=SpanTypes.SQL
        ) as span:
            span.set_tag_str(COMPONENT, config.mysqldb.integration_name)

            # set span.kind to the type of operation being performed
            span.set_tag_str(SPAN_KIND, SpanKind.CLIENT)

            span.set_tag(SPAN_MEASURED_KEY)
            conn = func(*args, **kwargs)
    return patch_conn(conn, *args, **kwargs)
```

It would be useful to have the same setting in `pymysql`, which currently doesn't support it:
```
def _connect(func, instance, args, kwargs):
    conn = func(*args, **kwargs)
    return patch_conn(conn)
```

### Which version of dd-trace-py are you using?
2.3.1

### Which version of pip are you using?
N/A

### Which libraries and their versions are you using?
N/A

<details>
  <summary>`pip freeze`</summary>
  
</details>

### What is the result that you get?
No spans for connection attempts in pymysql.

### What is the result that you expected?
New spans are created for connection attempts.

**Comment by emmettbutler** [comment]
Thank you for raising this, @baraklevy20. We've added it to an internal backlog, where it will be included in future prioritization passes as a feature request.

**Comment by baraklevy20** [comment]
Thank you @emmettbutler! Can I contribute to this repo by making a PR for this?
