### ISSUE TITLE
DD_RUNTIME_METRICS_ENABLED environment variable not documented

### ISSUE THREAD

**Issue by connorbrinton** [DataDog/dd-trace-py#8301]
### Summary of problem

The ddtrace documentation indicates in the `RuntimeMetrics` section that:

> This is normally started automatically by `ddtrace-run` when the `DD_RUNTIME_METRICS_ENABLED` variable is set.

Upon reading this, I went to [the configuration page in the ddtrace docs](https://ddtrace.readthedocs.io/en/stable/configuration.html) to try to understand (i) if this environment variable has a default value and (ii) more details about the kinds of runtime metrics collected by the runtime metrics service API. However, it appears that this environment variable isn't described anywhere on the ddtrace docs configuration page.

This feels like the kind of non-integration-specific environment variable that should be described on the configuration page. Would it be possible to add it there with a short description of what it does and its default value ([`False`](https://github.com/DataDog/dd-trace-py/blob/main/ddtrace/settings/config.py#L469))?

Thanks for maintaining ddtrace! 😄

**Comment by emmettbutler** [comment]
@connorbrinton we can certainly add that documentation. Thanks for pointing this out!
