### ISSUE TITLE
Got object of type 'dict' instead of a code object during stack unwinding

### ISSUE THREAD

**Issue by prha** [DataDog/dd-trace-py#8331]
### Summary of problem
Getting spurious warnings: `Got object of type 'dict' instead of a code object during stack unwinding`

### Which version of dd-trace-py are you using?
2.6.0

### Which version of pip are you using?
pip 23.3.2 from /usr/local/lib/python3.11/site-packages/pip (python 3.11)

**Comment by hwong557** [comment]
I have also been getting errors of the above form on version 2.8.1 and on version 2.11.1:
```
Got object of type 'builtin_function_or_method' instead of a frame object during stack unwinding

Got object of type 'Timeout' instead of a frame object during stack unwinding

Got object of type '_SSLSocket' instead of a frame object during stack unwinding

Got object of type '_TYPE_DEFAULT' instead of a frame object during stack unwinding
```
