### ISSUE TITLE
Unable to build package file mapping; TypeError: expected str, bytes or os.PathLike object, not Path

### ISSUE THREAD

**Issue by inhumantsar** [DataDog/dd-trace-py#8355]
### Summary of problem

After updating from a fairly ancient version of dd-trace, this error started coming up frequently. Functionality does not seem to be impacted, we're still receiving what appears to be all traces.

This error occurs in our live staging environment running Django in Docker (ECS Fargate) on Python 3.9

```
Traceback (most recent call last):
  File "/home/odyssey/.local/lib/python3.9/site-packages/ddtrace/internal/utils/cache.py", line 124, in _
    retval, exc = f.__callonce_result__  # type: ignore[attr-defined]
AttributeError: 'function' object has no attribute '__callonce_result__'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/odyssey/.local/lib/python3.9/site-packages/ddtrace/internal/packages.py", line 106, in _package_file_mapping
    _path = fspath(f.locate())
TypeError: expected str, bytes or os.PathLike object, not Path

Unable to build package file mapping, please report this to https://github.com/DataDog/dd-trace-py/issues
```

### Which version of dd-trace-py are you using?

ddtrace==2.5.1 on Python 3.9

### Which version of pip are you using?

24.0

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
amqp==5.1.0
appdirs==1.4.3
asgiref==3.7.2
aspy.yaml==1.3.0
auth0-python==3.22.0
authy==2.2.5
aws-encryption-sdk==2.5.0
Babel==2.8.0
backoff==2.0.1
base58==2.1.1
base58check==1.0.2
bech32==1.2.0
before_after==1.0.1
billiard==3.6.4.0
boltons==23.0.0
boto3==1.20.14
cachetools==4.1.0
celery==5.2.6
cerberus-python-sdk==22.11.22.0
certifi==2023.5.7
cffi==1.15.0
cfgv==3.1.0
click==8.1.2
cryptography==3.3.2
dataclasses-json==0.5.9
datadog==0.35.0
ddtrace==2.5.1
defusedxml==0.6.0
dict-to-dataclass==0.0.8
distlib==0.3.0
Django==4.2.9
django-admin-inline-paginator==0.4.0
django-admin-list-filter-dropdown==1.0.3
django-admin-rangefilter==0.8.1
django-allauth==0.54.0
django-appconf==1.0.4
django-celery-beat==2.0.0
django-cors-headers==3.7.0
django-cors-middleware==1.5.0
django-crispy-forms==2.0
django-extra-fields==3.0.0
django-formtools==2.2
django-migration-rollback==1.0.5
django-nested-admin==4.0.2
django-oauth-toolkit==1.3.2
django-otp==1.2.2
django-redis==5.2.0
django-request-logging==0.7.5
django-rest-passwordreset==1.3.0
django-s3direct==2.0.3
django-simple-history==3.0.0
django-timezone-field==4.0
django-two-factor-auth==1.15.3
django_admin_csvexport==2.0
djangogrpcframework==0.2.1
djangorestframework==3.14.0
drf-jwt~=1.19.2
entrypoints==0.3
filelock==3.0.12
fireblocks-sdk==2.2.1
flower==1.0.0
future==0.18.2
fuzzywuzzy==0.18.0
geoip2==4.5.0
gobiko.apns==0.1.4
grpcio==1.41.0
grpcio-tools==1.41.0
gunicorn==21.2.0
h2>=2.4,<3.0,!=2.5.0
hiredis==2.0.0
hpack==3.0.0
httpx==0.22.0
hyper==0.7.0
hyperframe==3.2.0
isort==5.10.1
jmespath==0.9.5
kombu==5.2.4
lazy-object-proxy==1.4.3
maxminddb==2.2.0
mccabe==0.6.1
msgpack==1.0.0
newton-ledger-sdk==24.1.19.0
nodeenv==1.3.5
oauthlib==3.1.0
pdfrw==0.4
pep8==1.7.1
phonenumberslite==8.12.1
pillow==8.3.2
plaid-python==7.5.0
prance==23.6.21.0
protobuf==3.18.1
psycopg2-binary==2.9.3
pycountry==23.12.11
pycparser==2.20
pycryptodome==3.9.7
PyJWT==2.3.0
python-crontab==3.0.0
python-dateutil==2.8.1
python-dotenv==1.0.0
python-http-client==3.2.7
python-json-logger==0.1.11
python-Levenshtein==0.12.2
python-memcached==1.59
python-monkey-business==1.0.0
python3-openid==3.1.0
pytz==2023.2
PyYAML==5.4
redis==4.1.0
regex==2023.3.23
requests==2.31.0
requests-oauthlib==1.3.0
responses==0.22.0
rest-condition==1.0.3
rsa==4.7.2
s3transfer==0.5.0
scalecodec==1.0.28
sendgrid==6.2.1
setproctitle==1.1.10
setuptools==68.0.0
Sift==5.0.1
simplejson==3.17.2
six==1.16.0
solders==0.14.1
sqlparse==0.4.2
stellar-sdk==8.2.0
tqdm==4.65.0
Unidecode==1.1.1
urllib3==1.26.7
user_agents==2.2.0
vine==5.0.0
whitenoise==6.4.0
wrapt==1.11.2
zenpy==2.0.24
zipp==3.1.0
</details>

### What is the result that you get?

See summary

### What is the result that you expected?

If the error is spurious and the exception is handled without issue, then I would expect this to be an INFO or WARN level error.

**Comment by emmettbutler** [comment]
Thanks for the report, @inhumantsar. I've opened #8505 to address it.
