### ISSUE TITLE
How do I manually specify the environment with Flask?

### ISSUE THREAD

**Issue by tlam** [DataDog/dd-trace-py#840]
I am currently using ddtrace 0.22.0 and manual tracing of flask with http://pypi.datadoghq.com/trace/docs/web_integrations.html#flask and it is working properly. At the top of my app file, I have:

    from ddtrace import config
    from ddtrace import patch_all
    config.flask['service_name'] = 'myownservice'
    patch_all()

Data and traces are sent properly to datadog but I have the environment as `env:none`. How do I manually specify the environment using the manual method? For example, I will like to see `env:staging`.

**Comment by majorgreys** [comment]
@tlam Glad your traces are getting sent up. To specify the environment using the manual method, you can follow this:

https://docs.datadoghq.com/tagging/assigning_tags/?tab=python#environment-variables

```python
from ddtrace import tracer
tracer.set_tags({'env': 'staging'})
```

**Comment by tlam** [comment]
It looks good now, thanks.
