### ISSUE TITLE
SQLAlchemy: ConnectionEvents.dbapi_error() event is deprecated

### ISSUE THREAD

**Issue by villlem** [DataDog/dd-trace-py#841]
SQL alchemy integration listens to `dbapi_error` event. (found here https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/sqlalchemy/engine.py#L70).

This event is deprecated sice sqlalchemy 0.9. Recently there is a warning:

> sqlalchemy.exc.SADeprecationWarning: The ConnectionEvents.dbapi_error() event is deprecated and will be removed in a future release. Please refer to the ConnectionEvents.handle_error() event.

**Comment by Kyle-Verhoog** [comment]
This should have been addressed with #1324. Feel free to re-open if you're still seeing the issue 🙂
