### ISSUE TITLE
Tracing cannot serialize psycopg2 Composed type

### ISSUE THREAD

**Issue by mlennon-lumere** [DataDog/dd-trace-py#867]
This may be a regression of #732 

I have a bit of code like the following:

```
from django.db import connection

from psycopg2 import sql

def get_data():
	cursor = connection.cursor()
    input_table = sql.Identifier('foo_table')
    cursor.execute(sql.SQL("SELECT EXISTS (SELECT * FROM {input_table} FOR UPDATE SKIP LOCKED LIMIT 1)").format(
        input_table=input_table))
    return cursor.fetchone()[0]
```

When I run this with datadog set up, I get logs like this:
`cannot send spans to localhost:8126: can't serialize Composed([SQL('SELECT EXISTS (SELECT * FROM '), Identifier('foo_table'), SQL(' FOR UPDATE SKIP LOCKED LIMIT 1)')])`

This is with version 0.23.0 of dd-trace-py, version 2.7.5 of psycopg2, and version 2.1.5 of django

**Comment by majorgreys** [comment]
@mlennon-lumere We have a test for this which should be catching such a regression: 

https://github.com/DataDog/dd-trace-py/blob/master/tests/contrib/psycopg/test_psycopg.py#L271

Starting with a basic Django app based on https://docs.djangoproject.com/en/2.2/intro/tutorial01/, I was able to get the following trace for a query like you describe above:

![image](https://user-images.githubusercontent.com/155673/56684684-403b3a00-669e-11e9-9a3c-03b66ce234fe.png)

If you are still experiencing the issue, can you share a minimal and complete example?

**Comment by mlennon-lumere** [comment]
I had tried to get such an example set up, but I was unable to get any trace at all on a locally-running django project with ddtrace installed.  If I was able to get around that, I'd be very happy to set up a complete example

**Comment by majorgreys** [comment]
I've updated our example for Django:

https://github.com/DataDog/trace-examples/tree/master/python/django-tutorial-docker

If you set the environment variable `DD_API_KEY`, this example will bring up the tutorial application with tracing enabled. 

Once you have the application started and database migrations executed, you can test whether spans are being generated properly for`psycopg2.sql.Composable` queries.

First start `django-admin` with `ddtrace-run`:

``` sh
docker-compose exec app ddtrace-run python manage.py shell
```

Then run a variation of the code above:

``` python
from django.db import connection

from psycopg2 import sql

def get_data():
    cursor = connection.cursor()
    input_table = sql.Identifier('polls_question')
    cursor.execute(sql.SQL("SELECT EXISTS (SELECT * FROM {input_table} FOR UPDATE SKIP LOCKED LIMIT 1)").format(
        input_table=input_table))
    return cursor.fetchone()[0]

get_data()
```

**Comment by majorgreys** [comment]
@mlennon-lumere I'll go ahead and close this issue but if you still need help on this please re-open the issue.
