### ISSUE TITLE
structlog integration (logs injection) is broken

### ISSUE THREAD

**Issue by oranav** [DataDog/dd-trace-py#8699]
### Summary of problem

When using the structlog integration, a new processor is being added to the **global processors list** every time `get_logger` is called. When `get_logger` is called multiple time, the tracer logs injection processor is injected again and again.

In addition, in case `structlog.configure` has been called after the logger has been created, but before it was bounded -- the trace injection won't work. This is because the global processors list is inspected upon binding time (it's lazy evaluated), not upon creation time.

```python3
In [1]: import structlog

In [2]: logger = structlog.get_logger()

In [3]: structlog.configure(processors=[])

In [4]: logger.bind()._processors
Out[4]: []
```

All in all, this makes the structlog integration not very usable, as a common use case is to create loggers at import time, and then to configure structlog at runtime during initialization -- making all the created loggers unpatched.

### Which version of dd-trace-py are you using?

2.6.5

### Which version of poetry are you using?

Poetry 1.8.2

### Which libraries and their versions are you using?

<details>
  <summary>`poetry show`</summary>

ddtrace                              2.6.5                            
structlog                            23.2.0
</details>

### How can we reproduce your problem?

Just call `get_logger` multiple times (with logs injection enabled), then inspect the processors:

```python3
In [1]: import structlog

In [2]: logger1 = structlog.get_logger()

In [3]: logger2 = structlog.get_logger()

In [4]: logger1.bind()._processors
Out[4]: 
[<function ddtrace.contrib.structlog.patch._tracer_injection(_, __, event_dict)>,
 <function ddtrace.contrib.structlog.patch._tracer_injection(_, __, event_dict)>,
 <function structlog.contextvars.merge_contextvars(logger: 'WrappedLogger', method_name: 'str', event_dict: 'EventDict') -> 'EventDict'>,
 <function structlog._log_levels.add_log_level(logger: 'logging.Logger', method_name: 'str', event_dict: 'EventDict') -> 'EventDict'>,
 <structlog.processors.StackInfoRenderer at 0x111236d40>,
 <function structlog.dev.set_exc_info(logger: 'WrappedLogger', method_name: 'str', event_dict: 'EventDict') -> 'EventDict'>,
 <structlog.processors.TimeStamper at 0x111243dc0>,
 <structlog.dev.ConsoleRenderer at 0x1102d8a50>]

In [5]: structlog.configure(processors=[])

In [6]: logger2.bind()._processors
Out[6]: []
```

### What is the result that you get?

`logger1` has multiple `_tracer_injection` processors; `logger2` has none.

### What is the result that you expected?

Both loggers should have exactly one `_tracer_injection` processor.

**Comment by emmettbutler** [comment]
Thank you for the clear report, @oranav. It looks like it will be straightforward for us to create a test case based on your replication code.
