### ISSUE TITLE
Celery integration

### ISSUE THREAD

**Issue by brettlangdon** [DataDog/dd-trace-py#87]
I just wanted to put this here as a place holder since I am currently working on an integration for `celery`.

If anyone is using `celery` and is interested in tracing any specific functions/features, please feel free to leave a comment. I am still trying to get a game plan together of what is worth tracing (tasks yes, but as far as the worker/consumer/producers/queues/etc TDB).

I am currently trying to take a "patch" approach with the integration, e.g.:

```python
from ddtrace.contrib.celery import patch_all; patch_all()
```

**Comment by jontonsoup** [comment]
@brettlangdon does this cover rabbitmq also?

**Comment by brettlangdon** [comment]
@jontonsoup no, this integration only covers tracing around task execution. So you can see when your code schedules a task with `celery.apply`/`celery.apply_sync`, and then get traces for when a task is executed by celery as `celery.run`.

There are some example screenshots in #135 that show `redis` tracing as well, this is because `redis` was patched as well. Those screenshots just show an example of what the `redis` tracing "inside" of the `celery` calls looks like.

**Comment by jontonsoup** [comment]
@brettlangdon makes sense -- thanks! Happy to help out with this if you need.
