### ISSUE TITLE
failed to decode _dd.p.dm: '1', 137 additional messages skipped

### ISSUE THREAD

**Issue by kevinchen-verkada** [DataDog/dd-trace-py#8749]
### Summary of problem
Seeing `failed to decode _dd.p.dm: '1', 137 additional messages skipped` after upgrading to `ddtrace==2.7.2`. Not sure if it is related, but we upgraded ddtrace because we started to use `openai==1.12.0`

### Which version of dd-trace-py are you using?
2.7.2

**Comment by emmettbutler** [comment]
Thank you for reporting this issue, @kevinchen-verkada. We'll look into it.

**Comment by emmettbutler** [comment]
@ZStriker19 do you think it's possible that this is related to any recent changes to the sampling logic?
