### ISSUE TITLE
Starlette tracing crashes with 0.32.0.post1

### ISSUE THREAD

**Issue by mfulgo** [DataDog/dd-trace-py#8823]
### Summary of problem
Enabling traces with Starlette [`0.32.0.post1`](https://pypi.org/project/starlette/0.32.0.post1/) raises the following error:
```
(snip...)/ddtrace/contrib/starlette/patch.py:50: in <module>
    _STARLETTE_VERSION = tuple(map(int, get_version().split(".")))
E   ValueError: invalid literal for int() with base 10: 'post1'
```
This is the latest Starlette dependency for FastAPI `0.108.0`.

### Which version of dd-trace-py are you using?
`2.7.5`

Looks like this was introduced in https://github.com/DataDog/dd-trace-py/pull/8614 and released in ddtrace `2.7.2`. ([compare](https://github.com/DataDog/dd-trace-py/compare/v2.7.1...v2.7.2))
It was also backported in https://github.com/DataDog/dd-trace-py/pull/8630 and released in ddtrace `2.6.7`. ([compare](https://github.com/DataDog/dd-trace-py/compare/v2.6.6...v2.6.7))

(This would also raise errors if Starlette decides to release any version that conforms to several of the other [valid python package versioning numbers](https://packaging.python.org/en/latest/discussions/versioning/), as they did for pre-releases `0.12.0b1` - `0.12.0b3`.)

**Comment by emmettbutler** [comment]
@mfulgo thank you for bringing this to our attention.

cc @zarirhamza
