### ISSUE TITLE
Kafka pathing crashes for ddtrace 2.7.6

### ISSUE THREAD

**Issue by PlugaruT** [DataDog/dd-trace-py#8846]
### Summary of problem
Pathing for `Consumer.consume` method crashing when the return value is an empty list
```
  File "/redacted/src/g/kafka/consumer.py", line 78, in consume_messages
    messages: list[Message] | None = self.consumer.consume(max_messages_per_batch, timeout)
  File "/redacted/.local/lib/python3.10/site-packages/ddtrace/contrib/kafka/patch.py", line 228, in traced_poll_or_consume
    _instrument_message(result, pin, start_ns, instance, err)
  File "/redacted/.local/lib/python3.10/site-packages/ddtrace/contrib/kafka/patch.py", line 237, in _instrument_message
    first_message = messages[0]
IndexError: list index out of range
```
Based on confluent_kafka [docs](https://docs.confluent.io/platform/7.5/clients/confluent-kafka-python/html/index.html#confluent_kafka.Consumer.consume), the method can return an empty list in case of timeouts and maybe other situations. 
The code that does the patching does not check if the list is empty and assumes that it will always return a list with messages.

### Which version of dd-trace-py are you using?
2.7.6

### Which version of pip are you using?
22.0.4

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
datadog==0.49.1
ddtrace==2.7.6
confluent-kafka==2.3.0
</details>

**Comment by PlugaruT** [comment]
See https://github.com/confluentinc/confluent-kafka-python/blob/master/src/confluent_kafka/src/Consumer.c#L1230

**Comment by emmettbutler** [comment]
Thank you for raising this, @PlugaruT. We'll fix it - in the meantime, please open a pull request fixing it if you're so inclined.

**Comment by PlugaruT** [comment]
@emmettbutler given that there is the PR with the fix open, can I hope for a new release cut in the next few days? Currently, this is the thing blocking us from using DSM. Thanks

**Comment by emmettbutler** [comment]
@PlugaruT Yes, we'll likely be able to get a 2.7 patch released with this fix included in the next few business days.
