### ISSUE TITLE
Hard to get django and logging integrations working together

### ISSUE THREAD

**Issue by carlosperello** [DataDog/dd-trace-py#888]
I tried to use the logging module together with Django so I can track log output with APM traces. I tried several combinations without success to get them working well.

- Using django app for django and `ddtrace-run` or logging's module patch method.
- Using `ddtrace-run` for both, django and logging module.
- Using ddtrace's patch method with `django=True` and `logging=True`

Only the third option worked, in any other case the logs had '0' as the trace_id and span_id. Based on previous issues I had on my side, I thought that it would be caused because I was doing the logging monkeypatching too late in the initialization, but it was not the case here, I did the import and the patch call directly at the beginning of manage.py file.

I didn't find a cause for this but with pdb I may have a clue, in case it helps to debug the issue. When initializing the django's ddtrace module, `ddtrace.contrib.django.conf.settings` is being created twice and on each case, the ddtrace.tracer instance was different so my guess is that django integration was using one instance and the logging one would be using the other. WARNING: this is just a guess, maybe I'm saying non sense as I don't know much this codebase.

Thanks.

**Comment by majorgreys** [comment]
We are currently working on a rewrite of the Django integration that should address this issue. Updates to come!

**Comment by marcosquiroga-nw** [comment]
Same here, any updates on this topic?

**Comment by Kyle-Verhoog** [comment]
Hey @marcosquiroga-nw, @carlosperello we have added documentation outlined here: https://ddtrace.readthedocs.io/en/stable/advanced_usage.html#logs-injection to help address setting up the trace-logs injection. 

Please let us know if after reading this that it's still difficult to get the integrations working together and we can re-open and improve!
