### ISSUE TITLE
Trace Id reported is not hex encoded like APM

### ISSUE THREAD

**Issue by jhirshman** [DataDog/dd-trace-py#8897]
### Summary of problem
when we use the datadog agent with APM, the trace id returned is a 128 bit number encoded as hex.
When we use the ddtrace library, the trace id is a 128 bit integer.

The function we're using to put trace ids into our logs is `get_log_correlation_context()`

In datadog, I can tell that the trace id is being correctly associated with the log.  But, it's not matching APM records.  I hypothesize because of the encoding difference between the hex and non-hex

### Which version of dd-trace-py are you using?
2.7.3

**Comment by jhirshman** [comment]
I contacted datadog support about this issue

They seemed to confirm the diagnosis here.

<img width="548" alt="image" src="https://github.com/DataDog/dd-trace-py/assets/876992/3b304d0c-2406-42a7-8ad8-231c86e13da0">

Rather than fixing this ourselves, which we could do by manually converting the trace id in python, I was hoping that this could be fixed in the library

**Comment by emmettbutler** [comment]
Thanks for the report, @jhirshman. This seems similar but maybe not exactly the same as https://github.com/DataDog/dd-trace-py/issues/7883.

cc @mabdinur

**Comment by jhirshman** [comment]
This has been fixed with the latest release of ddtrace (2.8.3)
see release notes: https://github.com/DataDog/dd-trace-py/releases/tag/v2.8.3
