### ISSUE TITLE
DD_KAFKA_PROPAGATION_ENABLED detached traces

### ISSUE THREAD

**Issue by philipbjorge** [DataDog/dd-trace-py#8967]
### Summary of problem

I've turned on the `DD_KAFKA_PROPAGATION_ENABLED` flag but my traces aren't being connected appropriately.

![CleanShot 2024-04-12 at 14 52 20](https://github.com/DataDog/dd-trace-py/assets/918891/7b87b7b6-468f-4f72-a284-d129e5abb3da)

![CleanShot 2024-04-12 at 14 52 46](https://github.com/DataDog/dd-trace-py/assets/918891/f218fe9b-7be3-490a-8e4f-b21b8cdcfdcd)

### Dev Notes

It almost looks like this PR regressed the functionality:
https://github.com/DataDog/dd-trace-py/pull/8511/files

**Before**

```
with pin.tracer.start_span(..., child_of=ctx):
  return message
```

**After**

```
try:
  return message
finally:
  with pin.tracer.start_span(..., child_of=ctx):
    pass
```

So I don't think any of the trace context gets propogated.

### Which version of dd-trace-py are you using?

2.8.0

### Which libraries and their versions are you using?

confluent-kafka 2.1.1

**Comment by emmettbutler** [comment]
@philipbjorge thanks for reporting this issue. I proposed a fix in #8983 and will see if I can put together a regression test.

**Comment by wconti27** [comment]
@philipbjorge having only taken a quick look so far, but I believe the gap between spans in the first screenshot in this case is not a bug. Instead, it represents the "time in queue" for the Kafka message before it was consumed.

**Comment by philipbjorge** [comment]
Thank you for taking a look! 

For reference, here's a better image of what I'm expecting:
![CleanShot 2024-04-15 at 08 40 30](https://github.com/DataDog/dd-trace-py/assets/918891/8c1ed79d-d3b7-461e-b075-bf513209c80f)

This is the same code path that the busted screenshots are from above. I achieved this by manually instrumenting our code with `tracer.context_provider.activate(Propagator.extract(dict(msg.headers())))` and `Propagator.inject(ctx, headers)`

**Comment by emmettbutler** [comment]
I think #8983 fixes this
