### ISSUE TITLE
[Feature] Support the DD_SERVICE_MAPPING environment variable

### ISSUE THREAD

**Issue by jcassee** [DataDog/dd-trace-py#897]
The Java tracer can rename services in traces using the DD_SERVICE_MAPPING environment variable. It would be nice to have the Python tracer support it too (or a similar mechanism).

**Comment by brettlangdon** [comment]
@jcassee thanks for the feature request.

How would you intend to use this feature in Python? Is there a service name you are currently unable to control the name of?

**Comment by jcassee** [comment]
Yes, we currently have a couple of Java, Python and Node applications that access a Postgres database. All of the Datadog trace libraries use a different name for the Postgres service:
* Java calls it "postgresql"
* Python calls it "postgres"
* Node calls it "<application>-postgres"

I would like to consolidate them.

In the Python application we use SQLAlchemy, and the only way to change to service name it to set `Pin.override(engine, service='NAME')` in code. I would not like to have to change the code in this way. (Also, we use flask-sqlalchemy so it is not obvious to me where to place it.)

**Comment by ottonello** [comment]
Just to add a use case here, we have a Django app which calls a postgres db 'defaultdb', and a Flask app which calls it 'postgres'. It'd be really handy to have everything under the same service.

**Comment by BastianM3** [comment]
Also interested in this. Dev teams have asked me quite a few times what the difference is between `postgres`, `defaultdb`...

**Comment by davesade** [comment]
We use Python and indeed, having resource called "postgres" in APM is misleading, as we run multiple databases and application. Having a control over the name or at least defaulting to $APP-postgres would be truly appreciated!

**Comment by pendolf** [comment]
Same in my team. One project example, we use django and multiple database connections

```python
DATABASES = {
    'default': env.db('POSTGRESQL_URL'),
    'locations-storage': env.db('LOCATIONS_DB_URL'),
}
```

```python
service_name = env.str('DD_SERVICE_NAME', default='core-api')
config.django['database_service_name_prefix'] = f'{service_name}-'
```

This is how trace looks like
![image](https://user-images.githubusercontent.com/598479/102324350-efcbcb00-3fab-11eb-8263-695e9ede7d29.png)

**Comment by davesade** [comment]
> Same in my team. One project example, we use django and multiple database connections
> 

Check #1887, maybe it helps you too?
