### ISSUE TITLE
ddtrace.readthedocs.io is stale

### ISSUE THREAD

**Issue by noelleleigh** [DataDog/dd-trace-py#9017]
### Summary of problem

The most recent build of [ddtrace.readthedocs.io](https://ddtrace.readthedocs.io/en/latest/) is for version [v2.6.2 on 2024-02-16](https://readthedocs.org/projects/ddtrace/builds/23460362/), but the most recent release of the package is [v2.8.1](https://github.com/DataDog/dd-trace-py/releases/tag/v2.8.1). Did the Read the Docs CI/CD process stop working?

**Comment by emmettbutler** [comment]
Yes, it looks like it did stop working. Thanks for bringing this to our attention, @noelleleigh.

**Comment by emmettbutler** [comment]
I created a new automation rule in [readthedocs admin](https://readthedocs.org/dashboard/ddtrace/rules/) (link requires admin access). I'll reopen this ticket if the next release doesn't trigger a documentation build.

**Comment by emmettbutler** [comment]
This still appears to be an issue. The latest version on readthedocs is 2.8.1, and the latest stable released version is 2.8.4.
