### ISSUE TITLE
Set service name for boto3/botocore from env var

### ISSUE THREAD

**Issue by HoneyryderChuck** [DataDog/dd-trace-py#9040]
### Summary of problem

Several other client libs support service name overrides from env var (`DD_AREDIS_SERVICE`, `DD_PSYCOPG_SERVICE`, `DD_HTTPX_SERVICE`), but there's no such env var support for overriding botocore service name (currently it's "aws.sqs", "aws.s3"...)

In fact, patching 

### Which version of dd-trace-py are you using?

I've searched on "latest" docs, and found nothing. But I'm using `boto3-1.33.13` and `botocore-1.33.13`.

### How can we reproduce your problem?

```python
import ddtrace
ddtrace.config.botocore["service_name"] = "bang"
ddtrace.patch(botocore=True)
# now try sending a message with SQS or smth..
```

### What is the result that you get?

service name was not overridden (still "aws.sqs").

### What is the result that you expected?

service name "bang".

**Comment by emmettbutler** [comment]
cc @tabgok

**Comment by joshverma** [comment]
Any update on this?

**Comment by quinna-h** [comment]
Hi @HoneyryderChuck ,

Thanks for submitting this issue! Could you provide more information as to why you want to override the service name for botocore? Generally the different botocore services have different functionality (between `aws.sqs` or `aws.s3`) so we haven't provided a setting for global override.

**Comment by HoneyryderChuck** [comment]
Most other integrations allow changing the service name. In the use case of managing multiple services, it makes it easier to narrow down which traces belong to which service.

**Comment by quinna-h** [comment]
Hi @HoneyryderChuck ,

Thanks for raising this issue! We created the fix [here](https://github.com/DataDog/dd-trace-py/pull/9856) as part of the [latest 2.10.0 release](https://github.com/DataDog/dd-trace-py/releases/tag/v2.10.0).
