### ISSUE TITLE
Scrolling for the left-side menu on the API docs is broken

### ISSUE THREAD

**Issue by goodspark** [DataDog/dd-trace-py#905]
Chromium, Ubuntu

Go to http://pypi.datadoghq.com/trace/docs/advanced_usage.html
Scroll up and down
If your browser window is short enough, you'll notice the left-side menu doesn't scroll with the page, leaving some parts inaccessible.

Video: [vokoscreen-2019-04-25_08-21-40.zip](https://github.com/DataDog/dd-trace-py/files/3117626/vokoscreen-2019-04-25_08-21-40.zip)

Since the API docs are generated from this repo, I figured I'd report the issue here.

**Comment by brettlangdon** [comment]
@goodspark thanks for catching this. We have fixed in #906 and our docs will update the next time we release (probably early next week).
