### ISSUE TITLE
Asyncio  - DATADOG_ENV is not read by tracer configure

### ISSUE THREAD

**Issue by coulix** [DataDog/dd-trace-py#909]
Using asyncio the env var `DATADOG_ENV` is not taken into account.

**Comment by paymog** [comment]
I'm seeing this with `gthread` workers with gunicorn

**Comment by majorgreys** [comment]
@coulix You will want to be using `DD_ENV`: http://pypi.datadoghq.com/trace/docs/configuration.html?highlight=dd_env

**Comment by majorgreys** [comment]
Also helpful to consult https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=kubernetes
