### ISSUE TITLE
Upgrading from v2.4.0 to v2.8.1 changes tracking from `trace.django.request` to `trace.django.middleware`

### ISSUE THREAD

**Issue by malthejorgensen** [DataDog/dd-trace-py#9092]
### Summary of problem
Upgrading from v2.4.0 to v2.8.1 changes tracking of requests from `trace.django.request` to `trace.django.middleware`.

**On version 2.4.0**
`trace.django.request` exists and tracks hits, duration and errors
`trace.django.middleware` doesn't exist

**On version 2.8.1**
`trace.django.request` doesn't exist
`trace.django.middleware` exists and tracks hits, duration but not errors

### Which version of dd-trace-py are you using?
Previously v2.4.0, now v2.8.1

### Which version of pip are you using?
pip v23.0.1

### Which libraries and their versions are you using?
django v3.2.8

### How can we reproduce your problem?
[TBD]

### What is the result that you get?
On version 2.4.0 request metrics lived under `trace.django.request`
In version 2.8.1 request metrics live under `trace.django.middleware` and error counts are not tracked in the default APM dashboard.

### What is the result that you expected?
This change is not documented in the changelog or the releases on Github, so a bit surprising. It broke our own dashboards.

**Comment by emmettbutler** [comment]
Interesting - thanks for flagging this, @malthejorgensen. It doesn't look to me like an intentional behavior change. We'll look into it.

cc @mabdinur

**Comment by malthejorgensen** [comment]
Hi @emmettbutler and @mabdinur 

I think this one is on our side. We're seeing some very strange behavior, it's not related to the version upgrade I think.

Hold off on the investigation, we'll try and get something more concrete for you.

**Comment by malthejorgensen** [comment]
Turns out `scoutapm` ([link](https://github.com/scoutapp/scout_apm_python)) was load-bearing in our Datadog setup.

This was completely unrelated to the version upgrade.

Apologies! Closing this issue.
