### ISSUE TITLE
asyncio task parenting broken

### ISSUE THREAD

**Issue by thehesiod** [DataDog/dd-trace-py#910]
I added the task parenting in https://github.com/DataDog/dd-trace-py/issues/247, however in a recent change it was broken because now the parent info is cleared out after the last span is removed from the context.  I added a fix for this here:
so in https://github.com/DataDog/dd-trace-py/pull/400/files#diff-1f4ab29acf614c9b2686031a425ee0f6R211

**Comment by Kyle-Verhoog** [comment]
This should be addressed by #1936
