### ISSUE TITLE
Tornado: Can we add request path as resource on execute and on_finish?

### ISSUE THREAD

**Issue by aonamrata** [DataDog/dd-trace-py#912]
Ref: https://github.com/DataDog/dd-trace-py/commit/d14d12909829427bddf74c3ab8ea6dfb827042fd

Can we add path as resource on execute and on_finish?
https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/tornado/handlers.py#L35-L39

At present all my endpoints use same handler but what I see in datadog empty name and multiple requests get merged in on single trace. 
![image](https://user-images.githubusercontent.com/1792005/56947105-c3024000-6b49-11e9-8ed0-9658818d5c32.png)

If not by default, can we add some settings to do that?

**Comment by jd** [comment]
Isn't the path stored as a tag usable in this case?

**Comment by aonamrata** [comment]
yes, but we have to go through each one of the list item to find the request that we want.

**Comment by brettlangdon** [comment]
@aonamrata the main problem with adding request URL as the resource name is the cardinality issues, e.g. `GET /users/123` and `GET /users/456`. It is better to keep these grouped together under a common resource, like `GET /users/:id`.

We can look into how we can handle this better in Tornado.

As well, if you enable trace search and analytics you'll be able to search on the url metadata and create graphs and find traces, etc matching your query.

https://docs.datadoghq.com/tracing/trace_search_and_analytics/?tab=python#pagetitle

**Comment by aonamrata** [comment]
hmm, ok let me try adding Environment Variable: DD_TRACE_ANALYTICS_ENABLED=true
Thanks.
