### ISSUE TITLE
The gRPC AIO server integration fails to set the gRPC status code for the span

### ISSUE THREAD

**Issue by lanttu** [DataDog/dd-trace-py#9308]
### Summary of problem

The gRPC AIO server integration fails to set the gRPC status code for the span.

### Which version of dd-trace-py are you using?

2.7.4

### Which libraries and their versions are you using?

grpcio "1.63.0"

### What is the result that you get?

gRPC AIO server span does not have status code tag.

### What is the result that you expected?

I'd expect the gRPC AIO server integration to include the status code in the span just like the client implementation does.

---

I think there a possibly two separate issues here. It seems like ddtrace [expects](https://github.com/DataDog/dd-trace-py/blob/main/ddtrace/contrib/grpc/aio_server_interceptor.py#L40-L41) `grpc.aio.ServicerContext.code()` to return integer, but at least recent gRPC versions return `grpc.StatusCode`.

The server integration seems to differ from client integration on tag name that is being used for the status code. Client interceptor uses constant `GRPC_STATUS_CODE_KEY` for tag name while server interceptor uses `ERROR_TYPE` tag name constant. Server integration does not attempt to include the status code for successful cases.

**Comment by emmettbutler** [comment]
Thank you for the report, @lanttu. We'll add it to our backlog of necessary fixes.

cc @mabdinur
