### ISSUE TITLE
Cannot override the `service_name` for the `requests` integration

### ISSUE THREAD

**Issue by Diaoul** [DataDog/dd-trace-py#9453]
### Summary of problem
Following the [documentation](https://ddtrace.readthedocs.io/en/stable/integrations.html#id154), I want to override the `service_name` for a particular `requests.Session` object.
However, it does not work, the service name remains the same (following the global config with split-per-domain).

Looking at the code I imagine there is no `Pin` associated with it but I'm not sure how to solve this (or if I should).

### Which version of dd-trace-py are you using?
`1.20.8`

### Which version of pip are you using?
Using `poetry`

### Which libraries and their versions are you using?
A lot, not sure it's relevant

### How can we reproduce your problem?
I guess by following your documentation like I did

### What is the result that you get?
I cannot override the `service_name`

### What is the result that you expected?
I can override the `service_name`

**Comment by emmettbutler** [comment]
Thank you for the report, @Diaoul. Even though you're using a pretty old version of the library, it seems to me that this behavior will persist in the current latest version. We'll look into it.

cc @mabdinur (let me know if there's someone else I should route integration issues to)

**Comment by quinna-h** [comment]
Hi @Diaoul ,

I reproduced the issue you described with a minimal example and was able to override the service name with `Pin` (below):

```
from ddtrace import tracer, config, Pin
from requests import Session

with tracer.trace("test-span", service='top-service'):
       session = Session() 
       Pin.override(session, service='service-name')

       session2 = Session()

      # Make a request using the sessions
      session.get('https://jsonplaceholder.typicode.com/todos/1')  # service name should be service-name
      session2.get('https://jsonplaceholder.typicode.com/todos/1') # service name should be requests

```

<img width="917" alt="Screenshot 2024-07-16 at 2 13 49 PM" src="https://github.com/user-attachments/assets/312d1faa-b2ff-4c07-8b6e-6d2172d7d3e7">

In the flame graph generated, the parent span 'test-span' has two child spans, one with the service name 'service-name' (using `Pin` override), and the other with the default service name 'requests'. 

Let us know if this matches the expected behavior, if not please follow up with more details!

**Comment by Diaoul** [comment]
Thanks! Trying to reformulate so I can make sure I understand correctly here:

1. You acknowledge that this snippet from [your documentation](https://ddtrace.readthedocs.io/en/stable/integrations.html#id154) is not working

```python
session = Session()
cfg = config.get_from(session)
cfg['service_name'] = 'auth-api'
```

2. You suggest a workaround with a `Pin.override`

Are you going do a fix that will make the documented snippet work? Or is your workaround the actual solution that we should use and you will update the docs accordingly?

**Comment by quinna-h** [comment]
Thanks for the follow-up! 

Using another minimal example with version `v1.20.8`, I replicated the code you have from the documentation:

```
from ddtrace import tracer, config
from requests import Session


def make_request():
   session = Session()
   session.get('https://jsonplaceholder.typicode.com/todos/1') # should generate span with default service name

   cfg = config.get_from(session)
   cfg['service_name'] = 'auth-api'
   cfg['distributed_tracing'] = False

   session.get('https://jsonplaceholder.typicode.com/todos/1') # should generate span with new service name

make_request()
```
I was able to generate the following spans, the first with the default service name `requests`, and the second with the new service name `auth-api`, as expected. 

<img width="1053" alt="Screenshot 2024-07-17 at 11 19 35 AM" src="https://github.com/user-attachments/assets/89870b89-4a59-43d8-99f8-29a61ad9917d">


It looks like we need further clarification, could you please provide more information?

**Comment by Diaoul** [comment]
Does your latest snippet work within an existing parent trace? This is the only difference I see with you minimal example and my production code.

If yes, then it may be some internals on my side messing with the service override, I'll take a closer look.

**Comment by Diaoul** [comment]
Thanks for checking so in depth with me!
I'll close this for now and re-open if I can find another contributing factor that is not due to our local setup.

I'll keep you posted either way.
