### ISSUE TITLE
mypy stub files

### ISSUE THREAD

**Issue by jasonkuhrt** [DataDog/dd-trace-py#951]
mypy throws an error when ddtrace is in use:

![image](https://user-images.githubusercontent.com/284476/58525411-a7ff0c00-8199-11e9-8bcb-770aeeeda3fb.png)

It would be nice if this library could ship with stub files or be put on https://github.com/python/typeshed. I'm not sure how to do that yet but maybe someone here is.

More info from mypy side here https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports

**Comment by brettlangdon** [comment]
@jasonkuhrt thank you for opening the request, this has been on my personal todo list for awhile.

I also do not know how to do it, but would love to try and find the time to do this.

**Comment by jasonkuhrt** [comment]
@brettlangdon fwiw this is what we did locally in our project to satisfy mypy (we're only stubbing the parts we use, not complete, of course)

![image](https://user-images.githubusercontent.com/284476/58559945-24253e00-81f2-11e9-96a4-90ac9ea762e4.png)

**Comment by brettlangdon** [comment]
Nice! Thanks for sharing.

**Comment by meshy** [comment]
I ended up creating a compat module so that I could use `ddtrace.tracer.wrap` without getting warnings:

```python
from typing import Any, Callable, TypeVar

import ddtrace

# This allows us to use a type annotated ddtrace.tracer.wrap.
# First, we assign the name "trace" to ddtrace.tracer.wrap.
# Then, we assign a type:
# "trace" is a callable that takes arguments, and returns a function.
# That function takes another function as an argument and returns it.
F = TypeVar("F", bound=Callable[..., Any])
trace: Callable[..., Callable[[F], F]] = ddtrace.tracer.wrap
```
