### ISSUE TITLE
Feature request: pyodbc support

### ISSUE THREAD

**Issue by kitsuyui** [DataDog/dd-trace-py#953]
Is there any plan to support pyodbc?
pyodbc allows to connect various databases which supports ODBC (Google BigQuery, Hive, MySQL, PostgreSQL, Microsoft Access, Excel, SQL Server, ...). https://github.com/mkleehammer/pyodbc/wiki/Connecting-to-databases

If it was implemented, DataDog can be applied in many use-cases.

**Comment by thehesiod** [comment]
I may get to this, we need it too and I've already written the asyncpg backend: https://github.com/DataDog/dd-trace-py/pull/394

**Comment by thehesiod** [comment]
related to this is aioodbc which uses pyodbc, so aioodbc may get away with just a pyodbc backend
