### ISSUE TITLE
TypeError: unhashable type: 'dict' thrown from cache

### ISSUE THREAD

**Issue by AndrewGuenther** [DataDog/dd-trace-py#9533]
### Summary of problem
Very rarely, we see requests fail with the following trace:
```
  File "/usr/local/lib/python3.11/site-packages/ddtrace/internal/utils/cache.py", line 81, in cached_f
    return cache.get(key, f)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ddtrace/internal/utils/cache.py", line 61, in get
    for h in sorted(self, key=lambda h: self[h][1])[: self.maxsize >> 1]:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ddtrace/internal/utils/cache.py", line 61, in <lambda>
    for h in sorted(self, key=lambda h: self[h][1])[: self.maxsize >> 1]:
                                        ~~~~^^^
TypeError: unhashable type: 'dict'
```

This comes from varying cache consumers, what's above is the common bottom of the trace.

### Which version of dd-trace-py are you using?
2.8.0

### Which version of pip are you using?
23.1.2

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
  
</details>

### How can we reproduce your problem?
Issue is sporadic and rare, haven't pinned down a repro case

### What is the result that you get?
See summary

### What is the result that you expected?
No exception thrown

**Comment by emmettbutler** [comment]
Thanks for the issue report, @AndrewGuenther. It might be helpful to see a bit more of the traceback, possibly one or two complete examples illustrating the various cache consumers that can trigger this crash.
