### ISSUE TITLE
Add support for faststream

### ISSUE THREAD

**Issue by florianmutter** [DataDog/dd-trace-py#9594]
Add support for https://faststream.airt.ai/latest/ (https://github.com/airtai/faststream)

It's an open-source framework for building asynchronous web services that interact with event streams. It has >2k stars on github and therefor fairly popular.

**Comment by emmettbutler** [comment]
Thanks @florianmutter for bringing this to our attention. We'll add faststream to our backlog of feature requests.

cc @mabdinur (let me know if someone else would be a more appropriate recipient for this category of ticket)

**Comment by smartinellimarco** [comment]
Can we reopen this issue?
