### ISSUE TITLE
Type-checking rough-edges in LLM Observability

### ISSUE THREAD

**Issue by bheilbrun** [DataDog/dd-trace-py#9600]
### Summary of problem

I ran across two type-checking issues that could maybe use some polish.

**`LLMObs.llm` et al. return `Optional[Span]`**

By returning `Span | None`, type-checkers complain about this example (taking from the docs),

```python
from ddtrace.llmobs import LLMObs

def process_message():
    with LLMObs.workflow() as span:
        ... # user application logic
    return
```

Pylance complains, `Object of type "None" cannot be used with "with"`. MyPy throws a similar error, `Item "None" of "Span | None" has no attribute "__enter__"`.

**`llmobs.utils.Documents` declares conflicting expectations**

`Documents` takes an arg `documents` of type, `Union[List[Dict[str, str]], Dict[str, str], str]`. In short, `dict[str,str]`.

However, the initializer's impl has this assertion,

```python
  if document_score:
      if not isinstance(document_score, (int, float)):
          raise TypeError("document score must be an integer or float.")
```

So, a type-checker complains if you call `Documents([{score: 1.0}])` but the implementation complains if you call `Documents([{score: "1.0"}])`.

### Which version of dd-trace-py are you using?

2.9.1 (latest release as of writing)

### How can we reproduce your problem?

Hopefully just visually spot-checking is sufficient. VSCode's Pylance or stand-alone MyPy will complain as well. Let me know if you need more specifics.

Thanks!

**Comment by emmettbutler** [comment]
Thanks for pointing this out, @bheilbrun. It looks like the CI's `hatch run lint:typing` check doesn't catch either of these. We'll fix it.

**Comment by bheilbrun** [comment]
Ah @Yun-Kim thanks for the docs typing fix. There was one other thing around returning `Optional[Span]`. Not sure if that could be looked at as well. Thanks.

**Comment by Yun-Kim** [comment]
Hi @bheilbrun, that was already addressed in https://github.com/DataDog/dd-trace-py/pull/9454 and should be included in the next ddtrace release (ETA is early july). Please let us know if you still run into this typing issue after upgrading!
