### ISSUE TITLE
Add admission controller to documentation

### ISSUE THREAD

**Issue by florianmutter** [DataDog/dd-trace-py#9606]
A lot of time the documentation says what to do if you use `ddtrace-run`. It would help if it would mention somewhere if using the admission controller means you are using `ddtrace-run` or not.

**Comment by emmettbutler** [comment]
Hi @florianmutter, and thanks for pointing this out. The documentation [here](https://github.com/DataDog/dd-trace-py/blob/09b537d2857de00aae9d31792a2a001dcb7825b6/lib-injection/README.md#L29) provides the piece of information you're looking for, albeit not in a very clear way.

What it means is that the admission controller and ddtrace-run use the same entrypoint and are not intended to have any meaningful differences.

Are there any specific bits of documentation that mention "if you use ddtrace-run..." that you think would benefit from clarification along these lines?

**Comment by florianmutter** [comment]
Thank you very much. This is already very helpful. I did not know this documentation and did only look at this page https://ddtrace.readthedocs.io/en/stable/installation_quickstart.html and could not see any mention of kubernets, adminssion or library injection.

It says for example:
> When ddtrace-run cannot be used, a similar start-up behavior can be achieved with the import of ddtrace.auto.
But to me it was not clear if you are supposed to use ddtrace.auto or not if you use the admission controller.

**Comment by emmettbutler** [comment]
@florianmutter glad it's been helpful so far. Hopefully https://github.com/DataDog/dd-trace-py/pull/9681 addresses your questions more directly.
