### ISSUE TITLE
celery producer stop trace reporting after celery update

### ISSUE THREAD

**Issue by barraquito** [DataDog/dd-trace-py#963]
We have updated this morning our Celery installation on production, and just after it we stop to receive `celery-producer` traces in our Datadog. These had been the changes in our `requirements.txt` file:

```
-amqp==1.4.9
+amqp==2.5.0
-billiard==3.3.0.23
+billiard==3.6.0.0
-celery==3.1.25
+celery==4.3.0
-kombu==3.0.37
+kombu==4.6.0
-redis==2.10.6
+redis==3.2.1
```

Also we have made a couple of changes related to Celery config for the migration. In `celery.py`, where celery is patched:

```
-patch(celery=True)
+patch(celery=True, redis=True, kombu=True)
```

In `settings.py`:

```
+# Celery 4 migration
+BROKER_TRANSPORT_OPTIONS = {
+    'fanout_patterns': True,
+    'fanout_prefix': True,
+}
+CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']
+
```
I tried to update `ddtrace` to the latest version (`0.26.0` we were using `0.20.2` before), but the update hasn't changed anything. Also I've tried to force a producer name using `ddtrace` config object, but also hasn't made any difference. Also checked previous bugs and information on the net but I couldn't find any hint about this behavior. Workers are reporting fine, as far as I see.

`gunicorn` is run with `ddtrace-run`.

Does it make any sense to any of you?

**Comment by majorgreys** [comment]
@barraquito I'm sorry it's taken so long for us to follow-up on this issue. Is this still an issue, either 0.26.0 or the current stable release?

**Comment by Kyle-Verhoog** [comment]
@barraquito please let us know if this is still an issue and we'll re-open and take a look!
