### ISSUE TITLE
[Django + uwsgi] DATADOG_TRACE settings never loaded

### ISSUE THREAD

**Issue by sazlin** [DataDog/dd-trace-py#986]
I'm trying to use dd-trace-py to hook up a Django 1.8 webapp w/ Datadog's APM feature. I've followed the directions [here](http://pypi.datadoghq.com/trace/docs/web_integrations.html#django) for configuring dd-trace-py with Django for APM but those instructions haven't worked consistently across the different ways we run our Django app. Specifically, APM does not work when we run Django with uwsgi, but things seem ok when we run a Django shell and experiment with tracing manually. 

Relevant parts of our stack:
- uwsgi 2.0.13.1
- Django==1.8.18
- django-configurations==1.0
- ddtrace==0.26.0

Our `DATADOG_TRACE` settings and some relevant settings:
```
    DATADOG_TRACE = {
        'DEFAULT_SERVICE': 'webapp',
        'TAGS': {'env': 'integration'},
        'DEFAULT_DATABASE_PREFIX': 'webapp-db',
        'DEFAULT_CACHE_SERVICE': 'webapp-cache',
        'ENABLED': True,
        'ANALYTICS_ENABLED': True,
        'AUTO_INSTRUMENT': True,
        'INSTRUMENT_TEMPLATE': True,
        'INSTRUMENT_DATABASE': True,
        'INSTRUMENT_CACHE': True
    }
    DEBUG = True  # We're testing APM in an integration environment where we want this
    INSTALLED_APPS = [
        'ddtrace.contrib.django',
        ...
    ]
```

More:
I've been debugging for a few days and can summarize as follows: the `DATADOG_TRACE` setting in our Django settings is defined correctly but is almost never (except for in a shell) being used to configure the global tracer that is used by default (`ddtrace.trace`). Let's go deeper; the `ddtrace.contrib.django.apps.TracerConfig` app **is** being installed and its `ready` method **is** being called. That method configures the global tracer using the `ddtrace.contrib.django.conf.settings` object, which is an instance of `ddtrace.contrib.django.conf.DatadogSettings`. The `ddtrace.contrib.django.conf.settings` object appears to be created on import of the `ddtrace.contrib.django.conf` module with this line:
`settings = DatadogSettings(None, DEFAULTS, IMPORT_STRINGS)`

The first argument of `None` causes the settings object to initially not include "user settings" and to use default values instead. The intent from the code appears to be that the `settings` object will initially be configured with defaults and then later will be assigned to a new `DatadogSettings` object that was created using the user settings in the `DATADOG_TRACE` Django setting. That's what I glean from here:
```
def reload_settings(*args, **kwargs):
    """
    Triggers a reload when Django emits the reloading signal
    """
    global settings
    setting, value = kwargs['setting'], kwargs['value']
    if setting == 'DATADOG_TRACE':
        log.info("reload_settings: %s", value)
        settings = DatadogSettings(value, DEFAULTS, IMPORT_STRINGS)
```

However, it's not clear to me how this code is ever called. What Django signal is supposed to trigger this function? How is this function registered to handle that signal? As far as I can tell, this function is never called.

And, even if `reload_settings` is eventually called somewhere, what ensures that `ddtrace.contrib.django.conf.settings` is assigned to the new `DatadogSettings` instance **_before_** `ddtrace.contrib.django.apps` imports `ddtrace.contrib.django.conf.settings`, which is necessary to ensure that `ddtrace.contrib.django.apps.TracerConfig.ready` will use the correct `DatadogSettings` instance when `ready` is called? That seems critical if `TracerConfig.ready` is to honor the user's settings in `DATADOG_TRACE`.

So, because `DatadogSettings` is never constructed with our actual Django settings, the reason our APM doesn't work is, primarily, due to this bit of code in `DatadogSettings`:
```
    @property
    def user_settings(self):
        if not hasattr(self, '_user_settings'):
            self._user_settings = getattr(django_settings, 'DATADOG_TRACE', {})

        # TODO[manu]: prevents docs import errors; provide a better implementation
        if 'ENABLED' not in self._user_settings:
            self._user_settings['ENABLED'] = not django_settings.DEBUG
```
Because `self._user_settings` is set to `{}`, and because `django_settings.DEBUG` seems to always return True (again, not from our Django settings), the `user_settings['ENABLED']` will be set to False, which is blocking APM across the app. This is why APM is ultimately not working.

**If I comment out the last two lines of that snippet, then APM does work** (because the global tracer is enabled by default), but of course the other settings like our service name and our env tag aren't used, which is still undesirable.

Further, if I abandon trying to use Django settings altogether and switch to using dd-trace-py and environment variables, then that can help me setup tags and other ddtrace settings, but the ENABLED setting will be forever False because of those two lines. So I can't just workaround this by using env vars if I also want to use the Django-specific patching in `ddtrace.contrib.django` via the `TracerConfig` Django app.

I suspect that import order is a critical factor here. For some reason, import order for running the `shell` management command works ok, but the import order when uwsgi spins up processes is different and fails to configure correctly.

So am I missing something or is there a bug here that needs addressing?

Oh yeah, when looking at other Github issues, I noticed that one suggested workaround for another issue with uwsgi and ddtrace was to try running things with `lazy-apps=true`. I tried that and uwsgi was not happy. Worker processes took too long to start up and were harikaried before they could finish starting up. I'm not inclined to risk such a config change just for ddtrace if we can avoid it.

**Comment by sazlin** [comment]
I was able to workaround this issue for now by creating a child Django App of `TracerConfig` that overrides the `ready` method to first reload settings and then configure the global tracer. I then add the custom app to our `INSTALLED_APPS` instead of the original `TracerConfig` app.

```
from ddtrace.contrib.django import apps, conf


class OUTracerConfig(apps.TracerConfig):
    """Custom Django app for doing Datadog APM that works around this bug"""
    name = 'ou_django_common.apm.django_app'
    label = 'ou_datadog_django'

    def ready(self):
        from django.conf import settings  # Not sure the function-level import is necessary
        conf.reload_settings(setting='DATADOG_TRACE', value=settings.DATADOG_TRACE)
        apps.settings = conf.settings
        super(OUTracerConfig, self).ready()  # This will configure the global tracer using the reloaded settings
```

Anyone see any downsides to this?

**Comment by brettlangdon** [comment]
@sazlin sorry for the long delay responding here, most of us were out for long weekend due to the holiday.

I am sorry you are having issues getting Django setup, these configuration issues are things we've seen a few times in the past and 👍 for the level of details provided in your report, this is awesome.

From your example work around, I don't see anything in particular that stands out as a downside, as long as it works then it seems like a good workaround for now.

For some transparency, we are going to have some discussions this week about the current state of our Django integration. It is one of our older integrations, a popular one, and one that we do see support cases like this from. We need to figure out if we should try to resolve your specific issue or attack the Django integration as a whole. I think given that you did find a workaround for right now, it buys us a little time to maybe think about Django on the whole and take the time to schedule the work to upgrade it a bit (🤞)

**Comment by tkrempser** [comment]
@brettlangdon Any news?

**Comment by brettlangdon** [comment]
@sazlin and @tkrempser we have recently released a big update to our Django integration in `ddtrace==0.34.0`, would you both be willing to give that a try and let us know if this issue still exists?

**Comment by majorgreys** [comment]
@tkrempser We had deprecated configuration of ddtrace by way of the Django settings module with v0.34.0 and it will be removed in v0.51.0. Please upgrade and migrate to the environment variables for configuring the tracer with your Django application.
