### ISSUE TITLE
django instrument_middleware not working but others are

### ISSUE THREAD

**Issue by ellisonleao** [DataDog/dd-trace-py#9919]
### Summary of problem

`ddtrace.config.django` configs are working apart from `instrument_middleware` one

### Which version of dd-trace-py are you using?

2.9.3

### Which version of pip are you using?

uv-pip 0.2.13

### Which libraries and their versions are you using?

```
anyio==4.4.0
asgiref==3.6.0
async-timeout==4.0.3
attrs==22.2.0
bytecode==0.14.1
cattrs==22.2.0
cerbos==0.7.1
certifi==2022.12.7
cffi==1.15.1
cfgv==3.4.0
charset-normalizer==3.1.0
coverage==6.5.0
cryptography==40.0.1
dataclasses-json==0.6.7
datadog==0.32.0
ddsketch==3.0.1
ddtrace==2.9.3
decorator==5.1.1
deprecated==1.2.14
distlib==0.3.8
dj-database-url==2.2.0
django==4.2.14
django-admin-rangefilter==0.13.0
django-cors-headers==4.4.0
django-db-geventpool==4.0.6
django-redis==5.4.0
django-waffle==4.1.0
django-watchman==1.3.0
djangorestframework==3.15.2
docutils==0.19
drf-spectacular==0.27.2
envier==0.5.2
exceptiongroup==1.1.1
factory-boy==3.3.0
faker==18.4.0
fancycompleter==0.9.1
filelock==3.15.4
flake8==7.1.0
freezegun==1.5.1
geographiclib==1.52
geohash2==1.1
geopin==1.16.0
geopy==2.1.0
gevent==24.2.1
gprof2dot==2022.7.29
greenlet==3.0.3
gunicorn==22.0.0
h11==0.14.0
h2==4.1.0
hiredis==2.2.2
hpack==4.0.0
httpcore==1.0.5
httpx==0.27.0
hyperframe==6.0.1
identify==2.6.0
idna==3.4
importlib-metadata==7.1.0
inflection==0.5.1
iniconfig==2.0.0
iso3166==1.0.1
josepy==1.13.0
jsonschema==4.17.3
librato-metrics==3.0.1
loadlog==0.7.0
loadsmart-dj==2.1.1
loadsmart-metrics==1.0.5
marshmallow==3.21.3
mccabe==0.7.0
metaphone==0.6
mozilla-django-oidc==4.0.1
mypy-extensions==1.0.0
nodeenv==1.9.1
opentelemetry-api==1.25.0
packaging==23.0
pdbpp==0.10.3
platformdirs==4.2.2
pluggy==1.5.0
pre-commit==3.7.1
protobuf==4.22.1
psycopg==3.2.1
pycodestyle==2.12.0
pycparser==2.21
pyflakes==3.2.0
pygments==2.15.0
pyjwt==2.8.0
pymiler==2.3.2
pyopenssl==23.1.1
pyrepl==0.9.0
pyrsistent==0.19.3
pytest==8.2.2
pytest-cov==5.0.0
pytest-django==4.8.0
pytest-mock==3.14.0
pytest-profiling==1.7.0
python-dateutil==2.8.2
python-json-logger==2.0.7
pytz==2024.1
pyyaml==6.0
redis==5.0.7
requests==2.28.2
requests-toolbelt==1.0.0
responses==0.23.1
sentry-sdk==2.9.0
setuptools==71.1.0
six==1.16.0
sniffio==1.3.1
sqlparse==0.4.3
statsd==3.2.1
structlog==23.1.0
tenacity==8.2.2
tomli==2.0.1
types-pyyaml==6.0.12.20240311
typing-extensions==4.5.0
typing-inspect==0.9.0
uritemplate==4.1.1
urllib3==1.26.15
virtualenv==20.26.3
whitenoise==6.7.0
wmctrl==0.4
wrapt==1.16.0
xmltodict==0.13.0
zipp==3.19.2
zope-event==4.6
zope-interface==6.0
```

### How can we reproduce your problem?

1. put the following configs in your project django settings.py file

```python
from ddtrace import config as ddconfig

ddconfig.django["cache_service_name"] = "test-cache"
ddconfig.django["database_service_name"] = "test-database" 
ddconfig.django["instrument_databases"] = True
ddconfig.django["instrument_middleware"] = False
ddconfig.django["service_name"] = "test-service"
```

2. Run your project with ddtrace-run

```bash
$ ddtrace-run python manage.py runserver
```

### What is the result that you get?

I can see the changes on following configs
- cache_service_name
- database_service_name
- instrument-databases
- service_name

but `instrument_middleware` is not being respected (trace image below)

![image](https://github.com/user-attachments/assets/732e8669-d7e9-4c81-926c-97fbfe71cd62)

### What is the result that you expected?

- for `instrument_middleware` setting to be respected

P.S: I can confirm that using `DD_DJANGO_INSTRUMENT_MIDDLEWARE` works and I saw that the docs are showing that the configs directly in the code will not work if you run your service using `ddtrace-run` but it is very confusing because some of the custom settings are working and this one is not. Can you clarify exactly how they should work? 

Issues References:
- https://github.com/DataDog/dd-trace-py/issues/3816
- https://github.com/DataDog/dd-trace-py/pull/1384

**Comment by emmettbutler** [comment]
Thanks for reporting this, @ellisonleao. We'll look into it.

cc @mabdinur

**Comment by matt-webshare** [comment]
reopen

We're still seeing this bug.

**Comment by folkvir** [comment]
I can also confirm the problem. Using the `ddtrace.config` object does not work at all.
For us with ddtrace latest (3.16.0) the only working thing is `os.environ["DD_DJANGO_INSTRUMENT_MIDDLEWARE"] = "0"` instead of `config.django.instrument_middleware = False`. This is set before `patch_all` and during a django app initialization, see the example.

```python
from django.apps import AppConfig

class MyAppConfig(AppConfig):
    name = "something"
    label = "something"
    verbose_name = "Something"

    def ready(self):
        from ddtrace import config, patch_all

        # not working
        config.django.instrument_middleware = False
        config.django["instrument_middleware"] = False
        
        # working
        import os
        os.environ["DD_DJANGO_INSTRUMENT_MIDDLEWARE"] = "0"

        patch_all()
```

Edit: We also use `ddtrace-run` in front of our application command.
