### ISSUE TITLE
What the size needed for the /tmp folder ?

### ISSUE THREAD

**Issue by thomasschaller1** [DataDog/dd-trace-py#9983]
### Summary of problem
Since this morning (and version 2.10.1), ddtrace_run need access to the tmp folder (for the `FileQueue` [here](https://github.com/DataDog/dd-trace-py/blob/main/ddtrace/settings/config.py#L448)) . Do you have some estimates about what would be the size used by ddtrace_run for this tmp dir?
### Which version of dd-trace-py are you using?
2.10.1

**Comment by emmettbutler** [comment]
@christophe-papazian might be able to provide a reasonable estimate.

**Comment by christophe-papazian** [comment]
As you can see, append operations stop as long as the temporary file is larger that 8192 bytes. So it should not go beyond that.
