### ISSUE TITLE
ci_visibility: unittest integration not working with Django's manage.py in ddtrace==2.9.2

### ISSUE THREAD

**Issue by romainkomorndatadog** [DataDog/dd-trace-py#9985]
### Summary of problem

Support for Test Visibility using Django's `manage.py` script is not sending results to Datadog's backend. 

### Which version of dd-trace-py are you using?

`2.9.2`

### Which version of pip are you using?

`23.0.1`

### Which libraries and their versions are you using?

Python `3.10.12`

<details>
  <summary>pip freeze</summary>

```
aniso8601==9.0.1
asgiref==3.8.1
async-timeout==4.0.3
attrs==23.2.0
Babel==2.15.0
bytecode==0.15.1
cattrs==23.2.3
certifi==2024.7.4
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
cryptography==43.0.0
ddsketch==3.0.1
ddtrace==2.9.2
defusedxml==0.8.0rc2
Deprecated==1.2.14
Django==5.0.7
django-cors-headers==4.4.0
django-debug-toolbar==4.3.0
django-filter==24.2
django-graphiql-debug-toolbar==0.2.0
django-htmx==1.18.0
django-js-asset==2.2.0
django-mptt==0.16.0
django-pglocks==1.0.4
django-prometheus==2.3.1
django-redis==5.4.0
django-rich==1.9.0
django-rq==2.10.2
django-tables2==2.7.0
django-taggit==5.0.1
django-timezone-field==7.0
djangorestframework==3.15.2
drf-spectacular==0.27.2
drf-spectacular-sidecar==2024.7.1
envier==0.5.2
exceptiongroup==1.2.2
feedparser==6.0.11
ghp-import==2.1.0
graphene==3.3
graphene-django==3.2.2
graphql-core==3.2.3
graphql-relay==3.2.0
gunicorn==22.0.0
idna==3.7
importlib_metadata==8.0.0
inflection==0.5.1
Jinja2==3.1.4
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
Markdown==3.6
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mdurl==0.1.2
mergedeep==1.3.4
mkdocs==1.6.0
mkdocs-autorefs==1.0.1
mkdocs-get-deps==0.2.0
mkdocs-material==9.5.30
mkdocs-material-extensions==1.3.1
mkdocstrings==0.25.2
mkdocstrings-python-legacy==0.2.3
netaddr==1.3.0
nh3==0.2.18
oauthlib==3.2.2
opentelemetry-api==1.26.0
packaging==24.1
paginate==0.5.6
pathspec==0.12.1
pillow==10.4.0
platformdirs==4.2.2
prometheus_client==0.20.0
promise==2.3
protobuf==5.27.2
psycopg==3.2.1
psycopg-c==3.2.1
psycopg-pool==3.2.2
pycparser==2.22
Pygments==2.18.0
PyJWT==2.8.0
pymdown-extensions==10.9
python-dateutil==2.9.0.post0
python3-openid==3.2.0
pytkdocs==0.16.1
PyYAML==6.0.1
pyyaml_env_tag==0.1
redis==5.0.7
referencing==0.35.1
regex==2024.7.24
requests==2.32.3
requests-oauthlib==2.0.0
rich==13.7.1
rpds-py==0.19.1
rq==1.16.2
sgmllib3k==1.0.0
six==1.16.0
social-auth-app-django==5.4.2
social-auth-core==4.5.4
sqlparse==0.5.1
strawberry-graphql==0.237.2
strawberry-graphql-django==0.47.1
svgwrite==1.4.3
tablib==3.6.1
text-unidecode==1.3
typing_extensions==4.12.2
tzdata==2024.1
uritemplate==4.1.1
urllib3==2.2.2
watchdog==4.0.1
wrapt==1.16.0
xmltodict==0.13.0
zipp==3.19.2
```

</details>

### How can we reproduce your problem?

Using a checkout of Netbox at `f949aa334ba0dec55ec7524d11be3798cd47356e`, along with dockerized Postgres and Redis images:

```
DD_PATCH_MODULES=unittest:true DD_API_KEY=<your_api_key> DD_CIVISIBILITY_AGENTLESS_ENABLED=1 DD_SITE=<your_dd_site> DD_TRACE_DEBUG=1 NETBOX_CONFIGURATION=netbox.configuration_testing ddtrace-run python ./manage.py test
```

This appears to also happen using EVP proxy mode (with a Datadog agent configured and without setting an API key or  `DD_CIVISIBILITY_AGENTLESS_ENABLED`.

### What is the result that you get?

No results in the backend. `DD_TRACE_DEBUG` does not show the expected span creation.

### What is the result that you expected?

Spans being created and results showing up in backend. 

#### Unittest integration itself works in the Django repo

Tests against the Django repo (which uses `unittest` for tests) work and properly populate results as expected.

#### Unittest integration invoked directly with python -m unittest works 

eg: a very simple single-file test with unittest invoked as follows works:
```
DD_TRACE_DEBUG=1 ddtrace-run python -m unittest
```

**Comment by robotmlg** [comment]
Thank you Romain for investigating this following my report in the Datadog slack.

Important detail: I looked back through our GitHub PRs, and this does appear to have broken in dd-trace-py 2.9.2.  I have PRs with datadog report comments from before upgrading from 2.9.1 to 2.9.2, and then no PRs with datadog reports after that upgrade.

**Comment by romainkomorndatadog** [comment]
@robotmlg , oh, great, thanks for that extra detail. I'm sure that'll come in handy. :)

**Comment by romainkomorndatadog** [comment]
@robotmlg , I was mistaken in saying (on Slack) that I was able to reproduce the issue locally. I am getting results using tests from Netbox's Django project (on a fork of https://github.com/romainkomorndatadog/test-environment-netbox ), with `ddtrace==2.9.2` installed.

eg: running tests with:
```shell
% DD_API_KEY=<my_api_key> DD_CIVISIBILITY_AGENTLESS_ENABLED=1 DD_TRACE_DEBUG=1 NETBOX_CONFIGURATION=netbox.configuration_testing ddtrace-run python ./manage.py test
```

Something's interfering with our debug logs, so I didn't see our typical messages about spans being finished, and I wasn't patient enough when looking at our backend, but I am in fact seeing results from running tests locally:
![image](https://github.com/user-attachments/assets/62e1030b-407d-4527-befb-61f68204a064)

And just to verify that I do have the right `ddtrace` installed:
```
% pip show ddtrace
Name: ddtrace
Version: 2.9.2
Summary: Datadog APM client library
Home-page:
Author:
Author-email: "Datadog, Inc." <dev@datadoghq.com>
License: LICENSE.BSD3
Location: /Users/romain.komorn/.pyenv/versions/3.12.3/envs/netbox-ddtrace-2.9.2-py3.12.3/lib/python3.12/site-packages
Requires: attrs, bytecode, cattrs, ddsketch, envier, opentelemetry-api, protobuf, setuptools, six, typing-extensions, xmltodict
Required-by:
```
and
```
% python --version
Python 3.12.3
```

I can't think of an obvious reason why GitHub Actions would behave differently, but let me see if I can also repro something there.

**Comment by romainkomorndatadog** [comment]
Looks like GHA also works:
I ran [a job](https://github.com/romainkomorndatadog/test-environment-netbox/actions/runs/10177807172/job/28150606347) based on [small changes](https://github.com/netbox-community/netbox/compare/develop...romainkomorndatadog:test-environment-netbox:enable_gha_ddtrace) to add `ddtrace` and run tests with `ddtrace-run` , which
produced these results:
![image](https://github.com/user-attachments/assets/011d49fa-6ce7-4244-ad02-92072128fbdf)

So I don't think this GH issue needs to stay open much longer.

**Comment by romainkomorndatadog** [comment]
I'm going to close this. If I do find evidence of a broader issue, I'll reopen it (or more likely create another, properly scoped issue).

**Comment by romainkomorndatadog** [comment]
I've had another report via our support channels of missing results from Django (also with `2.9.2`) but still haven't been able to reproduce the issue, so I'm leaving this issue closed for now.
